### ISSUE TITLE
UTF-8 encoding/deconding/testing

### ISSUE THREAD

**Issue by Iwan-Zotow** [nlohmann/json#10]
It is unclear how parser handles non-ascii strings. It would be nice to have it and have a statement about the i18n

**Comment by nlohmann** [comment]
I'll have a look once I have a better parser (see #12)

**Comment by nlohmann** [comment]
With pull request #22, this issue should be addressed.

**Comment by nlohmann** [comment]
Fixed in latest commit: UTF-8 is now supported.
