### ISSUE TITLE
failed to iterator json object with reverse_iterator

### ISSUE THREAD

**Issue by likebeta** [nlohmann/json#100]
Hello @nlohmann , I've got a problem.

code:
```
#include "json.hpp"
using nlohmann::json;
#include <iostream>
using namespace std;

int main()
{
	json config = {
		{ "111", 111 },
		{ "112", 112 },
		{ "113", 113 }
	};

	cout << config << endl;
	for (auto it = config.begin(); it != config.end(); ++it)
	{
		cout << it.key() << ": " << it.value() << endl;
	}

	for (auto it = config.rbegin(); it != config.rend(); ++it)
	{
		cout << it.key() << ": " << it.value() << endl;
	}

	return 0;
}
```
output:
```
{"111":111,"112":112,"113":113}
111: 111
112: 112
113: 113
Segmentation fault (core dumped)
```

Think you for your help!

**Comment by nlohmann** [comment]
This seems to be related to #93.

**Comment by nlohmann** [comment]
Hi @likebeta,

thanks for reporting! I can reproduce the error with Clang AddressSanitizer. I'll check on #93 first and see if that also fixes this issue.

All the best,
Niels

**Comment by nlohmann** [comment]
As far as I understand the issue right now, there seems to be an off-by-one error when using `base()` to link the reverse iterators to the "normal" iterators. I'm on it.

**Comment by nlohmann** [comment]
Hi @likebeta,

I fixed the code. It seems that I never really understood the relationship between a reverse iterator and its underlying iterator accessed via `base()`. All I needed to do was to decrement the `base()` iterator before forwarding calls to `key()` or `value()`.

I added your initial code as regression test.

Hope that works for you,
Niels

**Comment by likebeta** [comment]
@nlohmann Well done, Thank you for your help ^_^
