### ISSUE TITLE
How to check if key existed 

### ISSUE THREAD

**Issue by leeqicheng** [nlohmann/json#1000]
Hi to all is there a method to check if the key exist , 

what is the close to 

Java JSON 

> indivFB.has("object_id")

Thanks

**Comment by nlohmann** [comment]
Just like for a map: [`find()`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a89eb3928f57903677051c80534be9cb1.html#a89eb3928f57903677051c80534be9cb1).

**Comment by leeqicheng** [comment]
Hi thanks for the reply but im using iterator

any idea why is causing this problem ?

> Value of type 'iterator' (aka 'nlohmann::detail::iter_impl<nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>, bool, long long, unsigned long long, double, std::allocator, adl_serializer> >') is not contextually convertible to 'bool'

**Comment by nlohmann** [comment]
I would need to see a code example for that.

**Comment by leeqicheng** [comment]
Hi thanks for time, 

The problem i face is that sometimes the json result doesnt have the key so im trying to check for the key 

![screen shot 2018-03-09 at 5 22 49 pm](https://user-images.githubusercontent.com/6437615/37200051-978a2204-23be-11e8-9a32-5b5deda010e5.png)

**Comment by nlohmann** [comment]
When you iterate over an object (which I assume - I have not seen the JSON), doing this with a range for only gives you access to the values, not to the keys. You need to use [`items()`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_afe3e137ace692efa08590d8df40f58dd.html#afe3e137ace692efa08590d8df40f58dd) for this.

The exception comes, because you try to assign a number (from `...["total_count"]`) to a string (`totallike`). Try to output `...["total_count"]` directly and use a number type for `totallike`.

**Comment by leeqicheng** [comment]
Sorry wrong image it should be this 

![screen shot 2018-03-09 at 5 27 34 pm](https://user-images.githubusercontent.com/6437615/37200265-3680bff8-23bf-11e8-9323-f325cbafc19f.png)

**Comment by nlohmann** [comment]
Then use find:

```cpp
if (json_field_data[p]["reactions"]["summary"].find("total_count") != json_field_data[p]["reactions"]["summary"].end())
   // now you can be sure json_field_data[p]["reactions"]["summary"]["total_count"] exists
```

Alternatively, you could use [`value`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_adcf8ca5079f5db993820bf50036bf45d.html#adcf8ca5079f5db993820bf50036bf45d) and provide a default value (e.g., 0):

```cpp
totallike = json_field_data[p]["reactions"]["summary"].value("total_count", 0);
```

**Comment by leeqicheng** [comment]
Thanks for the library and the help

**Comment by Tudyx** [comment]
In case if we are not sure if the keys before the nested key exist, should we use nested if ? Because in the [documentation](https://json.nlohmann.me/api/basic_json/operator%5B%5D/) it's wrote that is an undefined behavior to if the element with key idx accessing by `operator[]` does not exist.

```C++
if (json_field_data[p].find("reactions") != json_field_data[p].end()){
    if(json_field_data[p]["reactions"].find("summary") != json_field_data[p]["reactions"].end()){
        if(json_field_data[p]["reactions"]["summary"].find("total_count") != json_field_data[p]["reactions"]["summary"].end())
    }
}
```

**Comment by nlohmann** [comment]
Yes, you need to check for each level. Note there is a `contains` function that could simplify your code: https://json.nlohmann.me/api/basic_json/contains/

Also note that that JSON Pointer could help you, see https://github.com/nlohmann/json/discussions/2585#discussioncomment-280524
