### ISSUE TITLE
more than one operator '=' matches these operands

### ISSUE THREAD

**Issue by balldrix** [nlohmann/json#1002]
I'm copying data into a struct. I get this warning when I copy a std::string.

```
// read file
	std::ifstream file(fileName);

	// parse data from file
	json data = json::parse(file);
	json animation = data["animation"];

	// iterate through data and save in animation list
	for(json::iterator it = animation.begin(); it != animation.end(); ++it)
	{
		// json of current it in array
		json j = it.value();

		// data struct
		Animation animationType;
		animationType.name = j["name"];
		animationType.spriteSheetIndex = j["index"];
		animationType.frameCount = j["frameCount"];
		animationType.framesPerSecond = j["framesPerSecond"];
		animationType.loop = j["loop"];

		// push data to list
		m_animationList.push_back(animationType);
	}
```

The code works as intended but would you know why this message appears? Is there a better way for me to take the json file and put the data in a vector list?

I'm using Windows 7 & Windows 10, Visual Studio 2017 v15.5.6.

Using the most recent release version of nlohmann/json.

**Comment by theodelrieu** [comment]
It's surprising that it even compiles. I would suggest using the `get<>` method:

```cpp
animationType.name = j["name"].get<std::string>();
```

Also, you could refactor your code and create a `from_json` method for your struct `Animation`, you would then be able to do:

```cpp
auto animations = data.get<std::vector<Animation>>();
```

**Comment by balldrix** [comment]
Thank you, the `get<>` method works and has removed the warning.

I'm not sure what you mean about the `from_json `method. Could you explain?

**Comment by theodelrieu** [comment]
You can take a look at this [section](https://github.com/nlohmann/json#arbitrary-types-conversions) of the readme.

If you need more info let me know

**Comment by balldrix** [comment]
I created the `from_json` method and now I'm able to do the above with this:

`	// read file
	std::ifstream file(fileName);

	// parse data from file
	json data = json::parse(file);
	json animation = data["animation"];

	m_animationList = animation.get<std::vector<Animation>>();`
