### ISSUE TITLE
How to compare two JSON objects?

### ISSUE THREAD

**Issue by zkelo** [nlohmann/json#1007]
I have default app settngs in JSON object `DefaultSettings` and I'm parsing current app settings from file `Config.json` (ifstream). How to compare indexes from `Settings` with indexes in `DefaultSettings`? Does library have functions for this? I tried to compare with `iterator_wrapper` but he's deprecated.

**Comment by zkelo** [comment]
For example, i have this JSON string and parsing it. Let this JSON will be a `Settings`. `Settings` string I'm getting from file.
`{
  "Value1": 4,
  "Value3": "Hello"
}`

And this string will be `DefaultSettings`.
`{
  "Value1": 4,
  "Value2": true,
  "Value3": "Hello"
}`

So, in the `DefaultSettings` i have three values, but in `Settings` only two. And when I will use Settings["Value2"] it will generate an exception. For fix it, I want to compare indexes and their values after parsing. Now I'll try to use `items()`, thanks...

**Comment by nlohmann** [comment]
The [`update`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a1cfa9ae5e7c2434cab4cfe69bffffe11.html#a1cfa9ae5e7c2434cab4cfe69bffffe11) function could be handy for you:

```cpp
// start with a copy of the default settings
json s = DefaultSettings;
// overwrite all default settings with those given in Settings
s.update(Settings);
```

Assume `Settings` is `{"Value1": 100}` and `DefaultSettings` like above. Then the result would be `s =  {"Value1": 100, "Value2": true, "Value3": "Hello" }`.

**Comment by zkelo** [comment]
Big thanks.

**Comment by pboettch** [comment]
@zkelo FWIW: for a larger use cases you might consider using JSON-schemas for validating JSON objects.
