### ISSUE TITLE
The library doesn't want to insert an unordered_map

### ISSUE THREAD

**Issue by tristan957** [nlohmann/json#1010]
**Bug Report**

- What is the issue you have? I am trying to insert an unordered_map, but it always comes out ordered in the json file.

- Please describe the steps to reproduce the issue. Can you provide a small but working code example? 
```
args = {"hello", "world"};
json j;
// get info from file
j["distributions"].push_back(std::unordered_map<std::string, std::string>({{"name", args[1]}, {"location", args[2]}}));

{
    "distributions": [
        {
            "location": "world",
            "name": "hello"
        },
        {
            "location": "there",
            "name": "hi"
        },
        {
            "location": "partin",
            "name": "tristan"
        }
    ]
}
```

- What is the expected behavior? I want the name key, then the location key.

- And what is the actual behavior instead? The location key comes before the name key.

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)? G++ 7.3 Solus (Linux)

- Did you use a released version of the library or the version from the `develop` branch? Released (latest stable)

**Comment by nlohmann** [comment]
The library uses `std::map` internally to store object keys, so they are always ordered. See https://github.com/nlohmann/json#notes (last item) for more information.

**Comment by tristan957** [comment]
Thanks for the comment. I did not see that.

**Comment by nlohmann** [comment]
No worries!
