### ISSUE TITLE
how to serialize class Object (convert data in object into json)??

### ISSUE THREAD

**Issue by Mamlesh** [nlohmann/json#1011]

**Comment by nlohmann** [comment]
Without more information, we cannot help you. This may be interesting though: https://github.com/nlohmann/json#arbitrary-types-conversions

**Comment by Mamlesh** [comment]
thanks ...but i want to do something like...
//example
class A
{
string a;
}
class B
{
A z;
string n;
}

class Main
{
B b;
}

//data will come in object at run time 
// so i want to covert data into direct json string...in c++

**Comment by nlohmann** [comment]
This can be achieved with the conversions described in the link above. You need to define a conversion function `to_json` for each class.

**Comment by Mamlesh** [comment]
Ok i'll try it ..thank you..sir

**Comment by nlohmann** [comment]
@Mamlesh Did it work? Do you need further assistance?
