### ISSUE TITLE
STL containers are always serialized to a nested array like [[1,2,3]]

### ISSUE THREAD

**Issue by fred777** [nlohmann/json#1013]
**Bug Report**

I'm using the single-header json.hpp (v3.1.1) and I am struggling with serializing stl containers:
```
auto tojson = nlohmann::json{ std::forward_list<double>{1,2,3} };
cout << tojson;
```
**Expected:** [1,2,3]
**Got instead:** [[1,2,3]]

It's the same for other STL containers like vector, list, initializer_list, ...

Did I miss something?

**Compiler:** Visual C++ 2017 (v15.6.1)
**OS:** Windows 10 x64

**Comment by nlohmann** [comment]
This is due to the outer-most braces which are interpreted as array. Try

```cpp
nlohmann::json tojson = std::forward_list<double>{1,2,3};
cout << tojson;
```

**Comment by fred777** [comment]
Thanks! You saved my day 👍
