### ISSUE TITLE
Function find overload taking a json_pointer

### ISSUE THREAD

**Issue by markand** [nlohmann/json#1017]
**Feature Request**

It looks like there is no `find` function taking a `json_pointer`. I think it could be handy to have a no-throwing find overload for it so we are able to do:

```cpp
#include <json.hpp>

int main()
{
    auto json = nlohmann::json({
        { "foo", "true" }
    });
    auto it = json.find("/foo"_json_pointer);

    if (it != json.end())
        std::cout << it->dump(4) << std::endl;
    else
        std::cout << "not found" << std::endl;
}
```

**Comment by nlohmann** [comment]
Internally, JSON pointers are heavily using exceptions internally, so the best such a function would do is, for instance, wrap the existing `at` function for JSON pointers.

**Comment by nlohmann** [comment]
Any opinions on this?

**Comment by nlohmann** [comment]
No one?

**Comment by gregmarr** [comment]
Is this just another name for `at()`?  Doesn't seem necessary to me, but I don't use json pointers.

**Comment by madmongo1** [comment]
Sorry for the late comment. This became relevant to me when using your wonderful library in a large production project recently.
Please see the attached bug report.
For my money, I would recommend that either:
1) find is modified to support json_pointer, or
2) json_pointer overloads are specifically disallowed (which seems restrictive to me)

At the moment, the API is allowing developers to unwittingly write and compile code that will crash at runtime. I feel this is serious enough to warrant re-opening and addressing this CR.

https://github.com/nlohmann/json/issues/1418
