### ISSUE TITLE
add json string in previous string??

### ISSUE THREAD

**Issue by Mamlesh** [nlohmann/json#1025]
1st string..

{ { "Layer",  },
{ "Data",{
{ { "Type", },{ "Count", },
{ "Point",
{
			
}
}
}
} },
};

2nd string..

{ "Point1",
{
{ "X", },
{ "Y", },
{ "Z", }
} },

how to add 2nd string into "Point" section of 1st string???

**Comment by nlohmann** [comment]
The example is not JSON. Could you provide a concrete example with proper JSON or C++ code?

**Comment by nlohmann** [comment]
Similar to #1012, use `operator[]` to navigate in objects and arrays:

```cpp
// assuming s1 is the JSON value for the first string and s2 the one for the second string
s1["HATCH"][0]["Data][0]["Point"].push_back(s2);
```

**Comment by nlohmann** [comment]
@Mamlesh Did that work?
