### ISSUE TITLE
HOCON reader?

### ISSUE THREAD

**Issue by abrownsword** [nlohmann/json#1027]
**Feature Request**

Since your JSON C++ API is mature and so much nicer than cpp-hocon's (not to mention WAY fewer dependencies), it would be really nice if this project were able to read HOCON files.  I would imagine the include mechanism would be the trickiest part, whereas having the parser skip comments and cope with the format's extensions shouldn't be a big deal.  Writing would be substantially more complex (due to the need to support adding includes, comments, etc) and is substantially less interesting since HOCON's primary goal seems to be to make config files more *human* writeable.

**Comment by OvermindDL1** [comment]
Oh I quite like the HOCON spec, defined at:  https://github.com/lightbend/config/blob/master/HOCON.md

It is JSON with extra features.  Any JSON is valid HOCON (though not the other way).  It is basically YAML done right (pretty old format too).  This would be quite nice though entirely understandable if not done.

**Comment by nlohmann** [comment]
I do not see this feature fit for this library. HOCON seems not the be used by many people, and at the same time, implementing a parser for it seems to be a lot of work...

**Comment by nlohmann** [comment]
Related: #1024

**Comment by abrownsword** [comment]
I am using your JSON library for configuration files quite heavily (indeed, that is ALL I am using it for at the moment, and when I do start using it for data purposes it'll be via one of the binary formats you support), and the advantages of HOCON for handwritten files are substantial.  If nothing else the addition of comments is a huge win, but I do think that comments shouldn't be added to JSON as a non-standard, breaking extension so doing it as a new JSON-derived format like HOCON is a better approach.

**Comment by nlohmann** [comment]
I understand, but the HACON description seems rather complex, and I fear that adding this complexity to the library is not really an improvement.

**Comment by OvermindDL1** [comment]
Eh, the most used features I enjoyed from my HOCON days was the ability to define defaults as variables and 'import' them, as well as including other files at positions (and comments as well).

**Comment by abrownsword** [comment]
Unfortunately the include mechanism requires machinery and assumptions, although I suppose most of that could be delegated to a user lambda.

**Comment by nlohmann** [comment]
The extension to HOCON is out of scope for this library.
