### ISSUE TITLE
Makefile: Valgrind flags have no effect

### ISSUE THREAD

**Issue by tsemaylo** [nlohmann/json#1030]
There is the following Valgrind configuration in CMake file from test subdirectory (test/CMakeLists.txt).
And it looks like there is a typo.

```cmake
if(JSON_Valgrind)
    find_program(CMAKE_MEMORYCHECK_COMMAND valgrind)
    message(STATUS "Executing test suite with Valgrind (${CMAKE_MEMORYCHECK_COMMAND})")
    set(MEMORYCHECK_COMMAND_OPTIONS "--error-exitcode=1 --leak-check=full")
    set(memcheck_command "${CMAKE_MEMORYCHECK_COMMAND} ${CMAKE_MEMORYCHECK_COMMAND_OPTIONS}")
    separate_arguments(memcheck_command)
endif()
```

Variable `CMAKE_MEMORYCHECK_COMMAND_OPTIONS` is not initialized instead of that we have `set(MEMORYCHECK_COMMAND_OPTIONS, ...)`. Therefore automated execution of tests will not report any memory check problem.

**Comment by nlohmann** [comment]
Thanks for noting! Now I hope the checks do not fail :)
