### ISSUE TITLE
Issued with Clion Inspection Resolution since 2018.1

### ISSUE THREAD

**Issue by trivigy** [nlohmann/json#1033]
Really not sure how to touch base with clion nor do I feel like they will do anything to fix this. Figured I will post it here and see if anyone else has the same issue.

In both cases I am getting: "no matching function" and "no matching constructor".

However the code compiles and works fine.
![screenshot from 2018-04-01 10-48-56](https://user-images.githubusercontent.com/3146062/38174413-ba910dd8-359a-11e8-9e91-1a6f8feb9d1d.png)
![screenshot from 2018-04-01 10-48-45](https://user-images.githubusercontent.com/3146062/38174414-baa2e364-359a-11e8-8f37-9ca07263c493.png)

**Comment by nlohmann** [comment]
This is strange. But CLion seems to have some issues with templates. It keeps proposing to "optimize" the code by removing SFINAE guards. I am not sure whether CLion has a bug tracker, but I think opening an issue there could help.

**Comment by trivigy** [comment]
Raised an issue on clion board. Hopefully someone on their end will look into this. One other thing I mentioned was that I noticed an update in clang version along with the upgrade to clion-2018.1. Could it be related to clang changing something? I believe inspection is done using clang, I may be wrong on that one though.

https://youtrack.jetbrains.com/issue/CPP-12558

**Comment by nlohmann** [comment]
Did the inspection work before the update?

**Comment by nlohmann** [comment]
The issue could be fixed with CLion 2018.1.1 EAP, see https://youtrack.jetbrains.com/issue/CPP-12558.

**Comment by trivigy** [comment]
I can confirm that it fixes it partially. My guess that this will get totally fixed in the next release. I also was right, this has to do with clang-tidy. I can see a slightly different issue now but I will keep following up on this with the jetbrains team. This thread can probably be closed.
![screenshot from 2018-04-03 12-07-09](https://user-images.githubusercontent.com/3146062/38261391-109a24c8-3738-11e8-81d7-0ee5ab17d2e6.png)

**Comment by nlohmann** [comment]
Thanks a lot for reporting! I'll do my best that this library can serve as a benchmark for Jetbrains ;-)

**Comment by trivigy** [comment]
@nlohmann Don't be harsh on yourself. You are already doing an absolutely amazing job. I tried tons of json libraries and finally stuck with this because of the awesome syntax you made work. I am sure implementing that was not easy. So, it is bound to have some issues with the jetbrains coding style and expectations.

**Comment by OvermindDL1** [comment]
For note, I tried the code in KDevelop (which also embeds clang) and it did not have such issues, so it's not a clang thing.  :-)
