### ISSUE TITLE
I know the library supports UTF-8, but failed to dump the value

### ISSUE THREAD

**Issue by htonus** [nlohmann/json#1036]
**Bug Report**

- What is the issue you have?
Failed to dump object with UTF8 value;

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?
jsonObject["name"] = "Telefónica";
jsonObject.dump()

- What is the expected behavior?
stringified json
- And what is the actual behavior instead?
thrown an exeption. Is it possible to avoid exceptions?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?
VS 2017 Community edition

- Did you use a released version of the library or the version from the `develop` branch?
From dev branch

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Feature Request**

- Describe the feature in as much detail as possible.

- Include sample usage where appropriate.

**Comment by nlohmann** [comment]
- Can you make sure that MSVC is actually using UTF-8 for string literals?
- What exactly does the exception say?

**Comment by htonus** [comment]
it is multibyte, and exception happened here:
                case UTF8_REJECT:  // decode found invalid UTF-8 byte
                {
                    std::stringstream ss;
                    ss << std::setw(2) << std::uppercase << std::setfill('0') << std::hex << static_cast<int>(byte);
                    JSON_THROW(type_error::create(316, "invalid UTF-8 byte at index " + std::to_string(i) + ": 0x" + ss.str()));
                }
<img width="322" alt="screen shot 2018-04-03 at 3 09 17 pm" src="https://user-images.githubusercontent.com/805160/38248576-80511bdc-3751-11e8-818f-87b3545a1a29.png">

**Comment by nlohmann** [comment]
If it is multibyte, then it is not UTF-8.

**Comment by htonus** [comment]
How I can convert to the format json::dump would accept it please?

**Comment by nlohmann** [comment]
This is currently not possible. The library only supports UTF-8 at the moment. Maybe this helps: https://docs.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8

**Comment by htonus** [comment]
Okay, thank you for the answers.
