### ISSUE TITLE
Direct download link for json_fwd.hpp?

### ISSUE THREAD

**Issue by wolframroesler** [nlohmann/json#1037]
On the release page (https://github.com/nlohmann/json/releases) there's a hyperlink to download the single header version of the library (currently, https://github.com/nlohmann/json/releases/download/v3.1.2/json.hpp). How about adding a similar link for the forward header file, json_fwd.hpp?

**Comment by nlohmann** [comment]
Does it help if I mention that that header is included in the `include.zip` file of the latest releases?

**Comment by wolframroesler** [comment]
Helps me right now, thanks :) 
Want to keep it as a suggestion for the next release?

**Comment by nlohmann** [comment]
I'm afraid the releases become a bit crowdy... Maybe others have an opinion on this?

**Comment by nlohmann** [comment]
As there is no further discussion, I would leave the release as is.
