### ISSUE TITLE
const_reference operator[](const typename object_t::key_type& key) const throw instead of assert

### ISSUE THREAD

**Issue by smonasco** [nlohmann/json#1039]
**Feature Request**

I'd rather have an out_of_range exception thrown than undefined behavior that kills my app (VS2015).

**Comment by OvermindDL1** [comment]
Except by following the standard, `operator[]` is unchecked where a `at` should be checked.  I.E. accessing an invalid key/index via `operator[]` is *supposed* to be UB.  If you want a checked version then you should use an `at` (if this library doesn't have an `at` then it should be added, I don't recall...).

**Comment by nlohmann** [comment]
Duplicate: #264 #135

**Comment by nlohmann** [comment]
The behavior of [`const operator[]`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_ab2318780e5ae692039e816b6ac32c91e.html#ab2318780e5ae692039e816b6ac32c91e) is documented. The goal is to have quick access without checking overhead. For the latter, there is [`at`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_acac9d438c9bb12740dcdb01069293a34.html#acac9d438c9bb12740dcdb01069293a34).

There have been long discussions about the behavior. In conclusion, we would rather have a const `operator[]` version with the current semantics than just a copy of `at`. We are aware of `std::map` not having a const `operator[]`.

**Comment by smonasco** [comment]
OK, but there are no savings in doing the assert over the if and throw. The assert still must make the comaprison.

https://ideone.com/e.js/RyHb0t

Everytime I check the assert over 1,000,000 iterations it ends up being slower actually.

**Comment by nlohmann** [comment]
In production code, you should compile without assertions.
