### ISSUE TITLE
Usage with gtest/gmock not working as expected

### ISSUE THREAD

**Issue by deblauwetom** [nlohmann/json#1044]
I am trying to use the library with google test/google mock. It seems gtest is not able to print the json value out with its universal printer.

Example that fails:
```cpp
#include <gtest/gtest.h>
#include <nlohmann/json.hpp>

using json = nlohmann::json;
using namespace testing;

TEST(EnsureJsonComparesCorrectly)
{
   auto test1 = R"BLA(
{
    "event" : "test",
    "description" : "Test description"
}
)BLA"_json;

   auto test2 = R"BLA(
{
    "description" : "Test description",
    "event" : "test"
}
)BLA"_json;
    EXPECT_THAT(test1, Eq(test2));
}

```

I am using 3.1.2 of nlohmann and 1.8.0 of google test/mock. I am compiling and running on macOS.

I also tried to use it with gmock, but it also fails. The myCall function is defined as:
```cpp
void myCall(std::string url, nlohmann::json message);
```
So this is in gmock:
```cpp
MOCK_METHOD2(myCall, void(std::string url, nlohmann::json message));
```
And then in the test I set an expectation, like this:
```cpp
 EXPECT_CALL(*myMock, myCall(_, test1));
```

but every time gtest tries to print, in this case the "test1" object, then it crashes.

So what could causing this? Gtest is normally able to use a custom PrintTo function but I could not get that to work. Any pointers on how to solve it?

I have a "workaround" but it goes against the "json as first-class citizen" philosophy :)
Workaround for EXPECT_THAT:
```cpp
EXPECT_THAT(test1.dump(), Eq(test2.dump()));
```
That is more or less acceptable, but not really.
And then for gmock it is really too much :) see:
```cpp
json tmp;
json test;
EXPECT_CALL(*myMock, myCall(_, _)).WillOnce(SaveArg<1>(&tmp));
EXPECT_THAT(tmp.dump(), Eq(test.dump()));
```
But of course it should be as easy as:
```cpp
EXPECT_CALL(*myMock, myCall(_, test));
```

**Comment by nlohmann** [comment]
I am not using Google Mock myself, so I have no idea what to do here.

**Comment by deblauwetom** [comment]
It seems I am hitting this situation: #709
And the solution is in googletest itself, however they still need to do a release of their current master as 1.8.1 which I hope is very soon. 
The workaround suggested in #709 is not working for me unfortunately.

**Comment by feedhandler** [comment]
Initially the workaround in #709 only worked for me, but some time later it seemed to stop working. I wasn't able to find out why but I suspect it was related to the problem discussed in google/googletest#1149 
Eventually I fixed it by adding overloads for my other types that are based off nlohmann::basic_json<>, e.g.
```C++
namespace nlohmann
{
  void PrintTo(const json& j, std::ostream* os)
  {
    *os << j.dump();
  }
  
  void PrintTo(const ordered_json& j, std::ostream* os)
  {
    *os << j.dump();
  }
}
```
where ordered_json is 
```
using ordered_json = nlohmann::basic_json<ifo_map>;
```
