### ISSUE TITLE
error: ‘BasicJsonType’ in namespace ‘::’ does not name a type

### ISSUE THREAD

**Issue by simulationcloud** [nlohmann/json#1051]
I get this error when compiling with nvcc, which is using g++6.4.1. I am specifying the --std=c++11 flag.

The version of nlohmann/json is 3.1.2. 

Any help would be greatly appreciated!

**Comment by nlohmann** [comment]
Could you indicate the line where the error occurs or paste the complete error message here? What was the code you tried to compile?

**Comment by simulationcloud** [comment]
/home/ec2-user/dev/john/Flow360_3.26.2018/json/include/nlohmann/detail/iterators/iter_impl.hpp:46:11: error: 
This is the error I get by only including the header file #include "nlohmann/json.hpp":

‘BasicJsonType’ in namespace ‘::’ does not name a type
     friend BasicJsonType;
           ^~~~~~~~~~~~~

I reverted to version 2.1.2 and got it to compile, but I would like to use the latest version.

**Comment by theodelrieu** [comment]
Seems like a compiler bug to me...

Could you try patching the `iter_impl.hpp`?

```cpp
using J = BasicJsonType;
friend J;
```

**Comment by simulationcloud** [comment]
hmm. Same thing with the patch:
/home/ec2-user/dev/john/Flow360_3.26.2018/json/include/nlohmann/detail/iterators/iter_impl.hpp:48:11: error: ‘BasicJsonType’ in namespace ‘::’ does not name a type
     friend J;

**Comment by theodelrieu** [comment]
This is weird, I guess it's the same problem if you change the name of the template parameter directly?

**Comment by simulationcloud** [comment]
I think it's a bug with nvcc. If I move the function to a separate cpp file and compile it only with gcc, it works.

**Comment by nlohmann** [comment]
Thanks for reporting back!

**Comment by pradeepisro** [comment]
is there anyway to make it work with nvcc?

**Comment by pradeepisro** [comment]
[This](https://stackoverflow.com/a/5608542/6059586) answer in Stackoverflow solves the problem. Adding a wrapper around the BasicJsonType works with nvcc and gcc.

    template<typename T>
    struct BasicJsonType_wrapper{
        typedef T type;
    };

    template<typename BasicJsonType>
    class iter_impl
    {
        /// allow basic_json to access private members
        friend iter_impl<typename std::conditional<std::is_const<BasicJsonType>::value, typename     std::remove_const<BasicJsonType>::type, const BasicJsonType>::type>;
        // friend BasicJsonType;
        friend class BasicJsonType_wrapper<BasicJsonType>::type;
        friend iteration_proxy<iter_impl>;
