### ISSUE TITLE
[Feature request] Access by path

### ISSUE THREAD

**Issue by SylvainCorlay** [nlohmann/json#1053]
It would be great if there was accessors by path in a JSON object:

for example, if we have a JSON object `x` containing

```JSON
{
    "foo": {
        "bar": {
            "value": 1   
        },
        "baz": {
            "value": 3
        }
    }
}
```

`x[{"foo", "baz"}]` would return a JSON object containing

```JSON
{
    "value": 3
}
```

**Comment by SylvainCorlay** [comment]
cc @martinRenou

**Comment by nlohmann** [comment]
What is the difference to `x["foo"]["baz"]`?

**Comment by SylvainCorlay** [comment]
> What is the difference to x["foo"]["baz"]?

The difference is the unknown number of elements in the sequence.

**Comment by theodelrieu** [comment]
Isn't json_pointer what you're looking for?

**Comment by nlohmann** [comment]
@theodelrieu is right. JSON Pointers can do this:

```cpp
#include <iostream>
#include "json.hpp"

using json = nlohmann::json;

int main()
{
    json j = R"({
        "foo": {
            "bar": {
                "value": 1
            },
            "baz": {
                "value": 3
            }
        }
    })"_json;

    std::cout << j["/foo/baz"_json_pointer] << std::endl;
}
```

**Comment by SylvainCorlay** [comment]
Thanks!  I did not know about this!

**Comment by juzzlin** [comment]
Could you give an example?

I'm trying to do something like this, but I don't understand why it won't compile:

``
using nlohmann::json;
using nlohmann::json_pointer;

json root;
std::string path = "/foo/bar";
root[json_pointer(path)] = 42;
``

**Comment by nlohmann** [comment]
What is the compiler error?

**Comment by juzzlin** [comment]
Seems that it just had to be `root[json_pointer<std::string>(...)`. Thanks a lot!

**Comment by anirudh582** [comment]
> ```c++
> #include <iostream>
> #include "json.hpp"
> 
> using json = nlohmann::ordered_json;
> 
> int main()
> {
>     json j = R"({
>         "foo": {
>             "bar": {
>                 "value": 1
>             },
>             "baz": {
>                 "value": 3
>             }
>         }
>     })"_json;
> 
>     std::cout << j["/foo/baz"_json_pointer] << std::endl;
> }
> ```

This code prints `null`. The only difference here is I am using `ordered_json` instead of `json`. Is there a way to make this work for `ordered_json`? Thanks.

**Comment by falbrechtskirchinger** [comment]
@anirudh582 Works fine here: https://godbolt.org/z/ExaTeeMTd

What version/compiler are you using?

**Comment by anirudh582** [comment]
I am using version 3.10.5. I checked with the latest version and it is working. Thank you!

**Comment by falbrechtskirchinger** [comment]
> I am using version 3.10.5. I checked with the latest version and it is working. Thank you!

`j[json::json_pointer("/foo/baz")]` should work in 3.10.5. Due to a bug, your code is equivalent to: `j["/foo/baz"]` (i.e., the `json_pointer` is converted to string)

**Comment by anirudh582** [comment]
> `j[json::json_pointer("/foo/baz")]` should work in 3.10.5. Due to a bug, your code is equivalent to: `j["/foo/baz"]` (i.e., the `json_pointer` is converted to string)

I checked this and `j[json::json_pointer("/foo/baz")]` does indeed work in 3.10.5. Thank you very much!
