### ISSUE TITLE
when using assign operator in with json object a static assertion fails..

### ISSUE THREAD

**Issue by jipr311** [nlohmann/json#1055]
**Bug Report**
suppose you have the following class:

```cpp
class Point{
public:
Point();
private:
int x;
int y;
}
```

then if you create a point:

```cpp
Point p { 100, 100 };
```

and do

```cpp
json j = p;
```

then you get the error: 

```
static assertion failed: could not find to_json() method in T's namespace
         static_assert(sizeof(BasicJsonType) == 0,
         ^
````

that is pretty st.forward, what is the reason of the failure?
**Feature Request**

- Describe the feature in as much detail as possible.

- Include sample usage where appropriate.

**Comment by nlohmann** [comment]
Please have a look at the documentation: https://github.com/nlohmann/json/blob/develop/README.md#arbitrary-types-conversions

**Comment by nlohmann** [comment]
@jipr311 Does the arbitrary types conversion section help you?

**Comment by nlohmann** [comment]
Can I close this issue?
