### ISSUE TITLE
newbie usage question

### ISSUE THREAD

**Issue by lonnieOST** [nlohmann/json#1063]
Hello,

I was looking over your json framework and think that it is exactly what I need for my project, but in your documentation I did not see how to iterate over a json set of attributes.

For example if I have a json file that looks like this:

```js
{
    "answers": [],
    "corrections": [],
    "infoboxes": [
        {
            "content": "...",
            "engine": "...",
            "id": "...",
            "img_src": "...",
            "infobox": "...",
            "urls": [
                {
                    "title": "...",
                    "url": "..."
                }
            ]
        }
    ],
    "number_of_results": ...,
    "query": "...",
    "results": [
        {
            "category": "....",
            "content": "...",
        },
        {
            "category": "....",
            "content": "...",
        },
        {
            "category": "....",
            "content": "...",
        },
        {
            "category": "....",
            "content": "...",
        },
        {
            "category": "....",
            "content": "...",
        }
    ],
    "suggestions": [],
    "somehting": [
        [
            "one",
            "two"
        ]
    ]
}
```

Then I have to 2 possible needs.

1. I would read it in a string variable and want to iterate over the "category" and "content" attributes to collect all of the different information.

2. I would like to be able to create the above json using your reference method.

In your example I would like to create:

```js
{
  "pi": 3.141,
  "happy": true,
  "name": "Niels",
  "nothing": null,
  "answer": {
    "everything": 42
  },
  "list": [1, 0, 2],
  "object": {
    "currency": "USD",
    "value": 42.99
  },
  "object": {
    "currency": "USD",
    "value": 2.99
  },
  "object": {
    "currency": "USD",
    "value": 4.99
  }
}
```

You show:

```cpp
// add another object (using an initializer list of pairs)
j["object"] = { {"currency", "USD"}, {"value", 42.99} };
```

but can it also be done something like:

```cpp
// add another object (using an initializer list of pairs)
j["object"] ["currency"]=  "USD"
j["object"]["value"]= 42.99;
```

but that would only be for 1 object and I need to be able to add many "object" items to a structure.

I also need to be able to reference nested items in a similar way if possible.

Thanks,

**Comment by nlohmann** [comment]
You cannot create a JSON like

```js
{
  "pi": 3.141,
  "happy": true,
  "name": "Niels",
  "nothing": null,
  "answer": {
    "everything": 42
  },
  "list": [1, 0, 2],
  "object": {
    "currency": "USD",
    "value": 42.99
  },
  "object": {
    "currency": "USD",
    "value": 2.99
  },
  "object": {
    "currency": "USD",
    "value": 4.99
  }
}
```

because each key in an object must be unique. See also https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a5e48a7893520e1314bf0c9723e26ea2a.html#a5e48a7893520e1314bf0c9723e26ea2a (section "Behavior").

You could instead create an array of objects, e.g.

```
[
{
    "currency": "USD",
    "value": 4.99
},
{
    "currency": "USD",
    "value": 2.99
}
]
```

**Comment by lonnieOST** [comment]
Hello,

What I have is a server returning some json with the following structure:

{
    "answers": [],
    "corrections": [],
    "infoboxes": [
        {
            "content": "...",
            "engine": "...",
            "id": "...",
            "img_src": "...",
            "infobox": "...",
            "urls": [
                {
                    "title": "...",
                    "url": "..."
                }
            ]
        }
    ],
    "number_of_results": 000,
    "query": "...",
    "results": [
        {
            "category": "...",
            "content": "...",
            "engine": "...",
            "engines": [
                "1",
                "2",
                "3"
            ],
            "positions": [
                1,
                2,
                1
            ],
            "score": 7.5,
            "title": "...",
            "url": "..."
        },
        {
            "category": "...",
            "content": "...",
            "engine": "...",
            "engines": [
                "1",
                "2",
                "3"
            ],
            "positions": [
                1,
                2,
                1
            ],
            "score": 7.5,
            "title": "...",
            "url": "..."
        },
        {
            "category": "...",
            "content": "...",
            "engine": "...",
            "engines": [
                "1",
                "2",
                "3"
            ],
            "positions": [
                1,
                2,
                1
            ],
            "score": 7.5,
            "title": "...",
            "url": "..."
        }
    ],
    "suggestions": [],
    "unresponsive_engines": [
        [
            "A",
            "B"
        ],
        [
            "ONE",
            "TWO"
        ]
    ]
}

And I am trying to find a way to read the data that is in each "category",
"content", "engine", "engines", "positions", etc.... as these are an array
of objects of the type:

        {
            "category": "...",
            "content": "...",
            "engine": "...",
            "engines": [
                "1",
                "2",
                "3"
            ],
            "positions": [
                1,
                2,
                1
            ],
            "score": 7.5,
            "title": "...",
            "url": "..."
        }



Any ideas on this as this is the structure that the server is returning to
me in the call?

Thanks again

**Comment by nlohmann** [comment]
You would use the `operator[]` in most cases, as described in https://github.com/nlohmann/json#json-as-first-class-data-type. Iteration is done similar to any other STL container.

**Comment by lonnieOST** [comment]
Thanks for the information and I will work on it.

Is there, by chance any examples for this?

My json data feed is received into an stl std::string or std::streamstring
type and I am mostly just looking to iterate through the array of objects
to get the list of items.

Thanks again,

**Comment by nlohmann** [comment]
You can see examples here: https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a233b02b0839ef798942dd46157cc0fe6.html#a233b02b0839ef798942dd46157cc0fe6

**Comment by nlohmann** [comment]
Do you need further assistance?
