### ISSUE TITLE
cyryllic symbols

### ISSUE THREAD

**Issue by eksponvt** [nlohmann/json#1064]
```cpp
auto main( ) -> int
{
	setlocale(0, "ru");
	std::cout << nlohmann::json::parse(std::string("{ \"happy\": тест, \"pi\": 3.141 }")) << std::endl;
	Sleep(INT_MAX);
}
```

if I replace "тест" with English symbols, program doesnt throw an exception

screenshot:
![dc782d02-2958-4559-8a59-bb5365342e33](https://user-images.githubusercontent.com/37670650/39099640-e3622600-469f-11e8-8d71-2aeec482c251.jpeg)

**Comment by gregmarr** [comment]
The input to `parse` needs to be UTF-8.  It is likely that the string that you're providing is not a valid UTF-8 string.

**Comment by eksponvt** [comment]
I compile with "/Zc:twoPhase- /utf-8"
And encoding is also set to Unicode

**Comment by nlohmann** [comment]
In your example, there are no quotes around `тест`. Does the code also fail with

```cpp
auto main( ) -> int
{
	setlocale(0, "ru");
	std::cout << nlohmann::json::parse(std::string("{ \"happy\": \"тест\", \"pi\": 3.141 }")) << std::endl;
	Sleep(INT_MAX);
}
```

?

**Comment by nlohmann** [comment]
Does your shell support UTF-8?

Could you try the following:

```cpp
auto j = nlohmann::json::parse(std::string("{ \"happy\": \"тест\", \"pi\": 3.141 }"));
std::string j_dump = j.dump();
```

And then check in the debugger which bytes are stored in `j_dump`?

**Comment by eksponvt** [comment]
![fa32627f-fd31-4b0d-9d70-f6476f70cb2d](https://user-images.githubusercontent.com/37670650/39126239-a3838220-4723-11e8-848e-41cf0c760c7c.jpeg)

**Comment by nlohmann** [comment]
Can you please give the exact bytes stored (best as hex value)?

**Comment by eksponvt** [comment]
![68795cb6-a58b-4d7b-90d0-9e69138a1ea8](https://user-images.githubusercontent.com/37670650/39128072-9bb4dc9c-4728-11e8-98d0-03972b754174.jpeg)

**Comment by nlohmann** [comment]
These bytes are UTF-8, so the library correctly parses and stores the string. Then it seems as if your system (shell, IDE, ...) does not correctly displays UTF-8.

**Comment by nlohmann** [comment]
@eksponvt Do you need further assistance?

**Comment by eksponvt** [comment]
No, thanks for help
