### ISSUE TITLE
Not existing value, crash

### ISSUE THREAD

**Issue by Dardanboy** [nlohmann/json#1065]
**Bug Report**

- When I get a json list (from server) and that a value I try to reach doesn't exist, the application crash

**Feature Request**

- I think that this kind of things shouldn't happen (maybe an error, or maybe something returning nothing would be better)

***What is the best solution in this cases ? (Check before trying to get value ?..)***

**Comment by Dardanboy** [comment]
Ok so I n particular, note operator[] implements unchecked access for const objects: If the given key is not present, the behavior is undefined (think of a dereferenced null pointer) and yields an assertion failure if assertions are switched on. If you are not sure whether an element in an object exists, use checked access with the at() function.

**Comment by meirdavis** [comment]
I personally found .value(key, defaultValue) to be more useful, so I get a blank value back rather than an exception.
