### ISSUE TITLE
Compilation error with ICPC compiler

### ISSUE THREAD

**Issue by stefashkaa** [nlohmann/json#1068]
Hello!

What could you say about **https://github.com/nlohmann/json/issues/994** issue?

I have a similar problem using the **ICPC** compiler.

...\json.hpp(904): error : type name is not allowed
detect(std::declval<typename BasicJsonType::template json_serializer<T, void>>()))>::value;
...\json.hpp(920): error : type name is not allowed
std::declval<typename BasicJsonType::template json_serializer<T, void>>()))>::value;
...\json.hpp(935): error : type name is not allowed
std::declval<typename BasicJsonType::template json_serializer<T, void>>()))>::value;

I use the following flags:
`icpc -qopenmp -Wall -otarget/main-uname -m main.cpp
`
Could you help me?

Best regards!
Stefan

**Comment by nlohmann** [comment]
Which version of the library are you using? Which compiler version are you using? Which program are you trying to compile?

**Comment by stefashkaa** [comment]
I using **icpc** from Intel Parallel Studio 16.4, 
**json** version 3.0.1.
I try to compile simple json for my diploma work using REST API

**Comment by nlohmann** [comment]
Does the error still occur with 3.1.2? How does the program look like? What is the call to the library that fails?

**Comment by stefashkaa** [comment]
Error is reproduced in 3.1.2, too. 
For instance, I use json for request:

```
json auth = "{\"label\":\"wavelet\",\"username\":\"stefan\",\"password\":\"pass\"}"_json;
slist = curl_slist_append(slist, "Content-Type: application/json");
```

	string response_string;
	string header_string;
	json token = getToken(curl, slist, auth);
	if (token == NULL)
	{
		cout << "Token wasn't loaded" << endl;
		return -1;
	}

	string token_str = token["access_token"];
	cout << "Token: " << token_str << endl;
```

**Comment by dhaumann** [comment]
@nlohmann I can reproduce this issue with the Intel compiler version 17.0 Update 4 on Windows, nlohmann json v3.1.2. The error I get is:

```
nlohmann/detail/meta.hpp(195): error : type name is not allowed
1>             detect(std::declval<typename BasicJsonType::template json_serializer<T, void>>()))>::value;
1>                                                                                     ^
1>
1>nlohmann/detail/meta.hpp(213): error : type name is not allowed
1>             std::declval<typename BasicJsonType::template json_serializer<T, void>>()))>::value;
1>                                                                              ^
1>
1>nlohmann/detail/meta.hpp(228): error : type name is not allowed
1>             std::declval<typename BasicJsonType::template json_serializer<T, void>>()))>::value;
1>                                                                              ^
```

The switch /Qstd=c++11 is set, so C++11 should be available. Any hints on what to do to get a solution? It seems others were able to resolve this somehow.

**Comment by dhaumann** [comment]
@nlohmann Found the issue. The following code exists three times: in has_from_json, has_non_default_from_json, has_to_json.

    static constexpr bool value = std::is_integral<decltype(
        detect(std::declval<typename BasicJsonType::template json_serializer<T, void>>()))>::value;

All three instances lead the the compiler error in my previous comment. If we change this to

    static constexpr bool value = std::is_integral<decltype(
        detect(std::declval<typename BasicJsonType::template json_serializer<T, void> >()))>::value;
                                                                                     ^

then it works. So we just need to insert a space to change '>>' to '> >'.

To me, this looks clearly like an Intel compiler bug when using >> in [nested?] templates, maybe mixed with decltype or declval.
