### ISSUE TITLE
[clang-3.6.2] string/sstream with number to json issue

### ISSUE THREAD

**Issue by vpetrigo** [nlohmann/json#107]
Dear Niels,

I have a library for working with some translate API. By using curl I form request to the server and obtain a string in the format `{"code":200,"lang":"ru-en","text":[hello]}`. After a while I met the issue that my library which had been build with clang dropped with `Segmentation fault` error. 
Below my test code which works well with `g++ (4.9.2 and 5.2.0)`, but not with `clang++ (3.6.2)`:
```cpp
#include <iostream>
#include <sstream>
#include "json.hpp"

using json = nlohmann::json;

int main() {
    std::istringstream is {R"({"code":200,"lang":"ru-en","text":["hello"]})"};
    json d;
    
    std::cout << is.str() << std::endl;
    
    is >> d;
    
    std::cout << d.dump() << std::endl;
    
    return 0;
}
```
And also tested such case:
```cpp
    std::string s{"{ \"code\" : 200 }"};
    json d;
    
    d = json::parse(s);
```
My current clang is `version 3.6.2 (tags/RELEASE_362/final)`. I will test it with other version and will tell you if something changes.

**Comment by nlohmann** [comment]
Hi Vladimir,

unfortunately, I cannot reproduce this. I tried with Clang 3.6.2 from Homebrew (package `llvm36`) and could compile and run your code successfully. Which OS are you using?

Cheers,
Niels

**Comment by vpetrigo** [comment]
Niels,

That is a little bit strange. I logged in Linux and this bug with did not take place there.
OS where I was able to do this bug was Windows with MSYS2 package.
And this bug takes place only when I try to serialize json data via `dump()` method.

**Comment by vpetrigo** [comment]
I made some drill and found that clang build in MSYS2 failed when it tried to call `strtold()` function.
![gdb](https://cloud.githubusercontent.com/assets/5689770/8977007/5a40f424-369d-11e5-807d-cd61c426e9eb.png)
It is quite strange because `gcc` and `clang` use the same libraries.

**Comment by maksis** [comment]
I'm having issues with parsing numbers as well, but with MSVC 2015.

Seems like strtold considers the trailing comma to be part of the number, causing endptr to go past m_cursor, so the function get_number() returns NAN.

**Comment by nlohmann** [comment]
Can you provide me with a concrete example?

**Comment by maksis** [comment]
Not yet, because parsing the same string seems to work ok in a clean project...

**Comment by maksis** [comment]
This seems to depend on the current system locale. If I change the number format from Finnish to US and run the program, the comma won't be included in the number. Parsing works correctly in a clean Win32 console project regardless of the locale though.

**Comment by nlohmann** [comment]
I made a change in the string-to-float conversion to make it locale-independent. Could you please check if the issue still exists, @maksis?

**Comment by maksis** [comment]
It seems to work correctly now

**Comment by vpetrigo** [comment]
@nlohmann thank you! Now it works fine.

**Comment by nlohmann** [comment]
However, the build on ApoVeyor fails. :-(

**Comment by vpetrigo** [comment]
As I can see it is because of the quite big precision of returned value. Is it the case to use something like this:
```cpp
long double foo(long double v) {
    std::stringstream ss;
    
    ss << v;
    
    ss.precision(6);
    
    ss >> v;
    
    return v;
}

int main() {
    long double a = 10.1238127638712638;
    
    std::cout << foo(a) << std::endl;
    
    return 0;
}
```

**Comment by nlohmann** [comment]
Unfortunately, this does not help. The issue is the following

```
C:\projects\json\test\unit.cpp(9340): FAILED:
  CHECK( json::parse(json_string)[0].get<double>() == Approx(expected) )
due to unexpected exception with message:
  json_string := [4.9406564584124654e-324]
  expected := 4.94066e-324
  parse error - 4.9406564584124654e-324 is not a number
 
===============================================================================
```

The Windows build fails to parse the number `4.9406564584124654e-324`. See https://ci.appveyor.com/project/nlohmann/json/build/554.

**Comment by nlohmann** [comment]
I reverted the fix. It has some unpredictable behavior, and compatibility to MSVC would break.

**Comment by nlohmann** [comment]
:-(

**Comment by vpetrigo** [comment]
Hello Niels. That issue could be closed, because `Segmentation fault` in MinGW environment with `clang` compiler caused by that issue https://github.com/Alexpux/MINGW-packages/issues/722. Now it is fixed and all works fine.

**Comment by nlohmann** [comment]
Thanks for getting back and telling me! :-)
