### ISSUE TITLE
Serializing OpenCV Mat problem

### ISSUE THREAD

**Issue by ArkadiuszRaj** [nlohmann/json#1070]
Hello,

Trying to serialise Mat object taken from camera

```cpp
        json j;	
        Mat image;
	j["PREVIEW"] = {
		{"GAIN", gain()},
		{"EXPOSURE", exposure()},
		{"IMAGE", image},
	};
```
Of course specialised serializer is prepared, for the sake of clarity only one Mat depth is shown:
```cpp
void to_json(json& j, const Mat& m)  
{
	json array = json::array();

	int cols = m.cols;
	int rows = m.rows;
	int depth = m.depth();
	
	if( m.isContinuous() ) {
		cols *= rows,
		rows = 1;
	}
	switch(depth) {
		case CV_8U:
			for(int row = 0; row < rows; row++) {
				auto vp = m.ptr<uchar>(row);
				for(int col=0; col < cols; col++, vp++)
					array.push_back(*vp); 
			}
			break;
	}
	j = json{
		{"COLS", cols},
		{"ROWS", rows},
		{"TYPE", depth},
		{"DATA", array}
	};
}

```
But code throws:
```
OpenCV(4.0.0-pre) /usr/local/include/opencv2/core/mat.inl.hpp:183: error: (-210:Unsupported format or combination of formats) in function '_OutputArray'
> std::vector<bool> cannot be an output array
```
It seems that somewhere under the hood the Mat type is changed while calling serializer.

But code works when I am explicitly calling serializer by myself:
```cpp
	j["PREVIEW"] = {
		{"GAIN", gain()},
		{"EXPOSURE", exposure()}
	};
       to_json(j["PREVIEW"]["IMAGE"], image) ;
```
Why first version does not?
Additionally, while pushing to array, json dump() (or serializing to stream in general) puts single value per line, making file unreadable. Is there possibility to set  number of values per line?
And can I serialize in such a way 3Mpx image? yes, finally I will put some base64 encoding yet still I need to serialize full image from time to time

**Comment by nlohmann** [comment]
I did not find the time to check the first issue so far. But since the parameter is a const reference, there should not be any change. (Maybe @theodelrieu has an idea)

On the second issue: the `dump()` function either produces a minimal serialization with minimal whitespace, or you can pass an integer to control the indentation depth.

**Comment by theodelrieu** [comment]
What makes the code throw exactly? Could you post the code leading to `to_json` being called?

**Comment by nlohmann** [comment]
@ArkadiuszRaj Could you provide more information?

**Comment by ArkadiuszRaj** [comment]
Hello, exactly as stated in first example.
Including image (OpenCV's Mat object) directly when constructing json fails.
```
        json j;	
        Mat image = Mat::zeros(5, 5, CV_32F);
	j["PREVIEW"] = {
		{"GAIN", 1},
		{"EXPOSURE", 1},
		{"IMAGE", image},
	};
```
But...
Explicitly calling to_json() works as intended, i.e.
```
        j["PREVIEW"] = {
		{"GAIN", 1},
		{"EXPOSURE", 1}
	};
       to_json(j["PREVIEW"]["IMAGE"], image) ;
```

What additional info do you need?

**Comment by theodelrieu** [comment]
Ok I got it, `Mat` is in the `cv` namespace, so your `to_json` function is found via ADL.

Please take a look at the readme section about third party types, you have to specialize `adl_serializer to make it work.

**Comment by ArkadiuszRaj** [comment]
That is true. I have populated other types in ADL but not Mat.
Will do that shortly and it will help this means it was my mistake - I will close this issue.

**Comment by ArkadiuszRaj** [comment]
Thanks!
