### ISSUE TITLE
Feature request :: Better testing for key existance without try/catch

### ISSUE THREAD

**Issue by mlfarrell** [nlohmann/json#1074]
Correct me if I'm wrong, but using a const json obj + .at() + try/catch is the only way safe to test for object key exists.  This seems REALLY brutal compared to the ease of use using the rest of the library

Perhaps there'd be some way to return a bool operator comparable for object gets along the lines of
```
if(auto possibleVal = json["maybeExists"])
{
  //possibleVal exists
}
```

or.. at the very least, a .exists(const std::string &) method would be helpful..

**Comment by nlohmann** [comment]
Here is the documentation for find: https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a89eb3928f57903677051c80534be9cb1.html#a89eb3928f57903677051c80534be9cb1

**Comment by nlohmann** [comment]
@mlfarrell Do you need further assistance?

**Comment by mlfarrell** [comment]
No this will help.  Thanks!
