### ISSUE TITLE
Valid json data not being parsed

### ISSUE THREAD

**Issue by moshe-rabaev** [nlohmann/json#1075]
libc++abi.dylib: terminating with uncaught exception of type nlohmann::detail::parse_error: [json.exception.parse_error.101] parse error at 1: syntax error - unexpected end of input; expected '[', '{', or a literal
Abort trap: 6

I'm parsing sport json data from a website and I get the text and parse it but it throws me the error
above. I validated the data using a tool online, it shows there are no errors so it must be nlohmann::json.

This is the data:
{"fullgameschedule":{"lastUpdatedOn":"2018-04-13 2:44:29 AM","gameentry":[{"id":"33943","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-10-25","time":"10:30PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"101","City":"Golden State","Name":"Warriors","Abbreviation":"GSW"},"location":"Oracle Arena"},{"id":"33956","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-10-27","time":"10:30PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"103","City":"Sacramento","Name":"Kings","Abbreviation":"SAC"},"location":"Sleep Train Arena"},{"id":"33972","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-10-29","time":"8:00PM","awayTeam":{"ID":"110","City":"New Orleans","Name":"Pelicans","Abbreviation":"NOP"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"33977","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-10-30","time":"6:00PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"92","City":"Miami","Name":"Heat","Abbreviation":"MIA"},"location":"American Airlines Arena"},{"id":"33993","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-11-01","time":"8:30PM","awayTeam":{"ID":"98","City":"Utah","Name":"Jazz","Abbreviation":"UTA"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34017","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-11-04","time":"9:00PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"98","City":"Utah","Name":"Jazz","Abbreviation":"UTA"},"location":"Vivint Smart Home Arena"},{"id":"34026","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-11-05","time":"8:30PM","awayTeam":{"ID":"102","City":"Los Angeles","Name":"Clippers","Abbreviation":"LAC"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34054","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-11-09","time":"9:30PM","awayTeam":{"ID":"109","City":"Houston","Name":"Rockets","Abbreviation":"HOU"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34067","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-11-11","time":"8:30PM","awayTeam":{"ID":"88","City":"Detroit","Name":"Pistons","Abbreviation":"DET"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34074","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-11-12","time":"8:00PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"109","City":"Houston","Name":"Rockets","Abbreviation":"HOU"},"location":"Toyota Center"},{"id":"34090","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-11-14","time":"8:30PM","awayTeam":{"ID":"92","City":"Miami","Name":"Heat","Abbreviation":"MIA"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34108","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-11-16","time":"10:30PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"103","City":"Sacramento","Name":"Kings","Abbreviation":"SAC"},"location":"Sleep Train Arena"},{"id":"34122","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-11-18","time":"10:30PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"105","City":"Los Angeles","Name":"Lakers","Abbreviation":"LAL"},"location":"Staples Center"},{"id":"34146","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-11-21","time":"8:30PM","awayTeam":{"ID":"108","City":"Dallas","Name":"Mavericks","Abbreviation":"DAL"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34153","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-11-23","time":"7:00PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"93","City":"Charlotte","Name":"Hornets","Abbreviation":"CHA"},"location":"Spectrum Center"},{"id":"34165","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-11-25","time":"1:00PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"82","City":"Boston","Name":"Celtics","Abbreviation":"BOS"},"location":"TD Garden"},{"id":"34180","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-11-26","time":"7:00PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"94","City":"Washington","Name":"Wizards","Abbreviation":"WAS"},"location":"Verizon Center"},{"id":"34204","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-11-29","time":"8:30PM","awayTeam":{"ID":"95","City":"Orlando","Name":"Magic","Abbreviation":"ORL"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34212","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-11-30","time":"8:30PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"108","City":"Dallas","Name":"Mavericks","Abbreviation":"DAL"},"location":"American Airlines Center"},{"id":"34229","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-12-02","time":"8:30PM","awayTeam":{"ID":"94","City":"Washington","Name":"Wizards","Abbreviation":"WAS"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34249","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-12-05","time":"8:00PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"90","City":"Milwaukee","Name":"Bucks","Abbreviation":"MIL"},"location":"BMO Bradley Harris Center"},{"id":"34259","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-12-06","time":"8:00PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"100","City":"Minnesota","Name":"Timberwolves","Abbreviation":"MIN"},"location":"Target Center"},{"id":"34276","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-12-08","time":"9:30PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"89","City":"Chicago","Name":"Bulls","Abbreviation":"CHI"},"location":"KeyBank Center"},{"id":"34293","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-12-10","time":"8:30PM","awayTeam":{"ID":"84","City":"Brooklyn","Name":"Nets","Abbreviation":"BRO"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34323","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-12-14","time":"9:30PM","awayTeam":{"ID":"82","City":"Boston","Name":"Celtics","Abbreviation":"BOS"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"40235","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-12-15","time":"9:00PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"104","City":"Phoenix","Name":"Suns","Abbreviation":"PHX"},"location":"Talking Stick Resort Arena"},{"id":"34352","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-12-18","time":"7:00PM","awayTeam":{"ID":"110","City":"New Orleans","Name":"Pelicans","Abbreviation":"NOP"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34365","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-12-20","time":"8:00PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"109","City":"Houston","Name":"Rockets","Abbreviation":"HOU"},"location":"Toyota Center"},{"id":"34381","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-12-22","time":"10:30PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"102","City":"Los Angeles","Name":"Clippers","Abbreviation":"LAC"},"location":"Staples Center"},{"id":"34394","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-12-23","time":"10:00PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"97","City":"Portland","Name":"Trail Blazers","Abbreviation":"POR"},"location":"Moda Center"},{"id":"34398","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-12-25","time":"5:00PM","awayTeam":{"ID":"89","City":"Chicago","Name":"Bulls","Abbreviation":"CHI"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34422","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-12-28","time":"8:30PM","awayTeam":{"ID":"104","City":"Phoenix","Name":"Suns","Abbreviation":"PHX"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34439","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2016-12-30","time":"8:30PM","awayTeam":{"ID":"97","City":"Portland","Name":"Trail Blazers","Abbreviation":"POR"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34448","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-01-01","time":"6:00PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"91","City":"Atlanta","Name":"Hawks","Abbreviation":"ATL"},"location":"Philips Arena"},{"id":"34465","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-01-03","time":"8:30PM","awayTeam":{"ID":"81","City":"Toronto","Name":"Raptors","Abbreviation":"TOR"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34483","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-01-05","time":"9:00PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"99","City":"Denver","Name":"Nuggets","Abbreviation":"DEN"},"location":"Pepsi Center"},{"id":"34498","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-01-07","time":"8:30PM","awayTeam":{"ID":"93","City":"Charlotte","Name":"Hornets","Abbreviation":"CHA"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34515","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-01-10","time":"8:30PM","awayTeam":{"ID":"90","City":"Milwaukee","Name":"Bucks","Abbreviation":"MIL"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34529","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-01-12","time":"8:30PM","awayTeam":{"ID":"105","City":"Los Angeles","Name":"Lakers","Abbreviation":"LAL"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34543","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-01-14","time":"6:00PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"104","City":"Phoenix","Name":"Suns","Abbreviation":"PHX"},"location":"Talking Stick Resort Arena"},{"id":"34565","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-01-17","time":"8:30PM","awayTeam":{"ID":"100","City":"Minnesota","Name":"Timberwolves","Abbreviation":"MIN"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34579","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-01-19","time":"8:30PM","awayTeam":{"ID":"99","City":"Denver","Name":"Nuggets","Abbreviation":"DEN"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34597","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-01-21","time":"8:30PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"86","City":"Cleveland","Name":"Cavaliers","Abbreviation":"CLE"},"location":"Quicken Loans Arena"},{"id":"34606","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-01-23","time":"7:30PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"84","City":"Brooklyn","Name":"Nets","Abbreviation":"BRO"},"location":"Barclays Center"},{"id":"34614","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-01-24","time":"7:00PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"81","City":"Toronto","Name":"Raptors","Abbreviation":"TOR"},"location":"Air Canada Center"},{"id":"34641","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-01-27","time":"8:00PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"110","City":"New Orleans","Name":"Pelicans","Abbreviation":"NOP"},"location":"Smoothie King Center"},{"id":"34657","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-01-29","time":"7:00PM","awayTeam":{"ID":"108","City":"Dallas","Name":"Mavericks","Abbreviation":"DAL"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34667","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-01-31","time":"8:30PM","awayTeam":{"ID":"96","City":"Oklahoma City","Name":"Thunder","Abbreviation":"OKL"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34684","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-02-02","time":"8:30PM","awayTeam":{"ID":"85","City":"Philadelphia","Name":"76ers","Abbreviation":"PHI"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34702","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-02-04","time":"9:00PM","awayTeam":{"ID":"99","City":"Denver","Name":"Nuggets","Abbreviation":"DEN"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34717","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-02-06","time":"9:30PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"107","City":"Memphis","Name":"Grizzlies","Abbreviation":"MEM"},"location":"FedEx Forum"},{"id":"34722","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-02-08","time":"7:00PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"85","City":"Philadelphia","Name":"76ers","Abbreviation":"PHI"},"location":"Wells Fargo Center"},{"id":"34741","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-02-10","time":"7:30PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"88","City":"Detroit","Name":"Pistons","Abbreviation":"DET"},"location":"The Palace of Auburn Hills"},{"id":"34757","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-02-12","time":"3:30PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"83","City":"New York","Name":"Knicks","Abbreviation":"NYK"},"location":"Madison Square Garden"},{"id":"34765","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-02-13","time":"7:00PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"87","City":"Indiana","Name":"Pacers","Abbreviation":"IND"},"location":"Bankers Life Fieldhouse"},{"id":"34774","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-02-15","time":"7:00PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"95","City":"Orlando","Name":"Magic","Abbreviation":"ORL"},"location":"Amway Center"},{"id":"34805","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-02-24","time":"10:30PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"102","City":"Los Angeles","Name":"Clippers","Abbreviation":"LAC"},"location":"Staples Center"},{"id":"34814","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-02-26","time":"3:30PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"105","City":"Los Angeles","Name":"Lakers","Abbreviation":"LAL"},"location":"Staples Center"},{"id":"34842","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-03-01","time":"8:30PM","awayTeam":{"ID":"87","City":"Indiana","Name":"Pacers","Abbreviation":"IND"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34857","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-03-03","time":"9:30PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"110","City":"New Orleans","Name":"Pelicans","Abbreviation":"NOP"},"location":"Smoothie King Center"},{"id":"34865","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-03-04","time":"9:00PM","awayTeam":{"ID":"100","City":"Minnesota","Name":"Timberwolves","Abbreviation":"MIN"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34882","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-03-06","time":"8:30PM","awayTeam":{"ID":"109","City":"Houston","Name":"Rockets","Abbreviation":"HOU"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34897","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-03-08","time":"8:30PM","awayTeam":{"ID":"103","City":"Sacramento","Name":"Kings","Abbreviation":"SAC"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34902","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-03-09","time":"8:00PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"96","City":"Oklahoma City","Name":"Thunder","Abbreviation":"OKL"},"location":"Chesapeake Energy Arena"},{"id":"34920","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-03-11","time":"8:30PM","awayTeam":{"ID":"101","City":"Golden State","Name":"Warriors","Abbreviation":"GSW"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34934","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-03-13","time":"8:00PM","awayTeam":{"ID":"91","City":"Atlanta","Name":"Hawks","Abbreviation":"ATL"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34951","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-03-15","time":"8:00PM","awayTeam":{"ID":"97","City":"Portland","Name":"Trail Blazers","Abbreviation":"POR"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34973","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-03-18","time":"9:00PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"107","City":"Memphis","Name":"Grizzlies","Abbreviation":"MEM"},"location":"FedEx Forum"},{"id":"34982","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-03-19","time":"7:00PM","awayTeam":{"ID":"103","City":"Sacramento","Name":"Kings","Abbreviation":"SAC"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"34996","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-03-21","time":"9:30PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"100","City":"Minnesota","Name":"Timberwolves","Abbreviation":"MIN"},"location":"Target Center"},{"id":"35010","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-03-23","time":"8:30PM","awayTeam":{"ID":"107","City":"Memphis","Name":"Grizzlies","Abbreviation":"MEM"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"35025","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-03-25","time":"8:30PM","awayTeam":{"ID":"83","City":"New York","Name":"Knicks","Abbreviation":"NYK"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"35039","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-03-27","time":"8:00PM","awayTeam":{"ID":"86","City":"Cleveland","Name":"Cavaliers","Abbreviation":"CLE"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"35058","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-03-29","time":"9:30PM","awayTeam":{"ID":"101","City":"Golden State","Name":"Warriors","Abbreviation":"GSW"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"35075","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-03-31","time":"8:00PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"96","City":"Oklahoma City","Name":"Thunder","Abbreviation":"OKL"},"location":"Chesapeake Energy Arena"},{"id":"35086","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-04-02","time":"3:30PM","awayTeam":{"ID":"98","City":"Utah","Name":"Jazz","Abbreviation":"UTA"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"35101","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-04-04","time":"8:30PM","awayTeam":{"ID":"107","City":"Memphis","Name":"Grizzlies","Abbreviation":"MEM"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"35110","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-04-05","time":"8:30PM","awayTeam":{"ID":"105","City":"Los Angeles","Name":"Lakers","Abbreviation":"LAL"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"35123","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-04-07","time":"8:30PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"108","City":"Dallas","Name":"Mavericks","Abbreviation":"DAL"},"location":"American Airlines Center"},{"id":"35133","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-04-08","time":"8:30PM","awayTeam":{"ID":"102","City":"Los Angeles","Name":"Clippers","Abbreviation":"LAC"},"homeTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"location":"AT&T Center"},{"id":"35149","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-04-10","time":"10:00PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"97","City":"Portland","Name":"Trail Blazers","Abbreviation":"POR"},"location":"Moda Center"},{"id":"35167","scheduleStatus":"Normal","originalDate":null,"originalTime":null,"delayedOrPostponedReason":null,"date":"2017-04-12","time":"9:00PM","awayTeam":{"ID":"106","City":"San Antonio","Name":"Spurs","Abbreviation":"SAS"},"homeTeam":{"ID":"98","City":"Utah","Name":"Jazz","Abbreviation":"UTA"},"location":"Vivint Smart Home Arena"}]}}

Store the above in a std::string and parse it using:
json::parse(str.begin(), str.end())

- What is the expected behavior?
To parse the data with no errors

- And what is the actual behavior instead?
It throws an exception

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?
It's not a runtime error so this question isn't applicable.

- Did you use a released version of the library or the version from the `develop` branch?
The develop version.

**Comment by nlohmann** [comment]
It seems as if your string contains a null byte in the beginning which is interpreted as end of file. Please make sure the string actually begins with `{`. Note you can directly pass the string to the `parse` function: `json::parse(str);`.

**Comment by moshe-rabaev** [comment]
But I tested it with an online json validator and it said it's good?

**Comment by nlohmann** [comment]
@moshe-rabaev Did you make progress on this issue?

**Comment by moshe-rabaev** [comment]
No, I didn't have time to deal with errors I switched to a csv parser.
Sorry.
