### ISSUE TITLE
Overriding default values?

### ISSUE THREAD

**Issue by simulationcloud** [nlohmann/json#1083]
I have a json file that I read in using nlohmann:json. It contains nested dicts/lists that are configurations specified by users.

Only when a user specifies a value in this file (read in to a json object) should it override the default value, which is specified by another json object. 

My question is: what's the easiest way to replace all the items in one json object with that of another json object, if that item exists in the other json object?

**Comment by nlohmann** [comment]
There is the [`update`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a1cfa9ae5e7c2434cab4cfe69bffffe11.html#a1cfa9ae5e7c2434cab4cfe69bffffe11) function that could be used for this. You could load the default values in a value `v` and then call `v.update(u)` where `u` are the values given by the user.

**Comment by simulationcloud** [comment]
Hi nlohmann, thanks for the help. When I call update, I get this error:
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.312] cannot use update() with array

My default object looks like:
    json jsn =
    {
        "geometry" ,
        {
            "endianness" , "little"
        },
        "nsSolver" ,
	{
            "tol" , 1.0e-8,
            "CFL0" , 1.0,
            "CFL1" , 200.0,
            "CFLsteps" , 100,
            "JacobiSweeps" , 30
        },
        "ransSolver" ,
        {
            "tol" , 1.0e-6,
            "JacobiSweeps" , 30
        },
        "freestream" ,
	{
            "Re" , 1000.0,
            "M" , 0.5,
            "Tref" , 300,
            "alpha" , 0.0,
            "beta" , 0.0
	},
        {
            "boundaries",
            {

            }
       }
    };

It seems it may be complaining about the hierarchy?

**Comment by nlohmann** [comment]
It says that you can only call `update` on an object. Can you provide the code where you call `update`?

**Comment by simulationcloud** [comment]
Here's the whole code:
`
#include "ParseInput.h"
#include "nlohmann/json.hpp"
#include <fstream>
#include <iostream>

json getDefaultConfig(void){
    json jsn =
    {
        "geometry" ,
        {
            "endianness" , "little"
        },
        "nsSolver" ,
        {
            "tol" , 1.0e-8,
            "CFL0" , 1.0,
            "CFL1" , 200.0,
            "CFLsteps" , 100,
            "JacobiSweeps" , 30
        },
        "ransSolver" ,
        {
            "tol" , 1.0e-6,
            "JacobiSweeps" , 30
        },
        "freestream" ,
        {
            "Re" , 1000.0,
            "M" , 0.5,
            "Tref" , 300,
            "alpha" , 0.0,
            "beta" , 0.0
        },
        {
            "boundaries",
            {

            }
       }
    };
    return jsn;
}

json readConfig(std::string file){
    std::ifstream i(file);
    json j;
    i >> j;
    i.close();

    json dflt = getDefaultConfig();
    //dflt.update(j.begin(), j.end());
    for(auto it= j.begin(); it != j.end(); ++it){
        dflt[it.key()].update(it.value());
    }
    return dflt;
}
`

**Comment by nlohmann** [comment]
What would be the content of an input file?

**Comment by simulationcloud** [comment]
The example content of an input file is:
{
    "geometry" :
    {
        "meshName" : "wing.ugrid",
        "endianness" : "little"
    },
    "nsSolver" :
    {
        "tol" : 1.0e-8,
        "CFL0" : 0.1,
        "CFL1" : 500.0,
        "CFLsteps" : 100,
        "JacobiSweeps" : 50
    },
    "ransSolver" :
    {
        "tol" : 1.0e-6,
        "CFL0" : 0.1,
        "CFL1" : 5.0,
        "CFLsteps" : 100,
        "JacobiSweeps" : 50
    },
    "freestream" :
    {
        "Re" : 10000.0,
        "M" : 0.25,
        "Tref" : 300,
        "alpha" : 0.0,
        "beta" : 0.0
    },
    "boundaries" : {
        "1" : {
            "type" : "NoSlipWall"
        },
        "2" : {
            "type" : "SlipWall"
        },
        "3" : {
            "type" : "Freestream"
        }
    }
}

Thanks for the help!

**Comment by nlohmann** [comment]
I assumed how your JSON value should look like.

```cpp
#include <iostream>
#include <fstream>
#include "json.hpp"

using json = nlohmann::json;

json getDefaultConfig(void){
    json jsn = R"(
    {
        "geometry": {
            "endianness": "little"
        },
        "nsSolver": {
            "tol": 1e-08,
            "CFL0": 1.0,
            "CFL1": 200.0,
            "CFLsteps": 100,
            "JacobiSweeps": 30
        },
        "ransSolver": {
            "tol": 1e-06,
            "JacobiSweeps": 30
        },
        "freestream": {
            "Re": 1000.0,
            "M": 0.5,
            "Tref": 300,
            "alpha": 0.0,
            "beta": 0.0
        },
        "boundaries": {}
    })"_json;
    return jsn;
}

json readConfig(std::string file){
    std::ifstream i(file);
    json j;
    i >> j;
    i.close();
    
    json dflt = getDefaultConfig();
    
    //dflt.update(j.begin(), j.end());
    for(auto it= j.begin(); it != j.end(); ++it) {
        dflt[it.key()].update(it.value());
    }
    return dflt;
}

int main() {
    auto j = readConfig("file.json");
    std::cout << std::setw(2) << j << std::endl;
}
```

Output:

```js
{
  "boundaries": {
    "1": {
      "type": "NoSlipWall"
    },
    "2": {
      "type": "SlipWall"
    },
    "3": {
      "type": "Freestream"
    }
  },
  "freestream": {
    "M": 0.25,
    "Re": 10000.0,
    "Tref": 300,
    "alpha": 0.0,
    "beta": 0.0
  },
  "geometry": {
    "endianness": "little",
    "meshName": "wing.ugrid"
  },
  "nsSolver": {
    "CFL0": 0.1,
    "CFL1": 500.0,
    "CFLsteps": 100,
    "JacobiSweeps": 50,
    "tol": 1e-08
  },
  "ransSolver": {
    "CFL0": 0.1,
    "CFL1": 5.0,
    "CFLsteps": 100,
    "JacobiSweeps": 50,
    "tol": 1e-06
  }
}
```
