### ISSUE TITLE
Serializing vector

### ISSUE THREAD

**Issue by yuvalyo** [nlohmann/json#1085]
at this moment i'm working on a little project and i'm trying to serialize a vector

the current code is:

```cpp
std::string JsonResponsePacketSerializer::serializeResponse(HighscoreResponse response)
{
	json j;
	j["status"] = response.status;
	j["highscores"] = {};
	for (auto iter = response.highscores.begin(); iter != response.highscores.end(); ++iter)
	{
		j["highscores"].push_back(*iter);
	}


	return j.dump();
}
```

as you can see in the struct the "highscores" is a vector
but i'm gettting all kind of erros such as:
1) could not find to_json() method in T's namespace
2)forcing MSVC stacktrace to show which T we're talking about.

thanks for your help 👍

**Comment by nlohmann** [comment]
Please have a look at this section of the README: https://github.com/nlohmann/json/blob/develop/README.md#arbitrary-types-conversions

**Comment by yuvalyo** [comment]
so you say i just need to do like:

json j;
j["highscores"] = response.highscores;

?

**Comment by nlohmann** [comment]
You need to provide a `to_json` function.

**Comment by yuvalyo** [comment]
std::string JsonResponsePacketSerializer::serializeResponse(HighscoreResponse response)
{
	json j = json{ { "status", response.status },{ "highscores", response.highscores }};
	return j.dump();
}
still does not work

**Comment by nlohmann** [comment]
Can you provide the code of your `to_json` function?

**Comment by yuvalyo** [comment]
void to_json(json& j, const HighscoreResponse& response)
{
	j = json{ { "status", response.status },{ "highscores", response.highscores }};
}

this is my to_json function but i need to know just hot to serialize the vector because from what i understood you can only convert normal types and not user_defined

**Comment by theodelrieu** [comment]
Is the `to_json` function in the same namespace than `HighscoreResponse`?

If so, it means that some member of `HighscoreResponse` is a user defined type which also need a `to_json` function

**Comment by yuvalyo** [comment]
i just need to know how do you convert a std::vector<string> to json

**Comment by nlohmann** [comment]
Given `std::vector<Foo>`, then it is sufficient to provide a `to_json` function for type `Foo` - the library then knows how to process a vector of `Foo`.

**Comment by nlohmann** [comment]
Do you need further assistance on this?
