### ISSUE TITLE
[Question] how to use nlohmann/json in c++?

### ISSUE THREAD

**Issue by boddumanohar** [nlohmann/json#1088]
I am working on an application where two process exchange data through shared memory. So instead of using structs to pack the data, I choose to use JSON so that I won't face any issues due to compilers.

My sender side is written in C++14 and the receiver side is written in C

On the reciver side, which is C, how do I read  the json data?

I really appreciate the help.

**Comment by nlohmann** [comment]
You want to know how to access a C++ data structure in C?

**Comment by boddumanohar** [comment]
Do you know of any other library that can fulfil my need?

**Comment by nlohmann** [comment]
Sorry, I do not. Maybe check on http://json.org which C libraries are suitable.

**Comment by boddumanohar** [comment]
Thanks a ton @nlohmann

**Comment by pboettch** [comment]
You could, theoretically, write a C-wrapper around this library. Losing basically every flexibility gained by using modern C++. But, with the advantage, that you could share the data-structure (and the same allocated memory) between C and C++ without reparsing JSON several times within the same application.

**Comment by nlohmann** [comment]
The library has a function `dump()` that serializes to a `std::string`. That string is returned and note stored in the library (if this is what you mean with "preserves the serialization").

**Comment by boddumanohar** [comment]
So serialisation means putting all the data in the form of plain old
string? So that it can be transmitted easily?

**Comment by nlohmann** [comment]
I guess so.
