### ISSUE TITLE
Serialize a list of class objects with json

### ISSUE THREAD

**Issue by AncaMRG** [nlohmann/json#1096]
Hello,
I want to serialize a list which contains a class objects. How can I do that using json. For a list of regular types I understand, but when I try to use json j_list(listName), and the listName is a list of objects I receive some errors from to_json method and 'force_msvc_stacktrace'.

This is the code.

       std::list<Student>studentList;

// populate studentList with objects of Student class

	string filename = "StudentList.json";
	std::ofstream output(filename, std::ofstream::out);
	json js_list(studentList);
	output << js_list;
	output.close();

What should I do to I make this work? 
Thank you! :D

**Comment by gregmarr** [comment]
If you read the errors, it should tell you what you need to do.

**Comment by AncaMRG** [comment]
Thank you! :D

**Comment by nlohmann** [comment]
@AncaMRG Do you need further assistance or can I close this issue?

**Comment by AncaMRG** [comment]
You can close the issue. Thank you! :D
    On Wednesday, 23 May 2018, 08:42:04 EEST, Niels Lohmann <notifications@github.com> wrote:  
 
 
@AncaMRG Do you need further assistance or can I close this issue?
