### ISSUE TITLE
Deserializing std::map

### ISSUE THREAD

**Issue by RolandasV** [nlohmann/json#1100]
- What is the issue you have?
When trying to deserialize a std::map which has a int/Enum as a key I'm getting compilation error.
Error	C2166	l-value specifies const object

When i try to deserialize a std::map with a key as a string for example, it compiles fine.

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?
Serialize a std::map having int/enum as a key. Try to deserialize it.

`json.at(_materialTypeByFaceSelectionJson).get<map<MaterialTypeEnum, FaceSelectionEnum>>();`

- What is the expected behavior?
It should compile.

- And what is the actual behavior instead?
It doesn't.

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?
I'm using windows 10 and Visual Studio 2017.

- Did you use a released version of the library or the version from the `develop` branch?
I'm using released version.

**Comment by theodelrieu** [comment]
There is an open PR to provide this feature: #1089 

Could you try this commit and tell me if it fixes your issue?

**Comment by giumas** [comment]
@nlohmann: since I need this feature, I am wondering if the develop branch is reliable to use it (unless 3.1.3 is coming).

**Comment by nlohmann** [comment]
I hope to release 3.1.3 before the end of July.

**Comment by giumas** [comment]
If one of the map pairs (e.g., `std::pair<int64_t, double>`) has `std::nan`, it becomes a `null` in the written json. 
If I read it back as a map, I get: `[json.exception.type_error.302] type must be number, but is null`.
What is the suggested approach in such a case? Should I iterate through each pair? If yes, how?

**Comment by giumas** [comment]
@nlohmann do you prefer that I move the described issue in a stand-alone ticket?

**Comment by nlohmann** [comment]
Yes, please.
