### ISSUE TITLE
Type checking during compile

### ISSUE THREAD

**Issue by trivigy** [nlohmann/json#1103]
Sorry for the naive question in case this is really rudimentary but is there a way to type check the json instance during compile time? The basic use case in my situation is that I am passing a json object as a function argument and I want to ensure that only `json::object` is passed. Was hoping it could be check done during compile time.

**Comment by nlohmann** [comment]
I am afraid this is not possible.

**Comment by OvermindDL1** [comment]
Well, it 'is' possible in C++98 and higher, just will slow compilation a great deal (though not as much in C++14 and higher), and will require a JSON parser programmed via templates (which is entirely doable, Boost even has such a library for making such compile-time parsers), and I don't know of any off hand that are already made...

If you feel up for making such a library @trivigy then this is a popular link for parsing strings at compile-time first-steps:  https://akrzemi1.wordpress.com/2011/05/11/parsing-strings-at-compile-time-part-i/

**Comment by trivigy** [comment]
If I wanted to use another library I wouldn't post it here. But thanks for
the recommendation. I was able to get away without depending on that check.
So all good with using just `json ()` type.
