### ISSUE TITLE
 i want to learn json

### ISSUE THREAD

**Issue by wenhuancai** [nlohmann/json#1104]
Hi, I want to learn about this json library.Json [key] = values.I think it's a cool thing to do, but I don't know how to read the source code.Is there any good documentation for me to join this project quickly?

**Comment by nlohmann** [comment]
Documentation can be found here:
- https://nlohmann.github.io/json/
- https://github.com/nlohmann/json/blob/develop/README.md

**Comment by nlohmann** [comment]
@wenhuancai Can we close this issue?

**Comment by nlohmann** [comment]
I don't think the project is suitable to actually learn programming C++. You should search for tutorials instead.
