### ISSUE TITLE
Get keys from json object

### ISSUE THREAD

**Issue by Radmir2015** [nlohmann/json#1107]
Is it possible to get all keys from json object (like on picture)?
![screenshot_181](https://user-images.githubusercontent.com/21173382/40528398-96257f0e-5ff9-11e8-9f8d-2f20e9fc3057.png)
![screenshot_182](https://user-images.githubusercontent.com/21173382/40528399-9657a2b8-5ff9-11e8-9ff8-67eb4d084421.png)

**Comment by nlohmann** [comment]
You may want to have a look at the [`items()`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_afe3e137ace692efa08590d8df40f58dd.html#afe3e137ace692efa08590d8df40f58dd) function.

**Comment by nlohmann** [comment]
@Radmir2015 Can we close this issue or do you need further assistance?

**Comment by Radmir2015** [comment]
Yes, of course. Thanks.

**Comment by arpit279** [comment]
when I am trying to use the item method, I am facing this error:-
‘using json = using json = class nlohmann::basic_json<> {aka class nlohmann::basic_json<>}’ has no member named ‘items’

**Comment by nlohmann** [comment]
Which version are you using? `items` was only introduced in a later version. Before, the function was called `iterator_proxy`.

**Comment by arpit279** [comment]
what version are you asking ? if the library then it is **2.1.1-1.1**, and does the function iterator_proxy works same as **items** ?

**Comment by nlohmann** [comment]
Basically yes, but you should consider updating the library - there have been multiple bug fixes and performance improvements since.

**Comment by arpit279** [comment]
Can you please guide me in updating, Since I am new to this things, I am still learning.
I tried the **sudo apt-get install --only-upgrade nlohmann-json-dev** command, but it shows already a newest version. please help.

**Comment by arpit279** [comment]
Thank you so much,
Now my code is working as expected.
