### ISSUE TITLE
How can I write from_json for a complex datatype that is not default constructible?

### ISSUE THREAD

**Issue by shikhartanwar** [nlohmann/json#1115]
Hi. This is more of a question rather than a issue. 

I have a requirement where I need to create objects from serialized json (serialized using this library only) but those types are not default constructible. I went through the section [regarding get() for non-default constructible/non-copyable types](https://github.com/nlohmann/json#how-can-i-use-get-for-non-default-constructiblenon-copyable-types) but wasn't sure as to how am I supposed to use it for a complex datatype.

Can you please help?

**Comment by theodelrieu** [comment]
Do you have a small piece of code? What did you try?

Basically you have to open up the `namespace nlohmann` in your own code, as shown in the section you linked:

```cpp
namespace mylib
{
struct complex_type
{
  complex_type() = delete;
};
}

namespace nlohmann
{
template <>
struct adl_serializer<mylib::complex_type>
{
  // ... proceed as shown in the section
};
}
```

**Comment by shikhartanwar** [comment]
Thanks a lot. I was able to get it to work.
