### ISSUE TITLE
Disable implicit conversions from json to std::initializer_list<T> for any T

### ISSUE THREAD

**Issue by tlemo** [nlohmann/json#1118]
This is a cherry pick for from #1116: I suspect most ambiguities related to implicit conversions from json to standard containers (and not only) can be avoided by expanding the SFINAE around basic_json::operator ValueType() to explicitly exclude conversions to any std::initializer_list specialization. 

It should be an quick, easy and safe fix (even if it doesn't fully address the full range of issues described in #1116). I'd be happy to prepare a patch if it helps.

**Comment by nlohmann** [comment]
Can you give an example for this?

**Comment by tlemo** [comment]
The code snippet in #1116 demonstrates the issue. The assignment case can be mitigated with SFINAE in most cases (for the specific vector case we can't "fix" the constructor case since vector has the "explicit vector(size_t)" ...)

```
json j = { 1, 2, 3 };

// works as advertised
std::vector<float> v = j;

// error: use of overloaded operator '=' is ambiguous (with operand types 'vector<float>' and 'json' (aka 'basic_json<>'))
// note: candidate functions:
//  operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
//  operator=(const vector& __x);
//  operator=(initializer_list<value_type> __l)
v = j;
```

**Comment by theodelrieu** [comment]
I'm quite against such a change, even if `std::initializer_list` with values cannot be constructed without braces.

The change would fix vector I agree, but it's a coincidence that there is no other `operator=`, otherwise it would not fix anything.

Especially if we decide to follow #958, this will make it harder for users to transition to `get()` everywhere in their codebase.

I have a huge bias because of #958 though :p

**Comment by tlemo** [comment]
Correct, this would be a band aid,  not a complete and universal solution. But it should be an effective band aid for the common cases (standard containers)

Is your concern that by mitigating some of the practical issues with implicit conversions we'd weaken the rationale for a more radical change (like the ones proposed in #958 and #1116) ?

**Comment by theodelrieu** [comment]
>Is your concern that by mitigating some of the practical issues with implicit conversions we'd weaken the rationale for a more radical change?

Exactly.

That's not my decision to make however, I think I have expressed my opinion enough already, so I'll follow along the final decision anyway.
