### ISSUE TITLE
clang compiler: error : unknown type name 'not'

### ISSUE THREAD

**Issue by d223chen** [nlohmann/json#1119]
I am building json.hpp with a project using the Clang/LLVM toolset in Visual Studio 2017 Community Edition (version 15.7.2)and getting these errors (and then some):

                  1>------ Build started: Project: SampleProject, Configuration: Debug Win32 ------
                  1>clang-cl.exe : warning : argument unused during compilation: '/ZI' [-Wunused-command-line-argument]
                  1>clang-cl.exe : warning : argument unused during compilation: '/Gm' [-Wunused-command-line-argument]
                  1>In file included from Source.cpp:2:
                  1>C:\Program Files\vcpkg\installed\x86-windows\include\nlohmann\json.hpp(322,66): error : unknown type name 'not'
                  1>template<class B> struct negation : std::integral_constant<bool, not B::value> {};
                  1>                                                                 ^
                  1>C:\Program Files\vcpkg\installed\x86-windows\include\nlohmann\json.hpp(322,80): error : expected class name
                  1>template<class B> struct negation : std::integral_constant<bool, not B::value> {};

(and many more errors).

Here is the compiler version:

            C:\Program Files\LLVM\bin>clang-cl.exe --version
            clang version 6.0.0 (tags/RELEASE_600/final)
            Target: x86_64-pc-windows-msvc
            Thread model: posix
            InstalledDir: C:\Program Files\LLVM\bin

I highly suspect this is a compiler issue. I successfully compiled the project when using the Microsoft Visual C++ compiler (MSVC) version 19.14.

**Comment by d223chen** [comment]
For reference, I issued a bug report [here](https://bugs.llvm.org/show_bug.cgi?id=37700).

**Comment by nlohmann** [comment]
Thanks for your effort!

**Comment by nlohmann** [comment]
It's a pity that there has not been any reaction yet.

**Comment by nlohmann** [comment]
To be fixed with #2259.
