### ISSUE TITLE
How to use a json::iterator dereferenced value in code?

### ISSUE THREAD

**Issue by d223chen** [nlohmann/json#1120]
I am trying to do something like this - it involves taking a json::iterator through some json objects, and getting their keys and values for entries. I want to use the values (i.e. it.value() and mit.value()) as arguments to other functions...

        json result;
        json inboundMessage = ...;//determined at runtime
        json savedMessage = ...; //determined at runtime
        for (json::iterator it = inboundMessage.begin(), mit = savedMessage.begin(); it != inboundMessage.end() && mit != savedMessage.end(); ++it, ++mit) {
		json pair;
		pair.emplace_back("log", it.value());
	        pair.emplace_back("data", mit.value());
		result.emplace_back(it.key(), pair);
        }
        return result;

When I build, I get the following error:            
` 'nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>::basic_json(nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer> &&) noexcept': cannot convert argument 1 from 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' to 'std::initializer_list<nlohmann::detail::json_ref<nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>'	`

What is the correct way to access the value referenced by an iterator such that the value can be used by code?

**Comment by gregmarr** [comment]
You want to use `json.items()` and not the `json` object itself for iteration.

    auto inbound = inboundMessage.items();
    auto saved = savedMessage.items();

    for (auto it = inbound.begin(), ...

**Comment by d223chen** [comment]
I still get the same error when I do that...

**Comment by gregmarr** [comment]
Which line is giving you the error?

**Comment by d223chen** [comment]
pair.emplace_back("log", it.value());
        pair.emplace_back("data", mit.value());
	result.emplace_back(it.key(), pair);

Actually, the error is technically at line 920 in file "xmemory0". The line looks like this:

	template<class _Objty,
		class... _Types>
		static void construct(_Alloc&, _Objty * const _Ptr, _Types&&... _Args)
		{	// construct _Objty(_Types...) at _Ptr
		::new (const_cast<void *>(static_cast<const volatile void *>(_Ptr)))
			_Objty(_STD forward<_Types>(_Args)...);
		}

**Comment by gregmarr** [comment]
Ah, you're inserting in a map, you want `emplace`, not `emplace_back`.  The latter is only for arrays.

**Comment by d223chen** [comment]
That solved it. Thank you!

I wonder if its possible to throw better errors in a situation like this. It was not obvious to me that something like this could be the issue, and I thought the error was something else entirely...

**Comment by gregmarr** [comment]
I don't think it's possible, as the error is that by using `emplace_back` you're essentially passing these parameters to the constructor of a `json` object through `std::vector<json>::emplace_back()`.

**Comment by d223chen** [comment]
I still run into this kind of error message to this day when using this library, and its very difficult to debug because it does not tell me exactly which line of C++ code is causing it, rather it still just redirects the error to some line in xmemory0.

If its impossible to improve this kind of error checking then I guess I will have to live with it...
