### ISSUE TITLE
can't not parse "\\“ string

### ISSUE THREAD

**Issue by wony-zheng** [nlohmann/json#1123]
`json::parse("{\"c\": \"a\\a\"}")` throw std::invalid_argument, msg: parse error - unexpected '"'

**Comment by nlohmann** [comment]
Please try with the most recent released version - the error message should be more verbose then.

**Comment by abolz** [comment]
The error is expected: The string is first processed by the compiler to "`{"c": "a\a"}`" and `a` is not a valid escaped character according to the JSON grammar.

If you want a `\` in the string literal you need to escape it twice: Once for the compiler and once for the JSON parser. This should work: `json::parse("{\"c\": \"a\\\\a\"}")` or `json::parse(R"({"c": "a\\a"})")`

**Comment by nlohmann** [comment]
The most recent version has this diagnostic message:

```
[json.exception.parse_error.101] parse error at 10: syntax error - invalid string: forbidden character after backslash; last read: '"a\a'
```

I hope this makes the syntax error more clear.

**Comment by nlohmann** [comment]
@wony-zheng Do you need further assistance on this?
