### ISSUE TITLE
Add a way to get a key reference from the iterator

### ISSUE THREAD

**Issue by GTValentine** [nlohmann/json#1127]
I may be missing something but I think when I am iterating over all keys in an object I have no way to access they key without actually copying them:

```cpp
bool foo(const std::string&)
{
...
}

json j = {...};
for (auto it = j.begin(); it != j.end(); ++it)
{
	//it.key() copies the entire std::string
	if(foo(it.key()))
	{
		bar(it.value());
	}
}
```

If my keys are large strings, I'd like to avoid copying them for perf reasons.

**Comment by nlohmann** [comment]
You can try the `items` function: https://nlohmann.github.io/json/classnlohmann_1_1basic__json_afe3e137ace692efa08590d8df40f58dd.html#afe3e137ace692efa08590d8df40f58dd

**Comment by nlohmann** [comment]
Since #1098, you can access keys by reference. Note this has not been released yet.

**Comment by GTValentine** [comment]
Oh cool. Can't wait to have it in master.
