### ISSUE TITLE
dump() can't handle umlauts

### ISSUE THREAD

**Issue by AndreasMartin72** [nlohmann/json#1131]
This small example runs into an exception ("invalid UTF-8 byte at index..."):

```
    nlohmann::json test;
    test["Value"] = "Für";
    cout << test.dump().c_str();
```

**Comment by nlohmann** [comment]
The library supports UTF-8. Please make sure your compiler is correctly configured.

**Comment by AndreasMartin72** [comment]
You don't get an exception with my code example?
What exactly do I have to check?

**Comment by nlohmann** [comment]
Which compiler do you use? Is the source file UTF8-encoded?

**Comment by AndreasMartin72** [comment]
Ah, ok. I have to do the latin to utf8 conversion by myself. The native ASCII string is the problem.
(My strings are read from a native ASCII file, latin encoded)
Does your library serves some conversion from latin?
