### ISSUE TITLE
Compile error. Unable convert form nullptr to nullptr&&

### ISSUE THREAD

**Issue by kirill-782** [nlohmann/json#1135]
I can not compile json.hpp.

> error C2664: "BasicJsonType *nlohmann::detail::json_sax_dom_parser<BasicJsonType>::handle_value<nullptr>(Value &&)": невозможно преобразовать аргумент 1 из "nullptr" в "nullptr &&"

problem code: 
```
    bool null() override
    {
        handle_value(nullptr); 
        return true;
    }
```

**Comment by nlohmann** [comment]
What code do you try to compile? Which compiler are you using? What version of the library are you using?

**Comment by kirill-782** [comment]
visual studio 2015 (vc140). library downloaded from develop branch (last version)

```
#include <nlohmann/json.hpp> // single include

using namespace std;

using json = nlohmann::json;

int main( void )
{
	json j = "{ \"happy\": true, \"pi\": 3.141 }"_json;
	return 0;
}
```

**Comment by nlohmann** [comment]
Is that compiler supported? From the README: Microsoft Visual C++ 2015 / Build Tools 14.0.25123.0 (and possibly later)

**Comment by kirill-782** [comment]
Microsoft Visual Studio Enterprise 2015
Версия 14.0.25431.01 Update 3
Microsoft .NET Framework
Версия 4.7.03056

**Comment by nlohmann** [comment]
Could you try to remove `using namespace std`?

**Comment by kirill-782** [comment]
Nothing has changed

**Comment by nlohmann** [comment]
That is strange as we use MSVC 2015 with AppVeyor in your CI suite.

**Comment by kirill-782** [comment]
Can any macro be defined? Or any compilation option? Can you sln the file?

**Comment by nlohmann** [comment]
Maybe related: #987.

**Comment by nlohmann** [comment]
> Can any macro be defined? Or any compilation option? Can you sln the file?

What do you mean by that?

**Comment by kirill-782** [comment]
I'm interested in Build Tools. 140 or 141?

**Comment by nlohmann** [comment]
AppVeyor uses Microsoft (R) Build Engine version 14.0.25420.1, MSVC 19.0.24215.1. What do you mean?

**Comment by kirill-782** [comment]
It is very strange.

**Comment by nlohmann** [comment]
I don't know how to proceed here. To summarize, it seems as if you are using the exact compiler version as we are doing on AppVeyor. Could you make sure that you run the exact same commands as [here](https://github.com/nlohmann/json/blob/develop/appveyor.yml#L52)?

**Comment by kirill-782** [comment]
The problem was solved by disabling the CRL in the compiler settings

**Comment by nlohmann** [comment]
Thanks for checking back!
