### ISSUE TITLE
How do I count number of objects in array?

### ISSUE THREAD

**Issue by zavodnyrichard** [nlohmann/json#1137]
Hi. I wanna count number of objects in array. For example: **jsonObj["array"]** is object that store another objects. I can access them by **jsonObj["array"][0]["something"]**, **jsonObj["array"][1]["something"]**, **jsonObj["array"][2]["something"]**, and so on. So how do I count number of objects in **jsonObj["array"]**?

Thank you. :)

**Comment by nlohmann** [comment]
How about `size()`?

**Comment by zavodnyrichard** [comment]
Oh yeah... Sorry. I'm blind eh.

**Comment by Sneirox** [comment]
Size () - is not length of Array, it's just count of all elements in whole array

**Comment by nlohmann** [comment]
See https://json.nlohmann.me/api/basic_json/size/#return-value
