### ISSUE TITLE
 could not find to_json() method in T's namespace

### ISSUE THREAD

**Issue by AistisT** [nlohmann/json#1140]
```
nlohmann::json subscriber;	
subscriber["Name"] = &callerName;
subscriber["SubscribeTopic"] = topicToSubscribe;
subscriber["CallBackTopic"] = callBackTopic;
	

```

and
 ```
nlohmann::json subscriber = {
		{ "Name", &callerName },
		{ "SubscribeTopic", &topicToSubscribe },
		{ "CallBackTopic", &callBackTopic },
	};
```
Both cause the error

Vs 2017, latest release

I seem to be unable to create json object, I've read through documentation like 20 times and there is nothing else that has been mentioned about it.

**Comment by nlohmann** [comment]
The error message indicates that you try to convert a type to JSON that the library does not know. In that case, it searches for a `to_json` method on the type's namespace, see https://github.com/nlohmann/json#arbitrary-types-conversions.

In your case, the problem seems to be line

```cpp
subscriber["Name"] = &callerName;
```

What is the type of `&callerName`?

**Comment by AistisT** [comment]
std::string pointer,  I realized that I have been trying to access it by reference, that was causing the issue, cheers for pointing my attention to it!

**Comment by nlohmann** [comment]
Cool! Does it work now?

**Comment by AistisT** [comment]
It does work now, but how should I deal with Unicode characters? Is it possible to use std::wstring ?  I would really like to avoid having to get another library and trying to figure how to encode strings in utf-8

**Comment by AistisT** [comment]
Nvm seems c++11 introduced easy way to encode strings to utf-8

`std::string msg = u8" महसुस Aistis message €";`

Feel free to close this now! 👍

**Comment by OvermindDL1** [comment]
> Nvm seems c++11 introduced easy way to encode strings to utf-8

That still depends on the compiler encoding the source text properly however.

**Comment by nlohmann** [comment]
Indeed the library only supports UTF-8, though you may parse from std::wstring (in the latest develop version). But @OvermindDL1 is right - your compiler must make sure that string literals are actually encoded with UTF-8.
