### ISSUE TITLE
Does json support converting an instance of a struct into json string?

### ISSUE THREAD

**Issue by GingerMoon** [nlohmann/json#1143]
Does json support converting an instance of a struct into json string?
And if yes, can the order of the fields be kept in the order of the declaration in the struct?
For example,
struct S {
int Z;
int A;
};
S s = {1,2};

I tried to read the doc but not able to find the answer.
The expect json string is:
{"Z":1, "A":2}

Any sample code would be much appreciated.

Some background information for this question:
I am developing a Qt client for a blockchain. I need to sign for a transaction struct json. But the json fields are in the order of alphabet, however on the server side, golang json packeg, the order is the declaration order of the struct fields. Hence the verification for the signature failed.

**Comment by nlohmann** [comment]
Do you really mean reapidjson?

**Comment by GingerMoon** [comment]
Thank you for the quick response and sorry for the typo.
I really mean nlohmann/json :) .
I did ask a similar question for rapidjson...
https://github.com/Tencent/rapidjson/issues/1299

**Comment by nlohmann** [comment]
From the README:

> - By default, the library does not preserve the **insertion order of object elements**. This is standards-compliant, as the [JSON standard](https://tools.ietf.org/html/rfc7159.html) defines objects as "an unordered collection of zero or more name/value pairs". If you do want to preserve the insertion order, you can specialize the object type with containers like [`tsl::ordered_map`](https://github.com/Tessil/ordered-map) ([integration](https://github.com/nlohmann/json/issues/546#issuecomment-304447518)) or [`nlohmann::fifo_map`](https://github.com/nlohmann/fifo_map) ([integration](https://github.com/nlohmann/json/issues/485#issuecomment-333652309)).

**Comment by nlohmann** [comment]
What I mean is that the library does support serializing user-defined types to JSON (https://github.com/nlohmann/json#arbitrary-types-conversions), but does not preserve the order of object keys by default. This can be achieved by the containers linked in the README snippet above.

**Comment by GingerMoon** [comment]
I did get similar information via searching, and I also remember that you mentioned in one of your reply that you will not recommend fifo_map.
It seemed that I missed these important information. Thank you very much!
I am really appreciated!

**Comment by nlohmann** [comment]
Using the fifo_map header is not really tested and there may be issues with that. But the more people try it, the better we know ;-)

**Comment by nlohmann** [comment]
If you experience any issues, please let me know!
