### ISSUE TITLE
Is it possible to dump a two-dimensional array to "[[null],[1,2,3]]"?

### ISSUE THREAD

**Issue by GingerMoon** [nlohmann/json#1146]
Is it possible to dump a two-dimensional array to "[[null],[1,2,3]]"?

I tried the code below:
   my_json j;
    std::vector<int> a[2];
    std::vector<int> a1;
    a1.push_back(1);
    a[1] = a1;
    j["a"] = a;

The output is:
{"a":[[],[1]]}
Is it possible to dump a two-dimensional array to "[[null],[1,2,3]]"?

**Comment by nlohmann** [comment]
You could try:

```cpp
// direct approach
json j = { {nullptr}, {1,2,3} };

// indirect approach
json j_array, j_array1, j_array2;
j_array1.push_back(nullptr);
j_array2.push_back(1);
j_array2.push_back(2);
j_array2.push_back(3);
j_array.push_back(j_array1);
j_array.push_back(j_array2);
```

I haven't run the code, but `j` and `j_array` should both serialize to `[[null],[1,2,3]]`.

**Comment by GingerMoon** [comment]
Thanks a lot, the output below is what I am expecting:
[[null],[1,2,3]]
[[null],[1,2,3]]
[null]
[1,2,3]
************
    // direct approach
    json j = { { nullptr },{ 1,2,3 } };

    // indirect approach
    json j_array, j_array1, j_array2;
    j_array1.push_back(nullptr);
    j_array2.push_back(1);
    j_array2.push_back(2);
    j_array2.push_back(3);
    j_array.push_back(j_array1);
    j_array.push_back(j_array2);

    std::cout << j.dump() << std::endl;
    std::cout << j_array.dump() << std::endl;
    std::cout << j_array1.dump() << std::endl;
    std::cout << j_array2.dump() << std::endl;
