### ISSUE TITLE
cocoapod integration

### ISSUE THREAD

**Issue by graph** [nlohmann/json#1148]
Is this ok? If I do it can I push to this repo? I want to be able to more easily use this library on ios. Perhaps under the pod `njson`.

**Comment by nlohmann** [comment]
That would be great, but I'd rather have a name like `nlohmann_json`, because this name is used with other package managers. See https://github.com/nlohmann/json#integration for an overview.

**Comment by graph** [comment]
and published https://cocoapods.org/pods/nlohmann_json

It's easy to add additional authors, for now I just put you. I didn't put your email. If you want me to update the list in anyway let me know. It's also very easy to do so yourself in the podspec file. The programming language of the podspec is ruby.

**Comment by nlohmann** [comment]
Thanks for taking care of this! Is PR #1150 needed after all if the library is already published?

**Comment by graph** [comment]
your welcome. Theoretically PR is not needed. But it's good to keep all integration files in the main repo.

**Comment by nlohmann** [comment]
I'd rather have the file in a repo controlled by the package maintainer (which I do not want to be). I cannot provide support for tools I do not use.

**Comment by graph** [comment]
I understand no worries. It will probably be good to add to your readme something like

If you are using cocoapods, you can use the unofficial pod by adding `pod "nlohmann_json", '~>3.1.2'` to your podfile.

**Comment by nlohmann** [comment]
Alright. Do you have a repository where you keep the pod? Then I can link it if someone has issues. Furthermore, I would need such an issue tracker to notify you about new releases.

**Comment by graph** [comment]
Happy Canada day. I'll set something up next week. In the mean time I will enjoy long weekend :)

**Comment by nlohmann** [comment]
I would also need a small running example (something demonstrating how to compile a small program using the library) for the pod.

**Comment by graph** [comment]
Ok I added a sample project too. I have set it up on my bitbucket, as [nlohmann_json-cocoapod](https://bitbucket.org/benman/nlohmann_json-cocoapod/src/master/). People can submit issues there in the [issue tracker](https://bitbucket.org/benman/nlohmann_json-cocoapod/issues?status=new&status=open)

**Comment by nlohmann** [comment]
Thanks a lot!
