### ISSUE TITLE
Parse throwing errors

### ISSUE THREAD

**Issue by AistisT** [nlohmann/json#1149]
So parse seem to work fine, if I load dll from my tester project, everything works fine, if I load exactly same dll with same data through windows services I get lots of errors  like "Unhandled exception at 0x75000132 in xxxxxxx.exe: Microsoft C++ exception: nlohmann::detail::parse_error at memory location 0x0293A868. occurred"

This is triggered by 
```
bool parse_error(std::size_t, const std::string&,
				const detail::exception& ex) override
			{
				errored = true;
				if (allow_exceptions)
				{
					// determine the proper exception type from the id
					switch ((ex.id / 100) % 100)
					{
					case 1:
						JSON_THROW(*reinterpret_cast<const detail::parse_error*>(&ex));
					case 2:
						JSON_THROW(*reinterpret_cast<const detail::invalid_iterator*>(&ex));  // LCOV_EXCL_LINE
					case 3:
						JSON_THROW(*reinterpret_cast<const detail::type_error*>(&ex));  // LCOV_EXCL_LINE
					case 4:
						JSON_THROW(*reinterpret_cast<const detail::out_of_range*>(&ex));
					case 5:
						JSON_THROW(*reinterpret_cast<const detail::other_error*>(&ex));  // LCOV_EXCL_LINE
					default:
						assert(false);  // LCOV_EXCL_LINE
					}
				}
				return false;
			}
```

at line 3624 of json.hpp, I am using hardcoded data defined right in dll at this moment, to rule out any memory issues, but it's not helping. It just dies when it's trying to parse std::wstring.

```
	static int SendToAgent(std::wstring & data, LPCWSTR LogType)
	{
		
		if (mqttHandlerGlobal.IsAgentOnline())
		{	
			//_asm {int 3}
			auto string = std::wstring(LogType);
			auto datatype = nlohmann::json::parse(string);
			auto parsedData = nlohmann::json::parse(data);
			nlohmann::json messageJson =
			{
				{ "DataType", datatype },
				{ "Data", parsedData },
			};
			printf("Message Sent\n");
			auto message = messageJson.dump();
			return mqttHandlerGlobal.MqttSend(message, *mqttHandlerGlobal.GetTopic());
		}
		return 0;
	}
```

called by 
```

std::wstring test = L"Test";
SendToAgent(test, L"TestType");
```
I've really got no clue what's causing it, apart that DLL with parsing code is being loaded by a different project that runs under windows service its exactly the same.

**Comment by AistisT** [comment]
this is with latest dev version

**Comment by nlohmann** [comment]
When you pass `Test` as `data` to `SendToAgent` and there call `json::parse(data)`, then a parse error should occur, because `Test` is not valid JSON.

**Comment by AistisT** [comment]
but it works if I run the same in tester loader, and couple days ago you told me that I should parse wstring for it to be accepted by json constructor. Is Parse just for parsing valid json in string format then?  What about iterator parse, how does that work? I'm a little confused.

How should I go about constructing a json when my data is in std::wstring

**Comment by nlohmann** [comment]
`parse` indeed expects a valid JSON text and throws an exception in case of syntax errors.

`std::wstring` is currently only supported as source for the parser; that is, you can pass a `std::wstring` to `parse`. There is currently no support to use `std::wstring` in any other parts of the library. That is, you can not do something like:

```cpp
std::wstring my_string = "...";
json j;
j["key"] = my_string;  // <--- this does not work
```

**Comment by AistisT** [comment]
I swear that worked for me before, but now I can reproduce it.
May I ask what's the reasoning for not supporting wstring? that seems limiting real life usage quite a lot. It should produce wstring json, after all json is just a string that's formatted in a json schema

**Comment by nlohmann** [comment]
The library uses UTF-8 internally. Storing `std::wstring` would mean a recoding. This is a lot of work and was not approached so far.

**Comment by nlohmann** [comment]
As the original problem is solved, can I close this issue?

**Comment by AistisT** [comment]
I've solved it by converting wstring to utf8 string, so in a way its solved I suppose
