### ISSUE TITLE
Issue with struct nested in class' to_json

### ISSUE THREAD

**Issue by Qbz23** [nlohmann/json#1155]
I'm getting the "could not find to_json() in T's namespace" error when trying to use a struct nested in a class. I figure I'm most likely just missing something...

The following does not work...

    class Tile : public MouseReactive
    {
    public:

        struct TileData
        {
          std::string name;
          uint32_t redStart;
          uint32_t blueStart;
          uint32_t redGain;
          uint32_t blueGain;
          uint32_t nutrientMax;
          bool impassable;
          std::string tex;
        };
        static void to_json(json& j, const TileData& td);
    };

    void Tile::to_json(json& j, const TileData& td)
    {
      j = json{ {"name",         td.name},
                {"redStart",     td.redStart},
                {"blueStart",    td.blueGain},
                {"redGain",      td.redGain},
                {"blueGain",     td.blueGain},
                {"nutrientMax",  td.nutrientMax},
                {"impassable",   td.impassable},
                {"tex",          td.tex}};
    }

But this similar example does. Not sure what I'm missing for classes 

    namespace TestNs
    {
      struct TestType
      {
        std::string name;
        uint32_t redStart;
        uint32_t blueStart;
        uint32_t redGain;
        uint32_t blueGain;
        uint32_t nutrientMax;
        bool impassable;
        std::string tex;
      };
      void to_json(json& j, const TestNs::TestType& tt);
    };

    namespace TestNs
    {
      void to_json(json& j, const TestNs::TestType& tt)
      {
        j = json{ { "name",         tt.name },
                  { "redStart",     tt.redStart },
                  { "blueStart",    tt.blueGain },
                  { "redGain",      tt.redGain },
                  { "blueGain",     tt.blueGain },
                  { "nutrientMax",  tt.nutrientMax },
                  { "impassable",   tt.impassable },
                  { "tex",          tt.tex } };
      }
    }

And I'm just testing it with 

      TestNs::TestType tt;
      json j = tt;
      Tile::TileData td;
      json j2 = td;

**Comment by nlohmann** [comment]
You need to define the `to_json` function in the same namespace as your class. Can you post a complete code example of the issue that raises the error?

**Comment by Qbz23** [comment]
Ah I understand. I misinterpreted the readme. I thought I would need to put to_json inside the class because that's where the struct is defined. Just putting the to_json in the global namespace where the class is defined works just fine. Thanks for the quick response!

**Comment by nlohmann** [comment]
No worries. This aspect of the class leads to a lot of questions, and I am in the course of extending the documentation for this.
