### ISSUE TITLE
resize(...)?

### ISSUE THREAD

**Issue by phyz777** [nlohmann/json#1157]
Hello, 

is there a resize() function for arrays, analogous to the resize function of std::vector<T>?

**Comment by phyz777** [comment]
The following piece of code does not compile, which leads me to the suggestion that currently, this function is not implemented: 

```
#include <iostream>
#include "json.hpp"

int main(int argc, char const *argv[]) {
    nlohmann::json j;

    j["array"] = nlohmann::json::array();

    j["array"].resize(5);

    return 0;
}
```

Is there an efficient way to store a std::vector in a nlohmann json array? 
Looping and repeatedly invoking `push_back` will lead to frequent memory re-allocations in the case of large objects. 
In this case, a previous call to j["array"].resize(myVector.size()) would lead to a great performance gain. 

Thus, I would suggest implementing the two `resize` functions analogously to the STL

**Comment by nlohmann** [comment]
The library itself does not have a `resize()` function, but you can access the vector inside a `json` array with [`get_ref`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_afbd800010b67619463c0fce6e74f7878.html#afbd800010b67619463c0fce6e74f7878) where you can call `std::vector::resize` on.

**Comment by nlohmann** [comment]
@phyz777 Does this solve your issue?

**Comment by phyz777** [comment]
Yepp, works fine! Thanks for linking the `get_ref<T>()` documentation, that helped a lot.

**Comment by nlohmann** [comment]
Cool!
