### ISSUE TITLE
no instance of overloaded function "std::swap" matches the specified type	

### ISSUE THREAD

**Issue by jefferson-1** [nlohmann/json#1159]
- What is the issue you have?
Cannot compile in Visual Studio 2017 after including json.hpp

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?
This line - 18474	inline void swap(nlohmann::json& j1, generates the following error
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0493	no instance of overloaded function "std::swap" matches the specified type	

- Did you use a released version of the library or the version from the `develop` branch?
Tried 3.01 and 3.12 develop

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

I'm able to cmake the project but unable to compile after including it... I've tried:
ISO C++ latest draft and ISO C++ 17. I'm not able to go to any earlier versions due to dependencies.

**Comment by jefferson-1** [comment]
Weird. I blew away the project, remade the project and everything worked.
#JustMicrosoftThings ...

**Comment by nlohmann** [comment]
I am not using MSVC myself, so I cannot really file a bug report on this.

**Comment by jefferson-1** [comment]
Here's the deal -- I did a little thinking on this and I think that it is possible that the JSON file being referenced could affect this bug. When I remade my project I rebuild the config file as well and I did it in a slightly different way. It may be something to look at ...
