### ISSUE TITLE
Showing difference between two json objects

### ISSUE THREAD

**Issue by arynaq** [nlohmann/json#1160]
I cannot figure out how I would go about doing this. 

I looked into the patch function and thought about applying it to a default state of the object but suppose a key is set to boolean true while the default is false but the two objects don't differ in this key then applying the patch to the default and looking at the default would indicate this value has changed to false.

Essentially I just want a diff with minimal extra tooling.

**Comment by nlohmann** [comment]
Have you tried the [`diff`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a543bd5f7490de54c875b2c0912dc9a49.html#a543bd5f7490de54c875b2c0912dc9a49) function?

**Comment by arynaq** [comment]
Ah good call, this was towards the end of the work day as I was despairing :+1: 
So the the diff function returns me a patch object with json pointers, I assume I can then look at the pointers to see which specific keys have changed.

I will try and paste the solution here.

**Comment by arynaq** [comment]
::diff was what I needed, thank you. I ended up just writing parts of the object that the diff had an op for to file, I had to parse the json path
`{
    "op": "replace",
    "path": "/XX/YY/0/centerFrequencyInHz",
    "value": 9933743300.0
  },`

To create the nested structure with `{"XX" : {"YY": [{"centerFrequencyInHz" : 9933743300.0 }` 
but this is fine, I assume there isn't much need for the library to provide something like substract(left, right, patch) which would output that directly.
