### ISSUE TITLE
Combine json objects into one?

### ISSUE THREAD

**Issue by Merethiel** [nlohmann/json#1165]
The title might not correctly describe what I'm attempting but essentially I have one structure that I can convert to a json string but I want to append a list of objects also to be converted into json strings and send that all together as one packet.

Something like this.
`json Packet;

Packet["PacketType"]  = config::packet::type::TYPE;

Packet["ArrayOfObjects"] = ArrayOfObjects;`

Or make two separate json objects and combine them.

Another question I have is, does an array of objects have to be set at initialisation?

**Comment by pboettch** [comment]
What have you tried? Could you show us some more elaborate code-examples of what you do and how you do it?

To push an object into a list you can do:

```C++
json a = json::array();
a.push_back({{"key", "value"}}); // two braces!

// or
json d;
d["key"] = value;
a.push_back(d);
```

**Comment by pboettch** [comment]
(small hint: on github use \`\`\` (three backticks) for code-highlighting (```cpp for language selection)

**Comment by pboettch** [comment]
Before proposing, could you write (by hand if needed) the json you would expect? Where do you see the array, where the object(s)?

**Comment by Merethiel** [comment]
It was more of a question than a proposal if it already existed, but the JSON results I would have been expecting from the code above, to look something like this:

```
    /*
     {
     "Id" : 10,
     "Xposition[0]": 0,
     "YPosition[0]": 1,
     "XPosition[1]" : 1,
     "YPosition[1]" : 2,
     "XPosition[2]" : 2,
     "YPosition[2]" : 3,
     */
```
And so on until XPosition[9] and YPosition[9]

But I'm thinking a way I can do this wiht the existing code is simply appending the string value of [0],[1] as I loop through?

**Comment by pboettch** [comment]
I meant before I can propose something.

However, are you sure your JSON is efficient? Why not:

```JSON
{"Id: 10,
 "Position": [ 
     { "x": 0, y: 1 }
     { "x": 1, y: 2 }
 ]
}
```

**Comment by Merethiel** [comment]
I think the way you wrote it is far more efficient and better looking than I how I wrote it. However if I'm not mistaken, are they not stored in maps with unique keys?

**Comment by pboettch** [comment]
Hmm, what do you mean with unique keys? Here is how you would access this with nlohmann-json:

```CPP
d["Id"] == 10;
d["Position"][0]["x"] == 0;
d["Position"][1]["y"] == 2;
```

**Comment by Merethiel** [comment]
Would that need to be added as a feature is there a workaround I can use for it? The other concern I have is, I'm sending this over through a websocket to a javascript client and I'm not certain if the JSON implementation in Javascript would be compatible if the feature was implemented here.

**Comment by pboettch** [comment]
This is standard-compliant JSON:

```CPP
{"Id": 10,
 "Position": [ 
     { "x": 0, "y": 1 },
     { "x": 1, "y": 2 }
 ]
}
```

**Comment by Merethiel** [comment]
Ah okay. Thank you so much! I'll see if I can find a work around until then.

**Comment by pboettch** [comment]
Workaround for what?

**Comment by Merethiel** [comment]
What you posted: 
```
{"Id": 10,
 "Position": [ 
     { "x": 0, "y": 1 },
     { "x": 1, "y": 2 }
 ]
}
```
Is this possible with the nlohmann json library?

**Comment by pboettch** [comment]
Of course.

```C++
#include <nlohmann/json.hpp>

#include <iostream>

int main(void)
{
	nlohmann::json pos;

	pos["Id"] = 10;
	pos["Position"] = nlohmann::json::array();

	for (int i = 0; i < 10; i++)
		pos["Position"].push_back({{"x", i}, {"y", i + 1}});

	std::cout << std::setw(2) << pos << "\n";
	return 0;
}
```
Prints

```JSON
{
  "Id": 10,
  "Position": [
    {
      "x": 0,
      "y": 1
    },
    {
      "x": 1,
      "y": 2
    },
    {
      "x": 2,
      "y": 3
    },
    {
      "x": 3,
      "y": 4
    },
    {
      "x": 4,
      "y": 5
    },
    {
      "x": 5,
      "y": 6
    },
    {
      "x": 6,
      "y": 7
    },
    {
      "x": 7,
      "y": 8
    },
    {
      "x": 8,
      "y": 9
    },
    {
      "x": 9,
      "y": 10
    }
  ]
}
```

**Comment by Merethiel** [comment]
Thank you! That's exactly what I was trying to do!

**Comment by pboettch** [comment]
You're welcome. Don't forget to close this issue if you have no further problems regarding your initial questions.
