### ISSUE TITLE
Unexpected behaviour of is_null - Part II

### ISSUE THREAD

**Issue by phyz777** [nlohmann/json#1167]
The following code produces a core dump with this error message: ``Assertion `m_value.object->find(key) != m_value.object->end()' failed``

```c++
int main() {
    nlohmann::json j;
    j["subobject"] = {{"key1", "value1"}, {"key2", "value2"}};

    const nlohmann::json &subobject = j["subobject"];

    if (!subobject["key1"].is_null()) {
        std::cout << "CHECK" << std::endl;
    } else {
        std::cout << "FAIL" << std::endl;
    }

    if (!subobject["key3"].is_null()) {
        std::cout << "CHECK" << std::endl;
    } else {
        std::cout << "FAIL" << std::endl;
    }

    return 0;
}
```

This is because the check inserts `{"key3", null}` into the object. 

I'm not sure whether this behaviour is intentionally, it might at least become a pitfall for some, so I wanted to bring this to your attention.

**Comment by nlohmann** [comment]
For const json objects, operator[] has an undefined semantics if the given key is not present, see https://nlohmann.github.io/json/classnlohmann_1_1basic__json_ab2318780e5ae692039e816b6ac32c91e.html#ab2318780e5ae692039e816b6ac32c91e

**Comment by nlohmann** [comment]
More details:

- `subobject` is const
- `operator[] const` cannot add keys to an object, so using it with an unknown key such as "key3" has undefined behavior
- when assertions are switched on, this undefined behavior triggers an assertion
- always use `at` if you need a runtime check

**Comment by phyz777** [comment]
For my purposes, it was sufficient to simply remove the `const` specifier. 
But I'm sure all these additional information will come in handy soon or later, both for me and for others. 
Thanks a lot!

**Comment by nlohmann** [comment]
Ok, thanks for checking back!

**Comment by p-i-** [comment]
```	json j = {
		{ "foo", 1 }
	};

	std::cout << j["bar"].is_null() << std::endl; // `1`
	// 1
	
	std::cout << j << std::endl;
	// {"bar":null,"foo":1}
```

This is very unexpected behaviour.

**Comment by gregmarr** [comment]
Where is the unexpected behavior here?

**Comment by nlohmann** [comment]
When you have a non-const JSON value and use operator[] to access a non-existing key, a value is default-constructed at that key. This is the same behavior as `std::map`.
