### ISSUE TITLE
Roundtripping null to nullptr does not work

### ISSUE THREAD

**Issue by nlohmann** [nlohmann/json#1169]
- What is the issue you have?

We use the `nullptr` to denote JSON's `null` value.

```cpp
json j = nullptr;
```

But the reverse does not work:

```cpp
std::nullptr_t n = j;
```

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

```cpp
#include <iostream>
#include "json.hpp"

using json = nlohmann::json;

int main()
{
    json j = nullptr;
    std::nullptr_t n = j;
    std::cout << std::boolalpha << (n == nullptr) << std::endl;
}
```

- What is the expected behavior?

Output:

```
true
```

- And what is the actual behavior instead?

Error `could not find from_json() method in T's namespace`.

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

Xcode Version 10.0 beta (10L176w).

- Did you use a released version of the library or the version from the `develop` branch?

`develop`.

* * *

Adding the following code to the library solves the issue:

```cpp
template<typename BasicJsonType>
void from_json(const BasicJsonType& j, typename std::nullptr_t& n)
{
    if (JSON_UNLIKELY(not j.is_null()))
    {
        JSON_THROW(type_error::create(302, "type must be null, but is " + std::string(j.type_name())));
    }
    n = nullptr;
}
```

**Comment by jaredgrubb** [comment]
+1

**Comment by nlohmann** [comment]
Fixed.
