### ISSUE TITLE
unordered_map with vectors won't convert to json?

### ISSUE THREAD

**Issue by alberto2000** [nlohmann/json#1173]
I have a `std::unordered_map<std::string, vector<float>> *valuesMap` and am trying to `nlohmann::json jstr(valuesMap);` but I do get error 

> error: static assertion failed: could not find to_json() method in T's namespace static_assert(sizeof(BasicJsonType) == 0

Are vectors not supported?

**Comment by theodelrieu** [comment]
Pointer conversion is not supported as-is, dereferencing `valuesMap` should work.

**Comment by alberto2000** [comment]
Thanks a lot!
