### ISSUE TITLE
I have a query regarding nlohmann::basic_json::basic_json

### ISSUE THREAD

**Issue by sonulohani** [nlohmann/json#1174]
Hi @nlohmann ,

While i was understanding the json code, I've got involved into a question. In this link:- https://nlohmann.github.io/json/classnlohmann_1_1basic__json_ab5dfd9a2b2663b219641cb7fe59b6da2.html#ab5dfd9a2b2663b219641cb7fe59b6da2 in the ctor "basic_json" I want to pass type_deduction as false. How can i do that.

**Comment by nlohmann** [comment]
You could try:

```cpp
auto j = basic_json({{"foo", "bar"}}, false);
```

**Comment by sonulohani** [comment]
@nlohmann Thank you.

**Comment by sonulohani** [comment]
I am doing like this:-

`using nlohmann::json;`
`json j_array = json({13, 29, 3, {{"one", 1}, {"two", 2}}, true, false, {1, 2, 3}, "foo", "baz"}, false);`

But still the value of type_deduction is still true.

**Comment by nlohmann** [comment]
I guess you then also need to pass a value for `manual_type`. These are actually internal parameters.

**Comment by nlohmann** [comment]
@sonulohani Can I close this issue?

**Comment by sonulohani** [comment]
@nlohmann Yeah sure. Thank you very much
