### ISSUE TITLE
Memory leak in face of exceptions

### ISSUE THREAD

**Issue by ColinH** [nlohmann/json#118]
The constructor often does a two-step initialisation, an `allocate()` followed by a `construct()`. If the `construct()` throws then the previously allocated memory will leak...

            AllocatorType<object_t> alloc;
            object = alloc.allocate(1);
            alloc.construct(object, value);

**Comment by gregmarr** [comment]
Probably the least intrusive way is to use a temporary unique_ptr with a custom deleter:

        AllocatorType<object_t> alloc;
        auto deleter = [&](object_t *object) { alloc.deallocate(object, 1); };
        std::unique_ptr<object_t, decltype(deleter)> local_object(alloc.allocate(1), deleter);
        alloc.construct(local_object, value);
        object = local_object.release();

Another way would be with try/catch:

        AllocatorType<object_t> alloc;
        object = alloc.allocate(1);
        try {
            alloc.construct(object, value);
        } catch(...) {
            alloc.deallocate(object, 1);
            throw;
        }

Beyond that, it would probably require wrapping the m_value and m_type in a struct, and moving the basic_json destructor to the new struct.

**Comment by ColinH** [comment]
Yes, either should work, not quite sure which style the author prefers.
