### ISSUE TITLE
Is there a way to get an element from a JSON without throwing an exception on failure?

### ISSUE THREAD

**Issue by d223chen** [nlohmann/json#1182]
For example, say `j` is an nlohmann::json object. I want to try to get a member called "raw" using the following code, but without throwing an exception if it fails -- exceptions seem to be a time bottleneck in my application.		

            p.raw = j.at("raw").get<int>();

Is it possible?

**Comment by gregmarr** [comment]
It depends on whether you want to know if it's there or not, or if you want to get a default value if it's not.  If you want to know, use `find()` first.  If you don't care, use `value()` which takes a default value.

**Comment by nlohmann** [comment]
I doubt that exceptions are *really* a time bottleneck, but you could use:

```cpp
if (j.find("raw") != j.end() and j.is_number_integer())
{
  p.raw = j["raw"];
}
```

**Comment by d223chen** [comment]
Changing the code to this:

          p.raw = j.value("raw",0);

seems to have fixed the problem. Before, the code was taking around 12milliseconds to run when the element wasn't available. Now it takes about 6 microseconds even if the element isn't available. Thanks!
