### ISSUE TITLE
Get an Index or row number of an element

### ISSUE THREAD

**Issue by CleanHit** [nlohmann/json#1186]
Let say I have this file:

```
{
  "tableName": "",
  "tableSchemaName": "",
  "_comment": "",
  "0": ["","", "", ""],
  "1": ["", "", "", ""],
  "2": ["", "", "", ""],
  "3": ["", "", "", ""],
  "4": ["", "", "", ""]
}
```
Is there a way to get the `index` or `row_number` of "0"? I didn't see it in the document.

**Comment by gregmarr** [comment]
No, that's not an array, it's an object, which is an unordered collection of name/value pairs, so there is no index.

**Comment by CleanHit** [comment]
I see. So basically I have to remember myself how many lines I have before the "0" starts, if I have to iterate over the `keys` with numbers. I need it for my loop size.

**Comment by nlohmann** [comment]
It seems as if an object is not really the right way to model your usecase (as its keys are unordered). Unless you can change this, using a secondary structure to organize the order of keys seems to be the only way.

**Comment by CleanHit** [comment]
Got it, thanks.
