### ISSUE TITLE
Add key name when throwing type error

### ISSUE THREAD

**Issue by icaroalvarez** [nlohmann/json#1189]
Congrats for the project. Really cool. I don't know if this is too much concrete and only adds value for my use case but I think it could be usefull to add the name of the key that fails when throwing a type error exception. This way I would fast know where I made a mistake. 

For example, it would be helpfull while using json for program parameter configuration:

```
nlohmann::json config_json =
            {
                    {"param_one", 1},
                    {"param_two", 2}
            };

    try {
        bool param_one = config_json.at("param_one");
        int param_two = config_json.at("param_two");
    }catch(const std::exception& e)
    {
        FAIL(e.what());
    }
```
The exception message is: **[json.exception.type_error.302] type must be boolean, but is number**

It could be nice if the message ended with: (**in key "param_one"**).

Just a thought. Cheers!

**Comment by nlohmann** [comment]
Duplicate: #932
