### ISSUE TITLE
Strange warnings in Code::Blocks 17.12, GNU GCC

### ISSUE THREAD

**Issue by turtleStew** [nlohmann/json#1192]
I'm not sure exactly what's causing it to happen but when I compile my project I often get these warnings:

```
||=== Build: Debug in Stellar Winds (compiler: GNU GCC Compiler) ===|
C:\C++ Projects\Stellar Winds\include\nlohmann\json.hpp||In instantiation of 'std::__cxx11::string nlohmann::detail::lexer<BasicJsonType>::get_token_string() const [with BasicJsonType = nlohmann::basic_json<>; std::__cxx11::string = std::__cxx11::basic_string<char>]':|
C:\C++ Projects\Stellar Winds\include\nlohmann\json.hpp|4309|required from 'void nlohmann::detail::parser<BasicJsonType>::parse(bool, BasicJsonType&) [with BasicJsonType = nlohmann::basic_json<>]'|
C:\C++ Projects\Stellar Winds\include\nlohmann\json.hpp|16931|required from 'static nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer> nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::parse(IteratorType, IteratorType, nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JS|
C:\C++ Projects\Stellar Winds\include\nlohmann\json.hpp|18544|required from here|
C:\C++ Projects\Stellar Winds\include\nlohmann\json.hpp|3366|warning: unknown conversion type character 'h' in format [-Wformat=]|
C:\C++ Projects\Stellar Winds\include\nlohmann\json.hpp|3366|warning: too many arguments for format [-Wformat-extra-args]|
||=== Build finished: 0 error(s), 6 warning(s) (0 minute(s), 3 second(s)) ===|
```

I'm using the single header version with sfml version 2.5.0, everything else is vanilla C++.

I was able to "fix" this a few times before by removing extra includes in my classes but now it remains more constant. My project compiles and runs fine with the warnings but they're annoying and I'm not sure if they're too important. Is this normal and/or can it be fixed?

**Comment by nlohmann** [comment]
Are you using MinGW?

**Comment by turtleStew** [comment]
yes

**Comment by nlohmann** [comment]
Then I guess MinGW does not implement `snprintf` properly.

**Comment by nlohmann** [comment]
Maybe related: https://stackoverflow.com/questions/10678124/mingw-gcc-unknown-conversion-type-character-h-snprintf

**Comment by nlohmann** [comment]
It seems we do not need the `h` specified in the first place.

**Comment by turtleStew** [comment]
Yeah, sorry I forgot to check back here. I'll have a response in about 11 hours

**Comment by turtleStew** [comment]
Works great, mingw builds it with no warnings/errors

**Comment by nlohmann** [comment]
Thanks for checking!

**Comment by jacob-keller** [comment]
I'm seeing similar warnings when using MinGW again:

json.hpp:3780:105: warning: unknown conversion type character 'h' in format [-Wformat=]
                 (std::snprintf)(cr.data(), cr.size(), "%.2hhX", static_cast<unsigned char>(element_type));

**Comment by nlohmann** [comment]
I'll check.

**Comment by nlohmann** [comment]
@jacob-keller Could you please check whether the warning disappears in branch https://github.com/nlohmann/json/tree/issue1192?
