### ISSUE TITLE
json.exception.type_error.316

### ISSUE THREAD

**Issue by 1Hyena** [nlohmann/json#1195]
- What is the issue you have?
After getting the latest version of this json library from its github repository my program started to crash randomly. It did not crash with the previous version. The reason of the crash seems to be an exception that was not thrown before. From the source code it seems that 316 is thrown during dumping the json object which I wouldn't ever anticipate. Why would dumping fail? The description of the said exception does not help me to understand its real cause.

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?
My program has to sometimes run for more than 12h to get this exception. I have no idea how to reproduce it.

- What is the expected behavior?
Well if this is a valid exception that users must 100% be prepared for then I'd have expected some documentation about it. Although I must admit getting an exception from the dump call feels unnatural.

- And what is the actual behavior instead?
Seems that calls to the dump function can throw an exception that wasn't thrown before with the old version of the lib that I had.

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Ubuntu server

- Did you use a released version of the library or the version from the `develop` branch?
Used this one from yesterday:
https://github.com/nlohmann/json/tree/develop/single_include/nlohmann

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by nlohmann** [comment]
The exception should contain the description that you try to dump a non-UTF-8 encoded string. The library only supports UTF-8. See the [documentation](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a5adea76fedba9898d404fef8598aa663.html) for more information.

**Comment by 1Hyena** [comment]
Whoa, what a quick reply, thanks! I would have thought that when assigning a string value to the json object it would later be able to do the encoding itself, but as I can see now it is not always the case? For example, if I assign an std::string that contains invalid utf8 bytes then later dumping it would produce this exception?

**Comment by nlohmann** [comment]
Exactly. The reason for this was that we kept running into issues when the library failed to parse JSON it produced itself.

**Comment by 1Hyena** [comment]
Ok thanks again, probably something fishy happening in my code then. Will need to investigate. Closing this for now.

**Comment by 1Hyena** [comment]
If dump can throw though, then perhaps adding the necessary try catch blocks to the example code in `README.md` might be a good idea. Give it a thought ;)

**Comment by 1Hyena** [comment]
Alright, there still might be something here. The exception that I am receiving is this:

```
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.316] invalid UTF-8 byte at index 6: 0x00
Caught signal 6 (Aborted).
```

According to the description, it is complaining about a **null byte**. However, [a null byte is a perfectly valid UTF8 character](https://stackoverflow.com/questions/6907297/can-utf-8-contain-zero-byte). That said, I think this exception reports a false positive.
