### ISSUE TITLE
Incompatible Pointer Type

### ISSUE THREAD

**Issue by kenshen112** [nlohmann/json#1196]
- Attempting to read Json array `"Item" : ["data", "data"]` 

`charArray = ["Array"].get<char*>();`

- What is the expected behavior?
It reads the array from the file into the char pointer array

- And what is the actual behavior instead?
Error	C2338	incompatible pointer type

- Which compiler and operating system are you using? Is it a [supported compiler]
  Visual Studio 2017 

- Did you use a released version of the library or the version from the `develop` branch? No

**Comment by nlohmann** [comment]
The library does not convert into pointers, but rather returns a pointer to the container used internally. Arrays are stored as `std::vector<nlohmann::json>` and strings are stored as `std::string`. Therefore, a `char*` could only be returned for a single string.

**Comment by kenshen112** [comment]
@nlohmann so then what would be the best way to read this char array out of the file with nlohman json and into a char array or is there one?

**Comment by nlohmann** [comment]
Can you give a precise example?

**Comment by kenshen112** [comment]
I mean I have a Json array of directions for a pet project text adventure game so `"Directions" :  ["N", "S"]` I want to read it into c++ char* directions so I could print on a per room basis `valid directions are N S`

**Comment by nlohmann** [comment]
OK. Assuming `input.json` has the content `{"Directions": ["N", "S"]}`

```cpp
std::ifstream i("input.json");
json j = json::parse(i);
for (auto& el : j["Directions"])
{
   std::string dir1 = el; // access string copy
   std::string& dir2 = el.get_ref<std::string&>(); // access string ref
   std::string* dir3 = el.get_ptr<std::string*>(); // access string ptr
   const char* dir4 = el.get_ptr<std::string*>()->c_str();
}
```

I haven't tested the code. but you should get the idea.

Docs:
- https://nlohmann.github.io/json/classnlohmann_1_1basic__json_afbd800010b67619463c0fce6e74f7878.html#afbd800010b67619463c0fce6e74f7878
- https://nlohmann.github.io/json/classnlohmann_1_1basic__json_aefa46bd2d96bb77a38d1c8b431eab44f.html#aefa46bd2d96bb77a38d1c8b431eab44f

**Comment by nlohmann** [comment]
@kenshen112 Do you need further assistance?

**Comment by kenshen112** [comment]
The purposed solution worked
