### ISSUE TITLE
compiler warning: double definition of macro JSON_INTERNAL_CATCH 

### ISSUE THREAD

**Issue by RalfBielig** [nlohmann/json#1213]
- version 3.2.0

```cpp
#define JSON_CATCH_USER(exception) if(false)
#include "nlohmann/json.hpp"
```
single_include/nlohmann/json.hpp:211:0: warning: "JSON_INTERNAL_CATCH" redefined
single_include/nlohmann/json.hpp:198:0: first definition of macro "JSON_INTERNAL_CATCH"

**Comment by nlohmann** [comment]
This was introduced by #1187.

@simnalamburt Could you have a look at this please?

**Comment by nlohmann** [comment]
I can confirm the warning. Minimal compilable program:

```cpp
#define JSON_TRY_USER if(true)
#define JSON_CATCH_USER(exception) if(false)
#include "single_include/nlohmann/json.hpp"

int main()
{}
```

**Comment by simnalamburt** [comment]
Oops I catched the mistake. I'll send a follow-up PR
