### ISSUE TITLE
Lambda in unevaluated context

### ISSUE THREAD

**Issue by mandreyel** [nlohmann/json#1225]
I've seen #705 but it doesn't appear to be fixed. I'm unfortunately not on bleeding edge (xtensa gcc 5.2.0) so can't use newer gcc versions where this has been fixed. Can we fix this? I can make a PR.

```
~/code/work/esp32-core/main/json/single_include/nlohmann/json.hpp: In constructor 'nlohmann::detail::input_adapter::input_adapter(IteratorType, IteratorType)':
~/code/work/esp32-core/main/json/single_include/nlohmann/json.hpp:2165:20: error: lambda-expression in unevaluated context
                    [&first](std::pair<bool, int> res, decltype(*first) val)
```

**Comment by nlohmann** [comment]
Yes, PRs welcome! Could you then please make sure the lambda is only created when `#ifdef DEBUG` so we have the same production code as with the lambda in the assertion?

**Comment by mandreyel** [comment]
Ok, great! And sure, that makes sense. I'll be able to work on it Monday and hopefully land it the same day.

**Comment by mandreyel** [comment]
Made the changes in #1230!
