### ISSUE TITLE
deprecated-declarations warnings when compiling tests with GCC 8.2.1.

### ISSUE THREAD

**Issue by awdAvenger** [nlohmann/json#1233]
When compiling the tests with GCC 8.2.1, I get lots of -Wdeprecated-declarations warnings.

This is on Arch Linux with no additional options added to the cmake command line.

One such example is below:

/home/avenger/json/test/src/unit-items.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____0()’:
/home/avenger/json/test/src/unit-items.cpp:44:51: warning: ‘static nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::iteration_proxy<nlohmann::detail::iter_impl<nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer> > > nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::iterator_wrapper(nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::reference) [with ObjectType = std::map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::adl_serializer; nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::iteration_proxy<nlohmann::detail::iter_impl<nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer> > > = nlohmann::detail::iteration_proxy<nlohmann::detail::iter_impl<nlohmann::basic_json<> > >; nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::reference = nlohmann::basic_json<>&; nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::value_type = nlohmann::basic_json<>]’ is deprecated [-Wdeprecated-declarations]
             for (auto i : json::iterator_wrapper(j))
                                                   ^
In file included from /home/avenger/json/test/src/unit-items.cpp:32:
/home/avenger/json/single_include/nlohmann/json.hpp:15378:38: note: declared here
     static iteration_proxy<iterator> iterator_wrapper(reference ref) noexcept
                                      ^~~~~~~~~~~~~~~~

**Comment by nlohmann** [comment]
Thanks for reporting anyways!
