### ISSUE TITLE
Custom deserialization of number_float_t

### ISSUE THREAD

**Issue by carlcook** [nlohmann/json#1236]
Hi, 

Do you know if there is any way to provide a deserialization routine for number_float_t, where I can get access to the underlying json string?

Basically I have an arbitrary length Decimal class, and I can easily read this in from json as follows:

`namespace nlohmann {
template <typename T> struct adl_serializer<Decimal> {
  static void from_json(const json &j, Decimal& decimal) {
    decimal = Decimal::parse(j.get<std::string>());
  }
};
}
`

The above only works of course if I pass my "Decimals" as strings in json, e.g.:

` {
  "myPrice": "43.2"
}`

What I'd really like to be able to do is pass "myPrice" as a number (i.e. not in quotes). I've tried a few different approaches, but it seems that number_float_t really has to be an IEEE floating point type (i.e. I can't see a way to "access" the underlying string buffer of the number).

Any pointers would be appreciated!

**Comment by nlohmann** [comment]
You can use the [SAX interface](https://github.com/nlohmann/json#sax-interface) which contains a callback `bool number_float(number_float_t val, const string_t& s)` which contains the parsed string.

**Comment by carlcook** [comment]
For now I'll leave this in the too hard basket. I tried experimenting with the output adpator (etc) but nothing great came of this...
