### ISSUE TITLE
Doesn't compile under C++17

### ISSUE THREAD

**Issue by iphydf** [nlohmann/json#1239]
`no type named 'string_view' in namespace 'std'`

You need to `#include <string_view>` somewhere.

**Comment by gregmarr** [comment]
See #735  There are compilers that support the C++17 flag but don't have a `<string_view>` header in the standard library that is being used.  Others have it as `<experimental/string_view>`, while most include it in `<string>` which is included, and so it gets included that way.
What compiler and standard library are you using?

**Comment by iphydf** [comment]
clang-5.0 and libstdc++ from gcc 6.3.0 (`__GLIBCXX__=20170516`). It does not in fact seem to provide `<string_view>`, so including it won't fix the problem.

**Comment by nlohmann** [comment]
Closing this issue as it is a duplicate of #735.
