### ISSUE TITLE
Parsing different json format

### ISSUE THREAD

**Issue by betomoretti** [nlohmann/json#1241]
Hi there!

I would like to ask if it's possible to parse with the following structure:
```
{"key1":"value1","key2":"value2"}
{"key1":"value1","key2":"value2"}
```
This  is my use case:
```
std::string ret(buffer);
auto j = json::parse(ret);
```
Thanks ! :)

**Comment by nlohmann** [comment]
You mean newline-separated JSON text?

**Comment by betomoretti** [comment]
Yes! :D

**Comment by betomoretti** [comment]
It worked! Thanks!! I will close this issue!
