### ISSUE TITLE
Cmake target_link_libraries unable to find nlohmann_json since version 3.2.0

### ISSUE THREAD

**Issue by SylvainCorlay** [nlohmann/json#1243]
We updated from `3.1.2` to `3.2.0`. The update causes the `target_link_libraries` cmake command to not properly include `nlohmann_json`, while `find_package(nlohmann_json REQUIRED)` did not result in an error.

After some investigation, it seems that the issue was the addition of namespaces to target names which is a **backward incompatible** change.

**Comment by SylvainCorlay** [comment]
cc @chuckatkins.

**Comment by nlohmann** [comment]
Thanks for reporting and sorry for the inconvenience!

The change that introduced the namespace was introduced by @chuckatkins in #1048, and I assumed that the change is fine given that Chuck is with Kitware. Maybe he can comment on the reasons for adding a namespace as I apparently did not understand the repercussions of the change.

**Comment by SylvainCorlay** [comment]
Yes, this is good cmake practice. Just giving a heads up because it is a breaking change for anyone using cmake to build against `nlohmann_json`.

**Comment by chuckatkins** [comment]
Indeed sorry about the breaking change.  The namespace was to transition to more modern CMake practices if namespaced target names being external and non-namespaced target names being "local".  Ideally, you'll want to transition to using the namespaced target name when consuming it externally through the config file.  In the meantime though, I think I have a quick workaround that can provide both.
