### ISSUE TITLE
A way to get to a JSON values "key"

### ISSUE THREAD

**Issue by robiwano** [nlohmann/json#1258]
- Describe the feature in as much detail as possible.

A possibility to get the key of a value, as I haven't been able to find a way to get to it.

- Include sample usage where appropriate.

For a JSON object `obj` as such:
```
auto obj = R"(
  {
    "first": 0,
    "second": true,
    "third": "stringy"
  }
)"_json;
```
I would like to iterate over values and get their keys:
```
for (auto& entry : obj) {
  std::cout << entry.key() << std::endl;
}
```
which should yield:
```
first
second
third
```

**Comment by robiwano** [comment]
Sorry. I found the way to do it.

**Comment by asowani** [comment]
Hi @robiwano I have come across exactly the same issue. If you don't mind, could you please share the way to do this?

**Comment by nlohmann** [comment]
Maybe the [items](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_afe3e137ace692efa08590d8df40f58dd.html#afe3e137ace692efa08590d8df40f58dd) function helps?

**Comment by robiwano** [comment]
```
json::iterator it = obj.begin();
for(; it != obj.end(); ++it)
  cout << it.key() << endl;
```

**Comment by asowani** [comment]
@robiwano Thanks a lot! It worked!
