### ISSUE TITLE
serialize std::variant<...>

### ISSUE THREAD

**Issue by MattiasEppler** [nlohmann/json#1261]
Hi.
I try to serialize std::variant<double,int> to json.
I look for an easy and comfortable way. Is there any solution available?

Or any idea how to do this.

**Comment by nlohmann** [comment]
[This section](https://github.com/nlohmann/json#arbitrary-types-conversions) from the README should help you.

**Comment by MattiasEppler** [comment]
Hi.
I already read this section.

I do it in this way

string value = "";

if(const auto pdouble = std::get_if<double>(&data.Value))
    value = std::to_string(*pdouble);
else if(const auto pint= std::get_if<int>(&data.Value))
    value = std::to_string(*pint);

I thought maybe there is an easier solution.

But if not you can close this issue.

Thanks

**Comment by nlohmann** [comment]
I'm afraid not - at least I am not aware of a generic way to collect all the possible values from a variant.

**Comment by theodelrieu** [comment]
You could do something like:

```cpp
namespace nlohmann {
template <typename ...Args>
struct adl_serializer<std::variant<Args...>> {
  static void to_json(json& j, std::variant<Args...> const& v) {
    std::visit([&](auto&& value) {
      j = std::forward<decltype(value)>(value);
    }, v);
  }
};
}
```

I don't think it's possible to provide a generic `from_json` here. Even if we serialize the index, it will be known at runtime, so switching on it would require to write N `case`, N being `sizeof...(Args) - 1`...

What I would do is setting the index in the json only when serializing an enclosing type:

```cpp
struct Example {
  std::variant<int, std::string, float> var;
};

void to_json(json& j, Example const& e) {
  j = {{"index", e.var.index()}, {"variant", e.var}};
}

void from_json(json const&j, Example& e) {
  auto const index = j.at("index").get<int>();
  switch (index) {
    case 0:
      e.var = j.get<int>(); break;
    case 1:
      e.var = j.get<std::string>(); break;
    case 2:
      e.var = j.get<float>(); break;
    default: throw std::runtime_error{""};
  }
}
```

**Comment by theodelrieu** [comment]
On a second thought, there might be a way to make it generic, I'll try it out and post the results.

**Comment by MattiasEppler** [comment]
Oh.... Thanks a lot for spending your time. I will try it.

**Comment by MattiasEppler** [comment]
My Compiler (Visual Studio 2017) does not know Args... and sizeof...

**Comment by nlohmann** [comment]
@MattiasEppler Did you try?

**Comment by MattiasEppler** [comment]
Hi. Oh sorry. 
Yes It works. Thanks to theodelrieu.

Will this be added to nlohmann\json?

**Comment by theodelrieu** [comment]
>Will this be added to nlohmann\json?

I guess we could add it, I'd like users to be able to do the following:

```cpp
std::variant<int, float, MyType> v(2);

json j = v;
auto i = j.get<int>();
auto v2 = j.get<decltype(v)>();
```

For this to work, we need to add a library-reserved field in the variant's alternative serialization:

```cpp
template <typename ...Args>
void to_json(json& j, std::variant<Args...> const& v) {
  std::visit([&](auto const& a) { 
                      j = a;
                    }, v);
  j["__nlohmann_variant_index"] = v.index();
}

template <typename ...Args>
void from_json(json const& j, std::variant<Args...>& v) {
  auto const index = j.at("__nlohmann_variant_index").get<int>();
  // recursive ugliness to get the correct index...
}
```

**Comment by nlohmann** [comment]
I agree with @theodelrieu. In a lot of cases, a variant is not the sole variable to be serialized, so type information may be derived implicitly from other members.

@MattiasEppler Is it OK to close the issue?

**Comment by MattiasEppler** [comment]
Hi. Yes its ok.

**Comment by ibkevg** [comment]
@theodelrieu @nlohmann after writing the `to_json()` and `from_json()` routines to serialize a std::variant I've found that the json constructor can't find my custom `to_json()` function. I wondered if the problem was that the to/from functions had to be in the std namespace but they don't compile if I do. I noticed above that you stuck the std::variant inside a struct but that isn't possible in my use case.

What do you recommend as the cleanest way to use std::variant?


Here is a small example (which I used on the latest Visual Studio 15.9)

`#include <nlohmann/json.hpp>
#include <variant>

using json = nlohmann::json;

typedef std::variant<int64_t, std::string>  TestVariant;

void to_json(json& j, TestVariant const& v)
{
    if (auto pInt64 = std::get_if<int64_t>(&v)) {
        j = json{ {"type", 0}, {"int64_t", *pInt64 } };
    } else if (auto pStdStr = std::get_if<std::string>(&v)) {
        j = json{ {"type", 1}, {"string", *pStdStr} };
    } else {
        throw std::bad_variant_access();
    }
}

void from_json(json const& j, TestVariant& v)
{
    auto const type = j.at("type").get<int>();
    switch (type) {
    case 0:
        v = TestVariant(j.at("int64_t").get<uint64_t>()); break;
    case 1:
        v = TestVariant(j.at("string").get<std::string>()); break;
    default: throw std::runtime_error{ "Unexpected FT:Variant" };
    }
}

void test()
{
    auto v1 = TestVariant(100);

#if 0
    // Gives compile error C2440 below
    json j = v1;
#else
    // This compiles/works
    json j;
    to_json(j1, vInt);
#endif

    std::cout << j << std::endl;
    TestVariant v2 = j; // Gives compile error C2440 below
    cout << std::get<uint64_t>(v2) << endl;
}
`
error C2440: 'initializing': cannot convert from 'TestVariant' to 'nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>'
note: No constructor could take the source type, or constructor overload resolution was ambiguous

error C2440: 'initializing': cannot convert from 'json' to 'std::variant<int64_t,std::string>'
note: No constructor could take the source type, or constructor overload resolution was ambiguous

**Comment by theodelrieu** [comment]
I would advise putting the conversion code inside the specialization, not calling your free function in the global namespace. Otherwise, it seems correct.

**Comment by zhongcy** [comment]
@nlohmann  nlohmann has not support C++17 Variant, right?

**Comment by jeffreyscottgraham** [comment]
The alternative 'cereal" library has support for boost variant by adding a separate includes file for those that need it.

**Comment by jeffreyscottgraham** [comment]
Any update on supporting std::variant?
What about boost variant via a separate #include file?

**Comment by nlohmann** [comment]
Well, there is the code in https://github.com/nlohmann/json/issues/1261#issuecomment-426209912. Apart of this, I would be happy to see a PR!

**Comment by chakpongchung** [comment]
Also want to see a variant example here

**Comment by beached** [comment]
just a comment. JSON can have odd ways of expressing what type will be in a member.  Take something similar to geojson where we have a type field that tells us what the data field is
```json
[{
  "type": "point",
  "data": [1.0, 2.0]
},
{
  "type": "poly",
  "data": [1.0,2.0,3.0,4.0]
}]
```
They are the same in terms of JSON types, but when deserializing they could be in a c++ structure like
```
struct geo {
  geo_type type;
  std::variant<point, polygon> data;
};
```

**Comment by narnaud** [comment]
My take on this: https://www.kdab.com/jsonify-with-nlohmann-json/

I needed a way to serialize/deserialize variant without saving the type.
This requires the types to be "exclusive".

```
template <typename... Ts>
struct adl_serializer<std::variant<Ts...>> {

    static void to_json(nlohmann::json &j, const std::variant &data) {
        // Will call j = v automatically for the right type
        std::visit([&j](const auto &v) { j = v; }, data);
    }
    
    // Try to set the value of type T into the variant data if it fails, do nothing
    template <typename T, typename... Ts>
    void variant_from_json(const nlohmann::json &j, std::variant<Ts...> &data) {
        try { 
            data = j.get<T>();
        } catch (...) {
        }
    }   
    static void from_json(const nlohmann::json &j, std::variant<Ts...> &data) {
        // Call variant_from_json for all types, only one will succeed
        (variant_from_json<Ts>(j, data), ...);
    }
};
```

It will guess the value based on the data. For example, a `struct { std::vector<int>, bool> data; };` is serialize like this:
```
{
    data: true
}
or
{
    data: [1, 2, 3, 4, 5]
}
```

**Comment by me21** [comment]
You probably could lift the requirement for types to be "exclusive" by using `std::is_same` in `variant_from_json` function.

**Comment by MattiasEppler** [comment]
Hi [narnaud](https://github.com/narnaud)
Thanks for your example. 

Can you give an example how to deserialize.
I have implemented the custom adl_serializer like above.
And try to use it in this way: but this do not work

```
using valuetype = std::variant<bool, double, int>;

inline void from_json(const json& j, valuetype& value)
{
     auto name = j.at("value").get<valuetype>();
}
```

**Comment by MattiasEppler** [comment]
Sorry just want to ask a question.

**Comment by narnaud** [comment]
@MattiasEppler 

I made a mistake in my previous code, the `variant_from_json` should have been outside the `adl_serializer` struct (fixed).
The code is now the one I'm using in production, and it should work with your example.

**Comment by MattiasEppler** [comment]
@narnaud 
I move the function variant_from_json outside of the adl_serializer. But still get an error

Error C2672: 'nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer,std::vector<uint8_t,std::allocator<_Ty>>>::get': no matching overloaded function found (346)

on line

value = j.at("value").get<valuetype>();

**Comment by MattiasEppler** [comment]
sooooory. Just forgot to include the file where the adl_serializer is defined   :-(

**Comment by MattiasEppler** [comment]
Maybe somone an idea to an alternative of switch case. If i try to deserialize a variant with known an index not included in json 

```
switch (index) {
    case 0:
      e.var = j.get<int>(); break;
    case 1:
      e.var = j.get<std::string>(); break;
    case 2:
      e.var = j.get<float>(); break;
    default: throw std::runtime_error{""};
  }
```

**Comment by mqnc** [comment]
@ibkevg @nlohmann 

> QUESTION: @theodelrieu @nlohmann after writing the to_json() and from_json() routines to serialize a std::variant I've found that the json constructor can't find my custom to_json() function. I wondered if the problem was that the to/from functions had to be in the std namespace but they don't compile if I do. I noticed above that you stuck the std::variant inside a struct but that isn't possible in my use case.

> ANSWER: here is the glue needed:
> 
> ```
> namespace nlohmann {
> 
> template <>
> struct adl_serializer<TestVariant> {
>     static void to_json(json& j, const TestVariant& value) {
>         ::to_json(j, value);
>     }
> 
>     static void from_json(const json& j, TestVariant& value) {
>         ::from_json(j, value);
>     }
> };
> 
> }
> ```

Why is this necessary? I got really stuck on this until I found this ANSWER... Why can every other type be converted with free to_json functions but it doesn't work with variants?

**Comment by gregmarr** [comment]
@mqnc covered here: https://github.com/nlohmann/json#how-do-i-convert-third-party-types

**Comment by mqnc** [comment]
Ah because it's in the std namespace... Thank you!

**Comment by lkotsonis** [comment]
> My take on this: [kdab.com/jsonify-with-nlohmann-json](https://www.kdab.com/jsonify-with-nlohmann-json/)
> 
> I needed a way to serialize/deserialize variant without saving the type. This requires the types to be "exclusive".
> 
> ```c++
>    // ...
> 
>     static void from_json(const nlohmann::json &j, std::variant<Ts...> &data)
>     {
>         // Call variant_from_json for all types, only one will succeed
>         (variant_from_json<Ts>(j, data), ...);
>     }
> };
> ```

This worked partially for me because I've been using `NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE_WITH_DEFAULT` for the variant types inside `std::variant` and on top of that my `std::variant` has a `std::monostate`. Also I've been keeping the index within the json when serialization in `to_json`. Hence, I had to add some extra logic to `variant_from_json` since this:
```
data = j.get<T>();
```
doesn't seem to throw even if T is not corresponding to the data in the json object. The logic is along the lines of using monostate as a fallback whenever the index doesn't match the variant type index, to avoid overwriting `data` with a default initialized variant type.

**Comment by vglavnyy** [comment]
I found a little bit better solution for ser/deser of the `std::variant<Ts...>`.
This is a comination of two ideas:
1. [Is it possible to print a variable's type in standard C++?](https://stackoverflow.com/a/20170989)
2. https://github.com/nlohmann/json/issues/1261#issuecomment-1099887452

The first part is converting invariant's type to `contexpr` string:
```cpp
namespace utils
{
  namespace details
  {
    template <typename T>
    constexpr auto make_type_name() {
      using namespace std::string_view_literals;
    #ifdef __clang__
      std::string_view name = __PRETTY_FUNCTION__;
      name.remove_prefix("auto utils::details::make_type_name() [T = "sv.size());
      name.remove_suffix("]"sv.size());
    #endif
      return name;
    }
  } // details
  
  /**
  * Convert type T into constexpr string.
  */
  template<typename T>
  constexpr auto type_name_sv = details::make_type_name<T>();
  
  static_assert(type_name_sv<int> == std::string_view{"int"});
} // utils
```

The second is serialization using pack foldind as proposed [narnaud](https://github.com/narnaud):

```cpp
namespace nlohmann
{
  namespace
  {
      template <typename T, typename... Ts>
      bool variant_from_json(const nlohmann::json& j, std::variant<Ts...>& data) {
        if (j.at("type").get<std::string_view>() != utils::type_name_sv<T>)
          return false;
        data = j.at("data").get<T>();
        return true;
      }
   } 

  template <typename... Ts>
  struct adl_serializer<std::variant<Ts...>>
  {
    using Variant = std::variant<Ts...>;
    using Json = nlohmann::json;
    
    static void to_json(Json& j, const Variant& data) {
      std::visit(
        [&j](const auto& v) {
          using T = std::decay_t<decltype(v)>;
          j["type"] = utils::type_name_sv<T>;
          j["data"] = v;
        },
        data);
    }
    
    static void from_json(const Json& j, Variant& data) {
      // Call variant_from_json for all types, only one will succeed
      bool found = (variant_from_json<Ts>(j, data) || ...);
      if (!found)
        throw std::bad_variant_access();
    }
  };
} // nlohmann
```

This approach is linear in time without exceptions during testing variants.

**Comment by aadilshabier** [comment]
For anyone wanting to do the same as [above](https://github.com/nlohmann/json/issues/1261#issuecomment-2048770747) for GCC and MSVC, just do this:
```cpp
namespace utils
{
  namespace details
  {
    template <typename T>
    constexpr auto make_type_name() {
      using namespace std::string_view_literals;
    #ifdef __clang__
      std::string_view name = __PRETTY_FUNCTION__;
      name.remove_prefix("auto utils::details::make_type_name() [T = "sv.size());
      name.remove_suffix("]"sv.size());
    #elif defined(__GNUC__)
      std::string_view name = __PRETTY_FUNCTION__;
      name.remove_prefix("constexpr auto utils::details::make_type_name() [with T = "sv.size());
	  name.remove_suffix("]"sv.size());
    #elif defined(_MSC_VER)
      std::string_view name = __FUNCSIG__;
      name.remove_prefix("auto __cdecl utils::details::make_type_name<"sv.size());
      name.remove_suffix(">(void)"sv.size());
    #endif
      return name;
    }
  } // details
} // utils
```
