### ISSUE TITLE
I get a json exception periodically from json::parse for the same json 

### ISSUE THREAD

**Issue by tamarlev** [nlohmann/json#1263]
this is my json file:
{
"version": 1,
"path": "C:/Users/Lists",
"arr": [1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4]
}
why am I getting a json exception on this json?and why sometimes I get it and sometimes not?

**Comment by nlohmann** [comment]
What code did you try? What was your error message?

**Comment by tamarlev** [comment]
This is the error message:
exception is [json.exception.parse_error.101] parse error at 119: syntax error - invalid literal; last read: '1 }tl'; expected end of input

**Comment by nlohmann** [comment]
This means that you are trying to parse invalid JSON. The error message states that at byte 119 of the input, you have garbage like `1}tl` which are unexpected. As this is not the JSON value above, I cannot say more about this.

**Comment by nlohmann** [comment]
@tamarlev Do you need further information?

**Comment by Vladddd46** [comment]
Всем привет, я Влад!

**Comment by GrefriT** [comment]
> Всем привет, я Влад!

Всем привет, я Влад!

**Comment by mishase** [comment]
> Всем привет, я Влад!

Всем привет, я Влад!

**Comment by nlohmann** [comment]
?
