### ISSUE TITLE
Question about get_ptr()

### ISSUE THREAD

**Issue by dariomt** [nlohmann/json#127]
I see the following in the documentation of get_ptr()

"@warning Writing data to the pointee of the result yields an undefined state."

IIUC this means that the following code yields an undefined state:
```cpp
json value = 17;
auto p = value.get_ptr<json::number_integer_t*>();
*p = 42;
```
i.e. I cannot modify the integer value inside the json

Why is this so?

**Comment by dariomt** [comment]
In fact, if "writing data to the pointee of the result yields an undefined state", why not simply return a pointer to const **in all cases**, so the compiler will make sure I cannot modify the pointee.

**Comment by nlohmann** [comment]
Hi @dariomt,

your code is not wrong in the sense that it would not compile and do what you expect, the warning only states that you _should_ not write to the pointer. A longer discussion about this can be found in #91.

Regards
Niels

**Comment by dariomt** [comment]
Sorry, I've read #91 but I still don't get it.
According to the documentation, my code would compile but "yields an undefined state".
What does "undefined state" mean in this context?
Is `value` still valid after the assignment to `p` or not?
i.e. does `value` hold a `json::number_integer_t` equal to 42?

**Comment by nlohmann** [comment]
Sorry about the confusion. It is OK to write to the pointer if you are sure that the underlying JSON object did not change. Once that object changed, the pointer is not valid any more.

**Comment by dariomt** [comment]
OK, that's much more clear now. Thanks for the clarification.
I suggest improving the documentation to make this point clear.
A good example could help:
```
json value = 17;
auto p = value.get_ptr<json::number_integer_t*>();

// writing through p is fine
// 'value' can be changed though the pointer
*p = 42;
assert( value == 42 );

// de-referencing p after an assignment to 'value' is still valid 
// as long as the assignment didn't change the type of the json object
value = 1234; 
assert( *p == 1234 ); 

// warning! *p is not valid after this assignment
// i.e. de-referencing p will yield undefined behavior
value = "doh!"
*p = 42;  // <<< K-BOOM!
```

**Comment by nlohmann** [comment]
I'll add a comment to the function in a later commit. Thanks for the discussion!
