### ISSUE TITLE
separate object_t::key_type from basic_json::key_type, and use an allocator which returns object_t::key_type

### ISSUE THREAD

**Issue by timprepscius** [nlohmann/json#1274]
- What

I would like the key_type which is searched for: 
json j = { "hi", "there" };
j.at("hi") <--- that "hi" is a going to be object_t::key_type, I believe.

To be different from the internal key type
for instance object_t::key_type might be string_view,
but the parameter types, might still be string...  but most likely would be string_view (if the internal type is string_view).

- Why?

I deal with json which has many millions of objects containing the same keys.
I would like there to be an allocator type which allocates strings in a big set of strings.  And returns the string_view of that string, rather than a new string, (or a may even return a const char * of the string.c_str())

This is close to the way the jvm allocates strings.

In this way, I would save a lot of memory, and also, key/value lookups in maps would be faster.

**Comment by timprepscius** [comment]
I made a patch which separates the internal map key type from the external map key type.  This allows for string_view to be used.  Which, in my case, collapses memory allocation considerably.  This is just a simple rough cut, will need to be redone later.

I purposefully did not do all the templatization, because I figure the owner of this repository would have clear ideas about how that should be done.

[make_string_view_as_map_key_possible.diff.txt](https://github.com/nlohmann/json/files/2474701/make_string_view_as_map_key_possible.diff.txt)

**Comment by nlohmann** [comment]
Thanks! A PR would still be very welcomed!
