### ISSUE TITLE
syntax error  on right json string

### ISSUE THREAD

**Issue by wkoroy** [nlohmann/json#1276]
I've been trying to implement this solution and I have been  getting the same  error:

```
terminate called after throwing an instance of 'nlohmann::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at 97: syntax error - unexpected '}'; expected string literal

```
My code:
```


  auto s =  create_json_config(); // return content from file jsonstr.txt
   cout<<s;
   json uuid;
   
   uuid.parse(s);
    if (uuid.is_object())
    {
        auto obj = uuid.get<json::object_t>();
        for (auto& kvp : obj)
        {
            std::cout << kvp.first << ":" << kvp.second << "\n";
        }
    }

```
[jsonstr.txt](https://github.com/nlohmann/json/files/2446468/jsonstr.txt)

**Comment by pboettch** [comment]
From your jsonstr.txt: Your JSON contains an invalid `,` at the end of object:

```JSON
{
"index":4,
"frequency":8,
"frame_index":2100,
"displace":256,
},
```
Here the `,` after 256 is invalid JSON.

**Comment by nlohmann** [comment]
@pboettch is right, and the error message hints at this: after the comma, an object key (i.e., a string literal) is expected. You can verify that `jsonstr.txt` is invalid by using, e.g., https://jsonlint.com.
