### ISSUE TITLE
how to get only "name" from below json

### ISSUE THREAD

**Issue by rijeshvp** [nlohmann/json#1278]
[{"name":"local.tar.gz.part-ab","hash":"99f7ff566a910064f774fee3acc06287","bytes":5368709120,"last_modified":"2018-10-05T16:07:37.841000","content_type":"binary/octet-stream"},{"name":"local.tar.gz.part-ac","hash":"8fab90eaff4c5c447e0076b508e11a9e","bytes":5368709120,"last_modified":"2018-10-05T16:12:21.569000","content_type":"binary/octet-stream"},{"name":"local.tar.gz.part-ad","hash":"fd2c9aec58b0de0b13117245c6baf62a","bytes":5368709120,"last_modified":"2018-10-05T16:16:54.336000","content_type":"binary/octet-stream"},{"name":"local.tar.gz.part-ae","hash":"26188ef13ec623382748faf7f7a380b2","bytes":2329785943,"last_modified":"2018-10-05T16:18:53.909000","content_type":"binary/octet-stream"},{"name":"vmohswbre024_admin.tar.gz.aa","hash":"83f43b790013c1633e354bbc0a0fd4e9","bytes":4194304000,"last_modified":"2018-10-05T17:53:40.375000","content_type":"binary/octet-stream"}]

**Comment by nlohmann** [comment]
Assuming the JSON text above is in some file `input.json`:

```cpp
std::ifstream i("input.json");
json j = json::parse(i);

// iterate the outer array
for (json& entry : j)
{
  // output the value at the "name" key
  std::cout << entry["name"] << std::endl;
}
```

**Comment by nlohmann** [comment]
@rijeshvp Do you need further support?

**Comment by rijeshvp** [comment]
Yes... please .. I forgot to mention that i am looking for a unix command... Will you be able to help me to have a unix command to extract the name element out of it.

**Comment by nlohmann** [comment]
You should try [jq](https://stedolan.github.io/jq/):

```
cat input.json | jq ".name"
```

**Comment by rijeshvp** [comment]
I am getting this output when i am running following. so i will not be redirecting this to a file.. want to format it on the fly
 curl -l -X GET \
  -u ${username}:${token}  \
  -x abc-proxy.server.com:80 \
  https://swiftobjectstorage.us-${region}-1.oraclecloud.com/v1/${tenancy}/${bucket}/${object}

**Comment by nlohmann** [comment]
Please have a look at this [tutorial](https://stedolan.github.io/jq/tutorial/)
