### ISSUE TITLE
eosio.wasmsdk error

### ISSUE THREAD

**Issue by cppfuns** [nlohmann/json#1284]
I am trying to use the following C++ JSON library:

https://github.com/nlohmann/json

Below is the code I am trying to compile with eosio-cpp gda.cpp -o gda.wasm
```cpp

#include <eosiolib/eosio.hpp>
#include <nlohmann/json.hpp>
#include <string>

using json = nlohmann::json;

class gda : public eosio::contract {
    public:
        explicit gda(action_name self) : contract(self) {}

        // @abi action
        void doit(const std::string action) {
            json j = {
                {"pi", 3.141},
                {"happy", true},
                {"name", "Niels"},
                {"nothing", nullptr},
                {"answer", {
                    {"everything", 42}
                }},
                {"list", {1, 0, 2}},
                {"object", {
                    {"currency", "USD"},
                    {"value", 42.99}
                }}
            };
            std::string d = j.dump();
        }
};

```
EOSIO_ABI( gda, (doit) )
Below is the output from trying to compile:

```
/usr/local/eosio.wasmsdk/bin/wasm-ld: error: locale.cpp.o: undefined symbol: strftime_l
/usr/local/eosio.wasmsdk/bin/wasm-ld: error: memory.cpp.o: undefined symbol: __cxa_pure_virtual
/usr/local/eosio.wasmsdk/bin/wasm-ld: error: system_error.cpp.o: undefined symbol:__cxa_pure_virtual
```
If the j.dump() line is commented out, the contract will compile.
A similar issue has been raised on stackoverflow.

https://stackoverflow.com/questions/52350514/linking-issue-with-eosio-ld

I was directed here from: EOSIO/eos#5832

**Comment by cppfuns** [comment]
The json library has been used incorrectly in the eos contract. I hope it will help here.

**Comment by theodelrieu** [comment]
I've never used eosio, but the `__cxa_*` symbols looks like it's missing `libc++abi` in the linker command line.

I don't find `strftime_l` in my `libc++`, even though there's `strftime`.

**Comment by cppfuns** [comment]
At present, the eos blockchain urgently needs a json parsing library. At present, nlohmann/json is the most suitable, but there is this error, although I don't know where the problem is, but it is very difficult.

**Comment by nlohmann** [comment]
Is it possible to get the eosio-cpp compiler somewhere and run it under, say, macOS?

**Comment by cppfuns** [comment]
> Is it possible to get the eosio-cpp compiler somewhere and run it under, say, macOS?

https://github.com/EOSIO/eosio.cdt

**Comment by cppfuns** [comment]
$ git clone --recursive https://github.com/eosio/eosio.cdt
$ cd eosio.cdt
$ ./build.sh EOS
$ sudo ./install.sh

```
Then create a new `gda.cpp` file
#include <eosiolib/eosio.hpp>
#include <nlohmann/json.hpp>
#include <string>

using json = nlohmann::json;

class gda : public eosio::contract {
    public:
        explicit gda(action_name self) : contract(self) {}

        // @abi action
        void doit(const std::string action) {
            json j = {
                {"pi", 3.141},
                {"happy", true},
                {"name", "Niels"},
                {"nothing", nullptr},
                {"answer", {
                    {"everything", 42}
                }},
                {"list", {1, 0, 2}},
                {"object", {
                    {"currency", "USD"},
                    {"value", 42.99}
                }}
            };
            std::string d = j.dump();
        }
};
```
Final execution
`eosio-cpp gda.cpp -o gda.wasm`

**Comment by cppfuns** [comment]
@nlohmann 
Are you following up on this issue? Any progress?
I am more anxious to confirm the plan here.

**Comment by nlohmann** [comment]
The errors seem to be unrelated to the library as they do not mention a library function. It seems that the compiler/STL is missing some standard features.

**Comment by nlohmann** [comment]
I am closing the issue. Feel free to reopen if you have an error more related to the library.
