### ISSUE TITLE
Release zips without tests

### ISSUE THREAD

**Issue by ibell** [nlohmann/json#1285]
The Release zip files with the tests included are rather enormous (>100 MB).  On a slow connection (for instance when having to log into corporate network through VPN), it takes absolutely ages(!) to check out the source of the repo.  Having the tests in the repo itself seems like a bit of an anti-pattern to me, but nonetheless, a useful compromise would be to also add test-free zip files because they would be much, much smaller (about 10 MB), and would result in a much faster download.

**Comment by ibell** [comment]
Also, I can't just download the header because I need the natvis file for Visual Studio and the cmake goodies.

**Comment by theodelrieu** [comment]
There is a ongoing PR #1251 that aims at solving the issue, if you happen to know git-lfs, I'll gladly take your input on it!
