### ISSUE TITLE
Enable the latest C++ standard with Visual Studio

### ISSUE THREAD

**Issue by naszta** [nlohmann/json#1287]
If the following flag would be added to MSVC part, the MSVC C++14 and C++17 features could be used in the code (including `std::string_view` and variadic template `std::less`).
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /std:c++latest")
```
I'm happy to write the code (opt-out as the latest VS runs properly with all tests passed).

**Comment by nlohmann** [comment]
Is it good style to set these flags from the project? Wouldn't this be something the user sets?

**Comment by naszta** [comment]
In visual studio project I specify explicitly `/std:c++14` or `/std:c++17`. But for tests or libs (when both VS 2015 and VS2017 should be supported) I definitely would use the latest flag.

**Comment by nlohmann** [comment]
I'm not using MSVC myself, that's why I would like to discuss whether it is best practice to set such switches.

**Comment by gregmarr** [comment]
What features are you looking to use, and how would you make sure that the library is still usable with only C++11?

**Comment by naszta** [comment]
There are standard switch macros in the code. They are set accordingly on used standard by the compiler. With this flag always the latest standard could be used what supported by VS. (In current code variadic `less` and `string_ref` are protected by these macros.)

**Comment by nlohmann** [comment]
I still have not understood why this library should set the C++ version when this is usually done by the code that actually uses the library. Do I miss something between CMake and MSVC?

**Comment by naszta** [comment]
No: my idea here is using the latest supported C++ in MSVC even in tests: MSVC is not a major platform for you and in this way you will have less macros for VS (as it uses the latest standard what it could handle).

**Comment by nlohmann** [comment]
I am already testing with these flags on AppVeyor. And if I would remove macros, wouldn't this break support for older MSVC versions?

**Comment by naszta** [comment]
The flag is supported since Visual C++ 2015 Update 3. If older VS versions are supported in tests, it shouldn't be introduced. Otherwise it's safe to go.

**Comment by nlohmann** [comment]
I still have not understood the benefit of enforcing this flag to projects using the library. FWIW, we use this [AppVeyor configuration](https://github.com/nlohmann/json/blob/develop/appveyor.yml), where we *additionally* check `/permissive- /std:c++latest /utf-8` for MSVC 2017.

**Comment by naszta** [comment]
Ok, nevermind.
