### ISSUE TITLE
merge_patch: inconsistent behaviour merging empty sub-object

### ISSUE THREAD

**Issue by adam-p** [nlohmann/json#1289]
When using `merge_patch` with an object like `{{"k", {}}}`, different results are obtained than with other methods for providing an empty object.

Example: https://wandbox.org/permlink/7SDUyC98tSZX7sPL

Like...
```
start with: {"k":{"a":"b"}}

merge_patch({{"k", json({})}}) --> {"k":{"a":"b"}}

merge_patch({{"k", {}}}) --> {}
```

It may be that I'm confused about what `{}` _means_ here. If it's equivalent to `null`, then I think this makes sense. But I don't see anything in the README about that being the case.

**Comment by gregmarr** [comment]
JSON Merge Patch is defined here: https://tools.ietf.org/html/rfc7386

     define MergePatch(Target, Patch):
       if Patch is an Object:
         if Target is not an Object:
       Target = {} # Ignore the contents and set it to an empty Object
         for each Name/Value pair in Patch:
       if Value is null:
         if Name exists in Target:
           remove the Name/Value pair from Target
       else:
         Target[Name] = MergePatch(Target[Name], Value)
         return Target
       else:
         return Patch

>   There are a few things to note about the function.  If the patch is
   anything other than an object, the result will always be to replace
   the entire target with the entire patch.  Also, it is not possible to
   patch part of a target that is not an object, such as to replace just
   some of the values in an array.
>
>   The MergePatch operation is defined to operate at the level of data
   items, not at the level of textual representation.  There is no
   expectation that the MergePatch operation will preserve features at
   the textual-representation level such as white space, member
   ordering, number precision beyond what is available in the target's
   implementation, and so forth.  In addition, even if the target
   implementation allows multiple name/value pairs with the same name,
   the result of the MergePatch operation on such objects is not
   defined.

**Comment by gregmarr** [comment]
So I agree that this looks like `{}` is being treated as `null`.

**Comment by gregmarr** [comment]
// create a JSON object
    json j = {};
    
    j.merge_patch({{"k", {}}});
    std::cout << "{}: " << j.dump() << std::endl << std::endl;

since `j` is `null`, I would expect `{}` here to be `null` as well.

**Comment by nlohmann** [comment]
@adam-p Do you need further assistance or can we close this issue?

**Comment by adam-p** [comment]
I'm good. Thanks. (Sorry for the delayed response.)
