### ISSUE TITLE
How do I go about customising from_json to support __int128_t/__uint128_t?

### ISSUE THREAD

**Issue by dubnde** [nlohmann/json#1290]
This is really more of a question than an issue. I hope this is not too much trouble as I continue to discover what this library can help us with.

I am thinking of reading big values from a `json` file. I am wondering how to go about customising the `from_json` to support such. For instance the extended values of `__int128_` and `__uint128_t` supported on some compilers. Or even some of those from the boost multiprecision library such as `cpp_int`. Is it possible to implement a `from_json` for such types and how would one go about it if so?

thanks once more

**Comment by theodelrieu** [comment]
Hello,

In theory you *could* specialize `adl_serializer` on the types you mention. However, if you want to fiddle with the internal way of serializing JSON Numbers, this is not currently possible I'm afraid.

There is an `external_constructor` in `detail/conversions/to_json.hpp` which deals with it, it is a `friend` of `basic_json`.

At the time of implementing `to_json/from_json` mechanism, I did not find a good way to provide such low-level support, and thought that I'd wait for a real use-case to start thinking about it :)

**Comment by dubnde** [comment]
Okay. Thanks very much for the response. Your response at least clarifies I was not misreading the API. 

I also think I may achieve what I need with implementing the sax parser API since it passes through the string representation of the number as a double if such a number cannot fit into `int64_t `or `unit64_t`
