### ISSUE TITLE
unicode: char16_t* is compiler error, but char16_t[] is accepted

### ISSUE THREAD

**Issue by igoloe** [nlohmann/json#1297]
- What is the issue you have?
nlohman::json{char16_t*} is a compiler error, but nlohman::josn{char16_t[]) is accepted
- Please describe the steps to reproduce the issue. Can you provide a small but working code example?
just compile as described
- What is the expected behavior?
char16_t* and char16_t[] should be handled the same way. 
Because both define a utf16 sequence, automatic conversion to utf8 is expected.
Same is true for u16string and u16string_view.
- And what is the actual behavior instead?
char16_t* is a compile error and char16_t[] is stored as array of values.
- Which compiler and operating system are you using? Is it a [supported compiler]
visual studio 2017 15.4.1
- Did you use a released version of the library or the version from the `develop` branch?
released, 3.1.2

**Comment by nlohmann** [comment]
How is this issue related to #1298?
