### ISSUE TITLE
unicode: accept char16_t, char32_t sequences

### ISSUE THREAD

**Issue by igoloe** [nlohmann/json#1298]
- Describe the feature in as much detail as possible.
it woudl be nice, if the lib can accept any char16_t and char32_t sequences and convert them to utf8 automatically, because most unicode strings in windows would be stored as u16string (non legacy code ofc) to distinguish it from ansi like in std::string. List of sequence like usage (maybe incomplete): charT*, charT[], basic_string<charT>, basic_string_view<charT> where charT from {char16_t,char32_t}
- Include sample usage where appropriate.
any usage of unicode in a type safe manner in c++ under windows (explicitly exlcuding std::wstring)

**Comment by nlohmann** [comment]
With "accept", I assume you do not mean parsing (the library already supports parsing from `std::u16string`), but assignments, right?

**Comment by igoloe** [comment]
As with release 3.1.2 there was no support as arguments of json ctor for char16_t[] and char16_t* or u16string and u16string_view. First one was interpreted as array of values, other ones were rejected by compiler. I am not sure, if this changed in 3.3 already.
Requesting support for char32_t was just for logical completeness.
If the lib already supports construction, then please reject my request and i will test again with the latest version.

**Comment by nlohmann** [comment]
If possible, please provide concrete examples.
