### ISSUE TITLE
Add to_string overload for indentation

### ISSUE THREAD

**Issue by tanadeau** [nlohmann/json#13]
Create an overload of the `to_string` member function that handles indentation (spaces) and line breaks.

```cpp
const std::string to_string(int indent) const noexcept
```

**Comment by kelvinh** [comment]
Yeah, I think this is needed when saving a json object to file, it is a great mess if there is no indentation and line breaks.

**Comment by nlohmann** [comment]
I implemented a pretty-printing serialization. For that, I renamed the function `to_string()` to `dump()` and used the syntax of Pythons `json.dumps()` (see https://docs.python.org/2/library/json.html#json.dump). 

This function takes an integer as parameter:
- If the parameter is -1, no pretty printing is done and the result is the same as before.
- If the parameter is 0, then newlines are added after elements in arrays and objects.
- If the parameter is positive, then this number of spaces is used as indentation.
