### ISSUE TITLE
Xcode - adding it to library 

### ISSUE THREAD

**Issue by changheon1** [nlohmann/json#1300]
Using XCode and Cmake for my project.
<img width="596" alt="screen shot 2018-10-16 at 6 49 18 pm" src="https://user-images.githubusercontent.com/26236887/46995226-42af5b00-d174-11e8-9f4f-b1ef4bb5e38e.png">

I am stuck on how to get json to be added to the library. 
What I want to do is: 
I have my codes inside work/src/ folder and have json files inside work/vendor.
Inside build I have done the cmake commands. (cmake -G Xcode ../work)
after it builds I run my code in XCode but the 
#include <nlohmann/json.hpp> is not found and I get heaps of errors in the json file.

I think this occurs because I am not adding a 'Link Binary with Libraries' for XCode but it's weird how I don't have that in 'Build Phase'
<img width="752" alt="screen shot 2018-10-16 at 6 55 38 pm" src="https://user-images.githubusercontent.com/26236887/46995425-37a8fa80-d175-11e8-85b8-c82581bb8b56.png">

Any help would be appreciated!

**Comment by changheon1** [comment]
Okay.. I've finally added #include <nlohmann/json.hpp> and it doesn't throw an error on that but not I am getting endless errors on the actual json.hpp file
<img width="1132" alt="screen shot 2018-10-16 at 9 11 05 pm" src="https://user-images.githubusercontent.com/26236887/47001956-2c12ff00-d188-11e8-8618-cf41cc968c9b.png">

I think I'm the only one with this kind of issue but I really hope to fix this... 
Any help would be appreciated thanks..

**Comment by nlohmann** [comment]
That is really strange, because we can compile and run the unit tests with Xcode. Could you try to compile the unit tests?

**Comment by jaredgrubb** [comment]
This looks like a too-early version of C++. What version of C++ are you compiling with? (Eg, can you copy-paste the command line that is being executed to compile this?)

**Comment by nlohmann** [comment]
FWIW: The library is tested with Xcode 6.4-10.0, see https://github.com/nlohmann/json#supported-compilers.

**Comment by changheon1** [comment]
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

I did update my mac 2 days ago with Xcode because it wouldn't update the build, also my lecturer has updated that because of the same reason. 

So what I've tried is: 
1) If I use cmake browse source just on the json-3.3.0 and compile, it generates no errors whereas if I do the browse source on my work folder and generates it, it generates heaps of errors as you can see for the second image.
2) I went into the 'build -> vendor -> json-3.3.0' and opened the project folder then built it, generates just hundreds of errors. Weird how this one looks the same with step 1) with no error version but still generates errors. 

![44149981_364011757474513_9018590787910238208_n](https://user-images.githubusercontent.com/26236887/47051504-f827f000-d200-11e8-885e-fb6edf68c1b1.png)


Maybe it's not the version of the Xcode or the c++ version, I may be missing out a step since it did generate no errors for the first step.
Cheers.

**Comment by changheon1** [comment]
Maybe the c++ or the Xcode version.. I've tried heaps of other way but getting same error.

Tried only building using json and it thought it wouldn't generate any errors but after making a main.cpp and #include <nlohmann/json.hpp> then using json=nlohman::json it generated same errors as before.
Any suggestions for this issue?

**Comment by jaredgrubb** [comment]
Can you copy-paste the command line invocation used? The fact that you're getting a failure around "enable_if_t" suggests that you probably don't have C++14 turned on. Or just look in your Build Settings to see what the version of C++ you have enabled.

**Comment by changheon1** [comment]
I used 
cmake -G Xcode (filename)

Couldn't find anything to allow c++ 14 or similar to my build setting

**Comment by changheon1** [comment]
<img width="1135" alt="screen shot 2018-10-17 at 1 37 24 pm" src="https://user-images.githubusercontent.com/26236887/47055032-e26ef680-d211-11e8-866a-d8d7813bad05.png">

I did find enabling c++14 but still generates same errors...

**Comment by nlohmann** [comment]
Any news on this?
