### ISSUE TITLE
Problem in Dockerfile with installation of library

### ISSUE THREAD

**Issue by DragonOsman** [nlohmann/json#1304]
I'm trying to build a Dockerfile for the project I've been working on that uses this library.  The Dockerfile build output can be seen on this Paste: https://pastebin.com/hT1Ha6Lc .  Could someone please tell me what I did and what I didn't do that I should've done?  If needed, I'll also post the main part the problem is at:
```
Step 8/12 : RUN g++ -std=c++14 -Wall -pedantic -I app/jinja2cpp/install/include -I app/json/include -I app/json/single_include -I /usr/local/include/ -I app/jinja2cpp/thirdparty/nonstd/value-ptr-lite/include currency_converter.cpp -L app/jinja2cpp/install/lib/static -ljinja2cpp -L usr/local/lib/stage/lib/ -lboost_system -lpthread -o currency_converter
 ---> Running in bfb27a00d9c8
currency_converter.cpp:29:10: fatal error: nlohmann/json.hpp: No such file or directory
 #include <nlohmann/json.hpp>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```
Any help is appreciated.  Thanks in advance.

**Comment by nlohmann** [comment]
Is this the same issue as #1296?

**Comment by nlohmann** [comment]
What is the content of directory `app/json/include`?

**Comment by DragonOsman** [comment]
I just ran this command to see what's in there:
```
RUN git clone https://github.com/nlohmann/json \
    && cd json \
    && ls
```
Waiting for it to get to the `ls` part.

**Comment by nlohmann** [comment]
You provided both single_include and include. One is sufficient. Please see the README for integration information.

**Comment by DragonOsman** [comment]
What about when I want to use `json_fwd.hpp`, though?

**Comment by nlohmann** [comment]
Then just use include

**Comment by DragonOsman** [comment]
Alright, thanks.  I think this is solved now.
