### ISSUE TITLE
Change json_pointer to provide an iterator begin/end/etc, don't use vectors, and also enable string_view

### ISSUE THREAD

**Issue by timprepscius** [nlohmann/json#1312]
I'm doing almost all interactions with my json trees via json_pointer.
The json pointer's vector is a performance bottle neck.

In my view, json_pointer should have the pointer_type be defined in the template specialization.
(so that I can easily turn on string_view)

And it should never split the strings into a vector, but rather allow for iteration, do on-the-fly-unescaping as needed.

In my my case, the speed up is quite considerable.

Also, this goes hand in hand with moving the object_t key_type to a separate template parameter.
(so that I can easily turn on string_view in the basic_json as well)

Will post a PR prob thurs/fri.  Will just make a new json_pointer class and if def, instead of making changes, might be useful to test one against the other.

**Comment by nlohmann** [comment]
Thanks for proposing an improvement!

I am really interested to see an example where the overhead of the current string/vector approach is measurable! It would be great to have this as a benchmark.

I would really look forward to a PR - just one remark: the library targets C++11, so an approach using `std::string_view` is not suitable, I'm afraid.
