### ISSUE TITLE
Splitting source

### ISSUE THREAD

**Issue by dariomt** [nlohmann/json#132]
Hi,
I appreciate the ease of deploying a single header file.
But, I think it would be better to decouple the different pieces of functionality.

I propose splitting the single json.hpp header file into three parts:
- json_fwd.hpp with only the forward declarations of template basic_json and the alias json
- json.hpp with the definition of template basic_json but without the io (and without the dependency to all the very heavy standard io related headers)
- json_io.hpp with the definition of the io funcitonality, i.e. parsing, streaming, etc...

Do you think this is feasible?

**Comment by nlohmann** [comment]
I don't think splitting is a good idea, because it makes using the code harder. Furthermore, it is hard to draw a line between "core functionality" and io, because implicit conversions and operator overloading are hard to classify.

**Comment by dariomt** [comment]
OK, understood.
Would you consider adding just the header with the forward declarations?
It makes it easier to write code that depends only on the **declaration** of basic_json.

**Comment by nlohmann** [comment]
Is there a way to create such a header automatically? I would like to avoid a manual step every time something is changed.

**Comment by dariomt** [comment]
I don't think so.
Forward declarations have to be manually synchronized with the definitions.

**Comment by nlohmann** [comment]
I also thought so. I am currently not planning to distribute the code over several files. The 1-file solution is a feature I would like to keep.
