### ISSUE TITLE
Implicit type conversion error on MSVC

### ISSUE THREAD

**Issue by kjpus** [nlohmann/json#1333]
- What is the issue you have?
Wrong type is deduced when json object is use in an expression with some other arithmetic types.

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

```cpp
// Compiled using MSVC 15.8.8
#include <iostream>
#include "nlohmann/json.hpp"

int main()
{
    nlohmann::json _j = R"({"Value":12.34})"_json;
    double x = _j["Value"]; // prints 12.34 here
    double y = _j["Value"] * 0.01; //prints 0.12 here
    std::cout << x << "  " << y << '\n';
    return 0;
}
```

- What is the expected behavior?
It should either fail to compile (as it does in gcc and clang), or deduce the correct type when mixed with  arithmetic types in an expression and prints 12.34 and 0.1234.

- And what is the actual behavior instead?
MSVC compilation succeeds without error/warning (with /W4 and /permissive- flag). The second `_j["Value"]` calls the implicit conversion function with unsigned int type, converts it to double, then does the multiplication. It prints 12.34 and 0.12 instead.

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?
MSVC 15.8.8 on Windows 10, x64

- Did you use a released version of the library or the version from the `develop` branch?
3.3 (through vcpkg)

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?
No compilation error.

**Comment by nlohmann** [comment]
I can confirm the code does not compile with Clang (tried Xcode 10). I also agree that the result right now is wrong, but I am not sure why MSVC behaves differently here.

**Comment by kjpus** [comment]
My current workaround is to provide operators for json type and an arithmetic type, e.g. 
```
template <typename T, typename = std::enable_if_t<std::is_arithmetic_v<T>>> 
T operator*(const nlohmann::json& _j, T v)
{
    return _j.get<T>() * v;
}
```
It solves the problem but I'm wondering if there is a more elegant way.

**Comment by theodelrieu** [comment]
Please use `auto v = _j["Value"].get<double>();` instead.

#1363 was merged recently to advise against using implicit conversions from a JSON value.

You can look at #958 for why that is recommended.

**Comment by kjpus** [comment]
Thanks for your response. 

If implicit conversion is allowed but can potentially produce wrong result, it might be a good idea to disable it all together, at least for MSVC.

BTW, I created a PR as the link to #958 is broken in ReadMe.md.
