### ISSUE TITLE
Improve number-to-string conversion

### ISSUE THREAD

**Issue by nlohmann** [nlohmann/json#1334]
The [`dump_integer`](https://github.com/nlohmann/json/blob/d2e6e1bf5852d9c8f2470c7c99eb6e600bb79138/include/nlohmann/detail/output/serializer.hpp#L543) function is naive custom code and the [`dump_float`](https://github.com/nlohmann/json/blob/d2e6e1bf5852d9c8f2470c7c99eb6e600bb79138/include/nlohmann/detail/output/serializer.hpp#L584) function uses a Grisu2 implementation. This leaves a lot of room for improvements.

In C++17, we could use [`<charconv>`'s `std::to_chars`](https://en.cppreference.com/w/cpp/utility/to_chars) as pointed out by [u/STL](https://www.reddit.com/r/cpp/comments/9ss87p/json_for_modern_c_version_340_released/e8trm5m) and live happily ever after. Unfortunately, we are still sticking around with C++11.

Examples for code to try are:

- https://gist.github.com/Veedrac/069dd35f896de4df4e14b881a455ca47 (CC0, see also https://www.reddit.com/r/programming/comments/7ljzty/how_to_print_integers_really_fast_with_source_code/dro1umo)
- https://github.com/ulfjack/ryu (Boost / Apache2)
- https://pvk.ca/Blog/2017/12/22/appnexus-common-framework-its-out-also-how-to-print-integers-faster/ (Apache2)

Maybe there are other projects, too.

It would be great to try different implementations. The largest piece of work should usually be to make it run as single header, and to adjust it to the interface.

**Comment by nlohmann** [comment]
#1411 tackled the integer part.

**Comment by victor-varjo** [comment]
> In C++17, we could use [<charconv>'s std::to_chars](https://en.cppreference.com/w/cpp/utility/to_chars) as pointed out by [u/STL](https://www.reddit.com/r/cpp/comments/9ss87p/json_for_modern_c_version_340_released/e8trm5m) and live happily ever after.

I wish it was so, but even the `__cpp_lib_to_chars` feature test macro doesn't guarantee that `to_chars` works with floats. If you ever decide to implement it with some sort of feature probing or gating here is a test case for you:
0x1.e69a800000000p+0
Grisu2 -> "1.9007949829101563"
std::to_chars -> "1.9007949829101562"
