### ISSUE TITLE
Non-verifying dump() alternative for debugging/logging needed

### ISSUE THREAD

**Issue by extmchristensen** [nlohmann/json#1335]
I have an embedded application using json.hpp v3.2.0 that mysteriously fails when stresstesting on a foreign lab-setup outside my PC. From the log I can see the reported error "Invalid UTF-8" error at index 1 : 0xF5" but nothing more.

I can not debug the software directly, so I would like to log the illegal json as a string or hex dump, so I can better diagnose the problem.

Would it be possible to provide a non-verifying dump() method, that could make a best effort to print out as much as possible of the json - even in the presence of such errors? With such a method I could inspect the output and use a process of elimination to better locate the part of the json that has a problem.

**Comment by nlohmann** [comment]
That means that the first or second byte is `0xF5` which is not valid in UTF-8.

With the latest [release 3.4.0](https://github.com/nlohmann/json/releases/tag/v3.4.0), it is possible to tell the dump function how to react on invalid Unicode, see [the documentation](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a50ec80b02d0f3f51130d4abb5d1cfdc5.html#a50ec80b02d0f3f51130d4abb5d1cfdc5), in particular the error handlers. There is also an example.

**Comment by extmchristensen** [comment]
Great - that should work - thanks a lot !!
