### ISSUE TITLE
Protect macro expansion of commonly defined macros

### ISSUE THREAD

**Issue by SylvainCorlay** [nlohmann/json#1337]
Wrapping `std::min` and `std::max` in parentheses prevents the expansion of windows' `min` and `max` macros. I agree these should have never existed in the first place, but that would allow windows users to make use of `nlohmann_json` without setting `NOMINMAX`.

Similarly, `Python.h` defines `snprintf` as a macro. Wrapping calls in parentheses would also prevent the expansion of this macro.

So the fix would be to replace instances of `std::min` with `(std::min)`, and similarly for `std::max` and `std::snprintf`.

**Comment by nlohmann** [comment]
I am not sure what this issue proposes - adding parentheses around `min` and `max`? Then point me to a place where the parentheses are missing.

**Comment by SylvainCorlay** [comment]
Sorry if I was not clear. I was suggesting to do the same with `snprintf` as for `min` and `max`, that is to wrap it in parentheses. `snprintf` is defined as a macro by Python.h (as equal to `_snprintf`).

I met the issue for `std::snprintf`, which is used in `serializer.hpp` and `binary_reader.hpp`.

**Comment by nlohmann** [comment]
Thanks for clarifying! I shall have a look.

**Comment by nlohmann** [comment]
Thanks for clarifying! I shall have a look.

**Comment by nlohmann** [comment]
@SylvainCorlay Could you please check whether https://github.com/nlohmann/json/tree/feature/snprintf fixes the issue?

**Comment by SylvainCorlay** [comment]
@nlohmann thanks! I could check and it works perfectly!

**Comment by nlohmann** [comment]
Thanks for the feedback!

**Comment by SylvainCorlay** [comment]
Thanks @nlohmann. And thanks for the great work on this library!
