### ISSUE TITLE
Copy-construct using initializer-list converts objects to arrays

### ISSUE THREAD

**Issue by arrtchiu** [nlohmann/json#1359]
I seem to have hit a bug in either this library / MSVC. Here's a minimal repro case:

```
struct MyObj {
 json mJson;
 explicit MyObj(json const& input) : mJson{input} {}
};

json j = json::object();
j["foo"] = "bar";
j["baz"] = "ba";
auto x = std::make_shared<MyObj>(j);

std::cout << obj->mJson.dump() << std::endl;
```

Output:
```
J: {"baz":"bah","foo":"bar"}
J: [{"baz":"bah","foo":"bar"}]
```

Interestingly, changing the initialiser from `mJson{input}` to `mJson(input)` produces the correct output:

```
J: {"baz":"bah","foo":"bar"}
J: {"baz":"bah","foo":"bar"}
```

I'm currently using 3.1.2 but confirmed it also reproduces on latest 3.4.0

**Comment by theodelrieu** [comment]
Indeed, using braces when a `initializer_list` constructor is present will pick that constructor, this is a bit tricky.

**Comment by nlohmann** [comment]
This is expected behavior, I'm afraid.

**Comment by arrtchiu** [comment]
Crikey thanks for the amazingly fast reply! I guess the solution is not to use braces for initialising members!

**Comment by arrtchiu** [comment]
Looks like a Clang bug, since the output on Clang for both variants of the code is:

```
J: {"baz":"bah","foo":"bar"}
J: {"baz":"bah","foo":"bar"}
```

GCC behaves the same as MSVC in this case.

I'll file a bug over there. Thanks again for the fast replies!

**Comment by nlohmann** [comment]
Great! Please let us know about the progress of the filed bugs!

**Comment by arrtchiu** [comment]
Clang developers pointed me to this: https://clang.llvm.org/cxx_dr_status.html#2137

Sounds like it’s an unresolved ambiguity in the c++ spec itself.
