### ISSUE TITLE
json::dump() silently crashes if items contain accented letters

### ISSUE THREAD

**Issue by pietro68** [nlohmann/json#1365]
- If a string field contains accented letters (e.g. à è ), a json::dump to std::string will silently crash

- run this simple snippet:
`void foobar()
{
 using namespace nlohmann;
  json foo = { "resumè" };
  std::string bar = foo.dump(4);
}
`

- I expect the .dump operation to complete without problems...

- ...but instead, it silently crashes (i.e. control flow goes out of scope of foobar() )

- compiler: Visual Studio 2015 version 14.0.25431.01 update 3; Windows 10

- Did you use a released version of the library or the version from the `develop` branch? yes

**Comment by nlohmann** [comment]
Can you provide more information on the crash? An exception? A stack trace?

**Comment by pietro68** [comment]
Sure. Code snippet upgraded to:
`{
  try
  {
    json foo = { "resumè" };
    std::string bar = foo.dump(4);
  }
  catch (std::exception& e)
  {    
    std::cout << e.what() << std::endl;
  }
}
`

And it prints out: 

**[json.exception.type_error.316] incomplete UTF-8 string; last byte: 0xE8**

**Comment by pietro68** [comment]
Thanks, this solved it. Apologies for not looking deeper. VisualStudio comes out of the box with codepage 1252 as the default encoding, I did not realize it.
