### ISSUE TITLE
Deserialize

### ISSUE THREAD

**Issue by Akirame** [nlohmann/json#1366]
There's a way to deserialize a Json file to a Json object? i have a json file that contains data and i need to read that

**Comment by nlohmann** [comment]
Please have a look at the project‘s README file. It is all explained there.

**Comment by Akirame** [comment]
Sorry for the question, i have this Json, how can i do to refer to "layers","height"? i tried 
json j["layers"]["height"] and i cant retrieve that data, thank you

`"height":32,
 "infinite":false,
 "layers":[
        {       
         "height":32,
         "id":1,
         "name":"Tile Layer 1",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":32,
         "x":0,
         "y":0
        }],`

**Comment by gregmarr** [comment]
`layers` is an array, so for this example you need `j["layers"][0]["height"]`.

**Comment by nlohmann** [comment]
@Akirame Did @gregmarr 's answer fix the issue?
