### ISSUE TITLE
Writing and reading BSON data

### ISSUE THREAD

**Issue by snirgaz** [nlohmann/json#1368]
I would like to read and write my data to a file using the BSON format.
It would be nice to have an example explaining how to achieve that.

The conversion to BSON format is explained very cleary,
`std::vector<std::uint8_t> v_bson = json::to_bson(j);`
What is less clear (atleast to me) is how to write (and subsequently read) v_bson to a binary file while maintaining compatability with the BSON file format allowing it to be read by python e.g.

**Comment by nlohmann** [comment]
Here is the documentation of the relevant functions:

- [`to_ubjson`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_ae1ece6c2059114eac10873f13ef19185.html#ae1ece6c2059114eac10873f13ef19185)
- [`from_ubjson`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a98ef289216564da59a78903a5cabfc8a.html#a98ef289216564da59a78903a5cabfc8a)

Do you need more information?

**Comment by snirgaz** [comment]
Thanks for pointing me in the right direction!
