### ISSUE TITLE
#define or ||

### ISSUE THREAD

**Issue by SapphireBrand** [nlohmann/json#1379]
- What is the issue you have?

I had a variable named "or", and my compiler issues an error message about "unexpected ||", so I guessed that there might be a stray #define that has not been #undefed.

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

I expect the header library to only export genuinely public symbols. Maybe #undef 'or' before the end of the header, or do without the #define.

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by nlohmann** [comment]
`or` is an operator, see https://en.cppreference.com/w/cpp/language/operator_alternative. You should not use it as a name.
