### ISSUE TITLE
float precision

### ISSUE THREAD

**Issue by vassilisw** [nlohmann/json#1384]
When a float is dumped and becomes float again via json::parse, looses precision

```
    json jjj;
    jjj["f"] = 11.123456789;
    float f = json::parse(jjj.dump())["f"];
    std::cout << f << std::endl;

```

expected: 11.12345678..
getting: 11.1235

Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0

Is there any way to increase precision?

**Comment by gregmarr** [comment]
Yes, increase your output precision:

    std::cout.precision(12);
    std::cout << f << std::endl;
