### ISSUE TITLE
using unordered_map as object type

### ISSUE THREAD

**Issue by eyun221** [nlohmann/json#1385]
following code can't not be compiled, for issue https://github.com/nlohmann/json/issues/164
```cpp
using json = nlohmann::basic_json<std::unordered_map>
```

is there some method to use unordered_map as Object type? For its better performance.

- Describe the feature in as much detail as possible.

- Include sample usage where appropriate.

**Comment by nlohmann** [comment]
No, this unfortunately still does not work.

**Comment by t-b** [comment]
@nlohmann What would need to change to support `std::unordered_map`?

**Comment by nlohmann** [comment]
I guess the template arguments would need to be adjusted. Not sure whether it’s possible to do this that (a) both std::map and std::unordered_map work and (b) the API does not break.
