### ISSUE TITLE
Error Code Return

### ISSUE THREAD

**Issue by dhruveshg** [nlohmann/json#1386]
- No error code is returned and it crashes if the "key" is not found. I am new to this library, am I missing something? Could it return error code, or the only way to avoid crashing is to use exception handling?

json jProfile;
std::ifstream f(profileFile);
f >> jProfile;
jProfile.at("CONFIG").at(std::to_string(1)).get_to(configFileName);

**Comment by RPGillespie6** [comment]
`.at()` throws an `json::out_of_range` if the key is not found. Also, this code with throw `json::parse_error` if `profileFile` is not valid json. You should wrap the whole thing with:

```
try {
    json jProfile;
    std::ifstream f(profileFile);
    f >> jProfile;
    jProfile.at("CONFIG").at(std::to_string(1)).get_to(configFileName);
} catch (json::exception & ex) {
    cout << "Uh oh, I messed up: " << ex.what() << endl;
}
```

**Comment by dhruveshg** [comment]
Thanks, I understand the implementation better now.
