### ISSUE TITLE
Get value without explicit typecasting

### ISSUE THREAD

**Issue by mprat** [nlohmann/json#1395]
I was wondering if there was a way to get the underlying value of an object without explicit typecasting. Here is what I mean:

```
json j = R"({"int_type": 3})"_json;

auto i_what_is_this = j["int_type"];

// to get an int, I need to explicitly typecast
auto i_int = j["int_type"].get<int>();
```

JSON natively supports different types, so is there a way to use that underling type to get `auto i = j["int_type"];` to be of type `int` without explicitly typecasting?

**Comment by gregmarr** [comment]
No, the type in the object is a runtime type, and auto requires compile-time types.  In this case, `i_what_is_this` is `json`.

**Comment by nlohmann** [comment]
@gregmarr is right. The only stylistic choice you have is to replace

```cpp
auto i_int = j["int_type"].get<int>();
```

by

```cpp
int i_int = j["int_type"];
```
