### ISSUE TITLE
sorry this is not an issue, just a Question, How to change a key value in a file and save it ?

### ISSUE THREAD

**Issue by FahedSabellioglu** [nlohmann/json#1398]
- Describe the feature in as much detail as possible.

- Include sample usage where appropriate.

**Comment by FahedSabellioglu** [comment]
The major problem is to change a value in a file and save it back, but this did not seem possible, I tried to do it with boost library, but it just corrupts the format when it saves.
I tried to save the data locally and write them back to a file, but how can I organize them since there are repeated keys with different values;
 [{
  Id= 1
  Name = David
},
{
  Id = 2
  Name = Katja
},
{
  Id = 3
  Name = Luka
}]

**Comment by nlohmann** [comment]
How does the code look like that you tried? What does the error look like?

**Comment by FahedSabellioglu** [comment]
Sorry, the code might not be that good, I'm a beginner to c++.
I tried to find the user I want and then find the json file and change it and close the file.
this is a function in a class
void Change_status()
	{

		//looking for an attribute to find the username I need
		if (UserName == "xxlea09xx")
		{ // changing the following_status attribute to true
			Following_status = true;
			std::list<Twitter_user> Reference_list;
			std::ifstream in("@CompGlyndwr_Followers.json");
			json File = json::parse(in);
			for (auto Json_Block : File)
			{
				if (Json_Block["screen_name"] == "xxlea09xx")
				{
					Json_Block["/following"_json_pointer] = true;
					in.close();
				}

			}
		}

**Comment by FahedSabellioglu** [comment]
I tried to follow the documentation in the method used for writing and save the data into a totally different file, but since I couldn't figure out how to separate the blocks, the keys were overwritten.

and I just want to ask is it possible to store the json data in a vector or a list ? just to write it back to the files with changed values.

**Comment by nlohmann** [comment]
The input from https://github.com/nlohmann/json/issues/1398#issuecomment-449135537 seems to be unrelated to https://github.com/nlohmann/json/issues/1398#issuecomment-449137705.

**Comment by nlohmann** [comment]
To answer the question in the title:

- You can change a JSON value by using the `operator[]`: If your JSON value `j` is an array of objects, then `j[3]["foo"]` goes to the 4th element of the array and accesses the value at object key "foo". You can set it to another value by simply `j[3]["foo"] = true;` or `j[3]["foo"] = "bar";`.
- JSON values can be stored to a file with `myfile << j;`.
