### ISSUE TITLE
-Wmismatched-tags in 3.5.0?

### ISSUE THREAD

**Issue by past-due** [nlohmann/json#1401]
While I'm aware of the workarounds, I thought you might find the following interesting.

- What is the issue you have?

`-Wmismatched-tags` using Clang v6.0 on Ubuntu 18.04:

```
json.hpp:1799:1: error: 'tuple_size' defined as a class template here but previously declared as a struct template [-Werror,-Wmismatched-tags]
class tuple_size<::nlohmann::detail::iteration_proxy_value<IteratorType>>
^
/usr/include/c++/7.3.0/utility:84:5: note: did you mean class here?
    struct tuple_size;
    ^
[...]
json.hpp:1803:1: error: 'tuple_element' defined as a class template here but previously declared as a struct template [-Werror,-Wmismatched-tags]
class tuple_element<N, ::nlohmann::detail::iteration_proxy_value<IteratorType >>
^
/usr/include/c++/7.3.0/utility:129:5: note: did you mean class here?
    struct tuple_element;
    ^
2 errors generated.
```

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

Attempted to update [Warzone 2100](https://github.com/Warzone2100/warzone2100) from nlohmann/json 3.4.0 to 3.5.0.
(Compilation succeeds with 3.4.0. CI treats many warnings as errors. `-std=gnu++11`)

- What is the expected behavior?

Compilation succeeds without error / warnings.

- And what is the actual behavior instead?

[-Wmismatched-tags] is triggered

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

The CXX compiler identification is Clang 6.0.0
on Ubuntu 18.04

- Did you use a released version of the library or the version from the `develop` branch?

3.5.0 release

**Comment by past-due** [comment]
An additional reference on this issue:

- [struct vs. class when specialising tuple_element/tuple_size](https://groups.google.com/a/isocpp.org/forum/#!topic/std-discussion/QC-AMb5oO1w)

**Comment by nlohmann** [comment]
Thanks for reporting. I had a warning before I released and adjusted the code wrt. to the examples from cppreference.com. Now, I do not get any warning with GCC 9 and Clang 8.

**Comment by past-due** [comment]
It looks like this might be fixed in Clang 8, but Clang 7 may also trigger it. (Was playing around with a small example linked in the isocpp group post above.)

@nlohmann: Would disabling the `-Wmismatched-tags` warning for Clang around the `tuple_size` and `tuple_element` specializations (similar to what @Naios suggested) be an acceptable PR?

**Comment by nlohmann** [comment]
@past-due Yes, of course are PRs welcome!

**Comment by theodelrieu** [comment]
Note that the C++ standard declares `tuple_size` and `tuple_element` as classes, but defines them as structs, see paragraph 19.4.4 of the current draft.

I'm also for explicitly disabling those warnings.

**Comment by past-due** [comment]
Please don't close, stale bot.
