### ISSUE TITLE
Which native types does get<type>() allow?

### ISSUE THREAD

**Issue by ibc** [nlohmann/json#1403]
For example, this seems to work:

```c++
uint32_t value = someField.get<uint32_t>();
```

But I cannot find in the API doc which types can be given as template.

**Comment by nlohmann** [comment]
There is no real documentation so far. For the primitive types (`bool`, `std::string`, `std::unint64_t`, `std::int64_t`, and `double`), `get` executes a static cast and throws if the types are incompatible. For structured types (object, array), we added some more magic to do the translations.

**Comment by ibc** [comment]
Ok, if a static cast is done internally then it's clear :)
Thanks.
