### ISSUE TITLE
Unexpected behaviour with structured binding

### ISSUE THREAD

**Issue by ChristianJacobsen** [nlohmann/json#1404]
- What is the issue you have?
When using range-for loop with structured binding over a simple JSON structure it puts the entire object in the `value` argument as if it's treated as an array.

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?
```c++
#include <fstream>
#include <iostream>
#include <nlohmann/json.hpp>

using nlohmann::json;

int main() {
    /**
     * config.json:
     *
     * {
     *     "someKey": "someValue"
     * }
     */
    json o{json::parse(std::ifstream{"./config.json"})};
    for (const auto& [key, value] : o.items()) {
        std::cout << key << ": " << value << "\n";
        // 0: {"someKey":"someValue"}

        for (const auto& [innerKey, innerValue] : value.items()) {
            std::cout << innerKey << ": " << innerValue << "\n";
            // someKey: "someValue"
        }
    }

    return 0;
}
```

- What is the expected behavior?
`someKey: "someValue"` in the first print.

- And what is the actual behavior instead?
What is in the comments below the print statements in the code above.

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?
GCC version 8.2.1 on Linux 4.19.11.

- Did you use a released version of the library or the version from the `develop` branch?
On version 3.5.0 provided by the AUR (Arch User Repository).

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?
No compilation errors.

**Comment by nlohmann** [comment]
The problem are the braces in line

```cpp
json o{json::parse(std::ifstream{"./config.json"})};
```

which yield an array.

Try:

```cpp
json o = json::parse(std::ifstream{"./config.json"});
```

**Comment by nlohmann** [comment]
(see also: #1359)

**Comment by ChristianJacobsen** [comment]
Damn you're fast! Thanks!
