### ISSUE TITLE
Efficient way to set a `json` object as value into another `json` key

### ISSUE THREAD

**Issue by ibc** [nlohmann/json#1406]
I've a function somewhere that creates and returns a `json data` object, and I want to use such a `json data` as value into the "data" key of another `json response` object.

Currently I'm doing something like this, and just wonder whether there is a way to avoid the `data` copy:

```c++
json response = json::object();

response["id"] = this->id;
response["data"] = this->foo.GetJsonData(); // This produces a `json`.

this->DoSomethingWith(response);
```

I expect there is no magic here and the `json data` returned by `foo.GetJsonData()` is being mem copied into `response["data"]`. May be I should, instead, do something like this?:

```c++
json response = json::object();

response["id"] = this->id;

// Allocate empty object for "data" key:
response["data"] = json::object();

// Get iterator to "data" object:
auto dataIterator = response.find("data"); 

// Pass the iterator to `foo.GetJsonData()` so it adds its keys/values into it.
this->foo.GetJsonData(dataIterator);

this->DoSomethingWith(response);
```

Then, `void Foo::GetJsonData(json::iterator dataIterator)` would do something like:

```c++
(*dataIterator)["foo"] = "FOO";
(*dataIterator)["bar"] = 1234;
```

Does it make any sense?

**Comment by gregmarr** [comment]
Yes, this would definitely be more efficient:

    void Foo::GetJsonData(json &storeDataInHere) {
        storeDataInHere["foo"] = "FOO";
        storeDataInHere["bar"] = 1234;
    }

    this->foo.GetJsonData(response["data"]);

**Comment by ibc** [comment]
Already using it, thanks :)

**Comment by gregmarr** [comment]
Read what I posted above again, and I think you'll find your answer.  Maybe this will help:

    json response = json::object();
    response["id"] = this->id;
    this->foo.GetJsonData(response["data"]);

**Comment by ibc** [comment]
Ok, so you are directly passing `response["data"]` to `foo.GetJsonData()`, this is, you are creating a "data" key in-place, great!

I have to remove some asserts that check `storeDataInHere.is_object()` to make it work, but nothing else. Thanks!
