### ISSUE TITLE
Append version to include.zip

### ISSUE THREAD

**Issue by aduskett** [nlohmann/json#1412]
Hello!

First off; I want to thank you guys for making such a wonderful library!
I was wondering if it would be possible to append the version number to each include.zip file that's released from now on. I contribute to the BuildRoot project, and it would be wonderful not to have to download the entire tarball. 

If you take a look at https://patchwork.ozlabs.org/patch/1019719/ you will see the issue with using include.zip. 

"Thanks to the hash, the right version of the file will be
re-downloaded, but this will entirely break sources.buildroot.net, in
the sense that they will not be able to provide include.zip for older
Buildroot versions, that use an older version of json-for-modern-cpp."

It's a small thing, but it would be MUCH appreciated if you guys would be willing to do this for us.

Thanks!

Adam

**Comment by aduskett** [comment]
While I appreciate that, the end result is still include.zip, which is the primary issue.
Would it be possible to instead call it include-v3.5.0.zip ?

**Comment by nlohmann** [comment]
I have to see. Adding the include folder was already something I did for other systems. I'm afraid changing the name would break their system now.

**Comment by aduskett** [comment]
I hope not! I don't want to break other systems!
