### ISSUE TITLE
Latest Ubuntu package is 2.1.1

### ISSUE THREAD

**Issue by phunkyfish** [nlohmann/json#1438]
I'm not sure what is required to get a later version of nlohmann-json-dev in the ubuntu package repo. Is there an action on your part or do you just wait for Ubuntu to catch up?

I ask as I've used it as a depends in kodi.

**Comment by nlohmann** [comment]
I am sorry, but I have no idea who is maintaining that package.

**Comment by phunkyfish** [comment]
No worries, I just thought I’d ask 😉
