### ISSUE TITLE
Setting values of .JSON file

### ISSUE THREAD

**Issue by harrysanchezs** [nlohmann/json#1444]
This is example of my .JSON file.
`{"Settings":{"AutoReload":true,"CheckingUpdates":false}}`
What function should I use to set the value of "Settings-AutoReload" from "True" to "False", for example? To set and save it.

**Comment by nlohmann** [comment]
Assume your JSON file is called `file.json`, then you can read it with

```cpp
std::ifstream input_file("file.json");
json j;
input_file >> j;
```

Then you can access the value with `operator[]`:

```cpp
j["Settings"]["AutoReload"] = false;
```

**Comment by harrysanchezs** [comment]
> Assume your JSON file is called `file.json`, then you can read it with
> 
> ```c++
> std::ifstream input_file("file.json");
> json j;
> input_file >> j;
> ```
> 
> Then you can access the value with `operator[]`:
> 
> ```c++
> j["Settings"]["AutoReload"] = false;
> ```

Okay. But question is about can I rewrite and save JSON file with the new value? Or I can work only with gotten value, can't set it?

**Comment by nlohmann** [comment]
Do you mean how to write a JSON value (like `j` in the example) to a file? Have a look at https://github.com/nlohmann/json#serialization--deserialization

**Comment by harrysanchezs** [comment]
> Do you mean how to write a JSON value (like `j` in the example) to a file? Have a look at https://github.com/nlohmann/json#serialization--deserialization

Yes, but only this value. Other values should not be changed if user didn't set them. Only needed value should be rewrited in JSON file.

**Comment by nlohmann** [comment]
I do not understand. How should the expected JSON file look like?

**Comment by harrysanchezs** [comment]
> I do not understand. How should the expected JSON file look like?

I'm sorry. For example, this's current JSON file
`{"Settings":{"AutoReload":true,"CheckingUpdates":false}}`

The user wanna set the value of "Settings - AutoReload", set it from "True" to "False" and save it by rewriting JSON file with the new value. The new JSON file will look like
`{"Settings":{"AutoReload":false,"CheckingUpdates":false}}`

As you can see, other value of "Settings - CheckingUpdates" was not touched, because user didn't set it. In short - can I work and rewrite only a specific value? Can I rewrite the file, changed "Settings - AutoReload" value to "True" and didn't touched "Settings - CheckingUpdates" value ?

**Comment by nlohmann** [comment]
So you want to write the complete changed value `j`.

```cpp
// read
std::ifstream input_file("file.json");
json j;
input_file >> j;

// change
j["Settings"]["AutoReload"] = false;

// write
std::ofstream output_file("new_file.json");
j >> output_file;
```

The content of that file should be

```js
{"Settings":{"AutoReload":false,"CheckingUpdates":false}}
```

**Comment by harrysanchezs** [comment]
> So you want to write the complete changed value `j`.
> 
> ```c++
> // read
> std::ifstream input_file("file.json");
> json j;
> input_file >> j;
> 
> // change
> j["Settings"]["AutoReload"] = false;
> 
> // write
> std::ofstream output_file("new_file.json");
> j >> output_file;
> ```
> 
> The content of that file should be
> 
> ```js
> {"Settings":{"AutoReload":false,"CheckingUpdates":false}}
> ```

Thank you very much.
