### ISSUE TITLE
Unpack list of integers to a std::vector<int>

### ISSUE THREAD

**Issue by p-i-** [nlohmann/json#1460]
Is there any way to unpack:
```
{
    "my_list" : [1,2,3]
}
```
into a `std:vector<int>` ?

I can't find any mention, and `std::vector<int> v = j["my_list"];` fails, as does `j["my_list"].get<std::vector<int>>()`

(Crosslinked to https://stackoverflow.com/questions/54389742/use-nlohmann-json-to-unpack-list-of-integers-to-a-stdvectorint)

**Comment by nlohmann** [comment]
I cannot reproduce the problem. This code works:

```cpp
#include "json.hpp"
#include <iostream>

using json = nlohmann::json;

int main() {
    json j = R"(
    {
        "my_list" : [1,2,3]
    }
    )"_json;

    auto v = j["my_list"].get<std::vector<int>>();
    
    for (auto i : v)
    {
        std::cout << i << std::endl;
    }
}
```

Output:

```
1
2
3
```

**Comment by nlohmann** [comment]
Which version of the library are you using? What is the exact error message you encounter?

**Comment by p-i-** [comment]
My apologies. It works on my end also. I failed to isolate a testcase and my JSON was malformed.

Might I make a couple of suggestions?

Firstly, in the documentation, it would be nice to present packing and unpacking hand-in-hand.
e.g. as you have presented above. Initially when I read the documentationIt was easy to access how to pack things, But really hard to figure out how to _un_-pack them.

Maybe an "Unpacking Examples" section?

Also, I wonder if It might be possible to overload assignment= operator on `std::vector<T>`, which would allow `auto v = j["my_list"];`

**Comment by theodelrieu** [comment]
Please look at #958 for more information.
