### ISSUE TITLE
use json construct std::string

### ISSUE THREAD

**Issue by yuzeng2017** [nlohmann/json#1462]
- What is the issue you have?
“std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string”: Overload function ambiguous.
- Please describe the steps to reproduce the issue. Can you provide a small but working code example?
        json j;
        j["account"] = "123456";
      std::string account_text(j["account"]);
     vs2015 compile error.
- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by nlohmann** [comment]
Related: #1061

**Comment by jerryjiahaha** [comment]
I have similar problem under **MSVC** 2017 (clang and gcc works). I want to convert json results to std::string vector and here is what I tried:

```cpp
#include "json.hpp"
#include <vector>
#include <iostream>
#include <fstream>

int main()
{
	nlohmann::json jConfig2 = R"(
		{
			"names": ["Tim", "Tom"],
			"nums": [1.2, 2.3]
		}
	)"_json;
	std::vector<float> iNums0;
	std::vector<std::string> sNames0;

	// Just work for float, but std::string failed
	iNums0 = std::vector<float>(jConfig2.at("nums").begin(), jConfig2.at("nums").end());
	for (auto i : iNums0) { std::cout << i << " "; } std::cout << std::endl;

	// Work around for MSVC 2017
	auto itseed = jConfig2.at("names").get<std::vector<std::string>>();
	sNames0 = std::vector<std::string>(itseed.begin(), itseed.end());

	// Compile ok, but run failed: "vector iterators in range are from different containers"
//	sNames0 = std::vector<std::string>(jConfig2.at("names").get<std::vector<std::string>>().begin(), jConfig2.at("names").get<std::vector<std::string>>().end());

	// Comiple failed: Error C2668 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string': ambiguous call to overloaded
//	sNames0 = std::vector<std::string>(jConfig2.at("names").begin(), jConfig2.at("names").end());

	// Compile failed: Error C2593 'operator =' is ambiguous
//	sNames0 = jConfig2.at("names");

	// Compile failed: Error C2440 '<function-style-cast>': cannot convert from 'nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>' to 'std::vector<std::string,std::allocator<_Ty>>'
//	sNames0 = std::vector<std::string>(jConfig2.at("names"));

	//  It works, too
	std::vector<std::string> _names = jConfig2.at("names");
//	sNames0 = _names;

	for (auto i : sNames0) {
		std::cout << i << " ";
	}
	std::cout << std::endl;

	return 0;
}
```

The format 
```cpp
std::vector<Type>(jsontype.at("Key").begin(), jsontype.at("Key").end());
```
works for Type int, float but not works under std::string.

I also tried `clang++` and `g++` with `-Wall`. `g++` compiled without warnning, `clang++` gave me warning:

> In file included from ConsoleApplication1.cpp:1:
> ./json.hpp:1799:1: warning: 'tuple_size' defined as a class template here but previously declared as a struct template
>       [-Wmismatched-tags]
> class tuple_size<::nlohmann::detail::iteration_proxy_value<IteratorType>>
> ^
> /usr/sbin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../include/c++/8.2.1/array:350:5: note: did you mean class
>       here?
>     struct tuple_size;
>     ^
> /usr/sbin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../include/c++/8.2.1/utility:84:5: note: did you mean class
>       here?
>     struct tuple_size;
>     ^
> In file included from ConsoleApplication1.cpp:1:
> ./json.hpp:1803:1: warning: 'tuple_element' defined as a class template here but previously declared as a struct template    
>       [-Wmismatched-tags]
> class tuple_element<N, ::nlohmann::detail::iteration_proxy_value<IteratorType >>
> ^
> /usr/sbin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../include/c++/8.2.1/array:359:5: note: did you mean class
>       here?
>     struct tuple_element;
>     ^
> /usr/sbin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../include/c++/8.2.1/utility:110:5: note: did you mean class
>       here?
>     struct tuple_element;
>     ^
> 2 warnings generated.
