### ISSUE TITLE
Disable installation when used as meson subproject

### ISSUE THREAD

**Issue by elvisoric** [nlohmann/json#1463]
When the library is used as `Meson` subproject it is included in top level project as dependency from the subproject. With current implementation of the library, when main project is installed the library is also installed which is undesirable.

`Meson` build script should be changed to allow installation only if the library is not used as subproject.

 The installation step should be guarded with:
```
if not meson.is_subproject()
# steps for install headers and pkgconfig
endif
```

**Comment by nlohmann** [comment]
Closed by merging #1464
