### ISSUE TITLE
Checking keys of two jsons against eachother

### ISSUE THREAD

**Issue by simulationcloud** [nlohmann/json#1465]
So, I have two JSON configuration files that may be nested multiple layers deep. One consists of all possible parameters a user can input set to their default value. The other is JSON input from a user. I want to check that no key (including nested keys) exists in the user JSON that does not exist in the configuration JSON.

Is there a simple way to do this?

Thank you very much in advance!

**Comment by nlohmann** [comment]
You could try the [`diff` function](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a543bd5f7490de54c875b2c0912dc9a49.html#a543bd5f7490de54c875b2c0912dc9a49).

**Comment by nickaein** [comment]
I am not sure whether there is an easier way of checking that, but here is a solution:

```
bool verify_with_schema(const json& schema, const json& user)
{
    for(auto& item_user: user.items()) 
    {
        auto item_schema = schema.find(item_user.key());
        if(item_schema == schema.cend())
            return false;

        if(item_user.value().is_object())
        {
            if(!verify_with_schema(*item_schema, item_user.value()))
            return false;
        }
    }

    return true;
}
```

I haven't tested it thoroughly though. Please check it before using it in production.

**Comment by nickaein** [comment]
@simulationcloud Forget the above function. Based on nlohmann comment, there is already infrastructure for comparing two JSONs. It also let you find out which values has been actually overridden by the user (indicated by `replace` operation).

**Comment by nlohmann** [comment]
@simulationcloud Do you need further assistance?

**Comment by simulationcloud** [comment]
No, you answered my question. Thank you very much!
