### ISSUE TITLE
Global variables are stored within the JSON file, how do I declare them as global variables when I read them out in my C++ program? 

### ISSUE THREAD

**Issue by XIAY0009** [nlohmann/json#1476]
Dear Nlohmann, 

Thanks so much for the library! It is relatively user friendly :) 

I am working on a project, which I keep the variables in a JSON file, and intend to read them out into my C++ program. I can do that, but the problem is that these variables are actually global variables. By reading them out in my main function, these variables are essentially local to the main function. Which is not what I require. I am not sure how could I make these variables global, your help will be much appreciated! 

int main() {
    std::ifstream in("/LearnJSON/test2.json");
    json file = json::parse(in);

    //auto size = file.size();
    //file["size"] = size;
    std::cout << file.at("pi") << '\n';
    std::cout << std::setw(4) << file << '\n';
    float pi_value = file.at("pi"); //Example I will like to make pi_value a global variable, but currently I can't
    std::cout << "Value of pi is: " << pi_value << '\n';
    return 0; 
}

**Comment by nickaein** [comment]
What issue do you have? You can still define your variables as global and assign them inside the `main` function:

```
float pi_value;

int main()
{
    std::ifstream fin("settings.json");
    json j_settings = json::parse(fin);

    // assign values to global variables from JSON data
    pi_value = j_settings["pi"];
    ...
}
```

Does that solves your problem?

**Comment by XIAY0009** [comment]
Yes, that does !! Thanks
