### ISSUE TITLE
Some Help please

### ISSUE THREAD

**Issue by kenkit** [nlohmann/json#1478]
How do I access the keys within the array  ?
`{"jsonrpc":"2.0","method":"aria2.onDownloadComplete","params":[{"gid":"5c6b48f1a09df47f"}]}`

I want to access the values within params.

e.g  `myjson["params"]["gid"].get<std::string>()`

**Comment by jaredgrubb** [comment]
```myjson["params"][0]["gid"].get<std::string>()``` (you need to say which element of the array you want, so ```[0]``` will do that)

**Comment by kenkit** [comment]
Ohhh, yeah. Thank you.
