### ISSUE TITLE
[Question] Unescaped dump

### ISSUE THREAD

**Issue by p-groarke** [nlohmann/json#1479]
I'm using jsonformoderncpp as a simple intermediary to traverse json and store it in another hierarchical format. All I need is strings for every key/value pair, regardless of their type. I use `dump`, which works as expected, but it adds escaped quotes to values.

Is their a way to get values "as is" without escaped quotes? `get<std::string>` can't work as it checks the json type is actually a string.

**Comment by jaredgrubb** [comment]
If I understand correctly, you want the JSON string representation of each value. You could just call ```value.dump()``` on each one right?

**Comment by p-groarke** [comment]
Yes that's what I'm doing, but `dump()` keeps quotes. What I'm looking for is serialization of the value.

Let me try to explain what I mean. Lets say I have the following :
```
{ "name" : "bob" }
```
`dump()` will output `"bob"`. I'm looking to get `bob` without the quotes, as if you would deserialize to  `string`. Does that make any sense?

I can do the parsing myself, I just want to make sure the capability to do this isn't already available so I don't take the perf hit of cleaning all the strings.

**Comment by jaredgrubb** [comment]
Let's be more concrete and include something where the difference matters.

Suppose you have ```{"country": "\\u65e5\\u672c"}```:

value.dump() will give type string ```"\\u65e5\\u672c"``` (14 bytes, all ASCII)
value.get<string>() will give you the string  ```日本``` (6 bytes, UTF8)

Are you saying you want ```\\u65e5\\u672c``` (12 bytes, ASCII) (dropping the quotes, but keeping the JSON-style escaping)?

**Comment by p-groarke** [comment]
No, I would want the string "as-if deserialized and reserialized". So `日本`, without quotes. However, I need this for every basic type as well (ints, floats etc).

So the setup :
db -> jsonformoderncpp, decomposes everything as string-> templating lib -> output

**Comment by p-groarke** [comment]
Just a note though, I would be ok with `\\u65e5\\u672c` without quotes, as I can always parse the utf8 myself or using another lib.

**Comment by gregmarr** [comment]
I remember another issue like this where the recommendation was to walk through the elements in the array/object, and if the type is `string`, use `get<std::string>`, and for anything else, use `dump()`.  I was looking for that issue, but wasn't able to find it.

**Comment by gregmarr** [comment]
I think this is the one: https://github.com/nlohmann/json/issues/1181

**Comment by jaredgrubb** [comment]
If you need this for basic types too, then how are you going to distinguish the difference between the *number* 42 and the *string* "42"? For example, given the JSON object ```{ "a": 42, "b": "42"}```, the values are very different things and it sounds like you want the same two-byte string ```42``` for both values? Going even further, I am trying to imagine what you are hoping to get for an array of strings or, worse, and array that has strings and numbers. :)

But, yes, you would need to do this at a higher level by switching on the type; there is nothing in the library that does this (because it removes information that cannot be recovered).

**Comment by p-groarke** [comment]
> I remember another issue like this where the recommendation was to walk through the elements in the array/object, and if the type is `string`, use `get<std::string>`, and for anything else, use `dump()`. I was looking for that issue, but wasn't able to find it.

Of course! That's perfect thx :)

To answer your question, the output is html. So` 42` and `"42"` are going to be rendered the same way : `42`. As far as I can tell there is no problem (I may be hallucinating, tbd ;) ). Note there is no processing happening, just rendering the values as text to html.
