### ISSUE TITLE
"Json Object" type does not keep object order

### ISSUE THREAD

**Issue by rockeet** [nlohmann/json#148]
for json: { "b" : "B", "a" : "A" }
The iteration order is by lexical order of keys, but it should be the original order in the json object.

**Comment by gregmarr** [comment]
The JSON specification says that the data is stored in an unordered fashion, so any order is acceptable.

**Comment by nlohmann** [comment]
Hi, @gregmarr is right. JSON does not specify an order in which keys of an object are stored. My library uses an std::map, so the perceived order is lexicographically. This is conforming the JSON specification.

If you can implement a container that preserves the order of keys, you could use this one in the linear via template types.

**Comment by rockeet** [comment]
Thanks, now I use my gold_hash_map as map, and ignored the compare and allocator.

**Comment by bernau84** [comment]
Or you can use Niels https://github.com/nlohmann/fifo_map as I do.
Thank you @nlohmann twice.
