### ISSUE TITLE
Type in README.md

### ISSUE THREAD

**Issue by jonericcook** [nlohmann/json#1486]
- What is the issue you have?
Found a typo
- Please describe the steps to reproduce the issue. Can you provide a small but working code example?
View this link https://github.com/nlohmann/json#json-merge-patch
- What is the expected behavior?
// a JSON value
json j_document = R"({
  "a": "b",
  "c": {
    "d": "e",
    "f": "g"
  }
})"_json;

// a patch
json j_patch = R"({
  "a":"z",
  "c": {
    "f": null
  }
})"_json;

// apply the patch
**j_document**.merge_patch(j_patch);
// {
//  "a": "z",
//  "c": {
//    "d": "e"
//  }
// }
- And what is the actual behavior instead?
// a JSON value
json j_document = R"({
  "a": "b",
  "c": {
    "d": "e",
    "f": "g"
  }
})"_json;

// a patch
json j_patch = R"({
  "a":"z",
  "c": {
    "f": null
  }
})"_json;

// apply the patch
**j_original**.merge_patch(j_patch);
// {
//  "a": "z",
//  "c": {
//    "d": "e"
//  }
// }
- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?
N/A
- Did you use a released version of the library or the version from the `develop` branch?
develop branch
- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by nickaein** [comment]
Thanks for reporting!
