### ISSUE TITLE
json to std::map

### ISSUE THREAD

**Issue by janekaldo** [nlohmann/json#1487]
hey
````
void config::save() {
	nlohmann::json j = g_Settings.config;
       std::ofstream o("default.json");
	o << j << std::endl;
}


void config::load() {
	nlohmann::json j;
	std::ofstream o("default.json");
	j >> o;
	g_Settings.config = j.get<std::map<std::string, bool>>;
}
````
this is my current code. saving works perfectly but loading doesnt. compiler gives the following erros:

> 'nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>::operator >>': was declared deprecated

**Comment by hydratim** [comment]
The library already supports the STL std::map interface, however you might need to write your own post-processor that iterates over the object and produces a true std::map.

**Comment by nickaein** [comment]
While the conversion [from STL containers to json](https://github.com/nlohmann/json#conversion-from-stl-containers) is supported, I doubt there is a conversion available *from* `json` to `std::map<std::string, bool>>`. You might try to implement a [`from_json`](https://github.com/nlohmann/json#basic-usage) method for your `config` data type or just do the conversion directly inside the `load()` function.

**Comment by theodelrieu** [comment]
I don't understand, the error is not about conversion from JSON to map, it seems to me that you're compiling with `-Werror` while using a deprecated function.

Replace `j >> o` by `j = json::parse(o)` and it should work as expected.

**Comment by nickaein** [comment]
Théo is right. There is indeed an overload of [`from_json` avaiable for `bool` as value type](https://github.com/nlohmann/json/blob/9294e25c98f9c09a1874842dbcaae7a91336a57e/include/nlohmann/detail/conversions/from_json.hpp#L67) which covers the `std::map<string,bool>>` conversion. Therefore writing a custom [`from_json`](https://github.com/nlohmann/json#basic-usage) method is unnecessary.

**Comment by nlohmann** [comment]
Instead of `j >> o;`, please use `o << j;`.

**Comment by garethsb-sony** [comment]
If the OP is trying to load a json file, don't they need

```C++
std::ifstream i("default.json");
i >> j;
```
