### ISSUE TITLE
how to find subelement  without loop

### ISSUE THREAD

**Issue by bnadem** [nlohmann/json#1490]
i hae normal json file structure like

```js
{
"element" :{
"test":"test",
"subelement": {
      "subsubelemnt1":"githu",
        "subsubelemnt2":"githu",
         "subsubelemnt3":"githu",
          "subsubelemnt4":"githu",

}
}
}
```

want to find "subelement2" or"subelement""subelement2"  without looping, is there function like find , exist, contain without iterating?

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by nickaein** [comment]
You can use [JSON Pointers](https://github.com/nlohmann/json#json-pointer-and-json-patch) to access an element if you can provide its full *address* in the hierarchy of JSON document e.g. `json_doc["/element/subelement/subelement2"]`. 

I'm not sure whether there is a method to look up for `subelement2` in all subtrees.

**Comment by bnadem** [comment]
no dont working, i become null pointer.

**Comment by nlohmann** [comment]
Assuming your JSON value is `j`, then you can access the value with `j["element"]["subelement"]["subsubelemnt1"];`.

**Comment by garethsb-sony** [comment]
> You can use [JSON Pointers](https://github.com/nlohmann/json#json-pointer-and-json-patch) to access an element if you can provide its full _address_ in the hierarchy of JSON document e.g. `json_doc["/element/subelement/subsubelemnt2"]`.


`json_doc["/element/subelement/subsubelemnt2"_json_pointer]`

**Comment by nickaein** [comment]
@garethsb-sony: Whoops. Thanks for clarification!

**Comment by garethsb-sony** [comment]
@nickaein I just didn't want anyone to think the ``json_pointer`` solution didn't work. :-)
