### ISSUE TITLE
How to get data into vector of user-defined type from a Json object

### ISSUE THREAD

**Issue by Haris3243** [nlohmann/json#1493]
**Anyone here who can help me on urgent basis,i shall be very very thankful to him/her, I am in a big trouble due to this kindly help me**
i want to store "Configurations" data into  vector<myclass> result.
where 

```cpp
class myclass{
string name;
string def;
string type;
string validation;
};
```

and my Json data is in nlohmann::Json object "Jdata" is as follows 

```js
{
    "Configuration":[
                                 {
	                               "Name":"FirstName",
	                               "Def":"DB('F_NAME')",
	                               "Type":"String",
	                               "Validation":""
                                 },
                                {
	                              "Name":"Age",
	                              "Def":"RANGE(MIN,MAX)",
                                      "Type":"Integar",
	                              "Validation":""
                                 },
                                {
	                              "Name":"DAY",
	                              "Def":"ENUM('MON','TUE','WED','THU','FRI','SAT','SUN')",
	                              "Type":"String",
	                              "Validation":"" 
                                }

                            ],
	"Input Configuration":[{"Name":"Fields"},{"Name":"Options"}]
}
```

**Comment by Haris3243** [comment]
please @nlohmann  kindly help me or assign anyone else who can help me

**Comment by nlohmann** [comment]
Please see https://github.com/nlohmann/json#arbitrary-types-conversions.

**Comment by shrikky** [comment]
@nlohmann  could you please expand on your answer. I did check out the arbitary type conversion but it is not giving me enough information. How do we parse json into a std::vector<customClass>... the get_to doesn't accept std::vector<customtype>...

**Comment by nlohmann** [comment]
You can only parse into a JSON value (the `parse` function returns `json`, and the conversions go from/to `json`). In the example, after parsing the JSON`, you could have code like:

```cpp
std::ifstream myinput("myfile.json");
auto j = json::parse(myinput);

std::vector<myclass> v = j["Configuration"];
```
