### ISSUE TITLE
Cmake 3.1 in develop, when is it likely to make it into a stable release?

### ISSUE THREAD

**Issue by phunkyfish** [nlohmann/json#1498]
There are certain build systems that don't support cmake 3.8, patching is one option while waiting for the next release but if it's imminent happy to wait.

**Comment by phunkyfish** [comment]
Any chance of a 3.5.1 release that relaxes the cmake dependency?

**Comment by pboettch** [comment]
See here: https://github.com/nlohmann/json/pull/1441

**Comment by phunkyfish** [comment]
Ah, still in progress. Sorry, got lost in the threads. Thanks for the (clearer) update.

**Comment by nlohmann** [comment]
Fixed by merging #1441.

**Comment by StormTrooper** [comment]
Is it possible to push this fix into a release. Its been fixed on the develop branch but Kodi do not want to point to develop branch.

Maybe a 3.5.1 version? Otherwise for OSMC we have to use a patched fork of vfs.sftp to point to the develop version of nlohmann-json which is not ideal.

**Comment by nlohmann** [comment]
It will be part of 3.6.0. I hope to make the release by tomorrow.

**Comment by nlohmann** [comment]
Released: https://github.com/nlohmann/json/releases/tag/v3.6.0

**Comment by phunkyfish** [comment]
Amazing, thanks!
