### ISSUE TITLE
Wish feature: json5

### ISSUE THREAD

**Issue by rockeet** [nlohmann/json#150]
As described in: http://json5.org/
And there is a js implementation for json5: https://github.com/aseemk/json5
But I didn't found a good json5 in C++

**Comment by rockeet** [comment]
I think the most useful feature is allowing trailing commas, and this feature is very easy to implement.

**Comment by stopiccot** [comment]
+1 for trailing commas, I'm full of this nazi parsers

**Comment by nlohmann** [comment]
I think adding JSON5 support is out of scope of this library. It would require a lot of effort to maintain JSON compliance while offering optional JSON5 support. Furthermore, I do not see a lot of need for JSON5 support.
