### ISSUE TITLE
"Integration" section of documentation needs update?

### ISSUE THREAD

**Issue by Memhir-Yasue** [nlohmann/json#1505]
Hello,
I declared the header file as `#include <nlohmann/json.hpp>` as the documentation suggested.

However, I ran into the following problem when complying 

 ```
lab.cpp:2:10: fatal error: nlohmann/json.hpp: No such file or directory
 #include <nlohmann/json.hpp>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

I found this issue from 2017 which suggests to instead use  `#include "nlohmann/json.hpp"`
 https://github.com/melpon/wandbox/issues/209

No errors encountered afterwards when complying. 

Using Ubuntu 18.04.02 with GCC 7.3.0

**Comment by gregmarr** [comment]
This means that you did not add the directory containing `nlohmann` in your compiler options as a system include directory.  The `<foo.h>` syntax generally means "search in system include directories" while `"foo.h"` means "search in system include directories and the directory of the file doing the include".

**Comment by nlohmann** [comment]
@gregmarr is right. Furthermore, there are several package managers which all assume this way of including. As a working example, see the compiler call on the bottom of https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a8faa039ca82427ed29c486ffd00600c3.html#a8faa039ca82427ed29c486ffd00600c3

**Comment by Memhir-Yasue** [comment]
Gotcha! Thanks for the explanations! Learned something new!
