### ISSUE TITLE
CBOR byte string support

### ISSUE THREAD

**Issue by ayounes-nviso** [nlohmann/json#1509]
There is already a ticket on that issue: #1129 
I could not re-open this ticket and I am not sure if our comments there are noticed by someone. Sorry about the duplication if the notification on closed ticket are actually working.

We (NVISO) are willing to contribute to this feature if you can give us some pointer where to start.

Thanks in advance and best regards,
Abdel

**Comment by ayounes-nviso** [comment]
BTW, this project already support incremental loading of CBOR, including Byte arrays:
  https://github.com/danielaparker/jsoncons

Maybe we can borrow some code if the license are compatible (there are using Boost Software License, Version 1.0).

**Comment by nlohmann** [comment]
I reopened #1129. Let's have the discussion there. Closing this issue to avoid duplicates.

It would be great to see some progress on binary support. Even better would be an idea that also works with MessagePack, UBJSON :)

**Comment by nlohmann** [comment]
Fixed with https://github.com/nlohmann/json/pull/1662.
