### ISSUE TITLE
std::complex type

### ISSUE THREAD

**Issue by mipac** [nlohmann/json#1510]
How can we serialize std::complex<T> type ?
And vector<complex<float>> in particular ?

I make to_json/from_json functions, but I wonder if there is a better way.

**Comment by nlohmann** [comment]
`std::complex` is not supported out of the box. So, yes, you need to define `to_json`/`from_json` functions. There, you need to define how you want to represent the values.

**Comment by gregmarr** [comment]
Specifically, you need to define them for `std::complex`.  If you do that, then `std::vector<std::complex>` comes for free.

**Comment by mipac** [comment]
thx for your replies,

I can't make it work for free with vector ;)
can you post a sample code?

**Comment by nlohmann** [comment]
How does your code for `std::complex` look like?

**Comment by mipac** [comment]
... It works when I put the code in std namespace... sorry

it could help:

```
namespace std {

template< class T > to_json(json &j, const std::complex< T > &p) {
  j = json {to_string(p.real()) + "+i" + to_string(p.imag())};
}

template< class T > from_json(const json &j, std::complex< T > &p) {
}

}

...
vector<complex<float>> v = { {1,1}, {2,2}};
json j(v);

```
Do you have an efficient way to deserialize ;)

**Comment by nlohmann** [comment]
How about

```cpp
#include "json.hpp"
#include <iostream>
#include <complex>

using json = nlohmann::json;

namespace std {
    
    template< class T > void to_json(json &j, const std::complex< T > &p) {
        j = json {p.real(), p.imag()};
    }
    
    template< class T > void from_json(const json &j, std::complex< T > &p) {
        p.real(j.at(0));
        p.imag(j.at(1));
    }
}

int main() {
    std::vector<std::complex<float>> v1 = { {1,2}, {3,4}};
    json j(v1);
    
    std::cout << j << std::endl;
    
    auto v2 = j.get<std::vector<std::complex<float>>>();
    std::cout << std::boolalpha << (v1 == v2) << std::endl;
}
```

**Comment by mipac** [comment]
ok tested and approved!
A big thank you ;)

**Comment by nlohmann** [comment]
You're welcome!

**Comment by danra** [comment]
Adding my vote for supporting `std::complex<T>` out of the box. Some canonical default would work for 99% for the use-cases and would lower friction.
