### ISSUE TITLE
json::parse(string) does not check utf8 bom

### ISSUE THREAD

**Issue by rockeet** [nlohmann/json#152]
Exception thrown when passing an utf8 string with starting bom to json::parse, it should skip the bom mark and treat the string as utf8

**Comment by nlohmann** [comment]
I changed the label to "enhancement", because the current behavior is compliant:

> Implementations MUST NOT add a byte order mark to the beginning of a JSON text. In the interests of interoperability, implementations that parse JSON texts MAY ignore the presence of a byte order mark rather than treating it as an error.

(see http://rfc7159.net/rfc7159#rfc.section.8.1)

**Comment by nlohmann** [comment]
@rockeet, just to be sure - we are talking about the bytes `EF BB BF`? Could you provide an example that triggers the exception?

**Comment by rockeet** [comment]
Cool, it works!

**Comment by nlohmann** [comment]
\o/
