### ISSUE TITLE
unable to parse json 

### ISSUE THREAD

**Issue by somequery** [nlohmann/json#1525]
I am parsing the json file:
{
  "default_txt": "sometext"
}

C++ code:
std::ifstream jsonFile("appTest.json", std::ios::in);
nlohmann::json parsed_json = nlohmann::json::parse(jsonFile);

I get an error:
terminate called after throwing an instance of 'nlohmann::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal

I tried:
1/ full path name instead of just the file name
2/ I have checked the json formatting in online parsers with success
3/ parsed successfully with boost property tree

Do yo have any suggestions?

Thanks.

**Comment by gregmarr** [comment]
Have you tried printing out the text after opening the stream?  You appear to have some sort of garbage before the first character.

**Comment by somequery** [comment]
It prints fine:  std::cout << jsonFile.rdbuf() << std::endl;

**Comment by nlohmann** [comment]
Could you please share the file?

**Comment by somequery** [comment]
I have attached the file (I changed the extension from json to txt).
Thanks.
[appTest.txt](https://github.com/nlohmann/json/files/2984393/appTest.txt)

**Comment by nlohmann** [comment]
Hm. This all looks good:

```cpp
#include "json.hpp"
#include <iostream>
#include <fstream>

using json = nlohmann::json;

int main() {
    std::ifstream f("/Users/niels/Downloads/appTest.txt");
    json j = json::parse(f);
    std::cout << j << std::endl;
}
```

produces

```json
{"default":"sometext"}
```

**Comment by nlohmann** [comment]
@somequery Can you try the exact program of https://github.com/nlohmann/json/issues/1525#issuecomment-474456032 (well, with a different path...)?

**Comment by somequery** [comment]
I used the full path as you mentioned, but the result is the same. I run it from VS and from a command line also, from the directory containing both the out and json file. I've received the same error always.

**Comment by somequery** [comment]
After rebuilding it now works. But there is still problem (with the same error) on nlohmann::json parsed_json = nlohmann::json::parse(f);

Am I doing wrong something?

**Comment by nlohmann** [comment]
> After rebuilding it now works.

Does it mean you can parse the file successfully now?

> But there is still problem (with the same error) on nlohmann::json parsed_json = nlohmann::json::parse(f);

What is the problem?

**Comment by somequery** [comment]
> Does it mean you can parse the file successfully now?
Yes. The json file has to be specified with full path. In my case "./appTest.json"

> What is the problem?
while learning the API I was using both:
`std::ifstream jsonFile(./appTest.json);`
`nlohmann::json parsed_json = nlohmann::json::parse(jsonFile);`

and

`nlohmann::json jFields;`
`jsonFile >> jFields;`

I figured out that I should be using the first or the second way but not both together. So everything works now.

Thanks.

**Comment by nlohmann** [comment]
Thanks for clarifying!

**Comment by terzioglan** [comment]
Thanks for the tip @gregmarr ! You are right and this actually solved the issue!.. Much kudos!

**Comment by gregmarr** [comment]
You're welcome.
