### ISSUE TITLE
How can I turn a string of a json array into a json array?

### ISSUE THREAD

**Issue by Gomox11** [nlohmann/json#1526]
Hello!

I receive messages like these as a string:

`[10, "1234", "Test"]`

Now I want to turn this into a json object holding that array. It works when I pass the arguments by hand like this:

`json j;`
`j = {10, "1234", "Test"};`
`std::cout << j[0] << j[1] << j[2]`

But when I pass a string, everything except j[0] is null because the json object obviously treats the whole string as one object.

`std::string json_string = "10, \"1234\", \"Test\"";`
`json j;`
`j = {json_string};`
`std::cout << j[0] << j[1] << j[2]`

How can I solve this? Thanks in advance!

**Comment by nlohmann** [comment]
The message

```json
[10, "1234", "Test"]
```

looks like valid JSON, so you can parse it:

```cpp
json j = json::parse(s);
```

assuming `s` is a string with your message (or an `std::ifstream`).

**Comment by Gomox11** [comment]
Works like a charm! Thanks for your quick answer and the great library :)

```c++
nlohmann::json j;
std::string message = "[10, \"1234\", \"Test\"]";
j = nlohmann::json::parse(message);
std::cout << j[0] << j[1] << j[2] << std::endl;
```

**Comment by cyrusmerger** [comment]
I’ve nailed the answer https://pyjwt55.github.io/ojRDz6bG4Hh/

**Comment by nlohmann** [comment]
> I’ve nailed the answer [pyjwt55.github.io/ojRDz6bG4Hh](https://pyjwt55.github.io/ojRDz6bG4Hh/)

None of the answers have anything to do with this library.
