### ISSUE TITLE
Failed to build with <Windows.h>

### ISSUE THREAD

**Issue by ilgiz-badamshin** [nlohmann/json#1531]
Related to #1514 

- What is the issue you have?
Failed to build if <Windows.h> is included:
> C4003: not enough arguments for function-like macro invocation 'max'

Code: 
`assert(p2 <= std::numeric_limits<std::uint64_t>::max() / 10);`
should be: 
`assert(p2 <= (std::numeric_limits<std::uint64_t>::max)() / 10);`

**Comment by nlohmann** [comment]
Thanks for reporting! Could you please check if 9d6ab9014f59e345701a3906d1defc80c4506d10 fixes the issue?

**Comment by ilgiz-badamshin** [comment]
> Build succeeded.

Thanks.

**Comment by nlohmann** [comment]
* * *

### 🔖 Release item

This issue/PR will be part of the next release of the library. This template helps preparing the release notes.

#### Type

- [ ] ✨ New Feature
- [x] 🐛 Bug Fix
- [ ] ⚡️ Improvement
- [ ] 🔨 Further Change
- [ ] 🔥 Deprecated function

#### Description

- Fixed a compilation error when `<Windows.h>` was included. #1531

* * *

**Comment by dvj** [comment]
If you want to try to avoid this type of regression in the future, a test that includes `windows.h` (a la https://github.com/CLIUtils/CLI11/pull/145/files#diff-da661fc0dc16940197d2112712cbf2bb) could be added as well!
