### ISSUE TITLE
Releases 3.6.0 and 3.6.1 don't build on conda / windows

### ISSUE THREAD

**Issue by SylvainCorlay** [nlohmann/json#1536]
- What is the issue you have?

I am the maintainer of the nlohman_json package on conda-forge. The package for the latest releases don't build on windows (VS 2015)

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

   The logs for the failing builds are available

   - here: (version 3.6.1) https://github.com/conda-forge/nlohmann_json-feedstock/pull/7
   - here: (version 3.6.0) https://github.com/conda-forge/nlohmann_json-feedstock/pull/6

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

MSVC / Windows / (VS 2015)

- Did you use a released version of the library or the version from the `develop` branch?

Released version.

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

The compilation error occurs while building the tests, as per the logs above.

**Comment by nlohmann** [comment]
That is odd, because the MSVC 2015 build runs successfully at our AppVeyor, see https://ci.appveyor.com/project/nlohmann/json/builds/23234117.

**Comment by SylvainCorlay** [comment]
Note that this only occurs with 3.6.x. Previous versions of `nlohmann_json` up until 3.5.x have been packaged succesfully on conda-forge.

**Comment by nlohmann** [comment]
The compilation error is in file `unit-allocator.cpp`. The changes there toward 3.6.0 came with #1492. I'm no expert in MSVC. Maybe @ stac47 or @theodelrieu have an idea on this, as they also proposed the fixes for GCC 9.

**Comment by theodelrieu** [comment]
It would be great to look at the `xmemory` file to see what the call is. But my guess is that `my_allocator` only defines some requirements of [`Allocator`](https://en.cppreference.com/w/cpp/named_req/Allocator), it seems to miss constructors at least.

Maybe `using std::allocator<T>::allocator` will be enough. If not, adding the constructors should do the trick.

I would suggest removing the inheritance from `std::allocator` and rewrite it from scratch though.

**Comment by nlohmann** [comment]
@theodelrieu Good point, I'll try the `using std::allocator<T>::allocator`.

**Comment by nlohmann** [comment]
@SylvainCorlay Could you try whether baaa2a4d0ffe210b32405e76fc007c46ecdc33ff builds?

**Comment by mistersandman** [comment]
The issue appears only when building `test-allocator` with MSVC in Debug mode, where the STL is augmented with debugging constructs. Adding the following constructors to `my_allocator` in `unit-allocator.cpp` seems to also fix the issue:

```
my_allocator() = default;

template <class U>
my_allocator(const my_allocator<U>&) {}
```

**Comment by nlohmann** [comment]
@mistersandman Thanks for the info! As you seem to have access to MSVC (I don't...), could you please check whether baaa2a4d0ffe210b32405e76fc007c46ecdc33ff also works?

**Comment by mistersandman** [comment]
I just checked and it works! Your fix is cleaner than mine 😃

**Comment by mistersandman** [comment]
The question for @SylvainCorlay remains, whether it is even necessary for his case to build the test suite. If the goal is only to install the library, there's no need for it. Building the test suite can be turned off by adding `-DBUILD_TESTING=OFF` to the command line when invoking CMake.

**Comment by SylvainCorlay** [comment]
Hey, thanks for the responses, I am busy for the next couple of hours but will respond after.

**Comment by nlohmann** [comment]
@SylvainCorlay Does https://github.com/nlohmann/json/commit/baaa2a4d0ffe210b32405e76fc007c46ecdc33ff fix the issue?

**Comment by SylvainCorlay** [comment]
Trying it out now

**Comment by SylvainCorlay** [comment]
Including your patch in the recipe appears to be fixing the compilation issue!

**Comment by SylvainCorlay** [comment]
3.6.0 and 3.6.1 are now on conda-forge!

**Comment by nlohmann** [comment]
Thanks a lot for your efforts!

**Comment by nlohmann** [comment]
* * *

### 🔖 Release item

This issue/PR will be part of the next release of the library. This template helps preparing the release notes.

#### Type

- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] ⚡️ Improvement
- [x] 🔨 Further Change
- [ ] 🔥 Deprecated function

#### Description

- The test suite could not be compiled on MSVC in debug mode. #1536

* * *
