### ISSUE TITLE
Quoted numbers

### ISSUE THREAD

**Issue by chiumichael** [nlohmann/json#1538]
I hope this hasn't been asked before (i did try searching through past issues and SO for this), but I was wondering if the library offers some functionality to parse numbers in json files that are quoted, for e.g.
```
{"a" : "5"}
```
I tried something like `int mynumber = j.at("a").get<int>()` but i get a runtime error saying that it expected a string. Is there some other function to use or do i have to extract it as a string first and then convert it to an integer myself elsewhere?

Thanks!

**Comment by nlohmann** [comment]
No, this is nothing the library does out of the box. You would need to call code like

```cpp
foo["a"] = std::to_string(foo["a"]);
```

yourself.
