### ISSUE TITLE
Add regression tests for MSVC

### ISSUE THREAD

**Issue by nlohmann** [nlohmann/json#1543]
We recently had two regressions in MSVC:

- In #1531, we forgot to put parentheses around a `min` call. The problem is that we don't have a unit test that includes `Windows.h`.
- In #1536, the test suite did not build in Debug mode. The problem is that all tests in AppVeyor seem to be compiled in Release mode.

It would be great if someone with experience with MSVC could add regression tests for these issues.

**Comment by nickaein** [comment]
I'll give it a try.

**Comment by nickaein** [comment]
I've created an PR to fix this issue. For checking whether `Windows.h` can cause any troubles, there are two approaches that I have discussed.
