### ISSUE TITLE
Thank you! 🙌

### ISSUE THREAD

**Issue by bengotow** [nlohmann/json#1545]
Hey! This isn't really an issue - feel free to close it. I just wanted to drop in and say I've really enjoyed using `nlohmann/json` and that the setup instructions, documentation, etc. has all been a pleasure to use.  This is probably one of the highest quality dependencies in our codebase.

Also as a sidenote, I find it absolutely amazing that this repo has 13,000 stars and thousands of forks and only 27 issues. Keep up the great work folks!

**Comment by nlohmann** [comment]
You're welcome! (And to be honest - I am using a GitHub bot to mark issues stale after a period of inactivity :)
