### ISSUE TITLE
Matrix output

### ISSUE THREAD

**Issue by AntonPolevoi** [nlohmann/json#1550]
Hello, nlohmann. How can I add matrix type to json file?
So, I did this :  
![Снимок экрана от 2019-03-27 11-31-24](https://user-images.githubusercontent.com/48867176/55061122-04538b80-5084-11e9-9208-c8f2cda4ef85.png)
![Снимок экрана от 2019-03-27 11-25-53](https://user-images.githubusercontent.com/48867176/55061180-28af6800-5084-11e9-990e-f92afec46c30.png)
And it doesn't work, it just prints this report:
![Снимок экрана от 2019-03-27 11-29-55](https://user-images.githubusercontent.com/48867176/55061286-6ad8a980-5084-11e9-9e3f-44f0c0f2b504.png)

**Comment by nlohmann** [comment]
Please have a look at <https://github.com/nlohmann/json#arbitrary-types-conversions>.

**Comment by nlohmann** [comment]
I cannot reproduce the error. The following program

```cpp
#include "json.hpp"
#include <iostream>

using json = nlohmann::json;

int main(int argc, char *argv[])
{
    constexpr std::size_t TASK_count = 3;
    int intensity_between_TASK[TASK_count][TASK_count] = {{1,2,3}, {4,5,6}, {7,8,9}};
    json j;
    j["intensity_between_TASK"] = intensity_between_TASK;
    
    std::cout << j << std::endl;
}
```

works with output

```js
{"intensity_between_TASK":[[1,2,3],[4,5,6],[7,8,9]]}
```

**Comment by nlohmann** [comment]
@AntonPolevoi Do you need further assistance on this issue?

**Comment by AntonPolevoi** [comment]
It's okay. Thank you for help!




пятница, 5 апреля 2019 г., 13:02 +0300 от notifications@github.com  <notifications@github.com>:
