### ISSUE TITLE
GDB renderers for json library

### ISSUE THREAD

**Issue by abrownsword** [nlohmann/json#1554]
GDB supports being extended via 'renderers' which are used to render in-memory data types for better viewing while debugging.  This can be done in Python (see here for quick overview:  http://anadoxin.org/blog/friendly-gdb.html).  

Sure would be a nice-to-have for the JSON library.

**Comment by nlohmann** [comment]
Yes, this would be nice indeed. Volunteers and PRs welcome!

**Comment by nlohmann** [comment]
Related: #1952
