### ISSUE TITLE
Import/Export compressed JSON files

### ISSUE THREAD

**Issue by jumpy88** [nlohmann/json#1556]
I've found in the doc it's possible with this library dealing with [binary JSON formats (BSON, CBOR, etc.)](https://github.com/nlohmann/json#binary-formats-bson-cbor-messagepack-and-ubjson). Anyway looking around the internet one of the most efficient ways of storing JSON files, in terms of space consumption, seems to be using standard JSON format and compress the file in a .json.gz or .json.bz2 file (as shown [here](https://www.peterbe.com/plog/msgpack-vs-json-with-gzip) and [here](https://eng.uber.com/trip-data-squeeze/)). I understand this can be done manually with few commands and it could require to add an undesirable dependency of your json.hpp on an external compression library. On the other hand I think it would be a useful nice-to-have doing it with a single line as it is very common using compressed formats for JSON files especially in network data transmission.

**Comment by abrownsword** [comment]
IMO this would be best accomplished using a user-provided input_adapter and/or output_adapter (see #1534).  This would avoid a dependency from this library to external libraries which implement the compression (or encryption since that is a fairly similar problem).  Such a user-provided adapter could be provided as another library which is dependent on this one and whichever compression/encryption library (or libraries) it wants to stream using.

**Comment by jumpy88** [comment]
Hello @abrownsword, thank you for your reply. I didn't know about the adapter design pattern (I'm studying it [here](https://en.wikipedia.org/wiki/Adapter_pattern), tell me if you have a better reference for that). Sorry for my lack of knowledge in design patterns. Anyway, after a quick look into, it seems it could work. Let's wait for @nlohmann opinion.

**Comment by nlohmann** [comment]
@jumpy88 I agree with @abrownsword: We should not add a dependency to a compression library to this library, and input adapters would be the way to realize reading compressed data.

**Comment by jumpy88** [comment]
Hello @nlohmann, as I anticipated in my first post, I too agree with avoiding dependencies which are not strictly required. So, is this something that can already be done or does it still need additional work on your side? (I've read in #1534 that you are currently working on input adapters). And if it's already usable, can you link some documented examples on how to use it?

Thank you for your support

**Comment by jumpy88** [comment]
@nlohmann are input/output adapters already supported by json library? I couldn't find anything about this in the readme. I only find Jonathan Dumaresq implemented an input adapter to read from FILE*
