### ISSUE TITLE
warning: use of the 'nodiscard' attribute is a C++17 extension

### ISSUE THREAD

**Issue by bvnp43** [nlohmann/json#1557]
- What is the issue you have?

 warning: use of the 'nodiscard' attribute is a C++17 extension

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

mac os, cmake, clang
```
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_FLAGS "-Wall -Wextra -Wfatal-errors -pedantic -fPIC")
```
- What is the expected behavior?

there were no this warnings in v3.5.0

- And what is the actual behavior instead?
```
nlohmann/json.hpp:13087:5: use warningof:  the 'nodiscard' useattribute  ofis  thea  'nodiscard'C++17  attributeextension  is[-Wc++17-extensions] a
 C++17 extension [-Wc++17-extensions]
    JSON_NODISCARD    JSON_NODISCARD

    ^    ^
```

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

```
g++ -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.3)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

- Did you use a released version of the library or the version from the `develop` branch?

tag 3.6.1

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by bvnp43** [comment]
seems duplicate

**Comment by nlohmann** [comment]
Duplicate of #1535. Will be part of the 3.6.2 release.
