### ISSUE TITLE
Build Option/Separate Function to Allow to Throw on Duplicate Keys

### ISSUE THREAD

**Issue by jayeshbadwaik** [nlohmann/json#1560]
In reference to the #375 , I would like to request a compile time option to allow the library to throw on encountering duplicate keys. Or at least a completely separate parse function to do the same?

**Comment by nlohmann** [comment]
I think it's rather hard to detect duplicate keys in `operator[]`, because it always returns a reference to a value - it could also be a default-constructed `null`. That is,

```cpp
j["foo"] = 1;
```

could not detect whether `foo` was stored before. We could also not add a check, because we cannot know whether the returned reference is used to read or to add a value.

So how could an API for this look like?

```cpp
j.add_or_throw("foo", 1);
```

Like this?

**Comment by jayeshbadwaik** [comment]
Apologies for not being clear in my request. I meant encountering duplicate keys on parsing of JSON file. I know the standard does not specify any behaviour. But, it would be good to have a non-default option to parse a JSON and ensure a unique key.

**Comment by nlohmann** [comment]
This could be done by implementing the `key` event of the SAX interface (see https://github.com/nlohmann/json/blob/develop/include/nlohmann/detail/input/json_sax.hpp#L145) differently. It is currently:

```cpp
bool key(string_t& val)
{
    // add null at given key and store the reference for later
    object_element = &(ref_stack.back()->m_value.object->operator[](val));
    return true;
}
```

To throw, one would need to check whether `val` (the key) is already stored in the object we are parsing to (`ref_stack.back()`).

Here is a complete example:

```cpp
#include "json.hpp"
#include <iostream>

using json = nlohmann::json;

class throwing_sax : public nlohmann::detail::json_sax_dom_parser<json>
{
  public:
    throwing_sax(json& j) : nlohmann::detail::json_sax_dom_parser<json>(j) {};
    
    bool key(json::string_t& val)
    {
        if (ref_stack.back()->contains(val))
        {
            throw std::invalid_argument("key " + val + " was already stored");
        }
        return nlohmann::detail::json_sax_dom_parser<json>::key(val);
    }
};

int main(int argc, char *argv[])
{
    json j;
    throwing_sax sax_consumer(j);
    
    auto input = "{ \"key\": 1, \"key\": 2 }";
    json::sax_parse(input, &sax_consumer);
    std::cout << j << std::endl;
}
```

The only problem left is that `ref_stack` is a private variable of `json_sax_dom_parser`. If you set it to protected, the code compiles. Would this be an approach that works for you?

**Comment by jayeshbadwaik** [comment]
Yes, this works for me. Thank you.

**Comment by tete17** [comment]
The solution @nlohmann provided works but we could also implement this into the library itself under a feature macro. I know is not the way of the true c++ but it could work. I leave the proposed solution, let me know if you guys want me to submit a PR.

```c++
bool key(string_t& val)
{
#ifdef JSON_THROW_REPEATED_KEY
    if (ref_stack.back()->contains(val))
    {
        JSON_THROW(parse_error::create(115, "found duplicated key: " + val));
    }
#endif
    // add null at given key and store the reference for later 
    object_element = &(ref_stack.back()->m_value.object->operator[](val));
    return true;
}
```

I would also need to add the 115 to the json parser error docu :wink:

**Comment by jayeshbadwaik** [comment]
I feel the advantage of the first method is that you can use both behaviors in the same build as necessary.

**Comment by jayeshbadwaik** [comment]
Hi! Sorry to raise this issue again, but is there some plan to provide this functionality in the future? Thanks.
