### ISSUE TITLE
How to iterate over nested json object

### ISSUE THREAD

**Issue by lapleski** [nlohmann/json#1561]
Hello.

I got json structure, which I need to parse:
```
{  
   "response":{  
      "count":207,
      "items":[  
         {  
            "id":262
         },
         {  
            "id":261
         }]
     }
}
```

In my c++ program I create json object from string with json:
```
using json = nlohmann::json;
json object = json::parse(json_param);
```
And then I need to iterate over respones.items. How propertly do this? I want to use 'for' operator:
```
for (auto it : object)
{
	std::cout << it["id"] << '\n';
}
```

**Comment by nlohmann** [comment]
Try

```cpp
for (auto& el : object["items].items())
{
  std::cout << el.key() << " : " << el.value() << '\n';
}
```

More on the items function: https://nlohmann.github.io/json/classnlohmann_1_1basic__json_afe3e137ace692efa08590d8df40f58dd.html#afe3e137ace692efa08590d8df40f58dd

**Comment by lapleski** [comment]
Thx.
To get "id" from iterator I used:
```
for (auto& el : object["response"]["items].items())
{
  std::cout << el.value()["id"] << '\n';
}
```

**Comment by lapleski** [comment]
But what if in iterator of this case I get another object?
```
{  
   "response":{  
      "count":207,
      "items":[  
         {  
            "id":262,
            "attachments":[{"element":"one"}, {"element":"two"}]
         },
         {  
            "id":261
            "attachments":[{"element":"three"}, {"element":"four"}]
         }]
     }
}
```

How do I iterate over it?

```
for (auto& el : object["response"]["items].items())
{
  std::cout << el.value()["id"] << '\n';
  for (auto& inner_el : el.value()["attachments"].items())
  {
    std::cout << inner_el.value()["element"] << '\n';
  }
}
```

**Comment by lapleski** [comment]
a, ok it works like I exampled :)

**Comment by michael-a-green** [comment]
Is there a way to iterate over a json object without having to know ahead of time how to move up or down the levels of hierarchy in the json object?

**Comment by nlohmann** [comment]
You could use the [`items()`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_afe3e137ace692efa08590d8df40f58dd.html#afe3e137ace692efa08590d8df40f58dd) function. If this does not help, please open a new issue and describe your use case.

**Comment by mayank1608** [comment]
Is there a way to iterate Array of Objects??
for eg: 
`const color = [
	{
		color: "red",
		value: "#f00"
	},
	{
		color: "green",
		value: "#0f0"
	},
	{
		color: "blue",
		value: "#00f"
	}
]`

I have tried this way but not working:

```
json jsonObj;
json a = json::array();
jsonObj = json::parse(color);
for (json::iterator it = jsonObj.begin(); it != jsonObj.end(); ++it) {
	// for (auto& el : *it.items()) {
	// 	std::cout << el.key() << " : " << el.value() << "\n";
	// }
	a.push_back(it.key());	// returns index of jsonObj
	std::cout << it.key() << '\n';
}

std::cout << a << '\n';
```
Thanks in advance.
