### ISSUE TITLE
example code  compile error

### ISSUE THREAD

**Issue by dongguaWDY** [nlohmann/json#1562]
```cpp
#include <nlohmann/json.hpp>

// for convenience
using json = nlohmann::json;
namespace ns {
// a simple struct to model a person
struct person {
std::string name;
std::string address;
int age;
};
}
// create a person
ns::person p {"Ned Flanders", "744 Evergreen Terrace", 60};

// conversion: person -> json
json j = p;

std::cout << j << std::endl;
// {"address":"744 Evergreen Terrace","age":60,"name":"Ned Flanders"}

// conversion: json -> person
auto p2 = j.getns::person();

// that's it
assert(p == p2);
```

error: no viable conversion from 'person' to 'json' (aka 'basic_json<>') json j = p;

**Comment by dongguaWDY** [comment]
`
#include <nlohmann/json.hpp>

// for convenience
using json = nlohmann::json;
namespace ns {
    // a simple struct to model a person
    struct person {
        std::string name;
        std::string address;
        int age;
    };
}
// create a person
ns::person p {"Ned Flanders", "744 Evergreen Terrace", 60};

// conversion: person -> json
json j = p;

std::cout << j << std::endl;
// {"address":"744 Evergreen Terrace","age":60,"name":"Ned Flanders"}

// conversion: json -> person
auto p2 = j.get<ns::person>();

// that's it
assert(p == p2);`

> 
error: no viable conversion from 'person' to 'json' (aka 'basic_json<>') json j = p;

**Comment by nlohmann** [comment]
You need to add the code described in https://github.com/nlohmann/json#basic-usage:

```cpp
namespace ns {
    void to_json(json& j, const person& p) {
        j = json{{"name", p.name}, {"address", p.address}, {"age", p.age}};
    }

    void from_json(const json& j, person& p) {
        j.at("name").get_to(p.name);
        j.at("address").get_to(p.address);
        j.at("age").get_to(p.age);
    }
} // namespace ns
```

The conversions don't work without the `from_json`/`to_json` functions.
