### ISSUE TITLE
try_get_to

### ISSUE THREAD

**Issue by TomMettam** [nlohmann/json#1563]
Please consider adding a try_get_to convenience function, which would assign a provided default value in case of a type mismatch (i.e, null)

`json.at("someKey").try_get_to(object.someKey, "DefaultValue");
`

Ideally, this would work in conjunction with a similar convenience method like try_at which would return a default value rather than throwing an exception if a value is not found (and perhaps null should be the default if not specified)

`json.try_at("someKey", json()).try_get_to(object.someKey, "DefaultValue");
`

Why? Well, the most common usage for JSON is for external interchange. In many cases, the sender is not under the control of the developer, and parameters may be added or removed at any time. 

These convenience functions would avoid the need to wrap every single parameter in from_json with a try catch, or a null/exists guard.

I have achieved the same result by wrapping in a template function, but I think this functionality is important enough to warrant being included in the library itself.

**Comment by danielkiedrowski** [comment]
+1
I just updated the library and found a breaking behavior. Before the update, I was able to use json.value("key", "default") to get a default value when "key" was missing in the json or was set to "null". Now I get a type mismatch.
