### ISSUE TITLE
How to determine the type of elements read from a JSON array?

### ISSUE THREAD

**Issue by amwink** [nlohmann/json#1564]
The JSON files I need to read with my program have the form
   `{   "labels":   [ 0, 0, 1, 1 ],   "vectors":   [  [ 1, 1 ],  [ 2, 2 ],  [ 2, 4 ],  [ 4, 2 ]  ]   }`
or 
   `{   "labels":   [ 0, 0, 1, 1 ],   "vectors":   [  "file1",  "file2",  "file3",  "file4"  ]   }`
to represent specimen that have a numerical label and numerical data, the second of which may be given in the JSONs themselves or read from files. 

The labels are read in the line 
```
std::vector <float> *y = 
     new std::vector <float> ( jdesign["labels"].get<std::vector<float>>() );
```
and for the first form the line
```
std::vector<std::vector<float>> 
     xtest1 ( jdesign["vectors"].get<std::vector<std::vector<intensity>>>() );
```
does the trick. But if I want to test for the second form (the values are given as file names) and use 
```
std::vector<std::string> 
     xtest2 ( jdesign["vectors"].get<std::vector<std::string>>() );
```

I get:
```
terminate called after throwing an instance of 'nlohmann::detail::type_error'
what():  [json.exception.type_error.302] type must be string, but is array`
```

Is there a way to find out the type of the elements of `vectors` before assigning them to my program variables?

I am using Debian Linux (stretch, kernel 4.9.0-8-amd64) and GCC 8.2.0 and the json library as pulled from the GitHub repository.

**Comment by nlohmann** [comment]
You could call [`type()`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a2b2d781d7f2a4ee41bc0016e931cadf7.html#a2b2d781d7f2a4ee41bc0016e931cadf7) to get the type.

**Comment by amwink** [comment]
Thanks! but both examples above are `json::value_t::array` -- is it possible to test the types of the array elements in some way?

**Comment by nlohmann** [comment]
You would need to call it for each element. As the array has a begin/end iterator, you can also use `std::all_of` together with functions like `is_string` to check if all elements are strings, for example.

**Comment by amwink** [comment]
That makes sense, thanks again. But if I understand it correctly then I would always first need to do a get<T>() before I could check the contents of the array, which sounds like a catch-22? I think it is better then to add a variable to the JSON to find out what T should be before calling get<T>().

**Comment by nlohmann** [comment]
No, you can access the JSON vector before this:

```cpp
if (std::all_of(jdesign["vectors"].begin(), jdesign["vectors"].end(), [](const json& el){ return el.is_string(); })
{
   // access as string vector, e.g. like
   std::vector<std::string> foo = jdesign["vectors"];
}
```

(untested code, but you should get the gist).
