### ISSUE TITLE
How to generate dll file for this project

### ISSUE THREAD

**Issue by jagdishjadeja** [nlohmann/json#1568]
- Describe what you want to achieve.
I want to generate dll for this project to use in my other projects

- Describe what you tried.
I have not tried anything but i also dont have any idea about that

- Describe which system (OS, compiler) you are using.
windows 

- Describe which version of the library you are using (release version, develop branch).
release version

**Comment by nlohmann** [comment]
The library uses templates, so it is not possible to pre-compile it into a library. https://stackoverflow.com/questions/362822/how-do-i-export-templated-classes-from-a-dll-without-explicit-specification lists some ideas how to proceed.
