### ISSUE TITLE
A "thinner" source code tar as part of release?

### ISSUE THREAD

**Issue by abrownsword** [nlohmann/json#1572]
Would it be possible to have a lighter weight version of the source code tarball included with the release?  The benchmark and test directories are quite large, and while I want the structure and much of the content of your full release, it would be less burdensome if not all of the test and benchmark directories were included.

**Comment by gregmarr** [comment]
See #96

**Comment by abrownsword** [comment]
Yes, exactly the same issue(s) -- my "search-fu" was clearly inadequate.  I haven't seen anyone suggest an additional release tarball as an alternative though.  There is probably a script that is used to build each release, it could be extended to create one more option available for download.

**Comment by gregmarr** [comment]
There have been several different issues for this.  #316

**Comment by abrownsword** [comment]
Yes, I scanned the list of related issues when you posted about 96.  We would prefer as much of the repo 'context' as possible though, not just the bare set of header files -- that's why we're not just grabbing the other provided downloads.
