### ISSUE TITLE
compilation error when using with another library

### ISSUE THREAD

**Issue by bl4ck5un** [nlohmann/json#1577]
- What is the issue you have?

To be honest, I'm not sure if this is a bug in this library, as it **only** happens when used together with another [library](https://github.com/unbound-tech/blockchain-crypto-mpc), and **only** on macOS. But I'd appreciate any insight the authors might have. The error message appears agnostic to the other library in question.

```
/Users/fanz/dev/deco/notary/external/json/single_include/nlohmann/json.hpp:12450:106: error: no matching member function for call to 'to_char_type'
                                    string_buffer[bytes++] = detail::binary_writer<BasicJsonType, char>::to_char_type('\xEF');
                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
/Users/fanz/dev/deco/notary/external/json/single_include/nlohmann/json.hpp:12117:25: note: in instantiation of member function 'nlohmann::detail::serializer<nlohmann::basic_json<std::map, std::vector,
      std::__1::basic_string<char>, bool, long long, unsigned long long, double, std::allocator, adl_serializer> >::dump_escaped' requested here
                        dump_escaped(i->first, ensure_ascii);
                        ^
/Users/fanz/dev/deco/notary/external/json/single_include/nlohmann/json.hpp:14744:15: note: in instantiation of member function 'nlohmann::detail::serializer<nlohmann::basic_json<std::map, std::vector,
      std::__1::basic_string<char>, bool, long long, unsigned long long, double, std::allocator, adl_serializer> >::dump' requested here
            s.dump(*this, true, ensure_ascii, static_cast<unsigned int>(indent));
              ^
/Users/fanz/dev/deco/notary/external/json/single_include/nlohmann/json.hpp:20743:20: note: in instantiation of member function 'nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>, bool, long
      long, unsigned long long, double, std::allocator, adl_serializer>::dump' requested here
        return h(j.dump());
                   ^
/Users/fanz/dev/deco/notary/external/json/single_include/nlohmann/json.hpp:10843:31: note: candidate template ignored: substitution failure [with C = char]: null non-type template argument must be cast to
      template parameter type 'enable_if_t<std::is_signed<char>::value && std::is_signed<char>::value> *' (aka 'void *')
    static constexpr CharType to_char_type(std::uint8_t x) noexcept
                              ^
/Users/fanz/dev/deco/notary/external/json/single_include/nlohmann/json.hpp:10850:21: note: candidate template ignored: requirement 'std::is_unsigned<char>::value' was not satisfied [with C = char]
    static CharType to_char_type(std::uint8_t x) noexcept
                    ^
/Users/fanz/dev/deco/notary/external/json/single_include/nlohmann/json.hpp:10861:31: note: candidate template ignored: requirement 'std::is_unsigned<char>::value' was not satisfied [with C = char]
    static constexpr CharType to_char_type(std::uint8_t x) noexcept
                              ^
/Users/fanz/dev/deco/notary/external/json/single_include/nlohmann/json.hpp:10872:31: note: candidate template ignored: substitution failure [with InputCharType = char, C = char]: null non-type template argument
      must be cast to template parameter type 'enable_if_t<std::is_signed<char>::value && std::is_signed<char>::value && std::is_same<char, typename std::remove_cv<char>::type>::value> *' (aka 'void *')
    static constexpr CharType to_char_type(InputCharType x) noexcept
```

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

In my case, as long as https://github.com/unbound-tech/blockchain-crypto-mpc/blob/master/src/utils/ub_common_def.h is included along with `json.hpp`, the compilation would fail.

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

```
Apple LLVM version 10.0.1 (clang-1001.0.46.3)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

- Did you use a released version of the library or the version from the `develop` branch?

`v3.6.1` is used.

**Comment by Macr0Nerd** [comment]
@nlohmann or @theodelrieu correct me if I'm wrong, but it seems that there is some interference with `to_char`, presumably from the other library. It looks like one of the characters being input isn't being read as `char`.

**Comment by Macr0Nerd** [comment]
@bl4ck5un can you provide an example of what you input and where the supposed error is?

**Comment by bl4ck5un** [comment]
never mind guys, it's a messy project and hard to extract a small example. I can work it around by arranging the header carefully. Will reopen with a reproducible example when I have one. Thanks anyway.

**Comment by x-santiaga-x** [comment]
The compilation error is caused by nullptr has been defined as 0 in ub_common_def.h when compiling with clang.
```
#if defined(__GNUC__) && (GCC_VERSION < 0x0406) // 4.6
#define nullptr NULL
#endif
```
clang [defines](https://stackoverflow.com/a/55926503) GNUC/MINOR/PATCHLEVEL as 4/2/1, i.e. compat with GCC 4.2.1.

So it might be helpful to insert some nullptr type checking with static_assert.

**Comment by gregmarr** [comment]
@x-santiaga-x Did you mean to submit this report to the library containing `ub_common_def.h`?

**Comment by x-santiaga-x** [comment]
I have discovered this error trying to compile my own project with the same #ifdef and it was hard to find.
Adding a static assertion can keep users from researching what `no matching member function for call to 'to_char_type'` might mean.
