### ISSUE TITLE
how i create json file 

### ISSUE THREAD

**Issue by javedabbas112** [nlohmann/json#1581]
console.log("Anycodes Scraper Loaded!");

var titles = document.querySelectorAll(".bf1808");

var titles_count = titles.length;

for (var index = 0; index < titles_count; index++) {
  console.log(titles[index].textContent);
}

var coupons = document.querySelectorAll(".offer_list_item");

var coupons_count = coupons.length;

for (var index = 0; index < coupons_count; index++) {
  var title = coupons[index].querySelector(".bf1808").textContent;
  var type = coupons[index].querySelector(".cou_property").textContent.trim();
  if(type=="Code"){
    console.log("Coupon");
    var coupon_id = document.querySelectorAll(".offer_list_item")[index].getAttribute("data-cid");
    console.log("https://www.anycodes.com/coupon-detail-"+coupon_id+".html");
    var url = "https://www.anycodes.com/coupon-detail-"+coupon_id+".html"

    
    var xhttp = new XMLHttpRequest();
    xhttp.onreadystatechange = function() {
      if (this.readyState == 4 && this.status == 200) {
       
        document.querySelector("body").innerHTML = this.response;
      
        var coupon_code = document.querySelector("#copy-code").textContent;
        console.log(coupon_code);
        myObj={
          

        } 
      
      }
    };
  
    xhttp.open("GET", url, true);
  
    xhttp.send();
  

  }else{
    console.log("Deal");
  }
  // console.log(title + " : " + type);
}

**Comment by nlohmann** [comment]
The code in your example is JavaScript. This library is for C++. Are you sure you have opened this issue in the correct GitHub repository?

**Comment by javedabbas112** [comment]
yes its javascript webscraping extention

**Comment by nlohmann** [comment]
How is the question related to JSON for Modern C++?

**Comment by javedabbas112** [comment]
how can i create javascript object

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by javedabbas112** [comment]
my issue is that i cant create json file

**Comment by nlohmann** [comment]
Please add the details above.

**Comment by huuson235** [comment]
I think I understand what he means. I also want to save my json object to a json file for other programs to read. How can I save json object to file?

**Comment by nickaein** [comment]
@huuson235: As described in [Serialization](https://github.com/nlohmann/json#serialization--deserialization) section, call `dump()` on your JSON object to get its string representation. That string can be then written to a JSON file.

More info on `dump()` can be found at [its documentation page](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a50ec80b02d0f3f51130d4abb5d1cfdc5.html#a50ec80b02d0f3f51130d4abb5d1cfdc5).

**Comment by nlohmann** [comment]
@javedabbas112 Do you need further information?
