### ISSUE TITLE
getting error terminate called after throwing an instance of 'std::domain_error'   what():  cannot use at() with string

### ISSUE THREAD

**Issue by Munodiwa** [nlohmann/json#1582]
After performing a http get request I receive a json string containing a string. I need to access the link inside this json string. I am using ubuntu. I downloaded the package with the cmd line sudo apt-get install nlohmann-json-dev

#include <stdio.h>
#include <stdlib.h>
#include "json.hpp"
#include <curl/curl.h>
#include <iostream>

using nlohmann::json;

int main()
{
curl_global_init( CURL_GLOBAL_ALL );
CURL * myHandle;
CURLcode result; // We’ll store the result of CURL’s webpage retrieval, for simple error checking.
myHandle = curl_easy_init ( ) ;
// Notice the lack of major error checking, for brevity
curl_easy_setopt(myHandle, CURLOPT_URL, "https://matiusulung.com/se.json");
result = curl_easy_perform( myHandle);
json object = "(result)"; 
std::cout<<object.at("link").get<std::string>();
curl_easy_cleanup( myHandle );
printf("LibCurl rules!\n");
return 0;

}

**Comment by nlohmann** [comment]
What’s the JSON you pass to the server?

**Comment by Munodiwa** [comment]
this is the json I receive from the server {"link": "ec2-3-121-209-122.eu-central-1.compute.amazonaws.com"}

**Comment by nlohmann** [comment]
Which version of the library are you using?

**Comment by nickaein** [comment]
```cpp
json object = "(result)";
```

creates an JSON object with value type of `string`. Shouldn't it be?

```cpp
json object = json::parse(result);
```

instead?

**Comment by nlohmann** [comment]
@nickaein is right - you created a string with `json object = "(result)";`, and the error message makes sense: `cannot use at() with string`.
