### ISSUE TITLE
Injecting class during serialization

### ISSUE THREAD

**Issue by pkartner** [nlohmann/json#1584]
I have a data class that I want to use during serialization to map a string value to something else. 

```
static void from_json(const json& j, T& value) 
{
    // I want to use my data class here to map the value returned from json
    j.at("somevalue");
}
```

Is this currently possible with the library?

**Comment by nlohmann** [comment]
Did you try the approach described in https://github.com/nlohmann/json#arbitrary-types-conversions? Can you provide an example?

**Comment by pkartner** [comment]
I'm not 100% sure what you mean. My prefered solution would be something like this.

`    void from_json(const json& j, person& p, const data& d) {
        auto value = j.at("name").get();
        p.name = d.get(value);
    }`

**Comment by nlohmann** [comment]
I'm afraid there is no API for this at the moment, I'd have no idea how to add it.
