### ISSUE TITLE
dump_escaped possible error ?

### ISSUE THREAD

**Issue by noxytrux** [nlohmann/json#1589]
I'm looking at dump_escaped implementation and i'm concerned about `uint32_t codepoint` variable it is not initialized with any value whatsoever. So imo in release it should contain garbage which then will be processed in decode method.

I'm right or just touchy ?

https://github.com/nlohmann/json/blob/develop/include/nlohmann/detail/output/serializer.hpp#L304

**Comment by nickaein** [comment]
I seems that `codepoint` is passed by referenced to [decode()](https://github.com/nlohmann/json/blob/develop/include/nlohmann/detail/output/serializer.hpp#L782) and will be assigned there.

**Comment by noxytrux** [comment]
Ah yes, you are right because of state being always UTF8_ACCEPT at start it will init codepoint with `static_cast<uint32_t>(0xff >> type) & (byte);`
