### ISSUE TITLE
Error in adl_serializer

### ISSUE THREAD

**Issue by frenzisys** [nlohmann/json#1590]
Hi!
I have a big problem and i don't know where i wrong.
i make this partial specialization for my classes:
```
	template <class T>
	struct adl_serializer<nia::value_t<T>> {
		static void to_json(json &j, const nia::value_t<T> &object) {
			if (object) object->toJson(j, true);
			 else  j = "";			
		}
		static void from_json(const json &j, nia::value_t<T> &object) {
			if (!object) throw "";
			else object->fromJson(j, true);			
		}
	};
```

Unfortunately this don't work, i have to write full specialization 
```
	template<>
	struct adl_serializer<nia::value_t<example>> {...}
```
for every type of class because 
`	nlohmann::detail::has_from_json<nlohmann::json,nia::value_t<example>>::value`
don't find the generic template.

i use clang9 in qtcreator... what i wrong?

**Comment by AntonioL** [comment]
I am running into a similar issue as well.

Can you advise?

**Comment by nlohmann** [comment]
Can you provide a small working example for the type?
