### ISSUE TITLE
I have a C structure which I need to convert to a JSON. How do I do it? Haven't found proper examples so far.

### ISSUE THREAD

**Issue by guru-77** [nlohmann/json#1591]
- Describe what you want to achieve.

- Describe what you tried.

- Describe which system (OS, compiler) you are using.

- Describe which version of the library you are using (release version, develop branch).

**Comment by pboettch** [comment]
Have you seen this in the main README-file (start-page of the project's site): https://github.com/nlohmann/json#arbitrary-types-conversions
