### ISSUE TITLE
initializer list constructor makes curly brace initialization fragile

### ISSUE THREAD

**Issue by maddanio** [nlohmann/json#1594]
Hey,

I just discovered when i convert something to json on the fly like this:
`nlohmann::json{my_value}`
it turns it into an array, which is highly unexpected. this is a bit like the operator T() problem: too muc magic. I would be less dangerous if array/object construction where explicit, i.e. json::array({....})/json::object({{key, value},...). one can even make json::array/object objects and lose the round braces.

**Comment by nlohmann** [comment]
The problem is known, and changing it would be a breaking change...

**Comment by maddanio** [comment]
As for operator T(), right? I would say it should be part of the same discussion. Or a version 2 started, which has less magic and better composbility?

**Comment by olavurmortensen** [comment]
Would probably be a good idea to mention this in the documentation. The Cpp Core Guidelines recommend always using value initialization, so I expect a lot of people are doing that. Had this problem today, and it took me a good while to locate it, and didn't fully understand it before finding this issue.

**Comment by falbrechtskirchinger** [comment]
@olavurmortensen It is mentioned in the FAQ. Where did you look? In other words, where should it be mentioned to make it more discoverable? Probably at least the constructor, where I can't find it.

**Comment by olavurmortensen** [comment]
I've only read in the reference:
https://json.nlohmann.me/api/basic_json/parse/
and the README:
https://github.com/nlohmann/json#read-json-from-a-file
But I didn't see any mention of this there.
