### ISSUE TITLE
Random Kudos: Thanks for your work on this!

### ISSUE THREAD

**Issue by davepl** [nlohmann/json#1596]
I had to recently convert a bunch of embedded json that was composed with printfs, and used the json.hpp library, and love it!

That it is as powerful and flexible as it is, while allowing me to do what I needed to do in 3 minutes without reading docs, is a thing of beauty.

All complicated stuff should be so simple.

**Comment by brouer** [comment]
Seconded. Absolutely wonderful piece of work.
Dead simple to "install", and a joy to use.

**Comment by nlohmann** [comment]
Thanks a lot!
