### ISSUE TITLE
Accessing value with json pointer adds key if not existing

### ISSUE THREAD

**Issue by sdaly2107** [nlohmann/json#1600]
- What is the issue you have?

When accessing a key using json pointer, if the key doesn't exist, it is added.  Is this expected behaviour?  If so, is there some alternative const accessor we can use?  For now, we are working around this by copying the object.

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

        json json;
        json["something"]["else"] = "me";

        auto dumpA = json.dump(4);

        auto value = json["/something/else"_json_pointer].get<std::string>();
        auto dumpB = json.dump(4);
        REQUIRE(dumpA == dumpB); //ok

        auto blah = json["/xyz"_json_pointer];
        auto dumpC = json.dump(4);
        REQUIRE(dumpB == dumpC); //fail, because new key has been added

- What is the expected behavior?

{
    "something": {
        "else": "me"
    },
    "xyz": null  <-- didn't expect this to be added when accessing via json pointer
}

- And what is the actual behavior instead?

Key added.

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

MSVC + Win 10
GCC + CentOS 7

- Did you use a released version of the library or the version from the `develop` branch?

Yes

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by brouer** [comment]
I use code like this:

        try
        {
            last_page = j.at("isLastPage");
        } catch (...)
        {
            //"isLastPage" was not present
            last_page = true;
        }

Quote from README.md:

> If you are not sure whether an element in an object exists, use checked access with the at() function.

**Comment by sdaly2107** [comment]
So looks like "at" might be the solution.  I'd rather not be throwing and catching in normal paths though - would be nice if count() worked with json pointer too, then I could do if(count(json_pointer) then at(json_pointer).

**Comment by brouer** [comment]
I only try/catch around optional entries that might not be present, in which case I may provide my own default as shown.

I don't try/catch with entries I expect to be there. If that happens, I let the exception propagate back up to the caller, as I consider that a parse error.

YMMV.

**Comment by nickaein** [comment]
> When accessing a key using json pointer, if the key doesn't exist, it is added. Is this expected behaviour? 

I believe yes, as [`basic_json::operator[]`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_ac6946dffeb3be5aa173645f0467a44b3.html#ac6946dffeb3be5aa173645f0467a44b3) documentation states. This mimics the behavior of `operator[]` on [`std::map`](https://en.cppreference.com/w/cpp/container/map/operator_at) which also adds an object when the key does not already exist.

>  If so, is there some alternative const accessor we can use? For now, we are working around this by copying the object.

AFAIK, this is not such API. To avoid copying, your best bet is probably a similar solution mentioned by @brouer. Here is documentation of [`basic_json::at(json_pointer&)`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a8ab61397c10f18b305520da7073b2b45.html#a8ab61397c10f18b305520da7073b2b45) that covers different scenarios.

> I'd rather not be throwing and catching in normal paths though - would be nice if count() worked with json pointer too.

That's very good point. Though I think adding an overload to [`basic_json::contains()`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a0a45fc740637123fdf05fef970f8be47.html#a0a45fc740637123fdf05fef970f8be47) that accepts `json_pointer` would be more fitting.  @nlohmann, @garethsb-sony  Any thoughts?

**Comment by nlohmann** [comment]
I understand the issue. The implementation of JSON Pointers is a bit hairy. I agree that `contains` or `count` should be available for JSON Pointers too.

**Comment by nlohmann** [comment]
I added a `contains` function for JSON pointers, see https://github.com/nlohmann/json/commit/258fa798f15a0010d04eaa23010be8b53afd2f4d. Feedback is greatly appreciated! @sdaly2107 @brouer @nickaein

**Comment by sdaly2107** [comment]
Looks good to me, thank you very much :D

**Comment by nlohmann** [comment]
* * *

### 🔖 Release item

This issue/PR will be part of the next release of the library. This template helps preparing the release notes.

#### Type

- [x] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] ⚡️ Improvement
- [ ] 🔨 Further Change
- [ ] 🔥 Deprecated function

#### Description

- Add overload of `contains` to check if a JSON pointer is valid without throwing exceptions. #1600

* * *
