### ISSUE TITLE
Value method with undocumented throwing 302 exception

### ISSUE THREAD

**Issue by lohmanndouglas** [nlohmann/json#1601]
I am using value function and I did not figure out if this should be the correct behavior according to the documentation. 

The following code  terminate called after throwing an instance of   [json.exception.type_error.302] type must be string, but is number. 

Should I add this throwing to the docs?

```C++ 
int main() 
{
    json json_types =
    {
        {"MyString", "Hello, world!"},
        {"MyInt", 123}
    };   
    std::string string_id;
    json_types.value("MyInt", string_id);
} 
```

**Comment by nlohmann** [comment]
You're right. The documentation (https://nlohmann.github.io/json/classnlohmann_1_1basic__json_adcf8ca5079f5db993820bf50036bf45d.html#adcf8ca5079f5db993820bf50036bf45d) only mentions the 306 exception.

**Comment by nlohmann** [comment]
* * *

### 🔖 Release item

This issue/PR will be part of the next release of the library. This template helps preparing the release notes.

#### Type

- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] ⚡️ Improvement
- [x] 🔨 Further Change
- [ ] 🔥 Deprecated function

#### Description

- Completed documentation of `value()` function with respect to type_error.302 exception.

* * *

**Comment by nlohmann** [comment]
Thanks for reporting! The documentation will be updated with the next release.
