### ISSUE TITLE
Reading and writing array elements

### ISSUE THREAD

**Issue by kamocio** [nlohmann/json#1607]
Say I am given a JSON:

{
  "name": "John Doe",
  "meals": 
  [
    {
      "breakfast": "omlet at 8AM"
    },
    {
      "lunch": "salad at 12"
    }
  ]
}

And its loaded into below object(does not matter how):

nlohmann::json someJson;

Now I'd like to load the "meals" structure into some STL container.

std::? = someJson["meals"];

I also need to be able to make some changes to the values and write it back.

someJson["meals"] = ?;

How would that look like? Struggling to figure out the type(s) to use here.

**Comment by nickaein** [comment]
The library already provides [STL-like access](https://github.com/nlohmann/json#stl-like-access) APIs for reading/writing JSON values. Do they cover your requirements?

**Comment by kamocio** [comment]
Thanks, that's what I've been trying to figure out. I'm not able to "fit" any STL container to the JSON format I listed above. 

Finding an STL container (even if its a nested, complicated one) that would allow reading/writing of "meals" element is what this question is about.

**Comment by kamocio** [comment]
It appears that the STL structure would be: 
vector<map<string, string>>

I was able to make it work like that, though the c++ code of adding/searching elements is quite ugly (nothing to do with the library, just a weird JSON doc format). I'll close this.

**Comment by nickaein** [comment]
> It appears that the STL structure would be:
> vector<map<string, string>>

The underlying data type is `std::map<std::string, basic_json>>` for JSON objects and `std::vector<basic_json>` for JSON arrays, by default. (More info [here](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a5e48a7893520e1314bf0c9723e26ea2a.html#a5e48a7893520e1314bf0c9723e26ea2a) and [here](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_ae095578e03df97c5b3991787f1056374.html#ae095578e03df97c5b3991787f1056374)).

>  though the c++ code of adding/searching elements is quite ugly (nothing to do with the library, just a weird JSON doc format). I'll close this.

Correct. JSON schema has a great impact on ease of implementation . I've written a sample demo based on your schema: https://wandbox.org/permlink/iVUmUQV1GDtXzr6Q

You can find more info at [README page](https://github.com/nlohmann/json) and indeed the [documentations](https://nlohmann.github.io/json/).

**Comment by kamocio** [comment]
Thanks!
