### ISSUE TITLE
Add C++17-like emplace.back() for arrays.

### ISSUE THREAD

**Issue by TrueWodzu** [nlohmann/json#1609]
Hi,

in C++17 there is a [change](https://en.cppreference.com/w/cpp/container/vector/emplace_back) in return value of std::vector::emplace_back(); Would it be possible to add this in library, so I could do something like this:
```
json json_obj;
json_obj["Type"] = 1;
json_obj["Version"] = 1;
json_obj["Documents"] = json::array();
auto document = json_obj["Documents"].emplace_back(); // Currently returns error.
```

**Comment by nlohmann** [comment]
That sounds doable!

**Comment by nlohmann** [comment]
@TrueWodzu I extended `emplace_back` to return a reference (see https://github.com/nlohmann/json/commit/1be63431f3910f09aa5ada66bc691ac391e50794). Is this what you had in mind?

**Comment by TrueWodzu** [comment]
Yes, exactly. Thank you :)

**Comment by nlohmann** [comment]
I reopened the issue, because the change has not yet been merged to the develop branch.

**Comment by TrueWodzu** [comment]
That's fine, you the boss ;)

**Comment by nlohmann** [comment]
* * *

### 🔖 Release item

This issue/PR will be part of the next release of the library. This template helps preparing the release notes.

#### Type

- [x] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] ⚡️ Improvement
- [ ] 🔨 Further Change
- [ ] 🔥 Deprecated function

#### Description

- Added return value for `emplace_back` function, returning a reference to the added element. #1609

* * *
