### ISSUE TITLE
is it possible convert json object back to stl container ?

### ISSUE THREAD

**Issue by tuananh** [nlohmann/json#1610]
I'm using emscripten and when I try to do emscripten::val(my_json), it will fail because `BindingError: _emval_take_value has unknown type`

Is there anyway to convert json object back to using stl container? without knowing the shape of the object?

**Comment by nlohmann** [comment]
Can you provide an example?

**Comment by tuananh** [comment]
I ended up using `val::object` and `val::array` in emscripten. this is not related to this lib. sorry.
