### ISSUE TITLE
Improved Enum Support

### ISSUE THREAD

**Issue by amirmasoudabdol** [nlohmann/json#1611]
So, I see that we are currently supporting enum types relatively well but the documentation mentioned there are some caveats. I was wondering if it’s a good idea to use something like [magic enum](https://github.com/Neargye/magic_enum) and achieve a safer conversion. I understand that you might not want to include another code to your code base but do you think this is something you’d like to have or you think the current method is sufficient? If you think it worth it, I maybe able to spare some time and work on it 👍🏼

**Comment by nlohmann** [comment]
That’s a C++17 library. What exactly do you have in mind?

**Comment by amirmasoudabdol** [comment]
I think I'm asking for some nicer syntax for this, but I didn't consider the standard at all, my bad! Basically, I wanted to avoid defining the map macro, and see if it's possible to extract the enum names automatically, exactly what magic_enum does.

**Comment by nlohmann** [comment]
I see. The library does not offer a unique mapping of enums, because it is up to the user to decide how to encode them (integers, strings, ???). But I think an example how to use a library like magic enum to support writing a `to_json`/`from_json` could be helpful.

**Comment by fredemmott** [comment]
I put together the magic enum stuff here: https://github.com/fredemmott/magic_json_serialize_enum
