### ISSUE TITLE
program crash everytime, when other data type incomming in json stream as expected

### ISSUE THREAD

**Issue by bnadem** [nlohmann/json#1612]
i use this nhlohman in backend , this wonderfull tool, i becomme every second json stream from outside, but when the users send other datatyp in json stream, my backend crash every time, i muss use in every code line try catch, to prevent crash backend, there is no other solution please, thanks 
- Describe what you want to achieve.

- Describe what you tried.

- Describe which system (OS, compiler) you are using.

- Describe which version of the library you are using (release version, develop branch).

**Comment by nlohmann** [comment]
Can you provide more information? Maybe example code? The library throws an exception in case of a parse error - is this your issue?

**Comment by bnadem** [comment]
Yes ihre this auto user_input = j_string.get<std::string>();
But user_input is integer, other datatyp but not string
Think for replay

**Comment by nlohmann** [comment]
You need to check the types yourself. Code like

```cpp
std:.string user_input;
if ( j_string.is_string())
    user_input = j;
```

is safe.

**Comment by bnadem** [comment]
I mean like that: std:string user_input = jsondata("inputdtream").get<std:string>().
  How I can check inputdstream ist string?

**Comment by nlohmann** [comment]
With the `is_string()` method: https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a69b596a4a6683b362095c9a139637396.html#a69b596a4a6683b362095c9a139637396

**Comment by bnadem** [comment]
thanks
