### ISSUE TITLE
Replace assert with throw for const operator[]

### ISSUE THREAD

**Issue by terminatorul** [nlohmann/json#1614]
Is is possible please to change const operator[] to throw if field name does not exist, instead of declaring this case as "undefinded" and then using assert ?

**Comment by nlohmann** [comment]
This would be a breaking change, so no.

**Comment by sogartar** [comment]
@nlohmann , I don't understand how this is a breaking change if the behavior is undefined. It can be anything. You should not get to the undefined behavior point anyway. If it throws it is just restricting the "beyond this point everything is possible" to only throwing.
The thing that would change is the burden of another bounds check.

**Comment by nlohmann** [comment]
But `operator[]` is not supposed to do bound checking.

**Comment by terminatorul** [comment]
It saves users the tedious task of tracking when the json object is const, and if so then checking before access if member exists. And if not found, maybe throw something :) or otherwise return.

For objects, the run-time overhead of my explicit check is duplicated work, because the operator will do the search in the properties map any way.

Maybe more important is keeping the behavior consistent with user expectations: if the non-const operator is always safe, how can the const one crash ? For most users out there, the distinction between const and non-const definitely should not cause such behavior.

Imagine my surprize when the QA team reported my latest fix was taking the webserver down. When all I did was to add const to a parameter that I do not change, and with a catch(...) clause carefully in place.

**Comment by nlohmann** [comment]
You are aware of [`at`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_acac9d438c9bb12740dcdb01069293a34.html#acac9d438c9bb12740dcdb01069293a34)?
