### ISSUE TITLE
Precedence of to_json and builtin harmful

### ISSUE THREAD

**Issue by ingo-loehken** [nlohmann/json#1617]
For a class that supports user-defined conversion to a const char* (compatible to string_type of nlohmann::json) and a to_json specialization, the expectation would be that the to_json function takes precedence.

```cpp
class MyClass
{
public:
	operator const char*() const; // (1)
	template <typename jsonT, typename T> friend inline typename std::enable_if_t<std::is_same_v<MyClass,std::remove_const_t<std::remove_reference_t<T>>>> to_json(jsonT&, T&&); // (2)
};

nlohmann::json x{MyClass{}}; // (3)
```
Executing (3), I would expect that (2) is selected, but (1) takes precedence.

**Comment by igoloe** [comment]
Built with Visual Studio 2017 15.4.1

Rationale
The example is just a simplified version of a to_json template function catching all derived classes convertible to a base class, where all the derived classes. All those classes are legacy data classes. Therefore eliminating the error prone implicit user defined conversion operator is very expensive and out-of-scope.
