### ISSUE TITLE
[Help] How to Improve Json Output Performance with Large Json Arrays

### ISSUE THREAD

**Issue by calben** [nlohmann/json#1624]
Hey everyone,

I have `class A` which includes a `std::deque<class B>`.
Both `A` and `B` have an `AsJson()` that return a json object, where `A`'s `AsJson` pushes back many instances of `B` onto an array, and later on I print this Json as a string.

```
    nlohmann::json json;
    // add some other fields
    ...
    ...
    for (auto e : events) {
        json["events"].push_back(e->AsJson());
    }
    return json;
    // later outputting json to stream as string or cbor
```

Constructing the large Json takes a bit of memory and time and then the whole things needs to be processed again to format to a string as well.
Is there a better way to handling constructing and outputting Jsons with large arrays with this library?

Thanks!

**Comment by igoloe** [comment]
Use an json array an reserve an then enplace back.

```cpp
nlohmann::json::array_t eventsAsJson;
eventsAsJson.reserve(events.size());

// for-loop or std::for_each

return {"events",std::move(eventsAsJson)};
```

**Comment by nlohmann** [comment]
@calben Does @igoloe 's proposal work for you?

**Comment by calben** [comment]
That does help a bit!  
Thank you.
