### ISSUE TITLE
Can without default constructor function for user defined classes when only to_json is needed?

### ISSUE THREAD

**Issue by akeyliu** [nlohmann/json#1629]
- Describe what you want to achieve.
1.  In my project with many user defined classes, JSON is used to streamlize for communication and log;
2. I added only to_json() for user defined classes;
3. I need to add default constructor function for all user defined classes, and it's work.
4. Some user defined classes with default constructor function is meansless and useless.
My Questions is  if we can ignore default constructor function when we only need to_json()?

- Describe what you tried.
1.  In to_json() for user defined classes, an example code for CClass is like these:
   friend inline void (JSON& j, const CClass1& obj1) {
     j["name1"] = obj1.strName;
    j["member"] = JSON(obj1.m_obj2);
  };
2. In upper code, JSON is typedef nlhomann::json,  obj1 is the current class object, obj2 is member class object, and maybe is STL object, i.e.  vector<CClass2>; 
3. If we have all to_json() for every user defined classes, it's possiable for Arbitrary types conversions without default constructor function for those classes?

- Describe which system (OS, compiler) you are using.
Ubuntu 18.04 LTS gcc 7.3

- Describe which version of the library you are using (release version, develop branch).
master branch version 3.6.1

**Comment by nlohmann** [comment]
This section of the README may be of interest: https://github.com/nlohmann/json#how-can-i-use-get-for-non-default-constructiblenon-copyable-types

(Or did I misunderstood the issue?)

**Comment by akeyliu** [comment]
Yes, I think my issue in not the same as the demo in README.
1. My question is not there can be a default construct function for user defined class, but not mandatory when only to_json() function is used without from_json() function.

**Comment by nlohmann** [comment]
Sorry, I do not understand. Could you give a small self-contained example?

**Comment by akeyliu** [comment]
Follow code is the real code in my project with public namespace.
class CSolution : public CObject
{
public:
    CSolution( string strBatchId ="", PTIME ptimeTakeOff = PTIME_DEFAULT_START );
    friend inline void to_json(JSON& j, const CSolution& obj) { 
                j["BatchId"]=obj.m_strBatchId; 
               j["TakeoffTime"]=obj.m_ptimeTakeOff;  
    };
}

1. These code are work OK. 
2. The original construct function for class CSolution should have a construct function without default value for strBatchId, because strBatchId should be a meaningful value;
3. But I must make it a default constrcution function, or to_json will compile fail for the class CSolution;
4. The default constructor function CSolution is weird, because strBatchId in the construct function should be defined meaningful, and may make it misused if forget the variable for the construct function.
5. I think to_json function should not use the default construct function for the class, and only from_json need it, please correct me if I misunderstand it.

**Comment by nlohmann** [comment]
Here is a complete example for a type `foo` that is not default constructible, yet can be converted to JSON:

```cpp
#include "json.hpp"
#include <iostream>

using json = nlohmann::json;

class foo
{
  public:
    foo() = delete;
    foo(int i) : m_i(i) {}
    int get_i() const { return m_i; }
    
  private:
    int m_i;
};

void to_json(json& j, const foo& f)
{
    j["i"] = f.get_i();
}

int main()
{
    foo ten(10);
    json j = ten;
    std::cout << j << std::endl;
}
```

**Comment by akeyliu** [comment]
Got it and really thanks, it's done.
