### ISSUE TITLE
To integrate an inline helper function that return type name as string

### ISSUE THREAD

**Issue by ghostplant** [nlohmann/json#1632]
- Describe the feature in as much detail as possible.
To integrate an inline helper function that return type name as string.

- Include sample usage where appropriate.
It helps for many runtime requirement, not only for debugging type data when logging, but also for transferring type information as message to other program components that is not with nlohmann library integrated. Using `is_number(), is_array() and ..` case by case is a lot more verbose which is unfriendly for those requirement.

The solution should be simple, and it is recommended to integrate into the library itself:
```sh
inline std::string json::type_as_string() {
  if (this->is_bool())
    return "bool";
  if (this->is_number_integer())
    return "int";
  if (this->is_number_float())
    return "float";
  ...
}
```

**Comment by nickaein** [comment]
This is already [`basic_json::type_name()`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a9d0a478571f82f0163b96b2424cd998f.html#a9d0a478571f82f0163b96b2424cd998f) method available for JSON objects. Does that accomplish what you are looking for?

**Comment by ghostplant** [comment]
@nickaein Thanks, it is just a little hard to find such usage from the documentation and I think it is too hidden.
