### ISSUE TITLE
Add json type as value

### ISSUE THREAD

**Issue by dvfdr43** [nlohmann/json#1636]
- Describe what you want to achieve.
I want to add `json` type object to other `json` object

- Describe what you tried.
```
std::vector<json> vec;
... // fill vec

json all;
for (auto obj : vec)
    all["inside"].emplace_back(obj):

```

- Describe which system (OS, compiler) you are using.
VS 2019

- Describe which version of the library you are using (release version, develop branch).
Latest from the Github (master)

PROBLEM:
but after `emplace_back` / `push_back`  the `all` json object is still empty

**Comment by jaredgrubb** [comment]
I'm not sure I follow. Can you explain what you get and what you were expecting to get?

**Comment by nickaein** [comment]
Are you sure `vec` is filled correctly? I tested the following demo code on VS 2019

```cpp
#include <iostream>
#include <vector>
#include "json.hpp"

int main()
{
    std::vector<nlohmann::json> vec;
    vec.push_back({ "item1", 1 });
    vec.push_back({ "item2", 2 });
    vec.push_back({ "item3", 3 });

    nlohmann::json all;

    for (auto obj : vec)
        all["inside"].emplace_back(obj);

    std::cout << all.dump() << std::endl;
    return 0;
}
```

and it outputs the following as expected:

```
{"inside":[["item1",1],["item2",2],["item3",3]]}
```

**Comment by nlohmann** [comment]
@dvfdr43 Did @nickaein 's answer help you?

**Comment by dvfdr43** [comment]
Solved, thank you
