### ISSUE TITLE
json.SelectToken("Manufacturers.Products.Price");

### ISSUE THREAD

**Issue by xOrMalware** [nlohmann/json#1637]
Using the following pseudo code,

json.SelectToken("Manufacturers.Products.Price");

Is there a way to do to gain the value of the price ?

json, is the structured data and SelectToken is just an example method.

**Comment by nickaein** [comment]
These sections of README could be helpful: 
* [JSON as first-class data type](https://github.com/nlohmann/json#json-as-first-class-data-type)
* [STL-like access](https://github.com/nlohmann/json#stl-like-access)
* [Implicit conversions](https://github.com/nlohmann/json#implicit-conversions)
* [JSON Pointers](https://github.com/nlohmann/json#json-pointer-and-json-patch)


You can reference the JSON object you are looking for either step by step e.g.

```cpp
auto price = j["Manufacturers"]["Products"]["Price"].get<int>();
```

or by using JSON Pointers, e.g.
```cpp
auto price = j["Manufacturers/Products/Price"_json_pointer].get<int>();
```

**Comment by nlohmann** [comment]
@xOrMalware Do you need further assistance?
