### ISSUE TITLE
nlohmann::adl_serializer<T,void>::to_json no matching overloaded function found

### ISSUE THREAD

**Issue by yoyo3243** [nlohmann/json#1641]
I want to serialize a vector of a type I created. (ex: std::vector< RoomData >)

So I used the to_json function on the class RoomData:
![Screenshot_61](https://user-images.githubusercontent.com/51876915/59562388-b15ef400-9034-11e9-927a-080f168e148f.png)

And serialize it like that: (res.rooms is std::vector< RoomData >)
![Screenshot_62](https://user-images.githubusercontent.com/51876915/59562397-dce1de80-9034-11e9-9f39-c63c1ac73c53.png)

*Both are found on the same file (the to_json file at the top)

but I'm getting those errors:
1) nlohmann::adl_serializer<T,void>::to_json no matching overloaded function found (File: json.hpp, line 1256)
2) Failed to specialize function template 'unknown-type nlohmann::adl_serializer<T,void>::to_json(BasicJsonType &, ValueType &&) noexept(<expr>)' (File: json.hpp, line 1256)

I'm using the latest version.

Any idea where is this coming from?

**Comment by nickaein** [comment]
Section [Arbitrary types conversions](https://github.com/nlohmann/json#arbitrary-types-conversions) might be helpful. Have you tried marking `RoomData&` parameter of `to_json` as a `const` reference?

As a sidenote, thanks for posting the code as clean and readable. You can also use builtin Markdown support for posting styled code in Github as [described here](https://guides.github.com/features/mastering-markdown/) (**Examples** section under the **Codes** tab). The plus would be that the code will be copy-able and searchable.

**Comment by yoyo3243** [comment]
> Section [Arbitrary types conversions](https://github.com/nlohmann/json#arbitrary-types-conversions) might be helpful. Have you tried marking `RoomData&` parameter of `to_json` as a `const` reference?
> 
> As a sidenote, thanks for posting the code as clean and readable. You can also use builtin Markdown support for posting styled code in Github as [described here](https://guides.github.com/features/mastering-markdown/) (**Examples** section under the **Codes** tab). The plus would be that the code will be copy-able and searchable.

Thank you very much, that was my problem.
