### ISSUE TITLE
Problem getting vector (array) of strings

### ISSUE THREAD

**Issue by chakpongchung** [nlohmann/json#1644]
Similar to this one:

https://github.com/nlohmann/json/issues/44

```
#include <nlohmann/json.hpp>
#include <iostream>

using nlohmann::json;

int main() {
  auto j = R"(
    {
         "names": ["Tim", "Tom"],
         "num": [1, 2]
    }
    )"_json;

  std::vector<std::string> names;
  names = j["names"];

  for (auto i : names) {
    std::cout << i << " ";
  }

  // prints: Tim Tom
}
```

> main.cpp:14:20: error: ambiguous overload for ‘operator=’ (operand types are ‘std::vector<std::__cxx11::basic_string<char> >’ and ‘nlohmann::basic_json<>::value_type {aka nlohmann::basic_json<>}’)
   names = j["names"];

Hi @nlohmann , separating the definition and declaration doesnt work again. Any solution for this? In some cases this separation is needed.

**Comment by nickaein** [comment]
Implicit type conversion *from JSON* objects [is not recommended](https://github.com/nlohmann/json#implicit-conversions) anymore. You might use explicitly-typed [`get<T>()`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_aa6602bb24022183ab989439e19345d08.html#aa6602bb24022183ab989439e19345d08) method:

```cpp
names = j["names"].get<std::vector<std::string>>();
```

**Comment by nlohmann** [comment]
This is a known issue, and there is no real way to fix it while preserving support for implicit conversions. The proposal of @nickaein works, however. You can further simplify the code with `get_to` (https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a65753c68f06639eda0d355f919564e01.html#a65753c68f06639eda0d355f919564e01):

```
j["names"].get_to(names);
```

**Comment by nlohmann** [comment]
@chakpongchung Do you need further assistance?
