### ISSUE TITLE
Suggestion: replace alternative tokens for !, && and || with their symbols

### ISSUE THREAD

**Issue by NotAPenguin0** [nlohmann/json#1652]
Title explains the issue. The usage of `and`, `or`, and `not` instead of `&&`, `||` and `!` has caused more compiler errors and headscratching for me than it adds to the readability of the code.

**Comment by nlohmann** [comment]
Thanks for suggesting, but I like this. Why does it bother you how the library‘s internal logic is expressed?

**Comment by NotAPenguin0** [comment]
When compiling using the latest release from the master branch today, clang 7 threw about 90 compiler errors at me which weren't understandable at all. Turns out replacing the alternative tokens with the symbols fixed the problem.

**Comment by gregmarr** [comment]
Sounds like either a compiler bug or something in your environment is doing something illegal with the preprocessor.  These are reserved words in C++ and can't be redefined.  Do you have a small sample program that shows the errors?

**Comment by nlohmann** [comment]
It really sounds like a bug. We use Clang 7 in our CI via Travis, and also include `<ciso646>` for compilers that have issues with these operators like MSVC.

**Comment by NotAPenguin0** [comment]
I don't know what caused it. If this issue is only present in my setup it's fine to leave it like this (I just ran a simple find-replace on the include to fix it for myself).

**Comment by nlohmann** [comment]
I'm closing this as it is unrelated to the library. Feel free to check back if you found the reason why your compiler complained about the operators.
