### ISSUE TITLE
Support Fleese Binary Data Format

### ISSUE THREAD

**Issue by Type1J** [nlohmann/json#1654]
Fleece is a binary encoding of JSON-like data similar to the others already supported. It's used as the storage format for Couchbase Lite: https://github.com/couchbaselabs/couchbase-lite-C

Here's the implementation used by Couchbase: https://github.com/couchbaselabs/fleece

**Comment by nlohmann** [comment]
Is there more information on the actual encoding? I only found the [design document](https://github.com/couchbaselabs/fleece/blob/master/Fleece.md) which does not explain how values are encoded in detail. I would like not to reverse engineer the format using their encoder...

**Comment by Type1J** [comment]
I'm not sure. I'll leave a link to it if I find it. It looks like we'll be using this format for a project, but abstracted through a library. I'm going to close this issue until I can give you a more concrete definition of this format.
