### ISSUE TITLE
Can't stream json object in to std::basic_stringstream<wchar_t>

### ISSUE THREAD

**Issue by BrainStone** [nlohmann/json#1656]
- What is the issue you have?

It is not possible to directly stream a json object into a `std::basic_stringstream<wchar_t>`.

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- Try to stream an `json` object into a `std::basic_stringstream<wchar_t>`

(Not) working minimal example:
https://wandbox.org/permlink/UPTfYGpCkteUSbDx

- What is the expected behavior?

That the required operator overload exists, so it can be streamed into a `std::basic_stringstream<wchar_t>` like it can into a `std::basic_stringstream<char>`

- And what is the actual behavior instead?

The operator overload is missing resulting in a complier error.

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

GCC 8.3 on Debian 10 (and yes, it is supported according to the link)

- Did you use a released version of the library or the version from the `develop` branch?

Using version 3.6.1

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

```
99% tests passed, 1 tests failed out of 88

Label Time Summary:
all        = 2271.43 sec*proc (41 tests)
default    = 134.07 sec*proc (41 tests)

Total Test time (real) = 2446.36 sec

The following tests FAILED:
         80 - test-unicode_all (Timeout)
Errors while running CTest
```

**Comment by nlohmann** [comment]
This is indeed not supported in the moment. What would be the encoding of the characters in the stream? UTF-16?

**Comment by BrainStone** [comment]
I cannot really answer the question. Though my guess would be UTF-8.  
I cannot answer it with 100% certainty because it is the stream type the https://github.com/zuhd-org/easyloggingpp library uses. Though I think they just use UTF-8. Especially considering I can use `.dump()` just fine.

**Comment by BrainStone** [comment]
Great to see this dying due to inactivity.

**Comment by nlohmann** [comment]
Sorry, but this is a part-time project. And for this issue it’s not even clear what to do.

**Comment by BrainStone** [comment]
The simplest solution would be to just stream a string object into it. I mean wstreams need to be able to handle that themselves. And if they don't that's not your problem.

**Comment by nlohmann** [comment]
But in order to do this, the characters of type `char` have to be converted to `wchar`. And this conversion would also involve encoding: how would an UTF-8 string be recoded to a sequence of `wchar`?

**Comment by BrainStone** [comment]
No. You can stream `char`s just fine into a "`wstream`".
http://cpp.sh/2u7wa

**Comment by nlohmann** [comment]
Technically, anything can be converted to anything. But:

> But in order to do this, the characters of type `char` have to be converted to `wchar`. And this conversion would also involve encoding: how would an UTF-8 string be recoded to a sequence of `wchar`?

I do not think such a conversion should be part of the API of the library - if needed, user code should do it, because only this code knows what a sequence of `wchar` should mean in this setting.

**Comment by BrainStone** [comment]
Again, you don't need to convert anything. Normal `char` based strings are just fine. Because then the stream is obligated to do the correct conversion.
