### ISSUE TITLE
Missing v3.6.1 tag on master branch

### ISSUE THREAD

**Issue by robertoleksy** [nlohmann/json#1657]
Found by blacksmith@peerfreedom.org

**Comment by nlohmann** [comment]
You're right. Can you give me a hint how to set it after the fact?

**Comment by MartB** [comment]
Switch to master and issue the following:
```
git tag v3.6.1 1126c9c 
git push origin v3.6.1
```

**Comment by nlohmann** [comment]
This does not work unfortunately:

```sh
$ git tag v3.6.1 1126c9c

fatal: tag 'v3.6.1' already exists

$ git push origin v3.6.1

Everything up-to-date
```

**Comment by MartB** [comment]
Did you switch to master? 

If yes the tag should already be there

**Comment by nlohmann** [comment]
Alright. Thanks for reporting anyway!

**Comment by MartB** [comment]
Okay actually, your master branch differs from the develop branch which is not really a great idea, the tag points to a commit which is only available in the develop branch.

**Comment by nlohmann** [comment]
I am using the same release script for a year now, so I am confused that tags behave differently now.

**Comment by MartB** [comment]
This is not specific to 3.6.1 a few more i checked are also only in develop.

It entirely depends on how you want to tag, if you want the master branch to be used as a way for users to build releases based on tags, the current tagging wont work and one must use develop for it.

If you want the master branch to have the same tags, you need to tag a commit that is in both branches.
