### ISSUE TITLE
Errors/Warnings in VS 2019 when Including Header File

### ISSUE THREAD

**Issue by pinkpig3777** [nlohmann/json#1659]
- Describe what you want to achieve.
I want my program to work but as soon as I included the header file it gave errors.
My include line:
`#include "../nlohmann/json.hpp"`
All of the warnings:
https://gyazo.com/682adfd4655aad5540471ea9ca55ee4e

- Describe what you tried.
I don't know what to try.

- Describe which system (OS, compiler) you are using.
Windows 10 Pro, Visual Studio 2019, C++17

- Describe which version of the library you are using (release version, develop branch).
1. I cloned the repository directly from the main page (which appears to be the develop branch because that's what I'm viewing now and I didn't change it?) then took the json.hpp file. When this file didn't work, I went to the releases page and tried the json.hpp from the latest release (as of 7/1/2019). This one also gave errors when I ran my code:
https://gyazo.com/116815c8c06ca6e737741aa960b3eb68

**Comment by nlohmann** [comment]
The title of the issue speaks of errors, yet I can only see warnings in the images.

Furthermore, can you compile the test suite?

**Comment by blueberrynotblue** [comment]
me too. win10+vs2019
compiler says: error, found duplicate definition in this line `const std::uint8_t type = utf8d[byte];` of json.hpp

**Comment by nlohmann** [comment]
Can you please give a complete build output when building the unit tests?

**Comment by blueberrynotblue** [comment]
That error disappeared after I restarted  my pc somehow. Maybe it's ide bug or something.. great library btw.

**Comment by pinkpig3777** [comment]
Apologies for the late reply, I may take a few days before I will have time to work on this / respond fully. Life got busy.

**Comment by nlohmann** [comment]
@pinkpig3777 Any news on this?
