### ISSUE TITLE
Member detector is not portable

### ISSUE THREAD

**Issue by glenfe** [nlohmann/json#166]
Your `has_mapped_type` definition may be dependent on the C++ implementation providing `int` and `char` of different sizes. It is valid for an implementation to make them the same size.

You can remedy this by changing the return types to types which will be different sizes.

**Comment by nlohmann** [comment]
Doesn't the C++ standard guarantee `sizeof(char) == 1` and an `int` to have a width of at least 16 bits?

**Comment by glenfe** [comment]
Yes? A C++ implementation can make sizeof(char) == sizeof(int) == 1 where CHAR_BIT is 16.

**Comment by nlohmann** [comment]
I see... (Even though this would be really odd...)

**Comment by glenfe** [comment]
Here's one possible fix:
```
template<typename C> static char test(typename C::mapped_type*);
template<typename C> static char (&test(...))[2];
```

Also, consider changing the next line to:
```
static constexpr bool value = sizeof(test<T>(0)) == 1;
```

**Comment by nlohmann** [comment]
That's way more elegant. Thanks a lot for nitpicking on this. And Happy New Year!
