### ISSUE TITLE
Should I include single-header after my to_json and from_json custom functions declaration? Why not?

### ISSUE THREAD

**Issue by oktonion** [nlohmann/json#1663]
So I was going through the code and can not get how the library find user-defined functions for conversion (`to_json` and `from_json`)?

Let me explain with code.

simple example could look like this:

```cpp
#include <json.hpp>

namespace mynamespace
{
    class myclass{};

    void to_json(json&, const myclass&);
    void from_json(const json&, myclass&);
}

// if I put it there then I understand how it finds my to_json and from_json
// #include <json.hpp> 

void func()
{
    mynamespace::myclass val;
    json j = val;
    val = j.get<mynamespace::myclass>();
}
```

Before include of `<json.hpp>` there is no declaration of `mynamespace::to/from_json` so I expect any check in `<json.hpp>` like `has_custom_to_json` to fail. If not then how it works?

My guess is that all the magic is in  `is_detected_exact ` but I could not figure out how is it possible and what template trick is used?

P.S.: Sorry for multiple edits.

**Comment by nlohmann** [comment]
It's using ADL. The internals are from @theodelrieu - maybe they can share more insights.

**Comment by oktonion** [comment]
Any comments from @theodelrieu ?

**Comment by theodelrieu** [comment]
Hello, this is because of two-phase lookup, you can find a short but accurate overview [here](https://stackoverflow.com/a/7767726).

Basically, `val = j.get<mynamespace::myclass>();` is the point of instantiation, i.e. the lookup's second phase. At that point, your `from_json` method is visible to the compiler, whereas it wasn't in the first phase.

**Comment by oktonion** [comment]
@theodelrieu Is this behaviour required by C++ standard (which one?) or there could be some other approach used by compiler? As I see from RSDN and SO discussions many compilers fail to implement two-phase lookup properly, so I assume this library would not work in such case,

**Comment by jaredgrubb** [comment]
Two-phase lookup was always the expectation, even pre-C++11. Some compilers (eg, MSVC) didn't do it quite right but at this point, I would expect all the C++14 and later compilers to definitely have it down.
