### ISSUE TITLE
Can not translate map with integer key to dict string ? 

### ISSUE THREAD

**Issue by ruoshui1314** [nlohmann/json#1664]
It is correct to translate to dict string when the key of map is string.
But translate to an array when it is an integer.
`    std::map<int, int> c_map;

    c_map[1111] = 1;

    c_map[2333] = 111;

    nlohmann::json j_map = c_map;

    std::cout << j_map.dump() << std::endl;
`
result:

`
[[1111,1],[2333,111]]
`

How could I solve it?

**Comment by nlohmann** [comment]
To create a JSON object, the keys must be strings; this is required by the JSON specification.

![](https://www.json.org/img/object.png)

All other mappings are translated into a list of key/value pairs.

**Comment by ruoshui1314** [comment]
Got it

**Comment by bradallred** [comment]
I understand the JSON requirement that keys must be strings. My question is then, what is the most convenient way to translate an `unordered_map` with integer keys into a JSON object with keys that are the string representation of the integers? Must we write a custom `to_json` function for the map, or is there something I have overlooked that will pass map keys though `std::to_string()`?

**Comment by jaredgrubb** [comment]
That sounds like the right approach to me!

**Comment by bradallred** [comment]
Indeed this seems to work! :)

here is what I did for any future travelers that need the same:

```
void to_json(nlohmann::json& j, const Map& map)
{
	for (auto& [key, value] : map) {
		j.push_back({{std::to_string(key), value}});
	}
}
```

**Comment by bear24rw** [comment]
Is there any better way to do this nowadays? I had to make a new map type because I couldn't get `from_json` to override the default behavior. It is undesirable to have to introduce a new type just for json serialization reasons.

```cpp
class UnorderedMap : public std::unordered_map<int, double> {};
```
