### ISSUE TITLE
Binary (0x05) data type for BSON to JSON conversion

### ISSUE THREAD

**Issue by frankipl** [nlohmann/json#1668]
- Describe the feature in as much detail as possible.

Here is list of supported data types for conversion from BSON to JSON
[data types](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a89a4a1834883de313280a85266ae292a.html)
Would it be possible to add (0x05) binary data type to covert to JSON as Base64 encoded string ?

Best Regards
Marek

**Comment by nlohmann** [comment]
There is currently a PR #1662 working on binary data types in JSON. It's not using Base64 strings, but  vector of bytes. It should also fit BSON. What do you think?

**Comment by OmnipotentEntity** [comment]
To add, the pull request only supports serialization to the 0x00 binary subtype; however, serialization from any binary subtype ought to be supported.  Though this requires testing, and the PR is still in development.

While this does mean that the library isn't transparent under encoding and decoding, this was selected to simplify the implementation and kick the can down the road a bit.

**Comment by nlohmann** [comment]
The PR is the first step to actually support binary types for CBOR, MessagePack, UBJSON, and BSON. Full support of all BSON subtypes would be the next step, I'm afraid.

**Comment by frankipl** [comment]
HI
I understand. Thanks for looking into it.
Best,
Marek

**Comment by nlohmann** [comment]
Binary types were added with #1662.

**Comment by themightyoarfish** [comment]
If this is now supported, is the documentation outdated? In the doxygen for 3.9 it still says "still unsupported" for binary.

**Comment by nlohmann** [comment]
Good point - I shall have a look.

**Comment by nlohmann** [comment]
Fixed.
