### ISSUE TITLE
include.zip should contain meson.build

### ISSUE THREAD

**Issue by eli-schwartz** [nlohmann/json#1672]
In order to make it easier to use nlohmann_json everywhere, it would be helpful to provide a unified meson interface to the project. Currently, the choices are:
- acquire the entire repository, which is very large, and use the meson.build as a subproject
- use the meson wrapdb to acquire just the header includes. The meson wrapdb is out of date and the wrap itself sucks -- it uses its own meson.build which doesn't include the fix from #1463
It's probably fair to say that relying on some thirdparty provider will not be a great way to stay up to date.
- download include.zip, vendor it into the other project's repository, and manually add the directory to the include paths.

It would be nice to see include.zip more closely resemble the expected use of this repository, except without the large files that aren't needed when simply using it in another project. The simple solution would be to change these lines:
https://github.com/nlohmann/json/blob/cf8251eb544dcaba780b12a1da90afb791d31395/Makefile#L594-L599

And add `$(AMALGAMATED_FILE) meson.build` to the zipped files.

This should not have any practical effect other than to enable first-class meson wrap support. No one currently using include.zip should notice the very small extra meson.build file, and the additional single_include/ file should be negligible. (784K vs. 1.5M vs. 435M)
Sadly, meson does not have a way to check if a directory exists before declaring an include_directories on it...

**Comment by eli-schwartz** [comment]
@nlohmann,

Would you be interested in such a change? I could submit a PR to implement it if you'd like, but I would first like to know if it is something that you'd be willing to accept.

**Comment by nlohmann** [comment]
Yes, PR welcome!

**Comment by eli-schwartz** [comment]
Done!

**Comment by eli-schwartz** [comment]
@nlohmann I made a PR but it has been languishing. Could you evaluate it and perhaps merge it?

**Comment by eli-schwartz** [comment]
On the topic of versions available in Meson WrapDB, currently they only have nlohmann_json v3.3.0 and v3.4.0 available.

There is a PR for v3.5.0 but it's been open since March 1 and isn't going anywhere. So even if I wanted my json-using project to install an extra copy of /usr/include/nlohmann/json.hpp, I wouldn't be able to get a recent one.
