### ISSUE TITLE
Change from v2 to v3. Encoding with cp1252

### ISSUE THREAD

**Issue by MattiasEppler** [nlohmann/json#1680]
In my visual studio codepage 1252 is default. If I upgrade from v2 to v3 of nlohmann-json I get exceptions if i try to serialize words with the "ä ü ö". Is it possible to set the codepage in the library or do I have to change the encoding of my code files to utf8?

**Comment by nlohmann** [comment]
The library only supports UTF-8. See https://github.com/nlohmann/json#character-encoding.

**Comment by MattiasEppler** [comment]
Ok. So I have to change my encoding in visual studio to utf8. Or maybe do you know an other option?

**Comment by nlohmann** [comment]
No, this is the only option - I think. I am not a MSVC expert.

**Comment by MattiasEppler** [comment]
Hmm. Ok, But why is it working in v2.1.1?
My Problem: for localization I need CP1252 so its not possible to change my codefile to utf8.

**Comment by nlohmann** [comment]
It also did not work in 2.1.1, but there data may have been silently corrupted as UTF-8 was assumed, but not enforced. To get back to the old behavior, you can pass `json::error_handler_t::ignore` to the `dump` function.

**Comment by MattiasEppler** [comment]
Ok. This is working. But not really nice.
Hm. I don't know at the moment how to solve the problem correctly.
I'm not sure if I can change the project settings to utf-8 without open all sourcecodefiles, and if I get no other problems.

**Comment by MattiasEppler** [comment]
With boost::locale::conv::to_utf its possible to convert to utf8 from other encodings. Maybe a dump method wich accepts converting methods?

**Comment by nlohmann** [comment]
The problem should only occur with JSON strings that you have as literals in your actual code. Reading from files should not be affected by that.

**Comment by MattiasEppler** [comment]
Yes exactly

**Comment by Tomeamis** [comment]
@MattiasEppler Can't you just use u8 string literals? These should be available in VS2015 and up.

**Comment by nlohmann** [comment]
@MattiasEppler Do you need further assistance on this issue?

**Comment by MattiasEppler** [comment]
Sorry for my last response. Yes I need further assistance. 
If I use json::error_handler_t::ignore in the dump method the umlauts äöü are not available in the file.
Also if i use u8 string literals. For example u8"Hello Wörld", ends in file with "Hello Wrld"

**Comment by nlohmann** [comment]
Yes, this is the intended semantics of `json::error_handler_t::ignore`.

**Comment by MattiasEppler** [comment]
`To get back to the old behavior, you can pass json::error_handler_t::ignore to the dump function.`

But that's not the old behavior.

**Comment by nlohmann** [comment]
The old behavior was some kind of undefined, as we stated we only support UTF-8, but did not enforce it. Sorry for the inconvenience.

**Comment by MattiasEppler** [comment]
> Sorry for the inconvenience
Its ok. But what I do not understand, why is it not working with the u8 string literals.

**Comment by nlohmann** [comment]
In fact we do have `u8` literals in our unit test suite. Do you have a small example?

**Comment by MattiasEppler** [comment]
I save a u8 string literal in a normal string. In c++ 11 there is no std::u8string.
Or what do I miss?

`std::string value = u8"Hello Wörld";`

**Comment by MattiasEppler** [comment]
I created a new Visual Studio Solution (2019).
Added the code. The result:

Output:
`"Hello W├Ârld"`


The file is encoded with Western European (Windows) - Codepage 1252

**Comment by nlohmann** [comment]
I have no idea how MSVC does its encoding, but it seems wrong...

**Comment by MattiasEppler** [comment]
Ok the problem seems to be the default output 

If you just write:
`std::cout  << u8"Hello Wörld" << std::endl;`
You get the same wrong output:
`Hello W├Ârld`

Next try: I write the json and the normal string to a file. Here it works correct. 
So why its not working in my real project. I have to do additional tests.
```
#include <iostream>
#include <filesystem>
#include <fstream>

#include "json.hpp"

namespace fs = std::filesystem;
using json = nlohmann::json;

int main() {

	json j = json::parse(u8"\"Hello Wörld\"");
    std::cout << j << std::endl;

	fs::path pj = fs::current_path().append("test.json");
	std::ofstream(pj) << j << std::endl;


	std::cout  << u8"Hello Wörld" << std::endl;

	fs::path p = fs::current_path().append("test.txt");
	std::ofstream(p) << u8"Hello Wörld" << std::endl;
}
```

**Comment by jaredgrubb** [comment]
You probably need to tell the compiler to treat your .cpp file as a UTF-8 file. Maybe this helps? https://stackoverflow.com/questions/47690822/possible-to-force-cmake-msvc-to-use-utf-8-encoding-for-source-files-without-a-bo

**Comment by MattiasEppler** [comment]
It works. Thanks for you help. Also thanks to #jaredgrubb but it was not necessary to do that.
With the simple example i found my error.  
In my real (big) project I do not marked every string with utf8 and in my writetofile  function i still passed the parameter  json::error_handler_t::ignore.

So some unfortunate circumstances led to the result. 

Thanks again for the help.
