### ISSUE TITLE
Information: My project uses this awesome library

### ISSUE THREAD

**Issue by filipe-marques** [nlohmann/json#1691]
My project is called [bit](https://github.com/filipe-marques/bit) and use this awesome library. 
Everyone is welcome to contribute!
This project is licensed under GNU GPL v3 or later.
bit is a tool to build C/C++ projects and it is faster and simpler than GNU Make and CMake.
The build test is made in circleci and its passing.
Many thanks to Niels Lohmann and its many contributors.

**Comment by nlohmann** [comment]
Thanks for sharing! Good luck!
