### ISSUE TITLE
puzzled implicit conversions

### ISSUE THREAD

**Issue by studywithallofyou** [nlohmann/json#1692]
- evironment:

vs2017 c++17 windows7 64 develop branch

- code:
```cpp
long long lnum = 327221437;
nlohmann::json a;
a["num1"] = 327220625;
nlohmann::json b;
b["num2"] = 900000;
if (lnum - a["num1"] > b["num2"])
{
    cout << lnum << endl;
    cout << a["num1"] << endl;
    cout << b["num2"] << endl;
    cout << lnum - a["num1"] << endl;
    cout << lnum - a["num1"].get<long long>() << endl;
}
```

- result:
```
327221437
327220625
900000
327221292
812
```

could you tell me why `lnum - a["num1"]` is not same as `lnum - a["num1"].get<long long>()` but `cout << a["num1"] << endl;` is correct

**Comment by nickaein** [comment]
Note that [implicit conversions from JSON are discouraged](https://github.com/nlohmann/json#implicit-conversions), you should avoid `a["num1"]` and use `a["num1"].get<T>()` or `a["num1"].get_to(target_var)`  instead.

Based on the result of `lnum - a["num1"]`, I guess the implicit conversion to `int` gets picked up for `a["num1"]` which corrupts the original number.


In `cout << a["num1"] << endl;` however, there is no type deduction magic involved and no implicit conversion happens. The [`operator<<`](https://github.com/nlohmann/json/blob/develop/include/nlohmann/json.hpp#L6052) gets called which in turn calls [`dump_integer`](https://github.com/nlohmann/json/blob/6c7cde181cc5ff5db565e54a897261980af022f1/include/nlohmann/detail/output/serializer.hpp#L252) that basically dumps the integer value to a string buffer and can handle integers as big as `long long`.

**Comment by studywithallofyou** [comment]
> 
> 
> Note that [implicit conversions from JSON are discouraged](https://github.com/nlohmann/json#implicit-conversions), you should avoid `a["num1"]` and use `a["num1"].get<T>()` or `a["num1"].get_to(target_var)` instead.
> 
> Based on the result of `lnum - a["num1"]`, I guess the implicit conversion to `int` gets picked up for `a["num1"]` which corrupts the original number.
> 
> In `cout << a["num1"] << endl;` however, there is no type deduction magic involved and no implicit conversion happens. The [`operator<<`](https://github.com/nlohmann/json/blob/a015b78e81c859b88840cb0cd4001ce1fe5e7865/include/nlohmann/json.hpp#L6052) gets called which in turn calls [`dump_integer`](https://github.com/nlohmann/json/blob/6c7cde181cc5ff5db565e54a897261980af022f1/include/nlohmann/detail/output/serializer.hpp#L252) that basically dumps the integer value to a string buffer and can handle integers as big as `long long`.

Thanks very much.
I think if implicit conversions is uncertainty, it will be error and can not build success. Make user use get<T>() forcibly like Jsoncpp it is not allowed to write like `a["num1"]`. Must be `a["num1"].asInt64()` instead.

**Comment by nlohmann** [comment]
For what it's worth, I cannot even compile the line

```cpp
std::cout << lnum - a["num1"] << std::endl;
```

in Clang

```
main.cpp:18:27: Use of overloaded operator '-' is ambiguous (with operand types 'long long' and 'nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>, bool, long long, unsigned long long, double, std::allocator, adl_serializer>::value_type' (aka 'nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>, bool, long long, unsigned long long, double, std::allocator, adl_serializer>'))
```

**Comment by studywithallofyou** [comment]
> 
> 
> For what it's worth, I cannot even compile the line
> 
> ```c++
> std::cout << lnum - a["num1"] << std::endl;
> ```
> 
> in Clang
> 
> ```
> main.cpp:18:27: Use of overloaded operator '-' is ambiguous (with operand types 'long long' and 'nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>, bool, long long, unsigned long long, double, std::allocator, adl_serializer>::value_type' (aka 'nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>, bool, long long, unsigned long long, double, std::allocator, adl_serializer>'))
> ```

My project is in visual studio 2017 and build with vs defaul tool msbuild. I didn't test with clang.

Fail also with gcc/g++ when I test. It is only OK complile with vs.

**Comment by studywithallofyou** [comment]
How to do for the bug. Should I close it?

**Comment by igoloe** [comment]
Ain't that some kind of operator precedence problem in combination with implicit conversions?

Putting parenthesis around the minus operation in the stream operation makes the execution order not collide wirh stream operator overloads.
