### ISSUE TITLE
/Zc:__cplusplus leads to C2416

### ISSUE THREAD

**Issue by crusader-mike** [nlohmann/json#1695]
OS: Windows 7
Compiler: MSVC 2017 (15.9.11)

If project uses `/Zc:__cplusplus` json lib v3.7.0 fails to compile with this:
```
C2416: attribute 'deprecated' cannot be applied in this context
```

Looks like MSVC doesn't like this attribute applied to operator>> definition.

**Comment by jaredgrubb** [comment]
I don't see why there is any bug here. Can you explain why the deprecated attribute is not legal in that context?

**Comment by crusader-mike** [comment]
I assume it complains because `[[deprecated]]` attribute was applied to *definition*. According to C++17 draft I have (10.6.4.p2):

> The attribute may be applied to the declaration of a class, a typedef-name, a variable, a non-static data member, a function, a namespace, an enumeration, an enumerator, or a template specialization.

Looks like MS read it as "can't happen on a definition". I have no opinion about correctness of this position.

**Comment by jaredgrubb** [comment]
Yeh, that's a nuance that I can't make a call on myself. Dumb fix would be just to disable C2416 for this file :)

**Comment by crusader-mike** [comment]
Bad bot!

**Comment by t-b** [comment]
Not sure how the project rules here are with respect to selectively disabling warnings but why not propose a PR which uses pragma push/pop logic for MSVC to disable that warning for this piece of code? See https://stackoverflow.com/a/18463996 as a starting point.

**Comment by crusader-mike** [comment]
or I could simply patch this lib in my `vcpkg` instance and avoid dealing with PR/etc ;)

**Comment by mrstux** [comment]
I'm seeing this too.

**Comment by nlohmann** [comment]
This should be fixed on develop branch as it contains an updated version of Hedley. Can anyone try this?

**Comment by t-b** [comment]
I've added a PR which compiles with `/Zc:__cplusplus`. Let's see if that works now.

**Comment by t-b** [comment]
Fails in CI as well, see https://ci.appveyor.com/project/nlohmann/json/builds/28319126/job/qp8uvagt7i56g5bp.

@mrstux The best thing here is to fix the issue in https://github.com/nemequ/hedley, then incorporat the changes into the linked PR.

**Comment by t-b** [comment]
It's not about the definition. MSVC chokes on the friend. Using "__declspec(deprecated)" does not trigger the warning.

**Comment by t-b** [comment]
@nlohmann Please reopen.

**Comment by LanderlYoung** [comment]
any progress here? As far as I know, the easy way is to disable the attribute for windows by:

```c++
#if defined(__cplusplus) && (__cplusplus >= 201402L) && !defined(_MSC_VER)
```

BTW: MSVC sucks on this and the __cplusplus marco bug.

**Comment by t-b** [comment]
@LanderlYoung The upstream bug in hedley was fixed.

@nlohmann How do I upgrade to a newer hedley version?

**Comment by dota17** [comment]
@t-b 
I had compared the current version and the newest version of hedley.
There are not a lot of differences or special changes. So it maybe ok to update the source codes.

**Comment by nlohmann** [comment]
I upgraded Hedley to version 13 in https://github.com/nlohmann/json/tree/feature/update_hedley - can someone check if this fixes this issue?

**Comment by t-b** [comment]
@nlohmann Yeep, I've rebased https://github.com/nlohmann/json/pull/1958.

**Comment by kenr** [comment]
Is the 3.7.4/3.4.0 with this fix planned anytime soon? I use bitsery with std::variant and that requires /Zc:__cplusplus for MSVC to set the correct __cplusplus value for C++17.

**Comment by nlohmann** [comment]
The next release will be version 3.8.0. I'm not sure how much more time I will need until it is ready.

**Comment by kenr** [comment]
@nlohmann Is there anything I can help out with towards the 3.8.0 release?

**Comment by nlohmann** [comment]
Not really - but if you are using MSVC and want to help, you may want to have a look at https://github.com/nlohmann/json/pull/2117.
