### ISSUE TITLE
Is there support for automatic serialization/deserialization?

### ISSUE THREAD

**Issue by BigDaddyDeezel** [nlohmann/json#1696]
Is there any support for automatic serialization/deserialization? For example some sort of template magic that would just choose a string to use for the key name based on the property name directly, to skip the having to manually add an entry for each property by hand in the from_json() and to_json() methods?   I see 2 really helpful benefits there - 1) the obvious of course is less code needing to be written by the developers using this lib, but the more important is 2) if a property is added later to a structure, it wouldn't be accidentally forgotten to be serialized too

**Comment by nickaein** [comment]
Short answer: It's not currently possible.

Long answer: Such functionality needs Reflection support in C++ language which is not present yet. There are some [discussions and proposals](https://meetingcpp.com/blog/items/reflections-on-the-reflection-proposals.html) to add support for static reflection in C++ which is targeted for C++23 or later.

**Comment by lawmaestro** [comment]
> Short answer: It's not currently possible.
> 
> Long answer: Such functionality needs Reflection support in C++ language which is not present yet. There are some [discussions and proposals](https://meetingcpp.com/blog/items/reflections-on-the-reflection-proposals.html) to add support for static reflection in C++ which is targeted for C++23 or later.

This library provides struct reflection, perhaps this could be a route to achieving this?
https://github.com/cbeck88/visit_struct
