### ISSUE TITLE
Json support for Cmake version 2.8.12

### ISSUE THREAD

**Issue by theamatuer** [nlohmann/json#1699]
Is it possible to change the CmakeLists.txt file so that it can support Cmake version 2.8.12?  If not directly, then I'd appreciate it if someone can tell me what features of the library are enabled by 3.1 and I'll see if I can try to work without them

**Comment by nlohmann** [comment]
The easiest way would be if you changed the minimally required version in the CMake file yourself and see where your CMake version is complaining.

**Comment by theamatuer** [comment]
ok looks like Cmake 2.8 prevents you from setting the version number in the project declaration, which in turn prevents stops write_basic_package_version_file from working.  commenting out these sections seems to let cmake compile it thanks

**Comment by theamatuer** [comment]
okay I managed to figure out a workaround that let me run write_basic_package_version_file() using Cmake 2.8.12 , which basically has me using the VERSION parameter as well and changing SameMajorVersion to AnyNewerVersion.  Dunno if that breaks anything but for now it's compiling and running my code so it probably works

these are the specific parts I changed
`cmake_minimum_required(VERSION 2.8)
if (POLICY CMP0048)
  cmake_policy(SET CMP0048 NEW)
endif (POLICY CMP0048)

##
## PROJECT
## name and version
##


project(nlohmann_json)
set (NLOHMANN_JSON_VERSION 3.6.1)`

`##
## INSTALL
## install header files, generate and install cmake config files for find_package()
##
include(CMakePackageConfigHelpers)
write_basic_package_version_file(
    ${NLOHMANN_JSON_CMAKE_VERSION_CONFIG_FILE} VERSION ${NLOHMANN_JSON_VERSION} COMPATIBILITY AnyNewerVersion
)`

Gonna close it then
