### ISSUE TITLE
Where is json::parse now?

### ISSUE THREAD

**Issue by pmahend1** [nlohmann/json#1702]
- Describe what you want to achieve.
Trying to parse a string into json and then extract values and create object
![image](https://user-images.githubusercontent.com/21352870/62784572-c84a2180-ba8c-11e9-8106-c8c0a32b9a48.png)

> class "nlohmann::basic_json<std::map, std::vector, std::string, bool, int64_t, uint64_t, double, std::allocator, nlohmann::adl_serializer>" has no member "parse"

Getting error class `"nlohmann::basic_json<std::map, std::vector, std::string, bool, int64_t, uint64_t, double, std::allocator, nlohmann::adl_serializer>" has no member "parse"`
- Describe what you tried.

```cpp
#include <iomanip>
#include <fstream>
#include <sstream>

#include <iostream>
#include <nlohmann/json.hpp>

using json = nlohmann::json;
using namespace std;
.
.
.
int main(){
	auto j3 = json::parse("{ \"happy\": true, \"pi\": 3.141 }");
}
```

- Describe which system (OS, compiler) you are using.
Windows 10
- Describe which version of the library you are using (release version, develop branch).

## VCPKG
```
nlohmann-json:x64-windows                          3.7.0            JSON for Modern C++
nlohmann-json:x64-windows-static                   3.7.0            JSON for Modern C++
nlohmann-json:x86-windows                          3.7.0            JSON for Modern C++
nlohmann-json:x86-windows-static                   3.7.0            JSON for Modern C++
```

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by pmahend1** [comment]
- Getting error `parse` method not found
- Installed from vcpkg : `.\vcpkg.exe insatll nlohmann-json:x64-windows nlohmann-json:x64-windows-static nlohmann-json:x86-windows nlohmann-json:x86-windows-static ` version3.7
- Expected behavior : should not get error parse method not found
- Compiler Visual studio 16.2 : 14.2 (seems supported)
- will run tests and get back to you

**Comment by nlohmann** [comment]
- What is the exact error message?
- Can you use the JSON library apart from the parse function? For instance, can you compile a program that does nothing but `json j;`?

**Comment by pmahend1** [comment]
- Exact error 

> nlohmann::basic_json<std::map, std::vector, std::string, bool, int64_t, uint64_t, double, std::allocator, nlohmann::adl_serializer>" has no member "parse

-  Yes, the below code is compiling and running fine.
```cpp
#include <iostream>

#include "nlohmann/json.hpp"
using json = nlohmann::json;
using namespace std;
int main()
{
	json j;
	return 0;
}
```

**Comment by nlohmann** [comment]
Strange...

Can you please try:

```cpp
std::string s = "{ \"happy\": true, \"pi\": 3.141 }";
json j = json::parse(s);
```

?

**Comment by ERap320** [comment]
I have the same exact behaviour in Visual Studio 2019, using the single include file.
The strangest thing is that everything seems to work correctly when I compile and run the program. Intellisense just refuses to find json::parse().

**Comment by nlohmann** [comment]
Oh, @pmahend1 - does the code compile or is it just an IntelliSense error?

**Comment by pmahend1** [comment]
> 
> 
> Strange...
> 
> Can you please try:
> 
> ```c++
> std::string s = "{ \"happy\": true, \"pi\": 3.141 }";
> json j = json::parse(s);
> ```
> 
> ?

This fails :Compilation  error

Running tests --> I am getting `Test not available without configuration.  (Missing "-C <config>"?)` error  `  i.e `PS C:\workspace\json\build> ctest --output-on-failure`

**Comment by nlohmann** [comment]
What is the exact compilation error message?

**Comment by pmahend1** [comment]
Please ignore. This is intellisense issue. Seems something went wrong with latest visual studio 16.2.1
If I filter out Intellisense errors , this compiles and runs as well.

**Comment by nlohmann** [comment]
Thanks!

**Comment by ERap320** [comment]
> 
> 
> Please ignore. This is intellisense issue. Seems something went wrong with latest visual studio 16.2.1
> If I filter out Intellisense errors , this compiles and runs as well.

So the only solution is to wait for a new build of VS and keep editor errors while developing?

**Comment by nlohmann** [comment]
I would not know any other way.

**Comment by bhardwajs** [comment]
@ERap320 - You might also want to report to Visual Studio at https://developercommunity.visualstudio.com/spaces/62/index.html.

**Comment by pmahend1** [comment]
I have reported on [developer community](https://developercommunity.visualstudio.com/content/problem/689128/intellisense-doesnt-work-properly-c-after-upgrade.html)

**Comment by 8infy** [comment]
Yup, still getting this error on visual studio 2019 16.2.3.

**Comment by nlohmann** [comment]
Maybe fixed with https://github.com/nlohmann/json/pull/1799.

**Comment by xarthurx** [comment]
@nlohmann  Not really.
I updated to the newest 3.7.3, still got this error. Though it doesn't affect the compilation, but it is still there FYI.

**Comment by Stefmachine** [comment]
Turns out the error will be fixed in VS 2019 16.4.

Right now it's only available as preview version. You can download and install it from [here](https://visualstudio.microsoft.com/vs/preview/). Although I wouldn't use it for serious development.

If you need proof:
![image](https://user-images.githubusercontent.com/32845418/69482574-2eb04100-0deb-11ea-843d-43357024feca.png)
On the left is 16.3 and on the right is 16.4.

So to problem is really caused by VS and not the library itself.

The problem was previously reported on the [developper comunity](https://developercommunity.visualstudio.com/content/problem/678883/c-intellisense-on-vs2019-reports-incorect-errors-t.html)

**Comment by nlohmann** [comment]
@Stefmachine Thanks a lot for checking!

**Comment by Niek-Okido** [comment]
currently using 16.6.3 version of visual studio, and i get the same issue.
i can paste wat for error i get etc. but it is exact the same 

gr

**Comment by nlohmann** [comment]
See https://github.com/nlohmann/json/issues/1702#issuecomment-519942374
