### ISSUE TITLE
Installing on Ubuntu 16.04

### ISSUE THREAD

**Issue by wiggitamoo** [nlohmann/json#1703]
- Describe what you want to achieve.

I would like to install the nlohmann_json v3.7.0 and use it in a c++ project.

- Describe what you tried.
1. Download the zip file to my Ubuntu 16.04 machine.
1. Unzip the package
1. mkdir build
1. cd build
1. cmake ..
1. make
1. make install

In my CMakeLists.txt i added:
```
find_package(nlohmann_json 3.7.0 REQUIRED)
target_link_libraries(configuration PRIVATE nlohmann_json::nlohmann_json)
```

- Describe which system (OS, compiler) you are using.

Ubuntu 16.04
cmake version 3.5.2
cmake_minimum_required(VERSION 3.10)
set(CMAKE_CXX_STANDARD 17)

- Describe which version of the library you are using (release version, develop branch).

nlohmann_json v3.7.0

- Describe the problem 

When I try to build I get the following error:

```
  Could not find a configuration file for package "nlohmann_json" that is
  compatible with requested version "3.7.0".

  The following configuration files were considered but not accepted:

    /usr/local/lib/cmake/nlohmann_json/nlohmann_jsonConfig.cmake, version: 3.7.0 (64bit)
```

**Comment by AustinJia** [comment]
I have the same issue.
Looks like ubuntu 16.04 xenial can't install the nlohmann package
`sudo apt-get install nlohmann-json-dev`
always shows to me, can't locate the package

**Comment by danem** [comment]
@AustinJia apt packages an old version of json (2.1.1-1.1) that doesn't seem to support this method.

**Comment by olegskip** [comment]
`nlohmann-json3-dev` helped me

**Comment by anancds** [comment]
> `sudo apt-get install nlohmann-json3-dev` helped me

i get an error:
`
Unable to locate package nlohmann-json3-dev
`

**Comment by Sheridan** [comment]
> `Unable to locate package nlohmann-json3-dev`

repository ppa:team-xbmc/ppa

**Comment by mstanton-impinj** [comment]
sudo apt-get install nlohmann-json3-dev worked for Ubuntu 20.04

**Comment by zarvis56** [comment]
use `vcpkg install  nlohmann-json`
