### ISSUE TITLE
IntelliSense goes crazy on VS2019

### ISSUE THREAD

**Issue by GkqqNkKC** [nlohmann/json#1704]
Issue: IntelliSense does not work anymore after including the main header

Steps to reproduce: just download the header / headers, and `#include <nlohmann/json.hpp>` in a VC2019 project

Details: 
![image](https://user-images.githubusercontent.com/35461917/62791729-70d0a380-bad6-11e9-8f56-dac3e194162c.png)

No settings were made regardless how compiler works.

The following operations are going forever:
![image](https://user-images.githubusercontent.com/35461917/62791877-c4db8800-bad6-11e9-9254-6a0c692449ff.png)

**Comment by bhardwajs** [comment]
This might be the same issues as #1702 . Worth reporting to VS at https://developercommunity.visualstudio.com/spaces/62/index.html

Also, which version of VS is it? I can try to repro.

**Comment by GkqqNkKC** [comment]
16.2.1
Like on the references issue, it does compile. I'm gonna try the filtering.

**Comment by nlohmann** [comment]
I am afraid there is little we can do if IntelliSense has an issue with the code...

**Comment by GkqqNkKC** [comment]
I understand. Thx for looking over my issue.
