### ISSUE TITLE
find an object that matches the search criteria

### ISSUE THREAD

**Issue by racdhawan** [nlohmann/json#1705]
- Describe what you want to achieve.
Trying to find object(s) that matches the search criteria
- Describe what you tried.
Do I need to write a search on each key value and loop over all the objects in the vector to find the match? That seems too expensive. Any suggestions? I should be able to search on all the keys and return the matching objects.
```C++
class person {
	public:
		std::string name;
		std::string address;
		int age;
	};

	void to_json(json& j, const person& p) {
		j = json{ {"name", p.name}, {"address", p.address}, {"age", p.age} };
	}

	void from_json(const json& j, person& p) {
		if (j.contains("name")) p.name = j.at("name").get<std::string>();
		if (j.contains("address")) p.address = j.at("address").get<std::string>();
		if (j.contains("age")) p.age = j.at("age").get<int>();
	
	}

int main()
{
	       std::vector<ns::person> persons;
		// convert to JSON: copy each value into the JSON object
		ifstream inputFile("input/person.json");
		json j;
		ns::person person;
		try {
			j = json::parse(inputFile, NULL, true);// false to get rid of error
			if (j.is_discarded()) {
				cout << "error";
			}
		}
		catch (std::exception& e)
		{
			std::cerr << e.what() << std::endl;
		}
		for (int i = 0; i < j.size(); i++)
		{
			std::cout << j.at(i)<<"\n";
			person = j.at(i);
			persons.push_back(person);
		}
//ask user for search criteria
// loop over all the objects and return the match?
}
```

- Describe which system (OS, compiler) you are using.

- Describe which version of the library you are using (release version, develop branch).

**Comment by nlohmann** [comment]
The [`items`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_afe3e137ace692efa08590d8df40f58dd.html#afe3e137ace692efa08590d8df40f58dd) function may help.

**Comment by racdhawan** [comment]
I am not sure how to map the std::vector(thats what i am using) to nlohmann ::json and use the items function on it.

**Comment by racdhawan** [comment]
nevermind. I figured looping over each json object in the  vector of objects and doing a search on each key using items.
