### ISSUE TITLE
Crash on trying to deserialize json string on 3ds homebrew

### ISSUE THREAD

**Issue by KironDevCoder** [nlohmann/json#1707]
- What is the issue you have?
When I try deserializing a string to json it crashes the app.

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?
`json data = "{\"a\": [\"1\", 2], \"b\": true}"_json;`

- What is the expected behavior?
Deserializing json string

- And what is the actual behavior instead?
An crash

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?
I think `arm-none-eabi-g++` or `gnu++17,` I use devkitARM. The operating system is 3DS for the app and Windows 10 Pro for development

- Did you use a released version of the library or the version from the `develop` branch?
A released version

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?
I don't have either `cmake` or `ctest`.

What might help is the part of the `make` log I think is about this: https://hastebin.com/amomibogic.rb

**Comment by nlohmann** [comment]
What is the exact error message? Do you have a stack trace?

**Comment by KironDevCoder** [comment]
nope, just crashes the app and returns to the homebrew menu

**Comment by KironDevCoder** [comment]
https://hastebin.com/amomibogic.rb is the closest to an error message / stack trace

**Comment by KironDevCoder** [comment]
nvm, it got fixed, idk how
