### ISSUE TITLE
name typo in the "spack package management" section of README.md

### ISSUE THREAD

**Issue by ejcjason** [nlohmann/json#1720]
- What is the issue you have?
In README.md, the package name in `spack` is supposed to be `nlohmann-json` instead of `nlohmann_json`. Please see this reference: https://spack.readthedocs.io/en/latest/package_list.html#nlohmann-json

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?
View https://github.com/nlohmann/json#package-managers.

Not a big deal. Thanks a lot for all of your contributions!

**Comment by nlohmann** [comment]
Thanks! Fixed in bf4156056b21322488a788ecda5a0f78bb707086.

**Comment by nlohmann** [comment]
* * *

### 🔖 Release item

This issue/PR will be part of the next release of the library. This template helps preparing the release notes.

#### Type

- [ ] ✨ New Feature
- [x] 🐛 Bug Fix
- [ ] ⚡️ Improvement
- [ ] 🔨 Further Change
- [ ] 🔥 Deprecated function

#### Description

- Fixed name of the spack package.

* * *

**Comment by ax3l** [comment]
Sorry, that's my fault.
