### ISSUE TITLE
please provide an API to read JSON from file directly.

### ISSUE THREAD

**Issue by coolsnake** [nlohmann/json#1725]
- Describe the feature in as much detail as possible.
In most case, I have a config file with json format data in it. I want to load this config parameter directly.

- Include sample usage where appropriate.
For example, I have a mysql client that will read the configuration of MySQL ip address, port,  user name and password. All these infos are provided in a json file.

**Comment by nlohmann** [comment]
This can be easily done with the public API:

```cpp
json from_file(const std::string& filename)
{
    std::ifstream s(filename);
    return json::parse(s);
}
```

**Comment by nlohmann** [comment]
(That said, I do not think that such a function needs to be added to the library.)

**Comment by coolsnake** [comment]
thanks
