### ISSUE TITLE
How to create JSON Object from my Structures of Data and Json File from that Object

### ISSUE THREAD

**Issue by GaneshJeevaa** [nlohmann/json#1726]
I have structures as follows,

```cpp
  struct Lel1
{
  string Title;
  struct Lel2 ns;
};
  struct Lel2
{
  string name;
};
```

I need to export tho one into json file.

can anyone help?

__

C.G

**Comment by nlohmann** [comment]
Please check https://github.com/nlohmann/json#arbitrary-types-conversions - there, it is described how to translate arbitrary types to and from JSON.
