### ISSUE TITLE
json::contains usage to find a path

### ISSUE THREAD

**Issue by devhandle** [nlohmann/json#1727]
- Describe what you want to achieve.

I want to test whether a path exists in a json file. For example, "_/root/settings/logging_".

- Describe what you've tried.

```cpp
auto jPtr = json::json_pointer("/root/settings/logging"_json_pointer);
auto exists1 = jsonfile.contains(jPtr);

auto exists2 = jsonfile.contains(json::json_pointer("/root/settings/logging"_json_pointer));

```
`exists1` is false and `exists2` is true.

I expected both of these to be true. Is this a bug or is this expected behaviour?

**UPDATE**: There are two `contains` functions. One which takes an rvalue reference to a `KeyT` and one which takes a reference to a json_pointer.  Both do different things. This seems inconsistent to me. If I `std::move` jPtr it works but I don't want to move the pointer. 

- Describe which system (OS, compiler) you are using.

g++ (Ubuntu 8.3.0-6ubuntu1~18.10.1) 8.3.0

- Describe which version of the library you are using (release version, develop branch).

v3.7.0

**Comment by pboettch** [comment]
> auto jPtr = json::json_pointer("/root/settings/logging"_json_pointer);

There is maybe one `_json_pointer` too much here?

Isn't it either

    auto jPtr = json::json_pointer("/root/settings/logging");

or 

    auto jPtr = "/root/settings/logging"_json_pointer;

What do you see when printing your jPtr?

**Comment by devhandle** [comment]
Thanks for replying but I've tested your suggestions and neither of them work.

**Comment by devhandle** [comment]
`at` seems to behave correctly. I haven't tested it fully yet but the code below works (outputs`Exists`). I'd prefer to use `contains` though as it isn't mean't to throw an exception.

        try
        {
            json::json_pointer p {"/root/settings/logging"};
            jsonfile.at(p);
            std::cout << "Exists" << std::endl;
        }
        catch (const json::exception &e)
        {
            std::cout << "Doesn't exist" << std::endl;
        }

**Comment by nlohmann** [comment]
Indeed there is a double invocation of the JSON Pointer constructor if you call

```cpp
json::json_pointer("/root/settings/logging"_json_pointer)
```

For your example, this code works:

```cpp
#include "json.hpp"
#include <iostream>

using json = nlohmann::json;

int main()
{
    json j;
    j["root"]["settings"]["logging"] = true;
    
    std::cout << std::boolalpha
        << j.contains("/root/settings/logging"_json_pointer) << '\n'
        << j.contains("/no/value/here"_json_pointer)
        << std::endl;
}
```

**Comment by devhandle** [comment]
Thanks but my question was about passing an instance of `json::json_pointer` and not hard coded paths.

It is related to the `contains` function and it's different implementations for const and non-const `json_pointers`.

```
auto jp1 = "/root/settings/logging"_json_pointer;
auto jp2 = json::json_pointer{"/root/settings/logging"};

std::cout << std::boolalpha << j.contains(jptr1);
std::cout << std::boolalpha << j.contains(jptr2);
```

....both return `false`.  But if I make them both const, they return `true`! 


```
const auto jp1 = "/root/settings/logging"_json_pointer;
const auto jp2 = json::json_pointer{"/root/settings/logging"};

std::cout << std::boolalpha << j.contains(jptr1);
std::cout << std::boolalpha << j.contains(jptr2);
```

Is this a bug because this really caught me out.

**Comment by nlohmann** [comment]
I see.

Calling `contains` with a non-const `json_pointer` calls

```cpp
template<typename KeyT, typename std::enable_if<
             not std::is_same<KeyT, json_pointer>::value, int>::type = 0>
bool contains(KeyT && key) const
{
    return is_object() and m_value.object->find(std::forward<KeyT>(key)) != m_value.object->end();
}
```

which is wrong, whereas calling it with a `const json_pointer` calls

```cpp
bool contains(const json_pointer& ptr) const
{
    return ptr.contains(this);
}
```

which is correct.

I am puzzled. Any ideas?

**Comment by devhandle** [comment]
I'm not familiar enough with the codebase to suggest a fix but I added a `contains` function which accepts a non const `json_pointer` and it fixes the issue:

```c++
bool contains(json_pointer& ptr) const
{
    return ptr.contains(this);
}
```
I believe the function below is being called incorrectly by the non-const call. Could you explain to me what the `std::enable_if` is mean't to achieve? Is it to prevent calls passing a `json_pointer` parameter because it does not do this. Is this a bug? 

```c++
template<typename KeyT, typename std::enable_if<
             not std::is_same<KeyT, json_pointer>::value, int>::type = 0>
bool contains(KeyT && key) const
{
    return is_object() and m_value.object->find(std::forward<KeyT>(key)) != m_value.object->end();
}
```

**Comment by tete17** [comment]
Hey @devhandle I have explained why this wasn't working in the pull requests but if you need more explanation from my side, don't doubt into dropping me a message :)

**Comment by devhandle** [comment]
Thanks @tete17! 

I've tested your change and it fixes my issue.  Also, thanks for the explanation - much appreciated.
