### ISSUE TITLE
Question about exceptions

### ISSUE THREAD

**Issue by dummy0stud** [nlohmann/json#173]
There is any possible way of using this lib without exceptions, or it always throws?

It would be nice something like:
```
json j =R"({,})"_json;
std::cout << j.is_parsed_sucess();
```

**Comment by nlohmann** [comment]
In case of a parse error, the code will always throw an exception. So far, I do not plan to make exceptions optional.

For your use case, you may catch `std::invalid_argument` and create a wrapper function `is_parsed_success` yourself.

**Comment by berkus** [comment]
`std::invalid_argument` does not work.

On a related note, I don't see a single word about JSON parsing errors in the documentation.

**Comment by gregmarr** [comment]
FYI, it is now possible to disable exceptions in the library.

**Comment by nlohmann** [comment]
@berkus The last released version works with `std::invalid_argument`. The `develop` branch contains an unreleased version with user-defined exceptions. There, the parser throws `json::parse_error`.
