### ISSUE TITLE
JsonObject.dump() 

### ISSUE THREAD

**Issue by mohammadrasekh68** [nlohmann/json#1732]
Hi
the problem is when we use dump() method, when it return the string literal from the JsonObject, JsonObject will be cleaned and initialized with random values!
so if i do something like this:
`std::cout<<JsonObject.dump()<<endl;
//printed :{"A":{"B":"7+NNf&&8Nf!","C":"12345678913456"}} 
std::cout<<JsonObject.dump()<<endl;
//printed : nothing or some random characters`

**Comment by gregmarr** [comment]
That seems very unlikely unless `JsonObject` is a reference to an object that is destroyed at the end of the first statement.  Do you have a full sample that demonstrates this issue?

**Comment by mohammadrasekh68** [comment]
`Json postData;
        postData = RequestTaskDescriptionJsonNode->getJsonNode(); //RequestTaskDescriptionJsonNode is a unique_ptr,returns a JsonObject
	// setup the POST data
	cout<<"post data Check: " <<postData.dump() .c_str());  // this one works fine
	curl_easy_setopt( ctx , CURLOPT_POSTFIELDS , postData.dump() .c_str()); // here data packet is empty`
but this behavior does not happen always,  I'm not facing it right now, even the code is the same!

**Comment by nlohmann** [comment]
I would need to see more code to be able to assess this. Alternatively, can you run your code with Address Sanitizer to make sure the string you are parsing is valid?

**Comment by kickunderscore** [comment]
I have often seen such problems in connection with macros. Unlike the function call (or operator call) in the first example, the lifetime of the std::string returned temporarily from `dump()` may not be guaranteed if a macro implementation contains multiple C++ statements.

@mohammadrasekh68: Can you please clarify whether `curl_easy_setopt` is a regular function or a macro?

**Comment by mohammadrasekh68** [comment]
@nlohmann  unfortunately I cant run the program with Sanitizer
@kickunderscore
but curl_easy_setopy is not a function but a marco
and one more thing is that we are using Dlt logging mechanism which is also a marco not a simple function.  

complete code script is: 
`std::unique_ptr <CreateRequestJsonNode> RequestTaskDescriptionJsonNode=make_unique<CreateRequestJsonNode>();
std::unique_ptr <struct t_obu_task_description_request> request =std::make_unique<struct t_obu_task_description_request>();
	if(!m_vin.empty())
	{
		request->vin = m_vin;
	}

	if(!m_serialNumber.empty())
	{
		request->serial_number = m_serialNumber;
	}

	if(!m_password.empty())
	{
		request->obu_password = m_password;
	}

	if( RequestTaskDescriptionJsonNode->init(request))
	{
		fclose(localFile);
		DLTLOG(DLT_LOG_ERROR,"error on create task description request");
		return EXIT_DATA_ERROR;
	}
	postData = RequestTaskDescriptionJsonNode->getJsonNode();
	DLTLOG(DLT_LOG_INFO,"post data Check: " ,postData .c_str());
	curl_easy_setopt( ctx , CURLOPT_POSTFIELDS , postData .c_str());`
