### ISSUE TITLE
No-throw json::value()

### ISSUE THREAD

**Issue by PerMalmberg** [nlohmann/json#1733]
Currently, it's a must to write code like this to prevent exceptions in the case optional values are omitted from the underlying data:

```cpp
auto id = cfg.contains("device_id") ? cfg.value("device_id", "") : "";
```

A more streamlined version would be like this, specifying no-throw, similar to `json::parse`:

```cpp
auto id = cfg.value("device_id", "", false);
```

Allowing `value()` to take an `allow_exception`, same as `json::parse` would reduce boiler place code and also meet user expectations; we're providing a default value, but instead of returning that, `value()` throws an exception.

Thoughts?

**Comment by jaredgrubb** [comment]
This already works, unless you're unsure if `cfg` is a dictionary. I don't think having .value return a default when cfg is actually a number or null is a good idea, personally.

FWIW, your code should be something like `auto id = cfg.is_object() ? cfg.value("device_id", "") : "";`, which will be far more efficient and have the same behavior.

**Comment by PerMalmberg** [comment]
That is actually exactly the case.

When the JSON-file (i.e. the configuration) is empty, `json::parse(.... false)` allows to "load" an empty string, where upon I want to read default values for everything. Personally, I think this addition would bring a little symmetry to the API; if `parse` can load an empty string, shouldn't `value` then be able to return the default value from that same (empty) data?

**Comment by nlohmann** [comment]
What would your code do if the proposed default value does not match the existing value:

```cpp
json j;
j["device_id"] = 10;
auto id = j.contains("device_id") ? j.value("device_id", "") : "";
```

(This currently throws: `[json.exception.type_error.302] type must be string, but is number`).

**Comment by PerMalmberg** [comment]
I might be missing your point, but I'd consider that a programmer error; i.e. mixing up types. I'd expect it to return the provided default value as that is what I'm asking for.

Had I wanted an integer as a default value, then I'd call value with an int as a default value.

**Comment by nlohmann** [comment]
The thing is: you do not know which value is actually stored in the object. You may have expected a string and provided `""` as default if the key was not found. But when a number was stored instead, only an exception makes sense. What I mean: by defining away the situation where you call `value()` on a JSON value other than an object, you do not get rid of all the exceptions.

**Comment by PerMalmberg** [comment]
You're right in that I don't know what value has actually been stored, but I'm 100% sure what the application expects, which is exactly why the ability to provide a default value without the possibility of an exceptions would be such a good thing.

If the application expects a string but a number has been stored, then there's a mismatch between expected and actual data. This could for example happen when a user manually edits a JSON configuration and enters `{ "key": "1" }` instead of `{ "key": 1 }` or I myself assign a variable to the wrong key at run time.

What is the correct behavior in this case? I'd say it is up to the application to decide; either 1) throw an exception (as it currently does), catch it and handle it by using a default value, or 2) catch the exception, log and exit.

In my case - an embedded system with no screen or keyboard - using default values is always the preferred option instead of entering a boot-loop due to bad configuration.

If this still doesn't makes sense to you, feel free to close this issue, I'll fallback to writing a wrapper for reading values.

**Comment by nlohmann** [comment]
My point is that even your "no-throw" `value()` could still throw, and I agree with https://github.com/nlohmann/json/issues/1733#issuecomment-526949808 that in the end it would be clearer to write

```cpp
auto id = cfg.is_object() ? cfg.value("device_id", "") : "";
```

as this makes it explicit that you are OK with `cfg` not being an object.
