### ISSUE TITLE
Allow The Colon Key-Value Delimiter To Have A Space Before It [@ READ ONLY]

### ISSUE THREAD

**Issue by ClaudiuHKS** [nlohmann/json#1735]
Example of current use ->

Only `{ "Name": "Michael", "Age": 24 }`

Example of use after this feature request ->

Either `{ "Name": "Michael", "Age": 24 }` or `{ "Name" : "Michael", "Age" : 24 }`

Note! This feature request should only affect the functions that read the trees. Those functions that write should remain the same.

**Comment by nlohmann** [comment]
This is already supported by the library:

```cpp
#include "json.hpp"
#include <iostream>

using json = nlohmann::json;

int main()
{
    std::string s1 = R"( { "Name": "Michael", "Age": 24 } )";
    auto j1 = json::parse(s1);

    std::string s2 = R"( { "Name" : "Michael", "Age" : 24 } )";
    auto j2 = json::parse(s2);
    
    std::cout << j1 << '\n' << j2 << std::endl;
}
```

Output:

```
{"Age":24,"Name":"Michael"}
{"Age":24,"Name":"Michael"}
```

Did I miss anything?

**Comment by ClaudiuHKS** [comment]
Thanks for your proper answers, looks like my fault, closing now!
Have a good day though!
