### ISSUE TITLE
how to know the parse is error

### ISSUE THREAD

**Issue by alongL** [nlohmann/json#1737]
```
string str = ""; //give a empty string
auto j3 = json::parse(str); //exceptin occours

auto j4 = json::parse(str, nullptr, false); //no exception
j4["action"];  //exception  occours
```

How to know the parse is right?

**Comment by nlohmann** [comment]
When you switch off exceptions as you did when parsing to `j4`, the result type will be `discarded` in case of a parse error (see documentation of [`parse`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a265a473e939184aa42655c9ccdf34e58.html#a265a473e939184aa42655c9ccdf34e58)). You can check this with `j4.is_discarded()` which should be true.

**Comment by alongL** [comment]
ok. Problem Solved
