### ISSUE TITLE
Serialize vector of glm:vec2

### ISSUE THREAD

**Issue by zalavariandris** [nlohmann/json#1739]
I'd like to serialize a vector of glm:vec2;

I have tried to follow the instructions in the readme and implemented from and to json methods like so:

```
namespace glm {
    void to_json(json& j, const glm::vec2& P) {
        j = { { "x", P.x }, { "y", P.y } };
    };

    void from_json(const json& j, glm::vec2& P) {
        P.x = j.at("x").get<double>();
        P.y = j.at("y").get<double>();
    }
}

json j;
std::vector<glm::vec2> points{ glm::vec2( 70, -140 ), glm::vec2(30, -30), glm::vec2(20, 125) };
j["points"] = points;
```

this little snippet wont compile and I got the following errors:
```
'glm::begin': ambiguous call to overloaded function
'glm::end': ambiguous call to overloaded function
 std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>::create': no matching overloaded function found
```

the funny thing is that when I replace glm::vec2 with a simple Point struct, it compiles, and works as expected.
I'm on windows, using Visual Studio, using the single header from the master branch version3.7.0

**Comment by nlohmann** [comment]
Strange. This code compiles with Xcode:

```cpp
#include "json.hpp"
#include <iostream>
#include "/usr/local/Cellar/glm/0.9.9.5/include/glm/glm.hpp"

using json = nlohmann::json;

namespace glm {
    void to_json(json& j, const glm::vec2& P) {
        j = { { "x", P.x }, { "y", P.y } };
    };
    
    void from_json(const json& j, glm::vec2& P) {
        P.x = j.at("x").get<double>();
        P.y = j.at("y").get<double>();
    }
}

int main()
{
    json j;
    std::vector<glm::vec2> points{ glm::vec2( 70, -140 ), glm::vec2(30, -30), glm::vec2(20, 125) };
    j["points"] = points;
    
    std::cout << j << std::endl;
}
```

Output:

```
{"points":[{"x":70.0,"y":-140.0},{"x":30.0,"y":-30.0},{"x":20.0,"y":125.0}]}
```

Can you try this minimal example?

**Comment by h4k1m0u** [comment]
Any idea why `to_json` and `from_json` have to be inside the glm namespace?
I'm asking because I wanted both functions to be templates (so I can use them with another Point struct with similar x/y/z fields), but I had the following summarized error:

```
error: no matching function for call to ‘nlohmann::basic_json<>::get<glm::vec3>()’
template argument deduction/substitution failed
```

**Update:** Nevermind, I just saw in the README that the two function must be in the same namespace as glm::vec3 type.

**Comment by falbrechtskirchinger** [comment]
@h4k1m0u You can also use [this alternate method](https://json.nlohmann.me/features/arbitrary_types/#how-do-i-convert-third-party-types) for third-party types which avoids placing the functions into the `glm` namespace.

**Comment by h4k1m0u** [comment]
Thanks @falbrechtskirchinger. I'll have a look later, seems advanced but I may need it in the future.

**Comment by dunyazad** [comment]
I had the same problem, and It worked when I put the functions (to_json, from_json) inside glm namespace.
