### ISSUE TITLE
In basic_json::basic_json(const CompatibleArrayType& val), the requirement of CompatibleArrayType is not strict enough.

### ISSUE THREAD

**Issue by mysyljr** [nlohmann/json#174]
This is a question Ralated to #167 : 
In basic_json::basic_json(const CompatibleArrayType& val), the requirement of CompatibleArrayType is not strict enough. 
```c++                  
template <class CompatibleArrayType, typename
              std::enable_if<
                  not std::is_same<CompatibleArrayType, typename basic_json_t::iterator>::value and
                  not std::is_same<CompatibleArrayType, typename basic_json_t::const_iterator>::value and
                  not std::is_same<CompatibleArrayType, typename basic_json_t::reverse_iterator>::value and
                  not std::is_same<CompatibleArrayType, typename basic_json_t::const_reverse_iterator>::value and
                  not std::is_same<CompatibleArrayType, typename array_t::iterator>::value and
                  not std::is_same<CompatibleArrayType, typename array_t::const_iterator>::value and
                  std::is_constructible<basic_json, typename CompatibleArrayType::value_type>::value, int>::type
              = 0>
    basic_json(const CompatibleArrayType& val)
        : m_type(value_t::array)
    {
        using std::begin;
        using std::end;
        m_value.array = create<array_t>(begin(val), end(val));
    }
```
Template constructor of basic_json_t above can receive any type that has a type member value_type which can be used as the only parameter in one of basic_json_t's constructors and regard that type as a CompatibleArrayType.
I think the scope of the target types is too much wide, though it excludes some of the types already meet the requirement but are not CompatibleArrayType, still not fine with 3rd party types.

**Comment by nlohmann** [comment]
The code was inspired by some similar constructor from [dropbox/json11](https://github.com/dropbox/json11). In fact, I only added constraints to make the code compile in my setting.

@mysyljr, do you have an example where the code actually breaks?

**Comment by mysyljr** [comment]
Simply define a type whose value_type is basic_json< xxx > will break the functionality, in which case a wrong conversion will be defined and unless you define a operator<< (or anything basic_json has) for that type, otherwise calling a operator<< will instantialize the conversion constructor ending with a compiling error.

**Comment by nlohmann** [comment]
I do not really see the need to change the library's code nor how a change would look like...

**Comment by nlohmann** [comment]
@mysyljr Sorry, I really need an actual example to proceed here.
