### ISSUE TITLE
Read a subkey from json object

### ISSUE THREAD

**Issue by leochou0729** [nlohmann/json#1740]
Hello,
  I try to use the following code to get a boolean subkey.
  `bool switch = !config["Function"]["Enable"].is_null() ? config["Function"]["Enable"] : true;`

But the build process failed with the "Expected unqualified-id" message.
I'm using Xcode with c++14 support. 

BTW, what's the correct way to read arbitrary key value(no matter in what level) to a variable? Thanks!

**Comment by nlohmann** [comment]
There are two issues:

- `switch` is a C++ keyword. You cannot use this as a name for a variable.
- To deduct the type of the variable, all branches need to return the same type. `true` is `bool`, but `config["Function"]["Enable"]` is `json`. The latter can be converted as follows:

```cpp
!config["Function"]["Enable"].is_null() ? config["Function"]["Enable"].get<bool>() : true;
```

**Comment by leochou0729** [comment]
Thanks a lot!
