### ISSUE TITLE
Construction in a member initializer list using curly braces is set as 'array'

### ISSUE THREAD

**Issue by kyeonghopark** [nlohmann/json#1742]
- What is the issue you have?
The type of json object is set as 'array' in a constructor of an inherited class.

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

```
class child : public nlohmann::json {
 public:
  explicit child(const nlohmann::json &j) : nlohmann::json{j} {}
};

nlohmann::json j = nlohmann::json::parse("{\"a\":1}");
child c{j};

```

- What is the expected behavior?
The type of `c` should be 'object', not 'array'.

- And what is the actual behavior instead?
The type of `c` is 'array'.

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?
Visual Studio 2019 (v142)

- Did you use a released version of the library or the version from the `develop` branch?
A released version 3.7.0

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?
This is not a compilation error.

**Comment by kyeonghopark** [comment]
It can also be reproduced with:

```
class child : public nlohmann::json {
 public:
  explicit child(const nlohmann::json &j) : j_{j} {}

  nlohmann::json j_;
};

nlohmann::json j = nlohmann::json::parse("{\"a\":1}");
child c{j};

```

**Comment by kyeonghopark** [comment]
I verified that it is not reproduced with parentheses in member initializer list:
`explicit child(const nlohmann::json &j) : nlohmann::json(j) {}`

It seems initialization with curly braces makes it as array.

**Comment by nlohmann** [comment]
> It seems initialization with curly braces makes it as array.

Yes, this is expected behavior for the library.

**Comment by kyeonghopark** [comment]
Ok, got it.
Thanks.
