### ISSUE TITLE
how to validate json object before calling dump()

### ISSUE THREAD

**Issue by nithax** [nlohmann/json#1748]
I'm having an issue with figuring out a method of detecting if a nlohmann:json object is valid for dump(). Currently, I've been experiencing a bug with dump() that is causing a crash with a malformed json object after parsing.

My answer to this would be to check if json::accept(json_object) would be valid before dumping to prevent a crash, but you can't do that unless you pass an input_adapter to json::accept, which is a string and not a json object.

**Comment by jaredgrubb** [comment]
What error are you getting? That it's not holding anything? Or that some subobject has a bad type (eg, a string that's not UTF-8)?
