### ISSUE TITLE
Since re2c is often ignored in pull requests, it may make sense to make a contributing.md file

### ISSUE THREAD

**Issue by whackashoe** [nlohmann/json#175]
Would save people a bit of time, plus could be useful for keeping code the same style and such too.

**Comment by nlohmann** [comment]
Thanks @whackashoe for noting this. Each time I commented on pull requests, I thought about writing such a file, but I always forget afterward. It's good to have this on the list here now. I shall try to merge this with the FAQ (#163).

**Comment by nlohmann** [comment]
I added some [guidelines](https://github.com/nlohmann/json/blob/master/CONTRIBUTING.md). Please tell me what you think!

**Comment by gregmarr** [comment]
Looks good.  There are a couple places under files to change bullet 1 where you use src.json.hpp instead of src/json.hpp.

**Comment by nlohmann** [comment]
Ooops. I fixed it.

**Comment by twelsby** [comment]
This is a small thing but perhaps add something about testing under Valgrind as occasionally (as I found out to my surprise in pull request #183) it can yield different results to a vanilla run.

**Comment by nlohmann** [comment]
Thanks for the feedback!
