### ISSUE TITLE
Add array support for update() function

### ISSUE THREAD

**Issue by Silberklinge** [nlohmann/json#1751]
I think it would be nice to add functionality to the `update()` function that allows one to update an array's contents with an object that has integer keys, like so:

```
nlohmann::json myarr = { 5, 4, 3, 2, 1 };
myarr.update({ { "1", 40 }, { "4", 10 } });
std::cout << myarr.dump() << std::endl;
// Should output [5,40,3,2,10]
```

**Comment by tete17** [comment]
Why not used a simple function like this?

```c++
void updateJson(nlohmann::json& j, const std::vector<std::pait<int,int>>& list)
{
    if(!j.is_array()) thorw ...;
    for (const auto& pair : list)
    {
        j[pair.first] = pair.second;
    }
}
```

Do you need your update function to take strings on the index argument?

**Comment by nlohmann** [comment]
This is an odd syntax to provide array indices as strings. In any case, this function could be realized without changing the library's API.
