### ISSUE TITLE
[Nested Json Objects] Segmentation fault

### ISSUE THREAD

**Issue by yiakwy** [nlohmann/json#1753]
I have a series objects which implements "json toJson() {}" 

```c++
json j
json pixels_json
j["camera"] = std::move(camera_->toJson())
j["pixels"] = std::move(pixels_json)

for (auto& pixel : pixels)
{
pixels_json.push_back(std::move(pixel->toJson()));
}
```

The snippet of codes raises a Segmentation fault. I doubt whether `json` implements JSON object parser correctly because a json parser should parse

- primitives: Number, Bool, Symbol, String, Function
- Array
- Json Object itself

Apparently, you cannot do it and the documentation does not event mention about it.

**Comment by yiakwy** [comment]
@nlohmann

**Comment by nlohmann** [comment]
The JSON parser is correct. And in your example, it is not even called.

Can you please provide code for the `toJson()` function you are calling? What is the stack trace when the segmentation fault happens?

**Comment by yiakwy** [comment]
@nlohmann get your commet. I will check my code carefully but I do recommend to add such usage in our documentation

**Comment by nlohmann** [comment]
Which usage do you mean?
