### ISSUE TITLE
Readme out of date

### ISSUE THREAD

**Issue by seppy87** [nlohmann/json#1756]
Hallo,
your readme is out of date.

e.g.
Visual Studio says nlohmann::json has no member parse.

can you update your readme?

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by seppy87** [comment]
I just put the single_include json.hpp into my
pojectdir/include/nlohmann/json.hpp
and included it with
#include"include/nlohmann/json.hpp"

I am trying to parse a std::string to Json Object.

with ifstream I have read my language file which is JSON.

```cpp
std::ifstream file("lang.json");
std::string text = "";
	std::string line = "";
	std::string lang = "en";
	while (file >> line) {
		text += line;
	}
	wchar_t* localname = new wchar_t[LOCALE_NAME_MAX_LENGTH];
	auto len = GetSystemDefaultLocaleName(localname, LOCALE_NAME_MAX_LENGTH);
	auto sys = QString::fromStdWString(localname);

```

I wanted to parse std::string text with json::parse(text);

this Message:

> Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler (aktiv)	E0135	"class "nlohmann::basic_json<std::map, std::vector, std::string, bool, int64_t, uint64_t, double, std::allocator, nlohmann::adl_serializer>"" hat keinen Member ""parse"".	QSearch	C:\Users\User\source\repos\QSearch\QSearch\QSearch.cpp	6	

IDE Visual Studio Community 2019 with Qt Addon
I used the Develop Version of nlohmann/json.hpp

**Comment by nlohmann** [comment]
Parsing from `std::string` is not an issue. It's part of the unit tests which also pass with visual studio. Can you try a minimal program like

```cpp
#include "json.hpp"
#include <iostream>

using json = nlohmann::json;

int main()
{
    std::string s = "{\"foo\": 42}";
    auto j = json::parse(s);
    std::cout << j << std::endl;
}
```

**Comment by gregmarr** [comment]
Does the program build?  If so, then it's the issue that intellisense in VS 2019 has some bugs that are preventing it from recognizing this as valid code.  You can find other reports of that here.

**Comment by marc2k3** [comment]
The latest preview of VS2019 finally fixes all these intellisense errors. Not sure when it's going to be "production" ready but I guess it won't be long.

The actual "cause" was posted by an MS employee here...

> This is caused by IntelliSense supporting the Clang __has_extension macro even in Microsoft mode, leading to json.hpp using GNU-style attribute syntax.
> 
> While we work on a fix, you can work around this by passing /Zc:__cplusplus to convince json.hpp to use the standard attribute syntax instead.

https://developercommunity.visualstudio.com/content/problem/678883/c-intellisense-on-vs2019-reports-incorect-errors-t.html

**Comment by nlohmann** [comment]
Maybe fixed with https://github.com/nlohmann/json/pull/1799.

**Comment by marc2k3** [comment]
Unfortunately not...

VS 2019 16.3.5 (latest production release), json 3.7.0

![370_1635](https://user-images.githubusercontent.com/34617027/67042356-9ce45280-f11f-11e9-8178-e26e0aa6a5c6.png)

16.3.5, json master

![master_1635](https://user-images.githubusercontent.com/34617027/67042357-9ce45280-f11f-11e9-9611-4b2f68fe99dc.png)

16.3.5, json 3.7.0 / master with `/Zc:__cplusplus` added as suggested above

![master_1635_cplusplus](https://user-images.githubusercontent.com/34617027/67042358-9d7ce900-f11f-11e9-928d-19e7795b7686.png)

When I updated the json header, I cleared the whole intellitsense database by deleting my .vs folder and starting from scratch. As soon as I applied the extra command line option, the error went away.

VS2019 16.4 Preview 2 also behaves like the last screenshot without `/Zc:__cplusplus` added to the command line options.

**Comment by nlohmann** [comment]
Can we close this issue?

**Comment by marc2k3** [comment]
> Can we close this issue?

VS2019 16.4 is on general release now so I'd say yes.

**Comment by nlohmann** [comment]
Thanks for checking back!
