### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by xabik** [nlohmann/json#1761]
When I execute this function, I get an exception like
**nlohmann :: detail :: parse_error**

```
	void load_info(std::vector<json> info) {
		std::ifstream f;
		f.open("info.json", std::ifstream::in);
		json building;
		while (f >> building) {
			info.push_back(building);
		}
		f.close();
	}
```

file **info.json** with info like this

```
{"coordinates":{"lt":{"x":52,"y":121},"rb":{"x":140,"y":43}},"order":1,"type":19}
{"coordinates":{"lt":{"x":55,"y":118},"rb":{"x":137,"y":46}},"order":3,"type":19}
{"coordinates":{"lt":{"x":54,"y":120},"rb":{"x":135,"y":43}},"order":2,"type":21}
{"coordinates":{"lt":{"x":54,"y":123},"rb":{"x":135,"y":40}},"order":4,"type":21}
```

but if i change my function to:

```
	void load_info(std::vector<json> info) {
		std::ifstream f;
		f.open("info.json", std::ifstream::in);
		json building;
		for (int i = 0; i < 4; i++) {
			f >> building;
			info.push_back(building);
		}
		f.close();
	}
```

function work good. How i can fix this?

MS Visual Studio 2017. Windows 7.

Version library 3.7.0 Release

**Comment by nlohmann** [comment]
What is the exact exception description?

**Comment by xabik** [comment]
Message with exception have only address in memory. Debugger stop program in **case 4:** in 

```
    bool parse_error(std::size_t /*unused*/, const std::string& /*unused*/,
                     const detail::exception& ex)
    {
        errored = true;
        if (allow_exceptions)
        {
            // determine the proper exception type from the id
            switch ((ex.id / 100) % 100)
            {
                case 1:
                    JSON_THROW(*static_cast<const detail::parse_error*>(&ex));
                case 4:
                    JSON_THROW(*static_cast<const detail::out_of_range*>(&ex));
                // LCOV_EXCL_START
                case 2:
                    JSON_THROW(*static_cast<const detail::invalid_iterator*>(&ex));
                case 3:
                    JSON_THROW(*static_cast<const detail::type_error*>(&ex));
                case 5:
                    JSON_THROW(*static_cast<const detail::other_error*>(&ex));
                default:
                    assert(false);
                    // LCOV_EXCL_STOP
            }
        }
        return false;
    }
```

**Comment by nlohmann** [comment]
You should still be able to access the `what()` member of the exception. As it seems to be an `json::exception::out_of_range` which only occurs in https://github.com/nlohmann/json/blob/develop/include/nlohmann/detail/input/parser.hpp#L265, your input seems to contain number that overflow. This is strange.

- Can you narrow down the error to a smaller input that you can share?
- Can you try to access the exception's `what()` message as it should give you the token where the error happend?

**Comment by xabik** [comment]
For more detail, I wrote a simple program. It first writes the information to a file, and then reads it. An error occurs at the reading stage.
```
#include "pch.h"
#include <iostream>
#include <nlohmann/json.hpp>
#include <fstream>

using json = nlohmann::json;

void write_to_file(json info) {
	std::ofstream f;
	f.open("info.json", std::ofstream::app);
	f << info << std::endl;
	f.close();
}

void read_from_file(std::vector<json> info) {
	std::ifstream f;
	f.open("info.json", std::ifstream::in);
	json building;
	while (f >> building) {
		info.push_back(building);
	}
	f.close();
}

int main()
{
	json test1 = {
	  {"type", 19},
	  {"coordinates", {
		{"lt", {
		  {"x", 52},
		  {"y", 121}
		}},
		{"rb", {
		  {"x", 140},
		  {"y", 43}
		}}
	  }},
	  {"order", 1}
	};

	json test2 = {
	  {"type", 21},
	  {"coordinates", {
		{"lt", {
		  {"x", 55},
		  {"y", 118}
		}},
		{"rb", {
		  {"x", 137},
		  {"y", 46}
		}}
	  }},
	  {"order", 3}
	};
	write_to_file(test1);
	write_to_file(test2);
	std::vector<json> info;
	read_from_file(info);
}
```
The `what()` member of the exception `= {_What=0x009e0240 "[json.exception.parse_error.101] parse error at line 2, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal" ...} | __std_exception_data`

**Comment by xabik** [comment]
![locals](https://user-images.githubusercontent.com/7445629/65458015-32186200-de66-11e9-898e-a31376cf0587.jpg)

**Comment by nlohmann** [comment]
I can reproduce the exception. I'll try to dig deeper later this week.

**Comment by DJLink** [comment]
I'm running into a similar exception as @xabik mentioned. Weirdly if I have my json in "beautified" mode when loading it parses correctly, using any online tool to minify (or writing it by hand) and the same exact json hits that exception. 
So I decide to break that minified json into a 2 line and now it loads. 
So in my case a 1 line minified json gives exceptions, >1 loads ok. 
Hope this helps.

**Comment by xabik** [comment]
@DJLink, can you attach file with json which loads correctly? I try to repeat loading.

**Comment by DJLink** [comment]
Here are 3 files, the single line file fails, the other load ok.

I'm using nlohmann::json::parse()


[test_ok_2_lines.txt](https://github.com/nlohmann/json/files/3692952/test_ok_2_lines.txt)
[test_ok_beautify.txt](https://github.com/nlohmann/json/files/3692953/test_ok_beautify.txt)
[test_fail.txt](https://github.com/nlohmann/json/files/3692954/test_fail.txt)

**Comment by nlohmann** [comment]
With the following program, I could successfully parse all of the three files of https://github.com/nlohmann/json/issues/1761#issuecomment-538625813

```cpp
#include <iostream>
#include "json.hpp"
#include <fstream>

using json = nlohmann::json;

int main()
{
    std::ifstream f("test_ok_beautify.txt");
    std::cout << json::parse(f) << std::endl;
}
```

**Comment by nlohmann** [comment]
I had another look at https://github.com/nlohmann/json/issues/1761#issuecomment-534252866. The issue is that `operator>>` does not return false in case of a parse error. Hence, for an input like

```json
{"coordinates":{"lt":{"x":52,"y":121},"rb":{"x":140,"y":43}},"order":1,"type":19}
{"coordinates":{"lt":{"x":55,"y":118},"rb":{"x":137,"y":46}},"order":3,"type":21}
```

`operator>>` only returns successfully twice - calling it a third time yields a parse error exception.

Hence, you would need code like 

```cpp
    try {
        while (f >> building) {
            info.push_back(building);
        }
    } catch (json::exception&)
    {}
```

to parse an arbitrary number of JSON values in a file.

**Comment by nlohmann** [comment]
Do you need further assistance with this issue?
