### ISSUE TITLE
example code for ifstream reading a json file results in no operator error

### ISSUE THREAD

**Issue by desluOs** [nlohmann/json#1766]
```cpp
#include <nlohmann/json.hpp>
#include <iostream>
#include <fstream>
using namespace std;
using json = nlohmann::json;
```

```cpp
void run() {
		ifstream in("test.json");
		json j;

		in >> j;
```

is where the problem occurs, with the >> the only thing resulting in an error.  I got the setup from the example code for reading json files.  This is happening in a header file.  Everything compiles with warnings and will run, but errors out when it gets to this point.

C++ no operator matches these operands            operand types are: std::ifstream >> json

is the exact text given when hovering over the red underlined >>;

Not sure what I'm missing, sorry if it's obvious but I tried to find a solution elsewhere first.

**Comment by MockusT** [comment]
Try changing version to 3.6.1. Should fix the problem (Wasn't working for me also on 3.7.0)

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by notzortex** [comment]
I'm having the same issue on VC++, ifstream and ostream doesn't seem to work with >> or << operands, is this a recent change to the repo itself or does it work for everyone else?

**Comment by mtissington** [comment]
I have the same issue and in addition I get an E0349 with Visual Studio 2019.

**Comment by nlohmann** [comment]
Can you please paste the exact error message?

This code works without issues:

```cpp
#include <iostream>
#include "json.hpp"
#include <fstream>

using json = nlohmann::json;

int main()
{
    std::ifstream in("test.json");
    nlohmann::json j;
    in >> j;
    std::cout << j << std::endl;
}
```

**Comment by TQwan** [comment]
I have the same problem, using Visual Studio 2019 with latest version (3.7.0)
Reverting back to 3.6.1 ( SHA-1: 1126c9ca74fdea22d2ce3a065ac0fcb5792cbdaf ) fixes the issue.

Problem is this line.
`in >> j;`
It seems the implementation of the >> operator has been removed in 3.7.

**Comment by nlohmann** [comment]
No, we did no remove this operator, but only deprecate it.

**Comment by mtissington** [comment]
Here are the 3 errors I get

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0349	no operator ">>" matches these operands	

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0065	expected a ';'	ActiveWords DLL	C:\ActiveWords4\ActiveWords DLL\json.hpp	18922	

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0079	expected a type specifier	ActiveWords DLL	C:\ActiveWords4\ActiveWords DLL\json.hpp	18921

**Comment by nlohmann** [comment]
Which compiler are you using?

**Comment by mtissington** [comment]
I’m using Visual Studio 2019 (latest)

ISO C++17 Standard (std:c++17)

 

But I just noticed these are not compiler errors, they are IntelliSence errors.

**Comment by nlohmann** [comment]
Seems to be related to #1704 #1702 #1756. In #1756, it is reported that a newer version of Visual Studio 2019 has fixed this issue (which is unrelated to this library).
