### ISSUE TITLE
Json dump

### ISSUE THREAD

**Issue by dibet** [nlohmann/json#1768]
- Describe the feature in as much detail as possible.
Any way that dump method dont show empty objects
- Include sample usage where appropriate.
{ "a": { "b": 1}, "c": {} }
o result should be
{ "a": { "b": 1} }

**Comment by jaredgrubb** [comment]
You are asking for an option to suppress printing a key/value pair if the value is `{}`? What if it's an empty array `[]`, or the value `null`, and so forth?

**Comment by dibet** [comment]
Yes, thanks, it is the idea...

**Comment by nlohmann** [comment]
No, this is currently not possible. You would need to remove unwanted values before serialization.

**Comment by dibet** [comment]
I try this approach but steel have some problems

case value_t::object:
            {
                if (val.m_value.object->empty())
                {
                    o->write_characters("{}", 2);
                    return;
                }

                if (pretty_print)
                {
                    o->write_characters("{\n", 2);

                    // variable to hold indentation for recursive calls
                    const auto new_indent = current_indent + indent_step;
                    if (JSON_HEDLEY_UNLIKELY(indent_string.size() < new_indent))
                    {
                        indent_string.resize(indent_string.size() * 2, ' ');
                    }

                    // first n-1 elements
                    auto i = val.m_value.object->cbegin();
                    for (std::size_t cnt = 0; cnt < val.m_value.object->size() - 1; ++cnt, ++i)
                    {
                        o->write_characters(indent_string.c_str(), new_indent);
                        o->write_character('\"');
                        dump_escaped(i->first, ensure_ascii);
                        o->write_characters("\": ", 3);
                        dump(i->second, true, ensure_ascii, indent_step, new_indent);
                        o->write_characters(",\n", 2);
                    }

                    // last element
                    assert(i != val.m_value.object->cend());
                    assert(std::next(i) == val.m_value.object->cend());
                    o->write_characters(indent_string.c_str(), new_indent);
                    o->write_character('\"');
                    dump_escaped(i->first, ensure_ascii);
                    o->write_characters("\": ", 3);
                    dump(i->second, true, ensure_ascii, indent_step, new_indent);

                    o->write_character('\n');
                    o->write_characters(indent_string.c_str(), current_indent);
                    o->write_character('}');
                }
                else
                {
                    o->write_character('{');

                    // first n-1 elements
                    auto i = val.m_value.object->cbegin();
                    for (std::size_t cnt = 0; cnt < val.m_value.object->size() - 1; ++cnt, ++i)
                    {
                        
                        if (i->second.m_type == value_t::object) {
                            
                            if (i->second.m_value.object->empty()) {
                                
                            } else {
                                o->write_character('\"');
                                dump_escaped(i->first, ensure_ascii);
                                o->write_characters("\":", 2);
                                dump(i->second, false, ensure_ascii, indent_step, current_indent);
                                o->write_character(',');
                            }
                        } else {
                            o->write_character('\"');
                            dump_escaped(i->first, ensure_ascii);
                            o->write_characters("\":", 2);
                            dump(i->second, false, ensure_ascii, indent_step, current_indent);
                            o->write_character(',');
                        }
                        
                        
                       
                    }

                    // last element
                    assert(i != val.m_value.object->cend());
                    assert(std::next(i) == val.m_value.object->cend());
                    
                    if (i->second.m_type == value_t::object) {
                            
                            if (i->second.m_value.object->empty()) {
                                
                                o->removeLastChar();
                                
                            } else {
                                o->write_character('\"');
                                dump_escaped(i->first, ensure_ascii);
                                o->write_characters("\":", 2);
                                dump(i->second, false, ensure_ascii, indent_step, current_indent);   
                            }
                        } else {
                            o->write_character('\"');
                            dump_escaped(i->first, ensure_ascii);
                            o->write_characters("\":", 2);
                            dump(i->second, false, ensure_ascii, indent_step, current_indent);   
                        }
                    
                    
                   
                    

                    o->write_character('}');
                }

                return;
            }
