### ISSUE TITLE
JSON performance benchmark comparision

### ISSUE THREAD

**Issue by xor-gate** [nlohmann/json#177]
I would be nice to see how well your JSON library compares with others:
https://github.com/miloyip/nativejson-benchmark

**Comment by gregmarr** [comment]
It's in there.  However, the test was run almost 9 months ago, so it's with an old version.

**Comment by xor-gate** [comment]
I overlook the entry `Nlohmann/json`, but you are right maybe they could update to the new v1.0.0 release.

**Comment by nlohmann** [comment]
Hi @xor-gate, thanks for opening an issue - I am really looking forward to seeing results!

(Though I know the code is not designed having efficiency in mind...)

**Comment by xor-gate** [comment]
@nlohmann there is always a tradeoff with cleanliness and speed.

**Comment by nlohmann** [comment]
I know. But C++ developers seem to only care about speed ;)

**Comment by nlohmann** [comment]
Or to put it differently: Cleanliness/simplicity is harder to quantify than objective criteria like runtime and memory consumption.

**Comment by nlohmann** [comment]
Apparently, the benchmark has been updated to version 1.0.0: https://github.com/miloyip/nativejson-benchmark/commit/7ca51bd8ad04689751a7dda88a04f9de6c335da0 - I haven't seen the results yet, though.

**Comment by nlohmann** [comment]
I ran the benchmarks locally and encountered some errors. I opened #186 and #187 for this.
