### ISSUE TITLE
Interoperability with other languages

### ISSUE THREAD

**Issue by omatrot** [nlohmann/json#1770]
- Describe what you want to achieve.

I'm calling .dump() on my JSON object to get a string representation. However, double quotes are escaped as we can see [in the doc](https://github.com/nlohmann/json#tofrom-strings).

This is unrecognized in Javascript or c# for instance. For me quotation marks should only be escaped within a string.

- Describe what you tried.

I've looked over the documentation but it seems there is no option to suppress those '\\'.

I'm using the release branch version of json.hpp.

**Comment by nlohmann** [comment]
The output should be fine if you call `dump`.

**Comment by omatrot** [comment]
I forgot to say that I'm running on Android, the code is compile with the android NDK.
Let me check by sending the string to the log to confirm.

**Comment by omatrot** [comment]
You're right, the problem is somewhere else up the chain to reach the Javascript.
