### ISSUE TITLE
A weird building problem :-(

### ISSUE THREAD

**Issue by tanpero** [nlohmann/json#1774]
I have a small problem.
I need to keep the insertion order of the JSON keys and output them. According to the existing suggestion, I used `nlohmann::fifo_map` instead of the original `std::map`, which is:

```c++
using json = nlohmann::basic_json<nlohmann::fifo_map>;
```

However, when I build, the compiler tells me this error:

```
add_key: isn't the member of std::less<void>
```
I guess `nlohmann::fifo_map` may need its own template parameters, but this depends on the type in the JSON library, so it won't work.
I checked the related issue, but others didn't seem to have encountered this problem. I want to know how this problem should be solved.
My development environment is: Visual Studio 2017
Thanks! :-D

**Comment by tanpero** [comment]
I tried change the code like this: #https://github.com/nlohmann/json/issues/1763#issue-497843808
and it looks like:

```c++
template<class K, class V, class dummy_compare, class A>
using my_fifo_map = nlohmann::fifo_map<K, V, nlohmann::fifo_map_compare<K>, A>;
using fifo_json = nlohmann::basic_json<my_fifo_map>;
using json = nlohmann::json;
```

But it still can't be compiled successfully. The error info is:

```
undefined identifier: `my_fifo_map`
```

**Comment by tete17** [comment]
@tanpero can you leave a small sample code, that produces the error you are seeing?

Maybe like a small main function?
