### ISSUE TITLE
pass a json object to a class contructor adds an array around the object

### ISSUE THREAD

**Issue by strahlc** [nlohmann/json#1776]
When I pass a json object to a class contructor, an array is added around my object

``` c++
#include <iostream>
#include <nlohmann/json.hpp>


class A {
	public:
		A(const nlohmann::json &by_ref) : _by_ref{by_ref} {
			std::cout << _by_ref.dump(4) << "\n\n";
		}
	private:
		nlohmann::json _by_ref{};
};


class B {
	public:
		B(nlohmann::json by_val) : _by_val{std::move(by_val)} {
			std::cout << _by_val.dump(4) << "\n\n";
		}
	private:
		nlohmann::json _by_val{};
};


int main() {
	nlohmann::json json_object;
	json_object["key1"] = "val1";

	std::cout << json_object.dump(4) << "\n\n";

	A a{json_object};
	B b{json_object};

	return EXIT_SUCCESS;
}
```

Output
``` json
{
    "key1": "val1"
}

[
    {
        "key1": "val1"
    }
]

[
    {
        "key1": "val1"
    }
]
```

I would expect all three outputs like the first one.

I'm using gcc-8.3.0 on gentoo linux and nlohmann_json-3.7.0

**Comment by nlohmann** [comment]
Braces are treated like arrays to allow this syntax:

```
json x = {1,2,3,4}; // [1,2,3,4]
```

Therefore, `{json_object}` will be treated as an array containing whatever is in `json_object`.

**Comment by strahlc** [comment]
In our project we have to follow the cpp coreguidelines, including `ES.23: Prefer the {}-initializer syntax` [1]. 
From that perspective that is an extremely unexpected behavior, because the standard says `={} gives copy initialization whereas {} gives direct initialization.`

[1] http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es23-prefer-the--initializer-syntax

**Comment by nlohmann** [comment]
I'm afraid this behavior cannot be changed without breaking existing code.
