### ISSUE TITLE
Migrate LGTM.com installation from OAuth to GitHub App

### ISSUE THREAD

**Issue by LGTM-badger** [nlohmann/json#1781]
Hi There,

This project is still using an old implementation of LGTM's automated code review, which has now been disabled. To continue using automated code review, and receive checks on your Pull Requests, please [install the GitHub App](https://github.com/apps/lgtm-com/installations/new) on this repository.

Thanks,
The LGTM Team

**Comment by nlohmann** [comment]
When doing so, I have the following permission list:

<img width="785" alt="image" src="https://user-images.githubusercontent.com/159488/67046902-7c24f880-f131-11e9-8619-1b27802cdbd6.png">

Is this expected?

**Comment by s0** [comment]
Yes. No special access to code is required as we only analyse open source repos, and we need to be able to write checks for pull requests.

**Comment by nlohmann** [comment]
Ok, then I think this can be closed.
