### ISSUE TITLE
Comparing data type with value_t::number_integer fails

### ISSUE THREAD

**Issue by kubkodev** [nlohmann/json#1783]
I'm trying to make template function that stores json integer value as int (signed). I had no problem with unsigned, however comparing type for signed seems to fail. What am I doing wrong? Using 3.5.0 version, thanks for any help.

```
//works fine
template<typename Td>
typename std::enable_if<std::is_integral<Td>::value && std::is_unsigned<Td>::value, bool>::type TryGetJsonValue(nlohmann::json const &data, Td &dest)
{
	if (data.type() != nlohmann::json::value_t::number_unsigned)
		return false;

	dest = data.get<Td>();
	return true;
}

template<typename Td>
typename std::enable_if<std::is_integral<Td>::value && std::is_signed<Td>::value, bool>::type TryGetJsonValue(nlohmann::json const &data, Td &dest)
{
	if (data.type() != nlohmann::json::value_t::number_integer) //here
		return false;

	dest = data.get<Td>();
	return true;
}
```

**Comment by tete17** [comment]
Hi @kubkodev 

I am sorry but those `std::enable_if` only make sure the second argument is of the type you are expecting but it says nothing about the actual json object you are passing. As an example, the following code would call your second function and would do the correct thing.

```c++
#include <nlohmann/json.hpp>
int main()
{
    int dest = 0;
    nlohmann::json data = "This json is just a string";
    TryGetJsonValue(data, dest); // This will be false;
}
```

Are you sure the json you are passing contains a signed integer? Could you please provide a small example/json object in which the type is not correct?
