### ISSUE TITLE
Add support for parse stack limiting

### ISSUE THREAD

**Issue by xyzzyz** [nlohmann/json#1788]
Currently. jsonhpp doesn't support stack limiting for parsing. If you try to parse a string that starts with 100 000 '[' characters, it will most likely overflow stack and crash the whole thread. That makes it unsuitable for parsing untrusted json inputs without separating parser to separate binary, potentially with sandboxing. 

Jsonhpp should keep track of the parse stack level, allow for configurable maximum level, and return runtime parsing error whenever stack limit io reached.

**Comment by t-b** [comment]
@xyzzyz I'm also interested in that feature.

Any ideas how to implement that?

The output routine has the same issue, for that I would just add a `maximum_depth` parameter to serializer::dump.

**Comment by nlohmann** [comment]
There are quite some options for `dump` already. It seems that it is time to create some struct `serializer_options` and put all the options in there. Does anyone has an idea how to achieve this without breaking code in newer versions if an option is added?

Say I have this struct:

```cpp
struct serializer_options
{
    bool pretty_print {false};
    std::size_t indentation_step {4};
    char indentation_char {' '};
    bool ensure_ascii {false};
    error_handler_t error_handler {error_handler_t::strict};
};
```

for the current options and their default values and client code with

```cpp
serializer_options options;
options.pretty_print = true;
std::cout << j.dump(options) << std::endl;
```

What would I need to do to avoid breaking this code if I wanted to add

```cpp
std::size stack_limit {0};
```

to `serializer_options`?

**Comment by nlohmann** [comment]
(The described approach https://github.com/nlohmann/json/issues/1788#issuecomment-545565067 could also fix the issues with floating-point precision #1519, #1421, #1384, #1191.)

**Comment by xyzzyz** [comment]
Shouldn't it rather be, **de**-serializer options? This is an issue on parsing side, not on printing side.

**Comment by nlohmann** [comment]
Ooops. Yes. Sorry for the confusion. In any case, the same question also applies for serialization.

**Comment by nlohmann** [comment]
Related #1599

**Comment by nickaein** [comment]
With the merge of #1436 and thanks to the non-recursive parser, the code will not crash for deeply-nested JSON values anymore. Now the parsing is only bounded by the available memory.

Even so, a max-depth parameter for parsing will probably be handy for the user to easily reject a subset of invalid JSONs.

**Comment by nickaein** [comment]
> This is not possible. The value of sizeof $somestruct is part of interface and therefore any change of it, will break the compatiblity. 

That's technically true. Though I wonder how users will be affected. For the most part, I think we can manage to add new members to `serializer_options` without breaking the user code. A disclaimer about the size of this struct can also be helpful. Therefore as long as they don't directly depend on the size of this struct, which is an implementation detail in a sense, we promise the future changes doesn't change the behavior.

We can also implement `from_json`/`to_json` for the users who want to store/load `serializer_options`.

One last solution would be to use [pimpl trick](https://en.cppreference.com/w/cpp/language/pimpl) to keep the struct size constant from the user point of view.

**Comment by t-b** [comment]
@nlohmann 

> Then maybe one could use json as type of the options to allow to add more options down the road.

So we would pass a json document with the options to `dump`? That sounds actually like a nice eat-your-own-dog-food approach.
