### ISSUE TITLE
Can't read json file

### ISSUE THREAD

**Issue by AustinJia** [nlohmann/json#1791]
- Describe what you want to achieve.
Read .json file as json object

- Describe what you tried.
downloaded the include/nlohmann  folder in my local project's include folder
Create a .json file in src
`std::ifstream i(path+"config.json", std::ifstream::binary);`
` json j;`
`i >> j;`
it always shows

> [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal

- Describe which system (OS, compiler) you are using.
ubuntu 16.04 xenial

- Describe which version of the library you are using (release version, develop branch).
JSON for Modern c++ v3.7.0

**Comment by nlohmann** [comment]
Why do you open the file in binary mode? Can you make sure it is properly opened (eg by piping the content to cout)?

**Comment by AustinJia** [comment]
Thanks. You are right.
I opened the file with `std::ifstream::in` now
I even can't print out the content to cout.
Any idea?

**Comment by AustinJia** [comment]
I figured out the issue, I was read the file from the build folder instead original folder.
