### ISSUE TITLE
variable name byte sometimes used as a #define

### ISSUE THREAD

**Issue by SmartMobileLabs** [nlohmann/json#1792]
- What is the issue you have?
in an android enironment/clang  the string byte seems to be #defined to "uint8_t" which causes compilation to fail. The problem i face is in function dump_escape

I am using version 3.6.1

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?
released version 3.6.1 (file json.hpp) from the projects github download page

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by nlohmann** [comment]
Which library makes the define of `byte`?

**Comment by SmartMobileLabs** [comment]
Hi - I found the culprit in one of our own libraries - which is strange as it worked for ubuntu and gcc.  But as it is not too much work I would suggest to not use this variable name.... 
So no action needed and thanks for making me go through our libraries ;-)

**Comment by nlohmann** [comment]
Thanks for checking back!
