### ISSUE TITLE
Add a the possibility to add dynamic json objects

### ISSUE THREAD

**Issue by linux-fan-dave** [nlohmann/json#1795]
When an object get's added to a json tree it is converted to values. The [inja](https://github.com/pantor/inja) engine uses the tree as an input for the template engine. I would like to have a an "lambda" or custom object with functions that are executed when the value is accesed not when the node is inserted in the tree. This adds support for some "lazyness".

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by linux-fan-dave** [comment]
- What is the issue you have?

I want to use the Json tree as an input for a template engine. The tree should not be instanciated (converted to json) when it is created (nodes added) but rather when the tree is walked from the template engine.
This means I want to have a lambda function (that produces a json node when called) beeing convertible to json. When the data is accessed the lambda is called and the json is returned. 

The makers of the template engine [mustache](https://github.com/no1msd/mstch) have implemented a json engine themselves. The user has the possibility to add a class or a lambda as a json node. This is possible as well with nlohmann_json but in contrast to the former in lohmann the object is beeing converted to json when it is added to the tree. In the former it is only converted when it is accesed. 
This means in nlohmann I can not add a user defined object to the tree. Just a json representation of it. This does allow to create "dynamic" trees.

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

In this implementation of json it is possible to add a lambda function to a object. It is executed when the data is accessed. 

mstch::map context{
  {"lambda", mstch::lambda{[]() -> mstch::node {
    return std::string{"World"};
  }}}
};

The user converts this tree to json -> the lambda is called and the following output is created.
{ "lambda": "World" }

- And what is the actual behavior instead?

This is not possible in nlohmann. It is only possible to add an object to the tree whose functions are called when it is added to the tree.

- Which compiler and operating system are you using? Is it a supported compiler?

Yes

- Did you use a released version of the library or the version from the develop branch?

Yes

- If you experience a compilation error: can you compile and run the unit tests?

No compilation error.

**Comment by nlohmann** [comment]
I have no idea how to realize this in the current implementation, as it is based on values. Adding arbitrary lambdas to it would bring a lot of complexity.

**Comment by linux-fan-dave** [comment]
Why not add a std::function<base_json()> as value type. I do not think it needs to be added to base_json as template parameter -> that the factory function is saved in a std::function is an implementation detail. A constructor needs to be added to convert everything callable (lambdas, free functions ...) to the std::function type. On access of a value the lambda would be called and the returned data would replace the lambda. I will try to implement a pull request. Is there any interest on merging any of this functionality?

**Comment by nlohmann** [comment]
This would be doable, but I am afraid of a lot of edge cases that may come up during development. For instance, what should `is_number()` return? Should be function be called for this and `is_number()` on its result? How would JSON pointers work when "entering" a dynamic part? What about code like `j["foo"]["bar"]` if `j["foo"]` is a function? A lot of this *can* be solved, but it may always be some kind of special case.
