### ISSUE TITLE
json error on parsing DBL_MAX from string

### ISSUE THREAD

**Issue by sinannuman** [nlohmann/json#1796]
Hello,
I am facing an exception with serialization on QNX platform. I am serializing a double with the DBL_MAX value (1.7976931348623157e+308). Then I try to parse that value from the string but the exception is thrown:

**Code snippet is:**
```cpp
{
    try
    {
        double d = DBL_MAX;
        nlohmann::json js;
        js["max"] = d;
 
        std::stringstream ss;
        ss << js["max"].dump();
        std::cerr << ss.str() << std::endl;
        nlohmann::json js2 = nlohmann::json::parse(ss.str());
        std::cerr << js2.dump() << std::endl;
    }
    catch(const std::exception& e)
    {
        std::cerr << e.what() << '\n';
    }
}  
```

**Exception:**
[json.exception.out_of_range.406] number overflow parsing '1.7976931348623157e+308'

Related ticket:
https://github.com/nlohmann/json/issues/360

**Comment by t-b** [comment]
@sinannuman Do the tests pass on your platform?

If I read the test code correctly we already have a test for DBL_MAX, see https://github.com/nlohmann/json/blob/ed5541440a36bf7dc1a544f9a84fa3e5ae97b71f/test/src/unit-regression.cpp#L705-L725.

**Comment by nlohmann** [comment]
I cannot reproduce the issue (macOS 10.14.6, Xcode 11.0):

```cpp
#include <iostream>
#include <sstream>
#include <cfloat>
#include "json.hpp"

using json = nlohmann::json;

int main() {
    try
    {
        double d = DBL_MAX;
        nlohmann::json js;
        js["max"] = d;
 
        std::stringstream ss;
        ss << js["max"].dump();
        std::cerr << ss.str() << std::endl;
        nlohmann::json js2 = nlohmann::json::parse(ss.str());
        std::cerr << js2.dump() << std::endl;
    }
    catch(const std::exception& e)
    {
        std::cerr << e.what() << '\n';
    }
}
```

Output:

```
1.7976931348623157e+308
1.7976931348623157e+308
Program ended with exit code: 0
```
