### ISSUE TITLE
Capturing Line and Position when querying

### ISSUE THREAD

**Issue by mjcrawford22** [nlohmann/json#1800]
I am using the pboettch/json-schema-library for validation. When an error is found it does not print the line and position where the anomaly was found. While line and position are printed when anomalies are found when reading the JSON string in your library, are the line and character position stored afterwards so the validator error message can include this information? I have not found this looking at the documentation. If it is there, how would the information be accessed?

We will need this on Linux, Windows and Mac.  I am using version 3.7.0.

**Comment by nlohmann** [comment]
This information cannot be accessed after parsing.
