### ISSUE TITLE
Private data on parsing

### ISSUE THREAD

**Issue by TerensTare** [nlohmann/json#1802]
- Describe what you want to achieve.
I was reading about overloading nllohman::adl_serializer<>.
Wanted to know how to do that with classes that have protected/private data members.
- Describe what you tried.

- Describe which system (OS, compiler) you are using.
Visual Studio 2019, Windows 10 Home
- Describe which version of the library you are using (release version, develop branch).
vcpkg latest release

**Comment by nlohmann** [comment]
This works:

```cpp
#include <iostream>
#include "json.hpp"

using json = nlohmann::json;

class Foo
{
  public:
    Foo(int x_, int y_) : x(x_), y(y_) {}

  private:
    int x;
    int y;
  
    // to allow access to private members
    friend void to_json(json& j, const Foo& f);
};

void to_json(json& j, const Foo& f)
{
    j["x"] = f.x;
    j["y"] = f.y;
}

int main() {
    Foo f(1,2);
    
    json j(f);
    std::cout << j << std::endl;
}
```

**Comment by TerensTare** [comment]
Thank you for everything.
I wish you happy coding.
