### ISSUE TITLE
Merge two json objects

### ISSUE THREAD

**Issue by georgii-ivanov** [nlohmann/json#1807]
OS: ubuntu x64, compiler is g++

I'd like to merge two objects:

```
json obj1 = {
   { "a": 1 }
}

json obj2 = {
   { "b": 2 }
}
```

Expected result:

```
 {
   { "a": 1 },
   { "b": 2 }
}
```

I found in example that I could be done with `merge_patch` method but I can't find it in my installed package.
I've installed the library from ubuntu package: https://packages.ubuntu.com/bionic/nlohmann-json-dev

error: ‘using json = using json = class nlohmann::basic_json<> {aka class nlohmann::basic_json<>}’ has no member named ‘merge_patch’
                     obj1.merge_patch(obj2);

**Comment by nlohmann** [comment]
Try `obj1.update(obj2)`.
