### ISSUE TITLE
Semi-frequent timeouts in `test-unicode_all` with 3.6.1 (aarch64)

### ISSUE THREAD

**Issue by grahamc** [nlohmann/json#1816]
On a semi-regular basis, the `test-unicode_all` test times out in the NixOS build farm.

This is running NixOS on the host, with GCC 8.3.0.

Full build log available: https://hydra.nixos.org/build/103809502/nixlog/1

Log snippet:

```
88/88 Test #80: test-unicode_all ....................***Timeout 1500.01 sec
100000 of 8860608 UTF-8 strings checked
[...]
8200000 of 8860608 UTF-8 strings checked


99% tests passed, 1 tests failed out of 88

Label Time Summary:
all        = 1627.51 sec*proc (41 tests)
default    =  25.67 sec*proc (41 tests)

Total Test time (real) = 1548.32 sec

The following tests FAILED:
         80 - test-unicode_all (Timeout)
```

**Comment by t-b** [comment]
In travis we use a custom timeout, see https://github.com/nlohmann/json/blob/f272ad533d32a40a3b2154a76f1ae9a45eacd6d3/.travis.yml#L336. Not sure if we can add that kind of setting into the test code itself which would be less error prone.

**Comment by grahamc** [comment]
This is not stale.

**Comment by nickaein** [comment]
The `test-unicode_all` [is known](https://github.com/nlohmann/json/issues/1836) to take a long time to run. Based on the logs, it was nearly finished when the timeout occurred (around 92%). Can the time limit be slightly increased to avoid such errors?

The long-term solution is probably breaking down such tests into smaller chunks.

**Comment by grahamc** [comment]
This is not stale.

**Comment by dota17** [comment]
The probleam is still not fixed, i think.
Currently, the `test-unicode_all` is always not finished because times out.
This often happens in `Xcode 9.2 C++` and before.
