### ISSUE TITLE
from_json for non default constructible class with dependency injection

### ISSUE THREAD

**Issue by rvishna** [nlohmann/json#1819]
I have a class without a non default constructor like this:
```
class SomeStruct
{
public:
    SomeStruct() = delete;
    SomeStruct(std::shared_ptr<ContextData) : contextData_(contextData) { }
private:
    std::shared_ptr<ContextData> contextData_;
}
```
`ContextData` is a class that encapsulates dependencies, i.e., data I wish to shared between classes. In my `main()`, I would create a new `ContextData` object based on data from, say, a configuration file, and pass it around to classes that need this data.

Is there a way to implement `from_json()` for `SomeStruct`? I saw the example in the demo for a move constructible type, but I don't understand how I can capture additional data needed by the constructor of my class that is not coming from the `json` object argument to `from_json()`.

**Comment by nlohmann** [comment]
Your type needs to be move-constructible. Then you can follow the example from the documentation: https://github.com/nlohmann/json#how-can-i-use-get-for-non-default-constructiblenon-copyable-types

**Comment by nlohmann** [comment]
Do you need further assistance with this issue?

**Comment by rvishna** [comment]
I conclude that for a struct to be json serializable, it must be default-constructible or move-constructible, which implies that the only way to achieve dependency injection is to do:

```
struct SomeStruct
{
    std::shared_ptr<DataStruct> dependencies_;
    void setData(std::shared_ptr<DataStruct> dependencies) 
    {
        dependencies_ = dependencies;
    }
};
```

instead of this:
```
struct SomeStruct
{
    std::shared_ptr<DataStruct> dependencies_;
    SomeStruct(std::shared_ptr<DataStruct> dependencies)
    : dependencies_(dependencies)
    {
    }
};
```

Is this correct? This is what I'm doing now. The downside is that between when the object of SomeStruct is constructed and when the client code decides to call setData(), some members of SomeStruct would have unassigned values. If this is the only way to achieve to_json() and from_json() of SomeStruct, I am happy to have the issue closed.
