### ISSUE TITLE
Can't compile from_json(std::valarray<T>).

### ISSUE THREAD

**Issue by yunocpp** [nlohmann/json#1824]
Following code couldn't be compiled because the from_json implementation uses the private member 'm_value'.

json Version: v3.7.0

```cpp
#include <nlohmann/json.hpp>

using json = nlohmann::json;

int main()
{
   json j = json::array({1, 0, 2});
   j.get<std::valarray<int>>();
}
```

https://wandbox.org/permlink/ifYduziYXUtfgP4n

**Comment by nlohmann** [comment]
Indeed. Changing

```cpp
std::copy(j.m_value.array->begin(), j.m_value.array->end(), std::begin(l));
```

to

```cpp
std::copy(j.begin(), j.end(), std::begin(l));
``

fixes the issue.

**Comment by nlohmann** [comment]
* * *

### 🔖 Release item

This issue/PR will be part of the next release of the library. This template helps preparing the release notes.

#### Type

- [ ] ✨ New Feature
- [x] 🐛 Bug Fix
- [ ] ⚡️ Improvement
- [ ] 🔨 Further Change
- [ ] 🔥 Deprecated function

#### Description

- fix conversion to `std::valarray`

* * *
