### ISSUE TITLE
Serialize big data in json

### ISSUE THREAD

**Issue by Roman-Koshelev** [nlohmann/json#1828]
For example, I want to add logged events to a JSON file and close it when I exit the program. I would also like to add them to a file as they become available.

What should I do to I make this work?

**Comment by effolkronium** [comment]
nop, json currently load ALL json into memory. It's a big feature to store part of json in memory depending on file pointers :)

**Comment by nlohmann** [comment]
You can use the SAX interface to avoid parsing everything to memory. See https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a8a3dd150c2d1f0df3502d937de0871db.html#a8a3dd150c2d1f0df3502d937de0871db for more information.

**Comment by pbialas7** [comment]
But can you use SAX to write not parse json to file?

**Comment by effolkronium** [comment]
@nlohmann can i use it with memory mapped file (if i have just pointer to data and its size) ?

**Comment by nlohmann** [comment]
> But can you use SAX to write not parse json to file?

No this is not possible in the moment.

**Comment by nlohmann** [comment]
> @nlohmann can i use it with memory mapped file (if i have just pointer to data and its size) ?

Yes, you can do this with

```cpp
json j = json::parse({data, size});
```

**Comment by nlohmann** [comment]
Do you need further assistance with this issue?
