### ISSUE TITLE
Invalid UTF-8 byte at index 1: 0x65

### ISSUE THREAD

**Issue by hayalbaz** [nlohmann/json#1831]
- Describe what you want to achieve.
I want to serialize an object that has a string with "Çevrimiçi" in it. When I try to j.dump() I am getting an exception (json.exception.type_error.316)
- Describe what you tried.
I have tried to set compiler option /utf-8 and source/execution_charset to utf_8.
I saved all my files with encoding utf-8
- Describe which system (OS, compiler) you are using.
windows 10
MSVC 19.20.27508
- Describe which version of the library you are using (release version, develop branch).
latest release version

**Comment by nlohmann** [comment]
Can you provide example code? Is the string `"Çevrimiçi"` inside your code or do you read it from a file?

**Comment by hayalbaz** [comment]
Here is the function I am getting exception thrown:
`
std::string AliveLog::getJSON() {
    json j = json{
        {"createdAt", createdAt},
        {"id", id},
        {"message", message},
        {"detail", detail},
        {"deviceId", deviceId},
        {"type", type.ordinal},
    };
    return j.dump();
}
`
Here message is "Çevrimiçi". It is stored as std::string and is set by a setter method, which I use a struct that has std::string field..

**Comment by nlohmann** [comment]
It seems that the literal "Çevrimiçi" is not encoded in UTF-8. Can you try this:

```cpp
for (int c : message)
{
    std::cout << "character: " << std::hex << c << std::endl;
}
```

to show the full encoded values in the string `message´?

If it's UTF-8, it should be something like

```
\xC3\x87\x65\x76\x72\x69\x6D\x69\xC3\xA7\x69
```

**Comment by hayalbaz** [comment]
character : ffffffc7
character: 65
character: 76
character: 72
character: 69
character: 6d
character: 69
character: ffffffe7
character: 69

**Comment by hayalbaz** [comment]
When I define it like u8"Çevrimiçi" i get
character: ffffffc3
character: ffffff87
character: 65
character: 76
character: 72
character: 69
character: 6d
character: 69
character: fffffffc3
character: fffffffa7
character: 69

**Comment by hayalbaz** [comment]
However when i use j.dump() now the message is with different characters(A with ~ ın tıo and something that looks like a cross instead of Ç). I assume this is due to Visual Studio?

**Comment by nlohmann** [comment]
The u8 version looks right.

**Comment by nlohmann** [comment]
Do you need further assistance with this issue?

**Comment by hayalbaz** [comment]
No, thanks for asking. Weird characters at debug screen was a  Visual Studio problem. It works fine now.
