### ISSUE TITLE
Project branches

### ISSUE THREAD

**Issue by concubicycle** [nlohmann/json#1839]
I'm trying to point CMake's ExternalProject_Add to set up a dependency on this library.

 I put release/3.70 as git tag, but this branch was removed. This breaks my build. Should release branches/tags ever be removed? Am I better off just pointing at master?

**Comment by t-b** [comment]
@concubicycle You probably have referenced a branch or? The tags are listed at https://github.com/nlohmann/json/tags.

**Comment by concubicycle** [comment]
Ah, yep! I put release/3.7.0. v3.7.2 is probably what I want.

**Comment by nlohmann** [comment]
Indeed you should use tags.

**Comment by nlohmann** [comment]
@concubicycle Do you need further assistance with this issue?

**Comment by concubicycle** [comment]
No, thank you guys!
