### ISSUE TITLE
JSON for modern C++ ECCN information

### ISSUE THREAD

**Issue by Taka0811** [nlohmann/json#1840]
I would like to know the JSON for modern C++ ECCN / LE  information.

I have checked the following, but I couldn't find this.
https://github.com/nlohmann/json/blob/develop/README.md

**Comment by nlohmann** [comment]
I never heard of this, sorry. What is it needed for?

**Comment by Taka0811** [comment]
Sorry for short explanation.
I would like to know if JSON for modern C++ contains US native technology.
If yes, I would like to know ECCN / LE information.

ECCN mean the following.
https://www.bis.doc.gov/index.php/licensing/commerce-control-list-classification/export-control-classification-number-eccn

**Comment by Taka0811** [comment]
Sorry for inconvenience.
Could you please update above?

**Comment by nlohmann** [comment]
I don't know the answer to your question - there are 144 contributors to the project. I do not know whether there is anything "US native" in the code. I also would not know how to classify the software in terms of ECCN. I guess you asking about such a classification may know much more about this.

**Comment by Taka0811** [comment]
Hi,
Sorry for late, and thanks for your explanation.
I understood.

Sorry for inconvenience, and thanks for your cooperation.
