### ISSUE TITLE
Please change assert into throw(maybe) in line 17946

### ISSUE THREAD

**Issue by beegerous** [nlohmann/json#1841]
- Describe the feature in as much detail as possible.
when run a code like:
``` cpp
void test(const nlohmann::json& a) {
    cout << a["a"] << endl;
}
int main() {
    nlohmann::json a;
    test(a);
}
```
It just assert fail with no log or hint of the error key. When the project is quite complicated, it is hard to know where i got wrong.

**Comment by nlohmann** [comment]
You can check the key in the debugger.
