### ISSUE TITLE
How to reuse the parser and serializer intermediate storage?

### ISSUE THREAD

**Issue by vinniefalco** [nlohmann/json#1847]
If I am parsing or serializing multiple JSON in a row, is there a way to re-use the intermediate storage used for those operations in between values?

**Comment by nlohmann** [comment]
What do you mean?

**Comment by vinniefalco** [comment]
Lets rewind. Does this library allocate temporary storage when parsing a JSON?

**Comment by tlee-vertiv** [comment]
Do you expect parsing the json in-place?

**Comment by vinniefalco** [comment]
No, I'm looking at the use-case of parsing a JSON into an `nlohmann::basic_json` (with default parameters). Maybe nlohmann doesn't allocate temporary storage, perhaps it only uses the regular stack?

**Comment by nlohmann** [comment]
The lexer (https://github.com/nlohmann/json/blob/develop/include/nlohmann/detail/input/lexer.hpp#L1481) and the parser (https://github.com/nlohmann/json/blob/develop/include/nlohmann/detail/input/parser.hpp#L487) manage their state in some member variables. It is not the state of the parsing (i.e., the stack needed to process the input), but rather the glue between input, lexer, and parser, as well as some variables to hold parsed values, error codes, etc. The actual hierarchy is managed in the SAX parser implementations (https://github.com/nlohmann/json/blob/develop/include/nlohmann/detail/input/json_sax.hpp#L317).

None of this can currently be reused.

**Comment by vinniefalco** [comment]
That was very helpful thanks. The one-off variables are not interesting but these are:
```
std::vector<bool> states;
```
and
```
std::vector<BasicJsonType*> ref_stack {}
```

These could be reused if the caller desires to parse several JSON texts in a row.

**Comment by nlohmann** [comment]
Could be. Any idea how to achieve this with a nice API?

**Comment by vinniefalco** [comment]
Hard to say, I would have to study the library in-depth to figure out how to do it harmoniously. You could just pack them up into a class and require the caller pass the address of it as the last parameter, or if the parameter is left out than a temporary one is used.
