### ISSUE TITLE
While trying to make a simple array, I get a nested array instead

### ISSUE THREAD

**Issue by jlconlin** [nlohmann/json#1848]
- Describe what you want to achieve.
I'm trying to make a simple JSON array for my custom class

- Describe what you tried.
```cpp
struct A{
  int c1;
  int c2;
};

void to_json( json& JSON, const A& a ){
  JSON = { A.c1, A.c2 };
}

A myA{ 21, 22};

auto json = nlohmann::json{ myA };
// Gives me [[ 21, 22]]
// Would like it to return [21, 22]
```

I've also tried (from #1013)
```cpp
void to_json( json& JSON, const A& a ){
  JSON = std::forward_list< int >{ A.c1, A.c2 };
}
```
and got the same response.

- Describe which system (OS, compiler) you are using.
MacOS 10.14, LLVM 3.8

- Describe which version of the library you are using (release version, develop branch).
master branch, commit `c0d511ea500e698061a4b288bd77ce43bd76fa70` (okay, it's kind of old)

**Comment by nlohmann** [comment]
The library interprets the braces in

```cpp
auto json = nlohmann::json{ myA };
```

as array. Try replacing this by

```cpp
nlohmann::json json = myA;
```

**Comment by jlconlin** [comment]
This works, but I'm struggling to understand the difference. Why aren't the braces interpreted as brace initialization?

**Comment by nlohmann** [comment]
I think it is interpreted as an initializer list, and the corresponding (implicit) constructor creates an array.
