### ISSUE TITLE
please improve the enum conversion documentation (my example gist provided)

### ISSUE THREAD

**Issue by qingfengxia** [nlohmann/json#1851]
my first expression is enum class conversion is not supported, but after an time consuming investigation, it is possible without any change, but official document does not provide example.

Here is mime

https://gist.github.com/qingfengxia/92f5fa843ac6bbc951135a32172bfcff

tested with C++17, but should works for C++14/11

also, thank you for this great lib

Qingfeng

**Comment by nlohmann** [comment]
Can you elaborate what is the difference to the documented approach in https://github.com/nlohmann/json#specializing-enum-conversion?

**Comment by qingfengxia** [comment]
Maybe add the the end this section

`NLOHMANN_JSON_SERIALIZE_ENUM()` also works for scoped `enum class`  (C++11), for example.

```cpp
enum  class DevicePreference {  CPU,    GPU };
NLOHMANN_JSON_SERIALIZE_ENUM(DevicePreference, {
          {DevicePreference::CPU, "CPU"},
          {DevicePreference::GPU, "GPU"},                               })
```

Usage is same

**Comment by nlohmann** [comment]
How does the existing documentation make you assume it would not work for an `enum class`?

**Comment by qingfengxia** [comment]
A line like "NLOHMANN_JSON_SERIALIZE_ENUM() also works for scoped enum class (C++11)" can assure new users, it works for C++11, if not, it is user's fault. Because, in multiple files project, namespace,etc make it not evident how it should setup. and template programming is hard to spot error.
