### ISSUE TITLE
json.at_or_default(key, defaultval)

### ISSUE THREAD

**Issue by adreed-msft** [nlohmann/json#1852]
- Describe the feature in as much detail as possible.

```
if (j.contains("access_token"))
{
    j.at("access_token").get_to(t.access_token);
} 
else 
{
    t.access_token = "";
}
```

This tends to be a lot of boilerplate to ensure something's there. I just want to supply a default within the single line if the key does not exist in the json struct.

- Include sample usage where appropriate.

`json.at_or_default("nonexistantkey", "default")` should return "default", as the key does not exist.

However,

`json.at_or_default("existing", "default") // "existing" exists, and contains "nondefault"` should return "nondefault" as the key does exist.

**Comment by marc2k3** [comment]
Have a a look at `value`.

https://nlohmann.github.io/json/classnlohmann_1_1basic__json_adcf8ca5079f5db993820bf50036bf45d.html#adcf8ca5079f5db993820bf50036bf45d

**Comment by adreed-msft** [comment]
Works for me!
