### ISSUE TITLE
Documentation on operator[] behavior with missing keys

### ISSUE THREAD

**Issue by sachabest** [nlohmann/json#1855]
- What is the issue you have?

Right now `operator[key]` is documented to create a `null` key in the called upon json object should `key` not exist in that object, if the source object is NOT `const`. If the object is `const`, `operator[]` returns the equivalent of `*(map.cend())`.

I think the documentation around this could be improved, as I would bet users are not fully aware of the behavioral differences depending on the `const`ness of the source object.

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

```c++
#include <nlohmann/json.hpp>

int main()
{
    const nlohmann::json j = {{ "key1", "value1" }}; // { "key1": "value1" }
    const nlohmann::json& missingKey = j["key2"];
    // missingKey here is UB
}
```
- What is the expected behavior?

I think the current behavior is fine, documentation could be improved to reflect it.

- And what is the actual behavior instead?

N/A

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

GCC 5 + RHEL7 as well as VC141/151 Win10 x64

- Did you use a released version of the library or the version from the `develop` branch?

Latest major version

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by nlohmann** [comment]
The function (https://github.com/nlohmann/json/blob/develop/include/nlohmann/json.hpp#L3280) has a `@warning` documentation:

```
    @warning If the element with key @a key does not exist, the behavior is
    undefined.
```

Any proposal how to improve this?

**Comment by sonulohani** [comment]
Documentation seems right. While accessing any key through operator [], we need to make sure that given key is in range, otherwise it will result in undefined behaviour and can also crash application.
