### ISSUE TITLE
Query a binary format (BSON, CBOR, MessagePack, UBJSON)

### ISSUE THREAD

**Issue by davidglavas** [nlohmann/json#1856]
Is it possible to serialize a json document as, say, a BSON document and then extract fields out of the BSON document directly? 

For example, the mongodb c++ driver offers functions for [getting fields out of BSON documents](http://mongocxx.org/mongocxx-v3/working-with-bson/#fields). Is there something similar?

**Comment by nlohmann** [comment]
Right now, you first need to parse the binary value before you can access a specific value:

```cpp
auto j = json::from_bson(x);
auto v = j["my_key"];
```
