### ISSUE TITLE
Memory Requirement for large json file

### ISSUE THREAD

**Issue by harajyotidas** [nlohmann/json#1858]
- Describe what you want to achieve.
I am evaluating  the memory requirements for big json file. The size of the json file(normal json file) is 68 mb. After parsing, I see that the application takes around 1GB of memory. Why is it taking so much of memory? 

- Describe what you tried.
```
std::ifstream i("project.json", std::ifstream::in);
json j;
i >> j;
```

- Describe which system (OS, compiler) you are using.
windows 10/64 bit/I7 processor/16GB RAM

- Describe which version of the library you are using (release version, develop branch).
latest release version

**Comment by nlohmann** [comment]
This depends on the JSON value. Can you share it?

The library uses at least 64 bit per value (number, bool, null), and pointers to `std::string`, `std::map`, `std::vector` for strings, objects, and arrays, respectively. You can use the SAX interface if you do not want a DOM parser.
