### ISSUE TITLE
How to serialize nested classes to semi-flat JSON object?

### ISSUE THREAD

**Issue by jlconlin** [nlohmann/json#1859]
- Describe what you want to achieve.
I'm trying to serialize my objects. They look like this (overly simplified):

```c++
struct A{
 double Aa;
 double Ab;
};

struct B{
  int Ba;
  int Bb;
};

struct super{
  A myA;
  B myB;
};
```

I'm trying to create a JSON object like this:

```json

super = {
 "Aa": 1.0,
 "Ab": 2.0,
 "Ba": 3,
 "Bb": 4
}
```

- Describe what you tried.
I have functions like this:

```c++
inline void to_json( nlohmann::json& JSON, const A& a ) {
  JSON = { "Aa", a.Aa, "Ab", a.Ab };
}
inline void to_json( nlohmann::json& JSON, const B& b ) {
  JSON = { "Ba", b.Ba, "Bb", b.Bb };
}
inline void to_json( nlohmann::json& JSON, const super& sup ) {
  JSON = {
   sup.myA, 
   sup.myB
  };
}
```
I'd like to have a single object with keys: "Aa", "Ab", "Ba", "Bb". Instead I get an array of two objects:
```json
super = [
  { "Aa": 1.0, "Ab": 2.0 },
  { "Ba": 3, "Bb": 4 }
]
```
Please help me know what I'm doing wrong.

- Describe which system (OS, compiler) you are using.
LLVM 3.8.1

- Describe which version of the library you are using (release version, develop branch).
Fairly recent from master branch.

**Comment by nlohmann** [comment]
The braces are interpreted as an array (there is no real nice syntax for C++...). You need additional braces - a list of pairs is interpreted as object:

```cpp
inline void to_json( nlohmann::json& JSON, const A& a ) {
  JSON = { {"Aa", a.Aa}, {"Ab", a.Ab} };
}
inline void to_json( nlohmann::json& JSON, const B& b ) {
  JSON = { {"Ba", b.Ba}, {"Bb", b.Bb} };
}
inline void to_json( nlohmann::json& JSON, const super& sup ) {
  JSON = sup.myA;
  JSON.update(sup.myB);
}
```

Function [update](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a1cfa9ae5e7c2434cab4cfe69bffffe11.html#a1cfa9ae5e7c2434cab4cfe69bffffe11) is used to merge two objects.

**Comment by jlconlin** [comment]
`update` is exactly what I needed. Thanks!
