### ISSUE TITLE
Best way to extract numbers in the string?

### ISSUE THREAD

**Issue by grancia** [nlohmann/json#1865]
Given following string having double quotes in input string, what is the best way to extract numbers only with nlohmann json?
input: "{'data_a': [1, 2], 'data_b': [3, 4]}"

**Comment by nickaein** [comment]
Have you read [the examples](https://github.com/nlohmann/json#examples)? This will be pretty straightforward if the input is valid JSON string.

**Comment by grancia** [comment]
I have checked but it looks a bit different case.
For example, if json file looks like below how can we extract number from them? Meaning in case, the data's value is double quoted... 
{"data": "{'data_a': [1, 2], 'data_b': [3, 4]}"}

**Comment by nickaein** [comment]
In this case your input is valid JSON string, but `data` field is a string containing ```{'data_a': [1, 2], 'data_b': [3, 4]}```. The contents are not an valid JSON string as keys are single quoted. One approach to extract the number might be:

https://wandbox.org/permlink/DQ9FSnoaEELbwJhG

**Comment by grancia** [comment]
thank you!
