### ISSUE TITLE
WIP: QT (cute) type supports

### ISSUE THREAD

**Issue by 42sol-eu** [nlohmann/json#1869]
- Describe the feature in as much detail as possible.

add a feature_flagged function the nlohmann::json(::magic) to support Qt-Datatypes
**I would at least start implementing that if someone would coach me through!**

good examples: easylogging++

- Include sample usage where appropriate.

```
QMap<QString, MyData> data = json_data; // converted with nlohmann::json::magic ;-)

QMap<std::string, MyData> data = json_data; 

QVector<QVariant> string_list = json_data;
```

**Comment by nlohmann** [comment]
This should be all possible via the `to_json`/`from_json` functions, described in https://github.com/nlohmann/json#arbitrary-types-conversions.

**Comment by 42sol-eu** [comment]
so i I would implement a json_qt.hpp with the to_json(... QMap<> ...) and from_json( ... QMap<>) the QT type system could be included?

often it is only like a std-library type e.g.
```
void to_json(json j, QString d )
{
    j =  d.toStdString()
}

void from_json(json j, QString d )
{
    d = QString::fromStdString( j.get_as<std::string>)
}
```

I was wondering where you implemented it for std:vector and std::list - maybe this would be a great template for the QT containers (by the way I hate them and would replace them with std-library containers as soon as possible, but ...)

**Comment by nlohmann** [comment]
I would not like to add the conversions from/to Qt to the library as it would then depend on the Qt headers. But all conversions are possible via to_json/from_json functions, so you could create your own `json_qt.hpp` header.
