### ISSUE TITLE
Sub-array to vector or map object?

### ISSUE THREAD

**Issue by flamendless** [nlohmann/json#1870]
Hi, how do I store the result of
`?? flags = parsed.at("flags");`

Into a std::map or std::vector so that I can loop them.

With this `.json` file:
```json
{
  "width": 640, "height": 480,
  "flags": {
    "Ph": 1, "En": 0, "Fr": 1
  }
}
```

Specifically i want to for-loop on the ?? return type and have access to the strings (i.e "Ph", "En", etc) and the associated values

I don't want to use `auto`

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by sonulohani** [comment]
Here is the way to store the result in std::map.

```
#include "../single_include/nlohmann/json.hpp"
#include <iostream>

int main()
{
    const nlohmann::json j = {{"width", 640}, {"height", 480}, {"flags", {{"Ph", 1}, {"En", 0}, {"Fr", 1}}}};

    std::unordered_map<std::string, uint32_t> m;

    j["flags"].get_to(m);
    for (auto i : m)
    {
        std::cout << i.first << " " << i.second << '\n';
    }
    return 0;
}
```

**Comment by nickaein** [comment]
Similar to @sonulohani solution, here is a working example without the use of `auto`: https://wandbox.org/permlink/HkBwBfWkS6waerF3

BTW, is there any reason to avoid that? Using `auto` in this case can make the code much cleaner. Given that this library needs C++11 support, the `auto` should be available nevertheless.

**Comment by flamendless** [comment]
@sonulohani thank you for this solution.

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by flamendless** [comment]
@nickaein indeed, using auto is clean, but im still learning c++ so for now i want to do it the old way

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nlohmann** [comment]
The return value of [`at`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a93403e803947b86f4da2d1fb3345cf2c.html#a93403e803947b86f4da2d1fb3345cf2c) is a reference (`json&`).
