### ISSUE TITLE
warning:c4503

### ISSUE THREAD

**Issue by Yordroid** [nlohmann/json#1875]
i want to delete warning
 warning C4503: “nlohmann::detail::conjunction<nlohmann::detail::negation<std::is_same<void,CompatibleObjectType>>,nlohmann::detail::negation<nlohmann::detail::is_compatible_object_type<BasicJsonType,CompatibleObjectType>>,nlohmann::detail::negation<std::is_constructible<std::basic_string<char,std::char_traits<char>,std::allocator<char>>,CompatibleArrayType>>,nlohmann::detail::negation<nlohmann::detail::is_basic_json_nested_type<BasicJsonType,std::unique_ptr<T,nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>::create::<lambda_ba3b2fe0e005bec25a60c7729be5696a>>>>,nlohmann::detail::has_value_type<CompatibleArrayType>,nlohmann::detail::has_iterator<CompatibleArrayType>>”: 超出修饰名的长度，名称被截断

compile by vs2015
use new version

**Comment by JuliaChiang** [comment]
Hi! I am new to Github. I am also interested in doing some projects in C++. I wonder if you can share some experience？ Thank you :)

**Comment by nlohmann** [comment]
According to https://docs.microsoft.com/de-de/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4503?view=vs-2019

> This compiler warning is obsolete and is not generated in Visual Studio 2017 and later compilers.

Given the nature of the warning, I think changing the code could introduce incompatibilities and is not worth the risk.
