### ISSUE TITLE
Serialize dynamic array

### ISSUE THREAD

**Issue by AlexRos101** [nlohmann/json#1879]
Hi nlohmann!

Thank you for your project.

I have a question.

I want to serialize a dynamic array. The code is like below.

```
struct person {
		std::string name;
		std::string address;
		int age;
		std::string *emails;	// this is a dynamic array of emails which the person has.
	};
```

How can I solve this problem?

Thanks.

**Comment by frenzisys** [comment]
Use std::vector<std::string> emails

Il mar 24 dic 2019, 08:17 AlexRos101 <notifications@github.com> ha scritto:

**Comment by AlexRos101** [comment]
Hi frenzisys!

Thank you for your reply.

In that case, I can implement from_json function.

Can you send me to_json function in the case of using std::vector?

Thanks.

**Comment by nlohmann** [comment]
`std::vector` is mapped to an array automatically. You just need to implement `to_json`/`from_json` for `person`. All steps for this are described in https://github.com/nlohmann/json#arbitrary-types-conversions.

**Comment by dota17** [comment]
> Can you send me to_json function in the case of using std::vector?


The example is very simple:
```c++
namespace ns {
    struct person {
	std::string name;
	std::string address;
	int age;
	std::vector<std::string> emails;	// this is a dynamic array of emails which the person has.
    };
    void to_json(json& j, const person& p) {
        j = json{{"name", p.name}, {"address", p.address}, {"age", p.age}, {"emails", p.emails}};
    }

    void from_json(const json& j, person& p) {
        j.at("name").get_to(p.name);
        j.at("address").get_to(p.address);
        j.at("age").get_to(p.age);
        j.at("emails").get_to(p.emails);
    }
} // namespace ns
```

I think this issue could be closed.
