### ISSUE TITLE
json::parse(begin, end) parse error on first character using uchar*

### ISSUE THREAD

**Issue by j-o-d-o** [nlohmann/json#1887]
### What is the issue you have?
Using the json::parse() function with uchar* yields in a parsing error for the very first character.

### Please describe the steps to reproduce the issue.
```c++
// outImg is of type cv::Mat (with outImg.rows > 0 and outImg.cols > 0)
uchar* imgBuff = outImg.isContinuous() ? outImg.data : outImg.clone().data;
size_t imgBuffSize = outImg.rows * outImg.cols * outImg.channels();
auto rawImgStr = nlohmann::json::parse(imgBuff, imgBuff + imgBuffSize);
```

### What is the expected behavior?
A parsed img string can be added to the json object such as:
```c++
nlohmann::json output = {
  {"image", rawImgStr},
  {"imgWidth", outImg.size().width},
  {"imgHeight", outImg.size().height},
};

std::vector<std::uint8_t> v_bson = json::to_bson(output);
```

### And what is the actual behavior instead?
Getting this error:
```bash
[json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: 'D'
```

### Which compiler and operating system are you using?
GCC v7.4, Linux Mint 19

### Did you use a released version of the library or the version from the `develop` branch?
Release version: 3.7.3

**Comment by nlohmann** [comment]
What type is `uchar` and what encoding to you use? The library only supports UTF-8.

**Comment by j-o-d-o** [comment]
Oh yeah, forgot to mention that, the uchar is from opencv `typedef unsigned char uchar`.

And I guess the encoding is the whole problem here since the unsigned char actually represent intensity values for each pixel and channel in the range of 0-255. I guess if I want to encode that information into a json string, I'd have to map these values to valid utf-8 byte codes.

I ended up encoding the image to .jpg and create a base64 from that. That I can add to the json without any issues.
