### ISSUE TITLE
Multiple arrays to vectors help

### ISSUE THREAD

**Issue by flamendless** [nlohmann/json#1888]
With this json
```
{
  {
    "name": "test", "author": "test", "index": 0
  },
  {
    "name": "test2", "author": "test2", "index": 1
  }
}
```
How do I parse that so I can get each sub-array (2 in this example) and store those to a `std::vector`?

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nlohmann** [comment]
Is the question on parsing or accessing?

The above snippet is not valid JSON: the outer braces start an object, but there is no key.

**Comment by flamendless** [comment]
Oh my bad. Yeah the json is not valid, sorry (new to json format). Anyways i have managed to answer my question. Thanks
