### ISSUE TITLE
Get array of items without using vector

### ISSUE THREAD

**Issue by shrikky** [nlohmann/json#1890]
I have an array of objects. I want to parse it into an array directly. 

Example I have an array of boxes in Json
"Boxes":[
{
"name" :" box1",
"area" : "45"
},
{
"name": "box2"
"area": "50"
}
]

I want to directly parse it into an array of objects say in Boxes* boxes

Is it possible to do something like 
Json J
Boxes* boxes = j.at("Boxes").get_ptr<Boxes*>();

I am on Win 10, Visual Studio 2019
- Describe which version of the library you are using (release version, develop branch).
Version 3.7.3

**Comment by nlohmann** [comment]
You cannot call `get_ptr` with non-library types. The following code should work (assuming you implemented a `from_json` function for type `Boxes` as described in the README:

```cpp
std::vector<Boxes> boxes = j.at("Boxes");
```

**Comment by shrikky** [comment]
Yep vector works, so there is no way to directly parse it into an array of boxes like boxes* ?

**Comment by nlohmann** [comment]
No, the library does not support C-style arrays.

**Comment by shrikky** [comment]
Okay thank you once again for taking your time.
