### ISSUE TITLE
What is the best way to parse vec3s into glm::vec3

### ISSUE THREAD

**Issue by shrikky** [nlohmann/json#1891]
I tried the following, but it didn't work.

	void from_json(const json& j, glm::vec3& vec)
	{
		j.at("x").get_to(vec.x);
		j.at("y").get_to(vec.y);
		j.at("z").get_to(vec.z);
	}
Please help me out,
thank you :)

**Comment by nlohmann** [comment]
You need to define the `from_json` function in the same namespace as the type (see the README), so the following should work:

```cpp
namespace glm
{

void from_json(const json& j, vec3& vec)
{
	j.at("x").get_to(vec.x);
	j.at("y").get_to(vec.y);
	j.at("z").get_to(vec.z);
}

}
```

**Comment by shrikky** [comment]
Hmm I tried that exactly, It didn't work. 
![image](https://user-images.githubusercontent.com/6486533/71902422-12b0f680-3130-11ea-86f1-8bb358c249b9.png)

I have all from_json in one class... Should I move the from_json function to the glm class? (that is in a separate library)

**Comment by shrikky** [comment]
that worked, I completely overlooked that. thank you very much nlohmann :)

**Comment by nlohmann** [comment]
Can I close the issue?

**Comment by shrikky** [comment]
Yes absolutely. Quick question, is there a forum for questions and answers? These questions you answer here maybe helpful to other people who stumble upon this. If the github search includes closed tickets then it should do I guess.
