### ISSUE TITLE
Best way to handle json files with missing key value pairs.

### ISSUE THREAD

**Issue by shrikky** [nlohmann/json#1893]
There are two possible ways (maybe more that I missed) to check if key is present in the json.

Json J;
j.contains("mykey") == true?
auto it = j.find("mykey");

I have a test application where the configuraton properties (json key/val) may or may not be present as it is based on the test case. I don't want to do j.find or j.contains for every key before parsing it into the class. Is there a better way to ignore or return default value when a json key/val is not present in the json file?

Currently j.at("mykey").get_to(value) throws error if the mykey is not present in json.

**Comment by nlohmann** [comment]
You may want to check the [`value`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_adcf8ca5079f5db993820bf50036bf45d.html#adcf8ca5079f5db993820bf50036bf45d) function.

**Comment by shrikky** [comment]
Brilliant ! thank you very much.

**Comment by shrikky** [comment]
Does Value work with loading an array objects into vectors? My vector always shows size 0 if I try something like std::vector<TestSettings> setupTasks = j.value("setupTasks",setupTasks);

**Comment by nlohmann** [comment]
Yes, that should work.
