### ISSUE TITLE
Small documentation mistake

### ISSUE THREAD

**Issue by PocketQuads** [nlohmann/json#1895]
https://github.com/nlohmann/json/blob/develop/single_include/nlohmann/json.hpp#L7986

It says that reading 1-9 in the decimal1 state will go to an error state, but actually it goes to the decimal2 state, as can be seen here

https://github.com/nlohmann/json/blob/develop/single_include/nlohmann/json.hpp#L8147-L8155

**Comment by nlohmann** [comment]
* * *

### 🔖 Release item

This issue/PR will be part of the next release of the library. This template helps preparing the release notes.

#### Type

- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] ⚡️ Improvement
- [x] 🔨 Further Change
- [ ] 🔥 Deprecated function

#### Description

- Fixed documentation of number scanner. #1895

* * *
