### ISSUE TITLE
Writing map to json file 

### ISSUE THREAD

**Issue by liorko87** [nlohmann/json#1896]
- Describe what you want to achieve.
I want to write my map to a json file. I want that the json file will look like this:

```
"data": {
"key1": "val1",
"key2": "val2",
}
```

- Describe what you tried:
I tried this code snippet:
```
json party = json::array();
json map = json::array();

    for (auto const& x : m_auxiliaryData)
    {
        json data = json::object();
        data[x.first] = x.second;
        map.insert(map.end(), data);
    }

    party["auxiliaryData"] = map;
```

At the last line of the code, I got this exception: 
```
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.305] cannot use operator[] with array
terminate called after throwing an instance of 'nlohmann::detail::type_errorterminate called after throwing an instance of 'nlohmann::detail::type_error'
'
  what():  [json.exception.type_error.305] cannot use operator[] with array
  what():  [json.exception.type_error.305] cannot use operator[] with array
```

When i removed the last line of the code, the object created without the main key:
```
{
"key1": "val1",
"key2": "val2",
}
```
How can i add it?

- Describe which system (OS, compiler) you are using: Ubuntu 18.04 LTS

- Describe which version of the library you are using (release version, develop branch): 3.0.1

**Comment by nlohmann** [comment]
What type does `m_auxiliaryData` have?

If it is a `std::map` and the keys are convertible to `std::string`, and the values are convertible to `json`, then the following code should work as the library has an implicit conversion for this:

```cpp
json party;
party["auxiliaryData"] = m_auxiliaryData;
```

**Comment by liorko87** [comment]
Thank you for your answer. It's works. `m_auxiliaryData` is `map<string,string>.
I have another question. When I'm trying to add more objects to `party` I got the same exception.

Code snippet:
```
for (int taskNameIdx = 0; taskNameIdx < m_names.size(); taskNameIdx++)
    {
        //Write for each task name all the iteration
        json task = json::object();
        task["name"] = m_names[taskNameIdx];

        for (int iterationIdx = 0; iterationIdx < m_numberOfIterations; iterationIdx++)
        {
            ostringstream streamObj;
            streamObj << fixed << setprecision(3) << (*m_cpuEndTimes)[taskNameIdx][iterationIdx];
            task["iteration_" + to_string(iterationIdx)] = streamObj.str();
        }

        party.insert(party.begin(), task);
    }
```

**Comment by nlohmann** [comment]
Which exception and from which line?

**Comment by liorko87** [comment]
the exception is at the last line:
`party.insert(party.begin(), task);`

Exception details:
```
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():    what():  [json.exception.type_error.309] cannot use insert() with object[json.exception.type_error.309] cannot use insert() with object
  what():  [json.exception.type_error.309] cannot use insert() with object

```

**Comment by nlohmann** [comment]
`insert` can only be called on arrays, see table https://nlohmann.github.io/json/ (bottom).

**Comment by liorko87** [comment]
I mixed between arrays and the map. Everything is work as expected.
Thank you for your kind help.
