### ISSUE TITLE
Compilation failure using Clang on Windows

### ISSUE THREAD

**Issue by jabra98** [nlohmann/json#1898]
Hi, the compilation fails when using Clang on Windows. I have used Ninja as my Generator and this is the cmake --build output:  https://pastebin.com/fWASC8cV
It compiles when using msvc. I also tried to change the if logic in the CMakeLists.txt in the root to include Clang to the MSVC specific settings. Didn't do anything though.

**Comment by dota17** [comment]
Can you tell how you build this library with clang on windows?
Or you can show your CMakeLists.txt.

I had tried many ways to build with clang on windows, but fail.
Now, I am not sure whether it can build with clang on windows?Does it support?

**Comment by tawmoto** [comment]
I am also interested to find out this answer, thanks

**Comment by nlohmann** [comment]
See https://github.com/nlohmann/json/issues/1818#issuecomment-636357613 - trying to reproduce.

**Comment by nlohmann** [comment]
To be fixed with #2259.
