### ISSUE TITLE
does Json sdk cares about dfc dfd utf8 issue?

### ISSUE THREAD

**Issue by issaharnoam** [nlohmann/json#1901]
used case:
json composed on windows by json parser and contains ü character
same json file parsed on mac 

In mac there is DFD and in windows - DFC utf8 encoding for letters like ü etc..
Is json toolkit cares about it? 
Thanks

**Comment by nlohmann** [comment]
This library supports UTF-8.

**Comment by nlohmann** [comment]
Do you need further assistance with this issue?

**Comment by dota17** [comment]
DFD?DFC?
I think you mean NFC and NFC, right?
Related Link: https://en.wikipedia.org/wiki/Unicode_equivalence

I think this library doesn't care about it. It just give you what you give it, and how to display depends on you.

**Comment by nlohmann** [comment]
@issaharnoam Do you need further assistance?

**Comment by issaharnoam** [comment]
Thanks for quick response

**Comment by issaharnoam** [comment]
> UTF-8

**Comment by issaharnoam** [comment]
> @issaharnoam Do you need further assistance?

I wil try to encode ti DFD and parse and see the values. I am not sure about the behavior because I encoded the file on windows and parsed on Mac and I did not see windows utf8
I will doublecheck again....
