### ISSUE TITLE
typo in a comment

### ISSUE THREAD

**Issue by fefe17** [nlohmann/json#1903]
```
single_include/nlohmann/json.hpp:This class implements a recursive decent parser.
```

The parser may also be decent, but it is a recursive descent parser. Note the s. :-)

**Comment by nlohmann** [comment]
Thanks for reporting!

**Comment by nlohmann** [comment]
* * *

### 🔖 Release item

This issue/PR will be part of the next release of the library. This template helps preparing the release notes.

#### Type

- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] ⚡️ Improvement
- [x] 🔨 Further Change
- [ ] 🔥 Deprecated function

#### Description

- Fix typo. #1903

* * *
