### ISSUE TITLE
install Slack app

### ISSUE THREAD

**Issue by aschoenenberg** [nlohmann/json#1904]
Hi,

I like to subscribe in slack this repo. Is it possible @nlohmann to install the slack app for this?

Would be great :-)

**Comment by nlohmann** [comment]
There is a slack at nlohmannjson.slack.com. Or what do you mean with "install the slack app"?

**Comment by dota17** [comment]
https://github.com/nlohmann/json/pull/355#issuecomment-267451492
> Hi everyone, we're almost done!
> 
> @nlohmann, @gnzlbg and I will have a Slack meeting shortly, to discuss the design decisions, and decide where we go from here.
> 
> If you want to join, feel free to send me an email, I'll invite you to the Slack team!
> 
> I'd like to plan it for this weekend, if it fits everyone's agenda. Let me know and I'll post the meeting date on Slack and Github.
> 
> Thanks

Maybe what he wants is to join the Slack team. 
: )
