### ISSUE TITLE
why root_schema be  implemented as unique_ptr in json-validator.cpp，could I use it as shared_ptr?

### ISSUE THREAD

**Issue by kelaicai** [nlohmann/json#1908]
hi! firend, I use original json-validator object in multithread enviroment, but core in second get validator,  and I see the source code,find it pass by  right value reference and use a unique_ptr，i want to know : why use it as a unique_ptr ？ forgive my poor English,thx!

**Comment by nickaein** [comment]
I didn't quite understand the problem but you can cast a `unique_ptr` to `shared_ptr` ([example](https://stackoverflow.com/questions/37884728)).

**Comment by nlohmann** [comment]
Do you mean this project: https://github.com/pboettch/json-schema-validator ?

cc @pboettch

**Comment by pboettch** [comment]
@kelaicai Please open an issue [here](https://github.com/pboettch/json-schema-validator).

If you want to use the validation in different thread, just do so. When validating a JSON-document the validator-instance and the json-document are considered `const`. Nothing is modified. So it is thread-safe.
