### ISSUE TITLE
Compile warnings on MSVC 14.2

### ISSUE THREAD

**Issue by paamand** [nlohmann/json#1911]
After upgrading from Visual Studio 17 to 19 i get the following compile warnings:

`Warning	C26451	Arithmetic overflow: Using operator '-' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '-' to avoid overflow (io.2).`
**.\nlohmann\detail\conversions\to_chars.hpp	993**
(also line 997, 1007, 1009, 1017, 1021, 1036 and 1038)

`Warning	C26444	Avoid unnamed objects with custom construction and destruction (es.84).`
**.\nlohmann\detail\input\json_sax.hpp	443**

`Warning	C28020	The expression '0<=_Param_(1)&&_Param_(1)<=400-1' is not true at this call.`
**.\nlohmann\detail\output\serializer.hpp	804**

`Warning	C26451	Arithmetic overflow: Using operator '+' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '+' to avoid overflow (io.2).`
**.\nlohmann\detail\output\serializer.hpp	810**

`Warning	C26495	Variable 'nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer>::m_type' is uninitialized. Always initialize a member variable (type.6).`
**.\nlohmann\json.hpp	1777**

**Comment by dota17** [comment]
Bad bot

**Comment by dota17** [comment]
1. C26495 in json.hpp
> Warning C26495 Variable 'nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer>::m_type' is uninitialized. Always initialize a member variable (type.6).
.\nlohmann\json.hpp 1777

https://github.com/nlohmann/json/blob/973c52dd4a9e92ede5ca4afe8b3d01ef677dc57f/include/nlohmann/json.hpp#L6474
Unfortunately, I didn't got this warning in my VS2019. And i think the value `m_type` has been initialized.

2. C26444 in json_sax.hpp
> Warning C26444 Avoid unnamed objects with custom construction and destruction (es.84).
.\nlohmann\detail\input\json_sax.hpp 443

I think this is a C26444 false positive.

**Comment by nlohmann** [comment]
Any idea how to proceed here?

**Comment by bhardwajs** [comment]
@nlohmann - I can take a look and send PR. However, I will be using the latest VS 16.5.3. Would that be okay or do you want to check for the specific VS instance?

**Comment by ArtemSarmini** [comment]
VS 16.5 should be compatible with older 16.X.

**Comment by nlohmann** [comment]
Yes, PRs welcome!
