### ISSUE TITLE
std::is_pod is deprecated in C++20

### ISSUE THREAD

**Issue by Predelnik** [nlohmann/json#1913]
Newest msvc preview version already implements warning for this case. While it's not urgent in any way, it might be nice to replace it with either `std::is_standard_layout` or `std::is_trivial` to avoid warnings during compilation with newer standard support.

Here you can find more details on its deprecation:
https://stackoverflow.com/questions/48225673/why-is-stdis-pod-deprecated-in-c20

**Comment by nlohmann** [comment]
Thanks for reporting. `std::is_pod` is used here:

```cpp
template < typename C = CharType,
           enable_if_t < std::is_signed<C>::value and std::is_unsigned<char>::value > * = nullptr >
static CharType to_char_type(std::uint8_t x) noexcept
{
    static_assert(sizeof(std::uint8_t) == sizeof(CharType), "size of CharType must be equal to std::uint8_t");
    static_assert(std::is_pod<CharType>::value, "CharType must be POD");
    CharType result;
    std::memcpy(&result, &x, sizeof(x));
    return result;
}
```

I think replacing this with `std::is_standard_layout` is suitable here, right?

**Comment by Predelnik** [comment]
To be able to do `memcpy` the requirement is `std::is_trivially_copyable` ([stackoverflow link]( https://stackoverflow.com/a/27009291/1269661))

`std::is_trivial` also adds trivial default constructor requirement which might be useful here.

Standard layout however [adds a lot of constraints](https://en.cppreference.com/w/cpp/named_req/StandardLayoutType) I guess for most of them it's a bit strange to be unsatisfied in hypothetical `CharType` but I think since operations done are technically correct the rest can be blamed on user for passing something so unorthodox.

My conclusion is that `std::is_trivial` should be used. But I'm not an expert so it might be nice if someone would confirm my guess.

**Comment by nlohmann** [comment]
I created a branch for this: https://github.com/nlohmann/json/tree/feature/issue1913

**Comment by dota17** [comment]
@stale This issue should be pinned.

@nlohmann, hello.
Is there any new progress? It seems that this issue will be closed by bad bot.

**Comment by nlohmann** [comment]
I have a branch for this an will finish this after my vacation.
