### ISSUE TITLE
char8_t and std::u8string support

### ISSUE THREAD

**Issue by LeonF23** [nlohmann/json#1914]
Hello,
when porting our codebase to std=c++2a the compability with nlohmann::json will break since we use u8"" string literals for assigning strings to json objects.
I tried changing ObjectType's StringType to std::u8string, but that is not working because there are some types hardcoded to char in the json.hpp, for example serializer's `output_adapter_t<char>` (line 14587) and others.

So my questions are:
Is there any native support for char8_t planned in the future?
Are there any known workarounds to add char8_t support by hand right now?

Greetings

**Comment by nlohmann** [comment]
You are right, `std::u8string` is currently not supported. I currently see no blocker in supporting it, but I cannot promise any timeline for the feature. Any help (and PRs) welcome!

**Comment by LeonF23** [comment]
So, just out of curiosity i replaced most of the char occurences with char8_t, and set StringType to std::u8string in the single json.hpp header. It builds successfully but produces garbage at runtime. [Here is the commit for reference, but please do not try this at home.](https://github.com/LeonF23/json/commit/3e7093bbfd71a3be34867b08559ca3a766cf73f9?diff=split)


Iam very  sure that I introduced undefined Behaviour, which is no wonder with such a straigh-forward type replacement (maybe i also replaced way to much, also iam not very familiar with the codebase). I guess it fails somewhere in the dump(..) dump_escaped() decode() area because calls to output_adapter_t<char8_t>::write_characters(...) sometimes overrwrite the beginning of output_adapter's underlying string, even though the function calls an StringType::append or StringType::push_back.

So it is somehow possible to build with char8_t enabled and with a lot of tweaking and tinkering the internal functionality could be kept as it is without any UB.
But for char8_t support that actually can be released a lot more is needed. 

StringType::CharT template parameters would be needed so that it is possible to switch between char and char8_t. Also some detection mechanism, if char8_t is availible, using compiler dependend defines could be usefull.

Some mechanism to allow backwards compability is needed. Therfore this [paper exists](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1423r0.html). There are some recommandations on how the be compatible in both directions. for example a user defined literal "U8(...)" that can switch between char and char8_t would be possible. But iam not quite sure if that would break something for the end users. those decisions have to be taken very carefully. 

I think a lot of the unit test would have to be rewritten. For example a
`CHECK(j["url"] == "https://github.com/nlohmann/json");` as it is right now would throw because there is no comparision operator between char and char8_t.

And i guess there is way more to think about. I just wanted to write down my thoughs, maybe they help some one else to develop a strategy.

**Comment by patrolez** [comment]
Hello,
I was reading Changelog.md which literally includes title of this issue and I believe it should not be closed.
I think this issue should be renamed to `Lack of char8_t and std::u8string support`.

The problem will still be there and will continue to arise as the release date of C++20 was some time ago and the use of its functionalities stabilizes.
