### ISSUE TITLE
Accessing strings (for example in keys or values) without having the lib create a copy of it.

### ISSUE THREAD

**Issue by aguaviva** [nlohmann/json#1916]
I am ok with just having a "const char *" of the string. 

I have tried several times an I haven;t had any luck, all I get are copies.

**Comment by nlohmann** [comment]
Can you provide an example? I currently do not know what you mean exactly.

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

**Comment by alfaunits** [comment]
I feel ya, aguaviva.
I had the use of the same a few times.

If we ask for, say, json_var["name"] we would get a new JSON object, converted to a string.
Being able to instead get a string object, pointing to actual memory inside the json_var, where the vale of the element "name" would reduce memiry need.
Talking about very large JSONs of course.

**Comment by nickaein** [comment]
How about using [`get_ptr()`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_abefbb319df8ed4f8705b4fd4e4dc731c.html#abefbb319df8ed4f8705b4fd4e4dc731c) to get a pointer to the stored object?

**Comment by alfaunits** [comment]
Would that not create a copy of an std::string when we try to use it as a string?

**Comment by nickaein** [comment]
Correct. The following code is one way to test it ([live example](https://wandbox.org/permlink/AVXhXfKQqYrILTd5)):

**Note:** Per documentation, writing data to the returned pointer is discouraged. Take following code just as a demonstration.


```cpp
#include "json.hpp"
#include <iostream>

int main() {

  nlohmann::json j;
  j["key"] = "hello";

  auto p1 = j["key"].get_ptr<std::string *>();
  auto p2 = j["key"].get_ptr<std::string *>();

  std::cout << "Addresses: " << p1 << "," << p2 << std::endl;

  std::cout << "Original:  " << j["key"].get<std::string>() << "," << *p1 << ","
            << *p2 << std::endl;

  *p1 += "1";
  std::cout << "Change p1: " << j["key"].get<std::string>() << "," << *p1 << ","
            << *p2 << std::endl;

  *p2 += "2";
  std::cout << "Change p2: " << j["key"].get<std::string>() << "," << *p1 << ","
            << *p2 << std::endl;

  return 0;
}
```


Typical output:

```
Addresses: 0xe37b20,0xe37b20
Original:  hello,hello,hello
Change p1: hello1,hello1,hello1
Change p2: hello12,hello12,hello12
```

**Comment by alfaunits** [comment]
Hmm, that works for me! Thanks


Not sure about the OP, their needs might be different.

>

**Comment by aguaviva** [comment]
@nlohmann any chance that we could have `const string &myvar =  json["myvar"]` 'to not return a copy as the default behaviour? This would speed up things a lot :)

**Comment by nlohmann** [comment]
`json::operator[]` returns a (const) reference of type `json&`. From there, you can use `get`, `get_ref` or `get_ptr` to access the value for various conversions.

**Comment by aguaviva** [comment]
why not make an operator overload to get json::operator[] return a std::string?

**Comment by nlohmann** [comment]
For several reasons:

- The type of the string is templated. It is `std::string` by default, but it could be another type. That's why the `get_ptr` and `get_ref` functions are do delicate as they allow you to dig into the JSON type which may lead to problems.
- What happens if you write `std::string& mystring = myjson["foo"]`, but `myjson["foo"]` is an integer?

**Comment by aguaviva** [comment]
Alright, thanks for the explanation and for such a good lib :)
