### ISSUE TITLE
Size of binary json representations

### ISSUE THREAD

**Issue by davidglavas** [nlohmann/json#1919]
For the following example, is it correct to say that `v_cbor.size()` is the size (number of bytes) of the CBOR representation for the JSON document `{"compact": true, "schema": 0}`? I guess it's the same for the other binary formats in this library?

    // create a JSON value
    nlohmann::json j = R"({"compact": true, "schema": 0})"_json;

    // serialize to CBOR
    std::vector<std::uint8_t> v_cbor = nlohmann::json::to_cbor(j);

    // 0xA2, 0x67, 0x63, 0x6F, 0x6D, 0x70, 0x61, 0x63, 0x74, 0xF5, 0x66, 0x73, 0x63, 0x68, 0x65, 0x6D, 0x61, 0x00

    // roundtrip
    nlohmann::json j_from_cbor = nlohmann::json::from_cbor(v_cbor);

    std::cout << "CBOR:" << std::endl;
    std::cout << j_from_cbor << std::endl;                                                     // print plaintext
    std::cout << uint8_vector_to_hex_string(v_cbor) << std::endl;                               // print binary representation
    std::cout << "Size (bytes) of binary representation: " << v_cbor.size() << std::endl;
    std::cout << std::endl << std::endl;

**Comment by nlohmann** [comment]
Yes - the result of the binary formats is a vector of bytes, so size() is the right way to query the size.
