### ISSUE TITLE
Is it possible to have template `json::parse` with `noexcept` specifier?

### ISSUE THREAD

**Issue by deiuch** [nlohmann/json#1922]
- Describe what you want to achieve.
Have `noexcept` for `json::parse` methods if the third argument is `false`.

- Describe what you tried.
I've tried to use this method in my exception-free code, but my IDE (especially ReSharper C++ plugin) warned me about unhandled exceptions from calling this function. Also `noexcept` specifier makes optimization passes to be more aggressive.

- Describe which system (OS, compiler) you are using.
Microsoft Windows 10, MSVC (from Microsoft Visual Studio 2017), CMake (from 3.12), Vcpkg (version `2020.01.17-nohash`).

- Describe which version of the library you are using (release version, develop branch).
Version available as the last in `vcpkg` (in library source marked as 3.7.3).

**Comment by deiuch** [comment]
Somehow this was not inserted into issue text, I'll paste it here.

https://github.com/nlohmann/json/blob/6a6790ab68603cfa1ce312e7470a5f6c153cc377/single_include/nlohmann/json.hpp#L20744-L20747

**Comment by deiuch** [comment]
I've found a macro that may affect exception policy of the library.
Is it possible to introduce some macro like `JSON_NOEXCEPT` that will put the corresponding `noexcept` declaration to every function like `json::parse` based on current `JSON_NOEXCEPTION` macro?

https://github.com/nlohmann/json/blob/6a6790ab68603cfa1ce312e7470a5f6c153cc377/single_include/nlohmann/json.hpp#L1747-L1758

**Comment by nlohmann** [comment]
Technically, the parse function is not noexcept, because it allocates memory which can yield `std::bad_alloc`.

**Comment by deiuch** [comment]
Got it, so no more questions :)
But you still may consider this macro (if it has any sense for some function in public API).
