### ISSUE TITLE
C++14 support is not enabled with msvc2015

### ISSUE THREAD

**Issue by Predelnik** [nlohmann/json#1932]
`_HAS_CXX14` is never defined by MSVC
Proof:
https://gcc.godbolt.org/z/5odXyR

Also you may check that [Microsoft STL](https://github.com/microsoft/STL) uses only `_HAS_CXX17`

So second half of check for C++14 version support is incorrect (never triggered):

```cpp
#elif (defined(__cplusplus) && __cplusplus >= 201402L) || (defined(_HAS_CXX14) && _HAS_CXX14 == 1)
```

What it leads to - on older msvc's which was not defining `__cplusplus` properly (at least on msvc2015) C++14 is never treated as supported even though it is supported. Currently it only disables usage of transparent comparator.

Unfortunately it seems there is no correct way to check for C++14 support for msvc since lowest value of their language switch is also `c++14` but more or less it was supported starting from VS2015 and since it is the lowest version library supports, maybe treating C++14 as always supported by msvc is the best option?

**Comment by nlohmann** [comment]
If this is a bug in MSVC, then I am afraid I can do nothing in this library. Any ideas?

**Comment by Predelnik** [comment]
I would not say it's a msvc bug per se, it's just that current check (`_HAS_CXX14` etc.) doesn't mean anything when compiling with msvc. Basically, msvc starting from 2015 supports `c++14` unconditionally with any compilation flags, previous versions probably do not support it.

So in my opinion considering that minimum supported msvc version of the library is 2015, just replacing
```cpp
 || (defined(_HAS_CXX14) && _HAS_CXX14 == 1)
```
with
```cpp
|| defined (_MSC_VER)
```
should be fine.
