### ISSUE TITLE
How to get the object name?

### ISSUE THREAD

**Issue by 3038922** [nlohmann/json#1936]
```
const json userData = {
    {
        "intake",
        {
            {"motor", {
                         {"L", {{"port", 9}, {"test", false}, {"gear", 0}}},
                         {"R", {{"port", 10}, {"test", true}, {"gear", 0}}},
                     }},
            {"ADI", {
                        {"port", 4},
                    }},
            {"pragma", {
                         {"val1", 2600},
                         {"val2", 40},
                         {"val3", 5},
                     }},
        },
    },
};
auto temp=userData ["intake"];
std::cout<<temp.????<<std::endl;
```
I hope he can output '**intake**'.
Which function should I use to get the name of the object name?

**Comment by nlohmann** [comment]
That’s unfortunately not possible. There was an issue in the past, but the solution would have taken a lot of memory overhead.

**Comment by Krzmbrzl** [comment]
Can't the object's name be printed by means of iterators ([doc](https://json.nlohmann.me/features/iterators/#access-object-key-during-iteration))?

From the docs:
```cpp

for (auto it = j.begin(); it != j.end(); ++it)
{
    std::cout << it.key() << " : " << it.value() << std::endl;
}
```
That appears to me as if by iterating over the top-level `json` object and then using the `key()` function on the iterator, you should be able to fetch the desired name :thinking:

**Comment by nlohmann** [comment]
No, the name belongs to the enclosing object rather to the value itself.

**Comment by Krzmbrzl** [comment]
Ah yes, I think I misread the question more towards the direction in which I was searching for something. My bad.
