### ISSUE TITLE
Version of nlohmann-json-dev in debian packages

### ISSUE THREAD

**Issue by epsilonrt** [nlohmann/json#1938]
Hi,
I want to use nlohmann-json-dev in one of my projects. I absolutely want to limit dependencies outside of the APT system.
I note that the packages distributed by the most recent Debian distributions are in version 2.1.1 while the current stable version is version 3.7.3.
Do you know why ?
Regards

**Comment by dota17** [comment]
Emmm, you will find that there are some other packages whose version are not the most recent.
I think it is up to the Debian Team, not for us.

**Comment by epsilonrt** [comment]
Thank you. I just wanted to know if you know the reason, I contact the debian package maintainer.
Have a nice day

**Comment by dota17** [comment]
As i known, for stable.
Here is a related question: [link](https://unix.stackexchange.com/questions/10940/how-to-keep-my-debian-system-with-the-latest-packages).
I hope this can help you.

**Comment by epsilonrt** [comment]
If it can be useful for other people, the person responsible for the package answered me. There are actually 2 different packages on Debian :
```
nlohmann-json-dev - JSON for Modern C++
nlohmann-json3-dev - JSON for Modern C++
```
One for version 2 and another for version 3, it had to be !

**Comment by LocutusOfBorg** [comment]
FYI I asked to remove the old one one year ago, so next stable won't have it anymore
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931674
it is still in stable and oldstable.
