### ISSUE TITLE
Nested objects serialize/deserialize

### ISSUE THREAD

**Issue by SadE54** [nlohmann/json#1941]
Hi ,

I have to write a config file from a node editor with something like this

struct Node
{
   int id;
   string name;
}

struct Pin
{
    int id;
    Node* node;
}

struct Link
{
    int id;
    Pin*  start;
    Pin* end;
}

struct Config
{
   std::vector<Node> Nodes;
   std::vector<Pin> Pins;
   std::vector<Link> Links;
}

How can i serialize the topover object Config ? and deserialize ?
Thanks!

**Comment by nickaein** [comment]
You just have to provide `from_json` and `to_json` functions for each type [as mentioned in README](https://github.com/nlohmann/json#arbitrary-types-conversions).

Also relevant: https://github.com/nlohmann/json/issues/1648
