### ISSUE TITLE
Adding "examples" section for real-life usages

### ISSUE THREAD

**Issue by nickaein** [nlohmann/json#1953]
Currently README provides a minimal set of examples about how the library can be used. While It covers most of basic functionality, some users occasionally have trouble in using the library in more complex situations. Here are some recent examples: #1930, #1874, #1892, #1931.

A user can eventually figure it out by reading the documentation, but having some examples for various use-cases which are closer to real-life scenarios can be very helpful in using the library "correctly" and can also reduce the number of opened issues related to usage problems.

Any thoughts or suggestions on adding such section to the library?

**Comment by nlohmann** [comment]
Good point. There is already an example for each function in the Doxygen documentation. I am a bit worried that adding another source of documentation may be confusing.

**Comment by dota17** [comment]
I think we can add these source into [github wiki](https://help.github.com/en/github/building-a-strong-community/about-wikis).
In wiki, we can tell that the examples of complex situations and how to build or tips.

**Comment by nlohmann** [comment]
The Wiki is intentionally switched off for this project as it would be another source of information which could be even more confusing.

**Comment by nickaein** [comment]
Whoops. I totally missed [docs/examples](https://github.com/nlohmann/json/tree/develop/doc/examples) directory. So this is where all example codes for the documentation is located.

Regarding the examples, I think there are two points to consider:

1. My hunch is that users usually look for `examples` directory in root of a project and if they don't find one, they probably assume the project doesn't provide examples. It would be nice if we can find a workaround it. One option is to add an `examples` directory as a symbolic link to `docs/examples`. [git supports symbolic links](https://stackoverflow.com/questions/954560), but I'm not sure if it is portable.

* The current examples are tailored for the documentation of a specific feature. I believe having examples for more complex use-cases can be helpful too, to demonstrate how multiple features can be used in mix. These examples can be placed inside `docs/examples` too, while adding a "Samples" section in the documentation to reference them.
