### ISSUE TITLE
Possible memory leak on push_back

### ISSUE THREAD

**Issue by davide9** [nlohmann/json#1971]
I'm experiencing a memory leak when using push_back to add strings to a json object

Steps to reproduce:
- Use a custom allocator to track memory allocations
- Create a json object as array: json myJson = json::array_t{};
- Add a string type object with push_back: myJson.push_back(String{"Hello leaking world"});
- Destroy the json instance.
- Experience the leak.

I'm using Visual Studio 2017 on Windows 10, compiling with standard Debug configuration in x64
My latest synch on this branch was on 28/02/2020 at 15:20 CET.

I've (probably) fixed the issue by removing (on the single header file) the line 19426: val.m_type = value_t::null; from the function void push_back(basic_json&& val).

From my debugging, the issue comes from the fact that the m_value.array->push_back(std::move(val)); is invoking the basic_json(const basic_json&) instead of the basic_json(basic_json&&), which creates a copy of the source value that should still be properly delete by the allocator. My fix shouldn't affect the final result since, if the move constructor is invoked in the push_back of 19422, the move constructor will take care of marking the type of the source basic_json as null.

Hope this will be helpful!

Cheers,

Davide.

**Comment by ArtemSarmini** [comment]
@davide9 could you provide minimal reproducible example?

**Comment by davide9** [comment]
`#include "json.hpp"

#include <string>
#include <map>
#include <unordered_map>
#include <iostream>
#include <cstdlib>

class String : public std::string
{
public:

	String()
		: std::string()
	{
		s_instanceCount++;
	}
	String(const String& str) : std::string(str)
	{
		s_instanceCount++;
	}
	String(const String& str, size_type pos, size_type len = std::string::npos)
		: std::string(str, pos, len)
	{
		s_instanceCount++;
	}
	String(const char* s)
		: std::string(s)
	{
		s_instanceCount++;
	}
	String(const char* s, size_type n)
		: std::string(s, n)
	{
		s_instanceCount++;
	}
	String(const_iterator first, const_iterator last)
		: std::string(first, last)
	{
		s_instanceCount++;
	}
	String(size_type n, char c)
		: std::string(n, c)
	{
		s_instanceCount++;
	}
	String(String&& str)
		: std::string(std::move(str))
	{
		s_instanceCount++;
	}

	~String() { s_instanceCount--; }

	static int s_instanceCount;	
};

int String::s_instanceCount = 0;

void* AllocatorAlloc(unsigned int _count, unsigned int _align)
{
	return _aligned_malloc(_count, _align);
}
void AllocatorFree(void* _ptr)
{
	_aligned_free(_ptr);
}

template <typename T>
struct Allocator
{
	typedef std::remove_const_t<T>	value_type;
	typedef	value_type* pointer;
	typedef value_type& reference;
	typedef const value_type* const_pointer;
	typedef const value_type& const_reference;
	typedef	size_t		size_type;
	typedef	ptrdiff_t		difference_type;
	template <typename U>	struct rebind { typedef Allocator<U> other; };

	Allocator()							throw() {}
	Allocator(const Allocator&)			throw() {}
	template <typename U>	Allocator(const Allocator<U>&)		throw() {}
	~Allocator()						throw() {}

	pointer			address(reference oRef)				const { return &oRef; }
	const_pointer	address(const_reference oRef)		const { return &oRef; }

	pointer allocate(size_type iCount) { return (pointer)AllocatorAlloc(((unsigned int)iCount) * sizeof(T), alignof(T)); }
	pointer allocate(size_type iCount, const void*) { return allocate(iCount); }

	void deallocate(pointer pBuf, size_type) { AllocatorFree(pBuf); }

	size_type max_size()								const	throw() { size_type iCount = (size_type)(-1) / sizeof(T); return 0 < iCount ? iCount : 1; }

	void construct(pointer pT, const T& oT) { ::new ((void*)pT) T(oT); }
	void destroy(pointer pT) { pT->~T(); }

private:
};

using Json = ::nlohmann::basic_json<std::map, std::vector, String, bool, int, unsigned int, float, Allocator, ::nlohmann::adl_serializer>;

int main()
{
	{
		Json json;
		json["test"] = Json::array_t{};
		json["test"].push_back("Leak");
	}
	std::cout << String::s_instanceCount << std::endl; // notice how s_instanceCount = 1 when Allocator is not std::allocator
	return 0;
}`

**Comment by davide9** [comment]
`
#include "json.hpp"

#include <string>
#include <map>
#include <unordered_map>
#include <iostream>
#include <cstdlib>

class String : public std::string
{
public:

	String()
		: std::string()
	{
		s_instanceCount++;
	}
	String(const String& str) : std::string(str)
	{
		s_instanceCount++;
	}
	String(const String& str, size_type pos, size_type len = std::string::npos)
		: std::string(str, pos, len)
	{
		s_instanceCount++;
	}
	String(const char* s)
		: std::string(s)
	{
		s_instanceCount++;
	}
	String(const char* s, size_type n)
		: std::string(s, n)
	{
		s_instanceCount++;
	}
	String(const_iterator first, const_iterator last)
		: std::string(first, last)
	{
		s_instanceCount++;
	}
	String(size_type n, char c)
		: std::string(n, c)
	{
		s_instanceCount++;
	}
	String(String&& str)
		: std::string(std::move(str))
	{
		s_instanceCount++;
	}

	~String() { s_instanceCount--; }

	static int s_instanceCount;	
};

int String::s_instanceCount = 0;

void* AllocatorAlloc(unsigned int _count, unsigned int _align)
{
	return _aligned_malloc(_count, _align);
}
void AllocatorFree(void* _ptr)
{
	_aligned_free(_ptr);
}

template <typename T>
struct Allocator
{
	typedef std::remove_const_t<T>	value_type;
	typedef	value_type* pointer;
	typedef value_type& reference;
	typedef const value_type* const_pointer;
	typedef const value_type& const_reference;
	typedef	size_t		size_type;
	typedef	ptrdiff_t		difference_type;
	template <typename U>	struct rebind { typedef Allocator<U> other; };

	Allocator()							throw() {}
	Allocator(const Allocator&)			throw() {}
	template <typename U>	Allocator(const Allocator<U>&)		throw() {}
	~Allocator()						throw() {}

	pointer			address(reference oRef)				const { return &oRef; }
	const_pointer	address(const_reference oRef)		const { return &oRef; }

	pointer allocate(size_type iCount) { return (pointer)AllocatorAlloc(((unsigned int)iCount) * sizeof(T), alignof(T)); }
	pointer allocate(size_type iCount, const void*) { return allocate(iCount); }

	void deallocate(pointer pBuf, size_type) { AllocatorFree(pBuf); }

	size_type max_size()								const	throw() { size_type iCount = (size_type)(-1) / sizeof(T); return 0 < iCount ? iCount : 1; }

	void construct(pointer pT, const T& oT) { ::new ((void*)pT) T(oT); }
	void destroy(pointer pT) { pT->~T(); }

private:
};

using Json = ::nlohmann::basic_json<std::map, std::vector, String, bool, int, unsigned int, float, Allocator, ::nlohmann::adl_serializer>;

int main()
{
	{
		Json json;
		json["test"] = Json::array_t{};
		json["test"].push_back("Leak");
	}
	std::cout << String::s_instanceCount << std::endl; // notice how s_instanceCount = 1 when Allocator is not std::allocator
	return 0;
}
`

**Comment by ArtemSarmini** [comment]
It is indeed related, thanks for tracking. It's still a bug though.

**Comment by ArtemSarmini** [comment]
I'll provide pull request soon, it seems only one line (that null assignment) needs to be changed.

**Comment by ArtemSarmini** [comment]
By the way, confirmed on gcc 9.3, so it isn't msvc-specific.
