### ISSUE TITLE
JSON patch diff for op=add formation is not as per standard (RFC 6902)

### ISSUE THREAD

**Issue by harishmurkal** [nlohmann/json#1983]
Hi,

When result_json = diff(source, target) is called with 

source = { "foo": [ "bar", "baz" ] }
dest = {"foo": [ "bar", "baz", "baa" ]}

NOTE: actual function is 

    static basic_json diff(const basic_json& source, const basic_json& target,
                           const std::string& path = "")

Obtained JSON is 
result_json = 
   [
     { "op": "add", "path": "/foo/1", "value": "qux" }
   ]

This is wrong as per RFC 6902 (refer section 4.1)
https://tools.ietf.org/html/rfc6902#page-4

Expected is 
result_json = 
   [
     { "op": "add", "path": "/foo/-", "value": "qux" }
   ]

Where is the problem here?

Or is it we need to interchange source and target to generate diff?
Waiting for your response.

Thanks and Regards,
Harish M

**Comment by dota17** [comment]
Hi @harishmurkal IMO, there is no problem here.
if 
```json
source = { "foo": [ "bar", "baz" ] }
dest = {"foo": [ "bar", "baz", "baa" ]}
```
the new element `baa` in the array is at the end of the array, so these two json patches below have the same effect on the `source` according to RFC6902:
1.
```json
[
{ "op": "add", "path": "/foo/-", "value": "baa" }
]
```
2.
```json
[
{ "op": "add", "path": "/foo/2", "value": "baa" }
]
```

**Comment by harishmurkal** [comment]
Hi @dota17, 

Thanks for responding. Unfortunately, the receiver of the PATCH request is throwing error saying that the patch is trying to access element that is out-of-range. In the example given, source "foo" has two elements (index 0 and 1). The PATCH informs to add an element at the index 2, technically, it's out-of-range.

### I've pasted some snippet from the standards, RFC 6902 (which indicates that there is an issue): 


An element to add to an existing array - whereupon the supplied
      value is added to the array at the indicated location.  Any
      elements at or above the specified index are shifted one position
      to the right.  The specified index **MUST NOT** be greater than the
      number of elements in the array.  If the "-" character is used to
      index the end of the array (see [RFC6901]), this has the effect of
      appending the value to the array.


Thanks and Regards,
Harish M

**Comment by dota17** [comment]
Actually, the number of elements in that array is 2, so the index 2 is not greater than it, this is consistent with what is stated in the RFC 6902. And I test some examples online, the result is no problem.

**Comment by nlohmann** [comment]
Thanks for reporting. I'll check.

**Comment by nlohmann** [comment]
I added a fix, see https://github.com/nlohmann/json/tree/feature/issue1983.

Is this OK for you?

**Comment by dota17** [comment]
> I added a fix, see https://github.com/nlohmann/json/tree/feature/issue1983.
> 
> Is this OK for you @harishmurkal @dota17?

Yes, I think it fixes the problem.
