### ISSUE TITLE
reading int number and string number

### ISSUE THREAD

**Issue by Behrouz-m** [nlohmann/json#1986]
Hi. I receive a JSON from 2 different places that contain a number.  one of them returns JSON with a number and the other returns the same JSON with a number with quotes. like this:

**{"state": 0}**

or:

**{"state": "0"}**

the problem is how can I read them with no problem?

**Comment by nlohmann** [comment]
What is your exact issue? Deserialization (also know as parsing) is described here: https://github.com/nlohmann/json#serialization--deserialization

**Comment by Behrouz-m** [comment]
my problem is that `state` can be `number` and also `string` that contains number.  I want to assign this number to int variable but it is not possible to read it using normal assignment.
```c++
json jp = R"({"state": "10"})"_json;
int state = jp["state"]; // return 0 instead of value 10

json jp = R"({"state": 10})"_json;
int state = jp["state"]; // return 10 becuase it is number not string
```

**Comment by nlohmann** [comment]
You can call `jp["state"].is_number()` or `jp["state"].is_string()` to check the type.

**Comment by Behrouz-m** [comment]
I know that. I am looking for an easier way instead of checking types for every number type in json. what about `jp.get<int>("state")` ?

**Comment by nlohmann** [comment]
The library does not provide such conversions.
