### ISSUE TITLE
Compiler Errors under VS2019 in Appveyor CI

### ISSUE THREAD

**Issue by dota17** [nlohmann/json#2009]
Recently, Appveyor CI had a lot of compiler errors under VS2019.
Since 3/20, all pr have the same compiler errors:
```
C:\projects\json\test\src\unit-conversions.cpp(1387): message : see reference to function template instantiation 'ValueType nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>::get<std::valarray<std::string>,std::valarray<std::string>,0>(void) noexcept(false) const' being compiled [C:\projects\json\test\test-conversions.vcxproj]
          with
          [
              ValueType=std::valarray<std::string>
          ]
...
```
#2004  just added `wsjcpp.yml`, and it got the same errors.

- What is the expected behavior?
Appveyor CI should pass.

**Comment by garethsb-sony** [comment]
Resolved by #2008, I think?

**Comment by dota17** [comment]
> Resolved by #2008, I think?

Yes, I had checked and tested in my fork repo.
After merging the PR, the Appveyor CI will pass.

Thanks for your help : ) .
This issue can be closed when the PR #2008 is merged.

**Comment by nlohmann** [comment]
#2008 was merged. Any ideas on this?

**Comment by dota17** [comment]
No. This issue can be closed.
