### ISSUE TITLE
GNU PREREQ Error with gcc 9.3.0

### ISSUE THREAD

**Issue by Bose90** [nlohmann/json#2015]
- Describe what you want to achieve.
I am trying to run some production code with gcc 9.3.0 in Cygwin(64bit) and want to get it compile successfully. My same code runs fine with gcc version 4.8.x, but not with the latest gcc version.
Below error i am getting continously in cygwin console.
/usr/include/_ansi.h:24:19: error: missing binary operator before token "("
   24 | #if __GNUC_PREREQ (3, 3)
      |                   ^
/usr/include/_ansi.h:72:19: error: missing binary operator before token "("
   72 | #if __GNUC_PREREQ (3, 1)
- Describe what you tried.
i have tried many ways and even searched in google to fix that issue, but nothing helped me.
- Describe which system (OS, compiler) you are using.
I have windows 10 machine with 64bit Cygwin and gcc/g++ installed is 9.3.0 version.
- Describe which version of the library you are using (release version, develop branch).
gcc - 9.3.0
g++ 9.3.0
please help me, it's been 10days i am trying every way to fix this

**Comment by dota17** [comment]
Maybe one of your head file name in your code is the same as the name of a file in the gcc 9.3.0 in Cygwin.

**Comment by Bose90** [comment]
thanks :) .. there's one more error i am encoutering 
Error"../../../../ut/CppUTest/include/CppUTestExt/MockSupport.h:40: error: default argument for ‘MockFailureReporter* failureReporterForThisCall’ has type ‘void*’

Here's the Prototype of function
MockSupport& mock(const SimpleString& mockName = "", MockFailureReporter* failureReporterForThisCall = NULL);

Defination
MockSupport& mock(const SimpleString& mockName, MockFailureReporter* failureReporterForThisCall)
{
	MockSupport& mock_support = (mockName != "") ? *global_mock.getMockSupportScope(mockName) : global_mock;
	mock_support.setActiveReporter(failureReporterForThisCall);
	return mock_support;
}

MockSupport::MockSupport()
	: strictOrdering_(false), standardReporter_(&defaultReporter_), ignoreOtherCalls_(false), enabled_(true), lastActualFunctionCall_(NULL), tracing_(false)
{
	setActiveReporter(NULL);
}

MockSupport::~MockSupport()
{
}
I am totally clue less what's this error is ?

**Comment by nlohmann** [comment]
I can see no connection to this library.
