### ISSUE TITLE
including another file

### ISSUE THREAD

**Issue by RiccardoRossi** [nlohmann/json#2016]
- Describe what you want to achieve.

I would like to include another json file within my json. Is there a way of doing it?

- Describe what you tried.

the schema syntax would be something like

~~~json
$ref:"/path/to/my/file.json"
~~~

- Describe which system (OS, compiler) you are using.
any

- Describe which version of the library you are using (release version, develop branch).
latest

**Comment by dota17** [comment]
This library didn't support Json Reference now, so I'm afraid it can't do that.

**Comment by RiccardoRossi** [comment]
ok, provided that we implement it within our wrapper around nlohmann (so that is it not an implementation problem) could u hint about what would be the "jsonic" way of achieving what we seek? 

I mean, implementing our own special handling of "$ref" would be a good choice or should we go for a different approach to be able to include one json inside the other

**Comment by nlohmann** [comment]
@dota17 is right, the library does not support this.

**Comment by RiccardoRossi** [comment]
Dear @nlohmann @dota17 i appreciate that (i also read it in your docs).

We have a wrapper on the top of your lib which allows us to implement extra stuff. I was asking for a hint of what you think should be the best strategy to achieve it, not from a programming point of view but rather from a "json-organizational" point of view.

**Comment by nlohmann** [comment]
You could do it either inside the parser writing your own [SAX interface](https://nlohmann.github.io/json/structnlohmann_1_1json__sax.html) or you do it as post processing step after parsing. For the former, you may want to have a look at the `json_sax_dom_parser` (https://github.com/nlohmann/json/blob/develop/include/nlohmann/detail/input/json_sax.hpp#L145) parser. With some work, you should be able to add the required logic to replace `$ref` values.
