### ISSUE TITLE
CppUTest/include/CppUTestExt/MockSupport.h:40: error: default argument for ‘MockFailureReporter* failureReporterForThisCall’ has type ‘void*’

### ISSUE THREAD

**Issue by Bose90** [nlohmann/json#2017]
I am trying to compile TestCases for my project code and getting below errors:

CppUTest/include/CppUTestExt/MockSupport.h:40: error: default argument for ‘MockFailureReporter* failureReporterForThisCall’ has type ‘void*’

Function Prototype:
=================
MockSupport& mock(const SimpleString& mockName = "", MockFailureReporter* failureReporterForThisCall = NULL);

Defination:
=================
MockSupport& mock(const SimpleString& mockName, MockFailureReporter* failureReporterForThisCall)
{
	MockSupport& mock_support = (mockName != "") ? *global_mock.getMockSupportScope(mockName) : global_mock;
	mock_support.setActiveReporter(failureReporterForThisCall);
	return mock_support;
}

MockSupport::MockSupport()
	: strictOrdering_(false), standardReporter_(&defaultReporter_), ignoreOtherCalls_(false), enabled_(true), lastActualFunctionCall_(NULL), tracing_(false)
{
	setActiveReporter(NULL);
}

MockSupport::~MockSupport()
{
}

Class :
================
class MockSupport
{
public:
	MockSupport();
	virtual ~MockSupport();

	virtual void strictOrder();
	virtual MockFunctionCall& expectOneCall(const SimpleString& functionName);
	virtual MockFunctionCall& expectNCalls(int amount, const SimpleString& functionName);
	virtual MockFunctionCall& actualCall(const SimpleString& functionName);
	virtual bool hasReturnValue();
	virtual MockNamedValue returnValue();
	virtual int intReturnValue();
	virtual const char* stringReturnValue();
	virtual double doubleReturnValue();
	virtual void* pointerReturnValue();
        etc etc......

**Comment by nickaein** [comment]
Hi!

Like #2015, this is irrelevant to this library.  If this is related to [CppUTest](https://github.com/cpputest/cpputest) library, you can report this issue to them.
