### ISSUE TITLE
How to create patch for merge_patch input ?

### ISSUE THREAD

**Issue by JeremieFiniel** [nlohmann/json#2018]
Hello,

I need to generate a patch like the one from merge_patch example :
```
// the patch
json patch = R"({
            "title": "Hello!",
            "phoneNumber": "+01-123-456-7890",
            "author": {
                "familyName": null
            },  
            "tags": [
                "example"
            ]   
        })"_json;
```

Is there an existing function to generate this ?
I tried diff function but it create a list of actions to apply, so not what I need.

I search somthing working like this:
``` c++
// the source document
json source = R"(
    {
        "baz": "qux",
        "foo": "bar"
    }
)"_json;

// the target document
json target = R"(
    {
        "baz": "boo",
        "hello": [
            "world"
        ]
    }
)"_json;

// create the patch
json patch = json::diff(source, target);
```
Where patch will be
```
{
    "baz": "boo",
    "foo": null,
    "hello": [
        "world"
    ]   
}
```

Thank you for your help.

**Comment by nickaein** [comment]
I don't believe this is currently supported out of the box. The library supports *applying* [JSON Merge Patches](https://github.com/nlohmann/json#json-merge-patch) through [`merge_patch‍()`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a7c43ed2a3004c1fa9543913f37b9fca9.html#a7c43ed2a3004c1fa9543913f37b9fca9) function, but there is no counterpart "merge_diff" function to generate one. There are some considerations before implementing a general-purpose one (e.g. how to handle `null` values in source).

**Comment by nlohmann** [comment]
@nickaein is right.

**Comment by dota17** [comment]
Is there a plan to support this case?

**Comment by nlohmann** [comment]
There is no real specification for this. Merge requests are welcome!
