### ISSUE TITLE
Extra backslashes in nested json

### ISSUE THREAD

**Issue by machadors** [nlohmann/json#2020]
There is an extra backslash when adding nested json.

This operations 
`json foo;`
`foo["key"] ="{\"hey\":\"hou\"}";`
`std::string result = foo.dump();`

gives 
`result = "{\"key\":\"{\\\"hey\\\":\\\"hou\\\"}\"}"`
with an extra backslashes in the nested json.

Is this a bug or there is another way to adding nested json ?

PD: This is my first ever github question, sorry in advance about format and so

**Comment by sanblch** [comment]
You need to explicitly show json type like
`foo["key"] = json::parse("{\"key\":\"hou\"}");`

**Comment by machadors** [comment]
Yes, I have. Thanks for the help!
