### ISSUE TITLE
Different JSON printouts for empty dictionary on Linux and Mac.

### ISSUE THREAD

**Issue by canaknesil** [nlohmann/json#2026]
- What is the issue you have?

When I create JSON string with this statement `json j = {{}};` and print it, `[null]`is printed on Linux, while `[{}]` is printed on Mac. I think the Linux one is erroneous.

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

`main.cpp`:
```
#include "json.hpp"
#include <iostream>

using json = nlohmann::json;
using namespace std;

int main()
{
  json j = {{}};
  cout << j << endl;

  return 0;
}
```

Compiled with `g++ -std=c++11 main.cpp`.

- What is the expected behavior?

The expected behavior is that both printouts should be `[{}]`.

- And what is the actual behavior instead?

I get `[null]` when I run the same code on Linux.

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

Linux operating system: Ubuntu 18.04.4 LTS  
Linux compiler: g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

Mac operating system: macOS Catalina Version 10.15.3  
Mac compiler: Apple clang version 11.0.0 (clang-1100.0.33.17)

- Did you use a released version of the library or the version from the `develop` branch?

I am using release version 3.7.3.

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

No error while compilation.

**Comment by nlohmann** [comment]
This is a known issue that the compilers (GCC and Clang) interpret the braces differently. There is little I can do about this. If you want the JSON `[{}]`, then the safest would be `json::array(json())` or `"[{}]"_json`. Sorry about the inconvenience.

**Comment by t-b** [comment]
@nlohmann Do you have a link for that known issue?

**Comment by nlohmann** [comment]
Latest is #2046 which also works on a solution.
