### ISSUE TITLE
Notes about dump function

### ISSUE THREAD

**Issue by MisterVento3** [nlohmann/json#2027]
Hi, while compiling my project I am getting many those notes: 
`note: see reference to function template instantiation 'std::basic_string<char,std::char_traits<char>,std::allocator<char>> nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>::dump(const int,const char,const bool,const nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>::error_handler_t) const' being compiled`. Earlier I was compiling my project on windows 7 and it was fine, now i am on windows 10 and i have those notes. It is a bit annoying because it is thousands of this. I am using VS Code, custom build system based on MSVC 19.25.2861 x64 and dev branch of this library. Any solution for that?
Best regards, Aleksander.

**Comment by nlohmann** [comment]
Do you have a complete error message, including a line number?

**Comment by MisterVento3** [comment]
Here is full error: `...\external\json\include\nlohmann/json.hpp(8104): note: see reference to function template instantiation 'std::basic_string<char,std::char_traits<char>,std::allocator<char>> nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>::dump(const int,const char,const bool,const nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>::error_handler_t) const' being compiled` additionally I am compiling it using c++17, but earlier I was compiling it in this standard too.

**Comment by nlohmann** [comment]
Thanks the line in question is the `return` in

```cpp
/// hash value for JSON objects
template<>
struct hash<nlohmann::json>
{
    /*!
    @brief return a hash value for a JSON object

    @since version 1.0.0
    */
    std::size_t operator()(const nlohmann::json& j) const
    {
        // a naive hashing via the string representation
        const auto& h = hash<nlohmann::json::string_t>();
        return h(j.dump());
    }
};
```

Any ideas how to fix this?

**Comment by ArtemSarmini** [comment]
@MisterVento3 please provide full log with all notes.
