### ISSUE TITLE
Is here any elegant way to combine serialization and deserialization code?

### ISSUE THREAD

**Issue by NukeBird** [nlohmann/json#2028]
I know everything can be much easier with reflection, but sadly C++ doesn't have it

When I'm writing code I noticed I'm repeating myself, serialization and deserialization looks very similar

How can I serealize and deserialize things in elegant way? For example lets say we want to serialize this:
```
struct Human
{
std::string name;
int age;
};
```
and then deserialize it back. As I said earlier, if it's possible I wanna combine serialization and deserialization code 

thanks for your help in advance!

**Comment by NukeBird** [comment]
black macro magic?

**Comment by nlohmann** [comment]
Yes. We have a macro for simplifying the enum conversion, see https://github.com/nlohmann/json#specializing-enum-conversion. If you have an idea to achieve something similar, please let me know!

**Comment by nlohmann** [comment]
This issue is fixed in #2175.
