### ISSUE TITLE
How to parse big decimal data

### ISSUE THREAD

**Issue by YXQ212526** [nlohmann/json#2036]
Hi nlohmann,
 I want to know how to parse data like this:
![image](https://user-images.githubusercontent.com/46663477/79136339-6ee87e00-7de3-11ea-8b5c-0125a8a6cb9d.png)
I use the parse () function to parse the original string and use ["data"] [0] ["amount"] to get the value,but I can't get accurate data, what I got is 7.953084699036454 instead of 7.953084699036454431
Looking forward to your reply, thanks!

**Comment by nlohmann** [comment]
The number `7.953084699036454431` cannot be expressed exactly by a 64 bit double, see https://float.exposed/0x401fcff56f72b7e2. The closest you can get is the number with hex representation `0x401fcff56f72b7e2`. For this number, `7.953084699036454` is the shortest decimal representation. Therefore, this is used by the library.

**Comment by nlohmann** [comment]
Related issues: #1580 #1698

**Comment by YXQ212526** [comment]
Thx for your reply 👍
