### ISSUE TITLE
SAX API uses unsigned std::size_t but  -1 if element size is not known;

### ISSUE THREAD

**Issue by steven-varga** [nlohmann/json#2037]
In the SAX API `std::size_t` defines the size, however in the documentation `-1` a different type signals  unknown size.  Did I overlook something?

**Comment by nlohmann** [comment]
What is the exact question? Indeed, if the size is known during parsing, a size can be passed to the `start_array()` or `start_object()` functions. If it is unknown, `std::size_t(-1)` is passed (just similar to `std::basic_string::npos`.

**Comment by steven-varga** [comment]
Thanks for explaining. I was not aware of this technique and was surprised to see an unexpected high value with `std::size_t` when took your library for a test run. Sorry for the noise!
