### ISSUE TITLE
How to parse multiple line value ?

### ISSUE THREAD

**Issue by stfzy** [nlohmann/json#2039]
- Describe what you want to achieve.
Just like this string  
"{"a" : 0, "b" : "cccccccc
                              ccccccccccc"}"

when calling json::parse it will throw a exception .

- Describe what you tried.

- Describe which system (OS, compiler) you are using.

- Describe which version of the library you are using (release version, develop branch).

**Comment by nlohmann** [comment]
Having unescaped newline characters is invalid JSON. This would be valid:

```json
{"a" : 0, "b" : "cccccccc\nccccccccccc"}
```
