### ISSUE TITLE
How to check if a key exists without silently generating null objects on the path

### ISSUE THREAD

**Issue by Survivor6666** [nlohmann/json#2041]
I have a deep nested JSON data model with a lot of optional keys and optional sub- structures.
When trying to read a non-existing optional key in a not yet existing path the library silently creates this path. When parts of the branch are not existing 'null' keys / 'null' structures are silently generated into the JSON model.

Even checking for a key generates the elements on its path:
```
...
if (jm["Elements"]["Comments"].contains("Comment")
{ /* Key is existing */
   bOk = !FALSE;
}
...
```
This generates following JSON output:
```
{
   "Elements": {
      "Comments": null
   }
}
```
I tried also the 'find' method with the same result. Addressing a non-existing key generates it.
To check each sub-level with 'contain' or 'find' before accessing the next sub-key is not a real option
because the nesting depth is 10 and the model contains a few thousand 1000 optional keys.

Is there any hint how to check if a key exists without checking each key on its path?

Any help is welcome
Christian

**Comment by nlohmann** [comment]
The [`contains`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a9286acdc0578fc66e9346323e69fc0e3.html#a9286acdc0578fc66e9346323e69fc0e3) function does that.

**Comment by Survivor6666** [comment]
I used the contains method in the example above. The JSON object was initially empty .
Checking with 'contains' in the not before existing ["Elements"]["Comments"] 'path' for the key ["Comment"] generates the content of the JSON output above including the "Comments": null  pair.

I could check step-by-step if ["Elements"] exists, then if ["Comments"] exists and finally if ["Comment"] exists. My hope is that I can check for the last key without generating the others.
My model is really huge and this step-by-step generates many lines of code.

**Comment by nlohmann** [comment]
You mix `operator[]` and `contains`. The former does create elements, the latter does not.

You need to go

```cpp
if (jm.contains("Elements") and jm["Elements"].contains("Comments") and jm["Elements]["Comments"].contains("Comment")
{ /* Key is existing */
   bOk = !FALSE;
}
```

Alternatively, you may want to try JSON Pointers:

```cpp
if (jm.cointains("/Elements/Comments/Comment"_json_pointer)
{...}
```

**Comment by Survivor6666** [comment]
Json Pointer is the solution :-)

if (jm.cointains("/Elements/Comments/Comment"_json_pointer)
{...}

The first proposal needs to be slightly modified.
The tests in the if condition are all called even if the first test (jm.contains("Elements")) is FALSE.
So the following tests generate the keys. Nested 'if' calls would work.

Ok, from today Json pointers are my friends.
Thanks for the lightspeed fast solution.

Christian
