### ISSUE TITLE
Crash when parse big jsonfile

### ISSUE THREAD

**Issue by oskycar** [nlohmann/json#2042]
- What is the issue you have?
I had gened a 5.8M json file.  when I parse it use nlohmann/json,  it crashed!.

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

`nlohmann::json jobj = nlohmann::json::parse(file);`

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?
MacOS 10.15.3, Use Xcode 11.3.1 

- Did you use a released version of the library or the version from the `develop` branch?
use released version 3.6.1,   I also tried latesed version 3.7.3, it crashed too.

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

the output error message:
`libc++abi.dylib: terminating with uncaught exception of type nlohmann::detail::parse_error: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: '/'`

I had upload the json file url:  https://www.dropbox.com/s/5wsfcd6p06jeckk/out.json?dl=0

**Comment by nlohmann** [comment]
Are you sure it is exactly that file? The parser error states that there was a `/` read. Can you make sure the file is read from the beginning?

**Comment by oskycar** [comment]
> Are you sure it is exactly that file? The parser error states that there was a `/` read. Can you make sure the file is read from the beginning?

o...，maybe I made a mistake, I passed the file path to it, like this:
`nlohmann::json jobj = nlohmann::json::parse("/tmp/a.json");`

when I follow the example code, It works very well.
`std::ifstream i("/Users/allenyang/Desktop/out.json");
    nlohmann::json j;
    i >> j;`

so It can only pass the file content to it ?

**Comment by ArtemSarmini** [comment]
This function expects a string to parse, not a path to some file.

**Comment by nlohmann** [comment]
You can pass an `std::ifstream` to the `parse` function to read from a file. If you pass a string, it is interpreted as JSON text, not as a filename.

**Comment by nlohmann** [comment]
@oskycar Do you need further assistance?

**Comment by oskycar** [comment]
> @oskycar Do you need further assistance?

thank you very much.  I had no more questions.

**Comment by oskycar** [comment]
> @oskycar Do you need further assistance?

we can close this  issue.  Thanks for your attention.
