### ISSUE TITLE
Confused as how I can extract the values from the JSON object.

### ISSUE THREAD

**Issue by jcracine** [nlohmann/json#2055]
- Describe what you want to achieve.
I want to retrieve data from a JSON object.
Ex: 
```
{
    "results": [
        {
            "series": [
                {
                    "columns": [
                        "time",
                        "value"
                    ],
                    "name": "test",
                    "values": [
                        [
                            1587405996298,
                            10
                        ],
                        [
                            1587406122630,
                            10
                        ]
                    ]
                }
            ],
            "statement_id": 0
        }
    ]
}
```

- Describe what you tried.
I've read the README section to understand better how to extract data from a JSON object, but I'm still confused on how I can do so. I tried `at()` or `get()` but can't seems to get to easily retrieve values like "name" or "columns".

- Describe which system (OS, compiler) you are using.
Linux Fedora 30 with gcc version 9.2.1 20190827 (Red Hat 9.2.1-1) (GCC)

- Describe which version of the library you are using (release version, develop branch).
I'm using version 3.7.3

**Comment by nlohmann** [comment]
Did you already parse the JSON?

**Comment by oitan** [comment]
As you said I would just use` json["results"].at(0)["series"].at(0)["name"];`. Not sure if there are easier ways without `at()` or `get() ` methods. To make it more accessible you could use object conversion from [this example](https://github.com/nlohmann/json#arbitrary-types-conversions). I hope it helps.

**Comment by jcracine** [comment]
> @nlohmann Did you already parse the JSON?
Yes I did.




> @oitan  As you said I would just use` json["results"].at(0)["series"].at(0)["name"];`. Not sure if there are easier ways without `at()` or `get() ` methods. To make it more accessible you could use object conversion from [this example](https://github.com/nlohmann/json#arbitrary-types-conversions). I hope it helps.
I think the object conversion could do the trick. Now that I read it and tested it more, I think I have a better grasp on how to extract the data.

**Comment by nlohmann** [comment]
You can also use `operator[]` for arrays, so instead of

```cpp
json["results"].at(0)["series"].at(0)["name"];
```

you can write

```cpp
json["results"][0]["series"][0]["name"];
```

The `get()` function is only needed if you want to explicitly state the type you want to get. You could also do it this way:

```cpp
std::string name = json["results"][0]["series"][0]["name"];
```

@jcracine Do you need further assistance?
