### ISSUE TITLE
How to convert a const std::vector<char8_t> message to a json, to be able to parse it and extract information from it? Can you point to any examples?

### ISSUE THREAD

**Issue by coderDec** [nlohmann/json#2058]
- Describe what you want to achieve.
How to convert a const std::vector<char8_t> message to a json, to be able to parse it and extract information from it? Can you point to any examples?

- Describe what you tried.

- Describe which system (OS, compiler) you are using.
Linux

- Describe which version of the library you are using (release version, develop branch).
Latest Release version.

**Comment by nlohmann** [comment]
This should work. See the last example on <https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a265a473e939184aa42655c9ccdf34e58.html#a265a473e939184aa42655c9ccdf34e58>.

**Comment by coderDec** [comment]
Thank you
