### ISSUE TITLE
Allow to use non strict parsing

### ISSUE THREAD

**Issue by mlutken** [nlohmann/json#2063]
Currently, when parsing json from the "wild-web" there might be small problems like for example an ';' appended after an otherwise correct json. Being able to create a parser that flips the internal strict mode to false would be a great help when parsing these kinds of json sources.

The 
"static basic_json parse" function around line 6608 in json.hpp calls the internal parser with a "hardcoded" 'true' for the strict mode parameter.
If we could somehow make it possible to instantiate a json parser which uses false here, that would be really useful.

The function looks like this:
```cpp
    JSON_HEDLEY_WARN_UNUSED_RESULT
    static basic_json parse(detail::input_adapter&& i,
                            const parser_callback_t cb = nullptr,
                            const bool allow_exceptions = true)
    {
        basic_json result;
        parser(i, cb, allow_exceptions).parse(true, result);
        return result;
    }
```

It's the `parser(i, cb, allow_exceptions).parse(true, result);` I would like to be able to be:

`parser(i, cb, allow_exceptions).parse(false, result);`

Regards Martin

**Comment by nlohmann** [comment]
You're right, this bool is not public. In order to use it, you would need to use the SAX parser directly:

```cpp
#include <iostream>
#include "json.hpp"

using json = nlohmann::json;

int main() {
    std::string input = "{};";

    json result;
    nlohmann::detail::json_sax_dom_parser<json> sdp(result, true);
    auto parse_result = json::sax_parse(input, &sdp, nlohmann::detail::input_format_t::json, false);
    
    if (parse_result)
    {
        std::cout << result << std::endl;
    }
}
```

Output:

```json
{}
```

**Comment by mlutken** [comment]
That works perfectly. Thanks a lot.
But is the details namespace meant for public use?

**Comment by nlohmann** [comment]
You're right. So far, we make no guarantees about stability of the `detail` namespace.

What is stable though is the following:

```cpp
#include <iostream>
#include <sstream>
#include "json.hpp"

using json = nlohmann::json;

int main() {
    std::string input = "{};";

    json result;
    
    std::stringstream ss;
    ss << input;
    ss >> result;
    
    std::cout << result << std::endl;
}
```

Parsing from a stream via `operator>>` will always use the non-strict parser and does not rely on the detail namespace.

**Comment by mlutken** [comment]
OK, that's good to know. So if in the future there will be no alternative to you first solution I can allways fallback to this one.
Again, thanks a lot for your great library :)
