### ISSUE TITLE
‘__int64’ was not declared

### ISSUE THREAD

**Issue by M-Tonin** [nlohmann/json#2068]
- Describe what you want to achieve.
src/../include/json.hpp:13704:61: error: ‘__int64’ was not declared in this scope
         std::memmove(buf + 2, buf + 1, static_cast<size_t>((__int64)k - 1));
- Describe what you tried.
Try to compile de json hpp in linux.
- Describe which system (OS, compiler) you are using.
g++ 7.04
Linux, (works fine in windows)
- Describe which version of the library you are using (release version, develop branch).

**Comment by nlohmann** [comment]
Which version are you using? In the develop branch, the code does not contain `__int64`, and the lines with `memmove` are the following:

```cpp
std::memmove(buf + (static_cast<size_t>(n) + 1), buf + n, static_cast<size_t>(k) - static_cast<size_t>(n));
std::memmove(buf + (2 + static_cast<size_t>(-n)), buf, static_cast<size_t>(k));
std::memmove(buf + 2, buf + 1, static_cast<size_t>(k) - 1);
```

**Comment by M-Tonin** [comment]
I am using single_include/json.hpp from develop. 
I have notice now the master branch.
Should I take the master code instead of ?

**Comment by nlohmann** [comment]
In any case, the code does not contain `__int64`. Can you please check whether you included some headers before `json.hpp` which may re-define `std::int64_t` or the like?

**Comment by M-Tonin** [comment]
You are right, for same reason the code I had got had this "__int64". But it doesn't really exist. I can't say what happened. Sorry and thanks!
