### ISSUE TITLE
How to convert STL Vector (of user defined type) to Json

### ISSUE THREAD

**Issue by rakeshhegde** [nlohmann/json#2072]
Here is what I am trying to do,

using json = nlohmann::json;
typedef struct xyz {
  int array[1024];
} xyz_t;

int main()
{
  vector<vector<vector<xyz_t>>> abc;

/*......
   Assume abc is filled here
...... */

json j;
json["data"]["values"] = abc; /* This gives 'error: no match for ‘operator=’ */

/* How do overload =operator in above case or is there any better way to acheive same? */

return 0;
}

**Comment by nlohmann** [comment]
You need to define a conversion function, like

```cpp
void to_json(json& j, const xyz_t& xyz)
{
    j["array"] = xyz.array;
}
```

Then you get the rest (like vectors of `xyz_t`) for free. See https://github.com/nlohmann/json#arbitrary-types-conversions for more information.

**Comment by rakeshhegde** [comment]
Thank you @nlohmann for the prompt response.
I tried this solution & it works. Closing this ticket.
