### ISSUE TITLE
CMake FetchContent > Updating the documentation?

### ISSUE THREAD

**Issue by ArthurSonzogni** [nlohmann/json#2073]
nlohmann::json documents 2 way of depending on it using CMake
1) Copy-paste the project/source into your own project.
2) Install nlohman::json and then use find_package.

(1) pollutes your git repository, (2) requires everyone to install the dependencies themselves.

Since 2018, CMake provide some kind of 'package manager' features using [FetchContent](https://cmake.org/cmake/help/v3.17/module/FetchContent.html)
It gives the following:
~~~cmake
include(FetchContent)

FetchContent_Declare(nlohmann_json
  GIT_REPOSITORY https://github.com/nlohmann/json
  GIT_TAG v3.7.3)

FetchContent_GetProperties(json)
if(NOT json_POPULATED)
  FetchContent_Populate(json)
  add_subdirectory( ${json_SOURCE_DIR} ${json_BINARY_DIR} EXCLUDE_FROM_ALL)
endif()
~~~

Then declares the dependency in the target using it:
~~~cmake
target_link_library(my_project PRIVATE nlohmann_json::nlohmann_json
~~~

I think it might worth updating the README to include this. What do you think? Would you like to receive a PR about this? If yes, do you have any special instructions?

**Comment by nlohmann** [comment]
This is a good idea, and I would look forward to seeing a PR!

While you're at it, please also add a test like https://github.com/nlohmann/json/tree/develop/test/cmake_add_subdirectory so that we can be sure we do not break anything in the future. That test should then use the `develop` branch, however.
