### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by iphydf** [nlohmann/json#2075]
- Describe what you want to achieve.

Stay more current with the developments in this library.

- Describe what you tried.

Depending on the git repo instead of the released include.zip. This repo is pretty large so I'd rather depend on the released version.

- Describe which system (OS, compiler) you are using.

Debian GNU/Linux. Clang.

- Describe which version of the library you are using (release version, develop branch).

Release 3.7.3.

**Comment by nlohmann** [comment]
Version 3.8.0 is planned, but I cannot say when it will be released. I'm afraid "when it's done" is as accurate as it can get...

**Comment by iphydf** [comment]
That's when you mark it "alpha", because then people have the expectation that it'll break at any moment. The alpha release doesn't need to go away, but people can choose to either stick with the stable API or move along with the API changes. This doesn't need to hinder your development, but it allows people to follow along and be ready for the release when it comes.

**Comment by nlohmann** [comment]
I will do this before breaking changes, i.e. major releases. But the next release will just add some features.

**Comment by nlohmann** [comment]
@iphydf Version 3.8.0 has been released today: https://github.com/nlohmann/json/releases/tag/v3.8.0
