### ISSUE TITLE
Can't have a json type as a property in an arbitrary type

### ISSUE THREAD

**Issue by TheOnlyArtz** [nlohmann/json#2078]
I'm trying to have a struct which can old json type as one of it's properties and it throws an error, for some reason.

```cpp
namespace DataSerialization
{
	struct GeneralResponse
	{
		int op;
		json d;
	};

	void from_json(const json& j, const GeneralResponse& response)
	{
		j.at("op").get_to(response.op);
               // ERROR HERE
		j.at("d").get_to(response.d);
	}

	void to_json(json& j, const GeneralResponse& response)
	{
		j = json{ {"op", response.op}, {"d", response.d} };
	}
}
```
![image](https://user-images.githubusercontent.com/30025874/80820129-fa814d80-8bde-11ea-845b-aa132448fa9c.png)

**Comment by nlohmann** [comment]
In the from_json function, your type must not be const.

**Comment by TheOnlyArtz** [comment]
> In the from_json function, your type must not be const.

Aight, but still, same error occurs, I've "found" a workaround by using
`response.d = j["d"].get<json>();`

**Comment by nlohmann** [comment]
You can simplify this with

```cpp
response.d = j["d"];
```

or

```cpp
response.d = j.at("d");
```

The `get_to` function is meant to derive the type for conversions and does not work with the `json` type itself, see [the documentation](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a65753c68f06639eda0d355f919564e01.html#a65753c68f06639eda0d355f919564e01).

The signature is

```cpp
template<typename ValueType,
         detail::enable_if_t <
             not detail::is_basic_json<ValueType>::value and
             detail::has_from_json<basic_json_t, ValueType>::value,
             int> = 0>
ValueType & get_to(ValueType& v) const noexcept(noexcept(
            JSONSerializer<ValueType>::from_json(std::declval<const basic_json_t&>(), v)))
```
