### ISSUE TITLE
How to override default string serialization?

### ISSUE THREAD

**Issue by jkwill87** [nlohmann/json#2079]
## Describe what you want to achieve

I would like to be able to override the default string serialization to return a `null` value for empty strings. For instance,

***source***
``` cpp
nlohmann::json j;
j["name"] = ""
std::cout << j << std::endl;
```

***output***
``` json
{"name": null}
```

## Describe what you tried

1. Overriding `void to_json(nlohmann::json &j, const std::string &s)`. Redefinition error while linking.
2. Writing a custom serializer [as done in the test files](https://github.com/nlohmann/json/blob/develop/test/src/unit-udt.cpp). Doesn't enter overwritten `to_json`, for example,

***source***

``` cpp
template<typename T, typename = void>
struct custom_serializer {
    // defaults
    template <typename BasicJsonType, typename U = T>
    static void from_json(const BasicJsonType &j, U &t) {
        using nlohmann::from_json;
        from_json(j, t);
    }
    template <typename BasicJsonType, typename U = T>
    static void to_json(BasicJsonType &j, const U &t) {
        using nlohmann::to_json;
        to_json(j, t);
    }
    // strings
    template <typename BasicJsonType>
    static void from_json(const BasicJsonType &j, std::string &t) {
        using nlohmann::to_json;
        to_json(t,j);
    }
    template <typename BasicJsonType>
    static void to_json(BasicJsonType &j, const std::string &t) {
        if (t.empty()) j = nullptr;
        else j = t;
    }
};

using custom_json = nlohmann::basic_json<
    std::map,
    std::vector,
    std::string,
    bool,
    std::int64_t,
    std::uint64_t,
    double,
    std::allocator,
    custom_serializer
>;

custom_json j;
j["name"] = "";
```

***output***

``` json
{"name": ""}
```

I'm working on my first CPP project and admittedly inexperienced templating or concepts like SFINAE. If anyone has a possible solution or point out where I'm going wrong it would appreciated. Thank you!

## Describe which system (OS, compiler) you are using

Linux 5.6.6 x86-64, clang 10.0.0

## Describe which version of the library you are using (release version, develop branch)

`develop` branch

**Comment by nlohmann** [comment]
No, this is currently not possible without changing the code of the original serializer, see `include/nlohmann/detail/output/serializer.hpp`, function `dump_escaped`.

**Comment by jkwill87** [comment]
Alright, thank you. I was able to make this change in the following to `serializer::dump`

```cpp
switch (val.m_type) {

    // ...

    case value_t::string: {
        if ((*val.m_value.string).empty()) {
            o->write_characters("null", 4);
        } else {
            o->write_character('\"');
            dump_escaped(*val.m_value.string, ensure_ascii);
            o->write_character('\"');
        }
        return;
    }

    // ...
```
