### ISSUE TITLE
Question about serialization.

### ISSUE THREAD

**Issue by kepler425b** [nlohmann/json#2084]
Hi all. Was reading some issues about previous (years old) pretty/customisible serialization attempts, dumping json into string, but none seemed finished, is there a working and tested implementation by anyone?

**Comment by nlohmann** [comment]
No, this is still left to do. I am currently preparing version 3.8.0, but that feature won't make it in that release, because a concept is currently missing.

**Comment by nlohmann** [comment]
Just to understand the needs better: what would you like to customize?

**Comment by kepler425b** [comment]
> Just to understand the needs better: what would you like to customize?

[As in your own comment](https://github.com/nlohmann/json/issues/229#issuecomment-215949065), it more or less covers all I would need. Other than that, I don't have anything specific in mind.
