### ISSUE TITLE
Cannot debug but Run works

### ISSUE THREAD

**Issue by hect1995** [nlohmann/json#2085]
- Describe what you want to achieve.
I want to check which is the result of the `json::parse` of a certain file. Whenever I compile and run I see that works if I try to access one field. On the other hand if in debug mode, it crashes in:
<img width="681" alt="Captura de pantalla 2020-05-03 a las 18 38 36" src="https://user-images.githubusercontent.com/19693566/80920045-9640c400-8d6d-11ea-9cf1-ebe458b6da23.png">

- Describe what you tried.
My simple script is:
```
#include "nlohmann/json.hpp"
#include <fstream>
#include <iostream>

using json = nlohmann::json;

int main()
{
    std::ifstream myinput("dataset/CTA_Bay17.json");
    auto j = json::parse(myinput);
    // write prettified JSON to another file
    std::cout << j["array"] << "\n";
}
```

And the JSON I am reading is:
```
{
    "array": [
        1,
        2,
        3
    ],
    "boolean": true,
    "color": "gold",
    "null": null,
    "number": 123,
    "object": {
        "a": "b",
        "c": "d"
    },
    "string": "Hello World"
}
```

- Describe which system (OS, compiler) you are using. Mac OS Catalina and LLDB

- Describe which version of the library you are using (release version, develop branch).
Master branch

**Comment by nlohmann** [comment]
What is the exact exception message? If I would need to guess, the file cannot be found, because your debugger may run in a different working directory. Can you double check the file can actually be opened?
