### ISSUE TITLE
Remove #include <ciso646>

### ISSUE THREAD

**Issue by igfraga** [nlohmann/json#2089]
Was a bit of a surprise that 'or' and 'and' work in our code base and tracked it down to files that include nlohmann/json. Also note this header is going away in C++20.

**Comment by jaredgrubb** [comment]
What do you mean? `and` and `or` have always been keywords in C++.

**Comment by ArtemSarmini** [comment]
They are not in msvc without `/permissive-`. It it set by default in VS 15.5 and above, but old projects may break if we remove this header.

**Comment by nlohmann** [comment]
Indeed we include the header due to old MSVC versions. We should check if we can detect these versions with a macro (Hedley has a lot of them...) and only include it then.

**Comment by nlohmann** [comment]
Related: #1782

**Comment by ArtemSarmini** [comment]
Problem is this option does not depend on msvc version, that is, old project with permissive setting can be built with newest msvc and vice versa. AFAIK there's no macro to check it. But we can check build flags and set some macro ourselves. @nlohmann sounds good?

**Comment by nlohmann** [comment]
@ArtemSarmini You are fast! I just wanted to let you know about the change and ask for your opinion. An alternative to this approach would be to detect C++20 and not try to include if C++20 is used. Would that be feasibleß

**Comment by ArtemSarmini** [comment]
Again this flag does not depend on C++ version.
I suppose many projects nowdays switch this flag off. But I don't know how many of library users have it on (and will be affected when we remove the include) and don't know how to find it out either. I'll make a poll in a local community but it may be unrepresentative.

**Comment by nlohmann** [comment]
But in C++20, the header disappears, so I would expect that alternative operator representations must then work without that header. Or to put it differently: is there a minimal version that does not need `<ciso646>` any more?

**Comment by ArtemSarmini** [comment]
> alternative operator representations must then work without that header

No idea. I'll try to ask STL about that. But I guess microsoft assumes projects either use old msvc version or have the flag off.

> is there a minimal version that does not need <ciso646> any more?

As I understand it there's no such version.

**Comment by nlohmann** [comment]
It's deprecated since C++17 and will be removed in C++20 (see https://en.cppreference.com/w/cpp/header/ciso646, http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2131r0.html).

So basically 

```cpp
#if __cplusplus <= 201703L
    #include <ciso646> // and, not, or
#endif
```

should do the job.

**Comment by ArtemSarmini** [comment]
I was wrong about version.
I was suggested a cool trick which should do it, I'll test it locally first and let you know.

**Comment by nlohmann** [comment]
@ArtemSarmini Any news on this? Any comment on https://github.com/nlohmann/json/blob/8c2b26de4a9886751b8c7d88b788dc33c515f9f0/include/nlohmann/detail/boolean_operators.hpp?
