### ISSUE TITLE
Get string field content without return std::string copy 

### ISSUE THREAD

**Issue by zmwangcode** [nlohmann/json#2091]
I am dealing with json with a lot of string fields, I checked the souce code , seems there is no way to get the underlying string of string field without a std::string copy?

auto content = j.get<char*>()

Something likes this will be very helpful.

**Comment by zmwangcode** [comment]
I am fully aware of the fact that the returned char* may be invalidate when the json object is altered later.  It's the client's responsbility to use the returned raw string properly, is ther any way to get it ?

**Comment by AraHaan** [comment]
just take the std::string return and to ``.to_cstr()``

**Comment by zmwangcode** [comment]
> just take the std::string return and to `.to_cstr()` or something like that.

this required a std::string copy as well.   I want the content without any copy..

**Comment by nlohmann** [comment]
This works:

```cpp
json j = "Hello";
auto s = j.get_ref<std::string&>().c_str();
```

**Comment by zmwangcode** [comment]
due to compatbility reason, I need to use version 2.1.1, and seems this version does not support such operation.

how to achieve this in version 2.1.?

**Comment by nlohmann** [comment]
According to the [Release Notes](https://github.com/nlohmann/json/releases/tag/v1.1.0), `get_ref()` was introduced in version 1.1.0.

**Comment by zmwangcode** [comment]
Cool, I got build error and though it was caused by no such definition.

I checked the code, my issue was not provide const before std::string reference, because my input json j is a const object.

**Comment by nlohmann** [comment]
Cool! (But you really should update to the recent version...)

**Comment by AraHaan** [comment]
This is why I use submodules makes update just a ``git submodule foreach "git pull"`` away.

**Comment by nlohmann** [comment]
This depends on your policies of how updates are made. But yes, this may be a convenient method.

**Comment by zmwangcode** [comment]
> This is why I use submodules makes update just a `git submodule foreach "git pull"` away.

this is not quite a safe way for large project, since it may introduce new features automatically that may break existing functionality.

I prefer to test intensively before mannually upgrade to new version.

**Comment by zmwangcode** [comment]
> Cool! (But you really should update to the recent version...)

Will check and upgarade. :-)

**Comment by AraHaan** [comment]
@zmwangcode I mean if it did not work out you can always ``git reset`` the submodule.
