### ISSUE TITLE
Compilation issues when included in project

### ISSUE THREAD

**Issue by gomerkyle** [nlohmann/json#2094]
- What is the issue you have?
When I include the file "json.hpp" in my source code I get the following error(s)

 /inc/json.hpp:32:35: error: stray '\302' in program
   <title>json/json.hpp at develop · nlohmann/json · GitHub</title>
\<snip\>
inc/json.hpp:360:76: error: stray '\206' in program
       <span aria-hidden="true" class="d-inline-block ml-1 v-align-middle">↵</span>
\<snip\>
inc/json.hpp:1067:70: error: stray '#' in program
         <td id="LC35" class="blob-code blob-code-inner js-file-line">#<span class="pl-k">define</span> <span class="pl-en">NLOHMANN_JSON_VERSION_PATCH</span> <span class="pl-c1">3</span></td>

"json.hpp:33275:189: error: expected unqualified-id before '<' token
         <td id="LC7871" class="blob-code blob-code-inner js-file-line">#<span class="pl-k">include</span> <span class="pl-s"><span class="pl-pds">&lt;</span>vector<span class="pl-pds">&gt;</span></span> <span class="pl-c"><span class="pl-c">//</span> vector</span></td>"

\<this follows for virtually every line of the header\>

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

#include "json.hpp"

\<my code that does not use any json features yet\>

- What is the expected behavior?

That the code should compile

- And what is the actual behavior instead?
Several pages of compile errors

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?
-- The C compiler identification is GNU 8.3.1
-- The CXX compiler identification is GNU 8.3.1
OS - macos but the compilation is happening while building a centos 7 docker image.

I use Cmake and have SET(CMAKE_CXX_STANDARD 17)

- Did you use a released version of the library or the version from the `develop` branch?
Release

**Comment by nlohmann** [comment]
Can you make sure the file is exactly the one from the release? It seems that the stray may have been introduced by copy/pasting (see https://arduino.stackexchange.com/questions/30581/stray-302-in-program-error-when-compiling for example). Can you attach the `json.hpp` you are using?

**Comment by gomerkyle** [comment]
I think that's probably it. The errors don't correspond to the line numbers in any meaningful way. I copied the file directly from the include.zip file and still have the same issue. I'm looking online if this is a macos problem but I don't understand why copying the file directly is not helping.

Is there an encoding issue in the source? I tried saving in vi with :set nobomb, I opened and saved the file in xcode
[json.hpp.zip](https://github.com/nlohmann/json/files/4605902/json.hpp.zip)



I've attached what I'm currently using.

**Comment by nlohmann** [comment]
I am using macOS myself and never had such problems. I could also see no encoding issue in the attached file. If there was a BOM, then the error should be directly in the first characters. Very strange issue.

**Comment by gomerkyle** [comment]
I'm closing this issue. I did a split diff of the file and found a lot of weird characters. Very long story short I had a process that was trampling on json.hpp in the background. I killed that process and re-downloaded your file and everything works. User error. Sorry for the trouble and thanks for the help!

**Comment by felixcra** [comment]
I had a similar issue when I downloaded the header file with wget. Copying the file out of the zip folder instead, solved the issue.
