### ISSUE TITLE
C++20: char8_t

### ISSUE THREAD

**Issue by igoloe** [nlohmann/json#2097]
Are there any plans to move to std::u8string once char8_t literals are default for u8? Or should this be adressed by clients defining the string_type as std::u8string?

**Comment by nlohmann** [comment]
This library targets C++11, so we cannot default to `char8_t`. I'm afraid the clients need to do that, but I have not tested this yet.

**Comment by igoloe** [comment]
Ok. I will report about our experience. Thx.

**Comment by nlohmann** [comment]
That would be great!

**Comment by shrinktofit** [comment]
Watch on this! `std::u8string_view` is serialized as number array now.. I have to explicitly convert it into `std::string_view` every time.
