### ISSUE TITLE
Reading concatenated json's from an istream

### ISSUE THREAD

**Issue by lilinjn** [nlohmann/json#210]
Hi, 
Your library is great (and because I am lazy about being lazy, I've typed nlohmann::json so many times that I feel like I practically know you)

I have a file of multiple concatenated, pretty printed json objects that I want to parse.  Is there a way with the current library to split a string in individual json which than can be dealt with as usual (of course, any other reasonable way of skinning the same cat would be appreciated.)  Otherwise, I've seen json PCRE regexes that might also do the trick.   Do think that is the way to go?

Thanks!

**Comment by gregmarr** [comment]
Is there anything between the json objects besides whitespace, or maybe newlines only between the objects but nowhere else?  Since you say pretty printed, I'm guessing the newlines is no.  Do you have a small sample you can share?

**Comment by lilinjn** [comment]
````
{
  "pi": 3.141,
  "happy": true,
  "name": "Niels",
  "nothing": null,
  "answer": {
    "everything": 42
  },
}
{
  "pi": 3.141,
  "happy": true,
  "name": "Niels",
  "nothing": null,
  "answer": {
    "everything": 42
  },
}
````

... would be an example. 

basically I am trying to slurp in data from a process which is periodically appending
objects to a file (and I don't want to force the json to be single line to make manual testing/debugging easier) -- my process wakes up, slurps the data, truncates the file, and the process repeats (processes use file locking to avoid races, etc)

thanks!

**Comment by whackashoe** [comment]
One thing you could try is iterate over the characters and count how many { you have and every time you encounter a } subtract from that counter. Once the counter is 0 you know the end of the first json object.

**Comment by lilinjn** [comment]
arg, of course.  that sounds good.  Thanks for the help!

**Comment by whackashoe** [comment]
No prob, have a nice weekend!

**Comment by nlohmann** [comment]
Hi @lilinjn, does the idea of @whackashoe help you?

The format you are using reminds me of [JSON Lines](http://jsonlines.org), but your input seems to be pretty-printed. I have currently no plans supporting such an extension.

**Comment by lilinjn** [comment]
Yes -- I think it's simpler to roll my own reader based on @whackashoe's
point.  Thanks everyone.

**Comment by nlohmann** [comment]
Ok, then thanks @whackashoe for helping!
