### ISSUE TITLE
Remove undefined behavior for const operator[]

### ISSUE THREAD

**Issue by Xylaant** [nlohmann/json#2111]
- Describe the feature in as much detail as possible.

In most places in the library, when using a non-const object, attempting to access a non-existent array value or key via the operator[] methods will result in creation of those methods.  On the other hand, if the basic_json object is const qualified, then for arrays operator[] results in undefined behavior, where for objects it acts more like the at() function with an exception.  

I'd like to propose modifying the implementations of the const overloads of operator[] to instead return a const-reference to a static instance of an empty basic_json<> object.  There are a handful of ways to do this (static data member or static singleton method).  This would mean that you can't easily slip into undefined behavior/exception by adding const qualifying a json object.

**Comment by nlohmann** [comment]
A lot of people were annoyed by the behavior of `operator[]`, but this is the first time someone actually has a constructive proposal how to improve the situation. I will consider this after the 3.8.0 release.

**Comment by Xylaant** [comment]
As part of the discussion, what do you think the correct behavior of operator[](size_type) const and operator[](key_type) const be if is_null() is true.  For the non-const version, it converts the object to an array or object.  

If the code were to return a constant reference to a nil object in the not-present case, should it also do that in the is_null() case?  The current behavior would be to throw an exception.  Is it worth considering have it just return the same null object?

**Comment by eferreira** [comment]
> A lot of people were annoyed by the behavior of `operator[]`, but this is the first time someone actually has a constructive proposal how to improve the situation. I will consider this after the 3.8.0 release.

For the record, I suggested this exact possibility in this thread back in 2017: https://github.com/nlohmann/json/issues/289#issuecomment-273933297

would still love for it to make it into the official library in some form or another, for all the same reasons that I went into back then.

**Comment by TLescoatTFX** [comment]
Hello,

It is a bit painful to have to check every key, especially when the researched value is deep. This proposal (just returning some kind of sentinel) would allow to search deep values in a user-friendly way , ex:

    const json& val = some_json["data"]["key"]["another_key"]["slot"];
    if(!val.is_null()) // ...

You mentioned you would consider this after the 3.8.0. Do you have some opinion on this request ?
