### ISSUE TITLE
Possible incorrect _MSC_VER reference

### ISSUE THREAD

**Issue by ua-code-dragon** [nlohmann/json#2112]
https://github.com/nlohmann/json/blob/e7b3b40b5a95bc74b9a7f662830a27c49ffc01b4/single_include/nlohmann/json.hpp#L17470
This condition seems to check "Visual Studio 2017 or later", so there should be >= 1914, not <=

**Comment by nlohmann** [comment]
This comparison was introduced in https://github.com/nlohmann/json/pull/1028 and last changed in https://github.com/nlohmann/json/pull/1496. In https://github.com/nlohmann/json/pull/1028#issuecomment-393975287, I think the reason is described why it should be `<=`:

> So the bug preventing enabling this feature on msvc has been fixed: https://developercommunity.visualstudio.com/content/problem/243183/stdstring-should-not-have-a-operator-that-takes-a.html
>
> It should be out in 15.8 (msvc 19.15?), so in 19.14 and older it is disabled, as discussed.

**Comment by ua-code-dragon** [comment]
Maybe I'm wrong, but std::string_view is only available from C++17. For example, Visual Studio 2015 has _MSC_VER=1900, so this #if becomes true and I got an error on unknown string_view.

**Comment by nlohmann** [comment]
Good point. I'm not using MSVC myself, but I may be able to check via AppVeyor.

**Comment by ua-code-dragon** [comment]
According to [this](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=vs-2019) the N4562 feature set with string_view has been added in VS 2017 15.0
According to [this](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2019) there was _MSC_VER=1910
Maybe the mentioned condition should be `... || (defined(_MSC_VER) and _MSC_VER >= 1910 and _MSC_VER <= 1914))`

**Comment by garethsb-sony** [comment]
Doesn't the check for `JSON_HAS_CPP_17` already deal with the beginning of the range?

**Comment by dota17** [comment]
> Doesn't the check for `JSON_HAS_CPP_17` already deal with the beginning of the range?

As I can see, the check for `JSON_HAS_CPP_17 ` and `_MSC_VER`  is a parallel relationship(`||`),
so I agree with @ua-code-dragon  in https://github.com/nlohmann/json/issues/2112#issuecomment-629688889.

**Comment by nlohmann** [comment]
Thanks everyone for the discussion!
