### ISSUE TITLE
assigning nullptr to std::string

### ISSUE THREAD

**Issue by GvYK** [nlohmann/json#2118]
####  Question
According to the document for "JSON for Modern C++", when the variable type is "std::nullptr_t", it returns "null".

It's a silly question, but if assigning "nullptr" to "std::string" like "Example", which one is intended as the specification?

(1) it causes the segmentation fault by undefined behavior of std::string
(2) it returns "null" as same as "std::nullptr_t"

It seems that (1) is the specification: it's undesired to assign "nullptr" to "std::string".
Is it correct about my understanding?

```
[Example]

#include <iostream>
#include <nlohmann/json.hpp>

int main() {
    nlohmann::json j;
    std::string value = nullptr;
    j[ "value" ] = value;
    std::cout << j << std::endl;

    ...
}
```

####  Version
- JSON for Modern C++ 3.7.3
- Linux gcc 8.3.0

**Comment by nlohmann** [comment]
I do not fully understand the issue. If you want to store the JSON value `null` at key `"value"`, then it's sufficient to write

```cpp
j[ "value" ] = nullptr;
```

There is no need to have a `std::string` involved.

**Comment by GvYK** [comment]
Thank you for the polite answer to store the JSON value "null" . Please close this question.
