### ISSUE TITLE
quick and convenient api to get/set nested json values

### ISSUE THREAD

**Issue by myseemylife** [nlohmann/json#2120]
- Describe the feature in as much detail as possible.
   while i used to use a json library which export a nice api. access  or write values like this: 
   json["a.b.c.d.0.b"]
- Include sample usage where appropriate.
  eg: 
  json v = '{a:{b:[ {c:'ok'}]}}'_json
  get values :  v["a.b.0.c"]
  set values:  v["a.b.0.c"] = "123"

**Comment by nlohmann** [comment]
You can use JSON Pointer (see https://github.com/nlohmann/json#json-pointer-and-json-patch).

**Comment by myseemylife** [comment]
great! i 'll try it. thx for your guide!
