### ISSUE TITLE
Intersection of two json files

### ISSUE THREAD

**Issue by AistisT** [nlohmann/json#2127]
Just a quick question, rather than an issue I suppose. Is there anything inbuilt into the library that allows comparison of two json files to find out if there are overlapping properties in them.

I had a scan, but couldn't find anything, but its possible that I've missed something.

**Comment by nlohmann** [comment]
No, there is just a diff function (see https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a9c4f3554773649beef69461a10a3de87.html#a9c4f3554773649beef69461a10a3de87) which is related. Maybe you can re-use some of the code.

**Comment by AistisT** [comment]
cheers, I'll have a look

**Comment by nlohmann** [comment]
Do you need further assistance?

**Comment by AistisT** [comment]
No, I'm good, you can close this now 




Sent from Outlook Mobile







On Wed, Jun 3, 2020 at 8:32 PM +0100, "Niels Lohmann" <notifications@github.com> wrote:















Do you need further assistance?
