### ISSUE TITLE
Changing the default format for unordered_map (or other set)

### ISSUE THREAD

**Issue by Endur1el** [nlohmann/json#2132]
#### What do you want to achieve?
I'm looking to use the library to save the state of a game simulation I'm working on. My knowledge of C++ is fairly basic (have only just begun shifting over from C# and Java) and I have been unable to find anyone else looking to achieve the same thing so I'm turning to here.

I'm trying to keep the save files easily and quickly readable with reasonable success. My only issue is with the way maps are converted, and I was wondering if there was a way to change the format without having to manually define a different from and to _json for every type.

When saving the unordered_map instead of having it a map as
```
[
        [
            "food",
            5.0
        ],
        [
            "amenities",
            10.0
        ]
]
```
is there an easy way to format this to
```
        ["food": 5.0],
        ["amenities": 10.0],
```
for all key value combinations? I have been unable to find anything about this anywhere so finally decided to reach out here as I've seen people be very helpful regarding questions.

- Compiler: VS 2019 C++17
- Operating system: Windows 10
- [x] latest release version 3.7.3

**Comment by nlohmann** [comment]
What is the exact type of which the serialization is 

```json
[
        [
            "food",
            5.0
        ],
        [
            "amenities",
            10.0
        ]
]
```

?

**Comment by Endur1el** [comment]
```
void to_json(json& j, const Resource& resource) {
    j = resource.content;
}
//within Resource
std::unordered_map<ResourceType, double> content;
```
and ResourceType is an enum where I have set up enum to string (rather than int) serialization, to clarify though, this was still the formatting when the enum was represented as an int.

**Comment by nlohmann** [comment]
I see. Since the keys are not convertible to `std::string`, the map is translated into a list of pairs. You could try two things:

- Define an implicit conversion of `ResourceType` to `std::string`. This could (haven't tested) yield to a conversion to a JSON object.
- Define a translation for `std::unordered_map<ResourceType, double>` via an `adl_serializer`, see https://github.com/nlohmann/json#how-do-i-convert-third-party-types.

**Comment by Endur1el** [comment]
The problem with option #2 is that from what I understand I would have to do that for every new way I stored objects together so #1 sounds a lot more viable, but I can't find any way to set up implicit `enum` to `std::string` conversion anywhere online.

**Comment by nlohmann** [comment]
Sorry, I forgot that it's not possible to provide a `operator std::string()` to an enum. So you may be left with option 2.
