### ISSUE TITLE
Incorrect CMake FetchContent example

### ISSUE THREAD

**Issue by quentin-dev** [nlohmann/json#2142]
#### What is the issue you have?

The README section about CMake FetchContent integration seems to have a typo

```
FetchContent_Declare(json
  GIT_REPOSITORY https://github.com/nlohmann/json
  GIT_TAG v3.7.3)
```
Should be

```
FetchContent_Declare(json
  GIT_REPOSITORY https://github.com/nlohmann/json.git
  GIT_TAG v3.7.3)
```
as is shown in the [examples](https://cmake.org/cmake/help/v3.17/module/FetchContent.html) given by CMake

**Comment by nlohmann** [comment]
Closed with #2143
