### ISSUE TITLE
Best way to catch errors when querying json

### ISSUE THREAD

**Issue by apivovarov** [nlohmann/json#2150]
I need to create API to return item name if item is found or `nullptr` if not.
What is the best way to do it if all json layers are optional? Should I check if every single layer exist and array index is in range? Or should I try to query json and catch particular exception(s) which indicate that item does not exist or array index is our of range in json

```
// Returns nullptr if name is not in json or index is out of range
const char* GetName(const int index) const {
    return json["Product"]["Suppliers"][index]["name"]
        .get_ref<const std::string&>()
        .c_str();
}
```

**Comment by nlohmann** [comment]
I would do this (though not tested):

```cpp
// Returns nullptr if name is not in json or index is out of range
const char* GetName(const int index) const {
	try
	{
	    return json.at("Product").at("Suppliers").at(index).at("name")
	        .get_ref<const std::string&>()
	        .c_str();
	}
	except (json::exception&)
	{
		return nullptr;
	}
}
```

**Comment by apivovarov** [comment]
is `except` Microsoft extension on C++?

**Comment by nlohmann** [comment]
No, it must be catch - I’m using too much Python these daycare.

**Comment by dota17** [comment]
> The try-except statement is a Microsoft extension that supports structured exception handling in the C and C++ languages. This extension is Microsoft-specific.

More details are in this link: https://docs.microsoft.com/en-us/cpp/cpp/try-except-statement?view=vs-2019

**Comment by apivovarov** [comment]
is there any diff btw `json.at("Product")` and `json.["Product"]`?

**Comment by dota17** [comment]
As it stated in readme:
> We designed the JSON class to behave just like an STL container.

`at()` will check the bound, but `operator[]` not. so `at()` is more safe.

**Comment by nlohmann** [comment]
Using `operator[]` on a nonexisting key/invalid index is undefined behavior. You must not do this if you are not sure the values exist.

Do you need further assistance?

**Comment by apivovarov** [comment]
Niels, Chen, thank you for great answers! Vielen Dank!
