### ISSUE TITLE
Accessing array inside array syntax? 

### ISSUE THREAD

**Issue by duojet2ez** [nlohmann/json#2151]
Hello,

I have a json file containing the following:
```
{
	 "cars": [
    { "name":"Ford", "models":[ "Fiesta", "Focus", "Mustang" ] },
    { "name":"BMW", "models":[ "320", "X3", "X5" ] },
    { "name":"Fiat", "models":[ "500", "Panda" ] }
		   ]
}
```

How would I go about accessing an array inside an array in my main.cpp file?  For example if I wanted to create a sting variable and set "Fiesta" to it. Would I read into the file, declare a json object (j), and then... from here I can only guess as what the syntax would be. j[0].models[0] ??

One more question is what if the json object is an array containing multiple types (string, int, bool). Would I declare a vector of type j for the json object in my cpp file? 

My apologies if this is covered in the documentation. I can't seem to figure it out.

**Comment by dota17** [comment]
`j["cars"]` = 
```json
[    
    { "name":"Ford", "models":[ "Fiesta", "Focus", "Mustang" ] },
    { "name":"BMW", "models":[ "320", "X3", "X5" ] },
    { "name":"Fiat", "models":[ "500", "Panda" ] }
]
```
`j["cars"][0]` =

```json
{ "name":"Ford", "models":[ "Fiesta", "Focus", "Mustang" ] }
```
`j["xars"][0][models]` =
```json
[ "Fiesta", "Focus", "Mustang"]
```
`j["xars"][0][models][0]` =

`"Fiesta"`

you just need to declare a `nlohmann::json` type variable `j`, it can accept any kind of JSON type value(e.g. object, array, string, bool, null, number)

**Comment by duojet2ez** [comment]
Thank you!! This is exactly what I needed!!!! Thanks for clearing up the syntax

**Comment by Lightningblade** [comment]
json```
{
    "tag": "CARL A",
    "isin": "DK0010181676",
    "shares": 33699252,
    "name": "Carlsberg Breweries A/S",
    "url": "https://www.carlsberggroup.com/",
    "market": "Nasdaq Copenhagen",
    "sector": "Food, Beverage and Tobacco",
    "segment": "Large",
    "trades": [
        {
            "time": "2012-10-31T08:01:00Z",
            "price": 527,
            "amount": 35,
            "buyer": "DDB",
            "seller": "NDA",
            "seq": 1,
            "code": 0
        },
        {
            "time": "2012-10-31T08:30:00Z",
            "price": 512,
            "amount": 100,
            "buyer": "DDB",
            "seller": "DDB",
            "seq": 2,
            "code": 0
        }
    ]
}
```
Accessing the trades gives me as expected:
```
[
    {
        "amount": 35,
        "buyer": "DDB",
        "code": 0,
        "price": 527,
        "seller": "NDA",
        "seq": 1,
        "time": "2012-10-31T08:01:00Z"
    },
    {
        "amount": 100,
        "buyer": "DDB",
        "code": 0,
        "price": 512,
        "seller": "DDB",
        "seq": 2,
        "time": "2012-10-31T08:30:00Z"
    }
]
```
However iterating over ```j["trades"]``` via ```for (auto &trade : jsontrades) ``` loops once with 
```{
    "amount": 35,
    "buyer": "DDB",
    "code": 0,
    "price": 527,
    "seller": "NDA",
    "seq": 1,
    "time": "2012-10-31T08:01:00Z"
}```
and null together with an error:
```
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.302] type must be string, but is null
```

What

**Comment by gregmarr** [comment]
@Lightningblade Can you provide a full example that reproduces the issue?

**Comment by Lightningblade** [comment]
main
```
    const char* FILEPATH = R"(TEST.json)";
    JsonParser jsonParser = JsonParser(FILEPATH);

    StockTradeHistory stockTradeHistory = StockTradeHistory(jsonParser);
```

stocktradehistory.cpp
```
StockTradeHistory::StockTradeHistory(JsonParser &input) {
    tag = input.j["tag"];
    isin = input.j["isin"];
    shares = input.j["shares"];
    name = input.j["name"];
    url = input.j["url"];
    market = input.j["market"];
    sector = input.j["sector"];
    segment = input.j["segment"];


    auto jsontrades = input.j["trades"];

    for (auto &trade : jsontrades) {

        Trade t;

        auto timestamp = trade["timestamp"];

        t.transactionTime = timestamp;

        t.price = trade["price"];
        t.amount = trade["amount"];
        t.buyer = trade["buyer"];
        t.seller = trade["seller"];
        t.seq = trade["seq"];
        t.code = trade["code"];

        trades.push_back(t);
    }
}
```

stocktradehistory.h
```
class StockTradeHistory {

public: StockTradeHistory(JsonParser &input);
    std::string tag;
    std::string isin;
            int shares;
    std::string name;
    std::string url;
    std::string market;
    std::string sector;
    std::string segment;

    std::vector<Trade> trades;

private: void AggregateTrades(JsonParser &input);
};
```
Trade is just a simple class with the 7 values.

And trades is a simple vector<Trade> defined in the .h file.

**Comment by gregmarr** [comment]
Your JSON has `time` but you're accessing `timestamp`.

**Comment by Lightningblade** [comment]
Thank you very much. I literally sat at this problem for two days.

**Comment by nlohmann** [comment]
Casual reminder that you can define [JSON_DIAGNOSTICS](https://json.nlohmann.me/api/macros/json_diagnostics/) before including the library to get [extended diagnostic messages](https://json.nlohmann.me/home/exceptions/#extended-diagnostic-messages) which can help to better locate the error.

**Comment by nlohmann** [comment]
Casual reminder that you can define [JSON_DIAGNOSTICS](https://json.nlohmann.me/api/macros/json_diagnostics/) before including the library to get [extended diagnostic messages](https://json.nlohmann.me/home/exceptions/#extended-diagnostic-messages) which can help to better locate the error.
