### ISSUE TITLE
nlohmann::json and =nullptr

### ISSUE THREAD

**Issue by apivovarov** [nlohmann/json#2156]
Can I use operators `= nullptr` and `== nullptr` with `nlohmann::json`?

For example:
```
nlohmann::json myjson = nullptr;

std::ifstream jsonFile (path);
try {
  jsonFile >> myjson;
} catch (nlohmann::json::exception&) {
  myjson = nullptr;
  cout << "Load json file failed\n";
}

if (myjson == nullptr) {
  cout << "Json is not loaded\n";
}

```
What exactly `json myjson = nullptr` is doing?

**Comment by dota17** [comment]
yes, you can. There are several implements about overload `operator=` and `operator==` inside this lib, 
 if the assigned value or the compared value are JSON type value(`nlohmann::json`), then it's ok to use it.
`json myjson = nullptr` is to set myjson to null, no longer hold the original value.

**Comment by apivovarov** [comment]
Can I use `myjson == nullptr` to check that `nlohmann::json` object was created but never filled with data?
```
if (myjson == nullptr) {
  cout << "Json is not loaded\n";
}
```

**Comment by nlohmann** [comment]
Yes, you can. It would be even more expressive if you would use `if (myjson.is_null())`.

**Comment by nlohmann** [comment]
More info:

- https://nlohmann.github.io/json/doxygen/classnlohmann_1_1basic__json_a122640e7e2db1814fc7bbb3c122ec76e.html#a122640e7e2db1814fc7bbb3c122ec76e
- https://nlohmann.github.io/json/doxygen/classnlohmann_1_1basic__json_afe9a6fe72337a174cfb117a2081d2cfc.html#afe9a6fe72337a174cfb117a2081d2cfc

**Comment by apivovarov** [comment]
Thank you!
