### ISSUE TITLE
Wide character strings not supported

### ISSUE THREAD

**Issue by kalumekenge** [nlohmann/json#216]
```
	std::wstring s1 = LR"({
  "pi": 3.141,
  "happy": true,
  "name": "Niels",
  "nothing": null,
  "answer": {
    "everything": 42
  },
  "list": [1, 0, 2],
  "object": {
    "currency": "USD",
    "value": 42.99
  }
})";
```
	auto p0 = json::parse(s1);
	auto p1 = p0.dump();
	std::wcout << p1 << std::endl;
VS 2015 Community Edition
 error C2665: 'nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator>::parse': none of the 3 overloads could convert all the argument types
while trying to match the argument list '(std::wstring)'

**Comment by nlohmann** [comment]
@kalumekenge, I made a branch to fix this version. Unfortunately, it requires the `<codecvt>` header which is not included in many Clang and GCCs out there.

**Comment by nlohmann** [comment]
I added an FAQ entry: https://json.nlohmann.me/home/faq/#wide-string-handling
