### ISSUE TITLE
Problem while reading a json file

### ISSUE THREAD

**Issue by MdAnayat** [nlohmann/json#2161]
First of all thanks for this nice library.

I have the json in below format:
{
	"values": "false",
	"tran_up_left_scene_x": "1",
	"CRC": "145"
}

I have saved it as input.json file and want to read it using the below code:
       int x;
	int y;
	std::ifstream ifs("C:/codes/input.json");
	json j = json::parse(ifs);
	for (const auto& element : j["tran_up_left_scene_x"])
	{
		std::cout << element << std::endl;
		x = element;
	}

But I am getting the below error:
Exception unhandled:
  default:
            JSON_THROW(type_error::create(302, "type must be number, but is " + std::string(j.type_name())));

The json validator is showing the above used json is valid.
Any kind of help to solve this problem will be highly appreciated.

**Comment by nlohmann** [comment]
You try to assign a string to a number. You need to make that conversion explicit, e.g. with std::to_string.

**Comment by MdAnayat** [comment]
For extracting every single parameter from a json file i was using the below code:
for (const auto& element : j["tran_up_left_scene_x"])
{
std::cout << element << std::endl;
x = element;
}
But using std::to_string how can i extract each parameter of the json file??
can you give a code example??

**Comment by nlohmann** [comment]
You need to do this:

```cpp
x = std::to_string(element);
```

But this only works if `element` holds a string. You can check the type with:

```cpp
if (element.is_string())
{
    x = std::to_string(element);
}
```

**Comment by MdAnayat** [comment]
As per your suggestion, i have modified the code as below:
int x;
	int y;
	std::ifstream ifs("C:/codes/input.json");
	json j = json::parse(ifs);
	for (const auto& element : j["CRC"])
	{
		
		std::cout << element << std::endl;
		if (element.is_string())
		{
			x = std::to_string(element);
		}
	}

But getting the below error:

**Error  C2668	'std::to_string': ambiguous call to overloaded function**

I have also tried **stringstream** to convert the string into a number. But it does not work either.

**Comment by nlohmann** [comment]
Oh, `std::to_string` makes no sense here.

```cpp
x = std::stoi(element.get_ref<std::string&>());
```

**Comment by MdAnayat** [comment]
The above-mentioned line throws the below error:
Error	C2662	'ReferenceType nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer,std::vector<uint8_t,std::allocator<_Ty>>>::get_ref<std::string&,0>(void)': cannot convert 'this' pointer from 'const nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer,std::vector<uint8_t,std::allocator<_Ty>>>' to 'nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer,std::vector<uint8_t,std::allocator<_Ty>>> &'

**Comment by nlohmann** [comment]
Then change it to

```cpp
x = std::stoi(element.get_ref<const std::string&>());
```

**Comment by MdAnayat** [comment]
This worked for me. Thanx a lot for your kind help.
You can close this issue now.
