### ISSUE TITLE
Q: When I received an illegal string,How the program knows?

### ISSUE THREAD

**Issue by huluBrother** [nlohmann/json#2162]
```
std::string body = "";//illegal
std::string body = "a"//illegal
nlohmann::json reqContext = nlohmann::json::parse(body);
```
how the program knows?

Of course, the premise is that the program cannot crash.
Thanks

**Comment by nlohmann** [comment]
You can use `accept()` instead of `parse` which returns a `bool`. There is also a parameter `allow_exceptions` for `parse` to suppress exceptions, see https://nlohmann.github.io/json/doxygen/classnlohmann_1_1basic__json_a4c734aac1ea36f4b62f25308b6c6784a.html#a4c734aac1ea36f4b62f25308b6c6784a

**Comment by huluBrother** [comment]
> You can use `accept()` instead of `parse` which returns a `bool`. There is also a parameter `allow_exceptions` for `parse` to suppress exceptions, see https://nlohmann.github.io/json/doxygen/classnlohmann_1_1basic__json_a4c734aac1ea36f4b62f25308b6c6784a.html#a4c734aac1ea36f4b62f25308b6c6784a
Sorry, I understand what you mean, but I did not understand how to pass this parameter, can you give an example?

**Comment by nlohmann** [comment]
Instead of calling

```cpp
auto result = json::parse(body);
```

do this:

```cpp
auto result = json::parse(body, nullptr, false);
```

**Comment by huluBrother** [comment]
> Instead of calling
> 
> ```c++
> auto result = json::parse(body);
> ```
> 
> do this:
> 
> ```c++
> auto result = json::parse(body, nullptr, false);
> ```

The content returned by this `result` is a discard?
How can I tell if parse is successful?

**Comment by nlohmann** [comment]
From the documentation:

> Returns: deserialized JSON value; in case of a parse error and allow_exceptions set to false, the return value will be value_t::discarded.

**Comment by huluBrother** [comment]
> value_t::discarded.

sorry,value_t::discarded. In which file, how do I refer to this variable?

**Comment by huluBrother** [comment]
> From the documentation:
> 
> > Returns: deserialized JSON value; in case of a parse error and allow_exceptions set to false, the return value will be value_t::discarded.

value_t::discarded. In which file, how do I refer to this variable

**Comment by nlohmann** [comment]
You can check with `result.is_discarded()` whether the value is discarded. Or `result == json::value_t::discarded`.

**Comment by huluBrother** [comment]
> You can check with `result.is_discarded()` whether the value is discarded. Or `result == json::value_t::discarded`.

```
	std::string body = "a";
	auto result = nlohmann::json::parse(body, nullptr, false);

	if (result == nlohmann::json::value_t::discarded) {
		std::cout << "nlohmann::json::value_t::discarded" << std::endl;
	}
	if (result.is_discarded()) {
		std::cout << "is_discard" << std::endl;
	}
```
Thank you very much, I solved the problem.
but `result == nlohmann::json::value_t::discarded` return false,

**Comment by nlohmann** [comment]
Sorry, I did not check my code example.

This works:

```cpp
    if (result.type() == nlohmann::json::value_t::discarded) {
        std::cout << "nlohmann::json::value_t::discarded" << std::endl;
    }
```

**Comment by nlohmann** [comment]
Do you need further assistance with this issue?

**Comment by huluBrother** [comment]
> Do you need further assistance with this issue?

Thanks, this has satisfied my needs, let me close this issue
