### ISSUE TITLE
templated from_json of non primitive types causes gcc error

### ISSUE THREAD

**Issue by kouberl** [nlohmann/json#2168]
#### What is the issue you have?

I use templated to_json/from_json methods, because I have different serializer for the same type.
I have problems with gcc with the from_json methods.

#### Please describe the steps to reproduce the issue.

When I use the json::get method it does not compile.

#### Can you provide a small but working code example?

```
#include <nlohmann/json.hpp>
#include <vector>

namespace ns {
    struct MyType {
        std::vector<int> i;
    };

    template <typename json_t>
    void to_json(json_t &j, const MyType &m) {
        j["i"] = m.i;
    }

    template <typename json_t> 
    void from_json(json_t const& j, MyType& m) {
        m.i = j.at("i").get<std::vector<int>>();
    }
}

int main() {
    ns::MyType type;
    type.i.push_back(42);
    nlohmann::json type_json = type;
    ns::MyType type2 = type_json;
}
```

As a workaround I inserted another copy: (toogle define to enable the workaround)
see https://godbolt.org/z/uVW_4b

#### What is the expected behavior?

should compile

#### And what is the actual behavior instead?

gcc error

#### Which compiler and operating system are you using?

- Compiler: gcc
- Operating system: linux

#### Which version of the library did you use?

- [x ] latest release version 3.7.3
- [ ] other release - please state the version: ___
- [ ] the `develop` branch

#### If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

- [ x] yes
- [ ] no - please copy/paste the error message below

**Comment by nlohmann** [comment]
Can you change

```cpp
    template <typename json_t>
    void from_json(json_t const& j, MyType& m) {
        m.i = j.at("i").get<std::vector<int>>();
    }
```

to

```cpp
    template <typename json_t>
    void from_json(json_t const& j, MyType& m) {
        m.i = j.at("i").template get<std::vector<int>>();
    }
```

Then it compiles for me - at least with Xcode.

**Comment by kouberl** [comment]
Ok big thanks, this works. I always forget the `template` keyword.
Thanks!

**Comment by nlohmann** [comment]
I would have missed it unless Xcode hadn't given me a hint:

![Screen Shot 2020-06-05 at 08 53 57](https://user-images.githubusercontent.com/159488/83845987-2a55d080-a70a-11ea-9622-aa5414b45b78.png)
