### ISSUE TITLE
Some troubles to compile the last revision

### ISSUE THREAD

**Issue by aliktab** [nlohmann/json#2177]
/libs/json/include/nlohmann/json.hpp:6735:5: error: an attribute list cannot appear here
    JSON_HEDLEY_DEPRECATED_FOR(3.8.0, sax_parse(ptr, ptr + len, ...))
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/libs/json/include/nlohmann/thirdparty/hedley/hedley.hpp:946:110: note: expanded from macro 'JSON_HEDLEY_DEPRECATED_FOR'
    #define JSON_HEDLEY_DEPRECATED_FOR(since, replacement) JSON_HEDLEY_DIAGNOSTIC_DISABLE_CPP98_COMPAT_WRAP_([[deprecated("Since " #since "; use " #replacement)]])
                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/json/include/nlohmann/thirdparty/hedley/hedley.hpp:693:5: note: expanded from macro 'JSON_HEDLEY_DIAGNOSTIC_DISABLE_CPP98_COMPAT_WRAP_'
    xpr \


Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.5.0
Thread model: posix

**Comment by nlohmann** [comment]
Sorry about that - #2174 should fix this.

**Comment by aliktab** [comment]
yes it fix it
