### ISSUE TITLE
.get<std::string> causing emdash errors

### ISSUE THREAD

**Issue by poi2000** [nlohmann/json#2180]
Not a very experienced programmer, but I've been putting together a small project using json files and encountered some issues with printing values from json. My code contains a number of conditionals similar to below, which are supposed to print out the value associated with a given key in a much larger json file. In this case, "type" is a key with an associated string value. However, when I run the program, the code prints out a small pile of random Unicode symbols instead of what's written in the json file. Is this something that is solvable, or is something wrong on my end?

`if (unique.find("type") != unique.end()) {
				cout << unique["type"].get<std::string>() << endl;
			}`

> Expected: Creature — Cat

> Actual: Creature ΓÇö Cat

I've been building my code on Windows using Visual Studio 2019 16.3.10, and am currently using nlohmann json version 3.7.3.

Thanks, Julian Lane.

**Comment by nlohmann** [comment]
How does the JSON value look like? What is the output of unique.dump()?

**Comment by poi2000** [comment]
Hadn't thought about dumping the json values yet, but the dump resulted in the same errors. I attached both the correct text form of the json and the dumped version for further troubleshooting.

[unique_dump.txt](https://github.com/nlohmann/json/files/4752785/unique_dump.txt)
[unique_plaintext_json.txt](https://github.com/nlohmann/json/files/4752786/unique_plaintext_json.txt)

**Comment by nlohmann** [comment]
Both files look good. Please provide the code you use to read/create the value and the exact error message.
