### ISSUE TITLE
How to send json data over the wire?

### ISSUE THREAD

**Issue by shrikky** [nlohmann/json#2185]
I have a client that is trying to send the following json data :

**On the client side** 
nlohmann::json j2 = 
		{
			  {"command", "Target Offset"},
			  {"args", {"1", "0", "2"}},
		};	

I create a string str = j2.dump();
I send str over the network to the server

**On the server side** 

I am able to recv the data as string, but how do I convert the string back to json? 

nlohmann::json j(read_msg_.body()); this line fails

I have to and from json written

 void from_json(const json & j, NetworkPacket& p)
 {
	 p.command = j.value("command", "");

	 if (j.contains("args"))
		 p.arguments = j.value("args", p.arguments);
 }

 void to_json(json & j, const NetworkPacket & p)
 {
	 j = json{ {"command",p.command},
							"args",p.arguments };
 }

and my NetworkPacket class looks like this 

struct NetworkPacket
{
public:
	string command;
	vector<string> arguments;
};

Please help, how do I send data from client to server over the network.

**Comment by nlohmann** [comment]
You need to call json::parse to create a JSON value back from the string.

**Comment by nlohmann** [comment]
Do you need further assistance with this issue?

**Comment by shrikky** [comment]
Thank you this worked, I remember trying this at first, maybe I did something mistake. But thanks for helping me out
