### ISSUE TITLE
Append to a std::nlohmann::json type

### ISSUE THREAD

**Issue by Robonics** [nlohmann/json#2186]
I want to add data from multiple JSONs into a singular variable

I want to Parse JSON_1's data into the json data type, then parse JSON_2's data into the same variable, without overwriting the original data (Like an append type operator)

I have tried iterating over the files and using `file >> json` for each, however the data from the first JSON is overwritten by the next jsons

```
    std::vector<std::string> cardPaths = getDir("cards/stats/", ".json");
    json cardData;
    std::wstring LoadMsg = L"Loaded:";
    for(auto f_path : cardPaths) {
        std::ifstream(f_path) >> cardData;
        std::cout << f_path << "loaded successfully" << std::endl;
    }
```

Windows 10 OS and compiler is g++ (Rev3, Built by MSYS2 project) 10.1.0

#### Library Version
- [x] latest release version 3.7.3
- [ ] other release - please state the version: ___
- [ ] the `develop` branch

**Comment by nlohmann** [comment]
You can use the update function for this.

**Comment by nlohmann** [comment]
See https://nlohmann.github.io/json/doxygen/classnlohmann_1_1basic__json_a6c02637be3d8bd730a14082cc05f7a85.html#a6c02637be3d8bd730a14082cc05f7a85 for documentation and an example.

**Comment by Robonics** [comment]
Thanks, that worked.
