### ISSUE TITLE
'nlohmann/json.hpp' file not found

### ISSUE THREAD

**Issue by Honorable22** [nlohmann/json#2188]
For some reason I am getting this error message on basic setup when running this library on VS Code:

UIDeveloperTest.cpp:26:10: fatal error: 'nlohmann/json.hpp' file not found
#include "nlohmann/json.hpp"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.

I can not seem to find the solution to this error.

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by Honorable22** [comment]
When trying to include the library with the following line: 

#include <iostream>
#include <fstream>
#include <cmath>

#include "nlohmann/json.hpp"

using json = nlohmann::json;

using namespace std;

int main() {
  cout << "Hello World!";
  return 0;
}

I get this error:
**fatal error: 'nlohmann/json.hpp' file not found**

I am running Visual Studio Code on a Mac I believe its being compiled using clang

**Comment by nlohmann** [comment]
Where did you put the `json.hpp` file?

**Comment by Honorable22** [comment]
Inside of a folder labeled nlohmann and then that is inside of a folder labeled include.

**Comment by nlohmann** [comment]
I am not familiar with Visual Studio Code. Maybe change the include to `#include <nlohmann/json.hpp>` and try to set the include path to your project path.

**Comment by Honorable22** [comment]
Yes I tried to change include to <nlohmann/json.hpp>, it didn't make a difference.

**Comment by nlohmann** [comment]
What’s the include path? Which build system are you using?

**Comment by Honorable22** [comment]
"includePath": [
                "${workspaceFolder}/**"
            ],

using clang as the build system

**Comment by nlohmann** [comment]
I'm sorry, I have no idea how to fix this error as it is not related to this library. Please seek help in a forum for VS Code.

**Comment by shivam-51** [comment]
@Honorable22 Did you get any solution?

**Comment by Honorable22** [comment]
No. I did not get an solution.

**Comment by shivam-51** [comment]
Never mind, My code compiles now :)

**Comment by Honorable22** [comment]
What was your solution?

**Comment by shivam-51** [comment]
> What was your solution?

First I had to install the nlohmann_json package from apt `sudo apt install nlohmann-json-dev `
then simply g++ file.cpp

**Comment by Honorable22** [comment]
Thank you for sharing.

**Comment by kevinmukuna** [comment]
if you experience the same issue. you can solve it by adding (nlohmann-json) the path to` c_cpp_properties.json` like this

```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**",
                "/opt/homebrew/Cellar/nlohmann-json/3.10.5/include/"
            ],
           ...
          ...
```

` c_cpp_properties.json` can be found in your current working dir under `.vscode` dir

**Comment by maxpain** [comment]
@kevinmukuna didn't help :(

**Comment by HamedGhorbaniOc** [comment]
I tried installing nlohmann json and some files found missing in /usr/include/nlohmann. I used sudo apt-get install nlohmann-json3-dev for installation and it was success. However some files are missing. My system details:
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
Architecture is arm64.
Can anyone please help to get it resolved?

**Comment by anu-n87** [comment]
I tried installing nlohmann json and some files found missing in /usr/include/nlohmann. I used sudo apt-get install nlohmann-json3-dev for installation and it was success. However some files are missing which I use in my code and hence the code is having compilation issues. I tried copying those files from other system. But it did not work :( My system details:
Distributor ID: Ubuntu
Description: Ubuntu 20.04.5 LTS
Release: 20.04
Codename: focal
Architecture is arm64.
Can anyone please help to get it resolved?

@nlohmann : Could you please help on this?

**Comment by nlohmann** [comment]
I am not maintaining this package. Please contact the maintainer.

**Comment by anu-n87** [comment]
> I am not maintaining this package. Please contact the maintainer.

@nlohmann Thanks for the reply. Can I please know the details of the maintainer?

**Comment by nlohmann** [comment]
I do not know. You should be able to look this up in your distro.

**Comment by vidyulshah** [comment]
When I do sudo apt install nlohmann-json-dev
It give me this:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package nlohmann-json-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
Any other solution or stable branch available?

**Comment by aseem-heg** [comment]
`sudo apt install libstdc++-12-dev` this also did not resolve this error. 
still getting error 
```
.plugin_symlinks/flutter_secure_storage_linux/linux/include/json.hpp:18:8: error: macro name missing
/home/aseem/code/pangea_flutter/linux/flutter/ephemeral/.plugin_symlinks/flutter_secure_storage_linux/linux/include/Secret.hpp:12:17: error: implicit instantiation of undefined template 'std::basic_string<char>'
/home/aseem/code/pangea_flutter/linux/flutter/ephemeral/.plugin_symlinks/flutter_secure_storage_linux/linux/include/Secret.hpp:57:25: error: use of undeclared identifier 'nlohmann'
```
