### ISSUE TITLE
Check if a key exists

### ISSUE THREAD

**Issue by tawmoto** [nlohmann/json#2191]
Hi,

Is there a method to check if a key exists? Other than using `.at()` and catching the exception?
Sometimes I get a field named `error` in the json response and I would like to check it also.

Thanks.

**Comment by nlohmann** [comment]
There is a contains(key) member function.

**Comment by tawmoto** [comment]
> contains(key)

Great, I don't know how I missed it. I was searching for "exists" or smth. :-)
Thanks a lot!
