### ISSUE TITLE
Exception Unhandled out_of_range error

### ISSUE THREAD

**Issue by duojet2ez** [nlohmann/json#2197]
Hello,

Thanks for this library and for answering questions!!

The library was working perfectly when I was working without an IDE. I just brought my files into visual studio and am getting the following error when trying to cout from my .json file:

Unhandled exception at 0x75754402 in Epic Disaster Story.exe: Microsoft C++ exception: nlohmann::detail::out_of_range at memory location 0x009CE6C0. occurred

It takes me to json_sax.hpp and shows the following code where the error occurred:
```

JSON_THROW(*static_cast<const detail::invalid_iterator*>(&ex));
```

In my code this occurs when I try:
```
std::cout << j["pages"][0]["text"]; 
 ```

I believe the json file is formatted properly as I had no problems without the IDE...

**Comment by nlohmann** [comment]
I would need more information to diagnose this. What is the `what()` string of the exception? Can you provide a code example?

**Comment by Journeyman-dev** [comment]
Same exception in Visual Studio 2019. The error occurred for me when trying to stream into the `json` directly from an `std::fstream`. To view the What() string you asked for, I had to use debugging tools. 

```
[json.exception.parse_error.101] parse error at line 115, column 9: syntax error while parsing object - unexpected string literal; expected '}'
```

Just like duojet2ezz, the `json` file I am using has no syntax errors, as I have checked it with multiple validators.

raw text:
https://pastebin.com/iEzCy6fW

**Comment by duojet2ez** [comment]
It appears to be working now. Looks like it doesn't like copying and pasting text in the string in the json file... So when I type in my text it works.. but copying it from another document does not.

**Comment by nlohmann** [comment]
Thad is odd. No, this is not a known issue. The library perfectly supports UTF-8 - maybe your editor adds some weird bytes or encoding when copy/pasting? Maybe you can attach a working and non-working file so we can look at the binary diff?

**Comment by duojet2ez** [comment]
Which files from my project would you like? Just the json... one working and one that does not work?

**Comment by nlohmann** [comment]
That sounds like your editor replaces some characters. Which editor do you use?

About the file: Please attach a file that does work if you read it directly, but does not work after copy/pasting.
