### ISSUE TITLE
JSON incorrectly serialized

### ISSUE THREAD

**Issue by avin-kavish** [nlohmann/json#2198]
I wrote the JSON to a file like this,

```c++
ofstream file("foo.json");
file << foo->serialize() << endl;
```
(`serialize()` returns `nholmann::json`)

and the file ended up looking like,

```
"[[{\"x\":27,\"y\":0},{\"x\":27,\"y\":1}],[{\"x\":27,\"y\":0}, ....
```

I think it gets serialized twice and ends up writing a string. But if I pipe `serialize()` to `std::cout` the console output is formatted properly.

I would want it to look like

```json
[[{"x":27,"y":0},{"x":27,"y":1}],[{"x":27,"y":0},
```

How can I achieve this?

**Comment by nlohmann** [comment]
That looks odd. Can you make sure `serialize()` returns a `json`?

**Comment by avin-kavish** [comment]
Whoops, I had put `.dump()` in that function but it compiled because string can be casted to json I guess...

Thanks.

**Comment by nlohmann** [comment]
That explains the double escaping. :)
