### ISSUE TITLE
Sending to a function a reference to a sub-branch

### ISSUE THREAD

**Issue by tawmoto** [nlohmann/json#2200]
Hi,

I am trying to send a reference to sub-branch (I don't know the exact name for this, sorry) of a json to a function. This is because I have a huge json and I don't want to split it in functions.

```
void func(json &j)
{
    j["branch"] = "abc";
}

int main()
{
json j2 = {{"pi", 3.141},
               {"happy", true}};

func(j2["tree"]);
}
```

and I expect
```
{
    "happy": true,
    "pi": 3.141,
    "tree": {
        "branch": "abc"
    }
```

Is this the proper way of doing it?
Thank you

**Comment by tawmoto** [comment]
I managed to make it work with
```
void func(json &j)
{
    j["branch"] = "abc";
}
```

Just want a small confirmation that this is the correct way of doing this. thank you

**Comment by nlohmann** [comment]
Yes, passing a reference is the way to go.

**Comment by tawmoto** [comment]
> Yes, passing a reference is the way to go.

Thank you, as I use it every day I am amazed how fantastic this library is!
