### ISSUE TITLE
array_index possible out of range

### ISSUE THREAD

**Issue by t-b** [nlohmann/json#2205]
Due to my work on #2203 I stumpled upon:

https://github.com/nlohmann/json/blob/29ad2178c666ad6eea7b653e44454bb54607a998/single_include/nlohmann/json.hpp#L24000-L24010

and I'm really not understanding why it is `if (JSON_HEDLEY_UNLIKELY(static_cast<size_type>(idx) > parent.size())) ` and not `if (JSON_HEDLEY_UNLIKELY(static_cast<size_type>(idx) >= parent.size()))`. For zero-based indizes we need to be smaller than the size or?

**Comment by nlohmann** [comment]
Good question. From the JSON Patch specification (https://tools.ietf.org/html/rfc6902#section-4.1):

> The specified index MUST NOT be greater than the number of elements in the array. If the "-" character is used to index the end of the array (see [RFC6901]), this has the effect of appending the value to the array.

I interpret these sentences that (1) passing the size of the array as index is allowed (as that index is not greater than the number of elements) and that (2) that value could be interpreted just like `-`, meaning we would append to the array.

So this code:

```cpp
#include <iostream>
#include "json.hpp"

using json = nlohmann::json;

int main() {
    json j = {0, 1, 2};
    json add = {{{"op", "add"}, {"path", "/3"}, {"value", 99}}};
    
    auto result = j.patch(add);
    
    std::cout << result << std::endl;
}
```

prints

```json
[0,1,2,99]
```

And `[{"op":"add","path":"/3","value":99}]` is treated the same as `[{"op":"add","path":"/-","value":99}]`.

Do you agree?

**Comment by t-b** [comment]
@nlohmann Yes, I agree.

Just for future reference: In your example "(parent.begin() + static_cast<difference_type>(idx)) == parent.end()" holds and parent.end() can be passed to insert.
