### ISSUE TITLE
Addint support for complex type

### ISSUE THREAD

**Issue by pfeatherstone** [nlohmann/json#2207]
Could we add official support for complex type. I don't know if this requires a fully blown PR as the code is so small:

```
namespace std {
    template<typename R, typename std::enable_if<std::is_arithmetic<R>::value>::type* = nullptr>
    void to_json(nlohmann::json& j, const complex<R>& d)
    {
        j = {d.real(), d.imag()};
    }

    template<typename R, typename std::enable_if<std::is_arithmetic<R>::value>::type* = nullptr>
    void from_json(const nlohmann::json& j, complex<R>& d)
    {
        d.real(j.at(0).get<R>());
        d.imag(j.at(1).get<R>());
    }
}
```

**Comment by nlohmann** [comment]
I'm hesitant, because this would define the serialization format for a standard type where there is not canonic serialization. You propose serializing as array, but an object would also make sense, e.g.

```json
{"complex": {"real": 1, "imag": 0}}
```

Though the user could override the defaults, I am not sure whether the library should propose a default.

Any opinions on this?

**Comment by pfeatherstone** [comment]
Good point. It seems msgpack also doesn’t define a spec for complex numbers. Weird. As engineers we use them almost just as often as real numbers so why do these specs not care about complex numbers??

**Comment by pfeatherstone** [comment]
I guess if you start doing that, then people will want quaternions and other exotic things and then it quickly becomes a math serialisation library.

**Comment by nlohmann** [comment]
The good thing is that you can realize the conversion with the few lines above, and I think this issue should pop up in any search for issues with the word "complex".

**Comment by pfeatherstone** [comment]
As a json string i would expect to see something like
```
{
"z": 1 + 2i
}
```
For example. But no other json library, including the built-in javascript JSON library, would understand that without adding custom parsers. We need to open an issue on the JSON spec if that exists.

**Comment by nlohmann** [comment]
The JSON specification is unlikely to ever change. The RFC has been updated every once in a while, but never were new types added.
