### ISSUE TITLE
free(): invalid pointer error in GCC 5.2.1

### ISSUE THREAD

**Issue by zer0-x** [nlohmann/json#221]
My old code using GCC 4.8.4 works fine. But today I upgrade my system and recompile the code.
It doesn't run anymore and crashes when I retrieve my data.
What should I do to investigate this more?
![snapshot1](https://cloud.githubusercontent.com/assets/11463928/13560828/f9f60eac-e456-11e5-9e6a-fd5681f274c3.png)

**Comment by nlohmann** [comment]
Can you please create a small code example so I can check? If this is not possible, can you run your code with Valgrind to get better error messages?

The testsuite is also run with Valgrind and does not detect any memory issues. On Travis, one instance runs with GCC 5.3.0.

**Comment by zer0-x** [comment]
I resolved the issue, it turned out nothing related to the library at all :smile: 
The variable I used in assignment was copied by memcpy (using copied non-Plain Old Data so it crashes).
Somehow the old GCC still supports that trick, which made me believe my code was alright.
Thanks for the suggestions and having created the amazing library.
