### ISSUE TITLE
Convert to Qt QVariant 

### ISSUE THREAD

**Issue by pylvain** [nlohmann/json#2216]
Hi, i'm currently working with JSON in Qt/Qml. Because of Qt poor support for JSON, i'm using this library. So, i have to convert this library's default type, which is using stl types, to a QVariant/QJsonValue, which is using Qt types, and vice versa. It's ok, but it feels like a waste of computer power and memory. Just out of curiosity, is it possible to work something out by modifying this definition :
```C++ 
template<template<typename U, typename V, typename... Args> class ObjectType =
         std::map,
         template<typename U, typename... Args> class ArrayType = std::vector,
         class StringType = std::string, class BooleanType = bool,
         class NumberIntegerType = std::int64_t,
         class NumberUnsignedType = std::uint64_t,
         class NumberFloatType = double,
         template<typename U> class AllocatorType = std::allocator,
         template<typename T, typename SFINAE = void> class JSONSerializer =
         adl_serializer,
         class BinaryType = std::vector<std::uint8_t>>
class basic_json;
```

with something like
``` C++
class ObjectType = QJsonValue::Object
class StringType = QJsonValue::String 
etc ...
```

I'm no C++ expert, and i cannot make this work on my own, this is a bit too advanced for me.

Thanks

**Comment by ArtemSarmini** [comment]
Make your own alias like
`using qt_json = basic_json<QMap, QVector, QString, ...>;`

**Comment by pylvain** [comment]
Thanks, simply that seems to work :
```C++
using myjson = basic_json<QMap,QVector,QString,bool,int,unsigned int,double>;
```
Silly me was trying to use QJSonValue:: thinking it was refering to types, but that was just an enum. Thank you !

**Comment by sandroandrade** [comment]
> Thanks, simply that seems to work :
> 
> ```c++
> using myjson = basic_json<QMap,QVector,QString,bool,int,unsigned int,double>;
> ```
> 
> Silly me was trying to use QJSonValue:: thinking it was refering to types, but that was just an enum. Thank you !

Is this currently working? Using QVector as array type yelds the following error:

```
/usr/include/nlohmann/json.hpp:560:11: error: wrong number of template arguments (2, should be 1)
  560 |     using array_t = ArrayType<basic_json, AllocatorType<basic_json>>;
      |           ^~~~~~~
```
Probably because QVector doesn't support passing the allocator as template parameter. Any hint? Similar errors occur for QMap type.

Thanks in advance,

**Comment by nlohmann** [comment]
You could define a wrapper type that just consumes the `AllocatorType` argument. Something like

```cpp
template<typename T, typename AllocatorType>
class q_vector_wrapper<T, AllocatorType> : public QVector<T>
{};
```

**Comment by Dariusz1989** [comment]
Can this be elaborated a bit? I want to support QVector<T> etc etc but I'm hitting walls left and right.
Any hints? how to declare/how to use? etc?
Tried with :
```
namespace nlohmann {
    template<>
    struct adl_serializer<QString> {
        static void to_json(json &j, const QString &s) {
            j = s.toStdString();
        }

        static void from_json(const json &j, QString &s) {
            s = QString::fromStdString(j.get<std::string>());
        }
    };

    template<typename T>
    struct adl_serializer<QVector<T>> {
        static void to_json(json &j, const QVector<T> &data) {
            for (const auto &element: data) {
                j.push_back(element);
            }
        }

        static void from_json(const json &j, QVector<T> &data) {
            for (const auto &element: j) {
                data.push_back(element.get<T>());
            }
        }
    };
}
```
but lots of errors 
```
error C2908: explicit specialization; 'nlohmann::json_abi_v3_11_2::adl_serializer<T,void>' has already been instantiated
        with
        [
            T=QString
        ]
        error C2766: explicit specialization; 'nlohmann::json_abi_v3_11_2::adl_serializer<T,void>' has already been defined
        with
        [
            T=QString
        ]
        : note: see previous definition of 'adl_serializer<QString,void>'
        ```
        etc etc

**Comment by Romain-Donze** [comment]
Hello,

To address the performance limitations of QJsonDocument when converting between JSON streams and QVariant, I’ve developed a lightweight library called QJsonVariant:

🔗 https://github.com/Romain-Donze/QJsonVariant

This library provides direct, stream-based conversion between JSON/CBOR and QVariant without the overhead of full QJsonDocument parsing or serialization. In certain scenarios, it can be up to 2x faster than QJsonDocument.

I’d love any feedback, suggestions, or contributions!
