### ISSUE TITLE
Enormous array created when working with map<int,T>

### ISSUE THREAD

**Issue by ralwing** [nlohmann/json#2220]
When json array object is indexed with some numeric value it creates an array containing nulls, and one single value.

```
#include <nlohmann/json.hpp>
#include <boost/container/flat_map.hpp>
#include <iostream>

int main()
{
    boost::container::flat_map<int, int> elems;
    elems.emplace(1000000, 2);
    nlohmann::json json;
    for (const auto& point : elems)
    {
        json["data"][point.first] = point.second;
    }
    std::cout << json.dump(2);
}
```
Which outputs:
```
{
  "data": [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null
[...]
```

[LiveExample](https://gcc.godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAM1QDsCBlZAQwBtMQBGAFlICsupVs1qhkAUgBMAISnTSAZ0ztkBPHUqZa6AMKpWAVwC2tQVvQAZPLUwA5YwCNMxLgE5SAB1QLC62nsMTQS8fNTorG3sjJxdOdyUVMNoGAmZiAgDjU05FZUxVPxS0ggi7R2c3RVT0zKCchWqS6zLoiriASkVUA2JkDgByKQBma2RDLABqcSGdWlZUBCMRWgB6PgU6ADoEDw9p7HEABgBBYdHxzCmZh1RvAhW0emZm4hWqYQIAfSWPbd39o6nSQjWhjAyTaY6dQNYiYZhGAEnQEAN1QeHQEyMEHagPEAHZZCcJsSJjc7iAUHRUi8Ke9mF8fpDrARSBNmfsJnkjAppoTjiTOexuZtMEYPMI%2BhBOIcZbLWZIcUM%2BQK5gslrRTCB1nQJtraLzAQKaMQJhBHg0JswDEQpAA2CZeZkTECC0UKHFEkn45UCkl68QAVlkkkk6HpzCkkkDABFA9JHfRNlQ8MQGjGrtGHWjE0pHugDZ7ifjY4WJg10BS0NarjpIbqNrRNuhjB4IAqC6c8SXTicnUtrNjcQTDZjB0qh9H%2Bp1WCB%2BgH%2BqRTP1DgvULPazI5GXur1LsNOAuCLOV%2B1OgBrECSPGbAAcN6GeNctpvtsknB4AdtAaEs%2B4C6XK6kGu/QLgoICHKQR7LlOpBwLASBoGKeDsGQFBmqgSEoSgwiiJ8BDEAYtBnqQyasAQzhgRADjHguDjWGkACes4HqQiFGFoBAAPJzEx0GkFg6rAOwNH8Sm%2BRqMimBgXxmAAB75NaAwscyygiaweAOMQjF6FgzGHsQeBGHpnQ0PQTBsBwPD8IIOFiHIchCBpYGwLQ8IcGSDSkJJLj9JweIHp0ECuexICqosyyfHqXkVPhhFnqeQEeEk0mgXkBQaBA5i1NkpDmKUUQxME3i%2BHQ2VFaEfj5eUsS5IkhSNGV9RpUkRTpFVrQ1Q0xSNVUxTtYVnCdBsPR9IIADuIhcUlACStA0MZP5zv%2BInAbJL4ALS2twExjCIwCmrFRHtKauCECQUzAjkEx6JhzgXUMg3XfZMiHjRCUXpI3CbHiP3SjeMrvrarj3otf6Lits6geBkFvbBMCICAzCeWhmD4EQBkVjkpmMCwwlWQITV1RlWX6FkZjaP1bSeMVSQ9SEJW0JTnXNfV3Wk3UtXiazbXNAVVNdTU7M5QLTSRNVXAJTOS3g3xq0bVtO22QdBFHRMxwWgAangmBjXdECnej91XTdHjIXd%2B7tK90HvZetqbK%2B3A3q4wKSLaz6HI%2BvBS2DAGrpDijQ1BJ5w/AEBIN0BAeNa5CUIhptYTkqNnTV2PmXjvBjVpHgLVL84y4BwH7hMY2EAgExrbam3bbtojK3Flsw9b57gd9PCSIckg3tKhxDI7vfft7y2y/7YEQUHMFwQjckKejMcQGkwAKAACiIygMAgqBjUuLFx8h9J%2BCvNisOvm%2B%2B6xGHxxUNfAHhKvEbvKGcdaJ9byJ0/IMcxCL/778pPgS4LlTrjSyvACZCD2igZ68h1IOGclAYK7lbieW8sxfyE8EGhXmOFDUkUGzRRcIdeKnRUBJT8ClLoI1LJVH/ofNeG9X6%2BRgrnIeBdZwVyrorPaddVbYHksga0519Zo3OhbJ6m4XqNxPM3duoMWF%2BxAgHMeb1pyzkkHIoC/tx4JW8j4DQ3AgA%3D%3D%3D)

#### What is the expected behavior?

The value map should be created inside instead.

- Compiler: MS VS, clang
- Operating system: windows

#### Which version of the library did you use?

- [x] latest release version 3.7.3
- [x] other release - please state the version: ___

**Comment by nickaein** [comment]
This is expected behavior as you are implicitly creating  `data` as an array.

JSON only allows string keys. Instead, you can try his:

```cpp
json["data"][std::to_string(point.first)] = point.second;
```

which outputs:
```
{
  "data": {
    "1000000": 2
  }
}
```

**Comment by ralwing** [comment]
Thanks for You answer.

**Comment by nlohmann** [comment]
> But don't You think all arrays should be implemented as a map, thus such cases wouldn't cause errors? Arrays should be created explicitly.

The library treats a JSON value like the combination of a `std::vector` and a `std::map`. Both implement `operator[]`. If you pass a string, we assume a JSON object, and if you pass a number, then we assume a JSON array. As `operator[]` does not perform bound checking, both implementation must return a reference to the value at the given argument. We decided to implement both like `std::map`, adding a value at the respective argument. As we cannot only have a vector value at some index, we need to fill all values until that index.

Sorry that this may appear surprising, but these are the reasons for that design decision.
