### ISSUE TITLE
replace emplace

### ISSUE THREAD

**Issue by geromueller** [nlohmann/json#224]
GCC 4.7 does not support std::map::emplace.
On scientific clusters older compilers are often found, e.g. on debian wheezy.

**Comment by geromueller** [comment]
Just saw the 4.8 bugs section..

**Comment by nlohmann** [comment]
Hi @geromueller, I understand your problem (I'm often stuck with older GCC versions myself), but making the library run with GCC 4.7 would mean dropping a lot of features.
