### ISSUE TITLE
Move semantics with std::initializer_list

### ISSUE THREAD

**Issue by ahorn** [nlohmann/json#225]
[Line 1564](https://github.com/nlohmann/json/blob/49dc2dff68abb4bbf1f3ee8b0327de7d0a673d16/src/json.hpp#L1564) uses move semantics when working with `std::initializer_list`. But when I debug the type of, say, `element[1]`, using clang++ 3.5 and compiling the unit tests, the compiler deduces a const reference type (see also [std::initializer_list::begin](http://en.cppreference.com/w/cpp/utility/initializer_list/begin)). There are no meaningful semantics for moving const references so I wanted to double check with you guys.

**Comment by nlohmann** [comment]
@ahorn you are right - http://stackoverflow.com/a/8193157/266378 seems to mention the same issue.

**Comment by nlohmann** [comment]
Thanks for noting! I removed the `std::move` calls to remove the appearance that move semantics is applied.
