### ISSUE TITLE
Update documentation about Homebrew installation and CMake integration - Homebrew

### ISSUE THREAD

**Issue by DataHearth** [nlohmann/json#2326]
The actual documentation is wrong. The provided command line to install `nlohmann_json` => `brew install nlohmann_json` isn't the correct one.

#### What is the issue you have?
The issue #1576 describe and resolved the problem. But the documentation on the [github page](https://nlohmann.github.io/json/) isn't updated for `Homebrew`. 
As said, to install the library with `Homebrew`, I should do:
```shell
brew tap nlohmann/json
brew install nlohmann_json
``` 

The second command isn't working properly. To resolve it, refer to the issue #1576. 
So, the documentation should be with `brew install nlohmann_json` but with `brew install nlohmann-json` (note the dash instead of the underscore).

#### Please describe the steps to reproduce the issue.

1. Follow the [steps](https://nlohmann.github.io/json/integration/package_managers/#homebrew) provided by the documentation to install the lib with `Homebrew`
2. Check the path `/usr/local/Cellar/nlohmann_json`
3. The lib folder containing the cmake isn't here

#### What is the expected behavior?
Lib folder should be available with the CMake configuration for integration with `find_package()`.

#### And what is the actual behavior instead?
Lib folder isn't present.

#### Which compiler and operating system are you using?
- Compiler:
```shell
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
- Operating system:
```shell
OS: MacOS Catalina
Version: 10.15.5
Laptop: MB pro 16" (sept 2019)
```
- Homebrew version: `2.4.9`

#### Which version of the library did you use?

- [x] latest release version 3.9.0
- [ ] other release - please state the version: ___
- [ ] the `develop` branch

**Comment by nlohmann** [comment]
Thanks! Good catch!
