### ISSUE TITLE
Reading ordered_json from file causes compile error

### ISSUE THREAD

**Issue by jin-clova** [nlohmann/json#2331]
#### What is the issue you have?
Code below is causing compilation error.
```
    std::ifstream i(path);
    ordered_json j;
    i >> j;
```
(20462, 53) No viable conversion from 'typename basic_json<nlohmann::ordered_map, std::vector, basic_string<char>, bool, long long, unsigned long long, double, std::allocator, adl_serializer, vector<unsigned char, allocator<unsigned char> > >::object_t::iterator' (aka '__wrap_iter<std::__1::pair<const std::__1::basic_string<char>, nlohmann::basic_json<nlohmann::ordered_map, std::vector, std::__1::basic_string<char>, bool, long long, unsigned long long, double, std::allocator, adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > > *>') to 'const std::__1::basic_string<char>'

#### Please describe the steps to reproduce the issue.

1. Write the code above.
2. Try build
3. Boom!

#### Can you provide a small but working code example?

It's not working, but see above for the code.

#### What is the expected behavior?

Successfully built, and read the json file.

#### And what is the actual behavior instead?

Compile error

#### Which compiler and operating system are you using?

- Compiler: xcode
- Operating system: mac

#### Which version of the library did you use?

- [x] latest release version 3.9.0
- [ ] other release - please state the version: ___
- [ ] the `develop` branch

#### If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

- [x] yes
- [ ] no - please copy/paste the error message below

I can compile this project and pass all unit tests, but I don't think the tests cover this case.

**Comment by nlohmann** [comment]
This is fixed with #2319.
