### ISSUE TITLE
compiler warning

### ISSUE THREAD

**Issue by laoshaw** [nlohmann/json#2341]
json.hpp:15411:15; warning: comparing floating-point with '==' or '!=' is unsafe[-Wsafe-equal]

if(value==0) //+-0

not sure if this is a really bug but if value is a float then it should not compare to 0 directly.

**Comment by nlohmann** [comment]
No, in that setting I *really* want to check whether the value is *exactly* 0. I am not sure how to convince the compiler that I don't want to be warned there. We already do

```cpp
// disable float-equal warnings on GCC/clang
#if defined(__clang__) || defined(__GNUC__) || defined(__GNUG__)
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wfloat-equal"
#endif
```

Should I also suppress `-Wsafe-equal`?
