### ISSUE TITLE
Error: an attribute list cannot appear here     JSON_HEDLEY_DEPRECATED_FOR

### ISSUE THREAD

**Issue by SylvainCorlay** [nlohmann/json#2342]
With nlohmann_json 3.8 and 3.9, including 3.9.1 (but not with earlier versions such as 3.7), we are getting the following error in our builds on OS X (xcode 8).

```
/Users/travis/miniconda/envs/xtl/include/nlohmann/json.hpp:23086:5: error: an attribute list cannot appear here
    JSON_HEDLEY_DEPRECATED_FOR(3.8.0, parse(ptr, ptr + len))
```

- [x] latest release version 3.9.1
- [x] other release - please state the version: 3.8.x, 3.9.x
- [ ] the `develop` branch

**Comment by SylvainCorlay** [comment]
A failing build when removing the constraints nlohmann_json<3.7:

**Comment by nlohmann** [comment]
Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

**Comment by SylvainCorlay** [comment]
Ok, it seems that you dropped support for xcode 8. Sorry for the noise.

**Comment by nlohmann** [comment]
No, no compiler support was consciously dropped. This seems to be an issue with Hedley. I will check.

**Comment by nlohmann** [comment]
So which exact compiler did you use?

**Comment by SylvainCorlay** [comment]
I was using the clang from the travis "xcode8" OS X image.

**Comment by nlohmann** [comment]
That image seems to be a bit abandoned by Travis and Homebrew. I am currently struggling to install CMake and Ninja there, so I'm not close to the error you reported yet...

**Comment by SylvainCorlay** [comment]
I just triggered a buld with xcode 8 for xtl: https://github.com/xtensor-stack/xtl/pull/199

This should show the issue.

Note: we are seeing this in other repositories, because we have the same pattern in many where we install our dependencies from conda.

**Comment by nlohmann** [comment]
Also using Hedley?

**Comment by SylvainCorlay** [comment]
We are not using Hedley.

**Comment by SylvainCorlay** [comment]
Here is the failing build: https://travis-ci.com/github/xtensor-stack/xtl/jobs/369629906

**Comment by ketgo** [comment]
I am also getting the same issue with clang-3.6. In fact all my clang builds are failing. Is that compiler not supported?

**Comment by t-b** [comment]
@ketgo Which json version are you using? Does it include https://github.com/nlohmann/json/commit/411fc3249b3e32b57469e28555b6d8cc323ecb27?

**Comment by ketgo** [comment]
@t-b No it does not. I am using v3.9.1

**Comment by nlohmann** [comment]
Can you please try again with the `develop` branch?

**Comment by JuanGarcia345** [comment]
@nlohmann the version in the `develop` branch works for me. I had the same issue with clang-3.[6-8].

By the way, thank you for the job you have done with this nice library.

**Comment by davidbrochart** [comment]
> Can you please try again with the `develop` branch?

I have the same issue, and it was solved by using the `develop` branch.

**Comment by davidbrochart** [comment]
Switching from Xcode 8 to Xcode 9 in Travis CI also solves the issue.

**Comment by ketgo** [comment]
develop branch worked for me. Thanks for the great package! :)
