### ISSUE TITLE
setprecision support

### ISSUE THREAD

**Issue by young66** [nlohmann/json#2362]
#### What is the issue you have?
i try to run the follow code
>`#include <iostream>`
>`#include <iomanip>`
>`json testj;`
>`testj["data1"] = 7.0000000001;//copy from var like 7.0`
>`//some more data in json`
>`testj["data2"] = 0.9999999999;//copy from var like 1.0`
>` cout << setprecision(2);`
>`cout << fixed;`
>`cout << "precision=2 fix :" << 1.1111111111111 << ", json: " << testj<< endl;`

#### Please describe the steps to reproduce the issue.

run the code

#### Can you provide a small but working code example?
yes ,see the sample 
>`#include <iostream>`
>`#include <iomanip>`
>`json testj;`
>`testj["data1"] = 7.0000000001;//copy from var with 7.0`
>`//some more data in json`
>`testj["data2"] = 0.9999999999;//copy from var with 1.0`
>` cout << setprecision(2);`
>`cout << fixed;`
>`cout << "precision=2 fix :" << 1.1111111111111 << ", json: " << testj<< endl;`

#### What is the expected behavior?
it should print 
`precision=2 fix :1.11, json: {"data1":7.00, etc... ,"data2":1.00}`

#### And what is the actual behavior instead?

but the output is 
`precision=2 fix :1.11, json: {"data1":7.0000000001, etc... ,"data2":0.9999999999}`
i try to test `setw` and `setfill`, it works; but doesn't work for `setprecision`

#### Which compiler and operating system are you using?

- Compiler: gcc.7.3.0
- Operating system: suse11.3

#### Which version of the library did you use?

- [ ] latest release version 3.9.1
- [x] other release - please state the version: 3.7.3
- [ ] the `develop` branch

**Comment by nlohmann** [comment]
It's not really a bug - the library has no option to change the output of floating-point numbers. If you use `testj.get<double>()` instead of `testj`, then it should work.

**Comment by young66** [comment]
sorry，i show this code ,just want to say `setprecision ` doesn't work.
my code is like this, i have update the code in issue.
>`json testj;`
>`testj["data1"] = 7.0000000001;//copy from var like 7.0`
>`testj["data2"] = 0.9999999999;//copy from var like 1.0`
>` cout << setprecision(2);`
>`cout << fixed;`
>`cout << "precision=2 fix :" << 1.1111111111111 << ", json: " << testj<< endl;`

**Comment by axtschmied** [comment]
Hello!

This topic has been closed due to inactivity, but it would be a very useful feature in my opinion as well.

**Comment by DinoMalpera** [comment]
We also need this. It would be very useful.
