### ISSUE TITLE
Using custom string.

### ISSUE THREAD

**Issue by armatti** [nlohmann/json#2398]
I've tried using custom containers with nlohmann::json. `ObjectType` and `ArrayType` can be swapped, but changing `StringType` breaks creating json from most types.

Here's a minimal, non-functional string implementation, that builds as long as you don't try to create a json from other types than string literals: [https://godbolt.org/z/GTvn8T](https://godbolt.org/z/GTvn8T)

If I read correctly `nlohmann::detail::detector` fails to find a matching `to_json` function, but I don't understand how changing `StringType` has anything to do with it. Should `StringType` be replaceable? Does it then need a custom serializer or what's the trick?

**Comment by nlohmann** [comment]
I can reproduce your findings, but not yet understood the error.

**Comment by nlohmann** [comment]
I could create a minimal wrapper around `std::string` with which I could compile your example:

```cpp
class my_string {
  public:
    using value_type = std::string::value_type;
    using size_type = std::string::size_type;

    my_string() {}
    my_string(const value_type* s) : _s(s) {}
    my_string(std::initializer_list<value_type> ilist) : _s(ilist) {}
    ~my_string() {}

    const value_type* data() const noexcept {
        return _s.data();
    }

    size_type size() const noexcept {
        return _s.size();
    }

    void clear() noexcept {
        _s.clear();
    }

    void push_back(size_type ch) {
        _s.push_back(ch);
    }

    friend bool operator<(const my_string& lhs, const my_string& rhs)
    {
        return lhs._s < rhs._s;
    }

  private:
    std::string _s;
};
```

I am not sure whether it is complete, but it helped me find a problem in your code. After removing the constructor

```cpp
my_string(char){}
```

your code compiles.

**Comment by armatti** [comment]
Sorry for not updating the issue sooner. Yes, thanks, removing that constructor does help. Additional gripe was with `nlohmann::detail::int_to_string` which was solved by defining an overload of the function with the custom string_type.

Looks like int_to_string was reported also in https://github.com/nlohmann/json/issues/2059 and commit https://github.com/nlohmann/json/commit/aeef50709e6a49f5807cdf787473ca8adecbe23c linked as a fix, but not sure how that is supposed to work: https://godbolt.org/z/aEWbM6joo

**Comment by gregmarr** [comment]
@armatti you're right that the referenced commit does not do what it was intended to do.  ADL is for the "arguments" of the function, not the return type.  However, looks like you can use ADL to replace this function instead, which is what it sounds like you did.

    void int_to_string(my_string& str, std::size_t value)
    {
        str = {};
    }

FYI @dota17

**Comment by armatti** [comment]
As problems could be solved without modifying nlohmann::json, I'm happy to close this issue.
