### ISSUE TITLE
Error ONLY in release mode

### ISSUE THREAD

**Issue by nyckmaia** [nlohmann/json#2425]
My C++ application compile and runs great without any warnings or errors on DEBUG mode.
When I try to compile it on RELEASE mode, I got this compile time error:

```
Symbol not resolved __imp_strtod
```
```
app.obj:-1: error: LNK2019: s¡mbolo externo nÆo resolvido, __imp_strtod, 
referenciado na fun‡Æo "private: enum nlohmann::detail::lexer_base<class nlohmann::basic_json<class std::map,class std::vector,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,bool,__int64,unsigned __int64,double,class std::allocator,struct nlohmann::adl_serializer,class std::vector<unsigned char,class std::allocator<unsigned char> > > >::token_type __cdecl nlohmann::detail::lexer<class nlohmann::basic_json<class std::map,class std::vector,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,bool,__int64,unsigned __int64,double,class std::allocator,struct nlohmann::adl_serializer,class std::vector<unsigned char,class std::allocator<unsigned char> > >,class nlohmann::detail::input_stream_adapter>::scan_number(void)" (?scan_number@?$lexer@V?
$basic_json@Vmap@std@@Vvector@2@V?$basic_string@DU?$char_traits@D@std@@V?
$allocator@D@2@@2@_N_J_KNVallocator@2@Uadl_serializer@nlohmann@@V?$vector@EV?$allocator@E@std@@@2@@nlohmann@@Vinput_stream_adapter@detail@2@@detail@nlohmann@@AEAA?AW4token_type@?$lexer_base@V?$basic_json@Vmap@std@@Vvector@2@V?$basic_string@DU?$char_traits@D@std@@V?
$allocator@D@2@@2@_N_J_KNVallocator@2@Uadl_serializer@nlohmann@@V?$vector@EV?
$allocator@E@std@@@2@@nlohmann@@@23@XZ)
```

**How can I fix it?**

**My system:**
- Windows 10 x64
- MSVC 2019 x64
- Library version 3.9.1

**Comment by nlohmann** [comment]
Do you have a code example?

**Comment by nyckmaia** [comment]
@nlohmann I really would like to give you my source-code as example, but I use the `nlohmann::json` library in a lot of sparse places in this file called `app.cpp`...in a way that is very difficult to try to isolate the problem.

I can copy and paste the entire `app.cpp` here, but it have a 1200 lines of code...

Is there another way that I can give you some information about my problem?

It compiles and run perfect in the DEBUG mode...
**Why this compile time error would happen only when I switch to RELEASE mode?**

**Comment by karzhenkov** [comment]
@nyckmaia, you can use [godbolt](https://godbolt.org/z/6Worxf) to present your code.

**Comment by nyckmaia** [comment]
That you @karzhenkov, that's a good tool. 
But as I said, my code is too long... and I think it is not fair for someone to try to find the error in this block of code.

https://godbolt.org/z/3TEEEW

I was thinking that may be I could try some compiler debug options that can help me to identify where are this release error.

Well...I will try to isolate some blocks and compile using RELEASE MODE...
Thank you for your patience...

**Comment by karzhenkov** [comment]
This looks as if your program is compiled with `/MD` to be linked against the dynamic runtime (`msvcrt.lib`) but actually is linked against the static runtime (`libcmt.lib`). Having the following `example.cpp`:
```
#include <cstdlib>

int main()
{
    std::strtod("0", nullptr);
}
```
your problem can be reproduced as follows:
```
C:\work>cl example.cpp /c /MD
example.cpp

C:\work>link example.obj /nodefaultlib:msvcrt libcmt.lib 
example.obj : error LNK2019: unresolved external symbol __imp__strtod referenced in function _main
example.exe : fatal error LNK1120: 1 unresolved externals
```
The problem probably is not in the `nlohmann::json` but in your project configuration (the `vcxproj` file). You can present the configuration file as a [gist](https://gist.github.com) if you didn't solve the problem yet.

**Comment by nlohmann** [comment]
Thanks for digging into this! I'll close this issue as it is not related to this library.
