### ISSUE TITLE
Trouble using parser with initial dictionary

### ISSUE THREAD

**Issue by calkinssean** [nlohmann/json#243]
Hey guys, I'm trying to use this parser along with OneSignal (push notifications) and I'm having a little trouble. It doesn't help that I'm completely new to C++ but I was wondering if you could give me a little point in the right direction. The data I'm trying to parse looks like this: 
{
   "coinsAdded": "10",
   "sound": "default",
   "title": "test"
}
and it's in a const char* called additionalData.
Any help you guys could give would be awesome.
Thanks, and great work!

**Comment by calkinssean** [comment]
I forgot to mention I'm using xCode 7.3.1

**Comment by nlohmann** [comment]
Hi @calkinssean,

I am not sure whether I understand you correctly. But it seems to me that this is what you want:

```cpp
#include <json.hpp>

using nlohmann::json;

int main()
{
	// your data as const char*
	const char* additionalData = "{\"coinsAdded\": \"10\", \"sound\": \"default\", \"title\": \"test\"}";

	// create a JSON object
	json j = json::parse(additionalData);

	// pretty-print
	std::cout << j.dump(4) << std::endl;
}
```

**Comment by calkinssean** [comment]
That did it, sorry for the simplicity of my question, C++ just isn't my field at all. But you guys have done some great work here and the library works beautifully.
