### ISSUE TITLE
Using std::wstring as StringType fails compiling

### ISSUE THREAD

**Issue by SparkyPotato** [nlohmann/json#2459]
#### What is the issue you have?

```c++
reference at(const typename object_t::key_type& key)
    {
        // at only works for objects
        if (JSON_HEDLEY_LIKELY(is_object()))
        {
            JSON_TRY
            {
                return m_value.object->at(key);
            }
            JSON_CATCH (std::out_of_range&)
            {
                // create better exception explanation
                JSON_THROW(out_of_range::create(403, "key '" + key + "' not found"));
            }
        }
        else
        {
            JSON_THROW(type_error::create(304, "cannot use at() with " + std::string(type_name())));
        }
    }
```
Compilation fails with the `JSON_THROW`, since `key_type` is assumed to have an `operator+` overload with a `const char*`, which `std::wstring` does not.

#### Can you provide a small but working code example?

```c++
using json = nlohmann::basic_json<std::map, std::vector, std::wstring>;
```

#### Which compiler and operating system are you using?

- Compiler: MSVC 19.27.29112
- Operating system: Windows 10

#### Which version of the library did you use?

- [x]  latest release version 3.9.1
- [ ] other release - please state the version: ___
- [ ] the `develop` branch

**Comment by nlohmann** [comment]
The library does not support std::wstring.

**Comment by AraHaan** [comment]
I mean wstring support is easy just have to have optional win32 code for things like ``MultiByteToWideChar`` and WideCharToMultiByte``
