### ISSUE TITLE
Update long-term goals

### ISSUE THREAD

**Issue by nlohmann** [nlohmann/json#246]
File https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#wanted is not up to date any more (locale-indepence is achieved, MSVC works, and Travis now also checks OSX).

**Comment by giordi91** [comment]
Hi mate, I am using the lib on VS 2015 should be up to date, or one update behind and not having any problem with it, worked out of the box. What kind of compiling error are you referring to?

M.

**Comment by nlohmann** [comment]
The MSVC job failed for several months, because of some weird (nonstandard) behavior of MSVC. It is fixed now, but I just forgot to remove it from the list. Good to know it works now out of the box! Could you give me the exact version you are using so I can reference it in the README file?

**Comment by giordi91** [comment]
I compiled my stuff at work too using version 14.0.24720.00 Update 1. Once
I get home I can tell you the other version aswell but should be close to
this one.

On Wed, May 18, 2016 at 9:51 AM, Niels <notifications@github.com> wrote:

> The MSVC job failed for several months, because of some weird
> (nonstandard) behavior of MSVC. It is fixed now, but I just forgot to
> remove it from the list. Good to know it works now out of the box! Could
> you give me the exact version you are using so I can reference it in the
> README file?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/nlohmann/json/issues/246#issuecomment-219964893>
>



-- 
Marco Giordano
Software Developer at Frontier Developmet
+447462721890
London(UK)
linkedin  <http://be.linkedin.com/in/marcogiordano3d/>

**Comment by nlohmann** [comment]
Thanks!
