### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by im95able** [nlohmann/json#251]
Is there any way to get which UTF encoding the JSON document is using ? 
Thanks in advance

**Comment by nlohmann** [comment]
To be honest: I am not sure whether the library works with anything other than UTF8. Did you try?

**Comment by im95able** [comment]
I didn't. I'm currently using your lib for parsing JSON objects I get from SoundCloud. So far everything workes well. Now I am not sure which encoding they use. My guess probably UTF8

**Comment by nlohmann** [comment]
So I checked and I could parse JSON files encoded as UTF-8 (with and without BOM). Unfortunately, I could not find and UTF16 example. So if anyone can provide such a file, I can add a test case.

**Comment by nlohmann** [comment]
After some superficial googling, it seems like UTF16 support for C++ is so limited that I shall conclude that I can only make guarantees for UTF8 at the moment.
