### ISSUE TITLE
is the release 2.0?

### ISSUE THREAD

**Issue by murinicanor** [nlohmann/json#253]
hi,

i'm working on a debian package for the your json library (because its a build dependency for usbguard). is the master branch already release 2.0? both https://nlohmann.github.io/json/ and the header of src/json.hpp mention 2.0, but the changelog and the releases page still list 1.1.0 as the latest release...

thanks for your work!

cheers,
muri

**Comment by nlohmann** [comment]
Hi @murinicanor, I recently switched to [gitflow](https://github.com/nvie/gitflow) and left the branches in a bit of mess. The current work is done on the `develop` branch.

The last release is 1.1.0, and version 2.0.0 is still in the planning phase (while I hope to have it out soonish).
