### ISSUE TITLE
Could we provide a more flexible `get<>` and `at<>` API?

### ISSUE THREAD

**Issue by sighingnow** [nlohmann/json#2543]
#### What is the issue you have?

(I didn't see a "feature request" category when opening a new issue thus I post this ticket as a "bug report")

I'm wondering could we provides a more flexible `get<>` (`get` with key) or `at<>` (`at` with type parameter) API like:

```cpp
template <typename ValueType>
ValueType get(const key_type &key) {
   return this->operator[](key).get<ValueType>();
}

template <typename ValueType>
ValueType at(const key_type &key) {
   return this->at(key).get<ValueType>();
}
```

I have notice we already has

+ `get` with type parameter but without key
+ `at` and `[]` with key but no type parameter
+ `value` with key but requires a typed default value.

I think the new API above would provide great convenience.

#### Please describe the steps to reproduce the issue.

None.

#### Can you provide a small but working code example?

None.

#### What is the expected behavior?

As the description of this issue.

#### And what is the actual behavior instead?

No such API.

#### Which compiler and operating system are you using?

None.

**Comment by sighingnow** [comment]
If such API is acceptable, I could prepare a pull request for that.

**Comment by sighingnow** [comment]
Also for `get_ref<>`.

**Comment by nickaein** [comment]
Can you provide some code snippets that demonstrate the usage of this API?

BTW, there is a "Ideas" category at [Discussions](https://github.com/nlohmann/json/discussions/) which seems to be meant for submitting proposals.
