### ISSUE TITLE
try/catch block does not catch parsing error

### ISSUE THREAD

**Issue by BFamzz** [nlohmann/json#2579]
#### What is the issue you have?
try/catch block does not catch parsing error

Error message is:
`
[json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: 'A'
`
#### Please describe the steps to reproduce the issue.

1. Sample code is provided below.

#### Can you provide a small but working code example?

```
#include<iostream>
#include <nlohmann/json.hpp>

int main()
{
    try
    {
        nlohmann::json jsonObject = nlohmann::json::parse("Alright");
        std::cout << "Parse completed!\n";
    }
    catch(const std::exception& e)
    {
        std::cerr << e.what() << '\n';
        return -1;
    }
    return 0;
}
```

#### What is the expected behavior?

Error should be caught in the try/catch block and program should continue execution.

#### And what is the actual behavior instead?

Program crashes while in the try block. Parsing error is not caught.

#### Which compiler and operating system are you using?

- Compiler: GCC 9.3.0 && GCC 10.1.0
- Operating system: Linux - Ubuntu 20.04

#### Which version of the library did you use?

- [`x`] latest release version 3.9.1

**Comment by nlohmann** [comment]
I cannot reproduce this issue: https://godbolt.org/z/d396TE

**Comment by nlohmann** [comment]
The libraries exceptions do inherit from `std::exception`. There must be something wrong in your setup I'm afraid.

**Comment by BFamzz** [comment]
Hi @nlohmann 

> I cannot reproduce this issue: https://godbolt.org/z/d396TE

Following the link you posted, the error message was displayed. 

Kindly see screenshot below.

![image](https://user-images.githubusercontent.com/38426051/104168267-14c22b00-53fe-11eb-9cb3-8ace9d79ff33.png)

**Comment by nlohmann** [comment]
The error message is displayed, because of the line

```cpp
std::cerr << e.what() << '\n';
```

And that line is only executed, because the exception has be caught.

**Comment by BFamzz** [comment]
Thanks @nlohmann You are right. There must be something wrong with my setup. I will close this and investigate my setup further. If I find anything, I'll update this thread with my findings. Thanks for your help.

**Comment by xiaozhuai** [comment]
@BFamzz @nlohmann
I got the same issue.
On MacOS, it works fine
On android with NDK r15c, it cannot catch the exception, same code

```c++
    try {
        throw std::runtime_error("aaaaa");
    } catch (std::exception &e) {
        std::cout << e.what() << "\n"; // works
    }

    try {
        auto aaa = json::parse("{aaaa}");
    } catch (json::exception &e) {
        std::cout << e.what() << "\n"; // not work
    }
```

**Comment by nlohmann** [comment]
@xiaozhuai Can you share more information on your setup?
