### ISSUE TITLE
braced-init-list: array vs other constructor

### ISSUE THREAD

**Issue by rm-blsh** [nlohmann/json#2583]
```c++
#include <nlohmann/json.hpp>

using json = nlohmann::json;

int main()
{
    // move construction 
    // json j(json::object()); 
    
    // want move construction but msvc and gcc converts into array, clang call move constructor
    json j{json::object()}; 
    return j.is_array(); 
}
```
It is debatable what the semantics for  `json j(json::object())` should be (array or not) but at least it should be the same for the major compilers.

I did not investigate this issue in detail if its a compiler or std library (type_traits) -error or undefined/unspecified behavior triggered by nlohmann::json lib.

**Comment by rm-blsh** [comment]
gcc calls basic_json(initializer_list_t... ) constructor
clang uses RVO

**Comment by bl-ue** [comment]
@rm-blsh your point is that they all three compilers should convert into an array, correct?

**Comment by Bellybutn278** [comment]
> ```c++
> #include <nlohmann/json.hpp>
> 
> using json = nlohmann::json;
> 
> int main()
> {
>     // move construction 
>     // json j(json::object()); 
>     
>     // want move construction but msvc and gcc converts into array, clang call move constructor
>     json j{json::object()}; 
>     return j.is_array(); 
> }
> ```
> 
> It is debatable what the semantics for `json j(json::object())` should be (array or not) but at least it should be the same for the major compilers.
> 
> I did not investigate this issue in detail if its a compiler or std library (type_traits) -error or undefined/unspecified behavior triggered by nlohmann::json lib.

https://github.com/users/Bellybutn278/projects/1#card-52705716

**Comment by rm-blsh** [comment]
> @rm-blsh your point is that all three compilers should convert into an array, correct?

actually I prefer that it should have the copy/move constructor semantics, but this is from a technical perspective not a sane option (initializer_list constructor have precedence over others) .  so yes all compilers should make an array.

on the other hand there is already json::array for empty array creation/ array with {{string, *}, .. } pairs.

you can see there are arguments for both semantics

**Comment by bl-ue** [comment]
Not sure if this will help, but
https://github.com/nlohmann/json/blob/085d497bf76fa13eaef381881e1c6f51f26afa85/include/nlohmann/json.hpp#L1534-L1658

**Comment by nlohmann** [comment]
This seems to be a duplicate of #2311.

**Comment by rm-blsh** [comment]
> This seems to be a duplicate of #2311.

Do you marked #2311 as "solution: wontfix" because it is compiler error of clang?

**Comment by nlohmann** [comment]
I don't see a way to fix this issue, because the compilers treat the initialization differently. Whatever I would now do to "fix" the behavior (and I am not sure if this is possible at all) would be a breaking change.

**Comment by rosshamish** [comment]
This issue looks like it can be closed, to me. 

@nlohmann do you think this difference in behavior between clang and gcc warrants an addition to "Supported Compilers" in the readme? https://github.com/nlohmann/json#supported-compilers

That section has 4 notes already, like
> - GCC 4.8 has a bug 57824): multiline raw strings cannot be the arguments to macros. Don't use multiline raw strings directly in macros with this compiler.

and

> - For GCC running on MinGW or Android SDK, the error 'to_string' is not a member of 'std' (or similarly, for strtod or strtof) may occur

**Comment by rm-blsh** [comment]
I would appreciate if this behavior of clang is documented (not only in the "Supported Compilers" section, but also with a waring at the constructor documentation). It would also minimize further duplicates of this issue.

**Comment by nlohmann** [comment]
I added a FAQ entry for this bug: https://json.nlohmann.me/home/faq/#brace-initialization-yields-arrays
