### ISSUE TITLE
VS2015 compile fail

### ISSUE THREAD

**Issue by aaron3481** [nlohmann/json#260]
Hi all,

I'm trying to import json.hpp into my project. When compiling, an error came out and pointed to line 8500 "max = static_cast<uint64_t>(std::numeric_limits<number_integer_t>::max()) + 1;"

Error Code: C2589 '(': illegal token on right side of '::'

**Comment by nlohmann** [comment]
I'll have a look into this. Just to make sure:

- Are you using the most recent version from the `develop` branch?
- Which version of MSVC are you using?

I'm asking because AppVeyor could execute all tests successfully (https://ci.appveyor.com/project/nlohmann/json) with MSVC 19.0.23918.0.

**Comment by Epidal** [comment]
I can confirm that this does happen with the most recent commit in VS2015.  This is due to the fact that Windows defines max() and min() as macros in windows.h.  You can avoid the macro expansion by surrounding numeric_limits::max in extra parentheses, like so:
`max = static_cast<uint64_t>((std::numeric_limits<number_integer_t>::max)()) + 1;`

**Comment by gregmarr** [comment]
You can also add the following to prevent them from being defined, as long as none of your code requires them to be defined, or you can update your code.
```#define NOMINMAX```

**Comment by aaron3481** [comment]
Many thanks to all. I will test right the way

**Comment by aaron3481** [comment]
@nlohmann I'm using VS Community 2015 Version 14.0.23107.0 D14REL and it is the  most recent version from the develop branch

**Comment by aaron3481** [comment]
@Epidal your suggestion fix the issues. Thx
@gregmarr NOMINMAX seems not work

**Comment by gregmarr** [comment]
You need to define that before including any Windows headers.

**Comment by nlohmann** [comment]
I committed the fix, but I won't merge it before Travis builds it (there seem to be problems with the LLVM's apt server...)

**Comment by nlohmann** [comment]
Finally merged commit b508d1f to develop branch.
