### ISSUE TITLE
Memory leak when working on ARM Linux

### ISSUE THREAD

**Issue by hayalbaz** [nlohmann/json#2601]
When I compile the same program and run it on an ARM Linux board, valgrind shows memory leak while my Ubuntu 18.04 x86-64 machine does not report memory leak. 

#### What is the issue you have?

I have written a sample program that reproduces the bug. The required cmake and cpp files attached. I also attached the log file produced by valgrind when it is run on ARM(valgrindd_trackerr.log) and x86 Linux.

[x86.log](https://github.com/nlohmann/json/files/5841704/x86.log)

[CMakeLists.txt](https://github.com/nlohmann/json/files/5841666/CMakeLists.txt)
[toolchain.txt](https://github.com/nlohmann/json/files/5841674/toolchain.txt)
[main.txt](https://github.com/nlohmann/json/files/5841675/main.txt)
[valgrind-trackerr.log](https://github.com/nlohmann/json/files/5841694/valgrind-trackerr.log)

To recreate the bug I create a complex json object and try to serialize it and print it on cmd.

#### Which compiler and operating system are you using?
For x86-64: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
For ARM: arm-linux-gnueabi-gcc-5 (Ubuntu/Linaro 5.5.0-12ubuntu1) 5.5.0 20171010

The Linux running on ARM is created using buildroot.

#### Which version of the library did you use?

- [x ] latest release version 3.9.1
- [ ] other release - please state the version: ___
- [ ] the `develop` branch

**Comment by nlohmann** [comment]
Could you compile your code with ASAN and TSAN? Usually, they give much better diagnostics than Valgrind.

Apart from that, I am pretty sure the library does not leak memory, and the reason for the leak is something else.

**Comment by hayalbaz** [comment]
I have not tried TSAN but I switched to another library and the leak was still there. The leak dissappears when I remove the std::thread so I think it is safe to say there is no leak. Thanks for your time.

**Comment by nlohmann** [comment]
Thanks for reporting back!
