### ISSUE TITLE
Missing get function and no viable overloaded '=' on mac

### ISSUE THREAD

**Issue by ErikToth97** [nlohmann/json#2610]
No viable overloaded '=' and no 'get' member function on mac 11.1.

#### What is the issue you have?
We get errors on mac with a code that works on windows. Although we use the same settings (c++ version, cmake settings), the below provided examples doesn't work on mac. 

For example in the code below, it raises a 
"No viable overloaded '='" error for  ```j = *opt```, and "No matching member function for call to 'get'" for the  ```j.get<T>``` part. (This code has been tested on windows and it works perfectly)
```cpp
static void to_json(json & j, const std::shared_ptr<T> & opt) {
			if (!opt) j = nullptr; else j = *opt;
		}

		static std::shared_ptr<T> from_json(const json & j) {
			if (j.is_null()) return std::unique_ptr<T>(); else return std::unique_ptr<T>(new T(j.get<T>()));
		}
```

In the code below we get the "No viable overloaded '='" error for ```j["context"] = x.get_context();``` and  ```j["assets"] = x.get_assets();```.
```cpp
inline void to_json(json & j, const quicktype::Scene & x) {
			j = json::object();
			j["context"] = x.get_context();
			j["scene"] = x.get_scene();
			j["assets"] = x.get_assets();
		}
```

#### Please describe the steps to reproduce the issue.
I have read through the posted "mac-issues", and tried some steps already:
I tried updating my softwares
I tried multiple versions of nlohmann
I tried building and running the provided tests this way:
mkdir build
cd build
cmake .. -GXcode
open nlohmann_json.xcodeproj
In Xcode, select scheme "ALL_BUILD" and build it.
Select scheme "RUN_TESTS" and run it.

And 2 tests fail:

Showing Recent Messages
The following tests FAILED:
	 57 - cmake_fetch_content_configure (Failed)
	 58 - cmake_fetch_content_build (Not Run)
Errors while running CTest
make: *** [RUN_TESTS_buildpart_0] Error 8
Command /bin/sh failed with exit code 2

#### Which compiler and operating system are you using?
 1. AppleClang 12.0.0.12
 2. c++17 (we tried c++14 too, same errors occured)
 3. Xcode is in 3.2-compatible mode
 4. Mac 11.1

#### Which version of the library did you use?

- [x] latest release version 3.9.1
- [x] other release - please state the version: 3.6.1
- [ ] the `develop` branch

**Comment by nlohmann** [comment]
Can you please share a minimal working example? I'd like to test the issue, but I don't want to fill the gaps like "what is `T`?" or `quicktype::Scene`.

**Comment by ErikToth97** [comment]
This is the file we use:
https://github.com/MTASZTAKI/ApertusVR/blob/0.9.1/plugins/virtualLearningFactory/sceneLoader/apeVLFTSceneLoaderPluginConfig.h
You can find the previously given examples in it too.

**Comment by nlohmann** [comment]
Can you please create a small working example? I'd rather not start building external projects.

**Comment by ErikToth97** [comment]
[example_project.zip](https://github.com/nlohmann/json/files/5885906/example_project.zip)
I have created a project for you with cmake, you can build it on windows and on mac too.

On windows it gives a runtime error but that is not important, it is because the json file it opens does not contain anything. The important thing is that on windows you can build it and run it (be sure to build/run the example_project, not the ALL_BUILD). 

On MacOs it does not build. It throws the above mentioned errors. (On mac you need to install nlohmann before you run cmake.)

**Comment by nlohmann** [comment]
I see code like

```cpp
namespace nlohmann {
	namespace detail {
		void from_json(const json & j, quicktype::Representation & x);
		void to_json(json & j, const quicktype::Representation & x);

		void from_json(const json & j, quicktype::Asset & x);
		void to_json(json & j, const quicktype::Asset & x);

		void from_json(const json & j, quicktype::Context & x);
		void to_json(json & j, const quicktype::Context & x);

		void from_json(const json & j, quicktype::Scene & x);
		void to_json(json & j, const quicktype::Scene & x);
...
```

The `to_json` and `from_json` functions need to be define in the namespace of the type, so in `namespace quicktype`.

**Comment by ErikToth97** [comment]
Okay this seems to have worked somewhat, only 1 error remains after I moved all the inline ```from_json```/```to_json```functions to the ```namespace quicktype``` (however it seems strange that it works on windows without these functions in the namespace).

The remaining error is the ```No matching member function for call to 'get'```, at the beginning of the header file:
```
struct adl_serializer<std::shared_ptr<T>> {
		static void to_json(json & j, const std::shared_ptr<T> & opt) {
			if (!opt) j = nullptr; else j = *opt;
		}

		static std::shared_ptr<T> from_json(const json & j) {
			if (j.is_null()) return std::unique_ptr<T>(); else return std::unique_ptr<T>(new T(j.get<T>()));
		}
	};
```
In this code the j.get<T>() throws it.

**Comment by ErikToth97** [comment]
I have managed to solve the issue by generating a new header file. The problem wasn't with the quicktype namespace but with the detail namespace under nlohmann.
