### ISSUE TITLE
Preserve decimal formatting

### ISSUE THREAD

**Issue by nickgeorge** [nlohmann/json#2618]
Hello, I'm trying to use this as part of a specialized json parsing/printing library.  It is essential that performing a round trip parse-print does not modify data.  Therefore, internally, we store decimals as strings, guaranteeing that formatting is not destroyed.  Is it possible to reproduce this in nlohmann/json?  or is it inherently destructive?

Examples:

`2.500` becomes `2.5`
`1E-22` becomes `1e-22`
`66.899999999999991` becomes `66.89999999999999` 

I understand the limitations of float representation - the hope is that it's possible to enable a mode/custom parsing that internally parses decimals into as strings, so as to side-step these limitations.

Most broadly, the question is if it's possible to get to a guarantee that (other than insignificant white-space)

`json::parse(my_json_string).dumps() == my_json_string`

Thanks,
Nick

**Comment by nlohmann** [comment]
This is not a bug, but intended behavior: the library uses `double`, `std::int64_t`, and `std::uint64_t` internally not store numbers. While we do expose the string from the parser in the SAX interface (see https://github.com/nlohmann/json/blob/develop/include/nlohmann/detail/input/json_sax.hpp#L64), we have no extension point for serializers yet. That means: you *could* write a SAX adapter to digest the parsed input and store strings alongside with numbers, you cannot use the `basic_json` class to store or serialize such data.
