### ISSUE TITLE
Preseving order of items in json

### ISSUE THREAD

**Issue by moneroexamples** [nlohmann/json#262]
Is there a way of cunstring json object so that it preserves the ordering of elements?

For example, this:
```c++
    nlohmann::json j1 {{"ccc", 2}, {"aaa", 4}};
    cout << j1 << endl;
```

results in a string in different order than originally defined
```c++
{"aaa":4,"ccc":2}
```

I would like to preserve the orginal order, i.e., to get this instead:
```c++
{"ccc":2,"aaa":4}
```

**Comment by gregmarr** [comment]
See this issue https://github.com/nlohmann/json/issues/106

**Comment by moneroexamples** [comment]
Thanks, so it seems as there is no "easy" way for this.
