### ISSUE TITLE
Throw exception instead of crashing my app

### ISSUE THREAD

**Issue by RandomSayHello** [nlohmann/json#264]
Hi there,

I just wanted to know how I can "predefine" a check-statement.

like, whenever I read something like json["test_me"] and it's non-existant, my app crash.
Is there any simple way to check if this value even exists before it force-read it?

sorry, Imma newbie here. I might explained my question in a totally wrong way .. however, I hope you can help me out! :+1:

**Comment by gregmarr** [comment]
If you're sure `json` is an `object`, you can do `json.count("test_me")`, and it will return 0 or 1.  If you're not sure, use `json.is_object()` first.

**Comment by RandomSayHello** [comment]
Thank you very much, gregmarr.

Is there any way to define it "globally" because I'm reading & writing like 300 lines of json (equals 600 lines in visual studio). Means If I have to to json.count on every line ... well, 1200 lines just to read and write 300 lines? You get me...

**Comment by gregmarr** [comment]
`json`, `json["test_me"]`, and `json["test_me"]["test_you"]` all refer to objects of type `json`, and behave the same way.

As to your first question, I don't understand.  If you try to get a field that doesn't exist, then a const json object throws an exception or a non-const json object creates the field and returns a reference to it.  The only way to get a different behavior is to check if the field exists first.  How you do that is up to you, I can't help you much with that.

**Comment by RandomSayHello** [comment]
Hoireka, I got it!
`std::string IwantYou = GetJSON[ "test_me" ][ "IamHere" ].is_null( ) ? 0 : GetJSON[ "test_me" ][ "IamHere" ]`

Thank you gregmarr, I tested json.count but apparently there is a json.is_null() function to check if XY exist in the json object!

Is there any way to code a function for that?
I'd like to have something like this:
`std::string IwantYou = Validate(GetJSON[ "test_me" ][ "IamHere" ]);`

Again, thank you very much!

**Comment by gregmarr** [comment]
If GetJSON is a const object, then you won't even get as far as calling is_null(), because the exception is thrown when you do ["IamHere"].  You could do something like 

```
std::string Validate(json const &j, std::string const &str)
{
    if(j.count(str) == 0)
        return {};
    return j[str];
}

std::string IwantYou = Validate(GetJSON["test_me"], "IamHere");
```

**Comment by nlohmann** [comment]
As a remark: There is also the [`at` function](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a7ed92d56cb313b243c1917696ffdf074.html#a7ed92d56cb313b243c1917696ffdf074) which throws a `std::out_of_range` if the key is not present.

**Comment by RandomSayHello** [comment]
Thank you very much guys, you helped me a lot! :+1:

**Comment by gregmarr** [comment]
Lest anyone else that finds this later be confused:
I said that `["something"]` on a `const` object throws if `"something"` doesn't exist.
It actually `assert`s that `"something"` exists.  If you want `throw` instead of `assert`, you need to use `at` instead, as @nlohmann said above.
