### ISSUE TITLE
No support for using an external/system copy of Hedley

### ISSUE THREAD

**Issue by musicinmybrain** [nlohmann/json#2651]
#### What is the issue you have?

The project uses a bundled copy of [Hedley](https://nemequ.github.io/hedley/), lightly forked with `JSON_` prefixes and with each macro undefined at the end of the header.

It seems like it would be possible, albeit a little tedious, to support including a system copy of `hedley.h`, “wrapping” the unprefixed macros.

Most Linux distributions, such as Fedora, are opposed to bundling [for various reasons](https://fedoraproject.org/wiki/Bundled_Libraries?rd=Packaging:Bundled_Libraries). In order to package this software in Fedora, I am [required](https://docs.fedoraproject.org/en-US/packaging-guidelines/#bundling) to ask you to support using an external or system copy of Hedley, and to record any response.

#### Please describe the steps to reproduce the issue.

Look at the sources; see a bundled copy of Hedley.

#### Can you provide a small but working code example?

(not applicable)

#### What is the expected behavior?

(not applicable)

#### And what is the actual behavior instead?

(not applicable)

#### Which compiler and operating system are you using?

(not applicable)

#### Which version of the library did you use?

- [x] latest release version 3.9.1
- [x] the `develop` branch

#### If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

(not applicable)

**Comment by nlohmann** [comment]
I would not put effort into this myself, but PRs welcome.

**Comment by xvitaly** [comment]
> Most Linux distributions, such as Fedora, are opposed to bundling for various reasons. In order to package this software in Fedora, I am required to ask you to support using an external or system copy of Hedley, and to record any response.

Fedora is okay with bundling.
