### ISSUE TITLE
2 backslash cause problem

### ISSUE THREAD

**Issue by yazi1297** [nlohmann/json#2652]
Code like this:
``` c++
try
{
    std::string strJson = "{\"file_path\":\"C\\123.txt\"}";
    nlohmann::json jsonMsg = nlohmann::json::parse(strJson);
    std::string strJsonDump = jsonMsg.dump();
    std::cout << strJsonDump << std::endl;
}
catch (const std::exception& e)
{
    const char* szErrInfo = e.what();
    printf("%s \n", szErrInfo);
}
```
It will crash, and error log is
```
[json.exception.parse_error.101] parse error at line 1, column 17: syntax error while parsing value - invalid string: forbidden character after backslash; last read: '"C\1'
```

#### What is the issue you have?

When I analyze json code which have 2 backslash, my proejct will crash. 

#### Please describe the steps to reproduce the issue.

1. Create a console project
2. Include Json.hpp in your project
3. Copy the code above into your main function, and run.

#### Can you provide a small but working code example?

```
#include "pch.h"
#include <iostream>
#include <string>
#include "json/json.hpp"
int main()
{
    try
    {
        std::string strJson = "{\"file_path\":\"C:\\123.txt\"}";
        nlohmann::json jsonMsg = nlohmann::json::parse(strJson);
        std::string strJsonDump = jsonMsg.dump();
        std::cout << strJsonDump << std::endl;
    }
    catch (const std::exception& e)
    {
        std::cout << e.what() << std::endl;
    }
    std::cout << "Hello World!\n";
}
```

#### What is the expected behavior?

It should print {"file_path":"C:\123.txt"} on the screen

#### And what is the actual behavior instead?

It crashed.

#### Which compiler and operating system are you using?

- Compiler: vs2019 + Visual Studio 2017 - Windows XP (v141_xp)
- Operating system: Windows

#### Which version of the library did you use?

- [] latest release version 3.9.1
- [ ] other release - please state the version: ___
- [x] the `develop` branch
develop + 3.9.1
#### If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

- [ ] yes
- [ ] no - please copy/paste the error message below

**Comment by nlohmann** [comment]
The literal `"{\"file_path\":\"C\\123.txt\"}"` after escaping is `"{"file_path":"C\123.txt"}"`. In JSON, a `1` is not allowed after a backslash - this is what the exception message is saying.

**Comment by gregmarr** [comment]
To get your desired result, you need to escape twice, once for JSON and one for std::string.

    std::string strJson = "{\"file_path\":\"C:\\\\123.txt\"}";

or you can use a raw string literal and only escape once

    std::string strJson = R"({ "file_path": "C:\\123.txt" })";

https://en.cppreference.com/w/cpp/language/string_literal

**Comment by nlohmann** [comment]
@yazi1297 Do you need further assistance with this issue?

**Comment by AronZhi** [comment]
use a raw string literal seems not work
