### ISSUE TITLE
.dump() not allowing compact form

### ISSUE THREAD

**Issue by qikdauie** [nlohmann/json#2678]
#### Please describe the steps to reproduce the issue.
use dump(-1) or dump(), it will add newlines.

#### Can you provide a small but working code example?

`
json obj {
 {"a", "ayyy"},
 {"b", "beee"}
}
std::cout << obj.dump(-1);
`
output:
`
{\n
"a": "ayyy",\n
"b": "beee"\n
}\n
`
#### What is the expected behavior?
`{"a": "ayyy","b": "beee"}`

In json.hpp starting a line 2236, the conditions here do not allow for -1 mode.
`        if (indent >= 0)
        {
            s.dump(*this, true, ensure_ascii, static_cast<unsigned int>(indent));
        }
        else
        {
            s.dump(*this, false, ensure_ascii, 0);
        }`

- Compiler:  cl
- Operating system: mac

#### Which version of the library did you use?

- [x ] latest release version 3.9.1
- [ ] other release - please state the version: ___
- [ ] the `develop` branch

#### If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-nit-tests)?

- [ ] yes
- [ x] no - please copy/paste the error message below

**Comment by qikdauie** [comment]
my output examples got the newlines removed, imagine newlines in the first output example.

**Comment by qikdauie** [comment]
Im just going to alter my copy of the lib, but, was this disabled for some reason?

**Comment by qikdauie** [comment]
if anyone is having this issue, a workaround is a compact function using regex. Here's mine if you're interested:


`std::string CompactJsonString(std::string& json) {
  std::regex no_space("\\s(?=([^\"]*\"[^\"]*\")*[^\"]*$)");
  std::regex no_newline("\\s\n(?=([^\"]*\"[^\"]*\")*[^\"]*$)");
  // write the results to an output iterator
  json = std::regex_replace(json, no_space, "");
  json = std::regex_replace(json, no_newline, "");
  return json;
}`

**Comment by t-b** [comment]
@qikdauie Do the tests pass on your platform?

From the test code at https://github.com/nlohmann/json/blob/176d8e261a00dc27bfbf334e12d50572bf43fc4c/test/src/unit-inspection.cpp#L228 it looks like `dump` does what you expect.

**Comment by qikdauie** [comment]
@t-b on a deadline at the moment. Ill test asap and get back to the thread. Thanks for the response.

**Comment by nlohmann** [comment]
I cannot reproduce the issue. The code for serialization is unchanged for months and part of the unit tests. Please provide a small working example. Please also check if the test suite passes.
