### ISSUE TITLE
Compiler warning with Intel compiler, same as #755

### ISSUE THREAD

**Issue by philbucher** [nlohmann/json#2712]
Using the intel compiler reports the following warning:
~~~
#186: pointless comparison of unsigned integer with zero
          const bool is_negative = std::is_same<NumberType, number_integer_t>::value && !(x >= 0); // see issue #755
~~~

I tried the solutions posted in #755 and others (e.g. [this one](https://github.com/nlohmann/json/issues/1390#issuecomment-625720208)) but I couldn't get it to work.
I also tried with `std::signed` & `std::unsigned` but no success either

@nlohmann you could add the Intel compiler to the CI with the [oneAPI](https://software.intel.com/content/www/us/en/develop/documentation/installation-guide-for-intel-oneapi-toolkits-linux/top/installation/install-using-package-managers/apt.html)
Looking at your github actions script this should be doable without too much effort. I'd be happy to help :)
You could install the compiler in what I assume is a docker image (`nlohmann/json-ci:latest`)

#### What is the issue you have?

cannot turn all warnings into errors

#### Please describe the steps to reproduce the issue.
Compile with ICC with e.g. `Werror-all`

#### What is the expected behavior?
Compiles without warnings

#### And what is the actual behavior instead?
Warning is issued

#### Which compiler and operating system are you using?

- Compiler: Intel 20.2.2.20210228 (through oneAPI)
- Operating system: Ubuntu 20.04

#### Which version of the library did you use?
- [x] latest release version 3.9.1
- [ ] other release - please state the version: ___
- [ ] the `develop` branch

#### If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

- [ ] yes
- [ ] no - please copy/paste the error message below

**Comment by nickaein** [comment]
I'm not sure whether this issue counts as ICC compiler bug or not, but just for the sake of testing can you try the workaround that is provided here https://github.com/nlohmann/json/issues/755#issuecomment-440739799 to see if this can suppress the warning?

I tried to reproduce the issue on Compiler Explorer which supports ICC/ICX compilers. It may not support the specific version you are using though and I couldn't reproduce the issue. Can you also give it a try? An online compiler can make working on the issue much easier.

Here is my (failed) attempt, which by the way is giving out another misguided warning: https://godbolt.org/z/nKreE4xW6
