### ISSUE TITLE
Possibility to use without the dependency to file io and streams to use in intel sgx enclaves

### ISSUE THREAD

**Issue by theShmoo** [nlohmann/json#2728]
I need to use your library in an intel sgx enclave. 
For security reasons it is not allowed to use file io there.

I created the pull request #2729 which includes some macros to be defined for using this great library without the file io.

**Comment by nlohmann** [comment]
What is the exact issue? Are certain types disallowed? Or certain headers?

**Comment by theShmoo** [comment]
In the intel SGX c++ library all io headers are not implemented. This means the headers don't exist.

**Comment by theShmoo** [comment]
Can I change something, so that you will accept this pull request?
