### ISSUE TITLE
Compilation error.

### ISSUE THREAD

**Issue by kerolex** [nlohmann/json#273]
Please notice this error during compilation phase:

```
test/src/unit.cpp:12033:32: error: unterminated raw string
             CHECK_NOTHROW(json(R"(
                                ^
test/src/unit.cpp:12048:14: warning: missing terminating " character [enabled by default]
             )"));
```

This error is also repeating on other lines with similar structure.
Please can you tell me if it is just a problem of mine?

My OS is Ubuntu 14.04 LTS and compiler g++ 4.8.

**Comment by gregmarr** [comment]
This library only supports g++ 4.9 and above.

**Comment by kerolex** [comment]
Sorry, my distraction. I haven't read carefully the part of compilers in the README.
Thank you for the answer.
