### ISSUE TITLE
Possibility to use with custom c++ version to use in intel sgx enclaves

### ISSUE THREAD

**Issue by theShmoo** [nlohmann/json#2730]
I need to use your library in an intel sgx enclave.
For that I am restricted to another standard library implementation (the one from intel)
You provide nice defines for the used c++ standard.
I use c++17 but the library of intel only has some c++11 features.
So I need to define the used standard version by my own.

I created a pull request that fixes this: #2731

**Comment by nlohmann** [comment]
Is there maybe a way to detect the used standard from that standard library?

**Comment by theShmoo** [comment]
The used standard in the intel sgx c++ library is kinda c++11 so yeah it is c++11
But to be able to use language features that are later than c++11 (e.g.: keywords, ...) I build with a later standard (c++17)
