### ISSUE TITLE
CMake failure in VS2019 Community

### ISSUE THREAD

**Issue by 4llenchan** [nlohmann/json#2734]
#### What is the issue you have?

1. Download and checkout tag v3.9.1
2. Open project with VS Community 2019 16.9.4
3. Run configure and get error like this:

```
1> [CMake]    'D:/Program Files/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe' '-C' 'D:/Code/github/json/out/build/x64-Debug' '-t' 'cleandead'
1> [CMake] 
1> [CMake]   failed with:
1> [CMake] 
1> [CMake]    ninja: error: CMakeFiles\rules.ninja:34: lexing error
```

#### Which compiler and operating system are you using?

- Compiler:  19.28.29914
- Operating system:  Windows-10.0.19041

#### Which version of the library did you use?

- [x] latest release version 3.9.1

#### If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

- [x] yes
- [ ] no - please copy/paste the error message below

**Comment by nlohmann** [comment]
This looks like a problem with Ninja. At least from your error message, I see nothing related to this library.

**Comment by nlohmann** [comment]
Can you try to use a different generator, e.g. Makefiles?

**Comment by 4llenchan** [comment]
After change the language setting to English, got a more concrete error:

```
1> [CMake] 
1> [CMake]    ninja: error: CMakeFiles\rules.ninja:34: expected '=', got lexing error
1> [CMake] 
1> [CMake]   Copyright (C) Microsoft Corporation.  All rights reserved.
1> [CMake] 
1> [CMake] 
1> [CMake]             ^ near here
```

And the rules.ninja file looks like this:
```
#############################################
# Rule for compiling CXX files.

rule CXX_COMPILER__doctest_main_Debug
  deps = msvc
  command = "Microsoft (R) C\C++ Optimizing Compiler Version 19.28.29914 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ \link linkoption... ]; MSVC_VERSION=1928; MSVC_TOOLSET_VERSION=142"  /nologo /TP $DEFINES $INCLUDES $FLAGS /showIncludes /Fo$out /Fd$TARGET_COMPILE_PDB /FS -c $in
  description = Building CXX object $out
```
The `Copyright (C)` line is exactly line 34, but still no no idea how to solve this.

**Comment by 4llenchan** [comment]
> Can you try to use a different generator, e.g. Makefiles?

I just want to use `FetchContent`  to make `nlohmann_json` available in my existing cmake project.

**Comment by 4llenchan** [comment]
As in my situation, I dont need test target, so I just set `JSON_BuildTests` to OFF before `FetchContent_MakeAvailable`.
Something like this:
```
set(JSON_BuildTests OFF CACHE INTERNAL "")
FetchContent_MakeAvailable(json)
```
