### ISSUE TITLE
Parsing a string into json object behaves differently under g++ and MinGW compilers.

### ISSUE THREAD

**Issue by chumaroz** [nlohmann/json#2746]
#### What is the issue you have?

Considering simple example:
```c++
const nlohmann::json j = json::parse(R"(
    {
		"key": "value"
    }
));
```

when compiled using __g++__ or __clang__ on a Mac OS the following code gets executed as expected:

```c++
const auto& var = j.at("key");
```
however under __MinGW__ in Windows the line above results in an error:
__[json.exception.type_error.304] cannot use at() with array.__

For some reason json parsed in the first instance appears to be simply a json object, while
in the second case json object gets placed inside an array, so only the following code works:

```c++
const auto& var = j[0].at("key");
```
What is the reason for such inconsistency, is there any simple solution to this to make the code crossplatform?

#### Which compiler and operating system are you using?

Json example works as expected here:
- Compiler: Apple clang version 12.0.0 (clang-1200.0.32.29)
- Operating system: macOS BigSur, MacbookPro M1

But not there:
- Compiler: MinGW gcc 10.2.0-10
- Operating system: Windows 10

#### Which version of the library did you use?

- [x] latest release version 3.9.1

**Comment by nlohmann** [comment]
Can you please double check that this is the exact code you're executing? Because it seems like a situation in which braced initialization is the reason for different behavior between compilers.

**Comment by chumaroz** [comment]
Hi Niels, thank you for the prompt reply, I'll get back to you later tomorrow with some working simple example.

**Comment by chumaroz** [comment]
> Can you please double check that this is the exact code you're executing? Because it seems like a situation in which braced initialization is the reason for different behavior between compilers.

I was able to reproduce the issue exactly, I realized that the example given above works well in MinGW, but it is something to do with the pointers instead, please see below. Maybe I'm doing something wrong here.


```c++
#include <json/single_include/nlohmann/json.hpp>
#include <iostream>
#include <memory>

nlohmann::json j = R"( { "key" : "value" } )"_json;

class A
{
	public:
	nlohmann::json params;
	A(const nlohmann::json params):
	params{params}
	{}
};

int main()
{
	auto a = std::make_unique<A>(j);
    const auto& temp =  a->params.at("key");
    std::cout << temp <<'\n';
    return 0;
}
```

**Comment by chumaroz** [comment]
And it doesn't matter whether I use `R"( { "key" : "value" } )"_json` or `json.parse(R"( { "key" : "value" } )")`

**Comment by nlohmann** [comment]
Can you please replace

```cpp
A(const nlohmann::json params):
	params{params}
	{}
```

with

```cpp
A(const nlohmann::json params):
	params(params)
	{}
```

and check again?

**Comment by chumaroz** [comment]
YAY! That solves the issue, thanks a lot!
Nels, could you please explain whether this is the expected behaviour and why {} renders different result under different compilers in this case?

**Comment by nlohmann** [comment]
It's all rooted in #2583. I have no solution to it other than to advice not to use brace initialization for JSON types.

**Comment by chumaroz** [comment]
Ok, at least this is a good solution for now, thank you very much!
