### ISSUE TITLE
Undefined symbol EOF 

### ISSUE THREAD

**Issue by cxxman** [nlohmann/json#2755]
#### What is the issue you have?

I am getting compilation error like "Undefined symbol EOF" with gcc9 on Ubuntu 18.04

#### Please describe the steps to reproduce the issue.

Include single header file json.hpp and try to compile code that uses it.

#### What is the expected behavior?

I can see EOF still used in the one place in the single header. Did not check multiple headers.
After replacing with `std::char_traits<char>::eof()` it has started to work.
Please incorporate this small change.

#### Which compiler and operating system are you using?

- Compiler: ___
- Operating system: ___

#### Which version of the library did you use?

- [x] latest release version 3.9.1
- [ ] other release - please state the version: ___
- [ ] the `develop` branch

#### If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

- [ ] yes
- [ ] no - please copy/paste the error message below

**Comment by nlohmann** [comment]
I can't reproduce the issue - we use several compilers include GCC9 on Ubuntu in our CI. Indeed there is one occurrence of `EOF`, but we also include the required header `<cstdio>`. That said - I have no idea why this is a compilation error on your side. Can you compile the unit tests?

That aside, I will create a PR that replaces this occurrence.

**Comment by cxxman** [comment]
thanks! btw, when 3.9.2 can be expected?

**Comment by nlohmann** [comment]
When it's done ;)

Seriously, I have no idea...

**Comment by cxxman** [comment]
Then why not release it now? It is better to release less things but a bit more often, then release a lot but never...

**Comment by nlohmann** [comment]
Because it’s not ready yet. This is a side project - there are no deadlines here.

**Comment by apirogov** [comment]
I have this issue now with the latest version, there are two places where the EOF macro is used.

**Comment by nlohmann** [comment]
@apirogov Right, I thought it was fixed, but it seems #4179 re-introduced the issue. Which compiler do you use that does not support `EOF`?

**Comment by apirogov** [comment]
Well, I'm compiling with GCC, but we're using clang-tidy (LLVM 18) to check the code as part of the workflow, and it complains about the "undefined symbol". I guess it's not about supporting the symbol, but that clang(-tidy) is more pedantic (which is good, actually). I patched the release version of json.hpp (replacing `EOF` with `std::char_traits<char>::eof()`, as suggested above), and the problem went away for us.

**Comment by nlohmann** [comment]
Thanks. I'll create a PR for this as well.

**Comment by nlohmann** [comment]
@apirogov PTAL at #4532
