### ISSUE TITLE
compilation error on clang-8 + C++17

### ISSUE THREAD

**Issue by janwilmans** [nlohmann/json#2759]
```
json.h:19799:62: error: no type named 'string_view' in namespace 'std'
                   && !std::is_same<ValueType, typename std::string_view>::value
```
I think an include of `<string_view>` is missing ? This only occurs on debian-8 + clang-8  + C++17 here.

**Comment by nlohmann** [comment]
Which version are you using? The filename seems odd.

**Comment by janwilmans** [comment]
The file is just renamed, its this version:
```
    __ _____ _____ _____
 __|  |   __|     |   | |  JSON for Modern C++
|  |  |__   |  |  | | | |  version 3.9.1
|_____|_____|_____|_|___|  https://github.com/nlohmann/json

Licensed under the MIT License <http://opensource.org/licenses/MIT>.
SPDX-License-Identifier: MIT
Copyright (c) 2013-2019 Niels Lohmann <http://nlohmann.me>.
```

The reason why I got this problem it that I installed a binary distribution of clang-8 on debian-8, but apparently, if I do not explicitly specify `-stdlib=libc++`  it still uses the stock version of libstd++, which doesn't support C++17.

Long story short, I have a weird setup, but looking at the code, I didnt't see an include of <string_view>, I see that on head it _is_ present (https://github.com/nlohmann/json/blob/develop/include/nlohmann/json.hpp#L77)
