### ISSUE TITLE
Cannot convert from 'json' to 'char'

### ISSUE THREAD

**Issue by DPD85** [nlohmann/json#276]
I'm not sure if this is an issue,
but it's not possible to assign a json object to a variable of type char.
With all other integral types it works, only the char type makes error.

Example:

``` cpp
    json j;
    j = 'B'; // ok, store a value as type number_integer
    char b = j; // compiler error: cannot convert from 'json' to 'char'
```

**Comment by nlohmann** [comment]
Thanks for reporting!

I tried the code and got the following error message:

```
error: no viable conversion from 'json' (aka 'basic_json<>') to 'char'
    char b = j; // compiler error: cannot convert from 'json' to 'char'
         ^   ~
./src/json.hpp:2995:20: note: candidate template ignored: disabled by 'enable_if' [with ValueType = char]
                   not std::is_pointer<ValueType>::value
                   ^
./src/json.hpp:2465:15: note: candidate function
    constexpr operator value_t() const noexcept
              ^
```

`char` is the character type for `string_t` and is excluded from the possible values for `operator ValueType() const` to avoid ambiguities as these types implicitly convert to `std::string`. I am not sure whether it would make sense to make a change to support this edge case.

**Comment by nlohmann** [comment]
While fixing #144, the following comment has been added to the operator ValueType() function:

> The character type of `string_t` as well as an initializer list of this type is excluded to avoid ambiguities as these types implicitly convert to `std::string`.

I don't think this issue can be fixed without breaking the #144.

**Comment by theodelrieu** [comment]
You can still use the `get` method though

**Comment by theodelrieu** [comment]
Just for the record, this is linked to #958.

**Comment by ElectricRCAircraftGuy** [comment]
For anyone who lands on this page trying to figure out how to print or use something like `jsonObject["my_key"]` as a `char*`, here is a demo that shows how:

```cpp
printf("name:   %s\n", j1["name"].get_ref<const std::string&>().c_str());
```

The `j1["name"].get_ref<const std::string&>().c_str()` part reads the value out of the `"name"` key from the `j1` json object as a `const std::string&` reference, and then obtains the `const char*` C-string from that using `.c_str()`. 

See:
1. https://en.cppreference.com/w/cpp/string/basic_string/c_str
2. https://json.nlohmann.me/api/basic_json/get_ref/

For my full demo of this and more, see [json_nlohmann_demo.cpp](https://github.com/ElectricRCAircraftGuy/eRCaGuy_hello_world/blob/master/cpp/json_nlohmann_demo.cpp) in my [eRCaGuy_hello_world](https://github.com/ElectricRCAircraftGuy/eRCaGuy_hello_world) repo.
