### ISSUE TITLE
recursive data structures

### ISSUE THREAD

**Issue by froatsnook** [nlohmann/json#277]
Hi, thanks for the great library :). I had a gotcha when working with a recursive data structure.

```c++
using namespace std;
using namespace nlohmann;
int main() {
    string text = "{\"A\":{\"id\":1,\"children\":{\"B\":{\"id\":2,\"children\":{\"C\":{\"id\":3,\"children\":{}}}}}}}";
    json data = json::parse(text);

    json& curr = data;
    curr = curr["A"]["children"];

    cout << "curr=" << curr.dump() << std::endl; // { B: ... } OK
    cout << "data=" << data.dump() << std::endl; // { B: ... } expected { A: ... }
}
```

I was able to work around this using a pointer:

```c++
    string text = "{\"A\":{\"id\":1,\"children\":{\"B\":{\"id\":2,\"children\":{\"C\":{\"id\":3,\"children\":{}}}}}}}";
    json data = json::parse(text);

    json* curr = &data;
    curr = &curr->operator[]("A").operator[]("children");

    cout << "curr=" << curr->dump() << std::endl; // { B: ... } OK
    cout << "data=" << data.dump() << std::endl; // { A: ... } OK
```

Is there a better way to work with `json` in this way?

**Comment by gregmarr** [comment]
Since curr is a reference to data, it is by definition identical to data.  This includes any change made to it applies to data.  That is not specific to this library in any way.  It is just how C++ works.  What you wrote is identical to this code:

```
int main() {
    string text = "{\"A\":{\"id\":1,\"children\":{\"B\":{\"id\":2,\"children\":{\"C\":{\"id\":3,\"children\":{}}}}}}}";
    json data = json::parse(text);

    data = data["A"]["children"];

    cout << "data=" << data.dump() << std::endl; // { B: ... } OK
    cout << "data=" << data.dump() << std::endl; // { B: ... }
}
```

**Comment by froatsnook** [comment]
Hey @gregmarr 

I see.  I just wonder if there's another way to do it without making a copy of the data?

**Comment by nlohmann** [comment]
The library cannot store references or pointers at this point, but will always make a copy of the values to store. It thereby mimics the behavior of the STL containers. Sorry about this.

**Comment by gregmarr** [comment]
You can't rebind references.  You need to use a new reference each time, or use something like std::reference_wrapper.  http://en.cppreference.com/w/cpp/utility/functional/reference_wrapper
