### ISSUE TITLE
[Question] CBOR rfc support.

### ISSUE THREAD

**Issue by FrozenSource** [nlohmann/json#2779]
Hi,

Love your project, have been using it for a while. For a project, I spotted that this library also supports CBOR conversions.
But I couldn't find which RFC's are used, could you elaborate. I am looking for RFC 8949 support.

Sincerely,
FrozenSource

**Comment by nlohmann** [comment]
Yes, we support CBOR. See https://json.nlohmann.me/features/binary_formats/cbor/ for an overview. I just note that at the time of implementation, RFC 7049 was recent. I have not yet checked what RFC 8949 changed.

**Comment by FrozenSource** [comment]
That’s a bummer since I’m restricted by regulations which are 2 months old 🤣🤣🤣. Oh well thanks either way.

**Comment by nlohmann** [comment]
Can you elaborate?

**Comment by FrozenSource** [comment]
Under new European regulations the RFC 8949 has become the standard for medical data transfer and we are supposed to comply with this. Even though it’s out since December… Though I doubt we need it, we should comply either way since you never know.
Then again I just really liked this library so it was worth asking. Guess we have to look for something else. 
I myself also have no idea what’s different.

**Comment by nlohmann** [comment]
The spec only mentions some examples. Would it help if I update the documentation?

**Comment by FrozenSource** [comment]
No I would say the website doc is fine. It’s just that I need the compliance in such short notice.

**Comment by nlohmann** [comment]
RFC 8949 states:

>   This document obsoletes RFC 7049, providing editorial improvements,
>   new details, and errata fixes while keeping full compatibility with
>   the interchange format of RFC 7049.  It does not create a new version
>   of the format.

As this library supports the format described in RFC 7049, it by definition also supports RFC 8949.

**Comment by FrozenSource** [comment]
Well I guess this is my lucky day. I clearly seem to have read over that. Sorry 🤣🤣🤣.
