### ISSUE TITLE
Value with spaces cannot be parsed

### ISSUE THREAD

**Issue by oleksandrlynda** [nlohmann/json#2781]
I cannot parse simple JSON if it has spaces in the value:
`{"testKey":"Value with spaces"}`

I have exception:
terminate called after throwing an instance of 'nlohmann::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at line 1, column 18: syntax error while parsing value - invalid string: missing closing quote; last read: '"Value'

Version:  3.9.1

**Comment by oleksandrlynda** [comment]
[prov.txt](https://github.com/nlohmann/json/files/6510492/prov.txt)

The file

**Comment by oleksandrlynda** [comment]
Also I can create this json using this library but cannot read it.

My system is: Linux o3 5.8.0-53-generic #60~20.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

**Comment by oleksandrlynda** [comment]
Data is parsed like that:
```
        std::ifstream i(path);
        std::string data;
        i >> data;
        nlohmann::json rootJson = nlohmann::json::parse(data);
```

**Comment by nlohmann** [comment]
Your code does not read the complete file into the string, but only until the first space is read. This is not related to this library.

If I output `data` before parsing, I get the following output:

```
{"testKey":"Value
```

Then, the error message makes sense, because indeed a closing quote is missing.

The following works:

```cpp
#include <fstream>
#include <iostream>
#include "json.hpp"

int main()
{
    std::string path = "/Users/niels/Downloads/prov.txt";
    std::ifstream i(path);
    nlohmann::json rootJson = nlohmann::json::parse(i);
    std::cout << rootJson << std::endl;
}
```

Output:

```json
{"testKey":"Value with spaces"}
```

**Comment by oleksandrlynda** [comment]
Great, thanks for the help.
