### ISSUE TITLE
Referencing a subkey which doesn't exist gives crash

### ISSUE THREAD

**Issue by sreerajchundayil** [nlohmann/json#2797]
I am not sure whether this is a real bug or undefined behaviour, it's related to referencing a subkey which doesn't exist including its parent.

My understanding is that when I try to do a C++ reference of a json object , if the key doesn't exist it will insert the key
and give back the reference of it.
In my example I have a main object `json js = null;`
Now I am trying to do `json& newJs = js["key1"]["key2"];`
Later when I try to insert some object to this newJs, it crashes.
I overcame this issue by doing first `js["key1"]["key2"] = null` and then giving reference of it.

If you think this is not an undefined behaviour, I will try to replicate the issue in simpler code.

**Comment by t-b** [comment]
This is documented behaviour,  see https://nlohmann.github.io/json/api/basic_json/operator%5B%5D/. Use https://nlohmann.github.io/json/api/basic_json/at/ which does handle non-existing keys gracefully.

**Comment by sreerajchundayil** [comment]
It's explained in documentation. Closing this issue.
