### ISSUE TITLE
strings can't be accessed after dump()->parse() - type is lost

### ISSUE THREAD

**Issue by guygman** [nlohmann/json#281]
Hi,

strangely, this code doesn't work and I can't find out what I'm doing wrong.... 

nlohmann::json out;
out[accessTokenField] = (const string&)accessToken;   // key and value std::strings
std::string tmp1 = out[accessTokenField]; // this works
std::string dump = out.dump(); // 'dump' is - {"accessToken": "b9c6f71f-0a10-4025-9628"}
nlohmann::json in;
in.parse(dump);
std::string tmp2 = in[accessTokenField]; // this fails!! error message- "type must be string, but is null"

update: using the static json::parse method works fine-
.
.
nlohmann::json in;
in = nlohmann::json::parse(dump);
std::string tmp2 = in[accessTokenField];

**Comment by nlohmann** [comment]
The [`parse`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a35303ad045a06c2a79dc28ac29652e86.html#a35303ad045a06c2a79dc28ac29652e86) function is static and *returns* the parsed JSON value. Instead of

```cpp
in.parse(dump);
```

which does not alter `in` and leaves it as `null`, the code should read

```
in = nlohmann::json::parse(dump);
```
