### ISSUE TITLE
value() does not work with _json_pointer types

### ISSUE THREAD

**Issue by clwill** [nlohmann/json#283]
It would be great if value(), which supports default values, worked like at() which can handle _json_pointer types.

This would allow the handling of nested objects, and still be robust to missing elements.

To wit:

```cpp
#include <json.hpp>

using json = nlohmann::json;

int main()
{
    json j =
    {
        {"object", {{"key1", 1}, {"key2", 2}}},
    };

    int at_integer = j.at("/object/key2"_json_pointer);
    int val_integer = j.value("/object/key2"_json_pointer, 0);

    std::cout << std::boolalpha << at_integer << " " << val_integer
              << " " << (at_integer == val_integer) << "\n";
}
```

This code produces the output:

```
2 0 false
```

Would be nice if it was `2 2 true`.

**Comment by nlohmann** [comment]
Hi @clwill, thanks for reporting. It definitely makes sense to have the symmetry between `value` and `at`. I shall extend the function once #278 is solved.

**Comment by clwill** [comment]
Sounds great, thanks.

Chris

**Comment by nlohmann** [comment]
As the discussion in #278 got quieter, I extended the `value` function accordingly.

**Comment by clwill** [comment]
Thanks so much!

Unfortunately, the project I'm currently embroiled in requires CUDA, and their tools only work on VS 2013 (until they release 8.0). And your great code doesn't compile over there... <darn it>

I'll be back to your library when CUDA releases 8.0 in August.
