### ISSUE TITLE
HELP! There is a memory leak in the code?!

### ISSUE THREAD

**Issue by HuberyQ** [nlohmann/json#2837]
### Discussed in https://github.com/nlohmann/json/discussions/2836

<div type='discussions-op-text'>

<sup>Originally posted by **HuberyQ** June 23, 2021</sup>
Sorry to attract you with such a scary title. First of all, I would like to thank you for this work!

I found that after parsing the. MSG file, I got the JSON object successfully, **but the CPU memory was not released until the end of the program!** Is there a mistake in the way I use it? Can you manually free up the consumed memory?

The size of the. MSG file is about 24MB, **but the memory consumption of the parsing process is about 0.4G!** Here is the test source code:

```cpp
void test_json(string path)
{
    std::ifstream ifs(path, std::ios::in | std::ios::binary);
    if (!ifs.is_open())
    {
        throw std::runtime_error("cannot load the file at " + path);
    }

    std::vector<uint8_t> msgpack;
    while (true)
    {
        uint8_t buffer;
        ifs.read(reinterpret_cast<char*>(&buffer), sizeof(uint8_t));
        if (ifs.eof())
        {
            break;
        }
        msgpack.push_back(buffer);
    }
    ifs.close();

    const auto json = nlohmann::json::from_msgpack(msgpack);
    cout << sizeof(json) / 1024.0 / 1024.0 << endl;
}
```

**Comment by HuberyQ** [comment]
I have two questions: (1) How to release the memory consumption that has not been released? (2) Why is memory consumption so huge?
Hope to get help from you or other people, thank you!

**Comment by HuberyQ** [comment]
This is the .msg file:[https://raw.githubusercontent.com/HuberyQ/Learning-OpenCV-3_examples/master/1.msg](url)

**Comment by HuberyQ** [comment]
https://raw.githubusercontent.com/HuberyQ/Learning-OpenCV-3_examples/master/1.msg

**Comment by HuberyQ** [comment]
I didn't test with Valgrind or ASAN...I just monitoring CPU through my terminal.
Ubuntu 20.04 / C++11

**Comment by nlohmann** [comment]
- There is no memory leak in the library - you can compile your code with ASAN or run it with Valgrind. All memory acquired for `json` is release once it goes out of scope.
- The memory consumption of the library is due to the overhead described in the README:
    > Each JSON object has an overhead of one pointer (the maximal size of a union) and one enumeration element (1 byte).
    
    Your JSON value contains of a lot of numbers, and hence this overhead adds up.

Note the overhead is much smaller if you compile your binary in release mode.

**Comment by HuberyQ** [comment]
>     * There is no memory leak in the library - you can compile your code with ASAN or run it with Valgrind. All memory acquired for `json` is release once it goes out of scope.
> 
>     * The memory consumption of the library is due to the overhead described in the README:
>       > Each JSON object has an overhead of one pointer (the maximal size of a union) and one enumeration element (1 byte).
>       
>       
>       Your JSON value contains of a lot of numbers, and hence this overhead adds up.
> 
> 
> Note the overhead is much smaller if you compile your binary in release mode.

Thank you for your reply! But when the **test_json** function exits, the CPU memory growth caused by it is not released! You can use the data and code above to reproduce it. We need your help!

**Comment by nlohmann** [comment]
I cannot reproduce this:

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/159488/123216535-f0e53400-d4c9-11eb-9f8d-5b1dbbbeb3c2.png">

The library releases all memory, there are no memory leaks. Can you please try to run your code with Valgrind or ASAN?

**Comment by gregmarr** [comment]
For an explanation of why memory freed by the application isn't returned to the OS: https://stackoverflow.com/questions/45538993/why-dont-memory-allocators-actively-return-freed-memory-to-the-os

**Comment by HuberyQ** [comment]
> For an explanation of why memory freed by the application isn't returned to the OS: https://stackoverflow.com/questions/45538993/why-dont-memory-allocators-actively-return-freed-memory-to-the-os

Thanks! It really helps a lot!

**Comment by HuberyQ** [comment]
> I cannot reproduce this:
> 
> <img alt="image" width="1148" src="https://user-images.githubusercontent.com/159488/123216535-f0e53400-d4c9-11eb-9f8d-5b1dbbbeb3c2.png">
> 
> The library releases all memory, there are no memory leaks. Can you please try to run your code with Valgrind or ASAN?
I tested on different systems：
ubuntu16：It's normal and ok!
ubuntu18：The memory was not released!
Then I refered to #1924 , and it worked! I guess that different versions of the glibc lead to different memory recovery mechanisms.

Thanks a lot! 
This library is really good to use!

**Comment by HuberyQ** [comment]
> I cannot reproduce this:
> 
> <img alt="image" width="1148" src="https://user-images.githubusercontent.com/159488/123216535-f0e53400-d4c9-11eb-9f8d-5b1dbbbeb3c2.png">
> 
> The library releases all memory, there are no memory leaks. Can you please try to run your code with Valgrind or ASAN?



I tested on different systems：
    ubuntu16：It's normal and ok!
    ubuntu18：The memory was not released!

Then I refered to #1924 , and it worked! I guess that different versions of the glibc lead to different memory recovery mechanisms.

Thanks a lot!
This library is really good to use!

**Comment by nlohmann** [comment]
Do you need further assistance with this issue?

**Comment by HuberyQ** [comment]
> Do you need further assistance with this issue?

Nope.Thanks!
