### ISSUE TITLE
Braced initialization and aggregate initialization behavior is different for `json::array()` function call.

### ISSUE THREAD

**Issue by Elnee** [nlohmann/json#2848]
#### What is the issue you have?
Braced initialization of variable with `json::array()` has different result from aggregate initialization.

#### Please describe the steps to reproduce the issue.

1. Run the code below.

#### Can you provide a small but working code example?

```c++
#include <nlohmann/json.hpp>
#include <iostream>

int main(int argc, char* argv[])
{
  auto aggregate = nlohmann::json::array();
  std::cout << aggregate.size() << std::endl;

  auto uniform{ nlohmann::json::array() };
  std::cout << uniform.size() << std::endl;
  
  return 0;
}
```

#### What is the expected behavior?
0 size for both.

#### And what is the actual behavior instead?
0 size for aggregate initialization and 1 size for braced initialization.

#### Which compiler and operating system are you using?

- Compiler: gcc 9.3.0
- Operating system: Ubuntu 20.04

#### Which version of the library did you use?

- [x] latest release version 3.9.1
- [ ] other release - please state the version: ___
- [ ] the `develop` branch

**Comment by gregmarr** [comment]
See #2311

**Comment by Elnee** [comment]
I am sorry, but I don't understand how those issues related to this issue. They all talk about different behavior for different compilers, but this issue talks about different behavior on the same gcc compiler between braced and aggregate initializations.

**Comment by nlohmann** [comment]
This is the same issue as #2311. In Clang, both initializations result in the same value, whereas GCC interprets braced initialization as putting the value into a new array.

**Comment by Elnee** [comment]
Ok. Thank you for explanation.
