### ISSUE TITLE
json::parse() works only with absolute paths

### ISSUE THREAD

**Issue by wiljam144** [nlohmann/json#2851]
So when i'm trying to read from a json file everything works fine with absolute paths but when i pass relative path the program crashes with this error message:
```
terminate called after throwing an instance of 'nlohmann::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
make: *** [Makefile:2: start] Error 3
```
the function code:
```
json loadFile(string filename) {
    ifstream ifs(filename);
    json data = json::parse(ifs);
    ifs.close();
    return data;
}
```

**Comment by nlohmann** [comment]
`unexpected end of input` means the that no input could be read - this is not a bug in the library, but just an indication that the file could not be read in the first place. Please make sure the working directory is correct. Maybe try to dump the file content to stdout without calling `parse` first.
