### ISSUE TITLE
string literals possibly being parsed as another type due to the presence of only digits and full-stops

### ISSUE THREAD

**Issue by nicholasdkunes** [nlohmann/json#2852]
I believe the parser is parsing IP strings like "10.0.1.1" or version strings like "2021.1.0" as something other than a string, and it fails to convert when a string is requested.

See below:
```
j["SW_VERSION"].get<std::string>();
```
Where:
```
"SW_VERSION":"2021.1.0"
```
Results in:
```
Exception thrown at 0x00007FFB0F0E467C in dx12win10.exe: Microsoft C++ exception: nlohmann::detail::type_error at memory location 0x000000D4FEEFEBC8.
```

**Comment by nicholasdkunes** [comment]
type_name() returns "number"

**Comment by nlohmann** [comment]
Can you share a small example of your JSON and your code?
