### ISSUE TITLE
Incorrect parsing of large int64_t numbers

### ISSUE THREAD

**Issue by mariobadr** [nlohmann/json#287]
Hello,

I use dynamic instrumentation to gather information about a program, and then output it using your json library to a file. When I parse the file into a different application using your library, I get different values. Below is a minimal example:

**_main.cpp_**
```
#include <fstream>
#include <iostream>

#include "json.hpp"

int main(int argc, char** argv) {
  using json = nlohmann::json;

  if(argc != 2) {
    return 0;
  }

  std::ifstream stream(argv[1]);
  json j;
  stream >> j;

  std::cout << j["id"] << "\n";

  return 0;
}
```

**_test.json_**
`
{
  "call": "pthread_mutex_lock",
  "id": 8492065431569638403,
  "object": 139898772169632
}
`

_**Output**_
`8492065431569638400`

The documentation states that numbers are stored in int64_t, and that the maximum value allowed is 9223372036854775807. The above value is less than that number, so I'm not sure what the problem is. Thanks.

Edit: I am using version 1.1.0

**Comment by mariobadr** [comment]
Sorry, just noticed #178 and tried out version 2.0.2 and everything works fine now. Thanks for the awesome library!

**Comment by nlohmann** [comment]
No worries! :)
