### ISSUE TITLE
g++ (11) -Wuseless-cast gives lots of warnings

### ISSUE THREAD

**Issue by fhuberts** [nlohmann/json#2893]
#### What is the issue you have?

When I compile the 'single include' file on g++ v11 on my Fedora 34 machine with the '-Wuseless-cast' flags enabled then I get lots of warnings.

#### Please describe the steps to reproduce the issue.

1. enable the -Wuseless-cast compiler flag and compile
2.
3.

#### Which compiler and operating system are you using?

- Compiler: gnu g++ v11
- Operating system: Fedora 34 x64

```
g++ (GCC) 11.1.1 20210531 (Red Hat 11.1.1-3)
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

#### Which version of the library did you use?

- [ ] latest release version 3.9.1
- [x] other release - please state the version: commit a563338039346c9ed722e09547419190b1eeddbe
- [ ] the `develop` branch

#### If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

- [ ] yes
- [ ] no - please copy/paste the error message below

**Comment by nlohmann** [comment]
Can you provide the warnings?

**Comment by fhuberts** [comment]
So it turns out 'lots' is 2. I just saw lots bacause we include it in lots of places. oops.
```
xxx/json.hpp: In member function ‘bool nlohmann::detail::binary_reader<BasicJsonType, InputAdapterType, SAX>::parse_cbor_internal(bool, nlohmann::detail::cbor_tag_handler_t)’:
xxx/json.hpp:8856:80: warning: useless cast to type ‘std::size_t’ {aka ‘long unsigned int’} [-Wuseless-cast]
 8856 |                 return get_number(input_format_t::cbor, len) && get_cbor_array(static_cast<std::size_t>(len), tag_handler);
      |                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
xxx/json.hpp:8910:81: warning: useless cast to type ‘std::size_t’ {aka ‘long unsigned int’} [-Wuseless-cast]
 8910 |                 return get_number(input_format_t::cbor, len) && get_cbor_object(static_cast<std::size_t>(len), tag_handler);
      |                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by nlohmann** [comment]
These are hard to fix, because not all architectures have the same definitions for size_t.

**Comment by nlohmann** [comment]
I double checked. In both cases, there is a cast from `std::uint64_t` to `std::size_t`:

```cpp
std::uint64_t len{};
return get_number(input_format_t::cbor, len) && get_cbor_object(static_cast<std::size_t>(len), tag_handler);
```

I case these types are the same, your reported warning makes sense. However, the types do not necessarily need to be the same.

Does anyone has an idea how to silence this warning?

**Comment by t-b** [comment]
I guess one could use something like the following

```
#include <type_traits>

template<typename T, typename U, std::enable_if_t<!std::is_same<T, U>::value, int> = 0>
T conditional_static_cast(U value)
{
return static_cast<T>(value);
}

template<typename T, typename U, std::enable_if_t<std::is_same<T, U>::value, int> = 0>
T conditional_static_cast(U value)
{
return value;
}

void func()
{
    int a = conditional_static_cast<int>(0);
    int b = static_cast<int>(0);

}
```

The first line in func gives no warning the second does.

**Comment by fhuberts** [comment]
I think I've dealt with this before, need to look it up.
Solution was something with ifdef's and type sizes

**Comment by nlohmann** [comment]
Thanks @t-b - I was thinking of preprocessor magic before, but this is much cleaner. I'll give it a try, see #2902.

**Comment by fhuberts** [comment]
tnx!

**Comment by Pirulax** [comment]
~~Wouldn't it be easier to just disable the warning instead making a workaround for it?
It seems like a pretty useless warning anyways, and disabling it is pretty straight forward.
EDIT:
Though it's used in headers too, so it might not be possible.~~
EDIT2: Sorry, I just noticed this isn't spdlog github, please disregard.
