### ISSUE TITLE
Support for integers not from the range [-(2**53)+1, (2**53)-1] in parser

### ISSUE THREAD

**Issue by antonovvk** [nlohmann/json#291]
Currently the test below fails:
```C++
TEST(WTF, BigInteger)  {
    nlohmann::json val = -3383556239975101330LL;
    val = nlohmann::json::parse(val.dump());
    EXPECT_EQ(-3383556239975101330, val.get<int64_t>());
}
```
And this is the internal inconsistency.
As far as I know, RFC does not require JSON integers to be in any range.
I think that internal consistency is more important than possible non-interoperability with third-party JSON parsers.

**Comment by antonovvk** [comment]
Sorry, I was using v1.1.0 and haven't noticed that this is fixed in newer versions.
Thank you for the great lib!

**Comment by nlohmann** [comment]
No problem - when I saw the title, I though "Man, didn't we already fix this?" ;-)
