### ISSUE TITLE
compiler warning: "not return a value"

### ISSUE THREAD

**Issue by GaRaOne** [nlohmann/json#2917]
#### What is the issue you have?

const typename object_t::key_type& key() const
nlohmann/json.hpp:11996:5: warning: non-void function does not return a value in all control paths [-Wreturn-type]

static ReferenceType get_ref_impl(ThisType& obj)
nlohmann/json.hpp:20017:5: warning: non-void function does not return a value in all control paths [-Wreturn-type]

reference operator[](T* key)
nlohmann/json.hpp:20925:5: warning: non-void function does not return a value in all control paths [-Wreturn-type]

const_reference operator[](const typename object_t::key_type& key) const
nlohmann/json.hpp:20877:5: warning: non-void function does not return a value in all control paths [-Wreturn-type]

and many more... mostly looking like:

```
    ReturnType fooBar( xxx )
    {
        if (JSON_HEDLEY_LIKELY( xxx ))
        {
          return xxx;
        }

        JSON_THROW( xxx );
    }

```
#### Please describe the steps to reproduce the issue.

1. use custom JSON_THROW_USER without exceptions
2. compile

#### What is the expected behavior?

no warnings

#### Which compiler and operating system are you using?

- Compiler: clang
- Operating system: ubuntu 21.04

#### Which version of the library did you use?

- [x] latest release version 3.9.1
- [ ] other release - please state the version: ___
- [ ] the `develop` branch

---

i'm not sure if this is intentional behavior. however, it floods the compiler output.
is there a trick to keep in mind when adding your own JSON_THROW?

ps: thanks for the awesome library. great work

**Comment by nickaein** [comment]
Which version of clang are you using?

Also, can you provide a minimal code sample that reproduces this issue?

**Comment by nlohmann** [comment]
I recently fixed something similar in https://github.com/nlohmann/json/pull/2898 which is not yet merged. So far, we never make a pedantic check with exceptions switched off.

**Comment by nlohmann** [comment]
From the [documentation of `JSON_THROW_USER`](https://json.nlohmann.me/features/macros/#json_throw_userexception):

> Note that JSON_THROW_USER should leave the current scope (e.g., by throwing or aborting), as continuing after it may yield undefined behavior.

The warnings you describe only occur if you do not leave the scope, but let the control flow reach its end without returning a value. There is nothing we can do in this situation - there are no default values to return in case of exceptions.
