### ISSUE TITLE
Errors during ninja test

### ISSUE THREAD

**Issue by breisfeld** [nlohmann/json#2918]
Hi,

I just built and tested the `rxDock` as per the instructions in the `INSTALL.md` file.  Unfortunately, all of the tests failed.

I am attaching `testlog.txt` with the details.

rxDock:
```
$ git rev-parse HEAD
307d7d541fbd213eac6968e117d36a837b65d67e
```

Platform: Fedora release 34.
```
$ uname -a
Linux xx.xx.xx 5.12.13-300.fc34.x86_64 #1 SMP Wed Jun 23 16:18:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

[testlog.txt](https://github.com/nlohmann/json/files/6934565/testlog.txt)

**Comment by nlohmann** [comment]
This seems to be unrelated to this library, but to whatever rxdock is.

**Comment by breisfeld** [comment]
I'm sorry. I meant to submit the report to the rxDock project. It happens that they use your library. Sorry for the noise.
