### ISSUE TITLE
Q: Is it possible to build json tree from already UTF8 encoded values?

### ISSUE THREAD

**Issue by clarkk** [nlohmann/json#293]
Is it possible to build a JSON tree from already UTF8 encoded strings?

eg
`utf8 encoded string with Ã¦Ã¸Ã¥`

**Comment by nlohmann** [comment]
I am not sure what you mean. You can parse any valid JSON text with `json::parse()`, including UTF-8 encoded strings. You can also create a JSON object with type string by calling the constructor with `std::string` or `const char[]`.

**Comment by nlohmann** [comment]
@clarkk Could you please clarify?

**Comment by clarkk** [comment]
just close the issue.. it was late when I wrote it :)
