### ISSUE TITLE
Linker error LNK2005 when compiling (x64) json-3.10.0.zip with Visual Studio 2019 16.11.1 

### ISSUE THREAD

**Issue by Andreas-Schniertshauer** [nlohmann/json#2941]
#### What is the issue you have?

Linker error LNK2005:

```
unit-regression2.obj : error LNK2005: "public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > * sax_no_exception::error_string" (?error_string@sax_no_exception@@2PEAV?$basic_string@DU?$char_traits@D@std@@V?$allo
cator@D@2@@std@@EA) already defined in unit-disabled_exceptions.obj [build\json\test\json_unit.vcxproj]
build\json\test\Release\json_unit.exe : fatal error LNK1169: one or more multiply defined symbols found [build\json\test\json_unit.vcxproj]
```

#### Can you provide a small but working solution / fix?

Add a namespace in both files `json\test\src\unit-disabled_exceptions.cpp` and `json\test\src\unit-regression2.cpp`:

```
namespace
{
  class sax_no_exception : public nlohmann::detail::json_sax_dom_parser<json>
  {
  ...
  };
  std::string* sax_no_exception::error_string = nullptr;
}  // namespace
```

#### What is the expected behavior?

No link error

#### And what is the actual behavior instead?

LNK2005 error

#### Which compiler and operating system are you using?

- Compiler:  Visual Studio 2019 16.11.1 Professional
- Operating system:  Windows 10 21H1

#### Which version of the library did you use?

- [x] latest release version 3.10.0 (zip file)
- [ ] other release - please state the version: ___
- [ ] the `develop` branch

#### If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

- [ ] yes
- [x] no - please copy/paste the error message below

**Comment by nlohmann** [comment]
Very strange. We are using these versions in the CI without problems:

<img width="847" alt="image" src="https://user-images.githubusercontent.com/159488/129860569-187faa85-aa5c-4a32-8136-d9157d351ee4.png">

Can you share the build settings? What are you building? I am confused that `unit-disabled_exceptions.cpp` and `unit-regression2.cpp` should affect each other.

**Comment by nlohmann** [comment]
Alright, I can reproduce what you're doing. You're building the binary `json_unit` which links all tests. The unit tests are documented to be build with

**Comment by Andreas-Schniertshauer** [comment]
I am building in the x64 Developer Command Prompt of Visual Studio 2019 16.11.1 with cmake 3.20.21032501-MSVC_2 (Visual Studio) and msbuild 16.11.0.36601 with a lot of parameters passed to cmake, but you can reproduce it very easily with this command:

```
cmake ..\..\json .
```
I use normally these flags for cmake from json:
`
 -D JSON_Install:BOOL=OFF -D JSON_ImplicitConversions:BOOL=OFF -D JSON_BuildTests:BOOL=ON
`

**Comment by nlohmann** [comment]
But what do you build then?

**Comment by nlohmann** [comment]
(The binary `json_unit` is marked `EXCLUDE_FROM_ALL`, so I don't think it was built with the test suite.
