### ISSUE TITLE
warning C4706: assignment within conditional expression

### ISSUE THREAD

**Issue by marsh0** [nlohmann/json#295]
There is a few lines like:

    if (keep and (not callback or (keep = callback(depth++, parse_event_t::object_start, result))))

That are causing warnings and make projects that treat warnings as errors unable to compile without fixing it or disabling warnings in the code. 

Microsoft Visual Studio Compiler 2015

**Comment by nlohmann** [comment]
I understand the warnings, but they seem to be uncritical and rather pedantic. A solution would be to either restructure the code by moving the assignment out of the conditional and make it less readable or to add `#pragma`s and make the code even less readable. Any other suggestions?

**Comment by nlohmann** [comment]
Just to better understand MSVC at warning level 4: Would

```cpp
if (keep and (not callback or ((keep = callback(depth++, parse_event_t::object_start, result))) != 0))
```

fix this issue?

**Comment by marsh0** [comment]
Yes that fixes the issue. 

It could be rewritten I do not think it makes it any less clear, (I personally find that line with increment depth in the if a bit confusing to begin with. (But I am not a super experienced coder). )

For a easy fix you could just add: 

#ifdef _MSC_VER 
#pragma warning(push)
#pragma warning(disable:4706) // assignment within conditional expression
#endif
...

#ifdef _MSC_VER 
 #pragma warning(pop)
#endif

There is already some code that ignores specific warnings for clang.

But its really up to you, as you said its not a critical problem. Just requires a tiny bit more work for someone integrating it. 


Awesome library btw, easy to use and great features.

**Comment by nlohmann** [comment]
Ok. I think adding some `!= 0` is a bit nicer than adding another pragma in an ifdef. I wonder why MSVC is not silenced by another pair of parentheses like Clang.

Thanks for reporting! For a MSVC beginner - can you tell me how to compile a CMake project with this level of warnings?

**Comment by marsh0** [comment]
Sorry to say I do not use CMake nor no how. I just included the source file in my visual studio project.

That being said Warning level 4 is /W4 or even better EnableAllWarnings is /Wall.

**Comment by nlohmann** [comment]
Thanks! I shall add this to the AppVeyor build to see what else MSVC is warning about.

**Comment by nlohmann** [comment]
I ran an [AppVeyor build](https://ci.appveyor.com/project/nlohmann/json/build/1145) with `/Wall` flags. All output is in the [log.txt](https://github.com/nlohmann/json/files/423582/log.txt) file.

**Comment by nlohmann** [comment]
@marsh0 Could you please check if the warnings disappeared?

**Comment by marsh0** [comment]
Yup, looks good now! Thanks!

**Comment by nlohmann** [comment]
Thanks for checking!

**Comment by eliasdaler** [comment]
Don't want to create a new thread, but I still have this warning on -W4 in VS 2017. Probably new expressions which should use the same pattern?

Or maybe #pragma will really be needed.

**Comment by nlohmann** [comment]
@eliasdaler Could you open an issue and paste the warnings? Please use the develop version.
