### ISSUE TITLE
2 tests fail in 3.10.0: cmake_fetch_content_configure, cmake_fetch_content_build

### ISSUE THREAD

**Issue by yurivict** [nlohmann/json#2951]
```
      Start 64: cmake_fetch_content_configure
64/67 Test #64: cmake_fetch_content_configure ................***Failed    0.10 sec
[  0% 1/8] Performing download step (git clone) for 'json-populate'
fatal: repository '/disk-samsung/freebsd-ports/devel/nlohmann-json/work/json-3.10.0' does not exist
fatal: repository '/disk-samsung/freebsd-ports/devel/nlohmann-json/work/json-3.10.0' does not exist
fatal: repository '/disk-samsung/freebsd-ports/devel/nlohmann-json/work/json-3.10.0' does not exist
-- Had to git clone more than once:
          3 times.
CMake Error at json-subbuild/json-populate-prefix/tmp/json-populate-gitclone.cmake:31 (message):
  Failed to clone repository:
  '/disk-samsung/freebsd-ports/devel/nlohmann-json/work/json-3.10.0'


FAILED: json-populate-prefix/src/json-populate-stamp/json-populate-download 
cd /disk-samsung/freebsd-ports/devel/nlohmann-json/work/.build/test/cmake_fetch_content/_deps && /usr/local/bin/cmake -P /disk-samsung/freebsd-ports/devel/nlohmann-json/work/.build/test/cmake_fetch_content/_deps/json-subbuild/json-populate-prefix/tmp/json-populate-gitclone.cmake && /usr/local/bin/cmake -E touch /disk-samsung/freebsd-ports/devel/nlohmann-json/work/.build/test/cmake_fetch_content/_deps/json-subbuild/json-populate-prefix/src/json-populate-stamp/json-populate-download
ninja: build stopped: subcommand failed.

CMake Error at /usr/local/share/cmake/Modules/FetchContent.cmake:1012 (message):
  Build step for json failed: 1
Call Stack (most recent call first):
  /usr/local/share/cmake/Modules/FetchContent.cmake:1141:EVAL:2 (__FetchContent_directPopulate)
  /usr/local/share/cmake/Modules/FetchContent.cmake:1141 (cmake_language)
  CMakeLists.txt:12 (FetchContent_Populate)


-- Configuring incomplete, errors occurred!
See also "/disk-samsung/freebsd-ports/devel/nlohmann-json/work/.build/test/cmake_fetch_content/CMakeFiles/CMakeOutput.log".

      Start 65: cmake_fetch_content_build
Failed test dependencies: cmake_fetch_content_configure
65/67 Test #65: cmake_fetch_content_build ....................***Not Run   0.00 sec
      Start 66: cmake_target_include_directories_configure
66/67 Test #66: cmake_target_include_directories_configure ...   Passed    0.03 sec
      Start 67: cmake_target_include_directories_build
67/67 Test #67: cmake_target_include_directories_build .......   Passed    0.01 sec

97% tests passed, 2 tests failed out of 67

Label Time Summary:
all                 = 561.56 sec*proc (56 tests)
git_required        =   0.10 sec*proc (2 tests)
not_reproducible    =   0.29 sec*proc (10 tests)

Total Test time (real) = 561.89 sec

The following tests FAILED:
	 64 - cmake_fetch_content_configure (Failed)
	 65 - cmake_fetch_content_build (Not Run)
Errors while running CTest
FAILED: CMakeFiles/test.util 
cd /disk-samsung/freebsd-ports/devel/nlohmann-json/work/.build && /usr/local/bin/ctest --force-new-ctest-process
ninja: build stopped: subcommand failed.
*** Error code 1
```

OS: FreeBSD 13

**Comment by nlohmann** [comment]
Can you provide the exact calls to CMake?

**Comment by yurivict** [comment]
Same in 3.9.1.

-----------------------

cmake call:

/usr/bin/env XDG_DATA_HOME=/disk-samsung/freebsd-ports/devel/nlohmann-json/work XDG_CONFIG_HOME=/disk-samsung/freebsd-ports/devel/nlohmann-json/work HOME=/disk-samsung/freebsd-ports/devel/nlohmann-json/work PATH=/disk-samsung/freebsd-ports/devel/nlohmann-json/work/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin SHELL=/bin/sh CONFIG_SHELL=/bin/sh /usr/local/bin/cmake -DCMAKE_C_COMPILER:STRING=cc -DCMAKE_CXX_COMPILER:STRING=c++ -DCMAKE_C_FLAGS:STRING=-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing  -DCMAKE_C_FLAGS_DEBUG:STRING=-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing  -DCMAKE_C_FLAGS_RELEASE:STRING=-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing  -DCMAKE_CXX_FLAGS:STRING=-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer   -DCMAKE_CXX_FLAGS_DEBUG:STRING=-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer   -DCMAKE_CXX_FLAGS_RELEASE:STRING=-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer   -DCMAKE_EXE_LINKER_FLAGS:STRING= -fstack-protector-strong  -DCMAKE_MODULE_LINKER_FLAGS:STRING= -fstack-protector-strong  -DCMAKE_SHARED_LINKER_FLAGS:STRING= -fstack-protector-strong  -DCMAKE_INSTALL_PREFIX:PATH=/usr/local -DCMAKE_BUILD_TYPE:STRING=Release -DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=YES -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DJSON_MultipleHeaders:BOOL=ON -DJSON_BuildTests:BOOL=OFF -GNinja -DJSON_BuildTests:BOOL=ON /disk-samsung/freebsd-ports/devel/nlohmann-json/work/json-3.10.0

**Comment by nlohmann** [comment]
Are your sources checked out via Git or downloaded otherwise? The specific test that fails in your case requires a Git checkout and is labeled with `git_required`. See the notes in https://github.com/nlohmann/json#execute-unit-tests for how to skip these tests.

**Comment by yurivict** [comment]
Sources are from the tarball from GitHub.

**Comment by nlohmann** [comment]
> Sources are from the tarball from GitHub.

Then https://github.com/nlohmann/json/issues/2951#issuecomment-901308482 describes why the test fails and you can skip this test with

```sh
ctest -LE git_required
```

**Comment by yurivict** [comment]
Ok, thanks,
