### ISSUE TITLE
[Improvement] Add option to remove exceptions

### ISSUE THREAD

**Issue by marsh0** [nlohmann/json#296]
It would be nice to have the option to compile without exceptions for use on platforms where exceptions cannot be enabled., such as consoles etc. 

Mainly for the reasons listed here: http://programmers.stackexchange.com/questions/113479/are-there-any-real-world-cases-for-c-without-exceptions

**Comment by nlohmann** [comment]
Instead of an exception, should the library just call `exit()` or `abort`?

**Comment by marsh0** [comment]
It could assert, and if that fails simply crash. Crash hard crash early.

**Comment by nlohmann** [comment]
This should be done together with #244, because then we have to touch all exceptions anyway.

**Comment by nlohmann** [comment]
Is there a more elegant way than to use preprocessor macros for this?

**Comment by marsh0** [comment]
The way that link details seems reasonable to me. At least the macro should only need to be used once with the try catch. Using -fno-exception may work with the standard library but it will still fail to compile on any try catches or throws in your own code. 

I have seen projects where you can define a preprocessor to remove exceptions. Though I think most libraries either support them or dont. This may cause to much extra code to be worth it. 

Here is another library with the same discussion: https://github.com/gabime/spdlog/issues/136. You could see how they implemented it.

**Comment by abarth** [comment]
Thanks for working on this issue!  I'm interested in this change to because I'd like to use your library in a project that builds with -fno-exceptions.

**Comment by abarth** [comment]
Consider `#define JSON_THROW(exception) std::abort()` rather than defining `JSON_THROW` to nothing when `JSON_NOEXCEPTION` is set to avoid trigging `control may reach end of non-void function` for folks who build with `[-Werror,-Wreturn-type]`

**Comment by nlohmann** [comment]
I implemented this change. Unfortunately, the test suite cannot be compiled with `-fno-exceptions` (see philsquared/Catch/issues/703). All you can do right now is

```
CPPFLAGS="-DJSON_NOEXCEPTION" make
test/json_unit -e
```

(one test fails, because an exception from `std::map` still occurs, but is no caught)

**Comment by nlohmann** [comment]
I shall merge this issue tomorrow.

**Comment by nlohmann** [comment]
Merged 1ab26ab. The library now respects `-fno-exceptions`. Additionally, exceptions can be switched off by defining `JSON_NOEXCEPTION `.
