### ISSUE TITLE
+= issue with multiple redirection.

### ISSUE THREAD

**Issue by sreerajchundayil** [nlohmann/json#2970]
Doing `+=` with `js2["key"]["num"]` is an error while runtime.

Error message is : `what():  [json.exception.type_error.308] cannot use push_back() with number`

But it works fine with `js1["num"]`.
Why are they different, it's against the intuition I think?

And is the error message relevant with the operation we are doing?

```
    int main()
    {
      json js1,js2;
    
      js1["num"] = 0;
      js2["key"]["num"] = 0;
    
      js1["num"] += 10;//fine
      js2["key"]["num"] += 10;//error
    }
```

**Comment by nlohmann** [comment]
Already the first occurrence of `+=` yields the same exception. The library uses `operator+=` as synonym of `push_back`, and it is not usable with numbers.

If you want to use `+=` with the stored integer, you need to make it explicit:

```cpp
int main()
{
    json js1,js2;
  
    js1["num"] = 0;
    js2["key"]["num"] = 0;
  
    js1["num"].get_ref<json::number_integer_t&>() += 10;
    js2["key"]["num"].get_ref<json::number_integer_t&>() += 10;
 
    std::cout << js1 << '\n' << js2 << std::endl;
}
```

Output:

```json
{"num":10}
{"key":{"num":10}}
```
