### ISSUE TITLE
Coverity scan fails

### ISSUE THREAD

**Issue by nlohmann** [nlohmann/json#299]
The recent [coverity scan build](https://travis-ci.org/nlohmann/json/jobs/154004878#L558) failed:

```
[WARNING] No files were emitted. This may be due to a problem with your configuration
or because no files were actually compiled by your build command.
Please make sure you have configured the compilers actually used in the compilation.
 For more details, please look at: 
```

I can reproduce the error locally, but the log file gives no information on the error. The only change made since previous successful builds was the split of the unit tests into several compilation units.

**Comment by cgzones** [comment]
The reason might be the compiler you are using. I tried coverity for one of my projects and it seems coverity does not support the most recent compilers, gcc-6 and clang-3.9. clang-3.6 however worked.

**Comment by nlohmann** [comment]
Interesting! I shall give it a try.

**Comment by nlohmann** [comment]
@cgzones Commit 25548f8 makes Coverity work again. Thanks!
