### ISSUE TITLE
'operator =' is ambiguous on VS2017

### ISSUE THREAD

**Issue by pietro68** [nlohmann/json#2997]
#### What is the issue you have?

I have a minimalistic code snippet which builds on VS2015, but not on VS2017

#### Please describe the steps to reproduce the issue.

1. try building the snippet below in VS2017

#### Can you provide a small but working code example?

`
#include <nlohmann/json.hpp>  // version 3.10.2

void prob()
{
  nlohmann::json foo;
  
  int i = foo["ww"];   // ok

  std::vector<int> vi;
  vi = foo["re"];      // C2593 'operator =' is ambiguous on VS2017; no probs on VS2015
}
`

#### What is the expected behavior?

should build 

#### And what is the actual behavior instead?

compiler error as in title

#### Which compiler and operating system are you using?

- Compiler: Visual Studio 15.9.38
- Operating system: Win10

#### Which version of the library did you use?

- [ X ] latest release version 3.10.2
- [ ] other release - please state the version: ___
- [ ] the `develop` branch

#### If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

- [ X ] yes
- [ ] no - please copy/paste the error message below

**Comment by gregmarr** [comment]
`std::vector` is a templated type, so that won't compile as-is.  What is the actual type of `vi`?

**Comment by pietro68** [comment]
ha! somehow the editor cut the <>. vi is a std::vector<int>

**Comment by gregmarr** [comment]
Assuming `std::vector<int>` then this code will also fail to compile on Clang and GCC, so I assume this is actually a VS2015 issue where it was accepting code that was ambiguous due to some of its loose typing rules.

This version works fine on Clang and GCC

    std::vector vi = foo["re"];

As does this one:

    std::vector<int> vi;
    vi = foo["re"].get<std::vector<int>>();

**Comment by pietro68** [comment]
I confirm your solution works on VS2017! thanks! I see then, it is actually an issue with VS2015 which actually allowed me to type less code... but an issue nevertheless. Thanks again.
