### ISSUE TITLE
Overwriting terminated null character

### ISSUE THREAD

**Issue by smorzhov** [nlohmann/json#3001]
https://github.com/nlohmann/json/blob/ec7a1d834773f9fee90d8ae908a0c9933c5646fc/src/json.hpp#L4684
I think it's better to check here the size of result and do something like:
```
if (result.size() > pos) {
    // overwrite trailing null character
    result[pos] = '\\';
}
```

**Comment by nlohmann** [comment]
I'm not sure if I understand your proposal. Here is the original code for reference:

```cpp
if (c >= 0x00 and c <= 0x1f)
{
    // print character c as \uxxxx
    sprintf(&result[pos + 1], "u%04x", int(c));
    pos += 6;
    // overwrite trailing null character
    result[pos] = '\\';
}
```

The string `result` has already the correct size and contains entirely of slashes. Therefore, we can start writing the `u1234` output at `pos+1` to have `\u1234`. `sprintf` null-terminates the string, so `result[pos]` is a null byte. As later escapings rely on slashes in `result`, we overwrite that null byte with a slash.

**Comment by smorzhov** [comment]
Let's see what's going on if we have `"\x01"` string. `extra_space` for that string will return 5. So `result` in `escape_string` will be of size 6 (1 + 5). And at the end you are doing `result[6] = '\\\\';'.

**Comment by smorzhov** [comment]
Sorry, фccidentally closed the issue

**Comment by nlohmann** [comment]
I just realized that the code you refer to is nearly 6 years old and has since been changed several times. See https://github.com/nlohmann/json/blob/develop/include/nlohmann/detail/output/serializer.hpp#L449 for the current implementation which looks much different to the previous one.
