### ISSUE TITLE
Issue iterating through 'items'

### ISSUE THREAD

**Issue by zlowell2** [nlohmann/json#3021]
When trying to compile my code, I am getting the following error: 

***

XXX.cpp:128:44: error: ‘using value_type = class nlohmann::basic_json<>’ {aka ‘class nlohmann::basic_json<>’} has no member named ‘items’
     for(auto& el: _pc["XX"]["XXXXX"].items()){

***

Prior to running this, I ran a sudo apt-get install nlohmann-json-dev. Any solution other than using the json.hpp header?

**Comment by nlohmann** [comment]
Which version are you using?

**Comment by nlohmann** [comment]
The `items()` function has been added in version 3.0.0 - it seems you are using an older version of the library. You can find out which version you are using with `meta()` (see https://json.nlohmann.me/api/basic_json/meta/).

**Comment by zlowell2** [comment]
Sounds good. I will update to the most recent version. I'm using Linux and figured the apt-get install nlohmann-json-dev would be the most up to date version, but I guess not.

**Comment by nlohmann** [comment]
Do you need further assistance with this issue?

**Comment by zlowell2** [comment]
No I do not. Thank you
