### ISSUE TITLE
std::shared_ptr<T> == nlohmann::json compiles, which seem undesirable

### ISSUE THREAD

**Issue by drussel** [nlohmann/json#3026]
Specifically `std::shared_ptr<nlohmann::json>() == nlohmann::json()` compiles (where one forgot to deference the shared_ptr before comparing).

#### What is the issue you have?
It is easy to miss dereferencing the pointer and so have the comparison not be as desired. 

#### Please describe the steps to reproduce the issue.

`std::shared_ptr<nlohmann::json>() == nlohmann::json()`

#### Can you provide a small but working code example?
`std::shared_ptr<nlohmann::json>() == nlohmann::json()` (which is true) or `std::make_shared<nlohmann::json>() == nlohmann::json()` (which is false)

#### What is the expected behavior?

A compilation error would be really nice as it is very likely a bug.

#### And what is the actual behavior instead?

Compiles (as far as I know, the comparison result is what you would expect given that it compiles.

#### Which compiler and operating system are you using?

- Compiler: apple-clang 12,13. Visual Studio 2017. Gcc 9.
- Operating system: various

#### Which version of the library did you use?

- [X] latest release version 3.10.2
- [X] other release - please state the version: 3.9.1
- [ ] the `develop` branch

**Comment by gregmarr** [comment]
This is due to the implicit conversions/constructors in the library.  If you disable them, then this code no longer compiles.  See here for how to disable them:
https://github.com/nlohmann/json#implicit-conversions

**Comment by maddanio** [comment]
so this issue can be closed, right? works as designed?

**Comment by drussel** [comment]
Works as designed and I can’t think of a better design.
