### ISSUE TITLE
accept and parse function not work well with a pure number string

### ISSUE THREAD

**Issue by WYHuestc** [nlohmann/json#3029]
When parse and accept a string, if the string is pure number string like "123" 
accept will return true(it looks a error result)
parse will not throw a exception(I think it is wrong, It should throw a expection)
after parse we use this object to emplace it throw a expection json.exception.type_error.311

Example code:
```cpp
using namespace nlohmann;
int main(){
    auto j = json::array();
    std::string my_input = "123456";
    if (json::accept(my_input)){
        std::cout << "it is a json" << std::endl;
    } else {
        std::cout << "it is not a json" << std::endl;
    }
    try
    {
        j = json::parse(my_input, nullptr, false);
        std::cout << "is_discarded: " << (j.is_discarded() ? "true" : "false") << std::endl;
        std::cout << "j.dump(): " << j.dump() << endl;
    }
    catch (json::exception& ex)
    {
        std::cout << "parse error reason: " << ex.what() << std::endl;
    }
    try {
        j.emplace("123","23");
    } catch (json::exception& ex) {
        std::cout << "emplace error reason: " << ex.what() << std::endl;
    }
    return 0;
}
```

The result output is :
**it is a json
is_discarded: false
j.dump(): 123456
emplace error reason: [json.exception.type_error.311] cannot use emplace() with number**

nlohmann::json version : 3.10.2
gcc version:
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: x86_64-apple-darwin20.6.0
Thread model: posix

**Comment by nlohmann** [comment]
This sounds reasonable:

- `123456` is valid JSON, therefore `accept` returns true.
- With `j = json::parse(my_input, nullptr, false);` you overwrite `j` which was an empty array, but is now a number.
- You then call `emplace` which only works with objects or `null` (see https://json.nlohmann.me/api/basic_json/emplace/ or https://json.nlohmann.me/home/exceptions/#jsonexceptiontype_error311)

**Comment by WYHuestc** [comment]
Thx for help
