### ISSUE TITLE
Linking error  "duplicate symbol: std::type_info::operator==" on static build with MinGW

### ISSUE THREAD

**Issue by o-kos** [nlohmann/json#3042]
json 3.9.1 + MinGW 10.3.0 + Clang 12.0.0 x86
Link error on build test example with "--static" flag when use dump() method:
```
warning: failed to compute relocation: IMAGE_REL_I386_REL32, Invalid data was encountered while parsing the file
lld-link: error: duplicate symbol: std::type_info::operator==(std::type_info const&) const
>>> defined at C:/tools/msys64/mingw32/include/c++/10.3.0/typeinfo:121
>>>            objects.a(main.cpp.obj)
>>> defined at libstdc++.a(tinfo.o)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```
without the "--static" flag, the build finishes successfully.
#### Can you provide a small but working code example?

```
#include "nlohmann/json.hpp"
using json = nlohmann::json;

int main()
{
    json j;
    j["pi"] = 3.141;
    std::string s = j.dump(2);
}
```

If comment string with j.dump(), build is ok.

**Comment by nlohmann** [comment]
I am not sure how this issue is related to this library if it mentions a duplicate symbol in namespace `std`... 🤔

**Comment by o-kos** [comment]
But this error exists only when using .dump () method and only in static build mode.

**Comment by nlohmann** [comment]
I understand - but maybe it's just triggering some bug inside the compiler. Anyway, I see if I can reproduce this in the CI.

**Comment by o-kos** [comment]
I looked inside the json.hpp code and reproduced problem without json library:
```
#include <memory>

class output_string_adapter
{
public:
    output_string_adapter() = default;
};

int main()
{
    std::make_shared<output_string_adapter>();
}
```

If last code line don't consist std::make_shared - no error. Do you have anything version about this?

**Comment by nlohmann** [comment]
Thanks for checking back!

**Comment by maveric2** [comment]
See the issue too, but cannot reproduce it with the reduced example (without json). I get the error within another context.
