### ISSUE TITLE
json schema validator

### ISSUE THREAD

**Issue by csitarichie** [nlohmann/json#305]
Is there any plan to extend the project to support json schema for validating serialization/ serialization ?.

**Comment by nlohmann** [comment]
JSON Schema is quite complicated, and it would not make sense to include validation into a header-only library. However, doing this in a different project surely would make sense. Unfortunately, I do not have time for this right now.

**Comment by pboettch** [comment]
I started to do exactly that: 

https://github.com/pboettch/json-schema-validator

**Comment by gregmarr** [comment]
@pboettch Have you looked at https://github.com/tristanpenman/valijson which is a header-only C++ library which was tested to work with v1.1.0 of this library?

**Comment by pboettch** [comment]
I saw it when doing my research, then forgot about it and was disappointed by the validator of rapidjson. Stupid me - it looks good. But I learnt how to use `nlohmann::json` and I learnt about schemas. Was worth the time spent.

**Comment by gregmarr** [comment]
That kind of experience with something you weren't well versed in before is always helpful. :)

**Comment by nlohmann** [comment]
@pboettch So what is the state of your project now? Will you continue or are you happy with tristanpenman/valijson?

**Comment by pboettch** [comment]
I continue. The design approach is different (completely based on your json-lib and nothing else).

**Comment by mipac** [comment]
> JSON Schema is quite complicated, and it would not make sense to include validation into a header-only library. However, doing this in a different project surely would make sense. Unfortunately, I do not have time for this right now.

Sorry for noise, but I can't see why the validation can not be a header only lib?

**Comment by pboettch** [comment]
Which one? valijson is header only. Mine's not. Mine seems to be faster. Compilation and runtime.

**Comment by mipac** [comment]
I've just seen yours, I like the idea of nlohmann lib "addon"
And have you test a header only version of your implementation ;)

**Comment by pboettch** [comment]
No, but you can try it yourself. Just include the .cpp-file in your code. 

You will lose on compile-time, gain nothing on runtime but it might be easier to integrate if you don't want to use CMake.

**Comment by mipac** [comment]
ok I'll give a try 
in a header only form it could be integrated in this lib

thx for your lib, seems very promising

**Comment by pboettch** [comment]
Hammering everything to header-only because project-policies is not helping anyone. At least in my opinion.

**Comment by mipac** [comment]
Oh ok, I don't have enough experience to have a good opinion
But, I think it could be useful to have an header version and a binary version :D
