### ISSUE TITLE
Parsing an emtpy string returns a string with size 1 instead of expected 0

### ISSUE THREAD

**Issue by joda01** [nlohmann/json#3057]
#### What is the issue you have?

When parsing a string from a json object which is empty, the resulting string has a size of one. Expected is a size of zero.

#### Please describe the steps to reproduce the issue.

Use this JSON file
```
{
    "system_id": "",
    "nodes": [
        {
            "id": "node-id",
            "name": "node-name",
            "address": "",
            "limits": [
                980,
                980,
                980
            ]
        }
    ]
}
```

```

json result;
  try {
    std::ifstream input(pathToCfgFile);
    result = json::parse(input);
  } catch(json::exception &e) {
  }

    //
    // Get meters
    //
    auto nodeAry = result["nodes"];
    for(auto node : nodeAry) {
      if(node["address"].size() > 0) {
        // Comes here but should not!!
       std::cout << "ERROR" << std::endl
    }
   }
```

#### What is the expected behavior?

Expected to be the string size zero.

#### And what is the actual behavior instead?

String size is 1

#### Which compiler and operating system are you using?

- Compiler: ___
- Operating system: ___

#### Which version of the library did you use?

C compiler identification is GNU 8.3.0
CXX compiler identification is GNU 8.3.0
OS: debian busters

**Comment by t-b** [comment]
Your code does not compile as `meter` is not defined.

**Comment by nlohmann** [comment]
See also https://json.nlohmann.me/api/basic_json/size/
