### ISSUE TITLE
vcpkg is out of date

### ISSUE THREAD

**Issue by patlecat** [nlohmann/json#3066]
the vcpkg for this lib is over 14 months old

**Comment by gregmarr** [comment]
From the readme:
>If you are using vcpkg on your project for external dependencies, then you can install the nlohmann-json package with vcpkg install nlohmann-json and follow the then displayed descriptions. Please see the vcpkg project for any issues regarding the packaging.

**Comment by nlohmann** [comment]
I am not the maintainer for this.

**Comment by nlohmann** [comment]
(The package at https://github.com/Microsoft/vcpkg/tree/master/ports/nlohmann-json is from last month)
