### ISSUE TITLE
Unhandled exception: nlohmann::detail::parse_error

### ISSUE THREAD

**Issue by ghost** [nlohmann/json#3078]
#### What is the issue you have?
I have an Unhandled exception error:
`Exception thrown at 0x76BBB5B2 in guessTheNumber.exe: Microsoft C++ exception: nlohmann::detail::parse_error at memory location 0x012FE18C.`
`Unhandled exception at 0x76BBB5B2 in guessTheNumber.exe: Microsoft C++ exception: nlohmann::detail::parse_error at memory location 0x012FE18C.`
And Visual Studio 2022 says the error is on line 6176
![image](https://user-images.githubusercontent.com/92357644/137112684-28fa0a9c-b4af-4de2-a9ec-f9af31514a20.png)

#### Please describe the steps to reproduce the issue.

1. Download, fork or clone [my code](https://github.com/CMDR-JohnAlex/guessTheNumber)
2. Compile and run the project using Visual Studio Community 2019 or 2022 (They both give error)
3. See the error for yourself

#### Can you provide a small but working code example?

My code is hosted on github [here](https://github.com/CMDR-JohnAlex/guessTheNumber)

#### What is the expected behavior?

Uhh, for the code to run and not give an error? I don't really understand the json.hpp code yet

#### And what is the actual behavior instead?

Two errors:
`Exception thrown at 0x76BBB5B2 in guessTheNumber.exe: Microsoft C++ exception: nlohmann::detail::parse_error at memory location 0x012FE18C.`
`Unhandled exception at 0x76BBB5B2 in guessTheNumber.exe: Microsoft C++ exception: nlohmann::detail::parse_error at memory location 0x012FE18C.`

#### Which compiler and operating system are you using?

* Operating System: Windows 10 (Yeah, I wasn't one of the first to get allowed 11)
* Code Editor: Visual Studio 2022 (Bug is also in Visual Studio 2019)

#### Which version of the library did you use?

- [x] latest release version 3.10.3
- [ ] other release - please state the version: ___
- [ ] the `develop` branch

#### If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

- [ ] yes
- [x] no
I don't know how to turn that on in Visual Studio 2022, I don't use cmake to compile my code.

**Comment by gregmarr** [comment]
@nlohmann It's using streams: https://github.com/CMDR-JohnAlex/guessTheNumber/blob/5298eb93df6a126ae5639b38278b619cbf64a997/src/file/file.cpp

**Comment by CMDR-JohnAlex** [comment]
> This means that your program is failing to open the file.

Why would that be happening? I see no bugs in my code where the file wouldn't open...

**Comment by nlohmann** [comment]
There are plenty of exceptions in your screenshot, but the first one indeed points out that either the file you want to parse is empty or could not be opened.

Best would be to run your program in the debugger to see stack traces in case of an uncaught exception.

**Comment by CMDR-JohnAlex** [comment]
> Most likely the file is not where you think it is relative to the working directory. Try using a full path instead of a relative path.

Yeah, the file path was different from what I put but that still didn't fix the problem, and I WAS using Unix path separators! I had no idea that Windows used `\\`, but I am compiling as Win32 so there shoudn't be any problems using Unix path separators. But thanks for that info! Very useful!

Here is the output of the call stack: (Not very useful in my opinion)
![image](https://user-images.githubusercontent.com/92357644/137231398-5130d6f0-212e-432e-b33b-4c97e09e4d2a.png)

Now when I compile my code, it gives this exception: (How did it trigger a breakpoint? I didn't add any breakpoints)
![image](https://user-images.githubusercontent.com/92357644/137234839-fd2bcb48-bdd8-4682-b73d-6b249ec8694b.png)

And this is my console: (Still the same sad errors)
![image](https://user-images.githubusercontent.com/92357644/137235173-76b0e344-9907-46ad-aac4-69d390439b9a.png)

> You can verify that you are opening the proper file by reading from it and then printing to the console.

After I ran `file.open()` in main I put `std::cout << file.highscore;` but that code never ran, so the problem is in the `file.open()` function.

> Note that you can't then use the same stream in the `>>` call, so just do that long enough to resolve your file issue, then return to using `>>` to read the json .

I'm sorry but I don't understand what you mean by this. Also, I just pushed my code to my repository now, so you can see the changes I made.

**Comment by CMDR-JohnAlex** [comment]
I found more info about the error, I made some simple code to test the error location. Here is part of my test code:
```
std::cout << "\nDebug Point 0\n";
std::ifstream FileRead("test\\test.json"); // This is the correct location of json file
std::cout << "\nDebug Point 1\n";
nlohmann::json TheFile;
std::cout << "\nDebug Point 2\n";
FileRead >> TheFile;
std::cout << "\nDebug Point 3\n";
std::cout << TheFile;
std::cout << "\nDebug Point 4\n";
FileRead.close();

std::cout << TheFile; // Read the json file
```
When I run this the terminal displays:
![image](https://user-images.githubusercontent.com/92357644/137255158-6778bcf5-54a3-4bef-b79f-83900647743d.png)

So I decided to put some things in their own try catch, here is the code:
```
std::cout << "\nDebug Point 0\n";
    std::ifstream FileRead("test\\test.json"); // This is the correct location of json file
    std::cout << "\nDebug Point 1\n";
    nlohmann::json TheFile;
    std::cout << "\nDebug Point 2\n";
    try
    {
        FileRead >> TheFile;
    }
    catch (const std::exception& exc)
    {
        std::cout << "Error from \'FileRead >> TheFile;\': ";
        std::cout << exc.what() << '\n';
    }
    std::cout << "\nDebug Point 3\n";
    try
    {
        std::cout << TheFile;
    }
    catch (const std::exception& exc2)
    {
        std::cout << "Error from \'std::cout << TheFile;\': ";
        std::cout << exc2.what() << '\n';
    }
    std::cout << "\nDebug Point 4\n";
    try
    {
        FileRead.close();
    }
    catch (const std::exception& exc3)
    {
        std::cout << "Error from p\'FileRead.close();\': ";
        std::cout << exc3.what() << '\n';
    }
    try
    {
        std::cout << TheFile; // Read the json file
    }
    catch (const std::exception& exc4)
    {
        std::cout << "Error from \'std::cout << TheFile;\': ";
        std::cout << exc4.what() << '\n';
    }
    return 0;
```

And here is the result:
![image](https://user-images.githubusercontent.com/92357644/137256966-8c706270-76b4-4546-8886-616dc5203581.png)

But I KNOW I have the right file location: 
![image](https://user-images.githubusercontent.com/92357644/137257458-487482d0-ae2c-42c1-a3c2-049c17e21f46.png) ![image](https://user-images.githubusercontent.com/92357644/137257533-56c9f046-8894-47a1-bf00-a60a9e1ae66d.png)

**Comment by nlohmann** [comment]
```cpp
std::ifstream FileRead("test\\test.json");
```

This is a relative path to file `test.json`. You must make sure that this path is valid from the location where you start your binary. It seems your IDE  starts the binary `guessTheNumber.exe` from the `Debug` directory. Hence, you need to make sure file `Debug\test\test.json` exists.
