### ISSUE TITLE
Limit AppVeyor use

### ISSUE THREAD

**Issue by nlohmann** [nlohmann/json#3089]
Check if all jobs in AppVeyor are needed. AppVeyor is much slower as GitHub Actions.

- [ ] Remove jobs that can also be executed in GitHub Actions.
- [ ] Adjust README file.

**Comment by falbrechtskirchinger** [comment]
Differences I'm noticing:
* Tests Visual Studio versions not available in GitHub runners. (2015 and 2017[1])
* Injects `#include <windows.h>` into `json.hpp`.
* Possibly minor differences in `CXXFLAGS`, e.g.
    `/Zc:__cplusplus` Enable the __cplusplus macro to report the supported standard (off by default).

[1] Visual Studio 2017 support ends March 15th: https://github.com/actions/virtual-environments/issues/4312

**Comment by nlohmann** [comment]
I did not know that GitHub would drop Visual Studio 2017 support - thanks for letting me know. If there are no hosted images - is anyone aware of Docker images to use instead?

**Comment by nlohmann** [comment]
Done.
