### ISSUE TITLE
Apple build failed with json/single_include/nlohmann/json.hpp:4384:57: 'path' is unavailable

### ISSUE THREAD

**Issue by tongyuze** [nlohmann/json#3097]
#### What is the issue you have?

I just updated the json.hpp from version 3.9.1 to 3.10.4. And the newest version failed the Mac/iOS build with the error:
"json/single_include/nlohmann/json.hpp:4384:57: 'path' is unavailable"
This happened during compilation.

#### What is the expected behavior?

Build should succeed.

#### And what is the actual behavior instead?

Build failed with the above error.

#### Which compiler and operating system are you using?

- Compiler: com.apple.compilers.llvm.clang.1_0.compiler
- Operating system: macOS 11.6 

#### Which version of the library did you use?

- [x] latest release version 3.10.4

**Comment by tongyuze** [comment]
> > > I have the same problem. My macOS deployment target is 10.12 so std::filesystem is unavailable. So we need something like this for filesystem on mac: `#if (MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_15) && defined(JSON_HAS_CPP_17)` instead of simply `#ifdef JSON_HAS_CPP_17`
> > 
> > 
> > And also the iOS version should be >= 13.0.
> 
> Thanks for the input! I will see to add the preprocessor macros. What would be the macro to test the iOS version?

For the ios, it should be `#if __IPHONE_OS_VERSION_MIN_REQUIRED >= 130000`
For mac, it should be `if __MAC_OS_X_VERSION_MIN_REQUIRED >= 101500`

**Comment by nlohmann** [comment]
Fixed with #3090.
