### ISSUE TITLE
[feature request]: schema validator and comments

### ISSUE THREAD

**Issue by rianquinn** [nlohmann/json#311]
Are there any plans to include a schema validator as well as comment support? Our project www.bareflank.org is about to add JSON support, and we are debating this code vs RapidJSON. We like the simplicity of this code, as well as the modern use of C++11/14, but we also like the Schema support and comment support with RapidJSON. 

Some more info on the roadmap would be really helpful with respect to make our decision. Thanks a ton, and great job on this library.

**Comment by gregmarr** [comment]
The JSON standard does not include comments.

See also:
https://github.com/nlohmann/json/issues/192
https://github.com/nlohmann/json/issues/294
https://github.com/nlohmann/json/issues/305

There is also a library that just does validation and supports this parser:
https://github.com/tristanpenman/valijson

**Comment by rianquinn** [comment]
Thanks
