### ISSUE TITLE
Wrong parsing of int64 values nearest of limit

### ISSUE THREAD

**Issue by gysevvlad** [nlohmann/json#3126]
#### What is the issue you have?
For number "9223372036854775808" (`int64_t::max()` + 1) I expects that `json.get<nlohmann::json::number_integer_t>()` throws exception.

#### Can you provide a small but working code example?
https://godbolt.org/z/v4ejoPszf
```C++
#include "nlohmann/json.hpp"
#include <iostream>

int main(int, char **) {
  auto json = nlohmann::json::parse(R"({ "package size": 9223372036854775808 })");
  auto [key, number] = *json.items().begin();
  std::cout << number.get<nlohmann::json::number_integer_t>() << std::endl;
  return 0;
}
```
#### What is the expected behavior?
I expects to get exception.

#### And what is the actual behavior instead?
```
Program stdout
-9223372036854775808
```

#### Which compiler and operating system are you using?

- Compiler: clang-12
- Operating system:  Ubuntu, RedHat

#### Which version of the library did you use?

- [X] latest release version 3.10.4
- [ ] other release - please state the version: ___
- [ ] the `develop` branch

**Comment by gysevvlad** [comment]
Also it's relevant for `is_number_integer` check:
```C++
#include "nlohmann/json.hpp"
#include <iostream>

int main(int, char **) {
  auto json = nlohmann::json::parse(R"({ "package size": 9223372036854775808 })");
  auto [key, number] = *json.items().begin();
  if (number.is_number_integer()) {
    std::cout << number.get<nlohmann::json::number_integer_t>() << std::endl;
  }
  return 0;
}
```
```
bash :> ./build/default/main
-9223372036854775808
```

**Comment by nlohmann** [comment]
The library differentiates between signed and unsigned integers (see https://json.nlohmann.me/features/types/number_handling/). `is_number_integer()` returns true for either integer type (see https://json.nlohmann.me/api/basic_json/is_number_integer/).

So with `get<nlohmann::json::number_integer_t>() ` you actually cast an `std::uint64_t` to a `std::int64_t`.

```cpp
#include <nlohmann/json.hpp>

int main() {
    const auto j = nlohmann::json::parse("9223372036854775808");
    assert(j.is_number_unsigned());
    std::uint64_t n = j;
    assert(n == 9223372036854775808U);
}
```
