### ISSUE TITLE
Bad JSON diff when removing object in array of object

### ISSUE THREAD

**Issue by LouisNoailles** [nlohmann/json#3146]
#### What is the issue you have?

In [this test](https://github.com/nlohmann/json/blob/develop/test/src/unit-json_patch.cpp#L181) A simple remove is expected as a diff. But the following exemple is not following the expected behavior:
Old JSON:
```json
{
    "a": ["aa", "ab"]
}
```

New JSON:
```json
{
    "a": ["ab"]
}
```
The JSON Patch:
```json
[
    {
        "op": "remove",
        "path": "/a/1"
    },
    {
        "op": "replace",
        "path": "/a/0",
        "value": "ab"
    }
]
```

#### Please describe the steps to reproduce the issue.

1. Create a JSON array containing multiple objects
2. Remove an object but not the last one

#### What is the expected behavior?

The patch should be as following:
```json
[
    {
        "op": "remove",
        "path": "/a/0"
    }
]
```

#### And what is the actual behavior instead?

The JSON Patch is currently as follow:
```json
[
    {
        "op": "remove",
        "path": "/a/1"
    },
    {
        "op": "replace",
        "path": "/a/0",
        "value": "ab"
    }
]
```

#### Which version of the library did you use?

Version: 3.9.1

**Comment by nlohmann** [comment]
I can confirm that the calculated patch is not the shortest one. However, it is correct, thus I removed the "bug" label. The currently implemented `diff` algorithm is not optimal. PRs welcome.

**Comment by yunxuo** [comment]
I have the same trouble. for multi-level json example：
They're just in a different order.
base json:
```json
{
  "cost":[
    {"count":0,"ccc":16.0},
    {"count":2,"ccc":13.0}
  ]
}
```

target json:
```json
{
  "cost":[
    {"count":2,"ccc":13.0},
    {"count":0,"ccc":16.0}
  ]
}
```
patch result:
```json
[
  {
    "op": "replace",
    "path": "/status/cost/0/ccc",
    "value": 16.0
  },
  {
    "op": "replace",
    "path": "/status/cost/0/count",
    "value": 0
  },
  {
    "op": "replace",
    "path": "/status/cost/1/ccc",
    "value": 13.0
  },
  {
    "op": "replace",
    "path": "/status/cost/1/count",
    "value": 2
  }
]
```
Is it possible to provide a good diff algorithm that considers these two jsons to be the same？
Looking forward to your reply！^_^
