### ISSUE TITLE
json::dump() is not compatible with C++ standards

### ISSUE THREAD

**Issue by andres-alban** [nlohmann/json#3147]
#### What is the issue you have?

I like to disable language extensions in my projects to ensure I am writing code compliant with the standards. All the basic functionality I have tested, except for `json::dump()`, is compliant with C++ standards according to my compiler. If I want to use json::dump(), I need to enable language extensions.

#### Please describe the steps to reproduce the issue.

Compile any program that calls `json::dump()` using the disable language extensions flag (/Za). Printing to streams produces the same error.

#### Can you provide a small but working code example?

```
#include <iostream>
#include <nlohmann/json.hpp>
using json = nlohmann::json;
int main()
{
    json j;
    j["name"] = "Bob";
    std::cout << j.dump();
}
```
#### What is the expected behavior?

print {"name":"Bob"}

#### And what is the actual behavior instead?

I get two compile errors
1. Error C2672	'nlohmann::detail::binary_writer<BasicJsonType,char>::to_char_type': no matching overloaded function found
2. Error C2783	'CharType nlohmann::detail::binary_writer<BasicJsonType,CharType>::to_char_type(uint8_t) noexcept': could not deduce template argument for '__formal'

My compiler points the errors to serializer.hpp lines 535-537:
```
string_buffer[bytes++] = detail::binary_writer<BasicJsonType, char>::to_char_type('\xEF');
string_buffer[bytes++] = detail::binary_writer<BasicJsonType, char>::to_char_type('\xBF');
string_buffer[bytes++] = detail::binary_writer<BasicJsonType, char>::to_char_type('\xBD');
```

#### Which compiler and operating system are you using?

- Compiler: Visual Studio 17
- Operating system: Windows 10 64-bit (I get the error compiling in both x64 and x86 architectures)

#### Which version of the library did you use?

- [ ] latest release version 3.10.4
- [x] other release - please state the version: 3.9.1 (installed using vcpkg)
- [ ] the `develop` branch

**Comment by gregmarr** [comment]
@nlohmann is correct, the proper way to do this in Visual Studio 17 and later is to use `/permissive-`.
https://devblogs.microsoft.com/cppblog/permissive-switch/

**Comment by andres-alban** [comment]
Thanks for the quick reply. I was under the impression that the /Za flag was the safest way to write portable code but I guess that I did not do my research properly and my sources were outdated. I will start relying on the /permissive- flag as @gregmarr suggests. Feel free to close the issue since I assume that you have not found any compatibility issues with the library.

**Comment by nlohmann** [comment]
We already use `/permissive-` in our CI, so this should be fine.

@gregmarr Thanks for clarifying!

**Comment by gregmarr** [comment]
You're welcome.
