### ISSUE TITLE
releasing single header file in compressed format

### ISSUE THREAD

**Issue by agauniyal** [nlohmann/json#316]
This is more of a feature request since a few c++ build systems enforce downloading of zip/tar.gz archives instead of direct files, would you mind releasing an archive for just `json.hpp` file in future releases. Currently, I've to clone whole repo which doesn't seems nice way to do things on a limited bandwidth network 😄

**Comment by agauniyal** [comment]
Btw I've added your package to wrapdb - https://wrapdb.mesonbuild.com/json which is based on meson build system.

**Comment by kainjow** [comment]
You could try cloning with a depth of 1, which won't grab the entire repository history:

    git clone --depth 1 https://github.com/nlohmann/json.git

**Comment by agauniyal** [comment]
Unfortunately I don't have control over it, I can only specify the archive url. Another reason is that some packages might do `git checkout v2.3` or such which should require that history I guess.

**Comment by nlohmann** [comment]
About which build system are we talking? Adding another file to a release is some (manual) work on my side - I would like to understand whether this is worth the effort.

**Comment by agauniyal** [comment]
@nlohmann I've linked it above but here it is - https://github.com/mesonbuild/meson/

**Comment by agauniyal** [comment]
You can also automate github releases as per as your requirements 😄 . And you're already attaching `json.hpp`, I'm just asking for a `tar.gz` version for it, if I wasn't clear. That should be 1 more command at most.

**Comment by nlohmann** [comment]
This seems to be a limitation of the meson build system not to be able to download a .hpp file, but only archives.

**Comment by agauniyal** [comment]
Yes I've also raised a issue here - https://github.com/mesonbuild/meson/issues/744, but the developers seem to be quite busy atm and I thought I could ask for some support here. If it's too complicated, I won't mind downloading whole sources as I'm doing currently, but it would be a lot helpful on limited bandwidth network for some of use.

**Comment by nlohmann** [comment]
I understand, but if the issue affects more than one project, it makes a lot of sense to fix this in the build system rather than each individual project. Though downloading whole archives is quite ugly, it is also the same as Homebrew is doing (see https://github.com/nlohmann/homebrew-json). I would like to close this issue, because I think mesonbuild/meson#744 should fix this.

**Comment by agauniyal** [comment]
I understand 👍
