### ISSUE TITLE
serialization problem, from_json need construct new object

### ISSUE THREAD

**Issue by jiapengwen** [nlohmann/json#3169]
### Discussed in https://github.com/nlohmann/json/discussions/3168

<div type='discussions-op-text'>

<sup>Originally posted by **jiapengwen** November 30, 2021</sup>
show you my code,:
```c++
using json = nlohmann::json;

namespace ns {
    void to_json(json& j, const person& p) {
    }
  // here will create new object, but i just want to init my object(outside create) whit json value
    void from_json(const json& j, person& p) {
    }
} // namespace ns


// in othre file
person my_person;
//here init my_person with json (j) value
from_json(j, my_person);
```
thank you your help</div>

**Comment by jiapengwen** [comment]
I think you are misunderstood my question,  i just want deserialization json to my already create object, but from_fson will create new object, this isn't my purpose

**Comment by nlohmann** [comment]
Please discuss this in #3168

**Comment by jiapengwen** [comment]
ok, thanks
