### ISSUE TITLE
json_unit runs forever when executed in build directory

### ISSUE THREAD

**Issue by tboede** [nlohmann/json#319]
It seems to me like a bug that json_unit runs forever when I build the project in a separate build directory with

```text
cmake ../json
make
```
and then try to execute

```text
./test/json_unit
```
in the build directory. 
I would expected it to run the tests and print a result when done which it indeed does if it was build and executed in the source directory.

When I sent an interrupt signal to the running program it terminates with following output:

```test
json_unit is a Catch v1.5.6 host application.
Run with -? for options

-------------------------------------------------------------------------------
constructors
  create a JSON value from an input stream
  std::ifstream
-------------------------------------------------------------------------------
/home/tim/Projekte/github/json/test/src/unit-constructor1.cpp:42
...............................................................................

/home/tim/Projekte/github/json/test/src/unit-constructor1.cpp:1305: FAILED:
due to a fatal error condition:
  SIGINT - Terminal interrupt signal

===============================================================================
test cases:   11 |   10 passed | 1 failed
assertions: 3938 | 3937 passed | 1 failed
```

A look at line 1305 in unit-constructor1.cpp
```c++
        SECTION("std::ifstream")
        {
            std::ifstream f("test/data/json_tests/pass1.json");
            json j(f);
        }
```
shows that the input stream test wants to load a file from a subdirectory which doesn't exists in the build directory.

To fix this I added following to 'test/CMakeLists.txt' in the source directory :
```cmake
string(COMPARE NOTEQUAL "${CMAKE_CURRENT_SOURCE_DIR}" "${CMAKE_CURRENT_BINARY_DIR}" JSON_HAS_SEPARATE_BUILDDIR)

if(${JSON_HAS_SEPARATE_BUILDDIR})

file(COPY "${CMAKE_CURRENT_SOURCE_DIR}/data" DESTINATION "${CMAKE_CURRENT_BINARY_DIR}")

endif()
```
Now test/data will be copied from the source directory to the build directory when they are not the same.

After rebuilding json_unit finally prints:

```text
===============================================================================
All tests passed (8644 assertions in 33 test cases)
```

**Comment by nlohmann** [comment]
I can confirm your observation, but the tests can be executed successfully with `ctest`:

```sh
mkdir build
cd build
cmake ..
make
ctest
```

which executes with

```
Test project /Users/niels/Documents/Repositories/json/build
    Start 1: json_unit_default
1/2 Test #1: json_unit_default ................   Passed    8.10 sec
    Start 2: json_unit_all
2/2 Test #2: json_unit_all ....................   Passed  136.44 sec

100% tests passed, 0 tests failed out of 2

Total Test time (real) = 144.54 sec
```

I don't think PR #320 is necessary. What do you think @tboede?

**Comment by tboede** [comment]
Yes with ctest it works because it reads the files from the source directory. 
Then it's my fault i thought the tests should be run by execute them manually.

**Comment by nlohmann** [comment]
Currently, Cmake is not mentioned in the README file, but is only called by AppVeyor. Do you think extending the REAMDE makes sense to describe the proper Cmake way?

**Comment by tboede** [comment]
Maybe "make check" in the Test section should be replaced with "ctest", it seems that there is no "check" rule in the Makefile anymore.

**Comment by tboede** [comment]
Yeah, i see the rule is in the prebuilt Makefile in the source directory which was of course not available when I tried to run `make check` in the separate build directory.

**Comment by tboede** [comment]
I think this issue can be closed now.

**Comment by nlohmann** [comment]
Thanks for reporting!
