### ISSUE TITLE
Tests failing when compiling with c++20

### ISSUE THREAD

**Issue by vakokako** [nlohmann/json#3207]
When built with c++20, on some platforms test `unit-comparison.cpp:213` fails.

The comparison of c++17 vs c++20 behavior can be seen here: [godbolt](https://godbolt.org/z/jodGv5vGM).

**Comment by nlohmann** [comment]
Thanks for reporting! We're running the tests on macOS (Xcode 12.4) and Ubuntu (Clang 14.0.0 and GCC 11.1.0) without problems. On Godbolt, the behavior only differs in GCC 11.2. I'll check to get that compiler.

**Comment by NeroBurner** [comment]
I've tried to run the tests with g++11.2.0 and clang 13.0.0 in C++20 mode. g++ fails as described, but clang works

I suspect it to be the default comparisons by the new spaceship operator

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2085r0.html

The mentioned paper isn't implemented in Clang 13 yet (but should be in Clang 14 :thinking: ). It's the last mentioned paper in the table when searching for `Consistent comparison (operator<=>)`

https://clang.llvm.org/cxx_status.html#cxx20

![Consistent comparison Clang implementation status](https://user-images.githubusercontent.com/9076163/152320694-1067db79-6ba6-472b-8983-c91f9547e574.png)

**Comment by nlohmann** [comment]
@falbrechtskirchinger What is needed beyond #3379 to fix this?

**Comment by falbrechtskirchinger** [comment]
Yes.

You can see for yourself by switching out the header here https://godbolt.org/z/jodGv5vGM
with the header from #3446:
`#include <https://raw.githubusercontent.com/falbrechtskirchinger/json/fix-c++20-issues-part2/single_include/nlohmann/json.hpp>`
