### ISSUE TITLE
Add nested object capability to pointers

### ISSUE THREAD

**Issue by clwill** [nlohmann/json#323]
You currently can create a new object with
```cpp
j["this"]["that"] = 27;
```
and if `this` and/or `that` don't exist, it's all good, it creates `this` as an object and puts `that` in it.

But if you use pointers (e.g. `"/this/that"`) it throws an exception if `this` doesn't exist.

For example:
```cpp
j.at("/this/that"_json_pointer) = 27;
```
would be nice.

**Comment by nlohmann** [comment]
I can confirm your observation - however, `at` is supposed to throw when applied to a nonexisting key.

Using `j["/this/that"_json_pointer] = 27;` still throws - this is a bug. What currently works is `	j["/this"_json_pointer] = 27;`. That is, the `operator[]` for JSON Pointers shall be extended to work with arbitrary nested pointers even if parts are not existing yet.

**Comment by clwill** [comment]
Of course, doh!

Thanks, I'm dealing with a complex structure and the ability to not have to parse/check the existence of each level is quite helpful.

**Comment by clwill** [comment]
Also, don't know if you saw my comment on #278, but there is a parallel issue with `value`. I think that

```
j.value("/this/that"_json_pointer, 27);
```
should return 27 if either `this` or `that` are not present, not throw on a missing `this`.

Thx.

**Comment by gregmarr** [comment]
Presumably it's "/this/that"_json_pointer that's throwing, not .value() itself.

**Comment by nlohmann** [comment]
Thanks for noting. The reason is that both functions use the same function inside the `json_pointer` class.

**Comment by clwill** [comment]
Got it. Didn't dive inside, it was late :)

**Comment by nlohmann** [comment]
The bug was that there was no code to cope when a JSON pointer was used on a `null` value. I'm on it.

**Comment by nlohmann** [comment]
I fixed the issue with `operator[](const json_pointer&)` and now shall have a look at your comment regarding `value(const json_pointer&, ValueType)`.

**Comment by nlohmann** [comment]
Let's discuss the semantics of `value` with JSON pointers in #323.

@clwill - Can you please have a look at branch https://github.com/nlohmann/json/tree/feature/issue323 if this fixes the issue?

**Comment by clwill** [comment]
I've done some playing with the branch above, and it seems to work as expected. I like it!

**Comment by clwill** [comment]
BTW, just so you can understand my use case... I have a generic configuration module that puts all the other modules' defaults into one master .json file. The value setting function used to be:
```
template<typename T>
void setValue(const std::string keyName, T val) {
	jsonMaster[moduleName][keyName] = val;
}
```
Which worked and was OK. But with this update, I can do:
```
	jsonMaster[json::json_pointer("/" + moduleName + "/" + keyName)] = val;
```
The modules setting a value can now not only pass in a `keyName` of, say `"this"` but they can also make their own nested values of, say `"this/that"`. This is very helpful.

Thank you.

**Comment by nlohmann** [comment]
Great. I shall merge the branch by the end of the week. However, I have no release date for 2.0.6 yet.

**Comment by clwill** [comment]
Thanks! Timing's OK, I can live with the `[this][that]` approach for the time being.

**Comment by nlohmann** [comment]
Merged the feature branch to develop.
