### ISSUE TITLE
Add a function that checks for valid json in a C++ string 

### ISSUE THREAD

**Issue by beemibrahim** [nlohmann/json#3245]
I want you to add a feature , that checks C++ strings for valid JSON . So that I don't get errors .

**Comment by nlohmann** [comment]
This exists: https://json.nlohmann.me/api/basic_json/accept/

**Comment by beemibrahim** [comment]
i didnt see any C++ strings

**Comment by nlohmann** [comment]
The example shows how it can be used: https://json.nlohmann.me/api/basic_json/accept/#examples

**Comment by beemibrahim** [comment]
In The Example What is The Type of the invalid text , also can I put a string in that auto variable

**Comment by nlohmann** [comment]
Yes, a `std::string` is also a valid `InputType`.

**Comment by beemibrahim** [comment]
alright thanks

**Comment by nlohmann** [comment]
I will overwork the documentation and make it explicit that `std::string`s are allowed.

**Comment by nlohmann** [comment]
@beemibrahim Would have been https://github.com/nlohmann/json/pull/3246/files easier to understand?

**Comment by beemibrahim** [comment]
yes
