### ISSUE TITLE
Unexpected implicit conversion

### ISSUE THREAD

**Issue by ppeiwang** [nlohmann/json#3254]
```C++
json j;
j["number"]          = 0.1;
const json& ref = j["number"];
double a = ref + 0.1; //  a = 0.1
```
I was thinking, this is an unexpected issue for these people who invoke the implicit conversion of a json object.

Actually, I stepped into the callstack and found that the json object, ref, had been converted to an integer type. 

I was just hoping,  the ref was a "double" in the statement.

**Comment by nlohmann** [comment]
I cannot reproduce the issue (using Apple Clang 13.0) due to a compilation error:

```
 error: use of overloaded operator '+' is ambiguous (with operand types 'const json' (aka 'const basic_json<>') and 'double')
        double a = ref + 0.1; //  a = 0.1
                   ~~~ ^ ~~~
```

Which compiler are you using?

**Comment by ppeiwang** [comment]
thanks for replying. 
I compiled this on Visual Studio 2019 (v142), and the C++ Standard is "ISO C++17 Standard (/std:c++17)"

**Comment by gregmarr** [comment]
I can repro, succeeds on MSVC, fails on GCC and Clang.  This looks like an excellent reason to use the disable implicit conversions option.

**Comment by nlohmann** [comment]
Indeed setting `JSON_USE_IMPLICIT_CONVERSIONS`  to 0 (see https://json.nlohmann.me/features/macros/#json_use_implicit_conversions) is the best way here. But technically - isn't this behavior also a bit buggy from compiler side? The return type and the type of the second operand is `double` - why should MSVC select a conversion to `int` here?

**Comment by gregmarr** [comment]
This compiles fine under MSVC in compiler explorer, so I'm not sure what's actually being reported here.

    nlohmann::json j;
    j["number"]          = 0.1;
    const auto & ref = j["number"];
    auto a = ref + 0.1; //  a = 0.1
    double *pa = &a;

**Comment by nlohmann** [comment]
Shouldn't `a` be `0.2`?

**Comment by gregmarr** [comment]
Probably, I just copied the code as provided and didn't notice that the comments were inaccurate.

**Comment by ppeiwang** [comment]
> Shouldn't `a` be `0.2`?

'a' should have been 0.2. It looks like a bug from MSVC.
