### ISSUE TITLE
Segmentation fault on saving json to file

### ISSUE THREAD

**Issue by j-o-d-o** [nlohmann/json#326]
I get a segmentation fault when saving a json data object to a file like this:

```cpp
#include <iostream>
#include <fstream>
#include "json.hpp"

bool SaveToFile(nlohmann::json data) {
	std::ofstream jsonFile;
		
	jsonFile.open("testFile.json" , std::ofstream::out | std::ofstream::trunc);
	jsonFile << data;
	jsonFile.close();
	
	return true;
}

int main() {
	std::cout << "========== Start Application ===========" << std::endl;
	
	return 0;
}
```

The problem is, I cant even debug anything. Because even if I don't use the function I get the segmentation fault. 
When changing: `jsonFile << data;` to `jsonFile << "Test String";`, I dont get any errors.

I am using Visual GDB with gcc 4.9.2 (from here: http://gnutoolchains.com/raspberry/).

Please ask if any other information or clarification is needed!

**Comment by ChristophJud** [comment]
I cannot reproduce it on a normal Ubuntu with a gcc 4.9.2. Must be something raspberrypi-specific. Can't you simply debug with the standard gdb and look at the backtrace after the program crashes?

**Comment by nlohmann** [comment]
Maybe @navybk can reproduce this on a Raspberry.

**Comment by j-o-d-o** [comment]
Actually, It works on a raspberry. I just tried. There error occures on a odroid xu4.

**Comment by nlohmann** [comment]
Ok. Thanks!

**Comment by j-o-d-o** [comment]
I guess this can be closed as I susspect even thou the error occures when using anything json related, it is not the real root of it.

**Comment by nlohmann** [comment]
Thanks for reporting anyway. If you can find anything more, I would be happy to have a look!

**Comment by j-o-d-o** [comment]
Just in case of the very unlikely event that someone would run into the same problem in the future. 
The error was because of Visual GDB (what exactly... I don't know). However what fixed the whole issue was upgrading from Ubuntu 15.10 to 16.04.
