### ISSUE TITLE
json.hpp 'isfinite' is not a member of 'std' also isinf; snprintf; stoull and to_string members of std

### ISSUE THREAD

**Issue by Zombieanfuehrer** [nlohmann/json#3263]
Hello,

on compile  nlohmann/json 3.10.5 qnx 6.6 with GNU 4.8.3 -std=c++11. 

got this messages:

Description	Resource	Path	Location	Type
'isfinite' is not a member of 'std'	parser.hpp	../external/json/include/nlohmann/detail/input	line 261	C/C++ Problem
Description	Resource	Path	Location	Type
'isinf' is not a member of 'std'	binary_writer.hpp	../external/json/include/nlohmann/detail/output	line 199	C/C++ 
Problem
Description	Resource	Path	Location	Type
'signbit' is not a member of 'std'	to_chars.hpp	../external/json/include/nlohmann/detail/conversions	line 1063	C/C++ 
Problem
Description	Resource	Path	Location	Type
'snprintf' is not a member of 'std'	binary_reader.hpp	../external/json/include/nlohmann/detail/input	line 322	C/C++ 
Problem
Description	Resource	Path	Location	Type
'std::to_string' has not been declared	iteration_proxy.hpp	../external/json/include/nlohmann/detail/iterators	line 20	C/
C++ Problem
Description	Resource	Path	Location	Type
'stoull' is not a member of 'std'	json_pointer.hpp	../external/json/include/nlohmann/detail	line 191	C/C++ Problem

**Comment by nlohmann** [comment]
This sounds like a broken STL - all standard headers for the mentioned functions are included. Can you please double check if you can compile a program like:

```cpp
#include <string>

int main()
{
    std::string i = std::to_string(12);
}
```

or

```cpp
#include <cmath>

int main()
{
    bool f = std::isfinite(100.0);
}
```

**Comment by Zombieanfuehrer** [comment]
> This sounds like a broken STL - all standard headers for the mentioned functions are included. Can you please double check if you can compile a program like:
> 
> ```c++
> #include <string>
> 
> int main()
> {
>     std::string i = std::to_string(12);
> }
> ```
> 
> or
> 
> ```c++
> #include <cmath>
> 
> int main()
> {
>     bool f = std::isfinite(100.0);
> }
> ```

Ok sorry, i updated the GNU Compiler under qnx 6.6 SDK to 4.8.3 from 4.7.3 to use your lib. 
Apparently I have scraped something, will try again.
