### ISSUE TITLE
try to assign dumped string to a class member varible

### ISSUE THREAD

**Issue by DamonsJ** [nlohmann/json#3300]
here is my code :

```cpp
class A {
public:
void func()
{
nlohmann::json j;
j["a"] = 2.0;

str = j.dump();
}
std::vector<std::string> str;
};
```

this code give me a crash 

why?

**Comment by nlohmann** [comment]
The return value of `j.dump()` is a `std::string`. You try to assign it to a `std::vector<std::string>`. What do you expect here?
