### ISSUE TITLE
Installing with Homebrew on Mac Errors (El Capitan)

### ISSUE THREAD

**Issue by jsuit** [nlohmann/json#331]
I install with homebrew as readme said. But when I insert #include "json.hpp" into the top of my file, I get a long list of errors when I try to compile:

In file included from twitterClient.cpp:2:
/usr/local/include/json.hpp:118:12: error: unknown type name 'constexpr'
    static constexpr bool value = sizeof(test<T>(0)) == 1;

/usr/local/include/json.hpp:118:22: error: expected member name or ';' after
      declaration specifiers
    static constexpr bool value = sizeof(test<T>(0)) == 1;

/usr/local/include/json.hpp:391:21: error: a space is required between
      consecutive right angle brackets (use '> >')
          basic_json>>>;
                    ^
/usr/local/include/json.hpp:437:67: error: a space is required between
      consecutive right angle brackets (use '> >')
    using array_t = ArrayType<basic_json, AllocatorType<basic_json>>;
                                                                  ^
/usr/local/include/json.hpp:752:16: error: ISO C++ forbids forward references to
      'enum' types
    enum class value_t : uint8_t
               ^
/usr/local/include/json.hpp:753:5: error: expected '(' for function-style cast
      or type construction
    {
    ^
/usr/local/include/json.hpp:831:32: error: expected ';' at end of declaration
      list
        json_value(boolean_t v) noexcept : boolean(v) {}
                               ^
/usr/local/include/json.hpp:942:16: error: ISO C++ forbids forward references to
      'enum' types
    enum class parse_event_t : uint8_t
               ^
/usr/local/include/json.hpp:943:5: error: expected '(' for function-style cast
      or type construction
    {
    ^
/usr/local/include/json.hpp:1087:41: error: expected ';' at end of declaration
      list
    basic_json(std::nullptr_t = nullptr) noexcept
                                        ^
/usr/local/include/json.hpp:2986:38: error: too many arguments provided to
      function-like macro invocation
            or std::is_same<array_t, pointee_t>::value
                                     ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:596:9: note: 
      macro 'static_assert' defined here
#define static_assert(__b, __m) \

....

What is giving me these errors

**Comment by gregmarr** [comment]
Your compiler doesn't have C++11 support enabled.

**Comment by nlohmann** [comment]
You need to add `-std=c++11` to your compiler flags (CXXFLAGS).

**Comment by nlohmann** [comment]
@jsuit Can we close this issue?
