### ISSUE TITLE
小米 MIX4 MIUI13  bug

### ISSUE THREAD

**Issue by q1013348239** [nlohmann/json#3316]
The screenshot of the interception in this mobile phone C is garbled as follows. My miui12 interception is normal. Can I reply to it?
![image](https://user-images.githubusercontent.com/55979795/152297289-f3c449ab-6bdd-420f-a942-f77cb738d19b.png)

**Comment by nlohmann** [comment]
The exception message states the issue: you have an unescaped null byte in your input. This is invalid JSON - null bytes must be escaped to `\u0000`. The exception also states the position of the null byte its after `59884`.

This is not a bug in the library.

**Comment by q1013348239** [comment]
> 异常消息说明了问题：您的输入中有一个未转义的空字节。这是无效的 JSON - 必须将空字节转义为`\u0000`. 该异常还说明了空字节在其之后的位置`59884`。
> 
> 这不是库中的错误。

using json = nlohmann::ordered_json;
char json_msg[4096] = "";
json result = json::parse(user_data);
sprintf(json_msg, "%s", result["msg"].get < std::string > ().c_str());

int json_code_int = result["code"].get < int >();
printf("code：%s,%d\n", json_msg, json_code_int);

This is my code, how to solve the problem you mentioned? I want to get code and msg! thanks

**Comment by nlohmann** [comment]
I assume line

```cpp
json result = json::parse(user_data);
```

throws the exception, right?

**Comment by q1013348239** [comment]
using json = nlohmann::ordered_json;
	char json_msg[4096] = "";
	char mem[4096] = "";
	int json_code_int;
	int json_time_int;
	 try
	{

		json result = json::parse(user_data);
		sprintf(json_msg, "%s", result["msg"].get < std::string > ().c_str());
   	 json_code_int = result["code"].get < int >();
	    json_time_int = result["time"].get < int >();
	    printf("msg：%s\ncode：%d\ntime：%d\n\n", json_msg, json_code_int,json_time_int);

	} catch(json::exception & e)
	{

		sprintf(mem, "%s", e);
		printf("mistake：%s\n\n", mem);

	}


This is my code.


There is no problem with Xiaomi 9 input！

![NPA%@3AYHSM_S33YN9E5REG](https://user-images.githubusercontent.com/55979795/152483155-30a8ad32-cbb8-4142-b5c0-bea401750d46.jpg)


Xiaomi 4mix miui13 output is like this.

![image](https://user-images.githubusercontent.com/55979795/152483206-23f71019-b92c-4f57-8071-30b840f6d43c.png)

**Comment by q1013348239** [comment]
> I assume line
> 
> ```c++
> json result = json::parse(user_data);
> ```
> 
> throws the exception, right?

Look at my new reply above and see what the problem is. Thank you.

**Comment by nlohmann** [comment]
If you enter the `catch` branch, can you please output the content of `e.what()` to check which exception occurred?

**Comment by q1013348239** [comment]
> If you enter the `catch` branch, can you please output the content of `e.what()` to check which exception occurred?


using json = nlohmann::ordered_json;
char json_msg[4096] = "";
char mem[4096] = "";
int json_code_int;
int json_time_int;
 try
{

	json result = json::parse(user_data);
	sprintf(json_msg, "%s", result["msg"].get < std::string > ().c_str());
 json_code_int = result["code"].get < int >();
    json_time_int = result["time"].get < int >();
    printf("msg：%s\ncode：%d\ntime：%d\n\n", json_msg, json_code_int,json_time_int);

} catch(json::exception & e)
{

	sprintf(mem, "%s", e);
	printf("mistake：%s\n\n", mem);

}


This is the e I printed, and the error output is empty. Look at my circle. Is there something wrong with my printing error code?

![Uploading 23e95b62a5eda287.jpg…]()

**Comment by nlohmann** [comment]
Please use

```cpp
std::cout << "exception: " << e.what() << std::endl;
```

**Comment by q1013348239** [comment]
> Please use
> 
> ```c++
> std::cout << "exception: " << e.what() << std::endl;
> ```
Is it because the code length is too long? How to solve this mistake?

![`~Q{QIJ1 6C`)3FF$4B IJ6](https://user-images.githubusercontent.com/55979795/152505409-62c6a7ea-6a7e-44db-a035-13dc4c4593e2.png)

**Comment by q1013348239** [comment]
> Please use
> 
> ```c++
> std::cout << "exception: " << e.what() << std::endl;
> ```

Is it because the msg length is too long? How to solve this mistake?

![image](https://user-images.githubusercontent.com/55979795/152505533-b3c5c0b2-f610-4d34-bc84-760a54bd19f0.png)

**Comment by nlohmann** [comment]
The error is the same. There is an unescaped null byte in your input, and the parser rightfully complains that this is invalid JSON. What type does `user_data` have?

**Comment by q1013348239** [comment]
> The error is the same. There is an unescaped null byte in your input, and the parser rightfully complains that this is invalid JSON. What type does `user_data` have?

const char *user_data = User_login(secret_key, app, appkey, Urlry, kmm, kmm_m, jqm);
printf("\nuser_data：%s\n\n", user_data);

This is the code of my user_data. I have no problem with my phone, my friend's phone has a problem, so I don't know what to do

**Comment by nlohmann** [comment]
Please double check that there is a null byte in the input of the parser. Can you print the output of `std::strlen(user_data)`?

**Comment by q1013348239** [comment]
> 
The above print is user_data, len is 765, you just asked me to print it, the json content must be there, but I don't know why the parsing error

![image](https://user-images.githubusercontent.com/55979795/152510065-94420ccd-a365-41dc-9916-9305d1033556.png)

**Comment by q1013348239** [comment]
> Please double check that there is a null byte in the input of the parser. Can you print the output of `std::strlen(user_data)`?

The above print is user_data, len is 765, you just asked me to print it, the json content must be there, but I don't know why the parsing error

![image](https://user-images.githubusercontent.com/55979795/152510248-23023a13-45ee-4566-b1f2-27e454ca231d.png)

**Comment by q1013348239** [comment]
> Please double check that there is a null byte in the input of the parser. Can you print the output of `std::strlen(user_data)`?

My own phone has no problem executing the exact same code, my friend's phone is an exception

**Comment by q1013348239** [comment]
> My own phone has no problem executing the exact same code, my friend's phone is an exception



> > Please double check that there is a null byte in the input of the parser. Can you print the output of `std::strlen(user_data)`?
> 
> The above print is user_data, len is 765, you just asked me to print it, the json content must be there, but I don't know why the parsing error
> 
> ![image](https://user-images.githubusercontent.com/55979795/152510248-23023a13-45ee-4566-b1f2-27e454ca231d.png)

My own phone has no problem executing the exact same code, my friend's phone is an exception

**Comment by nlohmann** [comment]
That's really strange. Can you please try to copy `user_data` to a `std::string` and call the parser with that string?

```cpp
std::string tmp = user_data;
std::cout << "strlen: " << std::strlen(user_data) << " - size(): " << tmp.size() << std::endl;
json result = json::parse(tmp);
```

**Comment by q1013348239** [comment]
> That's really strange. Can you please try to copy `user_data` to a `std::string` and call the parser with that string?
> 
> ```c++
> std::string tmp = user_data;
> std::cout << "strlen: " << std::strlen(user_data) << " - size(): " << tmp.size() << std::endl;
> json result = json::parse(tmp);
> ```

	const char *user_data = User_login(secret_key, app, appkey, Urlry, kmm, kmm_m, jqm);
	printf("\nuser_data：%s\n\n", user_data);
     
   
    std::string tmp = user_data;
    std::cout << "strlen: " << std::strlen(user_data) << " - size(): " << tmp.size() << std::endl;
    
    
	using json = nlohmann::ordered_json;
	char json_msg[4096] = "";
	char mem[4096] = "";
	int json_code_int;
	int json_time_int;
	 try
	{

		json result = json::parse(tmp);
		sprintf(json_msg, "%s", result["msg"].get < std::string > ().c_str());
   	 json_code_int = result["code"].get < int >();
	    json_time_int = result["time"].get < int >();
	   printf("msg：%s\ncode：%d\ntime：%d\n\n", json_msg, json_code_int,json_time_int);

	} catch(json::exception & e)
	{


		std::cout << "exception: " << e.what() << std::endl;

	}


![image](https://user-images.githubusercontent.com/55979795/152514715-bb936758-74c0-413d-9a9b-8e37527f7e61.png)

**Comment by nlohmann** [comment]
The strlen of 0 looks bad, and the error message as well.

Can you please run your code with address sanitizer or Valgrind? There seem to be some memory problem.

**Comment by q1013348239** [comment]
> The strlen of 0 looks bad, and the error message as well.
> 
> Can you please run your code with address sanitizer or Valgrind? There seem to be some memory problem.


If the length is very short, my friend's mobile phone intercepts normally, and my friend's mobile phone intercepts

![image](https://user-images.githubusercontent.com/55979795/152523113-d0ba4202-7c69-4702-92b7-d082382341a4.png)

**Comment by q1013348239** [comment]
> The strlen of 0 looks bad, and the error message as well.
> 
> Can you please run your code with address sanitizer or Valgrind? There seem to be some memory problem.

If the length is very short, my friend's mobile phone can intercept normally

![image](https://user-images.githubusercontent.com/55979795/152523239-4ba12021-c4ba-4110-a2de-3975dd94e783.png)

**Comment by gregmarr** [comment]
My guess at this point is that `User_login` is returning a pointer to internal temporary storage that is then being overwritten in another thread.  That's the only way I can see to have `strlen(user_data)` be 0 after copying the contents to the `std::string`.

Is the `User_login` function under your control?

**Comment by q1013348239** [comment]
> My guess at this point is that `User_login` is returning a pointer to internal temporary storage that is then being overwritten in another thread. That's the only way I can see to have `strlen(user_data)` be 0 after copying the contents to the `std::string`.
> 
> Is the `User_login` function under your control?

Thank you for your answers. I gave up json and directly intercepted the data. This way the compatibility is better. My friend's mobile phone and I have no problem. Thank you for your answers. Thank you

**Comment by q1013348239** [comment]
> The strlen of 0 looks bad, and the error message as well.
> 
> Can you please run your code with address sanitizer or Valgrind? There seem to be some memory problem.

Thank you for your answers. I gave up json and directly intercepted the data. This way the compatibility is better. My friend's mobile phone and I have no problem. Thank you for your answers. Thank you

**Comment by q1013348239** [comment]
> > The strlen of 0 looks bad, and the error message as well.
> > Can you please run your code with address sanitizer or Valgrind? There seem to be some memory problem.
> 
> Thank you for your answers. I gave up json and directly intercepted the data. This way the compatibility is better. My friend's mobile phone and I have no problem. Thank you for your answers. Thank you

If you can, you can delete this question, I solved it, thank you author
