### ISSUE TITLE
"type must be boolean, but is object" error thrown on non-boolean object

### ISSUE THREAD

**Issue by BBQGiraffe** [nlohmann/json#3319]
parsing the included json string throws a json::type_error with the description  **"type must be boolean, but is object"**

OS: Linux Mint 20.3
Compiler: g++ 9.3.0
CPP standard: C++17

**JSON string:**
```
{
  "DistanceSensor": {
    "Distance": 217,
    "SensorType": "PING"
  }
}
```
**minimal code example:**

```
try
{
    json j;
    j.parse(jsonStr);
}catch(json::type_error& e){
    std::cout << e.what() << std::endl;
}

```

**Comment by nlohmann** [comment]
The code example you provided cannot throw that exception you mentioned - this occurs if you try to assign a JSON value of type text to a C++ `bool` - an example would be code like

```cpp
json j = "text";
bool b = j;
```

Your example further call `parse` wrongly: it is a static function. You want to call

```cpp
json j = json::parse(jsonStr);
```

**Comment by BBQGiraffe** [comment]
oh wow I've been using this library super wrong, I fixed my blunders only to realize the type exception was from me forgetting that you can't null-check a non pointer object, thus leading to me using if(j) to determine if it parsed correctly before continuing, sleep before you program kiddos 


good way to check if your json parsed properly for anyone that makes the same mistake as me:
```
           json j;

            bool parsed = true;
            try{
                j = json::parse(text);
            }
            catch(json::parse_error e)
            {
                std::cout << e.what() << std::endl;
                parsed = false;
            }

            if(parsed)
            {
            }

```
