### ISSUE TITLE
Documentation for `ordered_json` should show proper use of the `parse()` function.

### ISSUE THREAD

**Issue by gregmarr** [nlohmann/json#3325]
https://json.nlohmann.me/features/object_order/ shows inserting objects in a particular order, but doesn't show how to properly use the `parse()` function to get the same result for existing JSON documents.

In particular, it needs to be this:

    auto j = nlohmann::ordered_json::parse(text);

and not this:

    nlohmann::ordered_json j = json::parse(text);

**Comment by gregmarr** [comment]
Can't change the labels, should be docs or enhancement or something like that.

**Comment by nlohmann** [comment]
Done: https://json.nlohmann.me/features/object_order/#notes-on-parsing
