### ISSUE TITLE
nlohmann::to_json method not acting as expected with nlohmann::adl_serializer specialization.

### ISSUE THREAD

**Issue by NovaSmoof** [nlohmann/json#3340]
I could not get the `nlohmann::to_json` method to work consistently with specializations of the `nlohmann::adl_serializer` which I assumed would work from the way described in the readme.

#### What is the issue you have?

I was using the [How do I convert third-party types](https://github.com/nlohmann/json#how-do-i-convert-third-party-types) explanation and I specialized the adl_serializer in the nlohmann namespace with my third party types, [Eigen's](https://eigen.tuxfamily.org/index.php?title=Main_Page) Vectors and Quaternions, I also did for some of my own types because they were move-constructible only. It sort of works. I would attempt to call `nlohmann::to_json` on my class's to `to_json` them. Because that appeared to work. (I looked at the [how to make your own serializer](https://github.com/nlohmann/json#can-i-write-my-own-serializer-advanced-use) for a small amount of guidance on implementing the functions) I did the nlohmann::to_json method because it was intuitive to me but it doesn't compile with `nlohmann::to_json(json, Quaternion{})`, things appear to compile when I do `json = Quaternion{}` though so I'm going to use that for now. 

#### Please describe the steps to reproduce the issue.

1. Define a specialization of the `nlohmann::adl_serializer` with some type 
2. Call the `nlohmann::to_json` on a type defined like this. 
3. Coin flip if it will compile or not.

#### Can you provide a small but working code example?

This is a repository I set up very quickly to show off the smallest case I had of this occurring. It should be cross platform in terms of files. It's simply a main file that includes your include directory and eigen's include directory. 
https://github.com/NovaSmoof/Eigen-nlohmann-conflict

#### What is the expected behavior?

that I can call nlohmann::to_json after specializing the adl_serializer. 

#### And what is the actual behavior instead?

That I could not. 

#### Which compiler and operating system are you using?

- Compiler: MSVC C++ from Visual Studio Community 2019 version 16.11.10
- Operating system: Windows 10

#### Which version of the library did you use?

I test both. Neither worked for MSVC.

- [x] latest release version 3.10.5
- [ ] other release - please state the version: ___
- [x] the `develop` branch

I tested with both and it failed with both.

#### If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

- [ ] yes
- [x] no - please copy/paste the error message below

I didn't get a compilation error, but my project's settings are really weird and it wouldn't build your unit tests right and your instructions didn't work. I tried it for an hour. And if you would like me to I'd be more than happy to attempt again, but as of right now I can't get many of them to run. I had difficulties downloading the data.

**Comment by nlohmann** [comment]
You're not supposed to call `to_json` or `from_json` directly. That is, instead of calling

```cpp
nlohmann::adl_serializer<Thing>::to_json(json["Thing"], thing);
nlohmann::to_json(json["Thing"], thing);
json["Thing"] = thing;
```

call

```cpp
json["Thing"] = thing;
```

Making these changes let me compile your example code. As the `main` is empty, I have no idea what to expect running it though.

**Comment by nlohmann** [comment]
@NovaSmoof Do you need further assistance?

**Comment by falbrechtskirchinger** [comment]
Note that Eigen had some issues with versions 3.10.4 and 3.10.5 (#3267). I think it had to do with the string type constraints, i.e., a similar issue as #3602.
