### ISSUE TITLE
json::out_of_range exception matches against lot of others while testing

### ISSUE THREAD

**Issue by nandanvasudevan** [nlohmann/json#3352]
#### What is the issue you have?
I was trying out https://github.com/nlohmann/json and wanted to test the exception mechanism it had.
My initial attempt was to use `CHECK_THROWS` but that was really difficult since [`nlohmann::json::out_of_range`](https://github.com/nlohmann/json/blob/e4643d1f1b03fc7a1d7b65f17e012ca93680cad8/include/nlohmann/detail/exceptions.hpp#L203-L216) is not easy to construct.
[`CHECK_THROWS_AS`](https://github.com/nandanvasudevan/cpp_scratch_pad/blob/3d274f7f62cf307a6be4414b8fb1f647f7a3ca94/src/main.cpp#L37-L38) was what I was supposed to use and that worked fine.

Before figure that out I tried `CHECK_THROWS` with `std::out_of_range` and to my surprise that worked! The test also passed with `std::bad_alloc`.

I am not sure if this is to be expected since `nlohmann::json::out_of_range` is derived from std::exception.

#### Please describe the steps to reproduce the issue.
This [`Code snippet`](https://github.com/nandanvasudevan/cpp_scratch_pad/blob/3d274f7f62cf307a6be4414b8fb1f647f7a3ca94/src/main.cpp#L40-L44)

#### Can you provide a small but working code example?
Minimal example here: https://github.com/nandanvasudevan/cpp_scratch_pad/tree/json_parsing

#### What is the expected behavior?
I expect the above tests to fail.
https://github.com/catchorg/Catch2/issues/2371

#### And what is the actual behavior instead?
The tests pass.

#### Which compiler and operating system are you using?
- Compiler: GCC v11
- Operating system: Jammy Jellyfish (development branch)
- Test framework: [Catch2 v3 Preview 4](https://github.com/catchorg/Catch2)

#### Which version of the library did you use?
- [x] latest release version 3.10.5
- [ ] other release - please state the version: ___
- [ ] the `develop` branch

#### If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?
Compiles fine.

- [ ] yes
- [ ] no - please copy/paste the error message below

**Comment by gregmarr** [comment]
By using just `CHECK_THROWS`, you are verifying that this expression throws:

    jsonParsed_full.at("Nonexistent"), std::out_of_range("")

and since it does throw, the check passes.  This is not a bug either in this library or in Catch2.

**Comment by nandanvasudevan** [comment]
It does not throw `std::out_of_range` or `std::bad_alloc`.

**Comment by nandanvasudevan** [comment]
I understand your point.
I guess I am supposed to use `CHECK_THROWS_AS` if I need to verify the type of the exception.

**Comment by nlohmann** [comment]
See https://github.com/catchorg/Catch2/issues/2371#issuecomment-1049576919.
