### ISSUE TITLE
Refactor unit tests to use more convenient doctest assertion macros

### ISSUE THREAD

**Issue by kkarbowiak** [nlohmann/json#3365]
Hello,

Since version 2.3.5 doctest supports new assertion macros that assert both exception type and message, in the form of `*_THROWS_WITH_AS` (e.g. `CHECK_THROWS_WITH_AS`).

With those, some code duplication in unit tests can be avoided, as for example the following (test/src/unit-constructor1.cpp):
```c++
CHECK_THROWS_AS((j.get<std::pair<int, int>>()), json::out_of_range&);
CHECK_THROWS_WITH((j.get<std::pair<int, int>>()), "[json.exception.out_of_range.401] array index 1 is out of range");
```
can be replaced with:
```c++
CHECK_THROWS_WITH_AS((j.get<std::pair<int, int>>()), "[json.exception.out_of_range.401] array index 1 is out of range", json::out_of_range&);
```

Would you be interested in that? If so, I can create a pull request.

**Comment by nlohmann** [comment]
Hey @kkarbowiak - yes, why not! I hope you can do this automatically as there are 979 `CHECK_THROWS_AS` calls and 1020 `CHECK_THROWS_WITH` calls...

**Comment by kkarbowiak** [comment]
I hope so too ;-) I will get back with a PR.
