### ISSUE TITLE
Regression test for #3070 is not being run and fails when enabled

### ISSUE THREAD

**Issue by falbrechtskirchinger** [nlohmann/json#3377]
Working on some unit test improvements, I discovered at least two unit tests that are not being run. This issue is about
```cpp
#if JSON_HAS_FILESYSTEM || JSON_HAS_EXPERIMENTAL_FILESYSTEM
    SECTION("issue #3070 - Version 3.10.3 breaks backward-compatibility with 3.10.2 ")
    {
        static_assert(false); // Added to confirm this test is never run
        nlohmann::detail::std_fs::path text_path("/tmp/text.txt");
        json j(text_path);

        const auto j_path = j.get<nlohmann::detail::std_fs::path>();
        CHECK(j_path == text_path);

        CHECK_THROWS_WITH_AS(nlohmann::detail::std_fs::path(json(1)), "[json.exception.type_error.302] type must be string, but is number", json::type_error);
    }
#endif
```
added in 6d3115924c.

`nlohmann::detail::std_fs::path(json(1))` fails to compile, because the constructor call is ambiguous.

@theodelrieu @nlohmann Was/is this expected to work?

(The fact, that this test isn't being run will be fixed by an upcoming PR.)

**Comment by falbrechtskirchinger** [comment]
Clarification: If I remember correctly the ambiguity arises from `std::fs::path` accepting both `std::string` and `std::fs::path` (copy ctor, obviously) and `basic_json<>` can implicitly convert to both. I don't see a way to resolve this ambiguity.

@nlohmann Thoughts?

**Comment by nlohmann** [comment]
Thanks for clarifying! I'll think about this. Good to know that it never worked - this allows us to make changes without breaking existing implementations ;-)

**Comment by nlohmann** [comment]
I am confused - locally, the test is executed and succeeds... (Apple clang version 13.0.0)

**Comment by nlohmann** [comment]
So it seems the test is indeed not executed on Windows - maybe the filesystem detection is broken and all compilers are skipped. The test is executed on macOS and Linux for some compilers. However, not for all C++17 enabled compilers. 🤔

**Comment by falbrechtskirchinger** [comment]
While I didn't dig into why it is now running in my builds (#3380). I consolidated the test macros into a separate header and copied them over from `include/nlohmann/detail/macro_scope.hpp`. The unit test embedded macros were either defined incorrectly or missing.

I'm also working on printing out build information with each test to better understand which test are compiled using which flags and standard version, etc.

**Comment by nlohmann** [comment]
Good point. I think outputting some of the defines makes sense. File `cmake/download_test_data.cmake` is currently used for this. Not optimal, but better than nothing.

**Comment by falbrechtskirchinger** [comment]
Well, I'm definitely going overboard but you can read all about the how and why in my PR soon. Hopefully, that is. After 20+ red CI runs they have to turn green eventually, right? :wink:
