### ISSUE TITLE
CMake script MAIN_PROJECT always OFF

### ISSUE THREAD

**Issue by Arnaud-Tardy** [nlohmann/json#3390]
https://github.com/nlohmann/json/blob/700b95f4473cac1d900b807541daad0ca3d98f52/CMakeLists.txt#L14
This following test is always FALSE
  if (CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR)

You wish to test: if ("${CMAKE_CURRENT_SOURCE_DIR}" STREQUAL "${CMAKE_SOURCE_DIR}")

**Comment by falbrechtskirchinger** [comment]
I don't believe you are correct. The CMake `if()` command predates the introduction of the `${}` variable expansion syntax. This legacy behavior is documented [here](https://cmake.org/cmake/help/latest/command/if.html#variable-expansion) and remains valid today.

**Comment by Arnaud-Tardy** [comment]
Sorry

**Comment by falbrechtskirchinger** [comment]
Thanks anyway. No harm done. :-)
