### ISSUE TITLE
""-operators ignore the length parameter

### ISSUE THREAD

**Issue by bisqwit** [nlohmann/json#340]
The operator""_json() and operator""_json_pointer() seem to be ignoring the length parameter generated by the compiler. While this works, the string constant will be used to construct a std::string at least in json_pointer(), and it would be slightly more efficient to pass the length parameter to the std::string constructor, so it does not need to do a strlen-operation to determine how much space to allocate for the string.

**Comment by nlohmann** [comment]
Fixed. Thanks!
