### ISSUE TITLE
About Serialization Error invalid UTF-8 byte at index

### ISSUE THREAD

**Issue by TimelifeCzy** [nlohmann/json#3414]
### Description

Chinese deserialization error

### Reproduction steps

#include <json.hpp>
using json_t = nlohmann::json;
std::string ch="中文";
json_t  j;
j["ch_debug"]=ch.c_str();
j.dump();

### Expected vs. actual results

![try_](https://user-images.githubusercontent.com/43507143/161411961-fd88cd73-8cec-4e13-9dc7-64c7806b20c6.jpg)

### Minimal code example

```Shell
#include <json.hpp>
using json_t = nlohmann::json;
std::string ch="中文";
json_t  j;
j["ch_debug"]=ch.c_str();
j.dump();
```

### Error messages

```Shell
JSON_THROW(type_error::create(316, "invalid UTF-8 byte at index " + std::to_string(i) + ": 0x" + ss.str(), BasicJsonType()));
```

### Compiler and operating system

win10 20he - IDE vs2019

### Library version

3.10.5

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
See https://json.nlohmann.me/home/exceptions/#jsonexceptiontype_error316

**Comment by TimelifeCzy** [comment]
> See https://json.nlohmann.me/home/exceptions/#jsonexceptiontype_error3
