### ISSUE TITLE
Allow hex numbers

### ISSUE THREAD

**Issue by ianmccul** [nlohmann/json#342]
Allowing hexadecimal numbers for integer constants would be very useful.  This would be a JSON extension, but as far as I can tell it wouldn't change the interpretation of any valid JSON syntax, just allow correctly parsing a format that is currently invalid.

**Comment by nlohmann** [comment]
I am against implementing JSON extensions, because such extensions break interoperability.

(Sorry, but creating JSON output with hexadecimal numbers is a problem in the first place)
