### ISSUE TITLE
feature wish: JSONPath

### ISSUE THREAD

**Issue by tesch1** [nlohmann/json#343]
A simple query() function would be a fantastic addition.  Maybe it's totally out of scope for this project, but searching the issues didn't turn up any discussion, so maybe this issue is just a place to say it wont be done :)

Some related refs:
http://goessner.net/articles/JsonPath/
https://chromium.googlesource.com/external/mozc/+/master/src/net/jsonpath.cc
https://www.genivia.com/doc/xml-rpc-json/html/

**Comment by nlohmann** [comment]
Currently, only JSON Pointer is implemented. JSON Path sounds interesting, but I currently do not have the time to look into it.

**Comment by nlohmann** [comment]
I had another look at this. It seems doable, but also a lot of work. I shall postpone this ticket until after the 3.0.0 release.

**Comment by tesch1** [comment]
No worries!  It'd definitely a lot of work.  Really cool of you to look at it tho, open source is awesome :)

**Comment by nlohmann** [comment]
Is there an agreed upon reference for JSON Path?

**Comment by tesch1** [comment]
I think this is the first - http://goessner.net/articles/JsonPath/

**Comment by nlohmann** [comment]
This less of a specification, but rather a list of examples.

Furthermore:
> XPath has a lot more to offer (Location pathes in not abbreviated syntax, operators and functions) than listed here.

**Comment by nlohmann** [comment]
I'm closing this for now in lieu of a proper specification of "JSONPath", see https://github.com/nlohmann/json/issues/343#issuecomment-270067634.

**Comment by yangbodong22011** [comment]
Hi, @nlohmann Would you consider supporting or accepting the PR of JSONPath?

**Comment by nlohmann** [comment]
Why not? Is there a proper specification now?

**Comment by yangbodong22011** [comment]
It is still not a standard, but we have "conventional" examples: https://github.com/freestrings/jsonpath/wiki/rust-examples

Including those implemented by [RedisJSON](https://github.com/RedisJSON/RedisJSON).

**Comment by nlohmann** [comment]
I see. In any case, it would be best to implement this as free functions; that is, not to add any member functions, because the API is already pretty bloated. Do you think this is possible?

**Comment by yangbodong22011** [comment]
I haven't dig into the code details yet, and I don't quite understand what you mean by `free functions`.

But I think as a parsing path, under the premise that JSONPointer is already supported, it would be best if it can be automatically recognized as JSONPath or JSONPointer and successfully access the element.

**Comment by nlohmann** [comment]
I meant I'd rather have something like

```cpp
json authors = json::selector(j, "$.store.book[*].author");
```

rather than

```cpp
json authors = j.selector("$.store.book[*].author");
```

**Comment by yangbodong22011** [comment]
Oh, I think I agree with you, after all, `json::parse` is like this.

**Comment by oiwg** [comment]
Now up to draft 6, progress tracked at https://datatracker.ietf.org/wg/jsonpath/about/ , standards track document due in November.

**Comment by jianbingfang** [comment]
Is the JsonPath feature available now?

**Comment by udem1234** [comment]
Hi.

@nlohmann :  Any news on this ?  :-)

(btw, I just came across this cool jsonpath online evaluator : [JSONPath Online Evaluator by Kazuki Hamasaki](https://jsonpath.com/) for those who might be interested)

Thank you.

**Comment by nlohmann** [comment]
It's not on my todo list, but merge requests are welcome.
