### ISSUE TITLE
Parsing error when there is a json string within a Json

### ISSUE THREAD

**Issue by WorstCodeWay** [nlohmann/json#3445]
### Description

In some situation, I want a special json object which has a json string as its value, take following as a example:

set std::string `samplestring` with following value:

```json
{
  "some_key":"{\"in_key\":\"in_value\"}"
}
```

### Reproduction steps

Just pass the string above for parsing

### Expected vs. actual results

Successfully parse that string with a json object, and we can also get sub-string of inner-json object.

### Minimal code example

```Shell
auto json = nlohmann::json::parse(samplestring);
```

### Error messages

```Shell
error: std::exception
```

### Compiler and operating system

ubuntu 18.04 g++ 7.5

### Library version

Maybe 13? Don't get this project from GitHub, so don't know the version.

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
What is the what() message of the exception?

**Comment by falbrechtskirchinger** [comment]
Please show a complete example. It works just fine here: https://godbolt.org/z/sjGq79Pnn
Output:
```
{
    "some_key": "{\"in_key\":\"in_value\"}"
}
{
    "in_key": "in_value"
}
```

**Comment by WorstCodeWay** [comment]
I think I get some useful information after many tries, the following are correct:

```json
# 1
{"some_key":"{\"in_key\":\"in_value\" }"}

#2
{"some_key":
    "{\"in_key\":\"in_value\" }"
}

# 3
{
   "some_key":"{"in_key":"in_value" }"
}
```
Following are incorrect:
```json
# 4
{"some_key":
    "{\
        \"in_key\":\"in_value\"\
    }"
}

# 5
{
   "some_key":"{"in_key":"in_value" }"
}

# 6
{"some_key":"{\"in_key\":\"in_value\"\
    }"
}
```

Conclusion from my opinion, the sub-json string value shouldn't be operated into multi-lines. and the '\' ESC expected。However， I don't know the root reason.

Besides, I'm introduce this project along with other third party project which is a tcp server, so I tested all this from a tcp client tool, pasting json strings above into client text widget as plain text, and send. So I guess the format reason is the most? Right?

**Comment by falbrechtskirchinger** [comment]
That's simply not valid JSON. Putting a backslash before a line break to escape it is not a thing in JSON (as far as I'm aware of).

**Comment by WorstCodeWay** [comment]
@falbrechtskirchinger 
> That's simply not valid JSON. Putting a backslash before a line break to escape it is not a thing in JSON (as far as I'm aware of).

```json
{"some_key":"{
        \"in_key\":\"in_value\"
    }"
}
```
Sorry for incomplete example list, I have added fourth example of incorrect list. I notice your point: not invalid JSON for ESC. But the fourth bad example should be a valid json?

**Comment by falbrechtskirchinger** [comment]
JSON doesn't support multi-line strings. Note that the Markdown renderer highlights your syntax errors in red. Below is the corrected version:
```json
{
    "some_key":"{\n        \"in_key\":\"in_value\"\n    }"
}
```

**Comment by WorstCodeWay** [comment]
> JSON doesn't support multi-line strings. Note that the Markdown renderer highlights your syntax errors in red. Below is the corrected version:
> 
> ```json
> {
>     "some_key":"{\n        \"in_key\":\"in_value\"\n    }"
> }
> ```

Thank you very much @falbrechtskirchinger . Now I understand what have happened. I will close this post, as it's not a bug.

Sorry for wasting your time.
Thanks, again. @nlohmann @falbrechtskirchinger
