### ISSUE TITLE
Weird things on for statement

### ISSUE THREAD

**Issue by EG-Julien** [nlohmann/json#3447]
### Description

Hi,
I'm using the library to read a kind of book database. The bug occurs when I try to "parse" all the records.

### Reproduction steps

When I do a for statement on the DB get through a method it doesn't seems to get it properly. However when I declare a variable (auto type) and call it in the for statement it works as expected.

### Expected vs. actual results

Trying to parse all id : 
It gives me this when I declare a variable :
```
$ SEARCH aze
0
1
2
3
4
5
6
7
8
```
And gives me nothing when I put the getter in the for statement.

### Minimal code example

```cpp
auto db_json = this->db.getRawDatabase().at("records");
for (auto r : db_json) {
    cout << r.at("id") << endl;
}
```
Output :
0
1
2
3
...

with getRawDatabase() :
```cpp
class Database
{
    private:
       nlohmann::json database;
       ...
   public:
      Database(const std::string __file);
      Database();
      ...
      nlohmann::json getRawDatabase() { return this->database; }
      ...
```
However this output nothing :
```cpp
for (auto r : this->db.getRawDatabase().at("records")) {
    cout << r.at("id") << endl;
}
```
```


### Error messages

```Shell
No error.
```

### Compiler and operating system

MacOS X 12.3.1 - Apple Clang 13.1.6

### Library version

latest

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by falbrechtskirchinger** [comment]
Just change your `getRawDatabase()` function to:
```
const nlohmann::json &getRawDatabase() const { return this->database; }
```

**Comment by EG-Julien** [comment]
Thanks it works just fine with this change.
I'm actually a student in electronics and I use this lib for a school project in order to learn cpp ... I was pretty sure it was related to my code instead of the lib :)

Thanks for your help and tips !
