### ISSUE TITLE
Unable to compile when using Microsoft's _CRTDBG

### ISSUE THREAD

**Issue by Shidell** [nlohmann/json#3457]
### Description

I use Microsoft's CRT memory analyzer to monitor memory usage in DEBUG builds, and wanted to use this JSON parser, but I'm having difficulty including it in our builds alongside Microsoft's [CRTDBG](https://docs.microsoft.com/en-us/visualstudio/debugger/finding-memory-leaks-using-the-crt-library?view=vs-2022).

### Reproduction steps

Microsoft's CRTDBG effectively breaks down to redefining **new** in DEBUG builds so that it can track memory leaks and provide analysis, including the offending line number, when requested.

We include it in our builds with other definitions ahead of library **#includes** and it looks like this:

```
#ifdef _DEBUG
	#define _CRTDBG_MAP_ALLOC
	#include <crtdbg.h>
	#ifndef DBG_NEW
		#define DBG_NEW new ( _NORMAL_BLOCK , __FILE__ , __LINE__ )
		#define new DBG_NEW
	#endif
#endif
```

If we **#include "json.hpp"** at any point after this declaration, it will fail. However, if we move including json.hpp ahead of the redefinition of new, then everything compiles as expected:

```
#ifdef _DEBUG
	#define _CRTDBG_MAP_ALLOC
	#include <crtdbg.h>
        #include "json.hpp"
	#ifndef DBG_NEW
		#define DBG_NEW new ( _NORMAL_BLOCK , __FILE__ , __LINE__ )
		#define new DBG_NEW
	#endif
#endif
```

### Expected vs. actual results

I expect to be able to include json.hpp just like any other library, but understand that there's an issue with redefining **new**. I'm not sure what the issue is, however, as I don't see **new** being redefined within json.hpp itself.

I'm hoping to better understand the nature of this problem, as I'd prefer to use this over the other, older JSON library, but I can't include json.hpp ahead of other libraries that have explicit defines, including the _CRTDBG declaration.

### Error messages

```
Shell Error	C2760	syntax error: '&' was unexpected here; expected 'type specifier'

The error line is 17412, the entire block looks like this:

    size_type erase(const Key& key)
    {
        for (auto it = this->begin(); it != this->end(); ++it)
        {
            if (it->first == key)
            {
                // Since we cannot move const Keys, re-construct them in place
                for (auto next = it; ++next != this->end(); ++it)
                {
                    it->~value_type(); // Destroy but keep allocation
                    new (&*it) value_type{std::move(*next)};
                }
                Container::pop_back();
                return 1;
            }
        }
        return 0;
    }
```
The specific offending line (Note this is just one example, of 32 total errors, related to this):
```
new (&*it) value_type{std::move(*next)};
```

### Compiler and operating system

VS2022, C++20

### Library version

3.10.5

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by falbrechtskirchinger** [comment]
The macro definition doesn't look like it would work with placement new, so this isn't very surprising. It might be possible to define your own variadic macro to handle placement news. Otherwise, there isn't much we can do here. There's an active PR that adds even more placement news, we're not going to get rid of them.

**Comment by falbrechtskirchinger** [comment]
You can give this try:
```cpp
#define NEW_DEBUG new(_NORMAL_BLOCK, __FILE__, __LINE__)
#define NEW_DEBUG2(...) new(__VA_ARGS__)
```
From: https://stackoverflow.com/questions/5053382/override-new-operator-in-c-while-crtdbg-h-is-causing-conflicts

**Comment by Shidell** [comment]
@falbrechtskirchinger Thanks for the suggestions; the above didn't work immediately. Unfortunately, It appears that CRTDBG doesn't support **placement new**, which is strange, as it's still Microsoft's recommended tooling for memory analysis for MSVC++.

I'm not sure what my path forward is, but this is clearly not a bug related to json.hpp, so I'm closing this issue. Thank you for the help!

**Comment by gregmarr** [comment]
@Shidell I believe the latest recommended method is to use `DBG_NEW` instead of `new` in your code.  https://docs.microsoft.com/en-us/visualstudio/debugger/finding-memory-leaks-using-the-crt-library?view=vs-2022

**Comment by Shidell** [comment]
Thanks @gregmarr, I'm considering doing so as well, although I'm not sure how I want to handle it with other library code that we use.
