### ISSUE TITLE
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE_WITH_DEFAULT can not parse { "key" : null}

### ISSUE THREAD

**Issue by engine5d** [nlohmann/json#3458]
### Description

struct Data{
     std::string key;
}

if json likes 
`{
    "key": null
}`
the NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE_WITH_DEFAULT to "Data" type occurs exception.

if json like 
`{
     "key" : ""
}`

it' OK.

### Reproduction steps

reproduction ...

### Expected vs. actual results

error

### Compiler and operating system

win10   vs 2017

### Library version

develope

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
I assume the exception complains about the type. `null` cannot be converted into a `std::string` automatically. If you want to have some custom behavior in this situation (e.g., `null` converting to the empty string), then you need to define the conversion manually with user-defined `to_json`/`from_json` functions.

See https://json.nlohmann.me/api/macros/nlohmann_define_type_non_intrusive/#examples for examples which code the macros create. You can start from there and add your desired behavior.

**Comment by nlohmann** [comment]
@engine5d Do you need further assistance with this issue?

**Comment by engine5d** [comment]
thanks. with user-defined to_json/from_json is ok although it's complicated

**Comment by wwwtiger2022** [comment]
It's better add a flag in these templates, or a new template,  to allow json null convert to empty string.
