### ISSUE TITLE
Is it possible to stream data through the json parser without storing everything in memory?

### ISSUE THREAD

**Issue by anden259** [nlohmann/json#347]
Is it possible to stream data through the json parser without storing everything in memory?

Lets say I have a json file that is 10 GB, is it possible to stream that through the parser without storing it in memory?

Something like:
file stream >> json deserialze >> data stream

and the reverse:
data stream >> json serialize >> json string stream

Is that possible with this library?

**Comment by nlohmann** [comment]
What exactly would the library do in this setting?

**Comment by nlohmann** [comment]
You may want to have a look at the parser callback mechanism of the library:
- [general documentation](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a9e35475e2027520a78e09f460dbe048a.html#a9e35475e2027520a78e09f460dbe048a)
- [an example](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a0923f9749409345a21f8cb15ee95fc0d.html#a0923f9749409345a21f8cb15ee95fc0d)

It may not be 100% what you need, but maybe you can express your usecase in terms of such a callback function.

**Comment by nlohmann** [comment]
@anden259 Can I close this ticket?

**Comment by anden259** [comment]
@nlohmann I had a look through the docs, examples and source code. The current library does not support what I need, so I decided to write my own. It'll get published once it's more complete than it is a the moment. Thank you for your help. Feel free to close the ticket.
