### ISSUE TITLE
It can't support  "nan", "inf", "-inf" for float type

### ISSUE THREAD

**Issue by laok-solomon** [nlohmann/json#3494]
### Description

when use PCL library, I need write some data to json. 
my code is some like: 

```cpp
"write special float value to json file":
float userFilterValue = std::numeric_limits<float>::quiet_NaN();
nlohmann::ordered_json ser;
ser["userFilterValue“] = userFilterValue;
std::ofstream("test.json") << ser.dump(2);

"read special float value to json file":
float userFilterValue2 = 0;
nlohmann::ordered_json ser2;
std::ifstream("test.json") >> ser2;
userFilterValue2 = (float) ser["userFilterValue“];
```

I found that the "test.json" file data:

```json
{
 "userFilterValue": null
}
```

### Reproduction steps

I just want to serialize some  special float value, such as "nan", "inf", "-inf"
but it throws exception wiht tips "type must be number, but is null"

### Expected vs. actual results

when I write "nan", "inf" as float value, but it got "null"

### Minimal code example

```Shell
float userFilterValue = std::numeric_limits<float>::quiet_NaN();
nlohmann::ordered_json ser;
ser["userFilterValue“] = userFilterValue;
std::ofstream("test.json") << ser.dump(2);


nlohmann::ordered_json ser2;
std::ifstream("test.json") >> ser2;
float userFilterValue2 = (float) ser["userFilterValue“];
```

### Error messages

```Shell
type must be number, but is null
```

### Compiler and operating system

visual studio 2019

### Library version

3.10.4

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
This is expected behavior, see https://json.nlohmann.me/features/types/number_handling/.
