### ISSUE TITLE
An exception occurred when sending a string with double quotes

### ISSUE THREAD

**Issue by Cdreamfly** [nlohmann/json#3504]
### Description

An exception occurred when sending a string with double quotes

### Reproduction steps

If I send a string with double quotes, it will not parse properly, for example, if I type "hello".

### Expected vs. actual results

After a json \"msg\":\"\"hello\"\"

### Error messages

```Shell
terminate called after throwing an instance of 'nlohmann::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at line 1, column 17: syntax error while parsing object - invalid literal; last read: '""o'; expected '}'
```

### Compiler and operating system

gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)

### Library version

JSON for Modern C++ version 3.10.5

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
Quotes must be escaped in JSON strings. This is valid JSON:

```json
{
    "msg": "\"hello\""
}
```

This is not:

```json
{
    "msg": ""hello""
}
```

**Comment by Cdreamfly** [comment]
Oh, yes, thank you for your answer, I should have thought carefully before asking.

**Comment by nlohmann** [comment]
No worries!
