### ISSUE TITLE
Enable 32bit unit test in CI

### ISSUE THREAD

**Issue by falbrechtskirchinger** [nlohmann/json#3524]
### Description

The CI image lacks support for `-m32` builds, and source lines have to be excluded until that is addressed.

### Reproduction steps

n/a

### Expected vs. actual results

n/a

### Compiler and operating system

n/a

### Library version

n/a

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
Should work with the latest CI image as used in #3528

**Comment by falbrechtskirchinger** [comment]
I'll either submit a PR against your `new_ci` branch or tell you where to `git cherry-pick` from.

**Comment by nlohmann** [comment]
I‘m traveling, so a PR would be best.

**Comment by nlohmann** [comment]
Closed by merging #3532.
