### ISSUE TITLE
Request: access with default value.

### ISSUE THREAD

**Issue by SmoofBullet** [nlohmann/json#353]
Hi everyone!

I would suggest to provide new member functions

        template <typename T>
        T operator ()(const typename object_t::key_type& key, const T &fallback) const
        {
            const auto it = find(key);
            if (it == end() || it.value().is_null())
            {
                return fallback;
            }
            else
            {
                return at(key);
            }
        }

        string_t operator ()(const typename object_t::key_type& key, const string_t &fallback) const 
        {
            return operator()<string_t>(key, fallback);
        }

        template <typename T>
        T operator ()(const typename object_t::key_type& key, const T &fallback)
        {
            const auto it = find(key);
            if (it == end() || it.value().is_null())
            {
                return (*this)[key] = fallback;
            }
            else
            {
                return (*this)[key];
            }
        }

        string_t operator ()(const typename object_t::key_type& key, const string_t &fallback)
        {
            return operator()<string_t>(key, fallback);
        }

I use those for convenient accesses to numbers, strings, vectors and maps in a json object with default values.

Further, i use

        reference operator()(const typename object_t::key_type& key)
        {
            return (*this)[key];
        }

        value_type operator()(const typename object_t::key_type& key) const
        {
            if (find(key) == end())
            {
                return value_type();
            }
            else
            {
                return (*this)[key];
            }
        }

for more consistent code look when using the functions above.

What do you think?

Greetings

**Comment by nlohmann** [comment]
This sounds related to the `value` function: https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a407e73a037e6e3067ef7aa2c25a79f39.html#a407e73a037e6e3067ef7aa2c25a79f39

**Comment by nlohmann** [comment]
@SmoofBullet Did you have the time to look at the value function?

**Comment by zumm** [comment]
@nlohmann method "value" helps to avoid outing of range only. If requested field exists, but has different type then this method throws exception. Such behavior is undesirable.

**Comment by nlohmann** [comment]
There has been quite a discussion about this, see #278.

**Comment by zumm** [comment]
So this functional will be implemented in release 3.0.0? Great (apropos when it happens?)!

**Comment by nlohmann** [comment]
#278 is planned for the 3.0.0. This release will most likely not be ready this year.

If you can live with the proposal in #278, I would like to close this ticket.

**Comment by zumm** [comment]
Yes, i can. :) But could starter of this ticket?

**Comment by nlohmann** [comment]
Oh, sorry. @SmoofBullet What do you think?

**Comment by SmoofBullet** [comment]
I think the solution will work for me, although im not sure whether the value function should be restricted to object types. If i provide a default value, i would not mind if the caller passed me the wrong type (something different than object).
