### ISSUE TITLE
turning an object into an array

### ISSUE THREAD

**Issue by azchatlanin** [nlohmann/json#3547]
### Description

Good afternoon. I can make mistakes in actions. But when I do initialization through curly brackets,  I get an array instead of the expected object.

### Reproduction steps

For examle

```c++
using json = nlohmann::json;

int main()
{
  std::string str = "{ \"uuu\": 123 }";
  json j = json::parse(str);
  json a {  j  }; // a is array of objects ["{ \"uuu\": 123 }"]
  json b {  a  }; // b is array of array of objects [["{ \"uuu\": 123 }"]]
}
```

### Expected vs. actual results

I would like to see the same object

### Compiler and operating system

g++

### Library version

last

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
Duplicate if #2583
