### ISSUE TITLE
unicode4 test consistently fails on RISC-V hardware

### ISSUE THREAD

**Issue by Madouura** [nlohmann/json#3579]
### Description

When compiling ``nlohmann_json`` on NixOS, on a RISC-V 64 bit system, StarFive VisionFive, the ``unicode4`` test times out and fails the build.
This does not happen on regular x86_64 systems, so I believe a fix may be needed for either the test, or the thing being tested, regarding RISC-V compatibility.

### Reproduction steps

Attempt to build ``nlohmann_json`` on a RISC-V system, either hardware or through a virtual machine like QEMU, on NixOS.
If you happen to have a StarFive VisionFive board, I suggest using this PR to reproduce: https://github.com/NixOS/nixpkgs/pull/168826

### Expected vs. actual results

``unicode4`` test should not be timing out.

### Error messages
https://gist.github.com/Madouura/edf2ac1b06bf6e63507b9dc9bb338064

### Compiler and operating system

GCC11 IIRC, NixOS

### Library version

3.10.5

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by falbrechtskirchinger** [comment]
Increase the timeout then? This happens in CI sometimes as well.

**Comment by Madouura** [comment]
I am very unfamiliar with this project, would you mind pointing to me where I can do that?
Is it a cmake option or something in the unit test itself?

**Comment by falbrechtskirchinger** [comment]
See `ctest --help`.

>  --timeout <seconds>          = Set the default test timeout.

The default is 1500 seconds.

**Comment by falbrechtskirchinger** [comment]
I'll look into raising the timeout for `test-unicode4_cpp11` permanently.

**Comment by falbrechtskirchinger** [comment]
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/nlohmann_json/default.nix

Have you considered building with the CMake option `JSON_FastTests=ON`?

```
  cmakeFlags = [
    "-DBuildTests=${if doCheck then "ON" else "OFF"}"
    "-DJSON_FastTests=ON"
    "-DJSON_MultipleHeaders=ON"
  ] ++ lib.optional doCheck "-DJSON_TestDataDirectory=${testData}";
```

Also, `BuildTests` is wrong. The option is named `JSON_BuildTests`. As is `doCheck` doesn't affect unit testing.

**Comment by Madouura** [comment]
I'll test it out and report back when done, thank you.

**Comment by Madouura** [comment]
Successful build in my case, with FastTests.
Should I keep this issue open, since you have a PR ready?

**Comment by falbrechtskirchinger** [comment]
Good to hear!
You can leave the issue open. I've linked it to the PR and it should be closed on merge.
