### ISSUE TITLE
Check if library can be used with ETL

### ISSUE THREAD

**Issue by nlohmann** [nlohmann/json#361]
The Embedded Template Library (http://www.etlcpp.com) seems to be a reasonable idea, and it would be nice to know to what extend the library can be used with the type provided by the ETL.

**Comment by nlohmann** [comment]
Closed due to inactivity.

**Comment by nlohmann** [comment]
There are still issues compiling the ETL, see https://github.com/ETLCPP/etl/issues/12.

**Comment by nlohmann** [comment]
I shall close this issue. Getting ETL to work is too much effort at this moment.

**Comment by GioF** [comment]
What's the current status of this issue? Compiling with the ETL would be very useful for many use cases still.

**Comment by nlohmann** [comment]
I would need a concrete example how you would use this library together with ETL.
