### ISSUE TITLE
ICPC: warning #1098: the qualifier on this friend declaration is ignored

### ISSUE THREAD

**Issue by nlohmann** [nlohmann/json#3632]
### Description

Compiling `test-alt-string_cpp11` yields a warning with ICPC.

```
[8/137] Building CXX object tests/CMakeFiles/test-alt-string_cpp11.dir/src/unit-alt-string.cpp.o
/__w/json/json/tests/src/unit-alt-string.cpp(164): warning #1098: the qualifier on this friend declaration is ignored
      friend bool ::operator<(const char* /*op1*/, const alt_string& /*op2*/) noexcept;
                  ^
```

### Reproduction steps

Run CI - see https://github.com/nlohmann/json/runs/7580471440?check_suite_focus=true

### Expected vs. actual results

Expected: no warning.

Actual: warning

### Error messages

```Shell
[8/137] Building CXX object tests/CMakeFiles/test-alt-string_cpp11.dir/src/unit-alt-string.cpp.o
/__w/json/json/tests/src/unit-alt-string.cpp(164): warning #1098: the qualifier on this friend declaration is ignored
      friend bool ::operator<(const char* /*op1*/, const alt_string& /*op2*/) noexcept;
                  ^
```

### Compiler and operating system

Intel 2021.5.0.20211109, Ubuntu 20.04.3 LTS

### Library version

develop

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by falbrechtskirchinger** [comment]
Removing the `::` seems to fix the issue.

**Comment by nlohmann** [comment]
> Removing the `::` seems to fix the issue.

I'll create a PR.
