### ISSUE TITLE
'to_string' is not a member of 'std' 

### ISSUE THREAD

**Issue by joshuagahan** [nlohmann/json#364]
added json.hpp to project and imported, set "g++ follow c++ ISO C++ language standard [-std=c++11] and get compiler errors for to_strong and stoi.  I'm using GNU GCC Compiler, Codeblocks 16.01 IDE, on windows.  

If this is something I'm doing wrong, vice an issue, I'm unaware.  I'm a very very new CS major and don't honestly know much about compilers, includes, well pretty much anything.

**Comment by gregmarr** [comment]
Sounds like the GCC compiler in that version doesn't have a complete standard library.  Can you determine which version of GCC is included?

**Comment by joshuagahan** [comment]
4.9.2 far as I can tell, I used codeblocks auto install for minGW and can't go g++ --version to check.  I've been using and running it for months with no problem, its just became an issure now trying to use this library

**Comment by nlohmann** [comment]
From the README:

> For GCC running on MinGW or Android SDK, the error `'to_string' is not a member of 'std'` (or similarly, for `strtod`) may occur. Note this is not an issue with the code,  but rather with the compiler itself. On Android, see above to build with a newer environment.  For MinGW, please refer to [this site](http://tehsausage.com/mingw-to-string) and [this discussion](https://github.com/nlohmann/json/issues/136) for information on how to fix this bug. For Android NDK using `APP_STL := gnustl_static`, please refer to [this discussion](https://github.com/nlohmann/json/issues/219).

**Comment by nlohmann** [comment]
@joshuagahan Could you fix the issue?

**Comment by nlohmann** [comment]
Inactive.
