### ISSUE TITLE
_json  operator""() 

### ISSUE THREAD

**Issue by boris-999** [nlohmann/json#3644]
### Description

had some issues with  `operator"" _json`  namespacing.  added the #define as per docs: https://json.nlohmann.me/api/operator_literal_json/   then there was an issue with #if JSON_USE_GLOBAL_UDLS   not making any sense.  should that be #ifdef ?  

### Reproduction steps

1. #define JSON_USE_GLOBAL_UDLS
2. #if JSON_USE_GLOBAL_UDLS   causes compiler error

### Expected vs. actual results

probaly should be #ifdef,  not #if

### Compiler and operating system

msvc 2019 - 16.11.17 (current as of 2022-08-02)

### Library version

3.11.0

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by falbrechtskirchinger** [comment]
This line in the documentation should probably read:
> Alternatively, define `JSON_USE_GLOBAL_UDLS` to `1` to make them available in the global namespace.

That is, please use `#define JSON_USE_GLOBAL_UDLS 1`. That is the default, though. Can you elaborate on what your problem is and how I might reproduce it?

**Comment by gregmarr** [comment]
The default is to have that defined to 1.  Define it to 0 if you want to disable the default behavior:

https://json.nlohmann.me/api/macros/json_use_global_udls/

@falbrechtskirchinger Maybe this line is left over from before it was the default:

https://json.nlohmann.me/api/operator_literal_json/
Alternatively, define [JSON_USE_GLOBAL_UDLS](https://json.nlohmann.me/api/macros/json_use_global_udls/) to make them available in the global namespace.

**Comment by falbrechtskirchinger** [comment]
We clearly had the same thought. :-)

**Comment by gregmarr** [comment]
@falbrechtskirchinger Got here just before me.  :)
