### ISSUE TITLE
Coverity issue (FORWARD_NULL) in lexer(std::istream& s)

### ISSUE THREAD

**Issue by darklukee** [nlohmann/json#368]
Coverity found an issue in lexer(std::istream& s):

> 1. assign_zero: Assigning: this->m_start = NULL.

```
7618        explicit lexer(std::istream& s)
7619            : m_stream(&s), m_line_buffer()
7620        {
7621            // fill buffer
```
> CID 1077412 (#1 of 3): Explicit null dereferenced (FORWARD_NULL)
> 2. var_deref_model: fill_line_buffer dereferences null this->m_start. 

`7622            fill_line_buffer();`

**Comment by nlohmann** [comment]
I'll have a look at this. By the way, how did you get Coverity to run? I currently have a problem with this, see #299.

**Comment by darklukee** [comment]
It was run locally on build server. I didn't set it up and I don't have access to configuration so I can't help you here. Coverity version used: 8.0.0.

But you are doing some weird steps in COVERITY_SCAN_BUILD_COMMAND_PREPEND. I would look into it.

**Comment by nlohmann** [comment]
Issue #299 seems to be fixed. I could run a Coverity analysis and I found the same error:

```
** CID 154530:  Null pointer dereferences  (FORWARD_NULL)
/src/json.hpp: 9124 in nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, long, unsigned long, double, std::__1::allocator>::lexer::lexer(std::__1::basic_istream<char, std::__1::char_traits<char>> &)()

________________________________________________________________________________________________________
*** CID 154530:  Null pointer dereferences  (FORWARD_NULL)
/src/json.hpp: 9124 in nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, long, unsigned long, double, std::__1::allocator>::lexer::lexer(std::__1::basic_istream<char, std::__1::char_traits<char>> &)()
9118             std::istream* m_stream = nullptr;
9119             /// line buffer buffer for m_stream
9120             string_t m_line_buffer {};
9121             /// the buffer pointer
9122             const lexer_char_t* m_content = nullptr;
9123             /// pointer to the beginning of the current symbol
   CID 154530:  Null pointer dereferences  (FORWARD_NULL)
   Assigning: "this->m_start" = "NULL".
9124             const lexer_char_t* m_start = nullptr;
9125             /// pointer for backtracking information
9126             const lexer_char_t* m_marker = nullptr;
9127             /// pointer to the current symbol
9128             const lexer_char_t* m_cursor = nullptr;
9129             /// pointer to the end of the buffer
```

However, I have yet to understand the error.

**Comment by nlohmann** [comment]
More details:

<img width="836" alt="error" src="https://cloud.githubusercontent.com/assets/159488/20609591/f00cdf2c-b28e-11e6-8e69-3250f9697f74.png">

**Comment by nlohmann** [comment]
This is a false positive:

- When `lexer(std::istream& s)` is called, a pointer to `s` is stored in `m_stream`. `m_stream` cannot be `nullptr` when `fill_line_buffer` is called from `lexer(std::istream& s)`.
- `m_stream == NULL` is the precondition (1.) of Coverity.

Nevertheless, I shall add an assertion before the `append` call.
