### ISSUE TITLE
MSVC natvis visualizer does not work after introduction of inline ABI namespace

### ISSUE THREAD

**Issue by jheydebrand** [nlohmann/json#3696]
### Description

#844 added a debugger visualizer for Visual Studio.
#3590 introduced an inline namespace under which the basic_json type now lives.

Therefore the type name pattern in the natvis file https://github.com/nlohmann/json/blob/0e61ee8b074ecb40be6439c7470764dc6c3e0743/nlohmann_json.natvis#L3 does not match the actual type anymore which means the visualizer does not work anymore.

With the inline namespace regularly changing, it might be worthwhile to dynamically generate the natvis file from CMake using the same "algorithm" for the type name pattern as implemented with the macros in the source code.

### Reproduction steps

Create a `nlohmann::json` instance, fill it with some data, and break with Visual Studio debugger to inspect the object instance.

### Expected vs. actual results

Actual: visualizer not active
Expected: visualizer provides pretty printing

### Compiler and operating system

Visual Studio

### Library version

3.11.1

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by falbrechtskirchinger** [comment]
On it. I think this is the thing I've been trying to remember, so, thanks!
