### ISSUE TITLE
Local copy given by operator[] or at() 

### ISSUE THREAD

**Issue by mbelhadi** [nlohmann/json#3704]
### Description

Hello, 

I have strange behaviour when I try to get a value from a json object.

### Reproduction steps

Just trying de get a reference using operator[] or .at()

### Expected vs. actual results

I expected the actual reference of a value when I do this

```cpp
std::string const &value = obj["key"];
// or
std::string const &value = obj.at("key");
```

### Minimal code example

```cpp
// ...
json obj = {{"key", "value"}};
const std::string &a = obj["key"]; // new local copy of value
const std::string &b = obj.at("key"); // new local copy of value
const std::string &c = obj.at("key").get_ref<std::string const &>(); // the real ref
std::cout << a.c_str() != c.c_str() << std::endl; // false
std::cout << b.c_str() != c.c_str() << std::endl; // false
```

### Compiler and operating system

gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1)

### Library version

develop commit 8fcdbf2e771f481d988cb36847d6af6b17e30a99

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by falbrechtskirchinger** [comment]
This is as designed and you already figured out that you need to use `get_ref()`.

`operator[]` and `at()` return a `basic_json` reference which implicitly converts to a copy of and not a reference to the internal value.

**Comment by mbelhadi** [comment]
Why do you not send always a reference , and the final variable defines the copy behaviour as STL does.
```cpp
std::string const &a = obj["key"]; // ref to const ref
std::string &b = obj["key"]; // ref to ref
std::string c = obj["key"]; // ref to copy
```
The get or get_ref have a heavy syntax, may be there is a technical limitation for doing this.

Thanks for your answer, closing the issue.

**Comment by falbrechtskirchinger** [comment]
> Why do you not send always a reference , and the final variable defines the copy behaviour as STL does.

Feel free to demonstrate how that would work. I don't think it's possible in a statically typed language.

**Comment by gregmarr** [comment]
FYi, operator[] and at() do return references, it's the implicit conversions to std::string afterwards that convert to a copy.
