### ISSUE TITLE
docs: how to release a json object in memory?

### ISSUE THREAD

**Issue by Fonger** [nlohmann/json#371]
If I have a huge json object and each json has reference to sub json object.
Is there a  way to completly free the huge json object with all it's child json object?

**Comment by nlohmann** [comment]
What do you mean with "free"? Deallocate the memory?

**Comment by nlohmann** [comment]
Inactive.

**Comment by nlohmann** [comment]
No, the memory is managed by the internal data structures, which base on `std::vector`, `std::map`, and `std::string`.
