### ISSUE TITLE
Compiler warnings?

### ISSUE THREAD

**Issue by davidbernstein** [nlohmann/json#372]
Hi, When I include json.hpp I get many compiler warnings like

//usr/local/include/nlohmann/json.hpp(3006): warning: type qualifier is meaningless on cast type

Is there a way to suppress these? I'm on OS X with Xcode 7.2 (stuck on that version for other reasons).

Thanks,
Dave

**Comment by davidbernstein** [comment]
[warnings.txt](https://github.com/nlohmann/json/files/620609/warnings.txt)

Attached is the full set of warnings I get. Clang sadly does not tell you the compiler flags to set to ignore the warnings in some cases.

**Comment by nlohmann** [comment]
Thanks for reporting. I had a look at the warnings:

- "warning: template parameter "T" is not used in declaring the parameter types of function template" in json.hpp(1335) and json.hpp(1430): The template parameter `T` is in fact not used inside the function, but only to remove the function if `number_integer_t`/`number_unsigned_t` is the same as `int`. I am not sure how to silence this warning.
- "unused type alias 'pointee_t'": `pointee_t` is used in a `static_assert` - I have no idea why the compiler warns about this.
- "warning: unused type alias 'PointerType'": in fact, `PointerType` *is* used in the next line `auto ptr = obj.template get_ptr<PointerType>();`

These warnings look odd...

**Comment by davidbernstein** [comment]
Yes I noticed that 2 and 3 were warnings about unused things that are actually used. I'm assuming this is probably some clang flakiness. One of these can be ignored with the flag  -Wno-unused-local-typedef. If I can find flags for the other two I'll post them here.

**Comment by gregmarr** [comment]
FYI XCode 7.2 uses Clang 7.0.2.

**Comment by davidbernstein** [comment]
Yes, that could be the problem. I'm stuck on 7.2 since this is for a CUDA project and the nvidia toolkit is not compatible with the latest Xcode.

**Comment by nlohmann** [comment]
This really seems to be a quirk of the Clang version: Apple LLVM version 8.0.0 (clang-800.0.42.1) compiles without warning when called with `-Wunused-local-typedef`.

**Comment by davidbernstein** [comment]
Ok then it's just me! Thanks for checking that out.
