### ISSUE TITLE
Reading from file

### ISSUE THREAD

**Issue by AliceCupcakee** [nlohmann/json#374]
I don't see any capability offhand for this to read a .json file. Is this a feature? If so, what is the syntax? If not, can this be made a feature?

**Comment by nlohmann** [comment]
You can use the `parse` function (https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a0923f9749409345a21f8cb15ee95fc0d.html#a0923f9749409345a21f8cb15ee95fc0d) or the `operator<<` (https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a60ca396028b8d9714c6e10efbf475af6.html#a60ca396028b8d9714c6e10efbf475af6)

You can pass any input stream to it, including an `ifstream`.

**Comment by nlohmann** [comment]
I updated the [README](https://github.com/nlohmann/json#tofrom-streams-eg-files-string-streams) and added a section on deserialization from file.
