### ISSUE TITLE
Allow to disable inline namespaces completley

### ISSUE THREAD

**Issue by ingo-loehken** [nlohmann/json#3746]
### Description

Inline namespaces do not coexist with C++/CLI. Therefore it would be great, to allow disabling inline namespaces at all.

Discussion from Microsoft Developer Community
https://developercommunity.visualstudio.com/t/ccli-bug-with-inline-namespaces-header/14964

### Reproduction steps

Create a project with C++/CLI support and include any nlohmann/json Header.

### Expected vs. actual results

No compiler error.

### Error messages

```Shell
compiler error: cannot reopen non inline namespace as inline
```

### Compiler and operating system

Visual C++ 16.11.18 (Visual Studio 2019)

### Library version

3.11.2

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
Removing bug label as this is a compiler bug with MSVC. We use several versions in the CI.

**Comment by falbrechtskirchinger** [comment]
That's already possible.

https://json.nlohmann.me/features/namespace/#disabling-the-inline-namespace-completely

**Comment by falbrechtskirchinger** [comment]
> Removing bug label as this is a compiler bug with MSVC. We use several versions in the CI.

We don't test C++/CLI aka. managed C++. Do we even support non-standard C++ officially?

**Comment by nlohmann** [comment]
Sorry I missed the C++/CLI part. No, we don't test it (yet - happy to see a PR). And also no, we do not support non-standard C++.

**Comment by ingo-loehken** [comment]
You are right, redefining the BEGIN and END namespaces macros should be sufficient. I will test that and report back here.

**Comment by ingo-loehken** [comment]
works as expected. thx.
