### ISSUE TITLE
parsing json with missing key throws exception

### ISSUE THREAD

**Issue by aangert** [nlohmann/json#3784]
### Description

When trying to parse a json file with missing keys json throws an exception and stops parsing
Is there a way of successfully parsing files with missing keys?

### Reproduction steps

compile and run the code

### Expected vs. actual results

Expected: 
json `[{
"testObj":{
"start": 3,
"stop": 7,
"time": 4
},
"obj": 3
}
]` is parsed without an exception

Actual: 
```
terminate called after throwing an instance of 'nlohmann::json_abi_v3_11_2::detail::out_of_range'
  what():  [json.exception.out_of_range.403] key 'missing' not found
```

### Minimal code example

```Shell
#include <iostream>
#include <fstream>
#include <nlohmann/json.hpp>

struct demo {
        int start;
        int stop;
        int missing;
        int time;
};

struct test {
        demo testObj;
        int obj;
};

NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(demo, start, stop, missing, time)
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(test, testObj, obj)

int main() {
        std::ifstream inFile("test.json");
        nlohmann::json jsonData = nlohmann::json::parse(inFile);
        test data = jsonData[0].get<test>();
        if (data.testObj.start == 3) return -1;
        return 0;
}
```

### Error messages

```Shell
terminate called after throwing an instance of 'nlohmann::json_abi_v3_11_2::detail::out_of_range'
  what():  [json.exception.out_of_range.403] key 'missing' not found
Abgebrochen
```

### Compiler and operating system

GCC 10.2.1

### Library version

4b2c8ce6bcfe7f39f2bb9e680c1e7a4d67c2dd48

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by gregmarr** [comment]
This is not a parsing error, this is an error converting the parsed object to your defined structures.  You specified by using the macro `NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE` that all structure members are required.  If you want some of the structure members to be optional, then you need to write the `from_json` function yourself and handle the data for that member not being provided in the JSON.

**Comment by aangert** [comment]
so there is no way of marking an element as optional without defining a custom `from_json` function?

**Comment by gregmarr** [comment]
The macro `NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE` shortcut for automatically creating the custom `from_json` function does not support optional elements.
