### ISSUE TITLE
When reading a non-existent key, I unexpectedly get a value. Is it the wrong way I use it?

### ISSUE THREAD

**Issue by flyfein** [nlohmann/json#3811]
### Description

When reading a non-existent key, I unexpectedly get a value

### Reproduction steps

Use the operator '[]' to read key values

### Expected vs. actual results

It is expected to return an empty object when reading a non-existent key, but an object corresponding to other keys is actually returned

### Minimal code example

```Shell
#include <iostream>
#include <memory>
#include <string>
#include <vector>
#include "json.hpp"

using namespace nlohmann;
static const std::string strjson = R"(
{
  "services": [
    {
      "routes": {
        "r1": [
          {
            "resource": "/a/b/c"
          }
        ]
      }
    }
  ]
}
)";

int main() {
  try {
    json j = json::parse(strjson);
    json rules = j["services"];
    auto tables = rules[0]["routes"];
    std::cout << "routes " << tables.dump() << std::endl;

    std::cout << "count of 't2' is " << tables.count("t2") << std::endl; // output -> count of 't2' is 0
    json snat = tables["t2"];
    std::cout << snat.dump() << std::endl;  // output ?/
  } catch (std::exception &e) {
    std::cout << e.what() << std::endl;
  }

  return 0;
}
```

### Compiler and operating system

gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

### Library version

JSON for Modern C++ version 3.5.0

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by gregmarr** [comment]
Compiler Explorer [output](https://godbolt.org/z/rq9Ke4WdM) looks right for gcc 7.5.0 with library 3.5.0.  Can you provide more information about what you're getting and what you're expecting?

**Comment by flyfein** [comment]
The latest version is OK
