### ISSUE TITLE
Update FAQ section in the guidelines for contributing

### ISSUE THREAD

**Issue by nlohmann** [nlohmann/json#382]
There are repeated requests for the same functionality, so it would save everybody's time to open a FAQ section:

- adding support to comments (no, link to [Reddit](https://www.reddit.com/r/programming/comments/4v6chu/why_json_doesnt_support_comments_douglas_crockford/))
- preserving the insertion order of object entries (no)
- compiler support for GCC 4.8

I shall extend this ticket with more entries.

**Comment by gregmarr** [comment]
Forward declarations.

**Comment by nlohmann** [comment]
I realized that part of the list is already in the [guidelines for contributing](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md) I shall update these instead of adding this to the README file.

**Comment by nlohmann** [comment]
@gregmarr I left the forward declarations out of the FAQ, because #314 is still open. I may add this point if we decide to reject this issue.
