### ISSUE TITLE
nlohmann::json::parse can't handle the "€" symbol.

### ISSUE THREAD

**Issue by AHURDYK** [nlohmann/json#3825]
### Description

I have a server application which sent me the following JSON response : 

{
	"requestAnswer":{
		"noError":1,
		"message":"Error while processing document 0",
		"complement":{
			"errCode":-40,
			"errLbl":"Dialogue logiciel vers unit\u9820incorrect",
			"errComp":"€"
		}
	},
	"processedDocs":[
		
	],
	"status":0
} 

A quick run of that JSON on https://jsonformatter.curiousconcept.com/# shows that this JSON is totally fine.

However, nlohman::json::parse does not seem to be able to parse this JSON. nlohmann:json::accept does not seem to accept this as a proper JSON either.

I tried to some characters that I suspected could cause nlohmann to not be able to parse my JSON, and quickly concluded that the library seems to have a particular distaste of the character "€".

### Reproduction steps

Just parse any JSON with the character "€" as a value. I recommend checking my minimal code example.

### Expected vs. actual results

Expected result : nlohmann should accept the JSON as a proper JSON, with "€" as a value for "errComp".
Actual result : "Unknown Exception" from my exception handler.

### Minimal code example

```Shell
//The code below will fail due do the "errComp" value : 
try
{
  nlohmann::json jj = nlohmann::json::parse("{ \"requestAnswer\":{\"noError\":1,\"message\" : \"Error while processing document 0\",\"complement\" : {\"errCode\":-40,\"errLbl\" : \"Dialogue logiciel vers unit\u9820incorrect\",\"errComp\" : \"€\"}},\"processedDocs\" : [],\"status\" : 0 }");
}
catch (std::exception e)
{
  std::string errMsg = e.what();
  std::cout << "NLOHMANN ERROR : " + errMsg << std::endl;
}

//Try to replace the "€" with anything else and you'll see that you won't fall into the catch block anymore.
```

### Error messages

```Shell
C++ std::exception item seems to return "Unknown Exception".
```

### Compiler and operating system

MSVC 2015

### Library version

3.11.2

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
Please make sure the file is UTF-8 encoded.

**Comment by AHURDYK** [comment]
My server doesn't send files, but I tried to put the faulty JSON string in an UTF-8 encoded file and open it anyway : the parse function managed to open it from the file.

Looks like I'll have to review my server and make sure my responses are properly encoded.
