### ISSUE TITLE
Compile Error on g++ using get() function

### ISSUE THREAD

**Issue by phil-zxx** [nlohmann/json#3827]
### Description

When iterating over a `nlohmann::json` object and then casting the **values** using `value.get<std::string>()`, we observe that `g++` gives a compile error. On `clang` and `msvc` everything compiles just fine.

Replacing `value.get<std::string>()` with `std::string(value)` fixes the problem on `g++`. But I wonder why the `get` function does not work?

### Reproduction steps

See https://godbolt.org/z/Gxv7dbsjW

### Expected vs. actual results

I would expect the "minimal code example" to compile as is on `g++`. But it does not.

### Minimal code example

```Shell
// https://godbolt.org/z/Gxv7dbsjW

#include <nlohmann/json.hpp>
#include <iostream>

template<class K, class V>
void convert(const nlohmann::json& sourceData, std::map<K, V>& targetMap)
{
    for (const auto& [key, value] : sourceData.items())
    {
        if constexpr(std::is_same_v<V, std::string>)
            targetMap.emplace(key, value.get<std::string>());
            //targetMap.emplace(key, std::string(value));  // Only way to fix g++ is to use this line
        else
            throw std::runtime_error("Case not covered");
    }
}

int main()
{
    const nlohmann::json data = {
        {"Year2", "2022" },
        {"Year3", "2023" },
        {"Year9", "2029" }
    };
    std::map<std::string, std::string> m;
    convert(data, m);

    for (const auto& [k, v] : m)
        std::cout << " - " << k << ": " << v << std::endl;

    return 0;
}
```

### Error messages

```Shell
<source>:10:42: warning: expected 'template' keyword before dependent template name [-Wmissing-template-keyword]
   10 |             targetMap.emplace(key, value.get<std::string>());
      |                                          ^~~
      |                                          template

<source>:10:57: error: expected primary-expression before '>' token
   10 |             targetMap.emplace(key, value.get<std::string>());
      |                                                         ^

<source>:10:59: error: expected primary-expression before ')' token
   10 |             targetMap.emplace(key, value.get<std::string>());
      |                                                           ^
```

### Compiler and operating system

g++ (Linux)

### Library version

3.11.1 & trunk

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by falbrechtskirchinger** [comment]
Don't use structured bindings or do as the compiler asks. Adding the `template` keyword to disambiguate the dependent name (which I assume is due to the compiler-generated code for the structured binding) resolves the issue on GCC and still compiles on Clang and MSVC.

```cpp
targetMap.emplace(key, value.template get<std::string>());
```

This is not a bug in the library.

Edit: In case you're unfamiliar with this construct, see: https://en.cppreference.com/w/cpp/language/dependent_name#template_disambiguator

**Comment by phil-zxx** [comment]
Thank you for the detailed explanation. I did not know about this syntax. Though, I am surprised clang and msvc don't complain.

As this is not a bug, the issue may be closed.
