### ISSUE TITLE
json::accept return false on valid JSON

### ISSUE THREAD

**Issue by piatf** [nlohmann/json#3838]
### Description

According to https://json.nlohmann.me/api/basic_json/accept/, the accept() method should return "true" if the JSON is valid.

Unfortunately, in my case, for my JSON database (~62000 lines ), the method accept returns false, even if online tools such as https://jsonlint.com/ confirms that my JSON is valid. 

### Reproduction steps

To reproduce, call method "accept()" on a large JSON file.

### Expected vs. actual results

With above code and json, accept() should return true, but it returns false.
It should also parse it successfully.

### Minimal code example

```Shell
#include <iostream>
#include <fstream>
#include "json/single_include/nlohmann/json.hpp"

using json = nlohmann::json;

int main()
{
    std::ifstream dbStream("./database.json");
    std::cout << std::boolalpha
              << json::accept(dbStream);
    return 0;
}

```
I hope this code is good btw.

### Error messages

If I try to parse the JSON, I get following error message : 
`
terminate called after throwing an instance of 'nlohmann::json_abi_v3_11_2::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: ' '
`

### Compiler and operating system

Compiler : GCC 8.1.0, OS Windows 10 Family, OS build 19045.2251

### Library version

3.11.2

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by Hansonyao417** [comment]
Hi I am gonna try to fix this issue as the final project for a class.

**Comment by gregmarr** [comment]
Based on the error message, sounds like it is not finding the file.  Please verify first that you are able to successfully read and output the file contents.  Once you are sure your configuration is working, then try using `json::accept()`.

**Comment by falbrechtskirchinger** [comment]
Please check that `dbStream.good() == true` before calling accept.

**Comment by piatf** [comment]
> Please check that `dbStream.good() == true` before calling accept.

Thanks for the tip, I did, and it returned true, even if accept() still returns false.

> Based on the error message, sounds like it is not finding the file. Please verify first that you are able to successfully read and output the file contents. Once you are sure your configuration is working, then try using `json::accept()`.

I am able to open and read it. With simple code using std::getline() method, I am able to print the file. 
However, something weird is that when I try to print it, I get an extra space between all charaters: 
e.g. :
```
" C l a s s N a m e "  :    " D e s c _ A l u m i n u m C a s i n g _ C "  ,
```
Instead of : 
```
"ClassName": "Desc_AluminumCasing_C",
````

**Comment by gregmarr** [comment]
Your file is stored as a Unicode file with 16 bit characters.  It has a Unicode Byte Order Mark at the beginning.  You can see this if you open it in Visual Studio as a binary file, it starts with 0xFF 0xFE.  https://en.wikipedia.org/wiki/Byte_order_mark

This library only accepts UTF-8 strings.

**Comment by piatf** [comment]
> 

Thanks a lot, this was indeed the issue. Sorry, I am quite new with handling and parsing external files, I just learnt something new !
