### ISSUE TITLE
json::parse and constructor with the same json generates different type

### ISSUE THREAD

**Issue by LukaMod** [nlohmann/json#3842]
### Description

I use gdb to debug the code example, find that `j1`(use `json::parse`) has a different `m_type` from `j2` (use constructor).
(gdb) p j1
$1 = {m_type = nlohmann::detail::object, m_value = {object = 0x641120, array = 0x641120, string = 0x641120, binary = 0x641120, boolean = 32, number_integer = 6557984,
    number_unsigned = 6557984, number_float = 3.2400746003765614e-317}}
(gdb) p j2
$2 = {m_type = nlohmann::detail::string, m_value = {object = 0x641080, array = 0x641080, string = 0x641080, binary = 0x641080, boolean = 128, number_integer = 6557824,
    number_unsigned = 6557824, number_float = 3.2399955498732268e-317}}

### Reproduction steps

compile and run the code

### Expected vs. actual results

expected results: demo works

actual results: throws exception

### Minimal code example

```Shell
#include <nlohmann/json.hpp>
#include <vector>
#include <string>
#include <iostream>

using namespace std;
using json = nlohmann::json;

struct Range {
    int pos;
    int len;    
};

struct Theme {
    string     url;    
    int    id;
    Range      range;
};

struct Text {
    Theme     theme;
    string    text;
};

struct Property {
    int type;
};

struct MediaSource {
    int                 type;
    string              url;        
    Range               range;   
    vector<Property>    props;
};

struct Operator {
    vector<Text>        texts;
    vector<Theme>       filters;
    vector<MediaSource> srcs;
    vector<Property>    props;
};

NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(Range, pos, len);
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(Theme, url, id, range);
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(Text, theme, text);
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(Property, type);
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(MediaSource, type, url, range, props);
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(Operator, texts, filters, srcs, props);


int main() {
    std::string s("{\"filters\":[],\"props\":[{\"type\":1},{\"type\":2}],\"srcs\":[],\"texts\":[]}");
    assert(json::accept(s) == true);
    
    Operator op1, op2;

    json j1 = json::parse(s);
    json j2 = s;

    j1.get_to(op1); // OK and op1 is correct

    cout << "op1 OK\n";

    j2.get_to(op2); // throw... what():  [json.exception.type_error.304] cannot use at() with string

    cout << "op2 OK\n";

    return 0;
	
}
```

### Error messages

```Shell
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.304] cannot use at() with string
```

### Compiler and operating system

g++ 4.8.5

### Library version

3.11.2

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
This is expected behavior. The parse function actually parses the input string and create a JSON object out of this. By just calling the constructor with a string, the string is only assigned, but not parsed. The error message `cannot use at() with string` is a consequence of this.
