### ISSUE TITLE
Proccess crash as soon as I parse json

### ISSUE THREAD

**Issue by hern0s-dev** [nlohmann/json#3843]
### Description

Its working well if I use this library on a console application c++ But when I use it on my DLL project Im using it in Main thread like this

     using jsonfile = nlohmann::json;
	std::ifstream file("SpellData.json");
	jsonfile data = jsonfile::parse(file);  //Crashing here
	for (auto spell : data)
	{
		std::cout << spell["name"] << std::endl;
	}

Program crashes.
Another question is where json file must be located ? In the same folder as dll output ? or Same folder as .sln ? and why its crashing ?

### Reproduction steps

I can't debug code . Because proccess I'm working on has a anti-debug protect soo I can't debug code.Its just crash as soon as I inject.

### Expected vs. actual results

Crashes

### Compiler and operating system

Visual Studio 2022 Windows 11

### Library version

Lastest

### Validation

- [x] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
The exception contains a member function `what()` which gives you an explanation - this should also be shown when the process crashes. From your questions I assume the file `SpellData.json` cannot be found. It has to be in the working directory of the process - I have no idea about the default value in Visual Studio, but I assume it should be the same folder than the binary.

**Comment by hern0s-dev** [comment]
Hello nlohmann ! Thank you for quick reply and this library.

I noticed problem was with ;
`std::ifstream file(".json path");`

I though it was looking json file inside my dll folder but I was wrong it was searching inside binary folder.Then I provided full path like C://bla bla bla... and now Its working as intended.
