### ISSUE TITLE
Occur error when parse character '\' 

### ISSUE THREAD

**Issue by AronZhi** [nlohmann/json#3844]
### Description

When I run code as follows:
```
    std::string sData("{\"a\":\"b\\a\",\"b\":2}");
    nlohmann::json obj = nlohmann::json::parse(sData);
```
It both throw error in version 3.7.3 and 3.11.2.

After delete '\' as follows:
```
    std::string sData("{\"a\":\"ba\",\"b\":2}");
    nlohmann::json obj = nlohmann::json::parse(sData);
```
It will run successfuly.

### Reproduction steps

Run code as follows:
```
    std::string sData("{\"a\":\"b\\a\",\"b\":2}");
    nlohmann::json obj = nlohmann::json::parse(sData);
```
It both throw error in version 3.7.3 and 3.11.2.

### Expected vs. actual results

expect: 
 json::parse run success and no error occur.

actually:
 error occur

### Compiler and operating system

Microsoft Visual C++ 2019 / Build Tools 16.3.1+1def00d3d (and possibly later)

### Library version

3.11.2 or 3.7.3

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
The exception message should tell you that backslashes need to be escaped.

**Comment by AronZhi** [comment]
>The code in reproduction steps section,  I did escaped the backslashes, but Git don't show the original code.

**Comment by AronZhi** [comment]
> When processing a string containing a windows format path, an unhandled exception will be thrown

**Comment by AronZhi** [comment]
This issue is same as issue #2652

**Comment by gregmarr** [comment]
@AronZhi See here for instructions on how to format code so it's not mangled: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks
