### ISSUE TITLE
Json Arrays have inconsistent nesting levels across different OSs

### ISSUE THREAD

**Issue by tizzymac** [nlohmann/json#3854]
### Description

When creating a json array, the nlohmann library adds an extra level of nesting on Windows but not on Mac when the exact same code is run. 

### Reproduction steps

I am creating an array of 1 using a json object that I have already defined. Run the code on Mac, then run the same code on Windows.

This causes `my_json` to be double nested in square brackets on Windows and single nested on Mac:
```
nlohmann::json my_json;
...
j["key"]= nlohmann::json::array({my_json});
```

Whereas this creates a single-nested array on Windows but on Mac no array is created and "my_json" is added directly:
`j["key"]= {my_json};`

### Expected vs. actual results

**Expected:**
```
"key": [
                {
                    "foo": "bar",
                    ...
                }
        ],
```

**Actual:**
```
"key": [
[
                {
                    "foo": "bar",
                    ...
                }
]
        ],
```

### Compiler and operating system

CMake, Windows, Mac

### Library version

3.9.1

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
This is not due to the OS, but due to the compiler's different behavior for braces initialization. See #2583.
