### ISSUE TITLE
I want the data field to be empty serialized and deserialized to each other

### ISSUE THREAD

**Issue by Cdreamfly** [nlohmann/json#3866]
### Description

```cpp
class Data{
public:
    NLOHMANN_DEFINE_TYPE_INTRUSIVE_WITH_DEFAULT(Data)
};
class test{
public:
    NLOHMANN_DEFINE_TYPE_INTRUSIVE_WITH_DEFAULT(test,cmd,data)
    std::string cmd;
    Data data;
};
```

### Reproduction steps

```cpp
std::string str = "{\n"
                      "    \"cmd\": \"TtsPlay\", \n"
                      "    \"data\": { }\n"
                      "}";
    json js = json::parse(str);
    test t = js;
    js = t;
    std::cout << js.dump() << std::endl;
```

### Expected vs. actual results

I want the data field to be empty serialized and deserialized to each other

### Error messages

```Shell
error: expected unqualified-id before ‘;’ token
 2733 | #define NLOHMANN_JSON_TO(v1) nlohmann_json_j[#v1] = nlohmann_json_t.v1;
```

### Compiler and operating system

gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)

### Library version

JSON for Modern C++ version 3.11.2

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
What is your goal with

```cpp
NLOHMANN_DEFINE_TYPE_INTRUSIVE_WITH_DEFAULT(Data)
```

? As per https://json.nlohmann.me/api/macros/nlohmann_define_type_intrusive/, there must be a member given.

Can you give an example how the JSON you want to generate should look like?

**Comment by nlohmann** [comment]
(see also https://github.com/nlohmann/json/discussions/3865#discussioncomment-4370686)

**Comment by nlohmann** [comment]
Do you need further assistance with this issue?
