### ISSUE TITLE
[json.exception.type_error.316] invalid UTF-8 byte at index 0: 0xB6

### ISSUE THREAD

**Issue by zhjiarong** [nlohmann/json#3879]
### Description

```cpp
int main()
{
	try
	{
		std::ifstream replyfile("D:\\REPLY.bson", std::ios::in | std::ios::binary);
		if (!replyfile.is_open())
		{
			return EXIT_FAILURE;
		}

		std::istreambuf_iterator<char> beg(replyfile), end;
		std::string replycontent = std::string(beg, end);
		replyfile.seekg(0, std::ios::end);
		nlohmann::json replyjson = nlohmann::json::from_bson(replycontent);
		std::cout << replyjson << std::endl;

		replyfile.close();
	}
	catch (std::exception& e)
	{
		std::cout << e.what() << std::endl;
	}

	system("pause");
	return 0;
}
```

output:
![image](https://user-images.githubusercontent.com/44044519/207539673-88d8211e-3a3a-4589-b041-abd679d1732e.png)
REPLY.bson：有中文
![image](https://user-images.githubusercontent.com/44044519/207541050-0cc6f7ee-4602-46cb-b417-ba5b25fac56d.png)
REPLY.bson file：
[REPLY.zip](https://github.com/nlohmann/json/files/10225591/REPLY.zip)

### Reproduction steps

打开包含中文字符的bson文件。

### Expected vs. actual results

能正确读写包含中文字符的bson文件。

### Error messages

```Shell
[json.exception.type_error.316] invalid UTF-8 byte at index 0: 0xB6
```

### Compiler and operating system

windows11

### Library version

3.11.2

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
There is an error and index 0 which means already the first byte is invalid. The spec (https://bsonspec.org/spec.html) does not allow byte `0xB6` as first byte.

When I look at your file, the first byte is `0x6E`, however. Can you please double check your example?

**Comment by nlohmann** [comment]
@zhjr2019  Any update?

**Comment by zhjiarong** [comment]
@nlohmann I don't know how to modify it. Can you teach me?
