### ISSUE TITLE
building with cmake

### ISSUE THREAD

**Issue by ozcanay** [nlohmann/json#3880]
### Description

Cmake .. && make -j does not work properly on CentOS-7

### Reproduction steps

I am having trouble compiling the project. Here is what I am doing:

```
git clone https://github.com/nlohmann/json.git
cd json
mkdir build
cd build
cmake ..
```

So far, so good.

However, when I execute:

```
make -j
```

Nothing happens, no response at all.

### Expected vs. actual results

I was expecting makefile to produce any message.

### Compiler and operating system

gcc 10.1.0, CentOS7

### Library version

3.11.2 (develop branch)

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
Which CMake version are you using? Can you share the complete output of running CMake?

**Comment by ozcanay** [comment]
![image](https://user-images.githubusercontent.com/9106924/207839611-87356bea-3b19-454d-988f-978a3cd83b9b.png)

**Comment by nlohmann** [comment]
This is as expected. Your CMake version is so old that `JSON_BuildTests_INIT` is unconditionally set to `OFF`, see https://github.com/nlohmann/json/blob/develop/CMakeLists.txt#L35.

Without setting `JSON_BuildTests` to `ON`, the tests will not be built.

Fix: Call

```shell
cmake .. -DJSON_BuildTests=ON
```

or upgrade CMake.

**Comment by ozcanay** [comment]
I would rather see a warning about this issue, though.

**Comment by nlohmann** [comment]
When the library is included as third-party, no tests should be compiled unless explicitly specified with `-DJSON_BuildTests=ON`. This is also documented in the README.

In which situation would you expect a warning?
