### ISSUE TITLE
Json::accept(std::ifstream)

### ISSUE THREAD

**Issue by snow-tyan** [nlohmann/json#3884]
### Description

```c++
std::ifstream ifs(device_file, std::ios::in);
CHECK_RET_MSG(ifs.is_open(), -1, "can not open {}", device_file);
CHECK_RET_MSG(Json::accept(ifs), -1, "{} not json", device_file);
Json json = Json::parse(ifs); 
ifs.close();
```  
When I use Json::accept to check whether the stream is legal, 
then Json::parse error occurs
After debug, it was found that the file pointer is moved to the end by Json::accept.
Whether other interfaces can return the stream pointer to the beginning after checking validation？

### Reproduction steps

-

### Expected vs. actual results

-

### Compiler and operating system

ubuntu20.04 gcc10.3

### Library version

3.11.2

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
You may have to reset the stream after reading from it. That is: does the `parse` work without calling `accept` prior?

**Comment by harcool** [comment]
hey @nlohmann , I tried to reproduce the issue in macOS Monterary, clang version 13.1.6. Parse is working without calling accept. If we call accept before parse. Following error message is coming - "libc++abi: terminating with uncaught exception of type nlohmann::json_abi_v3_11_2::detail::parse_error: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
Abort trap: 6"

**Comment by nlohmann** [comment]
This is expected. You try to read a stream twice which does not work without calling `seekg`.

**Comment by nlohmann** [comment]
This is not a library issue.
