### ISSUE TITLE
Check Drone CI

### ISSUE THREAD

**Issue by nlohmann** [nlohmann/json#3890]
### Description

Drone CI jobs do not finish.

### Reproduction steps

Check any of the latest PRs.

### Expected vs. actual results

Drone CI job completes.

### Minimal code example

```Shell
N/A
```

### Error messages

```Shell
N/A
```

### Compiler and operating system

-

### Library version

develop

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by barcode** [comment]
@nlohmann is it possible to help with this?

**Comment by nlohmann** [comment]
Yes: find out whether the service at Drone is discontinued, and maybe search if there is an alternative CI provider that offers ARM builds.

**Comment by barcode** [comment]
I found something about this in the drone Slack channel:

    it has been a challenge to keep [cloud.drone.io](http://cloud.drone.io/) stable in recent weeks/months, especially for the arm-based builds
    [...]
    this is a known issue at the moment, we have a ticket open with our hosting provider
    currently there is no ETA

I asked for an update and will write here when i a reply.

For other CI providers: it seems Travis is supporting arm64 ([article](https://community.arm.com/arm-community-blogs/b/tools-software-ides-blog/posts/continuous-ci-cd-momentum-for-arm-architecture), [doc](https://docs.travis-ci.com/user/multi-cpu-architectures/#multi-cpu-availability)).

**Comment by barcode** [comment]
@nlohmann If travis is active for this project, i could try to add a travis job building for ARM64.

**Comment by nlohmann** [comment]
We got rid of Travis a while ago (https://github.com/nlohmann/json/issues/3087) as their open source support of 25000 credits is not sufficient for us.

**Comment by barcode** [comment]
OK. I guess the [6k min / month](https://circleci.com/pricing/) of [circleci](https://circleci.com/docs/using-arm/) will not be enough as well...

I will take a look at a few more and put my results [here](https://github.com/barcode/dev-services/tree/main)

**Comment by barcode** [comment]
@nlohmann I found [cirrus-ci](https://cirrus-ci.com/) and did a [small test](https://cirrus-ci.com/task/6086553882066944). The test ran on an arm64 node. For open source projects there is no minute limit. I think the only limit is the number of concurrent jobs.

If you don't see a problem with this ci and enable it for the repo I can add a config as part of my [fix ci PR](https://github.com/nlohmann/json/pull/3906).

**Comment by nlohmann** [comment]
@barcode Awesome!
