### ISSUE TITLE
`modernize-avoid-c-arrays` clang-tidy warning when using `NLOHMANN_JSON_SERIALIZE_ENUM` macro

### ISSUE THREAD

**Issue by alzix** [nlohmann/json#3924]
### Description

clang-tidy emits a warning on a code using NLOHMANN_JSON_SERIALIZE_ENUM,
this requires to to put no-lint comments on the usage code

### Reproduction steps

run clang-tidy on the code using `NLOHMANN_JSON_SERIALIZE_ENUM` macro

### Expected vs. actual results

expected no warnings

### Minimal code example

```Shell
++
enum class Foo {
  kFoo1,
  kFoo2
};
NLOHMANN_JSON_SERIALIZE_ENUM(
    Foo,
    {
        {Foo::kFoo1, "FOO1"},
        {Foo::kFoo2, "FOO2"},
    })
```

### Error messages

```Shell
| Clang-Tidy: Do not declare C-style arrays, use std::array<> instead
```

### Compiler and operating system

Apple clang version 14.0.0, MacOS

### Library version

v3.11.2

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
It's a false positive - we do not use arrays, but only braced initialization. And idea how to fix this?

**Comment by avighnac** [comment]
Sounds like a clang issue though, right?

**Comment by nlohmann** [comment]
I guess. The code surely does not define a C array.

**Comment by alzix** [comment]
how about `static const std::pair<ENUM_TYPE, BasicJsonType> m[] = __VA_ARGS__;` in https://github.com/nlohmann/json/blob/c71ecde505ebf236048a731c81ae8ecaf2b260a8/include/nlohmann/detail/macro_scope.hpp#L212
