### ISSUE TITLE
#pragma GCC diagnostic ignored "-Wdocumentation"

### ISSUE THREAD

**Issue by pavel-pimenov** [nlohmann/json#393]
git - develop

c++ -std=c++11 -O2 -g -Wall -Wextra -D_WITH_SQLITE -Iskein/Optimized_32bit -I/usr/include -I/usr/include/lua5.1 -c /home/dc/src/ptokax-svn/core/DcCommands.cpp -o /home/dc/src/ptokax-svn/obj/DcCommands.o
In file included from /home/dc/src/ptokax-svn/core/DcCommands.cpp:40:0:
/home/dc/src/ptokax-svn/core/../json/json.hpp:76:36: warning: unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]
     #pragma GCC diagnostic ignored "-Wdocumentation"

c++ --version
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.

**Comment by nlohmann** [comment]
Related to #391. I did not know `-Wdocumentation` is a Clang-only flag.

**Comment by nlohmann** [comment]
Fixed the code by only using the pragma when Clang is used.

**Comment by jaredgrubb** [comment]
Thanks for finding and fixing this!
