### ISSUE TITLE
[json.exception.type_error.305] cannot use operator[] with a string argument with array

### ISSUE THREAD

**Issue by wkingnet** [nlohmann/json#3931]
### Description

This is my test: I create a json object, and I want save it to a file, and open it after. Unfortunately, the first step could not be completed. read json object directly is not possible.
```
#include <nlohmann/json.hpp>
#include <exception>
  json j = {
      {"player_id",
        {"addr", 0x011B90C4},
        {"offest", {}},
      },
      {"player_name",
        {"addr", 0x011B90B8},
        {"offest", {0x10,0x20,0x30}},
      }
  };
  cout << j.meta() << endl;
  cout << "j.type_name()=" << j.type_name() << endl;
  try {
    cout << j["player_id"] << endl;
  }
  catch (exception& e){
    cout << e.what() << endl;
  }
```

run the exe will be display a error: [json.exception.type_error.305] cannot use operator[] with a string argument with array

### Reproduction steps

copy code and run
```
#include <nlohmann/json.hpp>
#include <exception>
  json j = {
      {"player_id",
        {"addr", 0x011B90C4},
        {"offest", {}},
      },
      {"player_name",
        {"addr", 0x011B90B8},
        {"offest", {0x10,0x20,0x30}},
      }
  };
  cout << j.meta() << endl;
  cout << "j.type_name()=" << j.type_name() << endl;
  try {

    cout << j["player_id"] << endl;
  }
  catch (exception& e){
    cout << e.what() << endl;
  }
```

### Expected vs. actual results

Expected:
        {"addr", 0x011B90C4},{"offest", {}},

actual results:
```
{"compiler":{"c++":"202002","family":"msvc","version":1934},"copyright":"(C) 2013-2022 Niels Lohmann","name":"JSON for Modern C++","platform":"win32","url":"https://github.com/nlohmann/json","version":{"major":3,"minor":11,"patch":2,"string":"3.11.2"}}
j.type_name()=array
[json.exception.type_error.305] cannot use operator[] with a string argument with array
```

### Error messages

```Shell
[json.exception.type_error.305] cannot use operator[] with a string argument with array
```

### Compiler and operating system

"compiler":{"c++":"202002","family":"msvc","version":1934},"copyright":"(C) 2013-2022 Niels Lohmann","name":"JSON for Modern C++","platform":"win32","url":"https://github.com/nlohmann/json","version":{"major":3,"minor":11,"patch":2,"string":"3.11.2"

### Library version

3.11.2

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
Apparently, you did not create an object, but an array. Please double check that you provide a list of pairs to the constructor, where the first element of each pair is a string.

**Comment by wkingnet** [comment]
> 

sorry, it was my mistake. I forgot a pair of {}. thank you very much for your help!
