### ISSUE TITLE
Clean up badges

### ISSUE THREAD

**Issue by nlohmann** [nlohmann/json#3935]
### Description

- [x] Badge for recently added Cirrus CI is missing (URL: https://api.cirrus-ci.com/github/nlohmann/json.svg, Link: https://cirrus-ci.com/github/nlohmann/json - it should be added
- [x] Badge for lgtm states `no longer available` - it should be removed

**Comment by haadfida** [comment]
may I work on this?

**Comment by nlohmann** [comment]
Sure!
