### ISSUE TITLE
Parse doesnt work

### ISSUE THREAD

**Issue by volkaris** [nlohmann/json#3936]
### Description

Cant parse string or const char*

### Reproduction steps

setlocale(LC_ALL, "Rus");
	using json = nlohmann::json;

	auto q = R"("AUD": {
            "ID": "R01010",
            "NumCode": "036",
            "CharCode": "AUD",
            "Nominal": 1,
            "Name": "Австралийский доллар",
            "Value": 49.6231,
            "Previous": 49.3551
        })";

	string str1 = q;
	size_t start_pos = str1.find("Австралийский доллар");
	str1.replace(start_pos, strlen("Австралийский доллар"), "aus");
	q = str1.c_str();
	cout << q;
	auto j = json::parse(q);

### Expected vs. actual results

Error!!

### Compiler and operating system

windows

### Library version

latest

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
You did not provide the exception message. I bet it has to do with encoding. The library only supports UTF-8. See https://json.nlohmann.me/home/faq/#parse-errors-reading-non-ascii-characters
