### ISSUE TITLE
exit without error message

### ISSUE THREAD

**Issue by tesla-cat** [nlohmann/json#3948]
### Description

- without the try-catch block the code works 
- but after adding that try-catch block, and after sending json data to the websocket server, the program exits without error message

```cpp
void handle_message(uWS::WebSocket<false, true, PerSocketData>* ws,
                    string_view msg, uWS::OpCode code) {
    json data = json::parse(msg);

     try {
        OptimizerInput inp = data.get<OptimizerInput>();
    } catch (const exception& e) {
        cerr << e.what() << '\n';
    }

    ws->send(data.dump(), code);
}
```

### Reproduction steps

- the websocket server can run
- aftering sending json data to it from the frontend, the server exits without an error message.
- everything works without the try-catch part of the code

### Expected vs. actual results

expect to see error message

### Compiler and operating system

windows, Visual Studio 16

### Library version

nlohmann_json/3.11.2

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
Without knowing what any of the called functions do, there is little I can do. Can you provide a stacktrace?

**Comment by tesla-cat** [comment]
- thanks for the quick reply
-  i added this line `std::cout << boost::stacktrace::stacktrace();`, but it still just exits without printing any error message

```cpp
void handle_message(uWS::WebSocket<false, true, PerSocketData>* ws,
                    string_view msg, uWS::OpCode code) {
    json data = json::parse(msg);

    try {
        OptimizerInput inp = data.get<OptimizerInput>();
    } catch (const exception& e) {
        cerr << e.what() << '\n';
        std::cout << boost::stacktrace::stacktrace();
    }

    ws->send(data.dump(), code);
}

```

**Comment by nlohmann** [comment]
Can you set a breakpoint to the line where you call parse and find the last line before the exit?

(This looks like an issue in your setup - the library throws exceptions inherited from `std::exception`, and so far we never saw an issue.

**Comment by tesla-cat** [comment]
the exit is caused by `OptimizerInput inp = data.get<OptimizerInput>();`  because everything works after removing it

**Comment by nlohmann** [comment]
Can you then debug into it? `get` does not throw too many exceptions.
