### ISSUE TITLE
the alphabetic order in the code influence console_output.

### ISSUE THREAD

**Issue by testcheng307** [nlohmann/json#396]
Just compile and run the code,my english is poor ,so please see the attach picture.
![about a alphabetic order bug](https://cloud.githubusercontent.com/assets/24563359/21175554/ddd6e6e2-c21d-11e6-9eb3-4d6b12638d4e.png)

**Comment by nlohmann** [comment]
What do you mean? The keys of the objects are always sorted.

**Comment by nlohmann** [comment]
Can you provide more information?
