### ISSUE TITLE
why I can return tuple as json?

### ISSUE THREAD

**Issue by tesla1060** [nlohmann/json#3961]
### Description

I am wonder why below code can be compiled

```
#include "json.hpp"
#include <iostream>
using json = nlohmann::json;

std::tuple<bool, json> test() {
    json j;
    j["name"]="a";
    return std::make_tuple(true, j);
}

int main() {
    json j;
    j = test();
    std::cout << j.contains("name") << std::endl;
}
```

### Reproduction steps

code supplied description.

### Expected vs. actual results

I am expecting a compile time failure, while the above code can actually compiled and run

### Compiler and operating system

ubuntu 20

### Library version

gcc 9

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
See https://json.nlohmann.me/api/macros/json_use_implicit_conversions/

Can you try to compile with

```cpp
#define JSON_USE_IMPLICIT_CONVERSIONS 0
```
