### ISSUE TITLE
Parsing array error

### ISSUE THREAD

**Issue by gllonch** [nlohmann/json#3968]
### Description

I'm using your library which is working pretty well but I have an small issue.

When I'm trying to parse a array of number, I have a strange error.

### Reproduction steps

string strJson = "[0600,1000,1001,8297]"
json::parse(strJson)

### Expected vs. actual results

Array of 4 numbers.

### Minimal code example

```Shell
If I'm doing this, it's working: 

string strJson = "[600,1000,1001,8297]"
json::parse(strJson)

But if I'm adding a '0' on first number, it's not working:
 
string strJson = "[0600,1000,1001,8297]"
json::parse(strJson) -> Exception.
```

### Compiler and operating system

Microsoft Visual C++ 2022

### Library version

3.11.2

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
Leading zeros are not allowed in JSON.
