### ISSUE TITLE
Possible to speed up json::parse?

### ISSUE THREAD

**Issue by Noitidart** [nlohmann/json#398]
Is it possible for me to give a hint to json::parse so it is faster?

I am receiving a JSON string from stdin. It contains a 1024kb string. Is there any tricks to make parse faster? Right now it takes 4.5 seconds.

Thanks

**Comment by nlohmann** [comment]
Can you provide the concrete example?

**Comment by Noitidart** [comment]
Oh wow SUPER fast reply thank you sir!

I currently do it like this:

    auto payload = json::parse(payload_str);

`payload_str` is a `std::string` sent from javascript  (NativeMessaging for browser extensions). This is the javascript:

     { method:'test', arg:new Uint8Array(new ArrayBuffer(1024*1024)).toString(), cbid:5 }

`arg` is a string of a binary array thats a string.

**Comment by nlohmann** [comment]
Thanks, I shall have a look.

**Comment by gregmarr** [comment]
So `payload_str` is something like this:

    { method:'test', arg: "0,0,0...0,0,0", cbid:5 }

What kind of hint were you thinking to send that would help parse that 1MB string faster?

**Comment by nlohmann** [comment]
I generated a file that fits your description, see [issue398.json.zip](https://github.com/nlohmann/json/files/662162/issue398.json.zip). Then I ran a benchmark (using https://nonius.io) parsing this file. Here is the output:

```
benchmarking parse issue398.json
collecting 1000 samples, 1 iterations each, in estimated 37.623 s
mean: 38.9618 ms, lb 38.8074 ms, ub 39.1166 ms, ci 0.95
std dev: 2.48386 ms, lb 2.38355 ms, ub 2.61042 ms, ci 0.95
found 3 outliers among 1000 samples (0.3%)
variance is severely inflated by outliers
```

The mean parsing time is 38.96 milliseconds. I have no idea why parsing takes 4.5 seconds in your case.

How does your input file look like? How does your parsing code look like? What compiler flags are you using?

**Comment by Noitidart** [comment]
Thanks very very much for willing to discuss this with me, as it looks like it's a personal issue on my end!

I am new to wirting C++. I am using Visual Studio 2015.

Here is image of my code - http://i.imgur.com/OCmdZOC.png

(side note: i dont know why it underlines json::parse, but it doesnt prevent compiling - on hover it shows this message - http://i.imgur.com/OhSYpnr.png )


My compile flags I'm not sure, but I looked up how to see compile configuration on the net and it led me to this dialog box - http://i.imgur.com/FXv82EJ.png

Sincerest thanks!

**Comment by Noitidart** [comment]
@gregmarr yep that's correct it looks like that. I'm not sure, I was just trying my luck to ask haha.

**Comment by whackashoe** [comment]
@Noitidart can you try compiling as release rather than debug

**Comment by Noitidart** [comment]
Thanks @whackashoe testing right now! :)

**Comment by gregmarr** [comment]
Debug visual studio STL is SIGNIFICANTLY slower than release due to all the extra checking that happens.

**Comment by Noitidart** [comment]
Oh wow! You were right it is now 49ms if I do it with "Release". My sincerest thanks @nlohmann,  @whackashoe, and @gregmarr!!!

**Comment by whackashoe** [comment]
Glad it worked! Have a good one.

**Comment by Noitidart** [comment]
Hi folks, you guys were really helpful thank you! I have been working with json.hpp for about a month now and have some questions. Is there a place I can post this? I searched the issues and didn't find similar. I don't want to clog up the issues forum, I'm not sure if it's ok with you all. Is there somewhere you can recommend I can ask questions please?

**Comment by nlohmann** [comment]
@Noitidart Just open a new issue and ask. :)

**Comment by Noitidart** [comment]
You are too too fast haha thank you very much for being so friendly all of you to new comers!

**Comment by balannarcis96** [comment]
Is there a workaround for this? , i'm loading ~100mb of JSON and it takes about 2-3 minutes to parse in debug mode.

**Comment by nlohmann** [comment]
How fast is it in release mode?

**Comment by balannarcis96** [comment]
In release mode is as expected, very fast, but my main concern is debug mode, as the json data my program parses is big and can't be reduced very easily.
