### ISSUE TITLE
Can't support convert the type?      std::string json_str = R"({"value": "3.1415"})"; float value = j["value"].get<float>();  

### ISSUE THREAD

**Issue by TerryHoCQ** [nlohmann/json#3984]
### Description

#include <iostream>
#include <string>
#include <nlohmann/json.hpp>

using json = nlohmann::json;

int main() {
    std::string json_str = R"({"value": "3.1415"})";
    json j = json::parse(json_str);

    float value = j["value"].get<float>();
    std::cout << "Value: " << value << std::endl;

    std::string float_str = "3.1415926";
    float float_num = std::stof(float_str);
    std::cout << "Float: " << float_num << std::endl;

    return 0;
}

### Reproduction steps

#include <iostream>
#include <string>
#include <nlohmann/json.hpp>

using json = nlohmann::json;

int main() {
    std::string json_str = R"({"value": "3.1415"})";
    json j = json::parse(json_str);

    float value = j["value"].get<float>();
    std::cout << "Value: " << value << std::endl;

    std::string float_str = "3.1415926";
    float float_num = std::stof(float_str);
    std::cout << "Float: " << float_num << std::endl;

    return 0;
}

### Expected vs. actual results

#include <iostream>
#include <string>
#include <nlohmann/json.hpp>

using json = nlohmann::json;

int main() {
    std::string json_str = R"({"value": "3.1415"})";
    json j = json::parse(json_str);

    float value = j["value"].get<float>();
    std::cout << "Value: " << value << std::endl;

    std::string float_str = "3.1415926";
    float float_num = std::stof(float_str);
    std::cout << "Float: " << float_num << std::endl;

    return 0;
}

### Minimal code example

```Shell
#include <iostream>
#include <string>
#include <nlohmann/json.hpp>

using json = nlohmann::json;

int main() {
    std::string json_str = R"({"value": "3.1415"})";
    json j = json::parse(json_str);

    float value = j["value"].get<float>();
    std::cout << "Value: " << value << std::endl;

    std::string float_str = "3.1415926";
    float float_num = std::stof(float_str);
    std::cout << "Float: " << float_num << std::endl;

    return 0;
}
```

### Compiler and operating system

vs20019+WIN10

### Library version

v3.11.2

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by TerryHoCQ** [comment]
> ```shell
> float value = j["value"].get<float>();
> ```

float value = j["value"].get<float>();  //this will throw exception, the original type in JSON TXT R"({"value": **"3.1415"**})" is string, we try to convert string to a float.

**Comment by nlohmann** [comment]
The library does not provide string-to-float conversion.
