### ISSUE TITLE
json::parse of std::string being underlined by Visual Studio

### ISSUE THREAD

**Issue by Noitidart** [nlohmann/json#402]
This was just a nit pick. I don't know why but it keeps underlining my json::parse from strings. I use json::parse on varaibles like this:

```
	void listenMain(std::string payload_str) {
            json payload = json::parse(payload_str);
```

This compiles, but it gets underlined by visual studio like this:

![](http://i.imgur.com/ql3gbxV.png)

Do you know why this is? It works fine. Is there a way to properly use json::parse with variables?

Thank you!

**Comment by gregmarr** [comment]
The compiler used by Intellisense is not the same as the compiler used to build the program.  The Intellisense compiler doesn't always have all the information it needs to figure out whether something is valid or not, unfortunately.  As long as the program compiles, you'd need to report this Intellisense failure to Microsoft.

**Comment by Noitidart** [comment]
Ah interesting @gregmarr thanks for sharing that! I'll do some research and see if I can fix it. Will report back what I find. :)

**Comment by nlohmann** [comment]
Thanks @Noitidart. I shall close this issue in the meantime as there is nothing we can do about it.

**Comment by Noitidart** [comment]
Makes total sense thanks for telling me before closing. :)

**Comment by Noitidart** [comment]
Hey all, I found a weird fix for this silly issue. If I do .c_str() it doesnt underline it. It makes no sense to me. Does this make sense to anyone?

      json payload = json::parse(payload_str.c_str());

**Comment by nlohmann** [comment]
@Noitidart Thanks for checking back!
