### ISSUE TITLE
Missing requirement on `plantuml` binary package

### ISSUE THREAD

**Issue by schuylermartin45** [nlohmann/json#4026]
### Description

Apologies that this is coming in as a bug. I cannot seem to select this as a documentation issue. I assume someone else has the ability to change the type after submission.

As outlined in the discussion coming from #3942 and https://github.com/nlohmann/json/pull/4024, as someone who is trying to contribute to the documentation for the first time, it is not clear that `plantuml` is a depedency required to run the documentation engine.

In order for me to run the `mkdocs` instance for the first time, I needed to `brew install plantuml` on my Mac or `sudo apt install plantuml` on my Ubuntu machine. The [README](https://github.com/nlohmann/json/tree/develop/docs) discussing how to run the `mkdocs` project does not mention this requirement.

I see this as a documentation issue first, but arguably we could add a `make` directive to or have some other mechanism to ensure the required dependency is installed to the system attempting to run the documentation server.

### Reproduction steps

1. Fork and Clone this project for the first time
2. Attempt to run the `make install_venv serve -C docs/mkdocs` command, as described in the `docs/README.md` file
3. Expect this to fail if you do not have the `plantuml` MacOS/Debian/etc package installed previously on your system

### Expected vs. actual results

If the docs suggest that all I need to do is run a `make` command to start the documentation server, I would expect that is all I need to do as a new contributor to the project. This caused some confusion and a potential waste of everyone's time trying to debug something minor.

### Compiler and operating system

MacOS/Linux

### Library version

development

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by schuylermartin45** [comment]
And shout out to @JeanChristopheMorinPerso for helping me figure this issue out.

**Comment by nlohmann** [comment]
I think this can be fixed by adding a remark to the documentation.
