### ISSUE TITLE
Improve wording of parse_error exception

### ISSUE THREAD

**Issue by nlohmann** [nlohmann/json#4037]
@nlohmann This exact error happens enough that I'm wondering if there should be a more specific error message for it, such as "Error attempting to parse an empty input, check that your input string or stream contains the expected JSON."

_Originally posted by @gregmarr in https://github.com/nlohmann/json/issues/4028#issuecomment-1540263739_

**Comment by haseeb-xd** [comment]
I would like to work on this, Can you please tell me where can I add new parse_error exception message. 
Thanks

**Comment by nlohmann** [comment]
Please check the code where `parse_error` is thrown.

**Comment by theevilone45** [comment]
Hey @nlohmann, can I do it? 😊

**Comment by nlohmann** [comment]
> Hey @nlohmann, can I do it? 😊

Sure!

**Comment by st17931** [comment]
Is it done ?? Or i can look into it? @nlohmann

**Comment by nlohmann** [comment]
See #4073. It's not done yet.

**Comment by colbychaskell** [comment]
Looks like the work on this fell through... I can work on this if needed.
