### ISSUE TITLE
Overloaded += to add objects to an array makes no sense?

### ISSUE THREAD

**Issue by louwers** [nlohmann/json#404]
Hello there!

I was wondering why `+=` was overloaded to add an item to an array. `a += b` should always be the same as `a = a + b` in my opinion, but of course `+` isn't overloaded because that would not make any sense (as everyone rightfully expects both operands to be the same type when using `+`).

I'd like to hear your thoughts on this.

**Comment by nlohmann** [comment]
The syntax was borrowed from Python.

**Comment by nlohmann** [comment]
Any other opinions on this?
