### ISSUE TITLE
how about open a new repository for header only version？

### ISSUE THREAD

**Issue by qcmc17** [nlohmann/json#4060]
### Description

The disk space occupied by the repository  so far has reached 176mb, a horrible size for a json library. I especially need a separate code repository with only header files when I use submodle to manage my code, thanks.

### Reproduction steps

nope

### Expected vs. actual results

nope

### Minimal code example

```Shell
nope
```

### Error messages

```Shell
nope
```

### Compiler and operating system

centos

### Library version

3.11.2

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by gregmarr** [comment]
Have you looked at this thread https://github.com/nlohmann/json/issues/2088#issuecomment-624490510 and specifically shallow submodules: https://stackoverflow.com/questions/2144406/how-to-make-shallow-git-submodules
