### ISSUE TITLE
error: building nlohmann-json:arm64-osx failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by DuckyDuckerson** [nlohmann/json#4091]
### Description

I can not install nlohmann-json

### Reproduction steps

~vcpkg install nlohmann-json:arm64-osx

### Expected vs. actual results

I expected it to install but all i get is the error

error: building nlohmann-json:arm64-osx failed with: BUILD_FAILED

### Error messages

```Shell
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:163 (message):
  Could not find pkg-config.  Please install it via your package manager:

      brew install pkg-config
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:203 (vcpkg_find_acquire_program)
  ports/nlohmann-json/portfile.cmake:28 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:147 (include)


error: building nlohmann-json:arm64-osx failed with: BUILD_FAILED
Elapsed time to handle nlohmann-json:arm64-osx: 641 ms
```

### Compiler and operating system

mac os 13.4.1 (c) (22F770820d)

### Library version

installing with vcpkg

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
Please raise this issue here: https://github.com/Microsoft/vcpkg/tree/master/ports/nlohmann-json
