### ISSUE TITLE
Deprecation warning about std::char_traits<unsigned char>

### ISSUE THREAD

**Issue by nlohmann** [nlohmann/json#4163]
### Description

When parsing a binary format from a `std::vector<std::uint8_t>`, there is a deprecation warning:

<img width="997" alt="Screenshot 2023-09-24 at 11 36 41" src="https://github.com/nlohmann/json/assets/159488/725f5259-a30f-4817-9301-862861822b0e">

### Reproduction steps

Call `nlohmann::json::from_bjdata` on a `std::vector<std::uint8_t>`.

### Expected vs. actual results

Expected: no deprecation warning.

Actual:

<img width="997" alt="Screenshot 2023-09-24 at 11 36 41" src="https://github.com/nlohmann/json/assets/159488/e48a23e9-69c4-4a14-bbb8-750486dbce58">

### Minimal code example

```Shell
std::vector<std::uint8_t> vec {{ 0x7b, 0x55, 0x0b }};
nlohmann::json j = nlohmann::json::from_bjdata(vec);
```

### Error messages

```Shell
See screenshot above.
```

### Compiler and operating system

Apple clang version 15.0.0 (clang-1500.0.40.1)

### Library version

develop

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by colbychaskell** [comment]
@nlohmann I can start working on this

**Comment by nlohmann** [comment]
Sure!

**Comment by perryHV** [comment]
Hii @nlohmann  I want to work on this issue please assign me.

**Comment by nlohmann** [comment]
> Hii @nlohmann I want to work on this issue please assign me.

@colbychaskell is already working on this.

**Comment by AbuDarda25** [comment]
please assign this to me .
I will solve this issue in two days.

**Comment by nlohmann** [comment]
Go ahead.

**Comment by juwalter** [comment]
I have also been running into this. did you get a chance to work on this @AbuDarda25 @colbychaskell ?

**Comment by kleuter** [comment]
Very annoying indeed:
<img width="1832" alt="Screenshot 2023-11-13 at 12 22 12" src="https://github.com/nlohmann/json/assets/2600624/6afa1855-1097-495e-8621-c25790a5efa8">

**Comment by gregmarr** [comment]
See #4179 for a potential fix.
