### ISSUE TITLE
Initializing `json` by direct initialization and copy initialization invokes different constructors

### ISSUE THREAD

**Issue by FeignClaims** [nlohmann/json#4174]
### Description

- [direct initialization demo](https://godbolt.org/z/cbjfEW1Wj)

  ```cpp
  #include <iostream>
  #include <ostream>
  
  #include <nlohmann/json.hpp>
  
  auto main() -> int {
    std::map<std::string, std::string> map{{"key", "val"}, {"key2", "val2"}};
    nlohmann::json json{map};
    std::cout << json << '\n';  // output: [{"key":"val","key2":"val2"}]
    map = json;                 // exception: [json.exception.type_error.302] type must be object, but is array
  }
  ```

- [copy initialization demo](https://godbolt.org/z/e6Pc1aTs7)

  ```cpp
  #include <iostream>
  #include <ostream>
  
  #include <nlohmann/json.hpp>
  
  auto main() -> int {
    std::map<std::string, std::string> map{{"key", "val"}, {"key2", "val2"}};
    nlohmann::json json(map);
    std::cout << json << '\n';  // output: {"key":"val","key2":"val2"}
    map = json;                 // ok
  }
  ```

I think this behaviour is easy to make mistakes, so probably not an intentional design.

### Reproduction steps

refer to description

### Expected vs. actual results

The direct initialization code should behave as the same as the copy initialization one, which enables converting `json` back to `std::map`.

### Compiler and operating system

x86-64 clang (trunk), x86-64 gcc (trunk)

### Library version

35c0b3e54ce99716bf2a6bb6bdbd346f3e6d398b

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by gregmarr** [comment]
This is the very first item in the FAQ.  https://json.nlohmann.me/home/faq/

**Comment by FeignClaims** [comment]
I see, only searched in issue, sorry for the bother
