### ISSUE TITLE
why a single-object json file appears in an array

### ISSUE THREAD

**Issue by Corgile** [nlohmann/json#4183]
### Description

Unexpected '[' and ']', see pic:

![image](https://github.com/nlohmann/json/assets/48396880/cecf3a64-f045-46ed-9262-8039e66a1019)

### Reproduction steps

minimal code to reproduce:

```cpp

static nlohmann::json parseProfile(std::string profile) {
	std::ifstream file(profile);
	if (not file.is_open()) {
		INFO(RED("无法打开文件: "), profile);
		exit(EXIT_FAILURE);
	}
	return nlohmann::json::parse(file);
}
int main() {
	nlohmann::json profile{parseProfile("/home/brian/Projects/sqlite3-demo/profiles/demo.json")};

	std::cout << profile.dump(2);
}
```

### Expected vs. actual results

expected:
```json
{
  "one": 1,
  "two": "2",
  "tree": [
    1,2,3
  ]
}
```

actual:

```json
[
  {
    "one": 1,
    "tree": [
      1,
      2,
      3
    ],
    "two": "2"
  }
]
```

### Compiler and operating system

ubuntu 2204

### Library version

v3.11.2

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [x] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by Corgile** [comment]
if that's how it actually works, please explain why

**Comment by nlohmann** [comment]
See https://json.nlohmann.me/home/faq/#brace-initialization-yields-arrays
