### ISSUE TITLE
README.md overuses `template` keyword before `get` function

### ISSUE THREAD

**Issue by davidstone** [nlohmann/json#4205]
### Description

The documentation contains 18 matches for `template get`. All of them should just be `get` except for the line `value = j.template get<T>(); // oops!` which is correct as in.

### Reproduction steps

Read the readme

### Expected vs. actual results

Should not have `template` keyword

### Compiler and operating system

N/A

### Library version

develop current

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
IIRC there were compilers with issues without the template keyword, so we decided to add it just in case. If you have a concrete example, feel free to open a PR.

**Comment by nlohmann** [comment]
See #4038 and #4039.
