### ISSUE TITLE
Get an error - JSON pointer must be empty or begin with '/'

### ISSUE THREAD

**Issue by ORESoftware** [nlohmann/json#421]
I am a C/C++ newb so bear with me

I get this error:

```
../json.hpp:11286:87: error: exception handling disabled, use -fexceptions to enable
                 throw std::domain_error("JSON pointer must be empty or begin with '/'");
```

I am trying to create Node.js Addon - I included this project like so:

`#include "json.hpp"`

Here is the binding.gyp file I used:

```
{
  "targets": [
    {
      "target_name": "hello",
      "sources": [ "hello.cpp" ],
      "include_dirs": [
        "<!(node -e \"require('nan')\")"
      ],
      "cflags": [
        "-std=c++11"
      ]
    }
  ]
}

```
I think that's where I need to add the std=c++11 call

Any idea what the error might be about? Sorry don't know how to debug this at all

**Comment by TurpentineDistillery** [comment]
See https://github.com/nodejs/node-gyp/issues/17

**Comment by ORESoftware** [comment]
@TurpentineDistillery thanks that seemed to do the trick!
