### ISSUE TITLE
Exception thrown when dumping utf-8 characters when using std::string

### ISSUE THREAD

**Issue by felipegodias** [nlohmann/json#4213]
### Description

Calling dump when having a UTF-8 non ASCII character throws an exception.

### Reproduction steps

1. Create an string with "Á" value.
2. Insert it as a value in the json.
3. Call dump method.
4. Exception is thrown.

### Expected vs. actual results

An exception should not be thrown, the dump should contain the character without issue.

### Minimal code example

```Shell
std::string s = "Á";
    nlohmann::json j;
    j["value"] = s;

    try
    {
        std::string json_out = j.dump();
        std::cout << json_out << std::endl;
    }
    catch (const std::exception& e)
    {
        std::cerr << e.what() << std::endl;
    }
```

### Error messages

```Shell
[json.exception.type_error.316] invalid UTF-8 byte at index 0: 0xC1
```

### Compiler and operating system

MSVC version '19.38.33130.0' Windows 11

### Library version

3.11.2

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by gregmarr** [comment]
Especially with MSVC, I don't think that literal string is UTF-8 encoded.

**Comment by nlohmann** [comment]
@felipegodias Can you please provide more information. In particular, please double-check your input is actually UTF-8 encoded.
