### ISSUE TITLE
Implicit conversion from array to object

### ISSUE THREAD

**Issue by hxingpax** [nlohmann/json#425]
In the README I saw:
```cpp
// a way to express an _array_ of key/value pairs [["currency", "USD"], ["value", 42.99]]
json array_not_object = { json::array({"currency", "USD"}), json::array({"value", 42.99}) };
```

But  on my Ubuntu 1604 with gcc 5.4 I got `"{"currency":"USD","value":42.99}"`

After I change "value" into a numeric, e.g.
```cpp
json array_not_object = { json::array({"currency", "USD"}), json::array({4, 42.99}) };
```
I got `"[["currency","USD"],[4,42.99]]"`

Is this a bug? or feature?

**Comment by nlohmann** [comment]
You may want to use `array` as outmost function:

```cpp
json array_not_object2 = json::array({{"currency", "USD"}, {"value", 42.99}});
std::cerr << array_not_object2 << std::endl;
```

yielding `[["currency","USD"],["value",42.99]]`.

`array` is just a means to tell the library not to try to convert a list of pairs to an object even though it could.
