### ISSUE TITLE
is it possible merge two json object

### ISSUE THREAD

**Issue by itviewer** [nlohmann/json#428]
some function like this 
json1.join(json2) or
json1.merge(json2) or
json1 += json2

**Comment by nlohmann** [comment]
This is an interesting question. Currently, there is no `insert(InputIt first, InputIt last)` function such as `std::map::insert`.

**Comment by nlohmann** [comment]
(I should definitely have another look at all the overloads of `insert` of the STL containers. For instance, `std::map::iterator insert( const_iterator hint, const value_type& value );` exists, but an `insert` function with the same signature is currently only allowed for arrays.)

**Comment by andnp** [comment]
I have also needed this type of functionality. For the time being until this is closed, I have been using this code which modifies the json object in place.

One thing to consider is the desired behavior when `j1` and `j2` have matching keys. In this case `j1` is over-written by values in `j2`.

Hopefully this helps for now.

`void extendJson(json &j1, const json &j2) {
    for (const auto &j : json::iterator_wrapper(j2)) {
        j1[j.key()] = j.value();
    }
}`

**Comment by nlohmann** [comment]
Thanks for the hint. I shall have a look at the `insert` functions of the STL containers and propose an extension here.

**Comment by nlohmann** [comment]
Here is a proposal for an insert function that takes an iterator range and can merge an object into another: https://github.com/nlohmann/json/commit/97a25de93866fc92a32e44c1856217dd6327f212. Feedback very appreciated!

**Comment by AraHaan** [comment]
Well in python it interprets json data as an dict and then it could ``append`` (or ``insert``) . In that case append is an alias of insert that would append to the end of the json, but insert would allow you to specify where to insert entries at. Maybe this library could copy some of that logic even though it would not be an dict.

**Comment by nlohmann** [comment]
@AraHaan What exactly do you propose? We have several overloads for push_back and insert. And Python only interprets JSON objects as dict. Arrays are mapped to lists.

**Comment by nlohmann** [comment]
@AraHaan I fear that overload of `operator>>` would be very unintuitive for C++ programmers.

**Comment by itviewer** [comment]
Thanks，It's good for me！

**Comment by nlohmann** [comment]
Merged with 4b316ec52841de8e66f7592b917d5b8d03404272.

**Comment by mlund** [comment]
Great this has been added; #252 addresses a similar issue and I have used

```cpp
json merge( const json &a, const json &b )
{
    json result = a.flatten();
    json tmp = b.flatten();
    for ( auto it = tmp.begin(); it != tmp.end(); ++it )
        result[it.key()] = it.value();
    return result.unflatten();
}
```

I found the scenario below slightly counter-intuitive using the new approach,

```cpp
json j1 = { {"a",1} };
json j2 = { {"a",2} };
j1.insert(j2.begin(), j2.end()); // --> a=1
```

But perhaps this is also the behaviour of maps?

**Comment by mlund** [comment]
`std::map::insert` does not overwrite either.

**Comment by nlohmann** [comment]
We use std::map::insert internally to provide the least surprising behavior. I also would have needed to look up the behavior in case of a duplicate.

**Comment by mlund** [comment]
That makes sense. I think the solution is simply to pay attention order when merging,
```cpp
std::map<int, int> goodKeys;
std::map<int, int> betterKeys;
betterKeys.insert(goodKeys.begin(), goodKeys.end());
```
Thanks!
