### ISSUE TITLE
Simple example with nlohmann::ordered_json doesn't compile

### ISSUE THREAD

**Issue by patrikhuber** [nlohmann/json#4282]
### Description

Hi,

I wanted to write a json file where the order in the json file is the same as the order of the member variables of my struct - so after some googling, I found `nlohmann::ordered_json`, and wanted to try it out. However a simple example doesn't seem to work (I'm on the latest nlohmann::json version).

My apologies if I'm just overlooking something or making some stupid mistake.

### Reproduction steps

See code.

### Expected vs. actual results

I would have expected the code to compile.

### Minimal code example

```Shell
#include "nlohmann/json.hpp"

struct MyStruct
{
    bool n;
};

NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(MyStruct, n)

int main()
{
    MyStruct s;
    nlohmann::json j = s; // compiles
    nlohmann::ordered_json k = s; // compiler error
}
```
```


### Error messages

```Shell
See https://godbolt.org/z/6bEvr5ezn. I'm on MSVC (latest) but compiler explorer says the error occurs on gcc-13.2 too.
```

### Compiler and operating system

MSVC (latest) / gcc-13.2

### Library version

latest

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
See https://json.nlohmann.me/api/macros/nlohmann_define_type_intrusive/ implementation limits.

**Comment by patrikhuber** [comment]
Ah thank you for the docs link, sorry I haven't seen that. I guess we can close this then!
