### ISSUE TITLE
create json instance from raw json (unsigned char*)

### ISSUE THREAD

**Issue by CheyenneForbes** [nlohmann/json#431]
I cant get nor set values if I try :
```cpp
basic_ostream BOS = get_json_from_server(); // the json response from a server
json BOS_json = BOS;
```
If I am doing something wrong, whats the right way to create a json instance from raw json received from a webserver as basic_ostream?

**Comment by CheyenneForbes** [comment]
Can anyone help me?

**Comment by gregmarr** [comment]
You need to have an `istream`, not an `ostream`.

**Comment by CheyenneForbes** [comment]
What can I do if the http client I am using returns the response body as a "basic_ostream"?

**Comment by gregmarr** [comment]
That seems to be an odd thing for it to return.  What client are you using?

**Comment by CheyenneForbes** [comment]
it was made by a friend, I was reading wrong, it actually returns "unsigned char*" and not "basic_ostream", my apologies.

but it does work still, how can I create a nlohmann::json instance from json (not Serialized) returned from a server?

**Comment by gregmarr** [comment]
`json::parse()`

**Comment by CheyenneForbes** [comment]
that gives "Segmentation fault"

**Comment by gregmarr** [comment]
Where is the segmentation fault (stack trace)?  It could be a problem with the string itself.  Do you get the same fault if you use `strlen()` on the string?

**Comment by nlohmann** [comment]
@CheyenneForbes As @gregmarr said, the parse function can handle `char *`. Can you please add more precise description of your errors?

**Comment by nlohmann** [comment]
@CheyenneForbes Any update?

**Comment by CheyenneForbes** [comment]
Hey, sorry for the delayed response, the client was actually sending a POST request instead of a GET request so the json instance was actually "empty bytes" when I was trying to add/get data, I thought the issue was with the json instance because when I opened the link in the browser it worked. I recommend that anyone using the json header file and plan to receive the json data from "outside" should do so in a try{}catch(){} block when application crashes due to "empty" data arent "acceptable", for example when being used in a web server

**Comment by nlohmann** [comment]
Thanks for the quick response!
