### ISSUE TITLE
How to add json objects to a map?

### ISSUE THREAD

**Issue by davidshen84** [nlohmann/json#432]
I have an array of json objects.

    ［{id: 1...},
         {id: 2...}
         ....
      ]

I want to put each of them into a map<string, ?> for easy look up.

But I have no idea what to use for **?**.

**Comment by nlohmann** [comment]
That entirely depends on your stored JSON objects. If all object values are integers, you can use `std::map<std::string, int>` - but once you are not sure, you need to create a container which is basically `basic_json`.

**Comment by davidshen84** [comment]
No, the json object is not a scalar value, but a complex one, and I have to
store all of them.

I tried `basic_json`, but I got error saying something like template
instantiate not defined.

Regards,
David

**Comment by nlohmann** [comment]
Yes, you need to fill the template parameters - can you try `json`?

**Comment by davidshen84** [comment]
Of course I have tried `json`. How can I fill the template parameters?

**Comment by nlohmann** [comment]
You do not need to fill parameters if you use `json`- it is just a specialization for `basic_json`. Can you please provide a detailed error message?

**Comment by davidshen84** [comment]
Ok, `map<string, json>` works. Previously, I invoked the `.insert` method
wrong, and it gives me an ambiguous error message which lead me to think
that my declaration were wrong.

Thanks,
David
