### ISSUE TITLE
Wrong function name in documentation example

### ISSUE THREAD

**Issue by anderay** [nlohmann/json#4334]
### Description

Should be "from_json(...)" instead "to_json(...)"

### Reproduction steps

Read the doc with understanding

### Expected vs. actual results

Proper example

### Compiler and operating system

N/A

### Library version

N/A

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
Where exactly in the docs?

**Comment by anderay** [comment]
https://github.com/nlohmann/json/blob/199dea11b17c533721b26249e2dcaee6ca1d51d3/docs/mkdocs/docs/features/arbitrary_types.md?plain=1#L268
