### ISSUE TITLE
natvis not updated to 3.11.3

### ISSUE THREAD

**Issue by RomanKhv** [nlohmann/json#4340]
### Description

In version 3.11.3 the underlying namespace seems to be `nlohmann::json_abi_v3_11_3`.
But nlohmann_json.natvis is still written for `nlohmann::json_abi_v3_11_2`.

### Reproduction steps

- Create sample project in Visual Studio.
- Add supplied nlohmann_json.natvis visuzliazer (https://github.com/nlohmann/json/blob/develop/nlohmann_json.natvis).
- Write some basic intialization for json object.
- Run in Debug mode and stop after initilization

### Expected vs. actual results

In VS Debugger Watch window view for json object is not pretty-printed (visualizer is not applied)

### Compiler and operating system

Visual Studio

### Library version

3.11.3

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by gregmarr** [comment]
If you have Python installed, you can update it yourself using https://github.com/nlohmann/json/blob/master/tools/generate_natvis/generate_natvis.py

@nlohmann I guess executing this script should be added to the version update process.
