### ISSUE TITLE
[json.exception.parse_error.101] parse error at line 1, column 4520: syntax error while parsing value - invalid string: forbidden character after backslash; last read: '".\?

### ISSUE THREAD

**Issue by 181404010226** [nlohmann/json#4352]
### Description

I encountered an error while trying to load the JSON shown below. The error occurred at the position highlighted in blue.
![image](https://github.com/nlohmann/json/assets/108257182/0e542f1c-11d8-4775-9059-44671334f1c2)
The json file:
[tileset.json](https://github.com/nlohmann/json/files/15037044/tileset.json)
This is a 3D Tiles project where I convert strings to UTF-8 to ensure JSON exports correctly. Without this conversion, I encounter an error labeled "invalid UTF-8 byte at index." The image below shows the problematic string in debug mode.
![image](https://github.com/nlohmann/json/assets/108257182/0e53dc6a-1614-4dd8-9090-a4854e081fdf)

### Reproduction steps

when load the json file it happened.

### Expected vs. actual results

I expected it successed loaded.

### Minimal code example

```Shell
json childJson;  
try {
    file >> childJson;
}
catch (const json::parse_error& e) {
    std::cerr << "\033[1;31mERROR!\033[0m JSON parse error in file " << entry.path() << ": " << e.what() << std::endl;
    file.close();
    return; // 中断程序
}
file.close();
```

### Error messages

```Shell
ERROR! JSON parse error in file "C:\\Users\\Administrator\\Desktop\\Data\\temp\\开元通宝及广场\\tileset.json": [json.exception.parse_error.101] parse error at line 1, column 4520: syntax error while parsing value - invalid string: forbidden character after backslash; last read: '".\?
```

### Compiler and operating system

Microsoft Visual C++ 2022,windows10

### Library version

3.10.4

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by Nevermore1994** [comment]
I think the string ".\开元通宝及广场" itself does not comply with the JSON specification. When exported, it should be ".\\\开元通宝及广场" to comply with the specification.

**Comment by nlohmann** [comment]
The error message states the reason: after a backslash, only a few characters are allowed:

![](https://www.json.org/img/string.png)
