### ISSUE TITLE
add `reserve` function for array to reserve memory before adding json values into it

### ISSUE THREAD

**Issue by fnc12** [nlohmann/json#436]
`std::vector` has a very useful `reserve` function that is used to preallocate memory for future `push_back`s. It reduces `push_back` time in case if a number of items is high. So it would be useful to add this function to `basic_json` for array `reserve`

**Comment by gregmarr** [comment]
You can currently do this manually using this function:
```/// get a pointer to the value (array)
    array_t* get_impl_ptr(array_t* /*unused*/) noexcept
    {
        return is_array() ? m_value.array : nullptr;
    }```

**Comment by fnc12** [comment]
no, `get_impl_ptr` is private

**Comment by gregmarr** [comment]
Oh, sorry, I thought these had been added as public.  Maybe I was thinking of a request that never went through.

**Comment by nlohmann** [comment]
There is `get_ptr`.

**Comment by fnc12** [comment]
Thanks.
