### ISSUE TITLE
Can't use nlohmann on Linux

### ISSUE THREAD

**Issue by TomyFrank** [nlohmann/json#4363]
### Description

I've cloned the repo and tried to use it in a simple C++ app but it produces an error. 

### Reproduction steps

After cloning the repo, moved the `json` folder in my project directory then included `json.hpp` it got the error:
 ```
 fatal error: nlohmann/detail/json_custom_base_class.hpp: No such file or directory
   49 | #include <nlohmann/detail/json_custom_base_class.hpp>
```

### Expected vs. actual results

I expected the string `{"happy": true,"pi": 3.141}` on Terminal 

### Minimal code example

```Shell
#include <iostream>
#include <string>
#include "json/include/nlohmann/json.hpp"

  int main() {
      auto j = R"(
     {
      "happy": true,
      "pi": 3.141
     }
    )"_json;
    auto data = j.dump();
    std::cout << data << '\n';
    return 0;
}
```

### Error messages

```Shell
fatal error: nlohmann/detail/json_custom_base_class.hpp: No such file or directory
   49 | #include <nlohmann/detail/json_custom_base_class.hpp
```

### Compiler and operating system

Linux GCC

### Library version

version 3

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
You need to properly configure the library search path to the `json/include` folder and then use `#include <nlohmann/json.hpp>`.

**Comment by TomyFrank** [comment]
You have said it's a header-only library. so inclduing that would be enough useually but it's not. 
How to properly configure the library search path to the json/include?

**Comment by nlohmann** [comment]
You did not use the single header version which is in the `single_include` folder. Otherwise, follow https://github.com/nlohmann/json?tab=readme-ov-file#integration.

**Comment by TomyFrank** [comment]
The `single_include` folder doesn't exist in the repo folder so I downloaded both `json` and `json_fwd` headers in the project directory and changed the code:
```
#include <iostream>
#include "json.hpp"
#include "json_fwd.hpp"

  int main() {
      auto j = R"(
     {
      "happy": true,
      "pi": 3.141
     }
    )"_json;
    auto data = j.dump();
    std::cout << data << '\n';
    return 0;
}
```
Error:
```
 json.hpp:34:10: fatal error: nlohmann/adl_serializer.hpp: No such file or directory
   34 | #include <nlohmann/adl_serializer.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by nlohmann** [comment]
- You wrote that you cloned the repo, so there should be a `single_include` folder. Please check.
- If you want to use the files in the `include` folder, then just including `json.hpp` or `json_fwd.hpp` (don't include both, you probably only need `json.hpp`), then you must set your include path.

**Comment by TomyFrank** [comment]
Downloaded the ZIP and inslcued `json.hpp` and it runs. Thanks. 
So the easiest way to use nlohmann-json is this way yeah?

**Comment by nlohmann** [comment]
Good that you managed it.
