### ISSUE TITLE
Clone is long due to large history

### ISSUE THREAD

**Issue by Nir-Az** [nlohmann/json#4370]
### Description

json repo history is very big.
CMake ExternalProject_Add does not support shallow clone of a specific commit, that makes us work hard to minimize the clone part that happens on build step.

I suggest to use git tools to reduce history size
W/O history repo is ~ 7 [MB]
with history it's ~ 185 [MB]

### Reproduction steps

![image](https://github.com/nlohmann/json/assets/64067618/a6eac960-127e-4880-be03-a31bcd5496c3)

### Expected vs. actual results

Here how it looks w/o history
![image](https://github.com/nlohmann/json/assets/64067618/77360fca-77c8-4526-a5e6-34f72b210289)

### Error messages

```Shell
Clone step occasionally fail on timeout
```

### Compiler and operating system

Windows / Linux

### Library version

3.11.3 but also latest

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
Use the .xz archives instead.

**Comment by Nir-Az** [comment]
That an option yes.
Managed WA it this way: https://github.com/IntelRealSense/librealsense/pull/12914/files

But releases are not git source controlled and may be broken in the future, if you rename it in the future my link will be broken right?

reducing the history is a better long run approach IMO.

Thoughts?

**Comment by nlohmann** [comment]
I had this discussions a while ago. I will not change this repository's history. If you want a quick download, take the `.xz` archive. If you want to check out the repository, deal with its size. Sorry.

**Comment by Nir-Az** [comment]
NP, just raised an enhancement.
Thanks for the hard work on this great repository.
