### ISSUE TITLE
Problem getting vector (array) of strings

### ISSUE THREAD

**Issue by amirmasoudabdol** [nlohmann/json#44]
Considering the JSON below,

```json
{
     "names": ["Tim", "Tom"],
     "num": [1, 2]
}
```

 I want to get a vector of string. I realized that I could only use `auto a = json["name"]` and then process it using for-range loop. However, if I want to explicitly define the return type then I will get an error. For instance, both `vector<string> names = j["names"]` and `vector<string> names = j["names"].get<vector<string>>()` will give me an error:

```
./json.hpp:829:24: error: no matching constructor for initialization of 'std::__1::vector<std::__1::basic_string<char>,
      std::__1::allocator<std::__1::basic_string<char> > >'
                return T(m_value.array->begin(), m_value.array->end());
```

I can see that json library couldn't cast to `vector<string>`; however, it will work if I want to get `num` even explicitly like this: `vector<float> f = j["num"].get<vector<float>>()`.

Now, I'm wondering if I am doing it wrong or it's not implemented?

Thanks,
Amir.

**Comment by nlohmann** [comment]
Dear Amir,

thanks for reporting! It sure looks like a bug. I shall have a look once I'm back from holidays.

All the best
Niels

**Comment by nlohmann** [comment]
I could reproduce the bug.

**Comment by nlohmann** [comment]
Unfortunately, I cannot find a solution right now. I'll check again later.

**Comment by nlohmann** [comment]
The last commit (1bdb6acb1fb003a9bb8cb7771618f1630e78f7d0) fixed this issue. The following code compiles as expected:

```cpp
#include <src/json.hpp>

using nlohmann::json;

int main()
{
    auto j = R"(
    {
         "names": ["Tim", "Tom"],
         "num": [1, 2]
    }
    )"_json;
    
    std::vector<std::string> names = j["names"];
    
    for (auto i : names)
    {
        std::cout << i << " ";
    }
    
    // prints: Tim Tom 
}
```

**Comment by amirmasoudabdol** [comment]
Thanks! :)

**Comment by chakpongchung** [comment]
```
#include <nlohmann/json.hpp>
#include <iostream>

using nlohmann::json;

int main() {
  auto j = R"(
    {
         "names": ["Tim", "Tom"],
         "num": [1, 2]
    }
    )"_json;

  std::vector<std::string> names;
  names = j["names"];

  for (auto i : names) {
    std::cout << i << " ";
  }

  // prints: Tim Tom
}
```

> main.cpp:14:20: error: ambiguous overload for ‘operator=’ (operand types are ‘std::vector<std::__cxx11::basic_string<char> >’ and ‘nlohmann::basic_json<>::value_type {aka nlohmann::basic_json<>}’)
   names = j["names"];


Hi @nlohmann , separating the definition and declaration doesnt work again. Any solution for this? I need this.

**Comment by amirmasoudabdol** [comment]
You modified the code slightly and that might affect your code. I think you should either use the `names = j.at("names")` or indicates the types in `get` again, `names = j.get<std::vector<std:string>>()`.
