### ISSUE TITLE
json::value(const json_pointer&, ValueType) requires exceptions to return the default value.

### ISSUE THREAD

**Issue by rupertsteel** [nlohmann/json#440]
json::value(const json_pointer&, ValueType) is defined as:
```c++
template<class ValueType, typename std::enable_if<
             std::is_convertible<basic_json_t, ValueType>::value, int>::type = 0>
ValueType value(const json_pointer& ptr, ValueType default_value) const
{
    // at only works for objects
    if (is_object())
    {
        // if pointer resolves a value, return it or use default value
        JSON_TRY
        {
            return ptr.get_checked(this);
        }
        JSON_CATCH (std::out_of_range&)
        {
            return default_value;
        }
    }

    JSON_THROW(std::domain_error("cannot use value() with " + type_name()));
}
```

If exceptions are disabled, `JSON_TRY` turns into `if (true)` and `JSON_CATCH` turns into `if (false)`, this means that the default value will never be returned if exceptions are turned off.

**Comment by nlohmann** [comment]
You are right - the function `value` currently relies on exceptions. I currently only see copying a lot of the implementation of `get_checked()` into the function to fix this.

**Comment by nlohmann** [comment]
I think the easiest would be to remove the function when exceptions are turned off.

**Comment by TurpentineDistillery** [comment]
I'm seeing that the code in certain places still uses `throw` instead of `THROW` - was that intentional or an oversight?

**Comment by nlohmann** [comment]
@TurpentineDistillery This is an oversight. Thanks for noting!!

**Comment by nlohmann** [comment]
Replaced the `throw` calls.

**Comment by nlohmann** [comment]
Realizing this function without exceptions would mean doubling the code.
