### ISSUE TITLE
Library Cannot Parse JSON File It Wrote

### ISSUE THREAD

**Issue by JohnFayGeezer** [nlohmann/json#4448]
### Description

I used the JSON library to "pretty-print" a JSON file.  I then read that JSON file into a character array variable and the parser terminated on error.  This has happened with several JSON files; I am submitting a minimal example.

### Reproduction steps

I created the following file named "minimal.json" using Notepad++ on Windows.  It contains four lines, including a blank last line:

{
    "LABEL": 0.0
}

I then wrote the attached C++ program and built it using Cygwin.

g++ -g -DLINUX -Ijson/single_include json_test.cpp

I ran the executable with no command line inputs so that it read "minimal.json" and wrote "min_output.json".  I then renamed "min_output.json" to "minimal_BadChar.json" and ran the program again, this time with a command line argument so that it read this file.  The parser terminated on error with a message about an invalid input.

[minimal.json](https://github.com/user-attachments/files/16870858/minimal.json)
[minimal_badChar.json](https://github.com/user-attachments/files/16870859/minimal_badChar.json)
[json_test.cpp.txt](https://github.com/user-attachments/files/16870866/json_test.cpp.txt)

### Expected vs. actual results

I would expect the code to be able to read a file that it wrote.

### Minimal code example

```Shell
See files attached earlier.
```

### Error messages

```Shell
terminate called after throwing an instance of 'nlohmann::json_abi_v3_11_3::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at line 4, column 1: syntax error while parsing value - invalid literal; last read: '0.0<U+000A>}<U+000A>'; expected end of input
```

### Compiler and operating system

Cyrwin g++ 11.3.0

### Library version

3.11.3

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by Tkyzxim** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by gregmarr** [comment]
Looks like you wrote the string in ASCII mode so it was written with newlines as `\r\n` and then read it in binary mode, so the `\r` was kept.

**Comment by mbadinga1** [comment]
I have the same error and cannot fix for now. 
The solution proposed do not fix the bug.

**Comment by nlohmann** [comment]
The two JSON files are identical. I cannot reproduce the error (on macOS - I don't have access to Cygwin). @mbadinga1 What is your error message?

**Comment by mbadinga1** [comment]
error message : 
terminate called after throwing an instance of 'nlohmann::json_abi_v3_11_3::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at line 1, column 1: attempting to parse an empty input; check that your input string or stream contains the expected JSON
  
  
  in my cpp
  
  void handleBible::jsonBibile()
{
    
    std::ifstream file("bible_ut8.json");
    json data = json::parse(file);
}

and my json :
[bible_ut8.json](https://github.com/user-attachments/files/17212445/bible_ut8.json)
I have also tried with other simple json file but the error still the same.

I save bible_ut8.json with encoding utf8

I am using cmake to build and I am on ubuntu 22.10

Thank you

**Comment by nlohmann** [comment]
Please make sure you call the program in the right directory - That is, make sure that the file is actually opened before trying to parse it.

**Comment by gregmarr** [comment]
>parse error at line 1, column 1: attempting to parse an empty input; check that your input string or stream contains the expected JSON

You are opening a file without a path.  Your working directory is probably not what you think it is.

**Comment by JohnFayGeezer** [comment]
To work around the bug, I simply ran the string through a loop looking for the offending non-printing characters and changing them to blank spaces.

With the “diff” utilities at my disposal (TortoiseGit and WinDiff) the files looked identical.  Notepad++ on Windows wouldn’t show the non-printing characters either.

From: Musshca Badinga ***@***.***>
Sent: Tuesday, October 1, 2024 10:11 AM
To: nlohmann/json ***@***.***>
Cc:
Subject: [Non-DoD Source] Re: [nlohmann/json] Library Cannot Parse JSON File It Wrote (Issue #4448)


I have the same error and cannot fix for now.
The solution proposed do not fix the bug.

**Comment by mbadinga1** [comment]
Thank you, It was a path problem
