### ISSUE TITLE
json parse enclosing json object with []

### ISSUE THREAD

**Issue by dimitre** [nlohmann/json#4457]
### Description

json parse is encosing all json object by  [ ] so all json pointers logic is not valid anymore
it used to use the same structure of input file.

### Reproduction steps

j = { json::parse(contents) };

now I have to use
j = j[0];

### Expected vs. actual results

expected: same hierarchy

### Compiler and operating system

Ubuntu 24.04

### Library version

3.11.3

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by gregmarr** [comment]
See the first entry in the FAQ.  https://json.nlohmann.me/home/faq/
