### ISSUE TITLE
Latest tag not available on NuGet

### ISSUE THREAD

**Issue by pavelschon** [nlohmann/json#4478]
### Description

The most recent version (3.11.3) of the library is not available on NuGet, where only 3.11.2 is available.

https://www.nuget.org/packages/nlohmann.json

### Reproduction steps

-

### Expected vs. actual results

-

### Compiler and operating system

Windows

### Library version

3.11.3

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by gregmarr** [comment]
From the README:

If you are using [NuGet](https://www.nuget.org/), you can use the package [nlohmann.json](https://www.nuget.org/packages/nlohmann.json/). Please check https://github.com/nlohmann/json/issues/1132#issuecomment-452250255 on how to use the package. Please file issues [here](https://github.com/hnkb/nlohmann-json-nuget/issues).

**Comment by pavelschon** [comment]
@gregmarr This issue is not about how to use Nuget. Please read the Description above again.

**Comment by nlohmann** [comment]
Please file a report somewhere at NuGet.

**Comment by gregmarr** [comment]
@pavelschon This comment wasn't about how to use nuget, but about who maintains the nuget package.  The link for filing issues is in the repo where that package is maintained.
