### ISSUE TITLE
Json should not be constructible with 'json*'

### ISSUE THREAD

**Issue by jaredgrubb** [nlohmann/json#448]
I had something like this:
```
        json* p;
        json j(p);
```
This was a bug (I need to dereference the pointer), but json constructor accepts it as a boolean type because it's finding this overload:
```
template<typename BasicJsonType>
void to_json(BasicJsonType& j, typename BasicJsonType::boolean_t b) noexcept
```

The problem with 'bool' is that it captures a lot of things. Classes with 'operator bool()' are also being caught. 

I can think of some simple changes (SFINAE something), but I'm not sure how well they work with arbitrary BasicJsonType's.

**Comment by jaredgrubb** [comment]
Maybe the default to_/from_json should be implemented just for the common C++ types (bool, std::string, std::map, std::vector) and not in terms of BasicJson::whatever_t, and if you specialize basic_json then you have to also manually opt-in to the right to_/from_json overloads?

**Comment by theodelrieu** [comment]
If I remember correctly, there was a constructor for each `BasicJsonType:: whatever _t` prior to 2.1.0.

So I think we should keep those overloads for now, to keep backward compatibility.

To avoid this implicit conversion, I guess a simple `std::is_same<typename BasicJsonType::boolean_t, T>` in the enable_if will do the trick. It would be great to fix similar issues with different parameter types (integers and so on)

Unfortunately I don't have a laptop at hand until Sunday to test this

**Comment by nlohmann** [comment]
@theodelrieu I agree in both points, and I think I won't have time to fix this this week either.

**Comment by jaredgrubb** [comment]
I have done this and it seems to work:
```
-template<typename BasicJsonType>
-void to_json(BasicJsonType& j, typename BasicJsonType::boolean_t b) noexcept
+template<typename BasicJsonType, typename T,
+    enable_if_t<std::is_same<std::decay_t<T>, typename BasicJsonType::boolean_t>::value, int> = 0>
+void to_json(BasicJsonType& j, T b) noexcept
```

I'm not 100% that the decay is necessary.

**Comment by nlohmann** [comment]
Fixed using @jaredgrubb 's proposal.

**Comment by theodelrieu** [comment]
I don't think the decay is useful, but that's a minor thing.

Thanks for the fix!

**Comment by nlohmann** [comment]
I shall remove the decay then.
