### ISSUE TITLE
ohos model to json string garbage characters

### ISSUE THREAD

**Issue by SenyiWong** [nlohmann/json#4481]
### Description

![微信截图_20241030172000](https://github.com/user-attachments/assets/f724cde1-0fad-48e2-af43-024d23b35eaa)
![微信图片编辑_20241030155950](https://github.com/user-attachments/assets/3d2c67a1-9d42-4a84-9ec5-3c7db9a86179)

### Reproduction steps

100% reproduction

### Expected vs. actual results

struct Person {
    std::string name;
    int age;
    NLOHMANN_DEFINE_TYPE_INTRUSIVE(Person, name, age)
};    

Person person;
person.name = "中文字符"; 
person.age = 23;
nlohmann::json js = person;
const char *str =  js.dump().c_str();

 js.dump().c_str();   This will make the string garbled

but js.dump()  assignment to std::string show the correct string

### Compiler and operating system

ohos 5.0

### Library version

current version

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by SenyiWong** [comment]
picture 1 is android ndk
picture 2 is ohos ndk

**Comment by gregmarr** [comment]
```
person.name = "中文字符";
```
Is this UTF-8?  This library requires all strings to be UTF-8.

**Comment by nlohmann** [comment]
Please add a complete code example and not just images.

**Comment by SenyiWong** [comment]
```cpp
// Person.h

#include <string>
#include <nlohmann/json.hpp>
 
struct Person {
    std::string name;
    int age;
    NLOHMANN_DEFINE_TYPE_INTRUSIVE(Person, name, age)
};
```

```cpp
/**********************************************************************************************/

// napi_init.cpp  ohos IDE generate template class
// this will retrieve the correct JSON. 

static napi_value GetJson(napi_env env, napi_callback_info info) {
    Person person;
    person.name = "apple"; 
    person.age = 26;
    
    nlohmann::json js = person;
    std::string jsstr = js.dump();
    const char *str = jsstr.c_str();
    
    size_t length = NAPI_AUTO_LENGTH;                                        
    napi_value result = nullptr;
    napi_status status = napi_create_string_utf8(env, str, length, &result);
    if (status != napi_ok) {
        napi_throw_error(env, nullptr, "Failed to create UTF-8 string");
        return nullptr;
    }
    return result;
}

/**********************************************************************************************/
// js.dump().c_str(); will happen string garbled code

static napi_value GetJson(napi_env env, napi_callback_info info) {
    Person person;
    person.name = "apple"; 
    person.age = 26;
    
    nlohmann::json js = person;
    const char *str = js.dump().c_str();
    
    size_t length = NAPI_AUTO_LENGTH;                                        
    napi_value result = nullptr;
    napi_status status = napi_create_string_utf8(env, str, length, &result);
    if (status != napi_ok) {
        napi_throw_error(env, nullptr, "Failed to create UTF-8 string");
        return nullptr;
    }
    return result;
}
```

**Comment by nlohmann** [comment]
With

```cpp
const char *str = js.dump().c_str();
```

you store a pointer to a temporary that survives the lifetime of the temporary `js.dump()`, leaving a dangling pointer.

Hence, the code

```cpp
std::string jsstr = js.dump();
const char *str = jsstr.c_str();
```

works, because now `str` is valid as long as `jsstr` is.

This is not a library issue.
