### ISSUE TITLE
Namespace macros are not respected in many instances

### ISSUE THREAD

**Issue by iboB** [nlohmann/json#4484]
### Description

It may be the case that the feature is abandoned, but the macros seem to be widely ignored and instead the symbols are just typed from the namespace `nlohmann` or, `::nlohmann`

### Reproduction steps

Try to build with a renamed namespace

### Expected vs. actual results

Expected: successful build
Actual: multiple compilation errors where the macro is not respected

### Compiler and operating system

any

### Library version

any

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by gregmarr** [comment]
Which macros are you referring to?

**Comment by iboB** [comment]
> Which macros are you referring to?

The ones which affect the namespace name (in `detail/abi_macros.hpp`): `JSON_DIAGNOSTICS`, `NLOHMANN_JSON_NAMESPACE_BEGIN`... etc

**Comment by nlohmann** [comment]
Can you give more details?

**Comment by iboB** [comment]
> Can you give more details?

https://github.com/search?q=repo%3Anlohmann%2Fjson+%22nlohmann%3A%3A%22+language%3AC%2B%2B+path%3A%2F%5Einclude%5C%2Fnlohmann%5C%2F%2F&type=code

Or just try compiling with `NLOHMANN_JSON_NAMESPACE` defined to something

**Comment by nlohmann** [comment]
From the [documentation of `NLOHMANN_JSON_NAMESPACE`](https://json.nlohmann.me/api/macros/nlohmann_json_namespace/):

> When the macro is not defined, the library will define it to its default value. Overriding this value has no effect on the library.

Furthermore from the documentation of the [`nlohmann` namespace](https://json.nlohmann.me/features/namespace/):

> The root namespace is always `nlohmann`.

What exactly is your issue?

**Comment by iboB** [comment]
Yep. Apologies. My bad. I was under the impression that one could change the namespace with macros (to prevent symbol clashes)
