### ISSUE TITLE
use of undeclared identifier 'UINT8_MAX'

### ISSUE THREAD

**Issue by biyunhuang** [nlohmann/json#451]
hello, i meet this error ,  json.hpp:6365:59: error: use of undeclared identifier 'UINT8_MAX', 
Can someone help me with this question?

i compile in ndk , the version is ndk-r10e
this is my content in application.mk：

APP_STL := c++_shared
NDK_TOOLCHAIN_VERSION := clang3.6
APP_CPPFLAGS += -std=c++11 -frtti -fexceptions
APP_PLATFORM = android-19  (if android-21 ,Will not have this problem)

**Comment by nlohmann** [comment]
From http://stackoverflow.com/questions/16748392/cant-find-symbols-in-stdint-h:

> The macros are available when __STDC_LIMIT_MACROS is defined (additionally __STDC_CONSTANT_MACROS seems to be missing as well). This is probably incorrectly gated or missing when compiling c++. Objective-C and C pick up on these defines for UINT8_MAX and accompanying macros. For now you can define both of those macros globally and it should have no ill effects on your project.

Could you try to define `__STDC_LIMIT_MACROS` when compiling your code?

**Comment by biyunhuang** [comment]
@nlohmann oh yeah, it's usefull for me, thank you very much

**Comment by nlohmann** [comment]
Good to hear. I shall add a comment to the README.

**Comment by TurpentineDistillery** [comment]
Why not use `numeric_limits` here, considering that they are already used elsewhere?

**Comment by nlohmann** [comment]
Good point!

**Comment by nlohmann** [comment]
I replaced the macros with calls to `numeric_limits`. @biyunhuang Could you try the current version if it works without the need of defining `__STDC_LIMIT_MACROS`?

**Comment by nlohmann** [comment]
@biyunhuang Could you please try the current version if it works without the need of defining `__STDC_LIMIT_MACROS`?

**Comment by nlohmann** [comment]
I could reproduce the original error as well as verify it is fixed with the current version with the following configuration:

Application.mk
```
APP_ABI := x86
APP_PLATFORM := android-19
NDK_TOOLCHAIN_VERSION := clang3.6
APP_STL := c++_shared
APP_BUILD_SCRIPT := Android.mk
```

Android.mk
```
LOCAL_PATH := .
include $(CLEAR_VARS)
LOCAL_MODULE := testfile.out
LOCAL_SRC_FILES := testfile.cpp
LOCAL_C_INCLUDES += src
LOCAL_CPP_FEATURES += exceptions rtti
LOCAL_CPPFLAGS += -fexceptions -frtti -std=c++11
include $(BUILD_EXECUTABLE)
```

testfile.cpp
```cpp
#include <json.hpp>

using json = nlohmann::json;

int main()
{
    json j = 1;
}
```

and Android NDK r10e from https://github.com/android-ndk/ndk/wiki.
