### ISSUE TITLE
Warnings with Visual Studio c++ (VS2015 Update 3)

### ISSUE THREAD

**Issue by tksatware** [nlohmann/json#453]
When using the library with uint64_t values, some specialisations throw al lot of warnings (4267 and 4293).
The resulting code works fine, but I like a clean build log :)

So I propose to add the following lines before the first namespace Definition (line 103):

`#if defined(_MSC_VER)`
`#pragma warning(push)`
`#pragma warning(disable: 4267 4293)`
`#endif`

and this at the end before the last #endif:

`#if defined(_MSC_VER)`
`#pragma warning(pop)`
`#endif`

This also could be solved with type casts, but I think they would make the code less readable.

**Comment by nlohmann** [comment]
Interesting - it seems as if MSVC treats number literals like `0x9a` as `size_t` and warns about the conversion to `unsigned char`. I shall have a look whether there is a way to fix it without the pragmas.

**Comment by prsyahmi** [comment]
Adding another cast to all add_to_vector 8-bytes shift solve warning C4293
```
            case 8:
            {
                vec.push_back(static_cast<uint8_t>((static_cast<uint64_t>(number) >> 070) & 0xff));
                vec.push_back(static_cast<uint8_t>((static_cast<uint64_t>(number) >> 060) & 0xff));
                vec.push_back(static_cast<uint8_t>((static_cast<uint64_t>(number) >> 050) & 0xff));
                vec.push_back(static_cast<uint8_t>((static_cast<uint64_t>(number) >> 040) & 0xff));
                // intentional fall-through
            }
```
The 8-bytes add_to_vector however is never executed for string,object and array when targeting x86 on msvc since the size_type = size_t = 32bits. This (probably a dirty) fix works for me since I don't use large json data that exceeds 4GB.

**Comment by tksatware** [comment]
Am 19.02.2017 um 10:42 schrieb Syahmi Azhar:
> |vec.push_back(static_cast<uint8_t>((static_cast<uint64_t>(number) >> 
> 070) & 0xff)); 
> vec.push_back(static_cast<uint8_t>((static_cast<uint64_t>(number) >> 
> 060) & 0xff)); 
> vec.push_back(static_cast<uint8_t>((static_cast<uint64_t>(number) >> 
> 050) & 0xff)); 
> vec.push_back(static_cast<uint8_t>((static_cast<uint64_t>(number) >> 
> 040) & 0xff));|
or more readable:
         case 8:
           {
             uint64_t n = number;        // casts by itself
             vec.push_back(static_cast<uint8_t>((n >> 070) & 0xff));
             vec.push_back(static_cast<uint8_t>((n >> 060) & 0xff));
             vec.push_back(static_cast<uint8_t>((n >> 050) & 0xff));
             vec.push_back(static_cast<uint8_t>((n >> 040) & 0xff));
             // intentional fall-through
           }

And it also happens on x86 code, of course, when you're storing large 
values like database indices.

Timo

**Comment by nlohmann** [comment]
Both warnings to not occur any more. I think this can be closed, right?

**Comment by tksatware** [comment]
Confirmed! Thanks!
