### ISSUE TITLE
doubles are printed as integers

### ISSUE THREAD

**Issue by RiccardoRossi** [nlohmann/json#454]
Hello,
       i am having some trouble with my tests.

thing is that when if I read the string 
{"bool_value":true,"double_value":2.0,"int_value":10,"level1":{"list_value":[3,"hi",false],"tmp":5.0},"string_value":"hello"}

and i print it back, i get
{"bool_value":true,"double_value":2,"int_value":10,"level1":{"list_value":[3,"hi",false],"tmp":5},"string_value":"hello"}

where both "double_value" and "tmp" are written back as integers instead of double. This is an issue as when i read them back in next time they will be considered integers instead of doubles (floats).

same issue also happens with "dump(4)" instead of "dump()"

is there a way to preserve the type upon printing?

regards
Riccardo

**Comment by TurpentineDistillery** [comment]
This is #362.

**Comment by nlohmann** [comment]
I can confirm the bug - it should indeed be fixed with #362. I shall have a look at this this weekend.

**Comment by nlohmann** [comment]
Merged #378 with 4151f2d297f17658ae3fb10f134b99dc4eea79c7. This fixes #362 and #454.
