### ISSUE TITLE
Enum -> string during serialization and vice versa

### ISSUE THREAD

**Issue by thijse** [nlohmann/json#455]
A feature request: 
Include enum to string functionality for improved readability. For example, integrate
https://github.com/aantron/better-enums
I now use this to convert my enums into strings before putting it in a serialization object, but it would be much cleaner if this was integrated in the serialization code

Thanks for the great library!

**Comment by TurpentineDistillery** [comment]
Perhaps this is what you want? https://github.com/nlohmann/json#arbitrary-types-conversions

**Comment by nlohmann** [comment]
I am not sure whether the conversion from enum values to strings can be done *after* the enum has been defined. Can it?

**Comment by nlohmann** [comment]
Any idea on this?

**Comment by fnc12** [comment]
I think one can use `adl_serializer` to encode enum

**Comment by nlohmann** [comment]
Of course it can - currently, it is done like this: https://github.com/nlohmann/json/blob/develop/test/src/unit-udt.cpp#L100

I just don't think we can do it any nicer without touching the original enum. As far as I understand, there is no way to get any string representation from an enum.

**Comment by fnc12** [comment]
Yes. With `BETTER_ENUM` lib it can be done like this:
```
template <typename BasicJsonType>
void to_json(BasicJsonType& j, country c)
{
    j = c._to_string();
}
```

**Comment by nlohmann** [comment]
Right, but for this, you must define `country` with a macro defined in better enum.

**Comment by fnc12** [comment]
It's ok. But there is another problem - better enum value has no default constructor

**Comment by nlohmann** [comment]
I think it makes no sense to add code to this library to generate nicer serialization/deserialization for enums defined with `BETTER_ENUM`. And after all, if a user is using such enums, she is perfectly able to write nicer `to_json`/`from_json` functions.

**Comment by fnc12** [comment]
Yep. This lib gives user ability to provide a custom type mapper and it is a responsibility of a developer to create enum mapper for example (or use mapped from external libraries like `BETTER_ENUM`)

**Comment by nlohmann** [comment]
Alright. I think I can close this issue as there is nothing to be done in the library.
