### ISSUE TITLE
Roundtrip error while parsing "1000000000000000010E5"

### ISSUE THREAD

**Issue by nlohmann** [nlohmann/json#465]
Google OSS-Fuzz found an error executing [`fuzzer-parse_json.cpp`](https://github.com/nlohmann/json/blob/develop/test/src/fuzzer-parse_json.cpp):

1. input `"1000000000000000010E5"` is parsed to JSON value `j1`.
2. `j1` is dumped to string `s1`; result is `"1e+23"`.
3. `s1` is parsed to JSON value `j2`; result is `9.9999999999999991E+22` (Xcode debugger).
4. `j2` is dumped to string `s2`; result is `"9.999999999999999e+22"`.
5. `s1` and `s2` are different.

This is an error in the roundtrip check.

Any ideas on this? (maybe related to #378, #362, and #454)

**Comment by TurpentineDistillery** [comment]
I can reproduce the problem: "1e+23" roundtrips to "9.999999999999999e+22" with the new code, and back to "1e+23" with the old code.

I think this is the problem:
```c++
            static constexpr auto fmt = d == 6  ? "%.7g"
                                        : d == 15 ? "%.16g"
                                        : d == 16 ? "%.17g"
                                        : d == 17 ? "%.18g"
                                        :           "%.19g";
            // I'm not sure why we need to +1 the precision,
            // but without it there's a unit-test that fails
            // that asserts precision of the output
```

If I change the the values within the format string to the values of `d`, as one would expect in the first place, then the problem-case round-trips correctly. On the other hand, such change triggers a unit-test failure:

```
src/unit-inspection.cpp:257: FAILED:
  CHECK( ss.str() == "3.141592653589793" )
with expansion:
  "3.14159265358979" == "3.141592653589793"
```

**Comment by nlohmann** [comment]
After changing the precision, "3.141592653589793" roundtrips stably to "3.14159265358979". Not sure if this is correct though.

**Comment by TurpentineDistillery** [comment]
It appears that it's the right thing to do, and it is like a problem related to the the unit-test.

```c++
    const char* d_str = "3.141592653589793";
    const double d = strtod(d_str, nullptr);
    const auto digits10 = numeric_limits<double>::digits10;
    cout << "digits10:" << digits10 << endl; //15
    cout.precision(digits10);
    cout << d << endl; // 3.14159265358979 (no 3 at the end)

    // with old code that used operator << internally
    // and with the code that uses snrpintf("%.15g");
    const nlohmann::json j = nlohmann::json::parse(d_str);
    std::cout << j << endl; // 3.14159265358979 (no 3 at the end)
```

**Comment by nlohmann** [comment]
So the code

```cpp
            static constexpr auto fmt = d == 6  ? "%.7g"
                                        : d == 15 ? "%.16g"
                                        : d == 16 ? "%.17g"
                                        : d == 17 ? "%.18g"
                                        :           "%.19g";
```

would be changed to

```cpp
            static constexpr auto fmt = d == 6  ? "%.6g"
                                        : d == 15 ? "%.15g"
                                        : d == 16 ? "%.16g"
                                        : "%.17g"; // we already assert that d can only be 6, 15, 16, or 17
```

?

**Comment by TurpentineDistillery** [comment]
Yes.

**Comment by nlohmann** [comment]
OSS-Fuzz marked the issue as fixed. I shall close this ticket.
