### ISSUE TITLE
in vs can't find linkageId  

### ISSUE THREAD

**Issue by lumigit** [nlohmann/json#466]
string payload = "{\"linkageId\":\"L.4028044806278569\",\"conditions\":{\"content\":[{\"op\":0,\"beginTimeSpan\":\"\",\"isHeartbeatTrigger\":0,\"serialNum\":0,\"delayTime\":0,\"rid\":\"13.1.85\",\"type\":16,\"value\":\"1\",\"did\":\"lumi.158d00010fd68d\",\"endTimeSpan\":\"\"}],\"relation\":\"0\"},\"actions\":{\"content\":[{\"duration\":1800,\"serialNum\":0,\"autoReset\":0,\"increase_value\":0,\"delayTime\":0,\"priority\":5,\"rid\":\"4.1.85\",\"type\":2,\"value\":\"2\",\"did\":\"lumi.158d0001254584\",\"onTriggerResetDelay\":0}]}}";

json linkage_pack = payload; 
string linkageID = linkage_pack["linkageId"];

//================
json linkage_pack = json::parse(payload.c_str());
string linkageID = linkage_pack["linkageId"];

it's ok

**Comment by lumigit** [comment]
json linkage_pack = json::parse(payload.c_str());
string linkageID = linkage_pack["linkageId"];

it's ok

**Comment by nlohmann** [comment]
You can also just `json::parse(payload)` - there is no need to call `c_str()`.
