### ISSUE TITLE
[Bug?] Cannot get int pointer, but int64_t works

### ISSUE THREAD

**Issue by steffenbrem** [nlohmann/json#468]
Hi! I have been using `json["enabled"].get<bool*>()` alot and it works perfectly fine. But I cannot get pointers for `int` and `float`. For fun I tried other types and I was suprised to see that `int64_t` did work.

**I would expect this to work**
```cpp
int *value = config["range"].get<int*>();
float *health = config["health"].get<float*>();

// this one does work, why?
int64_t *range = config["range"].get<int64_t*>();
```

**Actual results**
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2338	incompatible pointer type	Chosseling	c:\users\ik\documents\visual studio 2015\projects\dc\rust\commonsdk\src\json.hpp	3385	
Error	C2664	'const double *nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>::get_impl_ptr(const double *) noexcept const': cannot convert argument 1 from 'int *' to 'std::map<StringType,nlohmann::basic_json<std::map,std::vector,StringType,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>,std::less<StringType>,std::allocator<std::pair<const StringType,nlohmann::basic_json<std::map,std::vector,StringType,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>> *'	Chosseling	c:\users\ik\documents\visual studio 2015\projects\dc\rust\commonsdk\src\json.hpp	3388	
```

I am not sure if this is a bug or not, if someone could clear this up that would be awesome! 👍

**Comment by gregmarr** [comment]
It doesn't store `int` and `float`, look at the template shown in the error message:

```
basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>
```

it stores `int64_t`, `uint64_t`, and `double`.

**Comment by steffenbrem** [comment]
@gregmarr I noticed that too indeed, any clue why other types are excluded from that list?

**Comment by gregmarr** [comment]
It's the types used internally for storing signed integers, unsigned integers, and floating point numbers.  There is only one type for each category.

**Comment by steffenbrem** [comment]
Ah right! Makes perfect sense now, thanks for clearing it up 👍
