### ISSUE TITLE
warning in the library

### ISSUE THREAD

**Issue by user1095108** [nlohmann/json#472]
../json/src/json.hpp:8318:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             assert(written_bytes < m_buf.size());

**Comment by nlohmann** [comment]
This was fixed in 345a106d73762d9954ddad8105e0db3301ad0402.

**Comment by user1095108** [comment]
confirmed

**Comment by nlohmann** [comment]
Thanks for reporting anyway. I was very sure that this was fixed, because I am just writing the release notes ;)
