### ISSUE TITLE
Error Using JSON Library with arrays C++

### ISSUE THREAD

**Issue by JMcCASKI** [nlohmann/json#475]
Hi,

I am using your json c++ libraryon a University project.

I am trying to create a json structure with an array of strings contained in it... along with some other information.

Whenever I try to add the array I get an error:
./json.hpp:843:9: error: static_assert failed "could not find to_json() method

      in T's namespace"

        static_assert(sizeof(BasicJsonType) == 0,

I have not implemented to_json() method if that is required, though, I am unsure how to do sure with you library implementation.

My code is along the lines of:

        // Store messageboard data with JSON Lib

        json mbData;    // Json file to hold messageboard information
        // Add to mbData

       

        mbData["messageBoard"] = 
        {
             mbMessage = {message}; // Store the array of strings here
            {"NumUser", "NumMessage"},
            {numUser, numMessage}
        };

where message is a string array each of char size 50 from the string.h lib.

Possibly you may know why this is happening ?

Thanks,

Josh McCaskill

**Comment by JMcCASKI** [comment]
I just realized it may be because I am not allocating mem for the strings properly?
This part of the project is less important.
I just want to get it working so I can start encryption.


string message[50];     // Messaged linked to user name through array index

**Comment by nlohmann** [comment]
You usually only need to implement a `to_json()` function if you are using a user-defined type. The error message you got indicates that the compiler did not find a `to_json()` function for your type. Looking at your code, it seems as if the compiler does not know how to convert

```cpp
    {
         mbMessage = {message}; // Store the array of strings here
        {"NumUser", "NumMessage"},
        {numUser, numMessage}
    };
```

to `json`.

I understand you want to store an array of strings. This is possible by code like

```cpp
json mbData;
mbData["messageBoard"] = {"foo", "bar", "baz");
```

I'm not sure if this helps you. Please let me know.

**Comment by gregmarr** [comment]
You probably want to use `std::vector<std::string> message;` or `std::array<std::string, 50> message;` instead of `std::string message[50];` and then it will work.

**Comment by JMcCASKI** [comment]
Thanks for the responses.

I do not think I will be able to store the strings as = { aaa, bbb } since they are inputted through both a file and interface. 

Unless this would work ?

GUI Input & File Input-> saved as strings
standard in...  >> var;1
file >> var2 

json mbData;
mbData["messageBoard"] = {var1, var2, var3);

I will know how many there are, but not what values they hold.

If not I will try 
std::array<std::string, 50> message;

What do the > mean in this statement?

**Comment by nlohmann** [comment]
You can use `push_back` just like you would for a `std::vector`.

**Comment by nlohmann** [comment]
@JMcCASKI Did it work now?
