### ISSUE TITLE
Streaming binary representations 

### ISSUE THREAD

**Issue by RaviGaddipati** [nlohmann/json#477]
Currently the CBOR and MessagePack requires a vector of bytes for reading/writing. It would be beneficial to enable byte by byte consumption, like in standard file streams. This helps prevent allocating more memory than necessary (large JSON files).

Looking at the implementation this doesn't seem like it would be too difficult, some additional checking would be needed to make sure enough bytes are available.

**Comment by nlohmann** [comment]
You mean a signature like

```cpp
static void to_cbor(const basic_json &j, std::ostream &o)
```

for writing?

**Comment by RaviGaddipati** [comment]
Yup. It would help if you had a multi-GB JSON file. By creating a vector and then parsing, essentially 2 copies are held in memory until parsing is complete and the vector can be destroyed.

**Comment by nlohmann** [comment]
Opened #623 as place to discuss the structure of the parsing functions.

**Comment by nlohmann** [comment]
Function

```cpp
static void to_cbor(const basic_json& j, detail::output_adapter<uint8_t> o)
{
    binary_writer(o).write_cbor(j);
}
```

now allows to write CBOR (and similarly, MessagePack) to the following types from which an `output_adapter<uint8_t>` can be constructed:

- `std::vector< uint8_t >&`
- `std::basic_ostream< uint8_t >&`
- `std::basic_string< uint8_t >&`

Note there is no function yet to write to `std::ostream`(i.e., where the character type is `char`). This is still open.

**Comment by nlohmann** [comment]
Done.
