### ISSUE TITLE
Remove deprecated constructor basic_json(std::istream&)

### ISSUE THREAD

**Issue by nlohmann** [nlohmann/json#480]
Function

```cpp
explicit basic_json(std::istream& i, const parser_callback_t cb = nullptr)
```

has been deprecated since version 2.0.0 (June 24, 2016) to unify the interface of the library. Deprecation warnings were produced with GCC, Clang, and MSVC.

To create objects from an input stream, there remain the following possibilities:

- with callback:
  - `parse(std::istream& i, const parser_callback_t cb = nullptr)`
- without callback
  - `std::istream& operator<<(basic_json& j, std::istream& i)`
  - `std::istream& operator>>(std::istream& i, basic_json& j)`

That is, code without callback `cb`

```cpp
json j(i);
```

must be replaced by either

```cpp
// alternative 1
json j = json::parse(i);

// alternative 2
json j;
j << i;

// alternative 3
json j;
i >> j;
```

Code with a callback function `cb`

```cpp
json j(i, cb);
```

must be replaced by

```cpp
json j = json::parse(i, cb);
```

**Comment by nlohmann** [comment]
As there is no other deprecated code, here is the macro for reference

```cpp
// allow for portable deprecation warnings
#if defined(__clang__) || defined(__GNUC__) || defined(__GNUG__)
    #define JSON_DEPRECATED __attribute__((deprecated))
#elif defined(_MSC_VER)
    #define JSON_DEPRECATED __declspec(deprecated)
#else
    #define JSON_DEPRECATED
#endif
```

**Comment by gregmarr** [comment]
Have you looked at using C++14's [[deprecated]] if C++14 is enabled?

**Comment by nlohmann** [comment]
@gregmarr No, but this is a good idea for the future.
