### ISSUE TITLE
Fix Visual Studo 2013 builds.

### ISSUE THREAD

**Issue by AraHaan** [nlohmann/json#490]
Some projects use your library in Visual Studio 2013. However it tries to use ``constexpr`` and ``noexcept`` which makes it unable to work on that version of Visual Studio. There is got to be a way to know if the version of Visual Studio code wise has ``noexcept`` and ``constexpr``.

**Comment by gregmarr** [comment]
Visual Studio 2013 is not a supported compiler, for exactly those reasons.

**Comment by nlohmann** [comment]
The C++11 support of MSVC 2013 is broken. We cannot support it.
