### ISSUE TITLE
consider using __cpp_exceptions and/or __EXCEPTIONS to disable/enable exception support

### ISSUE THREAD

**Issue by user1095108** [nlohmann/json#498]
It is much more user-friendly if exception support is automatically detected.

resources:
https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_exceptions.html
http://en.cppreference.com/w/cpp/experimental/feature_test

**Comment by nlohmann** [comment]
Thanks, I did not find these macros. Do you know which compilers are covered with them?

**Comment by user1095108** [comment]
gcc and clang definitely, others I don't know. You can test for a specific compiler than go on from there. But it is a proposed standard extension too.

**Comment by user1095108** [comment]
I guess you could also do #if defined(__cpp_excepetions) && (1 == __cpp_exceptions)

**Comment by nlohmann** [comment]
I'm checking for `__EXCEPTIONS` right now. No idea where I got this from...

**Comment by user1095108** [comment]
If you do it doesn't work too well :) I tried to compile without exception support and it didn't work, I check and saw I'd have to define some macro manually to get your library to compile.

**Comment by nlohmann** [comment]
@user1095108 I added a fix (see 65dfc97d401e17befa4d9a2320660b381529304e). Does this work for you?

**Comment by nlohmann** [comment]
Sigh... MSVC seems not to use `__cpp_exceptions` (Appveyor fails: https://ci.appveyor.com/project/nlohmann/json/build/1770). I read about ` _HAS_EXCEPTIONS` so far, but did not find a reliable source for that.

**Comment by user1095108** [comment]
I'd still check if __cpp_exceptions is defined. The macro is not part of c++98, just the exceptions themselves. Otherwise, great.

**Comment by nlohmann** [comment]
> I'd still check if __cpp_exceptions is defined.

What do you mean?

**Comment by nlohmann** [comment]
From https://msdn.microsoft.com/en-us/library/b0084kay.aspx:

> _CPPUNWIND Defined as 1 if one or more of the /GX (Enable Exception Handling), /clr (Common Language Runtime Compilation), or /EH (Exception Handling Model) compiler options are set. Otherwise, undefined.

**Comment by user1095108** [comment]
It is a proposed extension of c++, gcc and clang already implement it, but MSVC has its own thing as you noticed.

**Comment by nlohmann** [comment]
I see. If the fix works for you, I can close the ticket.

**Comment by user1095108** [comment]
sure, but you won't put this into the main branch? I think you want a
generic solution.

2017-03-11 18:21 GMT+01:00 Niels Lohmann <notifications@github.com>:

**Comment by nlohmann** [comment]
I will, but first I wanted your OK, and I want to wait for Travis to finish.

**Comment by user1095108** [comment]
ok, as I wrote earlier, I'd check #if defined(__cpp_exceptions) && (1 ==
__cpp_exceptions) ...

You may have your preferences though, maybe an existent macro definition
could override everything.

2017-03-11 18:36 GMT+01:00 Niels Lohmann <notifications@github.com>:

**Comment by nlohmann** [comment]
You're right, it is better to used `defined()`. But I would not care about the value of the macro - if someone defines it, it better has the standard semantics.

**Comment by user1095108** [comment]
I'm ok with this.

g++ -x c++ -dM -E - < /dev/null | grep _cpp_exceptions

2017-03-11 18:44 GMT+01:00 Niels Lohmann <notifications@github.com>:

**Comment by nlohmann** [comment]
```
$ g++ -x c++ -dM -E - < /dev/null | grep _cpp_exceptions

#define __cpp_exceptions 199711
```

**Comment by user1095108** [comment]
Yes, you might want to use that or just check if it is defined :)

2017-03-11 18:53 GMT+01:00 Niels Lohmann <notifications@github.com>:

**Comment by nlohmann** [comment]
GCC 4.9 does not define `__cpp_exceptions`. I might need `__EXCEPTIONS` there.

**Comment by user1095108** [comment]
It's your library, I personally don't care about 4.9 anymore.

2017-03-11 20:09 GMT+01:00 Niels Lohmann <notifications@github.com>:
