### ISSUE TITLE
CBOR/MessagePack is not read until the end

### ISSUE THREAD

**Issue by nlohmann** [nlohmann/json#505]
When reading a binary vector like `0xf9, 0xff, 0xff, 0x4a` and interpret it as CBOR, the first three bytes are a half-precision floating-point number (NaN, see #504). The parser will return this number and won't read the last byte.

Example program:

```cpp
#include "json.hpp"

using json = nlohmann::json;

int main()
{
    std::vector<uint8_t> vec = {0xf9, 0xff, 0xff, 0x4a};
    std::cerr << json::from_cbor(vec) << std::endl;
}
```

I would like to discuss how to cope with such a situation:
- Leave it as is?
- Throw an exception indicating the vector has not been read completely?
- Continue parsing at this value if the function is called another time. (OK, maybe not exactly this function, but maybe a streaming function.)

Related to #477 #367.

**Comment by TurpentineDistillery** [comment]
The audience for discussion here is likely severely limited.
Is this situation similar to parsing json from a stream containing "0123"... where a valid parse can stop at "0", or parse "0123", interpret as invalid, and throw? If so, throwing is best I think.

**Comment by nlohmann** [comment]
Meanwhile, I also think throwing is best, because we would not implement an `operator>>` where one could expect that the conversion ends once a value has been read.

**Comment by nlohmann** [comment]
Opened #623 as place to discuss the structure of the parsing functions.
