### ISSUE TITLE
Comparison of NaN

### ISSUE THREAD

**Issue by nlohmann** [nlohmann/json#514]
JSON values can store double precision floating-point numbers, including NaN. This is a problem when we compare two JSON values `j1` and `j2`, because `j1 == j2` ultimately returns `j1.m_value.number_float == j2.m_value.number_float`. The latter returns false for NaN, so two JSON values which are bitwise equal are treated unequal because of this.

Would it be a good idea to change the semantics of `==` in this regard to evaluate `json(NAN) == json(NAN)` to true? What do you think?

**Comment by gregmarr** [comment]
In C++, `NaN != NaN`, so it does make sense that it applies when that is in a JSON object.  What is the particular problem that you are looking to solve here?

**Comment by nlohmann** [comment]
OSS-Fuzz discovered this behavior, and I was not aware of it before. I just wanted to discuss whether the library's behavior isn't surprising to anyone else. I don't want to necessarily change anything.

**Comment by gregmarr** [comment]
I think it would be weird if `a == b` were true, but `a.get<double>() == b.get<double>()` were false.

**Comment by jaredgrubb** [comment]
+1 to gregmarr's comment.

**Comment by nlohmann** [comment]
(#516 and #518 are the reasons for this question)

**Comment by nlohmann** [comment]
I think nothing must be changed here, only the documentation must be clear.
