### ISSUE TITLE
NaN to json and back

### ISSUE THREAD

**Issue by martukas** [nlohmann/json#515]
double val = std::numeric_limits<double>::quiet_NaN();
  DBG << "val=" << val;
  json j = val;
  DBG << "j=" << j.dump();
  val = j;
  DBG << "val=" << val;

goes like this:

val=nan
j=null
terminate called after throwing an instance of 'std::domain_error'
  what():  type must be number, but is null

Could this not be behave nicer?

**Comment by nlohmann** [comment]
With the code in the `develop` branch, this works:

```cpp
int main()
{
    double val = std::numeric_limits<double>::quiet_NaN();
    std::cout << "val=" << val << std::endl;
    json j = val;
    std::cout << "j=" << j.dump() << std::endl;
    val = j;
    std::cout << "val=" << val << std::endl;
}
```

output:

```
val=nan
j=null
val=nan
```

Note the `develop` branch is unreleased and is subject to changes until version 3.0.0. This behavior of NaN was only introduced recently.

**Comment by nlohmann** [comment]
@martukas Did you try the develop branch? Could you comment on this?
