### ISSUE TITLE
Suggestion: Support tabs for indentation when serializing to stream.

### ISSUE THREAD

**Issue by timmcd69** [nlohmann/json#520]
With very slight modification to json.hpp, it can support setting the fill char on the output stream to '\t', and then using this fill char as the indent char instead of space.  It works well, for example:

nlohman::json jsonval(...);
std::ofstream ofs(path);
ofs << std::setfill('\t') << std::setw(1) << jsonval;

**Comment by nlohmann** [comment]
Done.

**Comment by pedro-vicente** [comment]
you can also use this method for space indentation , same as saving the string in dump(2) 

```
#include "nlohmann/json.hpp"
#include <fstream>
#include <iostream>
#include <iomanip>
using json = nlohmann::json;

void main()
{
  json j;
  j["pi"] = 3.141;
  std::string s = j.dump(2);
  std::ofstream file("key.json");
  file << std::setfill(' ') << std::setw(2) << j;

}

```
