### ISSUE TITLE
dump_float: truncation from ptrdiff_t to long

### ISSUE THREAD

**Issue by ftillier** [nlohmann/json#527]
Building with VisualStudio 2017, using /W4 and /Wx, I get the following:
```1>json.hpp(6946): warning C4244: '=': conversion from 'std::_Array_iterator<_Ty,64>::difference_type' to 'long', possible loss of data```

On Windows, long is always 32-bits.  Declaring 'len' as std::ptrdiff_t fixes the issue.

**Comment by ftillier** [comment]
```diff --git a/src/json.hpp.re2c b/src/json.hpp.re2c
index a9a5067..e7b23a5 100644
--- a/src/json.hpp.re2c
+++ b/src/json.hpp.re2c
@@ -6927,7 +6927,7 @@ class basic_json
             static constexpr auto d = std::numeric_limits<number_float_t>::digits10;
 
             // the actual conversion
-            long len = snprintf(number_buffer.data(), number_buffer.size(),
+            std::ptrdiff_t len = snprintf(number_buffer.data(), number_buffer.size(),
                                 "%.*g", d, x);
 
             // negative value indicates an error
```

**Comment by gregmarr** [comment]
According to the VS 2015 docs, the return type is `int`.  The VS2017 docs say the same thing.  I wonder if they changed the return type in VS 2017 without updating the docs.

**Comment by ftillier** [comment]
Sorry for the lack of context.  The compiler error comes from line 6946:
```                len = (end - number_buffer.begin());```

The return type of snprintf is still ```int```, which gets promoted to ```long``` just fine.  It's the assignment, which uses ```std::array::difference_type``` (in this case ```std::ptrdiff_t```) on the right hand side, which could truncate since ```long``` is smaller than ```ptrdiff_t```.

**Comment by gregmarr** [comment]
Thanks for the clarification, that makes more sense.  I just assumed that the error was on the code line that you posted, and that it was line 6946 in the version of the header that you were using.

**Comment by ftillier** [comment]
I don't have a system on which I can run re2c, so I hesitate to issue a PR for this - is the patch above sufficient?

**Comment by TurpentineDistillery** [comment]
@ftillier, you don't need re2c. You can do `git checkout src/json.hpp.re2c && git diff src/json.hpp | patch src/json.hpp.re2c`
@nlohmann, perhaps mention the above hack in contribution guidelines?

**Comment by nlohmann** [comment]
@TurpentineDistillery Good point!

**Comment by nlohmann** [comment]
@ftillier Should be fixed now. Could you please validate?

**Comment by ftillier** [comment]
@nlohmann, validated as fixed.  Thanks!
