### ISSUE TITLE
Port has_shape from dropbox/json11

### ISSUE THREAD

**Issue by berkus** [nlohmann/json#528]
It has a very nice utility function, which I ported to nlohmann/json for myself, but would be nice to have it as part of the class:

```cpp
#pragma once

#include <json.hpp>

/* has_shape(json, types)
 *
 * Return true if this is a JSON object and, for each item in types, has a field of
 * the given type. If not, return false and set err to a descriptive message.
 *                                        ^^^ feel free to adjust the return to your error model, but this one is handy
 */
using shape_t = std::initializer_list<std::pair<std::string, nlohmann::json::value_t>>;

bool has_shape(nlohmann::json const& js, shape_t const& shape, std::string& err)
{
    if (!js.is_object()) {
        err = "expected JSON object, got " + js.dump();
        return false;
    }

    for (auto & item : shape) {
        if (js[item.first].type() != item.second) {
            err = "bad type for " + item.first + " in " + js.dump();
            return false;
        }
    }

    return true;
}
```

**Comment by berkus** [comment]
Usage:

```
auto check = shape_t {
  {"field", json::value_t::string},
  {"ttl", json::value_t::number_unsigned}
};

if (has_shape(js, check, err)) {
  cout << "Conforming object" << endl;
} else {
  cout << "Non-conforming object: " << err << endl;
}
```

**Comment by TurpentineDistillery** [comment]
* The function should not modify the passed object (both args should be const-reference).
* The function should not invoke undefined behavior (trying to access by missing key). 
* I'd expect such function to be recursive and applicable to all json-types, not just json-object.
* In case of json-array, it is unclear what the behavior should be, since the semantics of a json-array may be either a list (any size, elements of a uniform shape) or a tuple (fixed size, elements of any shape).
* In case of signed-integer data, it is unclear whether/when it should type-match, e.g. if shape is unsigned, query-type shall be also unsigned; if shape is signed, the query may be either signed or unsigned.
* If the expected type is floating-point, it is unclear whether it should type-match with query type of signed/unsigned/null.
* output-message parameter should be optional.

**Comment by nlohmann** [comment]
I'm not sure whether such a function needs to be added. This sort of validation goes into the direction of JSON Schema or so, and is rather specific. Before we discuss specifics of a PR, let's talk about why this exact function is useful in which scenarios.

**Comment by berkus** [comment]
Well, it's a very convenient check that the object you received conforms to several assumptions at once.

Instead of checking field-by-field in a very clumsy manner

```
if (json.find(FIELD) != json.end and json.find(FIELD).type() == json::string) {
  json.find(FIELD).get<string>() do something with it
}

if (json.find(ANOTHER) != json.end and json.find(ANOTHER).type() == json::number_unsigned) {
  json.find(ANOTHER).get<int>() do something with it
}

if (json.find(THIRD) != json.end and json.find(THIRD).type() == json::number_unsigned) {
  json.find(THIRD).get<int>() do something with it
}
if (json.find(FOURTH) != json.end and json.find(FOURTH).type() == json::number_unsigned) {
  json.find(FOURTH).get<int>() do something with it
}

// it can be more than four fields here, e.g. a typical github api response would contain more than 10
```

you just specify expectation of what the object should look like and check in one go
```
if (!json.has_shape({
  {FIRST, string},
  {SECOND, number_unsigned},
  {THIRD, string}
  {FOURTH, array}
  {FIFTH, object}
})) 
   throw runtime_error("eh, not what i expected");

json[FIRST].get<string>() etc you can use further without any checks - it's there
```

I find this pattern repeatedly convenient when using json, even if I dont' require full-fledged schema validation. It's just less to type and less syntax errors to make. (`if json.find(x) != json.end` pattern is good for library writers but very inconvenient to type for application developers, it should have been something as simple as `json.has_field(name, type)`)

**Comment by nlohmann** [comment]
Any thoughts on this?

**Comment by meox** [comment]
I think that the proposal is great but probably is better if we can see in "embedded" style:

```
json::match_shape({
   {FIRST, [](auto&& x){ ...  } },
   {SECOND, [](auto&& x){ ...  } },
...
});
```
I use an approach similar to that on a simple messaging system based Actor Model (powered by ZMQ & nlohmann::json). I think that this could transform a lot of code if few lines.

**Comment by nlohmann** [comment]
It seems this check can be realized entirely with public methods, right?

**Comment by nlohmann** [comment]
I don't see this as an extension to the library that is useful for many. It is a very special use case, makes only sense for JSON objects, and after all, it can be realized entirely with public methods.

Therefore, I tend to close this issue unless I missed something.
