### ISSUE TITLE
Help request

### ISSUE THREAD

**Issue by abdessattar** [nlohmann/json#539]
Hello,
I want to thank you for the important advice. I get what I want but with simple class.
When I tried your solution with singleton and other specific classes. I got this error "C2338   could not find to _json() method in T's namespace ".
Really, I need your help for advancing as soon as possible.
thank you in advance,
Best regards,

**Comment by nlohmann** [comment]
Can you provide the code you try to compile?

**Comment by abdessattar** [comment]
Ok, but the problem that I work on specifec private project.
You find below the main code.


	#include <iostream>
	#include <stdio.h>
	#include <fstream>
	#include "StdAfx.h"
	#include <stdlib.h>
	#include "C:\Users\abahri\Desktop\visual studio\Project\first part\gui\g4\v5.1.0.0\v5.1.0.0\GUI_Descr.xsd.Output\SourceCodeCPP\GUI_DescrLib.h"
	#include "C:\Users\abahri\Desktop\visual studio\Project\first part\gui\g4\v5.1.0.0\v5.1.0.0\GUI_Descr.xsd.Output\SourceCodeCPP\GUI_DescrLib\DataStream.h"
	#include "C:\Users\abahri\Desktop\visual studio\Project\first part\gui\g4\v5.1.0.0\v5.1.0.0\GUI_Descr.xsd.Output\SourceCodeCPP\GUI_DescrLib\BaseDir.h"
	#include "C:\Users\abahri\Desktop\visual studio\Project\first part\gui\g4\json-develop\json-develop\src\json.hpp"
	using namespace LtXmlLib5;
	using namespace GUI_DescrLib;
	using json = nlohmann::json;

	bool SimpleTestGUI_DescrLibCDataStream(LPCTSTR);
	int main()
	{

		if(SimpleTestGUI_DescrLibCDataStream(_T("<UNCOMMENT & INSERT A SAMPLE XML FILENAME HERE>")));
		std::cout << "hello";
		system("pause");
		return 0;
	}


	bool SimpleTestGUI_DescrLibCDataStream(LPCTSTR lpctFilename)
	{
		GUI_DescrLib_Classes ecls;
		
		LtXmlLib5Data::CParentElementInfo elm = GUI_DescrLib::CClassFactory::getinfoclass(ecls, lpctFilename);
			json j;
			j["ms_pParentElementInfo"] = elm;

				return false;
			
	}

**Comment by nlohmann** [comment]
In line `j["ms_pParentElementInfo"] = elm;`, you try to assign type `LtXmlLib5Data::CParentElementInfo` to `nlohmann::json`. Such a conversion is not provided directly by the library (only default types such as strings, numbers, etc. are supported out of the box). Therefore, the library tries to find whether you provided a `to_json()` function in the namespace of your type (`LtXmlLib5Data` in your case).

You need to define a method `void to_json(json& j, const CParentElementInfo& e)` in namespace `LtXmlLib5Data` where you implement the conversion from a `LtXmlLib5Data::CParentElementInfo` object `e` to a `nlohmann::json` object `j`. This is documented in https://github.com/nlohmann/json#arbitrary-types-conversions.

**Comment by theodelrieu** [comment]
We could add support for enum classes too, this is quite trivial, and won't conflict with existing `to_json(json, my_enum)` methods

**Comment by nlohmann** [comment]
That would be great. Is this related to #513?

**Comment by theodelrieu** [comment]
Yes it is!

**Comment by abdessattar** [comment]
Is it necessary that the method have two arguments, we cannot define it only with first argument (json)?
Thank you in advance,

**Comment by nlohmann** [comment]
No, it has to have two arguments.

**Comment by abdessattar** [comment]
Because I get the same error, in spite I define it with tow arguments.
To your mind what is the solution?

**Comment by nlohmann** [comment]
Did you try what I proposed in https://github.com/nlohmann/json/issues/539#issuecomment-290360644?

**Comment by nlohmann** [comment]
You need to define the `to_json` function in the namespace of the class you want to convert to JSON. It has to have exactly two parameters: `json &` and a const reference of your class type.

**Comment by abdessattar** [comment]
The problem that the class type is a singleton, so Ihave to create one and only one instance of this class.

**Comment by nlohmann** [comment]
I don't understand. The `to_json` function is static.

**Comment by abdessattar** [comment]
As I said in the previous comment, the classes in my project are singletons and their attributes are static. So can I define thes method in the classes as a static method?

**Comment by nlohmann** [comment]
I see. Then you cannot use this mechanism. You can define any function that returns a json.

**Comment by nlohmann** [comment]
btw: this is a strange implementation of a singleton as you have no instance at all. If you follow approaches like http://stackoverflow.com/questions/1008019/c-singleton-design-pattern you would have exactly one instance and could the approach described in the README.

**Comment by abdessattar** [comment]
Good morning,
In which section the approach described?
Thank you in advance,

**Comment by nlohmann** [comment]
See https://github.com/nlohmann/json/issues/539#issuecomment-290360644

**Comment by abdessattar** [comment]
To muy mind, Ihave to add my one "adl_serializer", would do you please show an example of it.
Because I copied the example i this [link](https://github.com/nlohmann/json#arbitrary-types-conversions). 

	template <typename CBaseDir>
	struct adl_serializer {
		static void to_json(json& j, const	CBaseDir& value) {
		 tojson(json& j);
		}

	};
But I get this error "syntax error;identifier'json'".
Thank you in advance

**Comment by theodelrieu** [comment]
There is an example with `boost::optional` in the readme, it seems like your use case
