### ISSUE TITLE
Numbers as keys

### ISSUE THREAD

**Issue by ivan-kryukov** [nlohmann/json#54]
I know this isn't strictly `json`-compliant, but I would love to have numbers as keys.

Say I try:
```
std::map data<double, double> = {{1.0, 2.0}, {3.0, 4.0}};
```
I would like to be able to:
```
json j_data(data);
```
In order to get:
```
{1.0:2.0, 3.0:4.0}
```

I think the strength of `json` is that it can take a little bit of abuse.
Thanks.

**Comment by nlohmann** [comment]
Dear @ivan-kryukov, thank you for your proposal. As such an extension would not be JSON compliant, it would be out of scope of this library. I understand that there is a use case for anything thinkable, but I am afraid I would make my code less predictable and maintainable when I would leave the constraints of JSON.

**Comment by ivan-kryukov** [comment]
Fair enough. Thanks for the great library. I hope it will be pulled into the standard `C++` library at some point.
