### ISSUE TITLE
Using tsl::ordered_map

### ISSUE THREAD

**Issue by arvidsson** [nlohmann/json#546]
Hi!

I'm using Visual Studio C++ 2017 and I get the following error when I try to use tsl::ordered_map with basic_json:

'std::pair<Key,T>::second' uses undefined class 'nlohmann::basic_json<tsl::ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>'

**Comment by nlohmann** [comment]
Related to #485.

**Comment by nlohmann** [comment]
I failed to compile an example myself, but did not find the time to dig into it.

**Comment by risa2000** [comment]
While trying to get ordered `json` working (and got stuck on `fifo_map`) I tried the other recommended implementation in `tsl::ordered_map`, using this code:
```c++
#include <nlohmann/json.hpp>
#include <tsl/ordered_map.h>
// for convenience
using json = nlohmann::basic_json<tsl::ordered_map>;
```
but I am getting the same error as the OP (@arvidsson).
```
C:\PROGRA~2\MICROS~2\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\HostX64\x64\cl.exe  /nologo /TP  -ID:\Dev\include\xtensor -ID:\Dev\include\nlohmann -ID:\Dev\include /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MDd /Zi /Ob0 /Od /RTC1   -std:c++17 /showIncludes /Fohmdq\CMakeFiles\hmdq.dir\hmdq.cpp.obj /Fdhmdq\CMakeFiles\hmdq.dir\ /FS -c ..\..\hmdq\hmdq.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\utility(320): error C2079: 'std::pair<Key,T>::second' uses undefined class 'nlohmann::basic_json<tsl::ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>'
          with
          [
              Key=std::string,
              T=nlohmann::basic_json<tsl::ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>
          ]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\deque(926): note: see reference to class template instantiation 'std::pair<Key,T>' being compiled
          with
          [
              Key=std::string,
              T=nlohmann::basic_json<tsl::ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>
          ]
  d:\dev\include\tsl\ordered_hash.h(228): note: see reference to class template instantiation 'std::deque<std::pair<Key,T>,Allocator>' being compiled
          with
          [
              Key=std::string,
              T=nlohmann::basic_json<tsl::ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>,
              Allocator=std::allocator<std::pair<std::string,nlohmann::basic_json<tsl::ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>
          ]
  D:\Dev\include\tsl/ordered_map.h(112): note: see reference to class template instantiation 'tsl::detail_ordered_hash::ordered_hash<std::pair<Key,T>,tsl::ordered_map<Key,T,nlohmann::basic_json<tsl::ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>::object_comparator_t,std::allocator<std::pair<const StringType,nlohmann::basic_json<tsl::ordered_map,std::vector,StringType,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>,std::allocator<std::pair<Key,T>>,std::deque<std::pair<Key,T>,Allocator>,uint_least32_t>::KeySelect,tsl::ordered_map<Key,T,nlohmann::basic_json<tsl::ordered_map,std::vector,StringType,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>::object_comparator_t,std::allocator<std::pair<const StringType,nlohmann::basic_json<tsl::ordered_map,std::vector,StringType,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>,Allocator,std::deque<std::pair<Key,T>,Allocator>,uint_least32_t>::ValueSelect,Hash,KeyEqual,Allocator,ValueTypeContainer,IndexType>' being compiled
          with
          [
              Key=std::string,
              T=nlohmann::basic_json<tsl::ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>,
              StringType=std::string,
              Allocator=std::allocator<std::pair<std::string,nlohmann::basic_json<tsl::ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>,
              Hash=nlohmann::basic_json<tsl::ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>::object_comparator_t,
              KeyEqual=std::allocator<std::pair<const std::string,nlohmann::basic_json<tsl::ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>,
              ValueTypeContainer=std::deque<std::pair<std::string,nlohmann::basic_json<tsl::ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>,std::allocator<std::pair<std::string,nlohmann::basic_json<tsl::ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>>,
              IndexType=uint_least32_t
          ]
  D:\Dev\include\nlohmann/json.hpp(15909): note: see reference to class template instantiation 'tsl::ordered_map<StringType,nlohmann::basic_json<tsl::ordered_map,std::vector,StringType,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>,nlohmann::basic_json<tsl::ordered_map,std::vector,StringType,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>::object_comparator_t,std::allocator<std::pair<const StringType,nlohmann::basic_json<tsl::ordered_map,std::vector,StringType,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>,std::allocator<std::pair<Key,T>>,std::deque<std::pair<Key,T>,Allocator>,uint_least32_t>' being compiled
          with
          [
              StringType=std::string,
              Key=std::string,
              T=nlohmann::basic_json<tsl::ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>,
              Allocator=std::allocator<std::pair<std::string,nlohmann::basic_json<tsl::ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>
          ]
  ..\..\hmdq\hmdq.cpp(51): note: see reference to class template instantiation 'nlohmann::basic_json<tsl::ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>' being compiled
  ninja: build stopped: subcommand failed.
```
It seems that neither `fifo_map` nor `tsl::ordered_map` works with `json` and MSVC compiler. Does anyone knows any other solution which could work?

Or which compiler supports them as I assume some must as the README recommends both?

**Comment by ilelann** [comment]
To be able to use basic_json with tsl::ordered_map, I wrote this patch https://github.com/ilelann/json/commit/f106d6ba3abcee65765dcd5734fb670d539920d6 
As you can see, I "solved" the point raised here https://github.com/nlohmann/json/issues/546#issuecomment-304447518 about the position of Allocator template argument by introducing a small traits class.
Ultimately, I did not create a pull request for this because I was happy with fifo_map.

**Comment by continue98** [comment]
@Tessil How to use json parse? 

`1>------ Build started: Project: ConsoleApplication9, Configuration: Debug Win32 ------
1>ConsoleApplication9.cpp
1>D:\dev\pawn.json\src\3rd-party\json\json.hpp(9592,1): error C2440: 'return': cannot convert from 'const _Ty2 *' to 'nlohmann::basic_json<ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer> *'
1>        with
1>        [
1>            _Ty2=nlohmann::basic_json<ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>
1>        ]
1>D:\dev\pawn.json\src\3rd-party\json\json.hpp(9592,24): message : Conversion loses qualifiers
1>D:\dev\pawn.json\src\3rd-party\json\json.hpp(9584): message : while compiling class template member function 'nlohmann::basic_json<ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer> *nlohmann::detail::iter_impl<nlohmann::basic_json<ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>::operator ->(void) const'
1>D:\dev\pawn.json\src\3rd-party\json\json.hpp(4750): message : see reference to function template instantiation 'nlohmann::basic_json<ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer> *nlohmann::detail::iter_impl<nlohmann::basic_json<ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>::operator ->(void) const' being compiled
1>D:\dev\pawn.json\src\3rd-party\json\json.hpp(4748): message : see reference to class template instantiation 'nlohmann::detail::iter_impl<nlohmann::basic_json<ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>' being compiled
1>D:\dev\pawn.json\src\3rd-party\json\json.hpp(4733): message : while compiling class template member function 'bool nlohmann::detail::json_sax_dom_callback_parser<BasicJsonType>::end_object(void)'
1>        with
1>        [
1>            BasicJsonType=nlohmann::basic_json<ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>
1>        ]
1>D:\dev\pawn.json\src\3rd-party\json\json.hpp(8847): message : see reference to function template instantiation 'bool nlohmann::detail::json_sax_dom_callback_parser<BasicJsonType>::end_object(void)' being compiled
1>        with
1>        [
1>            BasicJsonType=nlohmann::basic_json<ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>
1>        ]
1>D:\dev\pawn.json\src\3rd-party\json\json.hpp(8737): message : see reference to class template instantiation 'nlohmann::detail::json_sax_dom_callback_parser<BasicJsonType>' being compiled
1>        with
1>        [
1>            BasicJsonType=nlohmann::basic_json<ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>
1>        ]
1>D:\dev\pawn.json\src\3rd-party\json\json.hpp(8734): message : while compiling class template member function 'void nlohmann::detail::parser<nlohmann::basic_json<ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>::parse(const bool,BasicJsonType &)'
1>        with
1>        [
1>            BasicJsonType=nlohmann::basic_json<ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>
1>        ]
1>D:\dev\pawn.json\src\3rd-party\json\json.hpp(20750): message : see reference to function template instantiation 'void nlohmann::detail::parser<nlohmann::basic_json<ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>::parse(const bool,BasicJsonType &)' being compiled
1>        with
1>        [
1>            BasicJsonType=nlohmann::basic_json<ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>
1>        ]
1>D:\dev\pawn.json\src\3rd-party\json\json.hpp(15661): message : see reference to class template instantiation 'nlohmann::detail::parser<nlohmann::basic_json<ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>' being compiled
1>C:\Users\continue\source\repos\ConsoleApplication9\ConsoleApplication9\ConsoleApplication9.cpp(19): message : see reference to class template instantiation 'nlohmann::basic_json<ordered_map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>' being compiled
1>Done building project "ConsoleApplication9.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`
