### ISSUE TITLE
illegal indirection

### ISSUE THREAD

**Issue by jacobjz** [nlohmann/json#548]
![image](https://cloud.githubusercontent.com/assets/17813116/24728803/cbba1bfa-1a5b-11e7-8399-17d974d81805.png)
so i get this error :/

**Comment by gregmarr** [comment]
What release/commit are you using?

**Comment by jacobjz** [comment]
version 2.1.1

**Comment by gregmarr** [comment]
That's very strange.  This is line 1136 in that release:

```
       result["url"] = "https://github.com/nlohmann/json";
```

What is line 1136 in your `json.hpp`?

**Comment by nlohmann** [comment]
Could you remove all headers but `json.hpp` and have your `main` just consist of `json j;`?

**Comment by jacobjz** [comment]
I've downloader version 2.0.5 and it works. :)

**Comment by nlohmann** [comment]
That's strange. Which version of MSVC is this?

**Comment by jacobjz** [comment]
2015. Btw can i make an object of any class with this repository? I'm trying to send an object from Java to C++.

**Comment by nlohmann** [comment]
As of version 2.1.0, you can convert any type from/to JSON, see https://github.com/nlohmann/json#arbitrary-types-conversions.

MSVC 2015 is supported, and we use it with AppVeyor, see https://github.com/nlohmann/json#supported-compilers.

**Comment by jacobjz** [comment]
Ok, i'll post the piece of code where this error occurs tonight and chceck AppVeyor as well:)

**Comment by nlohmann** [comment]
Any news here?

**Comment by tatjam** [comment]
Hmm I'm having the same issue (latest version, got it directly from the file in the repo). Seems to be happening in this line ``static constexpr T value{};``, line 1136.

**Comment by tatjam** [comment]
Also seems to happen on version 2.1.0, but no issues on version 2.0.10

**Comment by nlohmann** [comment]
Could you please tell me the exact versions of your MSVC. The library is known to work with the following versions:

- Visual Studio 14 2015, Microsoft (R) Build Engine version 14.0.25123.0 (and probably later)
- Visual Studio 2017, Microsoft (R) Build Engine version 15.1.548.43366 (and probably later)

These exact versions are used by [AppVeyor](https://ci.appveyor.com/project/nlohmann/json/build/1894) where the test suite can be compiled and executed without errors.

**Comment by tatjam** [comment]
Alright, I'm not if i'm looking at the right number but I believe my version is 4.6.01586 (Seen in the about dialog).

**Comment by nlohmann** [comment]
In Visual Studio, the Tab 'Help'-> 'About Microsoft Visual Studio' should give you the desired infos. (from http://stackoverflow.com/a/5089489/266378).

**Comment by nlohmann** [comment]
Any news on this?

**Comment by tatjam** [comment]
`Version 14.0.24720.00 Update 1`

Indeed that's older than what you use, I suppose they had no full support for contextpr maybe?

**Comment by nlohmann** [comment]
Right. Sorry, but we can't do anything about that.

**Comment by cfogelklou** [comment]
I'm getting this error in MSVC2017, same line - 1136, so definitely newer than MSVC2015.  Not sure if it should be closed?

**Comment by nlohmann** [comment]
Hi @cfogelklou, what is the exact version you are using?

We are using Microsoft (R) Build Engine version 15.1.548.43366 with AppVeyor, see https://ci.appveyor.com/project/nlohmann/json/build/1932 for the latest build which succeeds on MSVC 2017 as well.

**Comment by xgdgsc** [comment]
I also get this with VS2015 `Version 14.0.24720.00 Update 1`.

**Comment by nlohmann** [comment]
I think this version is not supported. The code is known to run with Microsoft Visual C++ 2015 / Build Tools 14.0.25123.0 (and possibly later), see https://github.com/nlohmann/json#supported-compilers.
