### ISSUE TITLE
Minimal repository (current size very large)

### ISSUE THREAD

**Issue by tdegeus** [nlohmann/json#556]
I want to use "json" as a submodule to my project, because:

1.  I want to be transparent is ownership, to give credits where they are due.
2.  To facilitate updating from source.

However, the current repository is extremely large, due to the tests and benchmarks. This hinders again the distribution of my code. Therefore it would be great if a minimal repository can be maintained.

Thanks!
Tom

**Comment by nlohmann** [comment]
Duplicate: #96, #482
