### ISSUE TITLE
Cant modify existing numbers inside a json object

### ISSUE THREAD

**Issue by AMScaglione** [nlohmann/json#557]
Say for example I have something like

```cpp
json j;
j["num"] = 0;
```

I can not do something like

` j["num"]  += 1; `

as it gives me this error on runtime:

```
terminate called after throwing an instance of 'std::domain_error'
  what():  cannot use push_back() with number
```

I tried simplifying it to 

`j["num"] = j["num"] + 1;`

but that gives me this error at compile time:
`
error: no match for 'operator+' (operand types are 'nlohmann::basic_json<>::value_type {aka nlohmann::basic_json<>}' and 'int')|`

**Comment by gregmarr** [comment]
`j["num"]` is a `json` object, not an `int`.  You need to `get()` the `int` out of it before you can add 1 to it and assign it back again.

**Comment by nlohmann** [comment]
In addition to @gregmarr s remarks: `+=` is an overload for `json::push_back` and can only be called on a JSON array. And indeed the `+` operator has no overload for `json` and `int`.

To increment `j["num"]`, you need to call

```cpp
j["num"] = j["num"].get<int>() + 1;
```

or

```
j["num"] = int(j["num"]) + 1;
```

**Comment by nlohmann** [comment]
@AMScaglione Does this work for you?

**Comment by AMScaglione** [comment]
Yeah! Sorry, it does

**Comment by nlohmann** [comment]
No problem.
