### ISSUE TITLE
Tip: Don't upgrade to VS2017 if using json initializer list constructs

### ISSUE THREAD

**Issue by grasmanek94** [nlohmann/json#559]
It will save you much hassle if you stick to VS2015:

https://developercommunity.visualstudio.com/content/problem/45529/intellisense-stops-working-vs-package-server-crash.html

If someone can find a workaround for the crash please let me know.

Edit: Maybe this is specific to Windows 7 x64 only, I'm investigating.
Edit2: Confirmed on W10 x64 with VS2015 and VS2017 installed.

**Comment by nlohmann** [comment]
I'm closing this at it has no implications on this library. It would, however, be great if you could update the issue when you get feedback from Microsoft.

**Comment by grasmanek94** [comment]
As of now Microsoft reports this is `fixed - pending release`. I expect it to be fixed within an update or two.

**Comment by nlohmann** [comment]
Thanks for checking back. This is good news!
