### ISSUE TITLE
json and Microsoft Visual c++ Compiler Nov 2012 CTP

### ISSUE THREAD

**Issue by Kostya1** [nlohmann/json#562]
Hello! I use MSVS 2012 with Microsoft Visual c++ Compiler Nov 2012 CTP (C++11). And I cannot compile my project, because there are different mistakes in json.hpp (eg. "C3646: 'noexcept': uknown override specifier"). Is it possible to build your project in MSVS 2012 with C++11 compiler?

**Comment by nlohmann** [comment]
No, unfortunately, you need at least Microsoft Visual C++ 2015 / Build Tools 14.0.25123.0; see https://github.com/nlohmann/json#supported-compilers. MSVC 2012 does not fully implement C++11, see https://msdn.microsoft.com/library/hh567368.aspx.
