### ISSUE TITLE
Support parse std::pair to Json object

### ISSUE THREAD

**Issue by nguoithichkhampha** [nlohmann/json#563]
Hi, I really interested with this library. But did you support parse a std::pair to Json object ?
Something like this:
`std::pair<std::string,std::string>{"test1","value1"}`
will have a json object: `{ "test1":"value1"}`

**Comment by nlohmann** [comment]
No, this is currently not supported. You can, however, create an object with an initializer list

```cpp
json j = { {"test1", "value1"} };
```

I'm not sure whether implementing a constructor for a pair would be too helpful. The only scenario where pairs may be of interest would be if they are the `value_type` of a `std::map`. Then, you can also assign the map at once:

```cpp
std::map<std::string, std::string> m;
m["key1"] = "value1";
m["key2"] = "value2";

json j = m;
```

What do you think?

**Comment by nguoithichkhampha** [comment]
I think very useful if can support std::pair . Sometimes my json object only one field, so I don't want to use a std::map. Although I can use a std::map with one element but I can't access directly key and value in map in case don't know key. Otherwise , with std::pair, I only call pair.first and pair.second to get info in pair.

**Comment by nlohmann** [comment]
But you can use the initializer syntax as well.

**Comment by nguoithichkhampha** [comment]
No, I mean I have a struct 
struct A {
std::pair<std::string,std::string> value;
};
And I want to parse struct A to Json object and reverse

**Comment by nlohmann** [comment]
You may want to have a look at this if you want to convert arbitrary types to JSON: https://github.com/nlohmann/json#arbitrary-types-conversions

**Comment by nguoithichkhampha** [comment]
Yes, I know but I need to parse manually , need to get pair.first and pair.second and after that add them in Json object. I did this . But if support parse std::pair I don't need write manual code

**Comment by nlohmann** [comment]
I see. But I'm not sure whether a constructor to create a singleton object would be helpful for others.

**Comment by TurpentineDistillery** [comment]
@nguoithichkhampha 
>No, I mean I have a struct
`struct A { std::pair<std::string,std::string> value; };`
And I want to parse struct A to Json object and reverse

Can you provide sample implementation?

**Comment by nguoithichkhampha** [comment]
yes, this is my case:
I want to create a json aray:
[{"record1":"note1"},{"record2":"note2"}......]

**Comment by nlohmann** [comment]
If you use `std::vector<std::pair<std::string,std::string>>`, where do you use the JSON library?

**Comment by nguoithichkhampha** [comment]
I'm building a web service. the response of ws is json format. I use JSON library at all when send reply.

**Comment by nlohmann** [comment]
Again, please provide a concrete example.

**Comment by nguoithichkhampha** [comment]
I can't give detail code in here. Just my idea to support std::pair. if you feel it not useful. You can discard.

**Comment by JohanMabille** [comment]
I am also interested in support for std::pair and std::tuple. The framework that we're building serializes patches of modified attributes in the context of an observer pattern. Some of these attributes may be std::pair. We have implemented specializations of adl_serializer as explained [here](https://github.com/nlohmann/json#how-do-i-convert-third-party-types). Would you be interested in a PR with that stuff ?

**Comment by nlohmann** [comment]
Meanwhile, this code compiles:

```cpp
#include "json.hpp"
#include <iostream>

using json =  nlohmann::json;

int main() {
    auto p = std::make_pair(1, 2);
    auto t = std::make_tuple("foo", "bar", "baz");

    json j;
    j["pair"] = p;
    j["tuple"] = t;

    std::cout << std::setw(4) << j << std::endl;
}
```

Output:

```js
{
    "pair": [
        1,
        2
    ],
    "tuple": [
        "foo",
        "bar",
        "baz"
    ]
}
```

Is this helpful for you, @JohanMabille?

**Comment by JohanMabille** [comment]
Indeed, this works in develop branch, but not in v2.1.1 (which we are using). We'll wait for the v3.0.0 then.
Thanks for your quick reply.

**Comment by nlohmann** [comment]
Sorry for the inconvenience!
