### ISSUE TITLE
contradictory documentation regarding json::find

### ISSUE THREAD

**Issue by Fytch** [nlohmann/json#565]
Consider the table [Container function overview](https://nlohmann.github.io/json/index.html). It states that `json::find` will always return `json::end()` for objects. Likewise ought `json::count` to return 0. However, the [source code](https://github.com/nlohmann/json/blob/v2.1.1/src/json.hpp#L4585) makes it very clear, that said information pertains to any JSON value type **but** objects. My guess is that both remarks *(returns `end()`)* and *(returns `0`)* are supposed to be in the column 'array', not in the column 'object'. This assumption is supported by the fact that [another](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_aeed33787bd362c7ead59a4ba945392db.html) [part](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a5261eba9637f59d17d6cab5f14ce5747.html) of the documentation also patently states that objects, not arrays, are the exception with respect to `json::find` and `json::count`.

**Comment by nlohmann** [comment]
Thanks a lot!
