### ISSUE TITLE
Conan.io

### ISSUE THREAD

**Issue by Pancir** [nlohmann/json#566]
Hello guys I think it would be a good idea to make the library to be available through the conan. https://www.conan.io/
I could do it without your help but it is the better way when the developers is responsible for it themselves.

**Comment by nlohmann** [comment]
I think it's already there: https://www.conan.io/source/nlJson/2.0.2/arnemertz/stable

That version is outdated. Would it make sense to add another one?

**Comment by Pancir** [comment]
Anyone can add to the conan's repository any library,  but official supporting is always better. For example it could be uploaded from the CI at once and the conan's recipe could be adjusted properly by the developers and it could have correct naming and user in the canan's repository.
Anyway it is just a suggestion to adjust delivering to the conan's repository.

**Comment by nlohmann** [comment]
@Pancir What exactly needs to be done for this? Is it sufficient to create a conanfile.py like this: https://github.com/arnemertz/conan-nlJson/blob/master/conanfile.py ?

**Comment by Pancir** [comment]
Yes and usually you have to create the test_package for checking the recipe.  
BTW The conanfile.py with the test_package can be in separated repository if you wish, you can see it with the link you have specified, it is in another repository. 
The test_package is just a simple consumer. 
http://conanio.readthedocs.io/en/latest/reference/commands/test_package.html
http://conanio.readthedocs.io/en/latest/packaging/getting_started.html#the-test-package-folder

**Comment by nlohmann** [comment]
I just learned [conan.io is deprecated](http://docs.conan.io/en/latest/move_to_bintray.html).

**Comment by Pancir** [comment]
Yes, they just moved their public repository to another place. I don't learn the issue about this moving yet but I guess it should not affect the conanfile.py and the test_package. 
The conan is still young and it is under active developing.

**Comment by nlohmann** [comment]
I am currently not planning to invest time into this. A PR would be appreciated.

**Comment by Pancir** [comment]
Sorry, I don't know what "PR" means.

**Comment by nlohmann** [comment]
A pull request. If anyone would create the required files (such as https://github.com/nlohmann/json/blob/develop/meson.build for Meson, see https://github.com/nlohmann/json/pull/576), I would be happy to add them to my repository.

**Comment by Pancir** [comment]
Thx for the explanation.

**Comment by nlohmann** [comment]
@Pancir As I described in #619, I cannot maintain Conan.io myself. If someone (like @arnemertz before) can maintain a repository with the required files, I would be happy.

**Comment by nlohmann** [comment]
I shall leave this ticket open for a while.

**Comment by vthiery** [comment]
As discussed, I packaged the library (version 2.1.1) here [conan-jsonformoderncpp](https://github.com/vthiery/conan-jsonformoderncpp) and made it available on [Bintray](https://bintray.com/vthiery/conan-packages/jsonformoderncpp%3Avthiery).

**Comment by nlohmann** [comment]
Great. What should I add to the README (about 1 sentence) so that Conan users would know what to do?

**Comment by vthiery** [comment]
In the same spirit of what I proposed in #619 , I would suggest:

> If you are using [Conan](https://www.conan.io/) to manage your dependencies, merely add `jsonformoderncpp/x.y.z@vthiery/stable` to your conanfile.py's requires, where `x.y.z` is the release version you want to use. Please file issues [here](https://github.com/vthiery/conan-jsonformoderncpp/issues) if you experience problems with the packages.

**Comment by nlohmann** [comment]
Thanks a lot! I shall update the README accordingly.

**Comment by Pancir** [comment]
Thank you guys!
