### ISSUE TITLE
Internal structure gets corrupted while parsing

### ISSUE THREAD

**Issue by sytelus** [nlohmann/json#569]
I've two json files. One is stored using ASCII encoding and other is stored using UTF-8 encoding without BOM (using Notepad++'s encoding feature). When I load the UTF-8 file using json.hpp, its internal structure looks corrupted (very large array sizes) and you will see crash trying to read any of elements. The ASCII encoding seems to work fine. However the thing is that there are non-ASCII chars in the content.

Attached is the very small json file I'm trying to read.

[settings.zip](https://github.com/nlohmann/json/files/953931/settings.zip)

**Comment by nlohmann** [comment]
The library fully supports UTF-8, and I can parse the file without problems:

```cpp
#include "json.hpp"
#include <fstream>

using json = nlohmann::json;

int main()
{
    std::ifstream f("settings.json");
    json j = json::parse(f);
    std::cout << std::setw(2) << j << std::endl;
}
```

output:

```js
{
  "Pixhawk": {
    "LocalHostIp": "127.0.0.1",
    "LogViewerHostIp": "127.0.0.1",
    "LogViewerPort": 14388,
    "Model": "Flamewheel",
    "OffboardCompID": 1,
    "OffboardSysID": 134,
    "QgcHostIp": "127.0.0.1",
    "QgcPort": 14550,
    "SerialBaudRate": 115200,
    "SerialPort": "*",
    "SimCompID": 42,
    "SimSysID": 142,
    "SitlIp": "127.0.0.1",
    "SitlPort": 14556,
    "UdpIp": "127.0.0.1",
    "UdpPort": 14560,
    "UseSerial": true,
    "VehicleCompID": 1,
    "VehicleSysID": 135
  },
  "RpcEnabled": false
}
```

The file does not contain any non-ASCII byte.

Can you provide more information?

**Comment by sytelus** [comment]
I'm not able to reproduce this now so closing the issue. If I see this again, I'll re-open.

**Comment by nlohmann** [comment]
Ok. Thanks for checking back!

**Comment by sedapsfognik** [comment]
Hello, guys! Got exactly the same issue :)
Parses perfectly on Windows, but crashes on Ubuntu. After parsing an object, is_object() returns false, while is_array() returns true. No exception on parsing, but exception on getting access to parsed fields.
[config.zip](https://github.com/nlohmann/json/files/1130848/config.zip)

**Comment by sedapsfognik** [comment]
Spent an hour :)
Even this do not work on Ubuntu: json jsonObj{ json_t::parse("{\"x\": \"y\"}") };

**Comment by sedapsfognik** [comment]
OMG...

json jsonObj{ json_t::parse("{"x": "y"}") }; - works fine on Windows with latest VS2017
json jsonObj = json_t::parse("{"x": "y"}"); - only such a variant works on Ubuntu with gcc -std=c++1y

Looks like different compilers chose different (copy?)constructors or something like that around initializer's list. Just WOW!

**Comment by nlohmann** [comment]
I'll have a look.

**Comment by sedapsfognik** [comment]
Thank you! BTW: Amazing lib! ;)

**Comment by sedapsfognik** [comment]
Sorry, for annoying, start from here:

class A
{
public:

  A()
  {
    std::cout << "A()" << std::endl;
  }

  A(std::initializer_list<A> list)
  {
    std::cout << "A(std::initializer_list<A> list)" << std::endl;
  }

  A(const A& a)
  {
    std::cout << "A(const A& a)" << std::endl;
  }
};

int main(int argc, char* argv[])
{
  A a1;
  A a2 = a1;
  A a3{ a1 };

  return 0;
}

Windows:
A()
A(const A& a)
A(const A& a)

Ubuntu:
A()
A(const A& a)
A(const A& a)
A(std::initializer_list<A> list)

**Comment by tlanc007** [comment]
@sedapsfognik : 

> json jsonObj{ json_t::parse("{"x": "y"}") }; - works fine on Windows with latest VS2017
> json jsonObj = json_t::parse("{"x": "y"}"); - only such a variant works on Ubuntu with gcc -std=c++1y

gcc has had problems with the unified initializer construct.  Although I thought that with version 7, it properly handled most of the legal constructs that clang/llvm and MSVS have been able to handle for years.

Also for the fun of it, is there any difference when you specifically use **g++** instead of **gcc** for the command line?  I know that there are cases where **clang** will do something a little differently than **clang++**.

**Comment by nlohmann** [comment]
I can confirm that Clang and GCC (I tried version 5 to 8) behave differently when it comes to these lines:

```cpp
json j1{ json::parse("{\"x\": \"y\"}") };
json j2 = json::parse("{\"x\": \"y\"}");
```

In all cases, `j1` is returned as an array containing `{"x":"y"}`, whereas `j2` is just the object `{"x":"y"}`.

I think there is nothing I can do from the library side.
