### ISSUE TITLE
erase elements using iterators

### ISSUE THREAD

**Issue by nlohmann** [nlohmann/json#57]
Just as other containers, iterators should be used to identify the element to be deleted from a container.

**Comment by nlohmann** [comment]
- [x] implement `erase(pos)` and `erase(first, last)` for array and object
- [ ] implement `erase(pos)` for other values (only allowed for `begin()` iterator - would result in null object)
- [ ] finish test cases

**Comment by nlohmann** [comment]
Done.

**Comment by drewpts** [comment]
Wow, thanks for such fast work!
