### ISSUE TITLE
Request: Object.at() with default return value

### ISSUE THREAD

**Issue by Getfree** [nlohmann/json#570]
On many implementations of dictionary-like structures, we have an `at/get` method that works like this:
`Object.at("key",defaultValue)`
i.e. if there's no key `"key"`, then this would return `defaultValue`.

Could we have something similar in this library?

Here is a possible implementation:

	template<typename returnType>
	returnType at(const typename object_t::key_type& key, const returnType& _default){
		if( is_object() ){
			JSON_TRY{
				return m_value.object->at(key) ;
			}
			JSON_CATCH( std::out_of_range& ){
				return _default ;
			}
		}else{
			JSON_THROW(std::domain_error("cannot use at() with " + type_name()));
		}
	}

Usage example:

    json js ;
    js.at("key", 5) ; // "key" is expected to hold something convertible to `int`, otherwise 5 is returned

**Comment by nlohmann** [comment]
Have a look at the `value` function.

**Comment by Getfree** [comment]
You mean the iterator's `value()` method?
That method doesn't take any optional arguments.

**Comment by nlohmann** [comment]
See https://nlohmann.github.io/json/classnlohmann_1_1basic__json_af9c51328fbe1da75eca750be3009917a.html#af9c51328fbe1da75eca750be3009917a

**Comment by Getfree** [comment]
Oh, that's great. I missed that one completely. I couldn't find it in anywhere in the documentation.

**Comment by Getfree** [comment]
Let's change this request to:
"Add `json.value()` to the list in https://nlohmann.github.io/json/"

**Comment by nlohmann** [comment]
Thanks for the hint. I mentioned the `value` function on the documentation main page.
