### ISSUE TITLE
error: static_assert failed

### ISSUE THREAD

**Issue by SpilledMango** [nlohmann/json#573]
I got this error when I built my application.
```
/json.hpp:843:9: error: static_assert failed "could not find to_json() method       in T's namespace"         static_assert(sizeof(BasicJsonType) == 0
```

**Comment by nlohmann** [comment]
This error occurs if you try to assign an unsupported type to `json`, e.g.

```cpp
MyClass foo;
json j = foo;
```

The second line tries to find a way to convert `MyClass` to `json` and does this by searching for a `to_json` function in the namespace of the class (see https://github.com/nlohmann/json#arbitrary-types-conversions for more information).

Without more context of your program, I'm afraid I cannot help more.

**Comment by nlohmann** [comment]
@SpilledMango Any news on this?

**Comment by SpilledMango** [comment]
No, it's fine.
