### ISSUE TITLE
Visual Studio seems not to have all min() function versions

### ISSUE THREAD

**Issue by j-k** [nlohmann/json#581]
Needed to change the line 8972 if the current version to:
`std::string(start + offset, min(length, max_length - offset));`
in order to make it compile

**Comment by gregmarr** [comment]
It should still be std::min, but yeah, I don't see any reason to use the initializer_list version instead of the two parameter version here.

**Comment by nlohmann** [comment]
I did not know that MSVC does not support the initializer-list version - according to cppreference it is C++11. Anyway, I shall replace it with the other version.

**Comment by nlohmann** [comment]
@j-k Could you please check if the fix works for you?

**Comment by gregmarr** [comment]
I didn't know that it wouldn't support it either until this issue was posted.  :)

**Comment by guygee** [comment]
cloned today, had the same issue, the suggested fix in the first post worked.
VS2015 community V. 14.0.25420.1 compiling x86

**Comment by nlohmann** [comment]
Thanks!

**Comment by guygee** [comment]
I should have added the error msgs and line number:
Error	C2589	'(': illegal token on right side of '::'	[...]\json.hpp	8936	
Error	C2059	syntax error: '::'	LibSonarProc	[...]\json.hpp	8936
it compiled for me when I changed std::min ->min
Wish I was using g++

**Comment by nlohmann** [comment]
I don't understand: I fixed this with commit 9b764ee5d671b41255d390ab9089f12036b2d38a. Does it still not work?

**Comment by guygee** [comment]
Line 8936:
            return std::string(start + offset, std::min(length, max_length - offset));
This fails to compile in VS2015 with the errors I show above.
If I change to this, it will compile:
            return std::string(start + offset, min(length, max_length - offset));

**Comment by nlohmann** [comment]
Which version of MSVC is this?

**Comment by guygee** [comment]
C:\Program Files (x86)\Microsoft Visual Studio 14.0>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

**Comment by nlohmann** [comment]
This version is not supported, see https://github.com/nlohmann/json#supported-compilers.

**Comment by guygee** [comment]
OK, thank you.

**Comment by nlohmann** [comment]
No worries. :)

**Comment by guygee** [comment]
Just to be clear,
Version 19.00.24210  is the MS command-line compiler version,
as I posted above,  the Visual Studio version is 2015, V. 14.0.25420.1

**Comment by nlohmann** [comment]
This is strange - this version is supported. But AppVeyor has no issues building and executing the tests.

**Comment by nlohmann** [comment]
I had another look: AppVeyor compiles the code without issues with Microsoft (R) Build Engine version 14.0.25420.1: https://ci.appveyor.com/project/nlohmann/json/build/job/74yfdd5tjwk0i7s1

Maybe this is related: #603
