### ISSUE TITLE
is it possible to check existence of a value deep in hierarchy?

### ISSUE THREAD

**Issue by crusader-mike** [nlohmann/json#584]
Smth like this:
```
json j = ...;
if (j.find("/this/that/then"_json_pointer) != j.end()) ...;
```

I can use `j.value(ptr, def_value)`, but then I can't tell if node actually existed. I can use `j.at(...)` -- but I don't want to deal with exceptions.

Edit: `j.value()` approach doesn't seem to work either...

**Comment by nlohmann** [comment]
No, this is currently not possible without exceptions.

**Comment by crusader-mike** [comment]
thank you

**Comment by nlohmann** [comment]
You may try the following:

```cpp
auto j_flatten = json::flatten(j);
if (j_flatten.find("/this/that/then") != j_flatten.end())
  ...
```

I think `flatten` does not use exceptions. It may be less performant, but still...

**Comment by nlohmann** [comment]
Docs: https://nlohmann.github.io/json/classnlohmann_1_1basic__json_ab838f000d76662917ffd6ec529569e03.html#ab838f000d76662917ffd6ec529569e03

**Comment by crusader-mike** [comment]
No, this is way too expensive (and it also throws, just in different circumstances (out of memory).

**Comment by nlohmann** [comment]
I see. Then I fear you have to be patient until we add more support for situations where exceptions are switched off.

May I ask in which situation you are using the library?

**Comment by crusader-mike** [comment]
cmdline app that receives a 'job definition' json, checks few values at various places in the tree (tweaks few things, if need be) and submits it for execution to another portion of code (aka engine).

Btw, few notes:
- I've defined to_json/from_json for my struct. In MSVC2015 following works:
json j = ...;
mystruct s{ j };

but in gcc 6.2 -- it fails to compile. Is it MS quirk?

- _from_json()_ receives reverence to already constructed struct. Which means we are doing unnecessary work (member variables written in default ctor will be overwritten). It can be implemented in better way:
`template<class T> T from_json(json const& j) { ... }`
users can provide their own specializations

- In current _from_json()_ form I have to deal with default value in this way:
```
struct MyStruct
{
    string var1{"ABC"};    // default value
};

void from_json(json const& j, MyStruct& v)
{
     v.var1 = j.value("var1", "ABC");   //... but I don't want default value to be repeated in two places (too easy to forget to update second one)

    v.var1 = j.value("var1", v.var1); //... but why should I pay (making string copy, passing second param) if value exists in the json?

   if (j.count("var1"))
        v.var1 = j["var1"];   // ... but I don't like doing two lookups to get one value
}
```

Is there a better way? Or maybe in case 2 it is guaranteed that default value is passed by reference and operator[] is inline?

**Comment by krisives** [comment]
Here is a snippet using C++11 or later:

Example:

```
nlohnmann::json obj = nlohmann::parse("{'foo': 'bar': {'baz': 100}}");
nlohnmann::json deep = Util::resolve(obj, {"music", "ytcracker", "baz"});
```

``` C++11
nlohmann::json Util::resolve(nlohmann::json obj, std::initializer_list<std::string> keys) {
  nlohmann::json j = obj;

  for (auto& key : keys) {
    if (!j.is_object()) {
      return nlohmann::json();
    }

    auto exists = j.find(key);

    if (exists == j.end()) {
      return nlohmann::json();
    }

    j = *exists;
  }

  return j;
}
```
