### ISSUE TITLE
Parsing from stream leads to an array

### ISSUE THREAD

**Issue by matsbror** [nlohmann/json#589]
Hello,

I parse the following file from a stream:
```js
{
  "anInt": 500,
  "aString": "fixed"
}
```

Then I send it to an output stream with dump(4), which yields the following output:
```js
[
    {
        "aString": "fixed",
        "anInt": 500
    }
]
```

It has become embedded in an array. Do you know why and how can I get around it? 
If it is consistent, I can of course deal with it as it is.

**Comment by nlohmann** [comment]
This is odd. Can you please provide the code that you execute for this?

**Comment by matsbror** [comment]
#include <iostream>
    #include <fstream>
    #include <cstdio>

    #include "json.hpp"

    using json = nlohmann::json;

    json readJsonFile(const std::string & fileName){
        std::ifstream jsonFile(fileName);
        return json::parse(jsonFile);
    }
    int main() {
        json bidConfig { readJsonFile("../test.json") };
        std::cout << bidConfig.dump(4) << std::endl;
        return 0;
    }
`

**Comment by matsbror** [comment]
edit the file name to where you have your json

**Comment by matsbror** [comment]
It seems to be related to that I pass the json document as return value from the readJsonFile function. If I parse it and use it in the same function, there is no array.

**Comment by matsbror** [comment]
OK, it is related to the universal initalization. It takes it as an initializer list and thus makes an array out of it. If I change:

    json bidConfig { readJsonFile("../test.json") };

to 

    json bidConfig = readJsonFile("../test.json");

it works as expected.

**Comment by nlohmann** [comment]
Yes, that is it. We use the braces as array literals, e.g. `{1,2,3}`.
