### ISSUE TITLE
not enough examples

### ISSUE THREAD

**Issue by kenkit** [nlohmann/json#592]
This is so far the greatest c++ json library, nice work.
However we don't have enough examples, I can figure how to extract data from this simple string, I tried using the `.at()` but without success, please help with a working example.
`["new message",{"username":"Someone","message":"Hi"}]`
also lets assume we have another like this
`11 ["new message",{"username":"Someone","message":"Hi"}]`
how would I parse such a string ?

**Comment by nlohmann** [comment]
Parsing is described in the [README](https://github.com/nlohmann/json#serialization--deserialization). The `at` function is documented [here](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a93403e803947b86f4da2d1fb3345cf2c.html#a93403e803947b86f4da2d1fb3345cf2c), including an example. All examples can be found here: https://github.com/nlohmann/json/tree/develop/doc/examples.

Please let me know if you need further assistance.

**Comment by kenkit** [comment]
please I need an example with the above string, whenever I parse it. It always fails or turns out blank.
I need just some small code showing how to display the message object as a string.
Thanks in advance

**Comment by nlohmann** [comment]
No, the parse function expects proper JSON. But if you know the length of the non-JSON prefix, you can try something like

```cpp
std::string s = R"(11 ["new message",{"username":"Someone","message":"Hi"}])";

// provide an iterator range: skip the first three bytes
json j = json::parse(s.begin() + 3, s.end());
```

**Comment by kenkit** [comment]
that's quite the problem, i'm new to c++11 so the R' symbol there is confusing. I retrieve the json from a website so the length can change.
Please include how to display the json, I appreciate you taking your time .

**Comment by nlohmann** [comment]
Please have a look at the README first. All is written there.

**Comment by kenkit** [comment]
I think this library maybe a little over my head, I guess the main problem is I can't find just the right examples to grasp how it works.
I'll unfortunately have to move to another, thanks in advance.

**Comment by nlohmann** [comment]
Please just check the README. It's all there - from parsing to value manipulation to printing.

**Comment by kenkit** [comment]
Sorry but I did check the readme, also the doxygen docs, but none of the examples i was looking for was there, especially one that involves displaying a value that is under another value.

**Comment by nlohmann** [comment]
In the example above, `j[1]["Someone"]` is `"Someone"`.

**Comment by kenkit** [comment]
Please re-open the issue someone else may be able to assist, I just need an example where the value is stored in a string or displayed on console.
i'm supposed to use the key "username" to access "someone", I saw somewhere it's possible to use the standard` ["new message"]["username"].get() `to access` "someone" ` string but as I said it never worked because i didn't do it right somehow.

**Comment by kenkit** [comment]
i tried 
```
json in_json=json::parse(message_str);
 auto& array = in_json.at("new message").at("username");
```
it also failed.

**Comment by kenkit** [comment]
What was the point of making the repo public if you won't let other users to freely give their ideas to help us better understand your library, I was supposed to close the issue as it was I who opened it.
You have closed the issue pre-maturely and yet it wasn't solved meaning it's still an open issue.
How do you invent a car and expect everybody to understand what you are saying ? 
Not everybody is a scientist !

**Comment by JakeShirley** [comment]
You can voice your opinion all day long, but the point of a public repo. is so *you* (not the author) can go make the changes you want and if you feel so inclined you can submit a pull request to get the changes back into this repository.

**Comment by kenkit** [comment]
what sought of changes are required to show/explain to  1 user  an example, then wait till he was satisfied and close the issue even if you don't help him ?
If he just left it open, then closed it after say 2 days what's the loss in that ?

**Comment by JakeShirley** [comment]
> and close the issue even if you don't help him/her ?

**Comment by gregmarr** [comment]
You were pointed to examples, several times.  You were given ideas on how to deal with the string that is not proper JSON.  At this point, if you need help, you need to show the code that's not working, and not just a snippet, but something that can be used to reproduce the problem.

Also, this issue is closed, and people are still commenting on it.  I fail to see the problem.

**Comment by nlohmann** [comment]
@kenkit I closed the issue, because I got the feeling that you have little interest in learning about the library, but only in your concrete problem. This is OK. Giving your issue the title "not enough examples" is misleading, because the library has plenty of examples - just not for your concrete question. I gave you some example, and pointed you to further documentation, but you kept insisting that the documentation is improper. As this is not the case, I closed the issue.

**Comment by gregmarr** [comment]
Also, you said "I'll unfortunately have to move to another, thanks all the same." indicating that you were done here.

**Comment by kenkit** [comment]
@gregmarr the problem wasn't malformed strings, I simply trimmed it to remain with a good json, the problem was with extracting and displaying the data from the json.
@nlohmann I told when I the oppening statebe, "This is so far the greatest c++ json library, nice work. "
so I don't get the lack of intrest

**Comment by gregmarr** [comment]
```
11 ["new message",{"username":"Someone","message":"Hi"}]
```
This is not a valid JSON string.

**Comment by kenkit** [comment]
the first string is what I have after str.erase, I posted two in the hope that maybe there was a way of parsing it .

**Comment by gregmarr** [comment]
Thanks for the clarification, that wasn't clear from your original request.

**Comment by kenkit** [comment]
sorry maybe I mistyped this "I can figure how "
it was supposed to be *can't

**Comment by gregmarr** [comment]
Yeah, that much was obvious.  What wasn't obvious was
>the first string is what I have after str.erase, I posted two in the hope that maybe there was a way of parsing it and ignoring the 11 .

**Comment by kenkit** [comment]
after erasing the 11, I still need a way of parsing it, even though this isn't a clean way. The library is supposed to ignore it automatically.
My question is simple, how do I parse and display value of "username" from the string above ?
One example will take me far, but I couldn't find one

**Comment by nlohmann** [comment]
See https://github.com/nlohmann/json/issues/592#issuecomment-303745544 (note: I edited the comment - I used a wrong index before)

**Comment by kenkit** [comment]
All examples are nearly like this one I believe 
{ 
        {"the good", "il buono"},
        {"the bad", "il cattivo"},
        {"the ugly", "il brutto"}
}

how about something like this 
{ 
        {"the good", {"username":"Someone"} },
        {"the bad", "il cattivo"},
        {"the ugly", "il brutto"}
}

**Comment by kenkit** [comment]
this is what a complete example looks like. Note the json string.
https://github.com/miloyip/rapidjson/blob/master/example/tutorial/tutorial.cpp
if only I could delete this issue, i'd feel alot better.
ISSUE SOLVED NOW
