### ISSUE TITLE
Double quotation mark is not parsed correctly

### ISSUE THREAD

**Issue by miloyip** [nlohmann/json#60]
In JSON, double quotation mark in a JSON string is escaped as `\"`, such as
~~~js
["\"foo\""]
~~~
should be escaped as `"foo"`. But this library did not handle it and parsed it as `\"foo\"`.

I reproduced the bug with the following test case:
~~~cpp
    SECTION("escape_dobulequote")
    {
        auto s = "[\"\\\"foo\\\"\"]";
        json j = json::parse(s);
        CHECK(j == json({"\"foo\""}));
    }
~~~

Results:
~~~
test/unit.cpp:6351: FAILED:
  CHECK( j == json({"\"foo\""}) )
with expansion:
  ["\\\"foo\\\""] == "\"foo\""
~~~

**Comment by jgod** [comment]
:+1: I noticed this too. I've been manually escaping my strings

**Comment by nlohmann** [comment]
The problem is the [`escape_string`](https://github.com/nlohmann/json/blob/master/src/json.hpp.re2c#L2189) function that seems to escape strings to strictly. I would be glad about help how to improve the function.

**Comment by nlohmann** [comment]
@miloyip @jgod , could you try https://gist.github.com/nlohmann/84625311b4801cee5420 ?
