### ISSUE TITLE
BOM not skipped when using json:parse(iterator)

### ISSUE THREAD

**Issue by red632nm** [nlohmann/json#602]
The byte-order mark is not being skipped when I use json:parse(iterator) interface for example:
nlohmann::json::parse(static_cast<const char *>(buffer), static_cast<const char *>(buffer) + nbytes)

It looks like the json::parse(stream) interface does skip the BOM.

Here is a quick fix that seems to work for me:
[json.txt](https://github.com/nlohmann/json/files/1045813/json.txt)

**Comment by jaredgrubb** [comment]
Interesting question ... FWIW, Python's json parser does not support this directly either:
https://stackoverflow.com/questions/13156395/python-load-json-file-with-utf-8-bom-header

**Comment by nlohmann** [comment]
I can confirm the observation. With the introduction of input adapters, I forgot to replicate the BOM skipping for all input types. Your fix seems valid. I shall add it as soon as I'm back from traveling.

**Comment by nlohmann** [comment]
Commit d19c5ced4bec1cd81fbb02e8a9381fb6cc90f286 is a fix for the develop branch.

@red632nm It would be great if you could check if this fixes the problem.
@jaredgrubb I didn't know Python would not skip by default. I like the way RFC 7159 describes this:

> In the interests of interoperability, implementations that parse JSON texts MAY ignore the presence of a byte order mark rather than treating it as an error.

**Comment by jaredgrubb** [comment]
@nlohmann : Thanks for the note! If it's a MAY, then totally agree that fixing is appropriate. Thanks for the good work!
