### ISSUE TITLE
[Question] Issue when using Appveyor when compiling library

### ISSUE THREAD

**Issue by tuananh** [nlohmann/json#603]
Hi,

Not sure if this is a right place to ask. I have a small project that use json as submodule library.

When I tried to use AppVeyor, I got some errors like this in the install step

```
src/json.hpp(8936): error C2589: '(': illegal token on right side of '::'
```

```
src/json.hpp(8933): note: while compiling class template member function 'std::string nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>::input_buffer_adapter::read(::size_t,::size_t)'
```

and this

```
json.hpp(8936): error C2062: type 'unknown-type' unexpected
```

Does any of you know what options/ flag I have to use in AppVeyor to make it works?

Regards,

**Comment by tuananh** [comment]
I had to `#define NOMINMAX` to prevent the error. Not sure why you don't need it in your appveyor !?

**Comment by nlohmann** [comment]
I have no idea, sorry.
