### ISSUE TITLE
Is there a way to validate the structure of a json object ?

### ISSUE THREAD

**Issue by Oberonc** [nlohmann/json#604]
Suppose I parsed a string from an unreliable source.
How can I validate the result json object ? (make sure it has certain structure / contents. Such as a list of 3 numbers and then a string ?)
Other than using a long boilerplate code with size() and get<>() and is_* ?

**Comment by pboettch** [comment]
To validate a json instance or document, the json-schema.org has defined "a vocabulary that allows you to annotate and validate JSON documents" (citation from their site).

To my knowledge, there are two libraries written in C++ on github. [One](https://github.com/pboettch/json-schema-validator) written by me, which supports draft4-version of json-schema.org only and is entirely based on this (nlohmann/json) library for json-parsing. 

And there is [valijson](https://github.com/tristanpenman/valijson) by Tristan Penman which does support other C++ json-parsers as well.

**Comment by nlohmann** [comment]
@pboettch is right - JSON Schema is the tool to use here. It lets you specify your requirements with a JSON document and avoids manual checks.
