### ISSUE TITLE
a bug of inheritance ? 

### ISSUE THREAD

**Issue by zhishupp** [nlohmann/json#608]
I did a test of inheriting from class nlohmann::json, and it's a little difference if I directly use nlohmann::json.

```cpp
#include "json.hpp"
using json = nlohmann::json;
class JSON : public json {};
int main(int argc, char* argv[])
{
    JSON j;
    JSON j1;
    j1["k"] = "v";
    j["o"] = j1;
    std::cout << j.dump() << std::endl;
    return 0;
}
```
the result:  **{"o":["v"]}**

```cpp
#include "json.hpp"
using json = nlohmann::json;
//class JSON : public json {};
int main(int argc, char* argv[])
{
    json j;
    json j1;
    j1["k"] = "v";
    j["o"] = j1;
    std::cout << j.dump() << std::endl;
    return 0;
}
```
the result:  **{"o":{"k":"v"}}**

"k" is lost in inheritance condition

**Comment by nlohmann** [comment]
It seems as if `is_compatible_array_type<BasicJsonType, CompatibleArrayType>::value` holds true in the inheritance case when `j["o"] = j1` is called: `j1` is treated as if it was an array, so `static void construct(BasicJsonType& j, const CompatibleArrayType& arr)` is called on the range `j1.begin()`/`j1.end()`. As `j1` is a string, this range returns exactly 1 item. For this reason, the result is `["v"]`.

I am not sure how to fix this right now. Maybe @theodelrieu has an idea. I guess we all just forgot about the case of inheriting from `basic_json`.

**Comment by theodelrieu** [comment]
Sorry for the veeery late reply, just found about this issue.
I will look into it!
