### ISSUE TITLE
How to parse multiple same Keys of JSON and save them?

### ISSUE THREAD

**Issue by dk1206** [nlohmann/json#612]
Hey guys,

**This is NOT AN ISSUE, but Niels told me to put my question here anyway.**

I have several Objects in my JSON, something like this:

```
 {
  Id= 1
  Name = David
},
{
  Id = 2
  Name = Katja
},
{
  Id = 3
  Name = Luka
},
```
..

As you can see, I have several identifiers (Id, Name) which are the same in my JSON. How can I do this in C++ with this Lib, so that I can parse it only once and store it somewhere for future use?

E.g. I want to populate  a List of Users on my GUI. And then also track which User was clicked and call get that Id from JSON (there are more data in JSON than Id and Name).

**Comment by nlohmann** [comment]
What about the following:

```cpp
#include "json.hpp"
#include <unordered_map>

using json = nlohmann::json;

int main()
{
    // the JSON text
    std::string s = R"([
        {"id": 1, "name": "David"},
        {"id": 2, "name": "Katja"},
        {"id": 3, "name": "Luka"}
    ])";
    
    // create a JSON value
    json j = json::parse(s);
    std::cout << j << std::endl;
    
    // some lookup container
    std::unordered_map<int, json> lookup;
    
    // add elements from the JSON value to the lookup container
    for (auto &el : j)
    {
        lookup[el["id"]] = el;
    }
    
    // lookup
    std::cout << lookup[2] << std::endl;
}
```

**Comment by nlohmann** [comment]
Hey @dk1206, does this work for you?

**Comment by dk1206** [comment]
I will work on it later, as this requires some other knowledge of c++, which I currently do not have.

I will close this issue for now. 

Thanks for help!
