### ISSUE TITLE
Insertion into nested json field

### ISSUE THREAD

**Issue by karthiksheshadri** [nlohmann/json#621]
Suppose one wants to insert iteratively into a nested field, for example:

```cpp
for (auto& i : strings) {

j["Outer level"]["Inner level[i]"]=match[i];

}
```

pushback() does not do this and one cannot use a string type as index, i.e, j["Outer Level"][str] doesn't work - is there any way to do this?

Many thanks!

**Comment by nlohmann** [comment]
What would be `match` in your example?

**Comment by nlohmann** [comment]
This works, but may not be what you want:

```cpp
#include "json.hpp"

using json = nlohmann::json;

int main()
{
    std::vector<std::string> strings = {"one", "two", "three"};
    json j;
    
    for (auto& i : strings) {
        j["Outer level"]["Inner level[i]"][i] = i;
    }
    
    std::cout << j << std::endl;
}
```

**Comment by karthiksheshadri** [comment]
match would be a string, for example, std:string match = "Hello";.

Thanks!

**Comment by nlohmann** [comment]
And what is `strings`? I need more information.

**Comment by karthiksheshadri** [comment]
int ii = 0;
	for (auto& i : strings) {
		if (std::regex_match(i, match, rgx)) {
			std::ssub_match submatch = match[1];
			j["includes"][ii] = submatch.str();
			std::cout << submatch.str() << '\n';
			ii++;
		}
	}

This works perfectly, thank you!

**Comment by nlohmann** [comment]
Thanks for checking back!
