### ISSUE TITLE
from_json for std::array

### ISSUE THREAD

**Issue by hsdk123** [nlohmann/json#625]
Hi, I'm realising that for an std::array, I can pass in the array as in into json and the library will convert it for me automatically, whereas when I'm trying to create an std::array from json, the conversion doesn't occur automatically, giving me an error saying that 'array doesn't have an insert function'. 

This might seem small, but can get very inconvenient - it would be great if we could also get auto conversion of json arrays into arrays without having to explicitly create one element by element.

**Comment by nlohmann** [comment]
Duplicate: #553.

**Comment by nlohmann** [comment]
With #624, the library now also supports the conversion from/to `std::pair`, `std::tuple`, and `std::array`.
