### ISSUE TITLE
Dependency injection in serializer

### ISSUE THREAD

**Issue by celian-garcia** [nlohmann/json#627]
Hello,
I'm currently using  your library with great pleasure but I was wondering if I could inject a service as a dependency to the adl_serializer and how to do that.

I saw that a lot of things are done at compile time so maybe that I'll have to use it as a static service ?
This option would work but if you have a better one, I'm listening :)

To illustrate, here is an example with both solutions.
``` c++
namespace nlohmann {
    template<>
    struct adl_serializer<firefly::Task> {
        static firefly::Task from_json(const json &j) {
            return firefly::Task(
                    j["name"].get<std::string>(),
                    j["description"].get<std::string>(),
                    ////////////////////////////////////////
                    // Solution 1 (wanted one) : Injected instantiated service ? How to inject it ? 
                    service.getProcessingTypeById(j["type"].get<int>()),
                    service.getModuleById(j["module"].get<int>()),
                    // Solution 2 (working) : Use the service statically
                    firefly::DataService::getProcessingTypeById(j["type"].get<int>()),
                    firefly::DataService::getModuleById(j["module"].get<int>()),
                    ////////////////////////////////////////
                    j["user_name"].get<std::string>(),
                    j["date"].get<std::string>(),
                    j["state"].get<int>()
            );
        }
    };
}
```

Thank you :)

Célian Garcia 

Edit : NB : I'll use "at" instead of "[]" as mentionned in your doc ;)

**Comment by theodelrieu** [comment]
Hi, you could add a third argument (`DataService&`) to your method, which would be defaulted to the object you want to use.

I didn't test it, but I'm confident this will work.

**Comment by celian-garcia** [comment]
Ah ok I see. I'll try it this evening and if it works I post the solution.

Thank you very much !

**Comment by celian-garcia** [comment]
Your solution did'nt solve my problem since `from_json` method call the default constructor of the object, and I don't want to make any encapsulated initialization in the default constructor of my object.

Ok after some digging, I found a solution. My solution consist in injecting my DataService **after** the parse.

Example : 
```cpp
CommonDataStore dataStore("a/file"); // Create the dependency
TaskBuilder taskBuilder = raw_json_data; // Parse the json in a builder (adl_serializer is called with TaskBuilder)
taskBuilder.injectDataStore(dataStore); // Inject the dependency to the builder
Task task = taskBuilder.build(); // The builder use the data from data store to build the Task object
```

**Comment by celian-garcia** [comment]
I close it because it works well for me. Thank you again.
