### ISSUE TITLE
[Question] Any fork for (the unsupported) Visual Studio 2012 version?

### ISSUE THREAD

**Issue by joxeankoret** [nlohmann/json#628]
Hi!

First of all, thanks for writing such a good piece of software! I've been using it with various compilers for some projects and it's awesome, I love it.

Now the question: I'm trying to use it with an old project that uses Visual Studio 2012 and I cannot port to a newer compiler. I've been checking if there was any port of this library for Visual Studio 2012 but I cannot find any.

Do you happen to know if it was ever ported/forked to Visual Studio 2012?

Thanks in advance!

**Comment by nlohmann** [comment]
I am not aware of such a fork, and given the state of the [C++11 support of Visual Studio 2012](https://msdn.microsoft.com/en-us/en-en/library/hh567368.aspx#featurelist) I think a significant rewrite would be necessary, because a lot of features would need to be removed.

**Comment by joxeankoret** [comment]
I've been trying myself to port it based on a VS2013 fork and... it's, basically, horrible. Ok, I had to ask if somebody did that hard work. Thank you!

**Comment by nlohmann** [comment]
I close this for now as there is nothing I can do about this issue.

**Comment by chipweinberger** [comment]
joxeankoret, could you link the fork? How would I go about finding it?
