### ISSUE TITLE
Are we forced to use "-fexceptions" flag in android ndk project

### ISSUE THREAD

**Issue by CodeMasterYi** [nlohmann/json#640]
Are we forced to use "-fexceptions" flag in android ndk project?
~~~

**Comment by nlohmann** [comment]
I am not using NDK myself. What happens if you do not provide the flags? What happens if you do?

**Comment by CodeMasterYi** [comment]
I am not sure. I am not using "-fexceptions" flag in my ndk project.
`
    try {
        json obj = json::parse("Hello, nlohmann::json!");
    }
    catch (std::exception e) {
        CCLOG("json - ParseError: %s", e.what());
    }
`
the CCLOG expression can never be touched, and the app crashed here! Crash Log's here:
`
A/libc: /tmp/ndk-cislave/tmp/build-7649/build-libc++/ndk/sources/cxx-stl/llvm-libc++/3.6/../../llvm-libc++abi/libcxxabi/src/cxa_personality.cpp:347: const __cxxabiv1::__shim_type_info *get_shim_type_info(uint64_t, const uint8_t *, uint8_t, bool, _Unwind_Exception *): assertion "ttypeEncoding == DW_EH_PE_absptr && "Unexpected TTypeEncoding"" failed
`

but the same code running on my ios project is ok! Log is like this:
`
Cocos2d: json::ParseError: std::exception
`

By the way, Is all exceptions throwed by methods of nlohmann::json derived from std::exception?

Thank you for your answering!

**Comment by nlohmann** [comment]
Yes, all exceptions inherit from std::exception. This won't change in 3.0.0, but then we use different exception classes.

I'm afraid I have too little NDK experience to help with the other issue.

**Comment by nlohmann** [comment]
Which NDK are you using? As I wrote in the README, this seems to work:

```
APP_STL := c++_shared
NDK_TOOLCHAIN_VERSION := clang3.6
APP_CPPFLAGS += -frtti -fexceptions
```

**Comment by CodeMasterYi** [comment]
Hi, Lohmann,
We use CrystaX NDK 10.3.2
in my Application.mk, we configure like this:
`
APP_STL := c++_shared
APP_CPPFLAGS := -std=c++11 -frtti -D__GNUC__=4
APP_PLATFORM := android-11
NDK_TOOLCHAIN_VERSION=4.9
APP_ABI := armeabi
#APP_ABI += armeabi-v7a
#APP_ABI += x86
`
and in  Android.mk, we add this:
`
LOCAL_CFLAGS := -fexceptions
`
BUT this is of no effect!~~~

**Comment by nlohmann** [comment]
Could you also add

```
LOCAL_CPP_FEATURES += exceptions
```

**Comment by CodeMasterYi** [comment]
ok, i try it now!
(Which time zone are you in? I'm deep in the dark night! 😭  )

**Comment by CodeMasterYi** [comment]
it is of no effect, either~~
i give up! i choose to use some extra verifications before parsing raw json string to avoid exceptions as possible.
Thank you~

**Comment by nlohmann** [comment]
You're welcome. Sorry not being able to help you, though.

**Comment by cosmos33** [comment]
i run into same issue on Android platform。[this issue](https://github.com/nlohmann/json/issues/1541)
