### ISSUE TITLE
Which is the correct way to json objects as parameters to functions?

### ISSUE THREAD

**Issue by pedrozan** [nlohmann/json#644]
I'm trying to pass a JSON object to a function, but despite all my attempts I always get a segmentation failure. Which is the correct way to do this?

**Comment by nlohmann** [comment]
You should be able to pass it just like a std::vector or a std::map - either as reference or const reference depending on your scenario.

Could you provide an example that fails?

**Comment by nlohmann** [comment]
Do you need further help?
