### ISSUE TITLE
Package Name

### ISSUE THREAD

**Issue by SylvainCorlay** [nlohmann/json#646]
I am interested in making a package for the conda package manager (on conda-forge).

What would you like the name of the package to be?

The conan package name is `jsonformoderncpp`. The cmake project name is `nlohmann_json`.

**Comment by SylvainCorlay** [comment]
Quick bikeshedding question as I have the occasion: have you guys considered splitting into multiple headers?

**Comment by nlohmann** [comment]
I think `nlohmann/json` or so would be best as this is the name at Homebrew. Please have a look at the README for other package managers.

I do not plan to split the header for release, but we may split it for development.

**Comment by theodelrieu** [comment]
We could also release the multiple headers version, and keeping the single header release of course. 

I think it would be a great addition, I've already split some headers in my work to help with compile times.

**Comment by SylvainCorlay** [comment]
What is the benefit of a single header?

**Comment by SylvainCorlay** [comment]
Regarding the package name, the conda documentation specifies

*Conda package names are normalized, and may contain only lowercase alpha characters, numeric digits, underscores, hyphens, or dots*

so it could either be

`nlohmann_json` or `nlohmann.json`.

**Comment by nlohmann** [comment]
The benefit is a trivial integration: just throw in one include and you're done.

About the name: I don't really have an opinion.

**Comment by SylvainCorlay** [comment]
> The benefit is a trivial integration: just throw in one include and you're done.

ok. Thanks. a 15k-long single header is a bit scary too :)

I really love your modern C++ API following the idioms of the STL (PS: I am co-author of [xtensor](http://xtensor.readthedocs.io/en/latest/))...  I have been banging my head when trying to do anything with rapidjson, and despite the claim that it is much faster, I am seriously considering dropping it.

Regarding the packaging, let me know if you come up with an idea. I cannot get to it before a couple of days. It would make sense for it to have the same name on conda / debian and all.

**Comment by nlohmann** [comment]
As the name is `jsonformoderncpp` for Conan, I think this should also be used for Conda.

**Comment by SylvainCorlay** [comment]
Sounds good! I was just going to propose `nljson` for a shorter version of `nlohmann_json `. There also seems to be a conan package with this name https://github.com/arnemertz/conan-nlJson.

Also, since headers typically fall under `PREFIX/include/`, I would have done something like `PREFIX/include/nljson/json.hpp`, and the include statement in most client code would then be `#include "nljson/json.jpp"`.

**Comment by nlohmann** [comment]
There is also https://github.com/vthiery/conan-jsonformoderncpp.

**Comment by SylvainCorlay** [comment]
I like short 😄

**Comment by SylvainCorlay** [comment]
Btw, I am reading up your C++ standard proposal which looks great.

**Comment by nlohmann** [comment]
It's 99.9% the work of @mariokonrad. I did not find the time to work on it so far. But yes, he does a tremendous job.

**Comment by nlohmann** [comment]
Can I close this issue? If there is anything to be changed in the library to support Conda, please let me know (or, better, open a PR).

**Comment by SylvainCorlay** [comment]
Sure. closing.
