### ISSUE TITLE
No exception raised for Out Of Range input of numbers

### ISSUE THREAD

**Issue by MichaelHuth** [nlohmann/json#647]
Hello,

if one has values that are beyond the range of the target type no exception is raised.

e.g. this code with a value of UINT64_MAX+1 and 10000 for the target of a signed char outputs 0 and 16 respectively.

```cpp
	json jtest = json::parse("{\"value\" : 18446744073709551617}");
	std::cout << std::to_string(jtest["value"].get<unsigned long long int>()) << "\n";
	jtest = json::parse("{\"value\" : 10000}");
	std::cout << std::to_string(jtest["value"].get<signed char>()) << "\n";
```

Both cases should throw an exception.

Best regards.

**Comment by nlohmann** [comment]
The first number is parsed as double and the second as uint64_t. Calling get does not check for overflows - it is just like writing `int i = 12345678901235.1235567`.

**Comment by nlohmann** [comment]
Remark: an exception is thrown by the parser if the given number does not fit neither the integer types nor the floating-point type.

**Comment by nlohmann** [comment]
Did this answer your question?

**Comment by nlohmann** [comment]
In fact, Xcode's undefined behavior sanitizer detects the first issue:

```
/Users/niels/Documents/development/debug_lexer/debug_lexer/json.hpp:949:23: runtime error: 1.84467e+19 is outside the range of representable values of type 'unsigned long long'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /Users/niels/Documents/development/debug_lexer/debug_lexer/json.hpp:949:23 in
```

However, this is not inside the library, but in the requested conversion from `double` to `unsigned long long`. I'm not sure whether adding runtime checks to the library would be helpful here.
