### ISSUE TITLE
Eclipse: Method 'size' could not be resolved

### ISSUE THREAD

**Issue by k22jung** [nlohmann/json#649]
I'm running Eclipse Oxygen on Linux and I followed all the instructions for Integration into my C++ project. When I try to call any function like `j.size()` or `j.parse()` on my `json j;` object, Eclipse keeps saying "Method '`function_name`' could not be resolved" and it shows an error. Creating a `json` object and accessing its contents works perfectly fine, it's just `size()`. However it doesn't seem building with g++ causes any errors to occur. Are there any known issues with Eclipse and json.hpp? I'm using json v2.1.1.

**Comment by nlohmann** [comment]
No, I have no heard about neither problems nor successes with the library and Eclipse. Maybe you need to set the language version to C++11?

And as a remark: `parse` is a static function.

**Comment by k22jung** [comment]
I've followed the instructions on integration and I've added the argument for C++11, but it still does it. It's not a major issue, just wondering if it was possible to fix. I can close the issue if you are not aware of any fixes.

**Comment by nlohmann** [comment]
This may be an issue in Eclipse's frontend, as you mentioned the code compiles without problems. I have little experience there.

**Comment by nlohmann** [comment]
I cannot reproduce the issue. I downloaded Eclipse (Oxygen Release (4.7.0)), created a C++ hello world project and added file `json.hpp`. I also set the language dialect to C++11.

The `size` method is properly auto-completed:

<img width="538" alt="eclipse" src="https://user-images.githubusercontent.com/159488/27984616-b57e5f22-63da-11e7-8b9e-c2b207bf5b3d.png">

and also has no issues when written out:

<img width="423" alt="eclipse2" src="https://user-images.githubusercontent.com/159488/27984618-c105298e-63da-11e7-9029-3e741c4b8e03.png">

I can compile without problems.

**Comment by nlohmann** [comment]
Here the complete Window including build information.

<img width="1104" alt="eclipse" src="https://user-images.githubusercontent.com/159488/27984677-31ef9c96-63dc-11e7-995d-145cc2258ebd.png">

**Comment by k22jung** [comment]
Are you using Ubuntu 16.04? Or is that Mac?

**Comment by nlohmann** [comment]
I'm using macOS Sierra.

**Comment by k22jung** [comment]
Okay I tried doing what you did with a new project on Ubuntu. It seems I get the same result as you - no errors. 

![image](https://user-images.githubusercontent.com/14689505/28045539-abbfea82-65ab-11e7-80cc-6d1d016f179b.png)

However, I have a second project that contains some cflags and libs for OpenCV, but I wouldn't think that would affect it. 

![image](https://user-images.githubusercontent.com/14689505/28045522-93984486-65ab-11e7-9514-1a6ddfc4cad9.png)

Also, the only major difference is that the project in the second image is version controlled under Git. Other than that, everything remains the same. Maybe it'll be better if I ask Eclipse support what's up.

**Comment by k22jung** [comment]
The kl_tracker project won't let me auto-complete any function related to `json`

**Comment by nlohmann** [comment]
This really sounds like an Eclipse issue.
