### ISSUE TITLE
Question: thread safety of read only accesses

### ISSUE THREAD

**Issue by kimwalisch** [nlohmann/json#651]
Hi,

Are ```nlohmann::json```objects thread safe for read only operations? E.g. assuming that the ```json``` object is not modified anymore after ```load_json()```, can I safely query the ```json``` object from multiple threads as in the example below?

```C++
// single threaded
auto json = load_json();

#pragma omp parallel for
for (int i = 0; i < threads; i++)
{
    // multi-threaded read only accesses
    double seconds = json["S2_easy"]["seconds"];
    int count = json["S2_easy"].count("s2_easy");
}
```

Thanks!

**Comment by nlohmann** [comment]
The library uses STL containers internally; that is, `std::vector` for JSON arrays and `std::map` for JSON objects. [Very brief googling](https://stackoverflow.com/questions/35959850/c-thread-safety-map-reading) gives me the feeling that concurrent reads should be fine.

**Comment by kimwalisch** [comment]
Thanks!

**Comment by nlohmann** [comment]
If you experience any issues, please let me know! I had no reports so far about multithreading applications.

**Comment by kimwalisch** [comment]
> If you experience any issues, please let me know! I had no reports so far about multi-threading applications.

My experiences:

I am using ```nlohmann::json``` in my math library to backup intermediate results of long running computations.  In the resume step (used e.g. after a crash) multiple threads read values from a single ```nlohmann::json``` object (none of the threads modifies the object).

Everything works as expected, there are no issues. I don't use any mutexes or locks during the resume step. I have tested the code using ```valgrind```and no issues have been detected.

Greetings,
Kim
