### ISSUE TITLE
how should I check a string is valid JSON string ?

### ISSUE THREAD

**Issue by zhishupp** [nlohmann/json#653]
I read all examples, but I didnt find a way to check a string is valid JSON string.
Is there an API to achieve this ? or I have to use "try catch" to check exceptions ?
thanks ^_^

**Comment by zhishupp** [comment]
ok, I noticed my question is just the same as #458 , so there will be a validation function in Release 3.0.1 ?

**Comment by nlohmann** [comment]
This is planned for 3.0.0, but I need to decide on how to best expose all possible parser/validation/format combinations which I discussed in #623. Therefore, this may take a while.

**Comment by nlohmann** [comment]
Duplicate of #458.

**Comment by machinetherapist** [comment]
@nlohmann any news ?

**Comment by nlohmann** [comment]
See https://json.nlohmann.me/api/basic_json/accept/

**Comment by anonymous9892** [comment]
In python use type(string_name)

**Comment by trraney328** [comment]
that is true
