### ISSUE TITLE
Adding additional push_back/operator+= rvalue overloads for JSON object

### ISSUE THREAD

**Issue by himikof** [nlohmann/json#657]
I propose adding the following three overloads to `basic_json`:

    void push_back(typename object_t::value_type&& val);
    value_type& operator+=(typename object_t::value_type&& val) &;
    value_type&& operator+=(typename object_t::value_type&& val) &&;

These are symmetric to existing `const typename object_t::value_type&` overloads, 
they bring the interface more in line with `std::map` (there are both `insert(value_type const&)` and `insert(value_type &&)` methods). The third overload allows rvalue json object to remain a temporary after `operator+=`.

Most importantly, these should allow for this simple code perform without copying:

    return json {
       {"type", "Polygon"},
    } += json::object_t::value_type {"coordinates", std::move(coordinates)};

Please note that this code is not equivalent to

    return json {
       {"type", "Polygon"},
       {"coordinates", std::move(coordinates)},
    };

because sadly in C++ `std::initializer_list` breaks perfect forwarding, and (possibly large) subobject is silently copied in this case.

Without these overloads, I think that this could only be expressed (without runtime overhead) by

    json result = {
       {"type", "Polygon"},
    };
    result.emplace("coordinates", std::move(coordinates));
    return result;

which is not very convenient.

Another alternative is to provide an explicit chainable method instead of (ab-)using `operator+=`. This could lead to cleaner code like:

    return json {
       {"type", "Polygon"},
    }.method_name("coordinates", std::move(coordinates));

This method should return an rvalue reference when called on an rvalue object, too.

**Comment by nlohmann** [comment]
This seems like a reasonable addition. PRs welcome!

**Comment by himikof** [comment]
Most of proposed additions (and probably all of them) are unnecessary since #663 landed and only complicate the API, therefore closing.

**Comment by nlohmann** [comment]
Thanks for checking back!
