### ISSUE TITLE
insert(or merge) object should replace same key , not ignore

### ISSUE THREAD

**Issue by itviewer** [nlohmann/json#661]
```cpp
json j1 = {{"one", 123}, {"two", 123}};
json j2 = {{"one", 456}};
j1.insert(j2.begin(), j2.end());
```

As key "one" has exist, now the result j1 is still {{"one", 123}, {"two", 123}}
while I think more commonly used logic is replace the same key，that is the result should be {{"one", 456}, {"two", 123}}

Thanks

**Comment by nlohmann** [comment]
This method should behave equivalent to [`std::map::insert`](http://en.cppreference.com/w/cpp/container/map/insert): The documentation there states:

> Inserts element(s) into the container, if the container doesn't already contain an element with an equivalent key.

**Comment by itviewer** [comment]
It was a pity that we limited by **std::map::insert** does not overwrite the exist key.
I'm not familiar with c++ stl, but I often use python and js ,either python's dict or js‘s array are implemented to replace the exist key. the approach of **std::map::insert** is really counter-intuitive.

So what is the problem with the operator [] ?example as
```
void merge(json &j1, const json &j2) {
    for (json::const_iterator it = j2.begin(); it != j2.end(); ++it) {
        j1[it.key()] = it.value();
    }
}
```

**Comment by nlohmann** [comment]
Interestingly, there will be a [`std::map::merge`](http://en.cppreference.com/w/cpp/container/map/merge) function in C++17 which again states:

> If there is an element in `*this` with key equivalent to the key of an element from `source`, then that element is not extracted from `source`.

**Comment by nlohmann** [comment]
From Python 3.6, we could borrow the ideas from [`update`](https://docs.python.org/3.6/library/stdtypes.html#dict.update) (emphasis added):

> Update the dictionary with the key/value pairs from other, **overwriting existing keys**. Return None.
>
> update() accepts either another dictionary object or an iterable of key/value pairs (as tuples or other iterables of length two). If keyword arguments are specified, the dictionary is then updated with those key/value pairs: d.update(red=1, blue=2).

So this would basically be your code with a different interface:

```cpp
void merge(const_reference j)
{
    if (not (is_object() and j.is_object()))
    {
        JSON_THROW(type_error::create(305, "cannot use merge with " + type_name()));
    }

    for (auto it = j.begin(); it != j.end(); ++it) {
        m_value.object->operator[](it.key()) = it.value();
    }
}
```

Any thoughts on this?

**Comment by jaredgrubb** [comment]
std::map::insert_or_assign basically does this, although it does not operate on a range, just one element. I would say that is the most discoverable name.

**Comment by itviewer** [comment]
I think @nlohmann 's suggestion ok for now, The interface name can be either merge or insert_or_assign，but the function implementation no need to use c++ 17's std::map::insert_or_assign，until c++ 17 becomes a formal standard and is supported by mainstream compilers.

**Comment by jaredgrubb** [comment]
Yes, I would *not* use the C++17 function until this library is C++17 only. It's very easy to implement the functionality. My suggestion was just about the naming.

**Comment by nlohmann** [comment]
I would implement `insert_or_assign` once I focus on C++ beyond C++11. I think the name is misleading if it would be used for more than a single value.

I tend to add the `merge` function I described in https://github.com/nlohmann/json/issues/661#issuecomment-317054390. However, I am unsure about the name, because [`std::map::merge`](http://en.cppreference.com/w/cpp/container/map/merge) has the semantics we do not want.

What about going the Python way and use `update`?

**Comment by itviewer** [comment]
> What about going the Python way and use update?

It's an acceptable solution

**Comment by nlohmann** [comment]
Via Twitter, I got further proposals:

- apply
- combine
- insert_or_update
- extend

**Comment by DmitryKuk** [comment]
`upsert` as [an option](http://sophia.systems/v2.2/api/sp_upsert.html)

**Comment by nlohmann** [comment]
Added a function`update`. I shall merge the feature branch once the Travis build succeeds.
