### ISSUE TITLE
How does from_json work?

### ISSUE THREAD

**Issue by itviewer** [nlohmann/json#662]
Sorry, I don't know if the question is right here, but I really needs help.
I need to convert json str to QString, and I defines the from_json function,
```cpp
void from_json(const json& j, QString& str)
{
    str = QString::fromStdString(j.get<std::string>());
}
```
`json object = {{"string","string"}};`

then I code this ,
`QString str = object["string"];`
it works no problem.but when I code this,
```
QString str;
str = object["string"];
```
then the compiler do not know how to compile，error with
`Error: C2593: "operator =" is not clear`

Do non-built-in variables can not be pre-defined? (I tried _int_ and _double_ type，it can work，)

**Comment by nlohmann** [comment]
I think @theodelrieu could help here.

**Comment by itviewer** [comment]
now I use 
```
QString str;
str = object["string"].get<QString>();
```
to explicit type conversion, it can work. maybe 
`QString str = object["string"];`  
can do some implicit type conversion during compilation ? while I don‘’t understand why
```
QString str;
str = object["string"];
```
can't do that.

Thanks, I think this issue can be closed.

**Comment by nlohmann** [comment]
`object["string"]` returns a `basic_json` object which can implicitly convert to `std::string`. `object["string"].get<QString>()` explicitly converts to `QString`. I'm not sure whether `QString` implicitly converts from `std::string` though...

Happy to hear that your issue is solved. :-)
