### ISSUE TITLE
How to iterate?

### ISSUE THREAD

**Issue by MartinKunz** [nlohmann/json#665]
Hi, i couldn't figure out how to iterate over some simple json data like this:

```
string sJson=
			"{"
				"\"data\": ["
					"{"
						"\"id\": \"1000\""
					"},"
					"{"
						"\"id\": \"1001\""
					"},"
					"{"
						"\"id\": \"1002\""
					"}"
				"]"
			"}";
```

Please could you provide an example how to print all the ids?
In addition not being able to forward declare your stuff is a big show stopper.

**Comment by MartinKunz** [comment]
Ok, i had to use

> json j = json::parse(sJson);

instead of

> json j = sJson;

The latter seems to add the sJson's text as a value to the json document.
After all this constructor doesn't make much sense for me...

**Comment by nlohmann** [comment]
You could also use a user-defined string literal:

```cpp
json j = R"(
{
  "key": "value",
  "another key": [1,2,3]
}
)"_json;
```
