### ISSUE TITLE
include problem, when cmake on osx

### ISSUE THREAD

**Issue by xiazhibin** [nlohmann/json#672]
I clone the project , and make install.
In my cpp file, I must `#include "nlohmann/json.hpp"` not `#include "json.hpp" as it mentions`

Why?

**Comment by dan-42** [comment]
This is due the latest changes in the CMakeLists.txt  to be consistent with the projects name and namespace. Also to avoid polute a systems ``` include ``` folder when other libraries might have a ``` json.hpp`` as well.

And for full consistency, the ``` develop ```-branch is preparing version 3.0.0 which will bring breaking changes as well. 
If you do not need special features from the current ``` develop-branch ``` it might be advised for you to use the master branch as the lates stable release.

Nonetheless it might be an option to enable when running ``` cmake && make install ``` to define if it should be in a subfolder or not.

**Comment by xiazhibin** [comment]
I see.Thanks a lot!
