### ISSUE TITLE
Could the parser locate errors to line?

### ISSUE THREAD

**Issue by PinkGabriel** [nlohmann/json#675]
hello again~
I use the lib to parse a json file like this:

std::ifstream ifs(filename);
json json_input;
ifs >> json_input;

Then I use the json class to do things. But if the input file has syntax error, the parser just reports what the error is, without where the error happens. Is it possible to locate errors to exactly which line the error happens in the json file?
Thanks!

**Comment by nlohmann** [comment]
Related: #301.

**Comment by nlohmann** [comment]
The location of parse errors is given in the version of the `develop` branch. It is unreleased code that will be released as version 3.0.0 later this year.

**Comment by nlohmann** [comment]
Examples for the exception strings are

```
[json.exception.parse_error.101] parse error at 2: syntax error - invalid number; expected digit after '-'; last read: '--'
```

for an input like `--1`.

**Comment by PinkGabriel** [comment]
Thanks for the reply!
Before asking I've searched the keyword locate but not location...Sorry for asking a same question..
I'll try the develop version, and hope the 3.0.0 everything goes well~~
thank you so much!

**Comment by nlohmann** [comment]
No worries! If you need further assistance, just open an issue.
