### ISSUE TITLE
create json object from string variable

### ISSUE THREAD

**Issue by sivapooja** [nlohmann/json#681]
How to create json object from string variable? i tried to create json object from string variable but doesn't work

`
json j = jsonStr_json
`

jsonStr is string variable which holds json string.

**Comment by theodelrieu** [comment]
User-defined literals only work with string literals:

```cpp
json j = "[0, true]"_json;
```

**Comment by nlohmann** [comment]
`_json` only works with string literals. To create a JSON value from a string, you need to call the `parse` function:

```cpp
json j = json::parse(jsonStr);
```

**Comment by nlohmann** [comment]
@sivapooja Does this solve your issue?

**Comment by sivapooja** [comment]
Yes, Thank you
