### ISSUE TITLE
Parse error while parse the json string contains  UTF 8 encoded document bytes string

### ISSUE THREAD

**Issue by sivapooja** [nlohmann/json#684]
Hi,
I am sending json string with UTF 8 encoded document bytees string from asp.net and receiving the json from c++ program , i am getting parse error while trying to parse the received json string to json object

```cpp
        string jsonStr = string( body.begin(), body.end() );               
         json j = json::parse(jsonStr);
```

Asp.net Json string 

```ASP
string docBytesStr = System.Text.Encoding.UTF8.GetString(docBytes, 0, docBytes.Length);
string jsonData = "{ \"template\" : \"1\", \"doc\":\"" + docBytesStr + "\"  }";
```

**Comment by nlohmann** [comment]
Could you post the error message and the exact content of `jsonStr`?

**Comment by sivapooja** [comment]
Error message is 

> std::invalid_argument'
  what():  parse error - unexpected '"'

the json string is very large because it contains the document byte string

**Comment by nlohmann** [comment]
The error message indicates that there is a JSON syntax error due to an unexpected quote character. Maybe `docBytesStr` contains a string with an unescaped quote? Can you validate that the string you pass to `parse` is valid JSON?

**Comment by nlohmann** [comment]
Any news on this?

**Comment by nlohmann** [comment]
@sivapooja Any news on this?
