### ISSUE TITLE
How to save json to file?

### ISSUE THREAD

**Issue by NeverMine17** [nlohmann/json#690]
I'm trying to save json to file and all I'm getting is some weird errors. Any help?
Here is all the info:

## Example code
```cpp
#include "json.hpp"
using jsonf = nlohmann::json;
jsonf jsonfile;

// ...

jsonfile["foo"] = "bar";

std::fstream file("key.json");
file << jsonfile;
```
## Error
```
json.hpp:843:9: error: static assertion failed: could not find to_json() method in T's namespace
         static_assert(sizeof(BasicJsonType) == 0,
         ^~~~~~~~~~~~~

json.hpp:843:9: error: static assertion failed: could not find to_json() method in T's namespace
```

**Comment by nlohmann** [comment]
This code works for me:

```cpp
#include "json.hpp"
#include <fstream>

using jsonf = nlohmann::json;

int main() {
    jsonf jsonfile;

    jsonfile["foo"] = "bar";

    std::ofstream file("key.json");
    file << jsonfile;
}
```

**Comment by NeverMine17** [comment]
Sorry, replace:
`jsonfile["foo"] = "bar";`
with
```cpp
const unsigned char a[] = "testing";
jsonfile["foo"] = a;
```

**Comment by nlohmann** [comment]
This works for me with the latest version of the `develop` branch and GCC 6.4.0 (macOS)

```cpp
#include "json.hpp"
#include <fstream>

using jsonf = nlohmann::json;

int main() {
    jsonf jsonfile;

    const unsigned char a[] = "testing";
    jsonfile["foo"] = a;

    std::ofstream file("key.json");
    file << jsonfile;
}
```

Note the output is

```js
{"foo":[116,101,115,116,105,110,103,0]}
```

Use `const char a[] = "testing";` if you want the content to be interpreted as characters rather than numbers.

**Comment by NeverMine17** [comment]
I guess thats fixed somehow, but now i get error:
```
 error: cannot convert ‘nlohmann::basic_json<>::value_type {aka nlohmann::basic_json<>}’ to ‘const unsigned char*’ in initialization
     const unsigned char * key = jsonfilekey["key"];                                                  ^
```

**Comment by nlohmann** [comment]
String are stored as `std::string` inside the JSON value. You can write

```cpp
std::string key = jsonfilekey["key"];
```

and organize the conversion to `const unsigned char*` from there.

**Comment by nlohmann** [comment]
Related: #683

**Comment by NeverMine17** [comment]
For unknown reasons, that corrupts the whole string.
My string contains of `base64(raw bytes)`.

**Comment by nlohmann** [comment]
What do you mean with "corrupts". Can you provide an example?

**Comment by nlohmann** [comment]
Any news on this?

**Comment by nlohmann** [comment]
@NeverMine17 Any news on this?

**Comment by ytfrdfiw** [comment]
> This code works for me:
> 
> ```c++
> #include "json.hpp"
> #include <fstream>
> 
> using jsonf = nlohmann::json;
> 
> int main() {
>     jsonf jsonfile;
> 
>     jsonfile["foo"] = "bar";
> 
>     std::ofstream file("key.json");
>     file << jsonfile;
> }
> ```

file.flush();
