### ISSUE TITLE
support the Chinese language in json string

### ISSUE THREAD

**Issue by yuanhui2015** [nlohmann/json#694]
new version doesn't support the Chinese language in json string, I has been fixed. please see the attachment.

**Comment by nlohmann** [comment]
There is no attachment.

The library does support UTF-8, so Chinese characters should not be a problem. Can you provide an example?

**Comment by yuanhui2015** [comment]
{"authority":0,"category":6,"category_id":"0","delete_by":"","delete_time":"","ext":"","ext_link":0,"is_delete":0,"is_file":0,"is_share":0,"lv_creator":"","lv_id":1,"lv_size":0,"lv_time":"","name":"回收站","x_id":6,"x_pid":1}

**Comment by nlohmann** [comment]
What is the error message and how does the code look like that produces this error message?

**Comment by yuanhui2015** [comment]
error occured in the function get_token() when parse the Chinese string

**Comment by yuanhui2015** [comment]
can you find my attachment in this topic, I didn't find it.

**Comment by nlohmann** [comment]
This code works for me:

```cpp
#include <json.hpp>
#include <iostream>
using json = nlohmann::json;
 
int main()
{
    std::string s = R"({"authority":1,"category":6,"category_id":"0","delete_by":"","delete_time":"","ext":"","ext_link":0,"is_delete":0,"is_file":0,"is_share":0,"lv_creator":"","lv_id":1,"lv_size":0,"lv_time":"","name":"回收站","x_id":6,"x_pid":1})";
    json j = json::parse(s);
    std::cout << std::setw(2) << j << std::endl;
}
```

What is the error message and how does the code look like that produces this error message?

**Comment by yuanhui2015** [comment]
test code is as below:
CString strText;
m_oJsonView.GetWindowTextW(strText);
std::string szJson = ToSTR(strText);
json j3 = json::parse(szJson);

**Comment by nlohmann** [comment]
Can you make sure the content of `szJson` is exactly the one from https://github.com/nlohmann/json/issues/694#issuecomment-321780677 ?

What is the error message?

**Comment by nlohmann** [comment]
(You seem to copy the string from window text into a `CString` variable. Maybe the string is encoded as UTF-16 or UTF-32? The library only supports UTF-8.)

**Comment by josephsmeng** [comment]
GetWindowTextW  do not mean you get a utf8 encode string!!
@nlohmann it's his problem, don't waste time here

**Comment by yuanhui2015** [comment]
error message is:parse error - unexpected '"' on line 11615.
I used VS2015 and the charset I used is unicode.

**Comment by nlohmann** [comment]
Which Unicode? The library only supports UTF-8.

**Comment by yuanhui2015** [comment]
@josephsmeng I convert CString to std::string by my funciton ToSTR, do you see it?
std::string ToSTR(CString cs)
{
	std::string sstring = "";
	if(cs.GetLength() == 0)
		return sstring;

	BSTR bstr = cs.AllocSysString();
	_bstr_t bstr_t(bstr);	
	sstring.append(bstr_t);
	SysFreeString(bstr);

	return sstring;
}

**Comment by josephsmeng** [comment]
@nlohmann you are just so nice, let the young man google his problem, and lean some thing about Unicode ....

**Comment by yuanhui2015** [comment]
when I create a new project by VS2015, the default charset is Unicode.  you can find it in VS as below
solution->property->config property->normal->charset

**Comment by nlohmann** [comment]
"Unicode" describes a family of encodings. For this library, the string you pass to `parse` needs to be UTF-8 encoded. UTF-16 or UTF-32 are not supported.

**Comment by yuanhui2015** [comment]
got it, thank you nlohmann.
you are great~~

**Comment by josephsmeng** [comment]
你可以从这里开始 http://www.ruanyifeng.com/blog/2007/10/ascii_unicode_and_utf-8.html，
你的问题其实只需要把UTF-16编码的字符串转换成UTF-8的，
我只告诉你到这里，你需要再自己学习一下字符串编码相关的知识，这是很基础的问题。

**Comment by yuanhui2015** [comment]
呵呵，我不喜欢在编码上浪费时间。
我只修改了json.hpp几行代码，就完全可以支持中文了，你觉得还有必要转换编码么？

**Comment by josephsmeng** [comment]
你高兴就好啦😄😄😄

**Comment by JueLance** [comment]
@yuanhui2015 

> when I create a new project by VS2015, the default charset is Unicode. you can find it in VS as below
solution->property->config property->normal->charset

this setting is not meaning your program character is UTF-8. It means the windows library function will use Unicode version funciton, such as SetWindowTextA() and SetWindowTextW(). When you use "Use Unicode Character Set", the unicode function - SetWindowTextW will be call finally, not SetWindowTextA.

**Comment by smily1223** [comment]
> 呵呵，我不喜欢在编码上浪费时间。 我只修改了json.hpp几行代码，就完全可以支持中文了，你觉得还有必要转换编码么？

老哥怎么解决中文的问题的？能说一下吗？

**Comment by JueLance** [comment]
> > 呵呵，我不喜欢在编码上浪费时间。 我只修改了json.hpp几行代码，就完全可以支持中文了，你觉得还有必要转换编码么？
> 
> 老哥怎么解决中文的问题的？能说一下吗？

不建议直接改代码，可以看看我之前在类似问题的解决方向：https://github.com/nlohmann/json/issues/1022

**Comment by smily1223** [comment]
> 

好的，谢谢老哥

**Comment by Olvi73** [comment]
In Qt project, you can use
`ui->lineEdit->text().toUtf8().data()` to get a value
and use
`ui->textEdit->setText(QString::fromUtf8(j.dump(4).c_str()));`
to set this text

**Comment by wuhaitao93** [comment]
1、确保windows中源文件（visual studio中）都是utf-8 with bom格式；
2、确保vs---项目属性---c/c++---命令行 ：其他选项 中有  /utf-8；
至此，json可实现正常解析，保存到文件不会乱码，但是打印到控制台仍然乱码，是因为控制台默认编码方式是936 GBK，要想解决，有两种方法：
a、写一个U2G函数，把UTF-8转换为GBK，打印到控制台不乱码；
b、https://blog.csdn.net/weixin_45265547/article/details/121931397 参考这个，把控制台默认编码方式改为UTF-8，这种方式不建议，因为windows上默认都是GBK输出，改了后其他工程可能会乱码；

综上，nlohmann在源码中应该考虑windows环境下输出到控制台时做U2G转换，不过考虑开源不易，期待有朋友提pr改一下~

**Comment by nlohmann** [comment]
The library only supports UTF-8.

**Comment by wuhaitao93** [comment]
> The library only supports UTF-8.

Yes, so let the users solve other encoding problems themselves ^.^
