### ISSUE TITLE
unique_ptr for ownership

### ISSUE THREAD

**Issue by hrobeers** [nlohmann/json#7]
Since you're using C++11, wouldn't it be better to manage object ownership using unique_ptr?

I will issue a pull request when I start using your library.

**Comment by hrobeers** [comment]
Let's quote Reddit again ;)


[–]hrobeers 3 points 13 hours ago 
If I'm not mistaken, there is no memory overhead because it just stores the raw pointer internally. But there could be a little runtime performance overhead when using another deleter. So when using the default deleter instead of manually call delete, there is no overhead.

[–]Splanky222 3 points 12 hours ago 
No overhead with regular destructors. Unique_ptr is just a wrapper around a raw pointer so you can use RAII

**Comment by hrobeers** [comment]
This would also fix issue #11

**Comment by nlohmann** [comment]
Alright - I understand that using unique_ptrs will be really nice. However, it seems as if the situation where pointers are inside a union makes the code quite difficult to port to unique_ptr in case we start swapping and moving. At lease this is what I take away from http://stackoverflow.com/questions/24713833/using-a-union-with-unique-ptr

I may need some more time to really understand the problem, but currently it seems as if I haven't understood all the implications yet. If you have any helping reference, I would be glad.

**Comment by hrobeers** [comment]
Yes it is indead true that smart pointers cannot be used inside unions. I missed the fact that you were heavily relying on a union, so using unique_ptrs is not possible.
When I start using your library, I'll try to find some other ways to manage memory.

Thanks for sharing this code, it looks really nice!

**Comment by nlohmann** [comment]
Thanks! Until then, we have to rely on Valgrind that no memory is leaked ;-)

**Comment by cmaloney** [comment]
For the json::iterator and json::const_iterator you can use optional types (Like std::optional which was unfortunately dropped from c++14), as a replacement for the explicit new / delete calls. Also can give a slight speed boost because it eliminates a indirection. std::unique_ptr would work as well though / take less additional boilerplate.
