### ISSUE TITLE
Issues when adding values to firebase database

### ISSUE THREAD

**Issue by jussihi** [nlohmann/json#704]
Hello, I'm having some issues adding values to a firebase database using this json library.

The test["pi"] adds into the firebase very well, but then when I try to add the test["pia"]["pia"] it responds with a  "error" : "Invalid data; couldn't parse JSON object, array, or value."

Here is my code:

    `json test;
     test["pi"] = 1.41;
     test["pia"]["pia"] = 2.0; 
     CURLcode res;
     struct curl_slist *headers = NULL;
     headers = curl_slist_append(headers, "Content-Type: application/json");
     curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
     curl_easy_setopt(curl, CURLOPT_URL, "https://aaaa.firebaseio.com/bbbb.json");
     curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, "PUT");
     curl_easy_setopt(curl, CURLOPT_POSTFIELDS, moi.dump());
     res = curl_easy_perform(curl);
     std::cout << res << std::endl;
     curl_slist_free_all(headers);
     curl_easy_cleanup(curl);`

**Comment by jussihi** [comment]
I found this with a solution that I should wrap my JSON into single quotes:
https://stackoverflow.com/questions/33683757/firebase-invalid-data-couldnt-parse-json-object

Can I do it automatically with this json library?

**Comment by jussihi** [comment]
More input; if I wirte this code:

    test["asd2"] = {{"asd3","asd2"},{"asd4","asd5"}};
    std::string s = moi.dump();
    std::cout << s << std::endl;

I get output `{"asd2":{"asd3":"asd2","asd4":"asd5"}}` from the cmd.

Now if I use libcurl from cmd, with input:
`curl -H 'Content-Type:application/json' -X PUT -d "{\"asd2\" :{\"asd3\": \"asd2\", \"asd4\":\"asd5\"}}" "https://....`

I get the exact same output ( `{"asd2":{"asd3":"asd2","asd4":"asd5"}}` ), but only using libcurl from terminal succees.. What is going on?

**Comment by nlohmann** [comment]
No, adding single quotes around a JSON text is not supported by the library, but can be done without problems in client code.

Unfortunately, I do not understand your third comment https://github.com/nlohmann/json/issues/704#issuecomment-324028519. What is the issue?

**Comment by jussihi** [comment]
Thank you very much for responding. I'm currently pulling my hair off because of this. Yes as you can see from this post it doesn't seem to need those single quotes anymore.. But here is what I got:

So, giving this exact input to my curl.exe straight from terminal works;
curl -H 'Content-Type:application/json' -X PUT -d "{\"asd2\" :1.41, \"pi2\" : 2.82}" "https://

It inputs no problem; also giving raw string from my C++ program like this works;
curl_easy_setopt(curl, CURLOPT_POSTFIELDS, "{\"pi\":1.41,\"pi2\":2.82}");


but then when I try to feed it with your json library output, it doesn't work:
curl_easy_setopt(curl, CURLOPT_POSTFIELDS, j.dump());

**Comment by nlohmann** [comment]
That's weird. Can you make sure the strings are identical to the byte? There may be some subtle issue with escaping.

**Comment by jussihi** [comment]
Can you point me a way to make clear they are identical?

Can I just memcmp with j.dump().data() and string.data() ?

**Comment by nlohmann** [comment]
Well, storing both in a `std::string` and check if they are equal with `==` should be sufficient. It's just a guess, but the first thing I would try if they "look" the same, but treated differently.

**Comment by theodelrieu** [comment]
I might miss something here, but are you passing a `std::string` to the curl API?
Does that even compile?

**Comment by jussihi** [comment]
@nlohmann the strings are the same

@theodelrieu yes it does, without warnings. and now as you ask, yes, it works if I put in j.dump().data()

**Comment by theodelrieu** [comment]
@jussihi It's because of varargs I guess, that's weird, glad it fixes your problem!
