### ISSUE TITLE
pointer to json parse vector

### ISSUE THREAD

**Issue by kessero** [nlohmann/json#711]
My main:
```cpp
int main(int argc, char *argv[])
{
  // read a JSON file
  std::stringstream ss;
  std::ifstream i("filee.json");
  json j_complete = json::parse(i);
  std::vector < int > data_send_to_LED;
  for (int i =0; i<j_complete["tablica"].size(); i++){
    data_send_to_LED.push_back(j_complete["tablica"][i].get<int>());
  }
  for (int i =0; i<data_send_to_LED.size(); i++){
    cout <<"data send: "<< data_send_to_LED[i]<<endl;
  }
  json j_vec(data_send_to_LED);
  long int pv = j_vec.get_ptr<json::number_integer_t*>();
  cout << j_vec.size() << endl;
  cout << j_vec << endl;
  cout << pv << endl;
...
n = write(sockfd,pv, j_vec.size()+1);
```

In general I want to send the contents of the file.json file to the server which accepts data in json format.
J_vec shows -  [192,0,0,1,0,0,1,0,84,76,126]
Pv.size shows 11 elements and this is OK 
pv shows 0
and n returns bad address?
I can skip the vector in the program and send the data directly form file.

**Comment by nlohmann** [comment]
`long int pv = j_vec.get_ptr<json::number_integer_t*>();` is weird: you store a pointer to `json::number_integer_t` inside a `long int` variable.

**Comment by theodelrieu** [comment]
First, you could use `j_complete.at("tablica").get<std::vector<int>>()` to avoid a loop, but to fix your problem, try to use `j_vec.get_ptr<json::array_t*>()`.

**Comment by kessero** [comment]
Now:
```
std::vector < int > data_send_to_LED;
  for (int i =0; i<j_complete["tablica"].size(); i++){
    data_send_to_LED.push_back(j_complete["tablica"][i].get<int>());
  }
  //j_complete.at("tablica").get<std::vector<int>>();
  for (int i =0; i<data_send_to_LED.size(); i++){
    cout <<"data send: "<< data_send_to_LED[i]<<endl;
  }
  json j_vec(data_send_to_LED);
  auto pv = j_vec.get_ptr<json::array_t*>();
  cout << j_vec.size() << endl;
  cout << pv << endl;

```
I don't have errors in this program but server shows mi error:

>  what():  [json.exception.parse_error.101] parse error at 1: syntax error - invalid literal; last read: 'p'
> pBg�� Cg
>

**Comment by nlohmann** [comment]
Your input to the `parse` function seems corrupted. Can you make sure you pass proper JSON?

**Comment by kessero** [comment]
I'm not sure what you mean but my json file looks like this:
```
{
  "tablica": [192, 0, 0, 1, 0, 0, 1, 0,84, 76, 126]
}
```

**Comment by nlohmann** [comment]
Well the parser exception says the first read character is `p`.

**Comment by kessero** [comment]
On server side bafore json error:

> bufor: p��{:

So some ^%&(*(* are sending.

**Comment by gregmarr** [comment]
As Niels and Theo have pointed out, it is most likely that `pv` is not of the proper data type.  What does the receiving side think is the format of the data being received?

**Comment by gregmarr** [comment]
If it's expecting json, you probably want:

    int main(int argc, char *argv[])
    {
      // read a JSON file
      std::ifstream i("filee.json");
      json j_complete = json::parse(i);
      json j_vec = j_complete["tablica"];
      cout << j_vec.size() << endl;
      cout << j_vec << endl;
      std::string json = j_vec.dump();
      n = write(sockfd, json.data(), json.size());

**Comment by nlohmann** [comment]
@kessero Any news on this?

**Comment by kessero** [comment]
Thnx gregmarr solve my problem i have to read what dump do in doc but works. Sorry for late response
