### ISSUE TITLE
Serialization of array of not same model items

### ISSUE THREAD

**Issue by Haaxor1689** [nlohmann/json#712]
When trying to serialize json string that contains array of elements that have a different model, serialization throws first time it encounters a different type for the same key. Simplified example of my situation is below:

```json
[
  {
    "id": 0,
    "name": "adsad"
  },
  {
    "id": "123",
    "name": "aawew"
  }
]
```

Is there a way to parse such json string?

**Comment by nlohmann** [comment]
There is no problem with this. This program parses your input and prints it:

```cpp
#include "json.hpp"
#include <iostream>

using json =  nlohmann::json;

int main() {
    std::string text = R"([
    {
        "id": 0,
        "name": "adsad"
    },
    {
        "id": "123",
        "name": "aawew"
    }
    ])";
    
    json j = json::parse(text);
    
    std::cout << std::setw(2) << j << std::endl;
}
```

Output:

```js
[
  {
    "id": 0,
    "name": "adsad"
  },
  {
    "id": "123",
    "name": "aawew"
  }
]
```

What is your error message?

**Comment by Haaxor1689** [comment]
So I've solved this issue now. I was getting the error in `from_json` method that converts that json to my model class.

```cpp
class Model {
    int id;
    std::string name;
}
```

Solution was pretty straightforward once I found out that I can check the type of data that lies in json type on runtime with this simple function:

```cpp
int getInt(const json& value) {
    return value.is_string() ? std::stoi(value.get<std::string>()) : value.get<int>();
}

So because I know that the value for id should be int but is sometimes saved as a string I just call this function when reading the value in `from_json` function.
