### ISSUE TITLE
How to detect parse failure?

### ISSUE THREAD

**Issue by davechurchill** [nlohmann/json#715]
Apologies for the seemingly simple question, but there is no example for detecting a parse failure on the readme. Maybe one could be added, or a simple explanation of how to detect a parse failure could be given?

**Comment by davechurchill** [comment]
@nlohmann I see you saw this and added it to documentation, in the mean time while you work on it could you let me know how? I need it for a project :)

**Comment by nlohmann** [comment]
Parse errors are indicated by exceptions. In the 2.x.x series, the exception type is `std::invalid_argument`, in 3.x.x (`develop` branch), the exception type is `json::parse_error`. See https://github.com/nlohmann/json/blob/develop/doc/examples/parse_error.cpp for an example of the latter.

**Comment by davechurchill** [comment]
Thank you for the quick response. Might you consider adding a simple boolean to the json object indicating whether or not there was a parse error? Sometimes it is quite inconvenient to rely on exceptions for some things. Here's a sample use-case:

std::ifstream in(filename)
json j;
in >> j;

if (j.parseError()) { print error message }

**Comment by gregmarr** [comment]
What is inconvenient about this?

    std::ifstream in(filename)
    json j;

    try {
        in >> j;
    } catch(json::parse_error) {
        print error message;
    }

**Comment by davechurchill** [comment]
Nothing is inconvenient about the code itself, apologies for implying that. It is inconvenient in the case where I am working with a codebase that has exceptions disabled :(

**Comment by gregmarr** [comment]
Oh, that's a different case altogether.  #582 

    std::ifstream in(filename)
    json j = json::parse(in, nullptr, false);
    if (j.is_discarded()) { print error message }

**Comment by davechurchill** [comment]
That's exactly what I'm looking for, thank you!

**Comment by naimac** [comment]
it'll be interesting for newbies like me, to remind that for parsing a jsonFile from the program's argument (linux) we have to do like so :

[linux] ./a.out "`cat myFile.json`"
[main.cpp] std::string myVar(argv[1])
