### ISSUE TITLE
Compile-Error C2100 (MS VS2015) in line 887 json.hpp

### ISSUE THREAD

**Issue by Rockettomatoo** [nlohmann/json#719]
Hey there,

I'm happy to have found this awesome repo for parsing json but unfortunately `json.hpp` doesn't compile in my current project.
My Project-Setup is a plain win32-commandline-project with the `json.hpp` from the master-branch pasted in.

As the Heading says, the Error is in line 887:
```
//error: 1>c:\vsprojects\path\to\project\source\json.hpp(887): error C2100: Invalid Dereferencing

// code arround line 887:

// taken from ranges-v3
template<typename T>
struct static_const
{
    static constexpr T value{}; //line 887
};
```

Any suggestions for that error?
Thanks in advance

**Comment by theodelrieu** [comment]
Yep I recognize that one. You need VS2015 Update 3 for 2.1.1 to work.

**Comment by nlohmann** [comment]
Duplicate: #467.
