### ISSUE TITLE
Determine the type from error message.

### ISSUE THREAD

**Issue by MattiasEppler** [nlohmann/json#720]
I get the erros
"could not find to_json() method in T's namespace"
"could not find from_json() method in T's namespace"

but I do not know for which type the methods are not found. How do I get this information?

**Comment by theodelrieu** [comment]
I assume you're using Visual Studio, which doesn't show a stack trace after the `static_assert`. I have to add that for 3.0. 

Meanwhile you can modify `json.hpp` yourself:

```cpp

// Somewhere in nlohmann::detail
struct from_json_fn {
static void call(T arg) {
  arg.show_me_the_type();
}
};
```

Do the same inside `to_json_fn` and that should help you to debug.

**Comment by MattiasEppler** [comment]
Hi. Yes i use Visual studio. Ok thanks for the information.

Do I have to add this

static void call(T arg) {
  arg.show_me_the_type();
}

inside "struct from_json_fn"

or just the arg.show_me_the_type(); to the existing call?

**Comment by theodelrieu** [comment]
Sorry I was on my phone, so hard to be explicit. You have to add it to the existing call, the one with the `static_assert`.

**Comment by MattiasEppler** [comment]
Sorry.

this one:

```
    template<typename BasicJsonType, typename T>
    void call(const BasicJsonType&, T&, priority_tag<0>) const noexcept
    {
        static_assert(sizeof(BasicJsonType) == 0,
                      "could not find from_json() method in T's namespace");
    }
```

where to find the arg?

**Comment by theodelrieu** [comment]
You have to add it:

```cpp
void call(const BasicJsonType&, T& arg, priority_tag<0>) const noexcept
```

**Comment by MattiasEppler** [comment]
Oh... I missed this :-)
ok.. now I get an error, 'show_me_the_type' is not a member of 'MyTpeToSerialize'.
Is this the trick?

**Comment by theodelrieu** [comment]
Yes it is. I have this in my TODO list, it will be done in 3.0 by default.

**Comment by MattiasEppler** [comment]
Hm ok.  But I do not understand why arg.show_me_the_type(); is only called if the static_assert is false.

**Comment by theodelrieu** [comment]
In fact, this `call` overload is only called if you forgot to add a `from/to_json` method.
That's why the `static_assert` in this overload does a `sizeof(T) == 0` check, that will **always** fail, this can be seen as the "failure" overload.

**Comment by MattiasEppler** [comment]
Ok. Thanks for the Explanation.

**Comment by nlohmann** [comment]
@theodelrieu Thanks a lot for taking care of this issue!
