### ISSUE TITLE
When will be 3.0 in master?

### ISSUE THREAD

**Issue by bajimu** [nlohmann/json#721]
When will be 3.0 in master?

**Comment by nlohmann** [comment]
Due to semantic versioning, the 3.0.0 release will be a rare opportunity to add API-breaking changes. Therefore, I do not want to rush the release.

However, I hope to finish the release this year.

**Comment by bajimu** [comment]
@nlohmann thanks. Which version should I use for big network project now (2.0 (master) or (3.0 beta (develop))?

**Comment by nlohmann** [comment]
I would propose using the `develop` version and would ask you to open issues when you encounter problems.

**Comment by bajimu** [comment]
@nlohmann ok, thanks.

**Comment by nlohmann** [comment]
I scheduled the 3.0.0 release for December 17, 2017.
