### ISSUE TITLE
Has this lib the unicode (wstring) support?

### ISSUE THREAD

**Issue by bajimu** [nlohmann/json#722]
Has this lib the unicode (wstring) support?

**Comment by nlohmann** [comment]
Yes, the library supports UTF-8. No, it can not parse input from `std::wstring`.

**Comment by bajimu** [comment]
@nlohmann, so how i can get unicode string from json ? String support Ascii ony.

**Comment by nlohmann** [comment]
`std::string` is agnostic to the encoding of the bytes it stores, and we assume UTF-8. You can use it as follows:

```cpp
std::string s = "[\"öäüß😃\"]";
std::json j = json::parse(s);
```

**Comment by nlohmann** [comment]
Do you need further assistance?

**Comment by nlohmann** [comment]
I added an FAQ entry: https://json.nlohmann.me/home/faq/#wide-string-handling
