### ISSUE TITLE
Using json Object as value in a map

### ISSUE THREAD

**Issue by FATEDx** [nlohmann/json#725]
I have a map, that have key string, and json as the value 
`std::map<std::string, json> mList;`
Then,
`std::map<std::string, json>::iterator i = mList.at(name);`
`std::map<std::string, json>::iterator end = mList.end();`

When i try to access the iterator, it keep giving me error about 
Error	C2338	could not find from_json() method in T's namespace

I have no idea what is going on, can someone help?

**Comment by nlohmann** [comment]
`std::map<std::string, json>::iterator i = mArchetypeList.at(name);` calls `at` which returns a reference and not an iterator. Can you provide a detailed error message?

**Comment by FATEDx** [comment]
1>c:\users\jordan lim\desktop\septem\engine\source\septemengine\system\json\json.hpp(1132): error C2338: could not find from_json() method in T's namespace
1>  c:\users\jordan lim\desktop\septem\engine\source\septemengine\system\json\json.hpp(1140): note: see reference to function template instantiation 'void nlohmann::detail::from_json_fn::call<BasicJsonType,T>(const BasicJsonType &,T &,nlohmann::detail::priority_tag<0>) noexcept const' being compiled
1>          with
1>          [
1>              BasicJsonType=nlohmann::json,
1>              T=std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const std::string,nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>>>
1>          ]
1>  c:\users\jordan lim\desktop\septem\engine\source\septemengine\system\json\json.hpp(1188): note: see reference to function template instantiation 'void nlohmann::detail::from_json_fn::operator ()<_Ty,ValueType>(const BasicJsonType &,T &) noexcept const' being compiled
1>          with
1>          [
1>              _Ty=nlohmann::json,
1>              ValueType=std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const std::string,nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>>>,
1>              BasicJsonType=nlohmann::json,
1>              T=std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const std::string,nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>>>
1>          ]
1>  c:\users\jordan lim\desktop\septem\engine\source\septemengine\system\json\json.hpp(3493): note: see reference to function template instantiation 'void nlohmann::adl_serializer<T,void>::from_json<const nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>&,T>(BasicJsonType,ValueType &) noexcept' being compiled
1>          with
1>          [
1>              T=std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const std::string,nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>>>,
1>              BasicJsonType=const nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer> &,
1>              ValueType=std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const std::string,nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>>>
1>          ]
1>  c:\users\jordan lim\desktop\septem\engine\source\septemengine\system\json\json.hpp(3493): note: see reference to function template instantiation 'void nlohmann::adl_serializer<T,void>::from_json<const nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>&,T>(BasicJsonType,ValueType &) noexcept' being compiled
1>          with
1>          [
1>              T=std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const std::string,nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>>>,
1>              BasicJsonType=const nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer> &,
1>              ValueType=std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const std::string,nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>>>
1>          ]
1>  c:\users\jordan lim\desktop\septem\engine\source\septemengine\system\json\json.hpp(3755): note: see reference to function template instantiation 'ValueType nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>::get<ValueType,std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const StringType,nlohmann::basic_json<std::map,std::vector,StringType,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>>>,0>(void) noexcept const' being compiled
1>          with
1>          [
1>              ValueType=std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const std::string,nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>>>,
1>              StringType=std::string
1>          ]
1>  c:\users\jordan lim\desktop\septem\engine\source\septemengine\system\json\json.hpp(3755): note: see reference to function template instantiation 'ValueType nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>::get<ValueType,std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const StringType,nlohmann::basic_json<std::map,std::vector,StringType,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>>>,0>(void) noexcept const' being compiled
1>          with
1>          [
1>              ValueType=std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const std::string,nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>>>,
1>              StringType=std::string
1>          ]
1>  c:\users\jordan lim\desktop\septem\engine\source\septemengine\system\gameobjects\gameobjectfactory.cpp(334): note: see reference to function template instantiation 'nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>::operator ValueType(void) const<std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const StringType,nlohmann::basic_json<std::map,std::vector,StringType,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>>>,0>' being compiled
1>          with
1>          [
1>              ValueType=std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const std::string,nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>>>,
1>              StringType=std::string
1>          ]
1>  c:\users\jordan lim\desktop\septem\engine\source\septemengine\system\gameobjects\gameobjectfactory.cpp(334): note: see reference to function template instantiation 'nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>::operator ValueType(void) const<std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const StringType,nlohmann::basic_json<std::map,std::vector,StringType,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>>>,0>' being compiled
1>          with
1>          [
1>              ValueType=std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const std::string,nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>>>,
1>              StringType=std::string
1>          ]

**Comment by nlohmann** [comment]
Can you also provide the code in gameobjectfactory.cpp(334) and maybe some context lines?

**Comment by FATEDx** [comment]
Oh dear, i found my mistake. Sorry. 
I would like to ask if storing all the data in the json object in this manner, will if have any effiency problem?

**Comment by nlohmann** [comment]
Under the hood, objects are stored in an `std::map`. Each value has some overhead (a few pointer), but basically it should not make things too bad.

**Comment by FATEDx** [comment]
Alright Thank you so much! This is very helpful
