### ISSUE TITLE
Project's name is too generic and hard to search for

### ISSUE THREAD

**Issue by guidow** [nlohmann/json#730]
The project's name is very generic, which makes it hard to search for in, for example, internet search engines or the package repositories of various operating systems. My first impulse upon finding this library was to see if it was already present in my distribution's package repository, but how should I even go about that? Searching for just "json" is not going to be helpful. (Turns out googling for "nlohmann json" works better, but still...)

The name is also bound to lead to some confusion, as it is already the name for the format/meta-format itself.

This also makes it awkward to specify a dependency on this library in a way that will likely work across distributions.

The full name of the project, "JSON for Modern C++", on the other hand, is too unwieldy, consists of several words and does not actually seem to be used much.

**Comment by nlohmann** [comment]
Duplicate #377.

**Comment by nlohmann** [comment]
After four years, I still can't think of a better name...

For what it's worth: Googling for "json c++" brings the library as first hit. And when you search for "json" at Github, it is also the first hit.

**Comment by nlohmann** [comment]
Any ideas?

**Comment by NeverMine17** [comment]
@nlohmann maybe jsony, js+, ossjson, mjson (like "modern json")

**Comment by theodelrieu** [comment]
I was thinking about `njson` personally, but `mjson` seems ok too

**Comment by guidow** [comment]
If you are okay with using your own name, how about ```nlohmann-json```? Another option might be ```modernjson++```, which is pretty close to the official long name already.

My opinion on the matter:  
It does not have to be particularly fancy or creative, it just shouldn't be just "json", simply because that is too ambiguous.

**Comment by NeverMine17** [comment]
pra*js*er  :smile:

**Comment by guidow** [comment]
There is already a Python library called mjson: https://bolerio.github.io/mjson/

**Comment by nlohmann** [comment]
I'm not convinced.

**Comment by nlohmann** [comment]
I know it would be nice to have a "better" name, but I'm not willing to change it just for having a new one.
