### ISSUE TITLE
Benchmarks for Binary formats

### ISSUE THREAD

**Issue by D1amond** [nlohmann/json#733]
It would be nice to have an idea of the parsing time difference between a JSON file and a binary serialized version of the same file.

This could be included in the library's benchmarks.

**Comment by hackboxlive** [comment]
I am new to the library, but I would definitely like to work on this issue. Could you point me into some right direction?

**Comment by nlohmann** [comment]
@hackboxlive We would need some benchmark code (in addition to https://github.com/nlohmann/json/tree/develop/benchmarks) that compares the parsing time for various JSON files compared to their CBOR/MessagePack versions.
