### ISSUE TITLE
Compilation error with std::map<std::string, std::string> on vs 2015

### ISSUE THREAD

**Issue by leozzyzheng** [nlohmann/json#734]
```C++
using json = nlohmann::json;
json j;
std::map<std::string, std::string> m;
m = j.get<decltype(m)>();
```
it says `error C2665: 'std::pair<const _Kty,_Ty>::pair': none of the 2 overloads could convert all the argument types`

if I change to 
```
m = j;
```
it says `'operator =' is ambiguous`

Did I miss anything about converting map data to/from json ?

**Comment by nlohmann** [comment]
I can run your above example without problems with Xcode

```cpp
#include "json.hpp"

using json = nlohmann::json;

int main(int argc, char const *argv[])
{
    json j = {{"key", "value"}};
    std::map<std::string, std::string> m;
    m = j.get<decltype(m)>();
}
```

I can confirm the error with `m = j;`. There was a similar ticket, but I can't find it right now. Maybe @theodelrieu remembers it.

**Comment by leozzyzheng** [comment]
oh, sorry forget to tell that I faced the problem on vs2015.

**Comment by nlohmann** [comment]
Just to make sure: Can you compile and run the test suite without problems?

**Comment by leozzyzheng** [comment]
no, I'm using the code
```c++
#include "json.hpp"

using json = nlohmann::json;

int main(int argc, char const *argv[])
{
    json j;
    std::map<std::string, std::string> m;
    m = j.get<decltype(m)>();
}
```
I think there is no difference between your code and mine. :)

**Comment by nlohmann** [comment]
Do you run at least Microsoft Visual C++ 2015 / Build Tools 14.0.25123.0?

**Comment by leozzyzheng** [comment]
vs2015 with update 3, I need tomorrow to check the version number.

**Comment by leozzyzheng** [comment]
I have check that I'm using 14.0.25420.1
![image](https://user-images.githubusercontent.com/6134295/30254616-fa7f289c-96cd-11e7-935d-7b5d99dbab1d.png)

I think it should be without problems.

**Comment by leozzyzheng** [comment]
And I have switched to vs 2017, still has problem.

**Comment by leozzyzheng** [comment]
The last call stack in json.hpp is here:
![image](https://user-images.githubusercontent.com/6134295/30255468-b34cbec2-96d6-11e7-8461-d21def36cf03.png)

`obj = CompatibleObjectType(begin(*inner_object), end(*inner_object));`
 It calls
![image](https://user-images.githubusercontent.com/6134295/30255484-cfbdc8f8-96d6-11e7-9395-5015c4aaecd9.png)
according to the error call stack. I can see the template `_Iter` is `std::_Tree_const_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const std::string,nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>>>>`.

And this type is used to construct map at here
![image](https://user-images.githubusercontent.com/6134295/30255533-14218336-96d7-11e7-85ee-a3a078684d84.png)
which needs
```
'std::pair<const _Kty,_Ty>::pair(std::pair<const _Kty,_Ty> &&)'
with
[
     _Kty=std::string,
    _Ty=std::string
]
or       'std::pair<const _Kty,_Ty>::pair(const std::pair<const _Kty,_Ty> &)'
with
[
    _Kty=std::string,
    _Ty=std::string
]
```

But `_Args` is `const std::pair<const StringType,nlohmann::basic_json<std::map,std::vector,StringType,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>>`

I can see the second type of std::pair is not the std::string, so I think this is the problem. I'm not very familiar with template, so maybe the error is caused by another reason. :)

**Comment by leozzyzheng** [comment]
I found if I change std::map<std::string, std::string> to std::map<std::string, int>, then it works without problems.

**Comment by nlohmann** [comment]
Sorry for not checking back earlier. Can I close this issue or is there still anything wrong with the library?

**Comment by leozzyzheng** [comment]
I still cannot convert this type into json using vs2015, so I write the special convert code for this type. It's fine to close it and I wish anyone had same problem could give me some advise.

**Comment by jseward** [comment]
I just tried this out on both VS 2015 and VS 2017. It compiles with no issues. Should be safe to close. @leozzyzheng perhaps try again with latest code?

**Comment by leozzyzheng** [comment]
@jseward I don't mean that it will cause compilation error, it only let VS shows the red underline. If I add c_str(), the red line gone. So it doesn't matter. Thanks.

**Comment by leozzyzheng** [comment]
@jseward  I will try it later, thanks.

**Comment by leozzyzheng** [comment]
@jseward I have downloaded the latest release version on github and used the exactly same code from nlohmann, unfortunately it still have the same compilation error.

**Comment by theodelrieu** [comment]
Sorry for the late reply,  I'm looking into it.

**Comment by theodelrieu** [comment]
I have no problem with VS2015 14.0.25431.01 Update 3 and the latest `develop` version.

**Comment by nlohmann** [comment]
I am confused...

**Comment by leozzyzheng** [comment]
@theodelrieu The latest `develop` version has no problem to me! I think it could be closed. :)

**Comment by nlohmann** [comment]
Thanks for checking everyone!

**Comment by na-n** [comment]
TL:DR; I duplicated this with #827. Now I'm gonna do the reading.
