### ISSUE TITLE
Dumping Json to file as array

### ISSUE THREAD

**Issue by ankitsultania** [nlohmann/json#738]
Hi,

Is there a way to append a file with json objects as array one by one?

Any pointers are highly appreciated. I am stuck at doing this in a clean way.

**Comment by ankitsultania** [comment]
ex: 
json obj 1: { fname:x, lname:y}
write to file
json obj 2: { fname:a, lname:b}
write to file

file output:
[
{ fname:x, lname:y},
 fname:a, lname:b}
]

**Comment by nlohmann** [comment]
As JSON requires opening and closing brackets as well as proper commas in between the elements, it is hard to achieve this. You may stream to a file and, after writing the last element, remove the last comma and add the closing bracket.

You may want to have a look at http://jsonlines.org/:

> JSON Lines is a convenient format for storing structured data that may be processed one record at a time.

It is trivial to implement a JSON Lines writer and reader with this library.

**Comment by ankitsultania** [comment]
Thanks for the response.
