### ISSUE TITLE
CMake target nlohmann_json does not have src into its interface includes

### ISSUE THREAD

**Issue by sogartar** [nlohmann/json#741]
If you do in CMake:
```
add_subdirectory(nlohmann/json)
target_link_libraries(my_target PRIVATE nlohmann_json)
```
Then `my_target` does not have nlohmann/json/src into its includes, where json.hpp is. You can not properly include this project into other CMake projects.
Note that in v2.1.1 it used to be OK.

**Comment by nlohmann** [comment]
maybe related: #695

**Comment by dan-42** [comment]
@sogartar what system do you use?  Windows? Mac? Linux?
have you installed it first via?
```bash
cmake
make
make install
```


If the usage you described is a common one (I did never useed 3rdparty  CMake-Projekts like this)
Then indeed this might be a BUG.
Please not that the up comming version V3.0.0 will bring breaking changes including the usage of build-tools and package-managers. see #698

**Comment by dan-42** [comment]
@sogartar  I forgot, a simpler oneliner for you're case could be 
```cmake
include_directory(nlohmann/json/src)
```

**Comment by nlohmann** [comment]
Is there anything to be done to close this issue?

**Comment by sogartar** [comment]
I think you should add nlohmann/json/src to the public includes of the nlohmann_json target. See [target_include_directories](https://cmake.org/cmake/help/latest/command/target_include_directories.html).

**Comment by dan-42** [comment]
Well @sogartar thx for answering any of my questions. so IMHO I would ignore it.

But I will have a look and see what impact the suggestion would be.

**Comment by nlohmann** [comment]
Does anyone has an idea how to proceed here?

**Comment by nlohmann** [comment]
Issue #790 also proposes to change the include dir.

**Comment by nlohmann** [comment]
Sorry, #790 is unrelated to this issue.

**Comment by nlohmann** [comment]
I need more info on this issue. What needs to be fixed? Is there example code to demonstrate the issue?

**Comment by theodelrieu** [comment]
Playing with `target_include_directories` and generator expressions should do the trick.

I'll open a PR tomorrow morning.

**Comment by theodelrieu** [comment]
Could you try `nlohmann_json::nlohmann_json`? The target should be inside a namespace IIRC.

**Comment by pfaco** [comment]
> Could you try nlohmann_json::nlohmann_json? The target should be inside a namespace IIRC.
Yes, that solved it! Just added nlohmann_json::nlohmann_json to the target_link_libraries command. Thanks!
