### ISSUE TITLE
Retrieve all values that match a json path

### ISSUE THREAD

**Issue by leflabs** [nlohmann/json#743]
Assuming that my json file is the following, I would like to collect all values that match with a regular expression using json_pointer.  How can I get all values (integers) in the path /array/a/*? 

I have used flatten() so far, that gives the "keys". But I don't know if I can query the json object to return an array of values that "match" a json path. 
```
{
 "array": [
    {
      "a": 1,
      "b": [10,11,12]
    },
    {
      "a": 2,
      "b": [20,21,22]
    },
    {
      "a": 3,
      "b": [30,31,32]
    }
  ],
  "cost": 1
}
```

**Comment by nlohmann** [comment]
What about

```cpp
#include "json.hpp"
#include <iostream>
#include <regex>

using json = nlohmann::json;

int main(int argc, char const *argv[])
{
  json j = R"({
    "array": [
    {
      "a": 1,
      "b": [10,11,12]
    },
    {
      "a": 2,
      "b": [20,21,22]
    },
    {
      "a": 3,
      "b": [30,31,32]
    }
    ],
    "cost": 1
  })"_json;

  auto f = j.flatten();

  std::smatch sm;
  std::regex re("/array/[^/]+/a");

  json result;

  for (auto it = f.begin(); it != f.end(); ++it)
  {
    std::regex_search(it.key(), sm, re);
    if(not sm.empty())
    {
      result.push_back(it.value());
    }
  }

  std::cout << result << std::endl;        
}
```

**Comment by leflabs** [comment]
Hello, 

thank you for the follow up. I have already used this approach as a workaround. I was hoping that the library could take /array/*/a and reply back with a "vector" of values. 

Thanks.

**Comment by nlohmann** [comment]
No, but you must admit that this is a very specific usecase... And I think you could clean up the code above and use some `<algorithm>` magic.

**Comment by leflabs** [comment]
True, it is a specific issue. 

What kind of magic do you have in mind :-) ?

**Comment by nlohmann** [comment]
I don't know, maybe something like `std::copy_if`.
