### ISSUE TITLE
User-friendly documentation

### ISSUE THREAD

**Issue by itviewer** [nlohmann/json#744]
As the project becomes more and more popular, well-organized documents are necessary. Up to now, the project uses the README file to describe how to use the library, with the some disadvantages:

- with the description more and more, README file becomes very long
- the user needs a clearer structure to describe how to use the library
- inconvenient documentation contribution and collaboration

So I suggested to separate the document and the code library to provide a more friendly document experience.  I created two styles of demo  based on [mkdocs](http://www.mkdocs.org):

1. https://itviewer.github.io/manual-material/
2. https://itviewer.github.io/manual/

repository corresponding respectively

1. https://github.com/itviewer/manual-material
2. https://github.com/itviewer/manual/

I just copyed the content from the README file and did not modify anything. both the above two  demo looks ok. The markdown syntax for github is good, almost no error format.

The [mkdocs](http://www.mkdocs.org) tool  is a python package, also easy to use, powerful and flexible.

**Comment by nlohmann** [comment]
FYI: https://nlohmann.github.io/json/

**Comment by nlohmann** [comment]
Such a documentation looks nice, but there is already a lot of documentation in Doxygen format, including live examples. I would like to generate a documentation out of this to not risk diverging the "reality" and the documentation. Admittedly, the Doxygen documentation is rather ugly...

**Comment by itviewer** [comment]
https://nlohmann.github.io/json/ is suitable for API reference
