### ISSUE TITLE
Best method for exploring and obtaining values of nested json objects when the names are not known beforehand?

### ISSUE THREAD

**Issue by sqwunkly** [nlohmann/json#747]
Hi Niels, 

Could you please advise me the best way to explore down into a list of JSON objects, without knowing the names of the nested objects beforehand. 

I'm using the notation below (1 & 2) for setting and getting values and this works well, however I've not been able to find a way of quickly getting the names and values of objects when I don't know the names of those objects beforehand. I've used the iterator method (3) however it doesn't seem suited for quickly diving and exploring into nested objects.

What is the most direct way of exploring and getting values of nested objects when the names of those objects are not known beforehand? 

(1)
![image](https://user-images.githubusercontent.com/31691223/30565084-6189c78a-9d0a-11e7-97b5-fc33129c099d.png)

(2)
![image](https://user-images.githubusercontent.com/31691223/30565140-88fd778a-9d0a-11e7-8293-cf4f6fc60ac4.png)

(3)
![image](https://user-images.githubusercontent.com/31691223/30565301-10c1d74c-9d0b-11e7-8287-96e6c503b914.png)

**Comment by sqwunkly** [comment]
I'm stuck at this stage.. I don't know if this is the best way of delving into nested objects.. it seems promising but I don't know how to do it.

Here is the code I'm using to get pointer to the first object ("group 1") inside the json file read into my program. From here I need to get the name (unknown) of the "group 1" nested object ("Schedule1") and obtain names for each successive sibbling object ie "Schedule1", "Schedule3", "Schedule4" etc... however I don't know beforehand their names.. they could for example be named "Morning Schedule", "Afternoon Schedule", "Rainy Day Schedule", etc or something else. ... so these names are unknown.

![image](https://user-images.githubusercontent.com/31691223/30574565-1e86df48-9d3e-11e7-8e5a-92181f29cdd1.png)

Debugger view below:- I have the p1 pointer.. it's pointing to "group 1" (obtained in code above)... using this p1 pointer I now need to locate position of "Schedule1", "Schedule2", etc and obtain their names (ie unknown arbitrary names) and read their values (the structure of this 'schedules' data is consistent and is known), so I can access and recreate this json data inside my program within a corresponding linked list of data.

![image](https://user-images.githubusercontent.com/31691223/30574654-b82e9a6e-9d3e-11e7-8ac9-39982d85fe92.png)

I don't know what to do next.. your help again be much appreciated.

**Comment by sqwunkly** [comment]
Explicitly showing these arbitarily named 'schedules' objects:-

![image](https://user-images.githubusercontent.com/31691223/30576622-776b05fe-9d4c-11e7-820b-18160f41fe65.png)

How do I access these in a succinct manner without knowing their key names beforehand?

Thanks.

**Comment by sqwunkly** [comment]
Hi Niels, This works below however I'm wondering, is there a more direct and succinct way of querying nested keys and obtaining their values of unknown 'key' name'? 

![image](https://user-images.githubusercontent.com/31691223/30577643-f9e3f8be-9d52-11e7-81b3-19f7c75a5d3a.png)

**Comment by gregmarr** [comment]
This example should help make your for loop cleaner, but you have the basic idea.  Just make sure that you have the right types when accessing things, as in your other issue.  Use `auto` wherever possible so that you don't silently change the type.

https://github.com/nlohmann/json/blob/develop/doc/examples/iterator_wrapper.cpp

**Comment by nlohmann** [comment]
Can I close this issue?

**Comment by sqwunkly** [comment]
yes
