### ISSUE TITLE
user-defined literal operator not found

### ISSUE THREAD

**Issue by vsakharuk** [nlohmann/json#750]
I am getting this error with json 2.1.1

using precompiled header file ".../test/cotire/json_unit_CXX_prefix.pchi"
.../test/src/unit-deserialization.cpp(82): error: user-defined literal operator not found
              CHECK("[\"foo\",1,2,3,false,{\"one\":1}]"_json == json({"foo", 1, 2, 3, false, {{"one", 1}}}))

I see literal operator in json.hpp
I suspect this is due to pre-compiled headers for icc16.

How do I disable usage of those for icc in cmake?

Edit:
I flipped in test files
#include <json.hpp>
#include <catch.hpp>
and it compiles, issue clearly is pre-compiled headers.
Is there a switch to disable it or editing those the only way to do it?

Of note,
I notice at least one test file uses #define private public
so it may not be a good idea to use pre-compiled headers at all.

**Comment by theodelrieu** [comment]
I had this issue too, had to run `ninja clean` each time, but I believe it has been removed on the `develop` branch.

**Comment by nlohmann** [comment]
@vsakharuk Does this issue also occur with the version in `develop`?

**Comment by nlohmann** [comment]
Any news here?

**Comment by vsakharuk** [comment]
Sorry, missed you post. Will try.

**Comment by vsakharuk** [comment]
I tried with develop, it is working.

**Comment by nlohmann** [comment]
Thanks for checking back!
