### ISSUE TITLE
parsing works sometimes and crashes others

### ISSUE THREAD

**Issue by AdamMiltonBarker** [nlohmann/json#752]
Hi guys I am using this with paho c, both installed using VCPKG and used in a C++ console app. I attempting to convert message->payload to json so I can access the elements of the response. This works sometimes but in others I get errors such as:

"parse error - unexpected 's'; expected end of input"

Exactly the same response is work and not working randomly. This is the code which is the on message arrived callback from paho:

```
int msgarrvd(void *context, char *topicName, int topicLen, MQTTAsync_message *message)
{
	int i;
	const char* payloadptr;

	payloadptr = (const char*)message->payload;
	std::cout << payloadptr;
	std::vector<std::string> v = explode("/", topicName);
	std::string s(payloadptr);
	std::cout << s;
	json data = json::parse(s+'\n');
	std::cout << data["Command"];

	if (v[4]=="Commands") {

	}
	 
	MQTTAsync_freeMessage(&message);
	MQTTAsync_free(topicName);
	return 1;
}
```

Example response:

`{"Sensor":"CCTV","SensorID":130,"Command":"Capture","CommandValue":"Face"}`

**Comment by gregmarr** [comment]
It wouldn't affect the crash issue, but you don't need the `\n` at the end.

**Comment by gregmarr** [comment]
Do you have the `std::cout` output from when it works and when it doesn't?  It's likely a difference in the string.

**Comment by AdamMiltonBarker** [comment]
Hi thanks for reply, I added that as I thought it would help :) I will remove it, I will try get that for you now, but the strings being sent are exactly the same, I have an interface that sends the above string on click of a button and that is all it is receiving at the moment, I have a feeling that is to do with the pointer not being completely populated by the time it gets to json::parse, I have posted in Paho also.

https://github.com/eclipse/paho.mqtt.c/issues/337

**Comment by AdamMiltonBarker** [comment]
OK so this is happening, which explains the e error. This is 100% not sent with the message:

`{"Sensor":"CCTV","SensorID":130,"Command":"Capture","CommandValue":"Face"}et.c{"Sensor":"CCTV","SensorID":130,"Command":"Capture","CommandValue":"Face"}et.c`

One thing I not is that I have FFMPEG running on the same console. The output from that sometimes get split up in between the print outs of the response, and I doubt that would be it but I checked and there is nothing with et.c in it, but checked anyway to see if it was conflicting, so somewhere it appears that text is getting added to the response. In addition the interface with the button also receives its own publishes and this is totally fine every time, looks like something in my code or an issue with Paho, cannot see anything doing it from the code above though.

**Comment by AdamMiltonBarker** [comment]
:O It is coming from the output of FFMPEG I disabled it and it works everytime, no idea how that is possible.

**Comment by AdamMiltonBarker** [comment]
Anyway this appears to be issue between Paho and FFMPEG, thanks for the time to help. Will close this off.

**Comment by AdamMiltonBarker** [comment]
New output:

`{"Sensor":"CCTV","SensorID":130,"Command":"Capture","CommandValue":"Face"}{"Sensor":"CCTV","SensorID":130,"Command":"Capture","CommandValue":"Face"}"Capture"{"Sensor":"CCTV","SensorID":130,"Command":"Capture","CommandValue":"Face"}X#╖º3êêêê─╧ûF{"Sensor":"CCTV","SensorID":130,"Command":"Capture","CommandValue":"Face"}X#╖º3êêêê─╧ûF`

**Comment by AdamMiltonBarker** [comment]
{"Sensor":"CCTV","SensorID":130,"Command":"Capture","CommandValue":"Face"}etOut.êêêêcå({"Sensor":"CCTV","SensorID":130,"Command":"Capture","CommandValue":"Face"}etOut.êêêêcå(

**Comment by AdamMiltonBarker** [comment]
Solved with:

```
int msgarrvd(void *context, char *topicName, int topicLen, MQTTAsync_message *message)
{
	int i;
	char* payloadptr;

	payloadptr = (char*)message->payload;
	std::cout << payloadptr;
	std::string s = "";
	for (i = 0; i<message->payloadlen; i++)
	{
		s = s + *payloadptr++;
	}
	s = s + '\n';

	std::vector<std::string> v = explode("/", topicName);
	std::cout << s;
	json data = json::parse(s);
	std::cout << data["Command"];

	if (v[4]=="Commands") {

	}
	 
	MQTTAsync_freeMessage(&message);
	MQTTAsync_free(topicName);
	return 1;
}
```
