### ISSUE TITLE
Getter is setting the value to null if the key does not exist

### ISSUE THREAD

**Issue by adityamarella** [nlohmann/json#754]
Here is the sample code
```
#include <iostream>
#include <json.hpp>

int main(void) {
    nlohmann::json json;
    json["xxx"] = 1;
    auto y = json["yyy"];
    std::cout << json.dump() << std::endl;
    return 0;
}
```
The output is `{"xxx":1,"yyy":null}`. 

The expected behavior is to throw std::out_of_range exception

**Comment by adityamarella** [comment]
Closing this since the documentation already recommends at() vs. operator[], although this definitely is unexpected behavior.

> In function from_json, use function at() to access the object values rather than operator[]. In case a key does not exists, at throws an exception that you can handle, whereas operator[] exhibits undefined behavior.

**Comment by nlohmann** [comment]
Note this behavior is *exactly* the one of `std::map`:

```cpp
#include <map>
#include <iostream>

int main(int argc, char const *argv[])
{
    std::map<std::string, int> m;
    m["xxx"] = 1;
    auto y = m["yyy"];
    
    for (auto i = m.begin(); i != m.end(); ++i)
    {
        std::cout << i->first << " : " << i->second << std::endl;
    }
}
```

produces:

```
xxx : 1
yyy : 0
```

The note you cited refers to the case when we access a const object. Then, `operator[]` cannot add `null` values to the object when called with an unknown key and the semantics is undefined.

**Comment by adityamarella** [comment]
Thanks for your comment. I wonder why std::map behaves this way. It is counterintuitive to set the value to null or 0 when the key is missing.

**Comment by gregmarr** [comment]
Because if it didn't, then `json["xxx"] = 1;` wouldn't work.  It creates an entry with the default value, and then sets it to `1`.

**Comment by nlohmann** [comment]
There is already a note, see https://github.com/nlohmann/json/blob/develop/README.md#notes.
