### ISSUE TITLE
std::signbit ambiguous

### ISSUE THREAD

**Issue by adayoegi** [nlohmann/json#761]
I just cloned the latest files and only copy json.hpp to my project, on Win10 with vs2015.

While compilation, the error message C2668 states that signbit is ambiguous on line 6663,
`const auto is_negative = std::signbit(x);`
it seems signbit is from corecrt_math.h with 3 overloads whose inputs are float, double, long double.
Since line 6663 is in dump_integer(), I guess the input x is an int so the compiler is not sure which type to convert.

Does anyone ever encountered C2668 ambiguous call to overloaded function "signbit" ?
How do you guys solve this?

**Comment by nlohmann** [comment]
This is strange, because `std::signbit` should have overloads for integral types (see http://en.cppreference.com/w/cpp/numeric/math/signbit). I reverted the changes though, so the code should compile with MSVC again.

**Comment by adayoegi** [comment]
Thanks for your help!

Is this a compiler or platform specific problem?
The definition of std::signbit is directed to corecrt_math.h, not cmath.
I am not sure if these 2 files are the same, did not find any info about corecrt_math.h
(i.e. Is `#include <cmath>` the same as `#include paht/to/corecrt_math.h` ? )

**Comment by nlohmann** [comment]
I don't know. The code worked with Clang and GCC with both Linux and macOS.

**Comment by adayoegi** [comment]
I see. Thank you.
