### ISSUE TITLE
warnings in msvc about mix/max macro while windows.h is used in the project

### ISSUE THREAD

**Issue by crea7or** [nlohmann/json#762]
In the version 2.1.1, msvc generates a few warnings about std::numeric_limits<>::max() (and min) usage. This is because windows.h have their own min/max macros definitions in the global namespace (here is [microsoft kb article about it.](https://support.microsoft.com/en-us/help/143208/prb-using-stl-in-windows-program-can-cause-min-max-conflicts).
warning exact text: warning C4003: not enough actual parameters for macro 'max'

possible fixes:
1)

`#define NOMINMAX`

2)

```
#ifdef max
#undef max
#endif

#ifdef min
#undef min
#endif
```

3) use additional parenthesis

std::numeric_limits<uint8_t>::max() => (std::numeric_limits<uint8_t>::max)()

First two methods can produce problems, due to use original windows min/max in the gdi and more.
the third method should be tested on the other compilers.

Source to reproduce the problem:

```
#include "stdafx.h"
#include "windows.h"
#include "json.hpp"

using json = nlohmann::json;

int main( int argc, char const *argv[] )
{
	json j;
	j[ "test" ] = 1;
}
```

**Comment by nlohmann** [comment]
Does this also occur in the `develop` branch?

**Comment by crea7or** [comment]
just tested dev branch - yes, even the errors appeared:

```
json.hpp(3583): warning C4003: not enough actual parameters for macro 'min'
json.hpp(3583): error C2589: '(': illegal token on right side of '::'
json.hpp(3583): error C2062: type 'unknown-type' unexpected
json.hpp(3583): error C2059: syntax error: ')'
json.hpp(3513): error C3615: constexpr function 'nlohmann::detail::operator ==' cannot result in a constant expression
json.hpp(3513): note: failure was because type 'nlohmann::detail::primitive_iterator_t' is not a literal type
...
```
changing line 3583 from:
`    difference_type m_it = std::numeric_limits<std::ptrdiff_t>::min();`
to
`    difference_type m_it = (std::numeric_limits<std::ptrdiff_t>::min)();`
fixes all the problems.

**Comment by nlohmann** [comment]
Thanks! I'll have a look.

**Comment by nlohmann** [comment]
@crea7or Can you please check if this works now?

**Comment by crea7or** [comment]
Everything is clear in visual studio 2015 + visual studio 2017 with all available sdk versions:
![untitled-1](https://user-images.githubusercontent.com/467357/31093330-0e828ab2-a7ba-11e7-9098-d67d77c18f62.png)

**Comment by nlohmann** [comment]
Thanks for checking!
