### ISSUE TITLE
Documentation or feature request.

### ISSUE THREAD

**Issue by deathly809** [nlohmann/json#763]
Is it possible to flatten fixed sized arrays to a single array? 

**Serialize**
```
std::vector<Vec3> points = {{1,2,3} , {4,5,6} };
```
```
{
  "points" : [
        1,
        2,
        3,
        4,
        5,
        6
  ]
}
```

**Deserialize**
```
{
  "points" : [
        1,
        2,
        3,
        4,
        5,
        6
  ]
}
```
```
std::vector<Vec3>  points = { {1,2,3} {4,5,6} };
```

**Comment by nlohmann** [comment]
This feature is too specific to be added to this general-purpose JSON library. You may want to do the flattening/unflattening outside the library (see https://stackoverflow.com/questions/17294629/merging-flattening-sub-vectors-into-a-single-vector-c-converting-2d-to-1d for examples) and store `std::vector<int>` inside the JSON value. To avoid copies, you can use `get_ref` (see https://nlohmann.github.io/json/classnlohmann_1_1basic__json_afbd800010b67619463c0fce6e74f7878.html#afbd800010b67619463c0fce6e74f7878).

**Comment by deathly809** [comment]
Thanks.  I will give it a try.

**Comment by nlohmann** [comment]
I'm closing the issue. If you experience any problems, feel free to ask and I will reopen it.
