### ISSUE TITLE
Invoking is_array() function creates "null" value

### ISSUE THREAD

**Issue by drewpts** [nlohmann/json#77]
Hello.
```cpp
 if (j[SUBPR_DESCR].is_array()) {
                if (j[SUBPR_DESCR].at(0).is_string() == false)
                    return json::parse(error_code + "Wrong values type of subprojects key!\"}");
            } else if (!j[SUBPR_DESCR].is_null() && !j[SUBPR_DESCR].is_array()) {
                return json::parse(error_code + "Corrupted or absent subprojects key!\"}");
            }
```
After invoking such function on json object data with key SUBPR_DESCR appearing with value "none".

![2015-05-28 12 46 21](https://cloud.githubusercontent.com/assets/10561098/7857293/059ef150-0538-11e5-9de7-c8f5f48a1c11.png)
![2015-05-28 12 46 31](https://cloud.githubusercontent.com/assets/10561098/7857292/059dab10-0538-11e5-96b0-030987fc02c6.png)

[offtop] Lol, horrible char * to string casting at the bottom of image :hamster: [/offtop]

**Comment by drewpts** [comment]
I just faced similar behaviour with method is_null(): if no value in object **O** under "foo" key invoking O["foo"].is_null() creates such value (see screen):
![2015-05-29 13 35 50](https://cloud.githubusercontent.com/assets/10561098/7881081/f0e1c302-0607-11e5-98c7-4a5ee0eb531d.png)

Thank you for you attention!:)

**Comment by nlohmann** [comment]
What you try to do is to find out whether an object stores a value for a key. For that, you could try `j.count("subprojects") == 0`.

However, `j["subprojects"]` has a different semantics: If a key `subprojects` is stored in `j`, it returns a reference to that object. But if it does not, it creates a `null` value for that key. While this may make little sense when combined with `is_null()`, it helps to create objects easily, for instance `j["foo]["bar"] = 1`.
