### ISSUE TITLE
error: ‘BasicJsonType’ in namespace ‘::’ does not name a type

### ISSUE THREAD

**Issue by pdroalves** [nlohmann/json#770]
I'm using g++ 5.4.0 and nvcc 8.0.44 to compile the most recent commit of the library. I compiled, installed the library, and included in my code (with C++11 flag) but when I try to compile my code I get:

    /usr/local/include/nlohmann/json.hpp:3624:10: error: ‘BasicJsonType’ in namespace ‘::’ does not name a type

What am I missing?

**Comment by theodelrieu** [comment]
Seems to be this line: `friend BasicJsonType;`

This is weird, the "simple-type-specifier" works since C++11, do you have a more recent GCC version to try?

You could also take the latest release, it should work fine.

**Comment by pdroalves** [comment]
I don't think the problem lies in the GCC version. The library passed on all tests.
Maybe on nvcc?

**Comment by pdroalves** [comment]
I think I solved it. I was running the last commit. Changed to v2.1.1 and it worked.

**Comment by yhtang** [comment]
Just some information for people running into the situation lately:

The problem showed up again with v3.1.2 when compiling with nvcc 9. Upgrading to CUDA 10 will automatically solve it. Apparently this is an issue of the nvcc compiler.

**Comment by babaozhouy5** [comment]
People who running into this situation, can add a #

**Comment by babaozhouy5** [comment]
[This answer](https://github.com/nlohmann/json/issues/1051#issuecomment-420516846) can solve the problem.
