### ISSUE TITLE
Build warnings: shadowing exception id

### ISSUE THREAD

**Issue by pvleuven** [nlohmann/json#776]
Hi,

I get a bunch of build warnings (see below) that inform on hiding the exception member 'id'. To me it seems the member is not needed as the id is always passed through the calling functions. Looks like a potential source of trouble to me.

Best regards,

Peter

warnings: 
 In file included from .*******: ********json/json.hpp(209): warning #3280: declaration hides member "nlohmann::detail::exception::id" (declared at line 204)
      static std::string name(const std::string& ename, int id)
                                                            ^
 ********json/json.hpp(273): warning #3280: declaration hides member "nlohmann::detail::exception::id" (declared at line 204)
      static parse_error create(int id, std::size_t byte_, const std::string& what_arg)
                                    ^
 ********json/json.hpp(337): warning #3280: declaration hides member "nlohmann::detail::exception::id" (declared at line 204)
      static invalid_iterator create(int id, const std::string& what_arg)
                                         ^
 ********json/json.hpp(388): warning #3280: declaration hides member "nlohmann::detail::exception::id" (declared at line 204)
      static type_error create(int id, const std::string& what_arg)
                                   ^
 ********json/json.hpp(431): warning #3280: declaration hides member "nlohmann::detail::exception::id" (declared at line 204)
      static out_of_range create(int id, const std::string& what_arg)
                                     ^
 ********json/json.hpp(469): warning #3280: declaration hides member "nlohmann::detail::exception::id" (declared at line 204)
      static other_error create(int id, const std::string& what_arg)

**Comment by nlohmann** [comment]
Thanks for reporting. Is this an ICC warning?

**Comment by theodelrieu** [comment]
Indeed, troubles ahead! I didn't take a detailed look to 3.0 exceptions but I think the member `id` is useful, especially when catching.

The naming convention I usually have is to prefix private member variables with an underscore.

**Comment by pvleuven** [comment]
Yes it's ICC forgot to mention it: 
icpc (ICC) 17.0.4 20170411 to be precise

**Comment by nlohmann** [comment]
@theodelrieu In class exception, `id` is a public member. Would the error be fixed if I rename parameter `id` of function name?

**Comment by theodelrieu** [comment]
Yep that will suffice

**Comment by nlohmann** [comment]
@pvleuven Could you please check if d300a8e2681c95fd0b11569a74d4f88d608a3f69 fixes the warnings?

**Comment by nlohmann** [comment]
Can I close this issue?

**Comment by pvleuven** [comment]
Yes it works, and I didn't mean to close it, I'll leave that to you.

**Comment by nlohmann** [comment]
Thanks for checking back!
