### ISSUE TITLE
All unit tests fail?

### ISSUE THREAD

**Issue by QuantumDonDoerner** [nlohmann/json#787]
Using up-level cmake:
%cmake3 --version
cmake3 version 3.6.3

Using up-level compiler (6.3.0, on the list)
%c++ --version
c++ (GCC) 6.3.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Tests built with a couple of innocuous warnings like this:
.../json/test/src/unit-serialization.cpp:71:18: warning: ‘std::ostream& nlohmann::operator>>(const
nlohmann::basic_json<>&, std::ostream&)’ is deprecated [-Wdeprecated-declarations]

But all tests fail: "0% tests passed, 70 tests failed out of 70"

Any idea what may be happening?

**Comment by nlohmann** [comment]
We compile and execute the test suite without problems using GCC 6.3.0 on Ubuntu, see https://travis-ci.org/nlohmann/json/jobs/287422140.

Did you run the tests like this?

```sh
$ mkdir build
$ cd build
$ cmake ..
$ cmake --build .
$ ctest
```

**Comment by QuantumDonDoerner** [comment]
Yes, I ran them exactly as directed on the page https://github.com/nlohmann/json#projects-using-json-for-modern-c, except that I am working on CentOS 7 (1611) not Ubuntu.


I just looked:

%ctest --version

ctest version 2.8.12.2

By chance is there a ctest version requirement that I may not be meeting?

[https://avatars3.githubusercontent.com/u/159488?v=4&s=400]<https://github.com/nlohmann/json#projects-using-json-for-modern-c>

GitHub - nlohmann/json: JSON for Modern C++<https://github.com/nlohmann/json#projects-using-json-for-modern-c>
github.com
to the files you want to use JSON objects. That's it. Do not forget to set the necessary switches to enable C++11 (e.g., -std=c++11 for GCC and Clang).




Thanks,

-don-
________________________________

**Comment by nlohmann** [comment]
I am using ctest version 3.9.4. To be sure, can you provide some log files from the failing tests? It's hard to tell right now.

**Comment by QuantumDonDoerner** [comment]
Found it, my mistake, please close the issue.


FYI, the problem was that when I updated my compiler, I didn't point at the right libraries.


Thanks,

-don-
________________________________
