### ISSUE TITLE
ppa to include source

### ISSUE THREAD

**Issue by jgsuess** [nlohmann/json#791]
Hi!
We are using cmake and Ubuntu in our build. Would you be willing to make a PPA so json can be shipped in the ubuntu sphere.
And _Yes_ - I am aware that:
- it is just a single source file
- I can use wget to simply grab it of the repository for each release.
Consideration would be welcome though!

**Comment by nlohmann** [comment]
No problem. Is there anything I need to do?

**Comment by jgsuess** [comment]
Basically this: https://askubuntu.com/questions/71510/how-do-i-create-a-ppa#answer-71516
That would allow anyone wanting to use it to say
`apt install json.h` to get it. It also mirrors the version number.
And if you are really good you pack a pkg-config file with it: https://www.freedesktop.org/wiki/Software/pkg-config/
This will allow cmake-based projects to integrate json.h without any effort:
https://cmake.org/Wiki/CMake:How_To_Find_Libraries#Piggybacking_on_pkg-config
I know `cmake is a bit old hat, compared to `meson`, but it is still pretty common...

**Comment by nlohmann** [comment]
As I am not actively using Ubuntu myself, I don't think it's a good idea to create this. If anyone is willing to do this, I would be happy.
