### ISSUE TITLE
how to get the json object again from which printed by the method of dump()

### ISSUE THREAD

**Issue by CoderOverflow** [nlohmann/json#792]
string wormhole;
wormhole = jsonPayload.dump();

How can I convert std::string to json object again?
When I use 'auto x = json::parse(wormhole.c_str()) ', the exception was occurred.

**Comment by nlohmann** [comment]
You don't need the `.c_str()`. Which exception did occur?

**Comment by CoderOverflow** [comment]
I found that the when json data is include some Chinese character, the parse function can't work.

**Comment by nlohmann** [comment]
We extensively tested the `parse` function with all kinds of UTF-8 characters, so it should work. Could you please provide an example where parsing fails?

**Comment by CoderOverflow** [comment]
from dump string
["1","2017-10-18 17:38:41.000322","i","20160506","","晋A12345"] NG
["1","2017-10-18 17:37:12.000321","i","20160506","","a"]  OK

**Comment by nlohmann** [comment]
Which exception do you get?

**Comment by nlohmann** [comment]
Which exception do you get? The exception gives hint where the parse error occurs.

**Comment by CoderOverflow** [comment]
what kind of exception you want to catch？ it just jump into the catch(...) block..

**Comment by nlohmann** [comment]
Just surround the `parse` call with `try/catch(std::exception &e)` and give me the result of `e.what()?``.

**Comment by CoderOverflow** [comment]
parse error - unexpected '"'

**Comment by nlohmann** [comment]
This is really strange. Could you please try without the `.c_str()`? Do you use the most recent version from the `develop` branch?

**Comment by CoderOverflow** [comment]
```
c_list.push_back(W2A(strId));
								c_list.push_back(W2A(strDataTime));
								c_list.push_back("i");
								c_list.push_back(W2A(strRQ));
								c_list.push_back(W2A(strDDID));
								//c_list.push_back("a");
								c_list.push_back(W2A(strHP));
								json ss(c_list);
								std::string err = ss.dump();
								json xx = json::parse(err);
```
Actually, I didn't use c_str().

**Comment by nlohmann** [comment]
What does `W2A` do?

**Comment by CoderOverflow** [comment]
how to check the version? I get the json.hpp at version 2.1.1 on 06/18/2017
W2A/A2W is the morco that will convert the between multiByte and wideChar
I use it to convert the CString of mfc to std::sting

**Comment by nlohmann** [comment]
Could you try this file: https://github.com/nlohmann/json/blob/develop/src/json.hpp

Is the resulting string UTF-8 encoded?

**Comment by CoderOverflow** [comment]
I am not sure, maybe is not encoded by UTF-8. I will check this after.

**Comment by nlohmann** [comment]
Assuming `strHP` is the string that results in the failure, could you please try

```cpp
std::string s = "\"";
s += W2A(strHP);
s += "\"";
json::parse(s);
```

**Comment by CoderOverflow** [comment]
It does the UTF-8 encoding cause this problem:)
I guess my the encoding of environment of my vs2015 is gbk. 
After I added an covert function converting string from gbk to utf-8, the exception is gone.

THX ^_^

**Comment by nlohmann** [comment]
Thanks for checking back!
