### ISSUE TITLE
Iterating over sub-object

### ISSUE THREAD

**Issue by fwsGonzo** [nlohmann/json#794]
I'm sorry but I'm completely lost
I just want to iterate over a value:

```
    auto tiles = j.find("tiles");
    if (tiles != j.end())
    {
      for (auto tile : *tiles)
      {
        std::cout << tile.key() << std::endl;
        //printf("Name: %s\n", tile.key().c_str());
      }
    }
```
I even used std::cout just like the examples.
```
{
  "tiles":
  {
    "a": [2, 5],
    "b": [3, 0],
```

What am I doing wrong? It says `error: no member named 'key' in tile` but that makes no sense because im *iterator so I should already be ranged-for-ing over each tile.
The examples also don't really provide any insight into iterating over things like these.

Iterating over the sub-object and then `std::cout << tile << std::endl;` works like expected, however that is just magic. I want to print the key and the value separately, one as a string and the other as an array using indexing operator.

**Comment by nlohmann** [comment]
You may want to look at [iteration wrappers](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_aea8c06bb8e632f14cd77632519213d75.html#aea8c06bb8e632f14cd77632519213d75) - here is an example how to use them https://github.com/nlohmann/json/blob/develop/doc/examples/iterator_wrapper.cpp.

**Comment by fwsGonzo** [comment]
Thanks, worked :)
