### ISSUE TITLE
Using your library (without modification) in another library

### ISSUE THREAD

**Issue by chetmurthy** [nlohmann/json#796]
Hi,

First, this is wonderful.  Thank you so much!

Second, I'd like to use your library in some code I'm writing to provide a JSON wire-format for Apache Thrift.  I'll be distributing this code on github in source, under the Apache license, and would -like- to be able to include a copy of your json.hpp (with your license) in my source-tree.  Only b/c it'll be convenient that people who clone this repo won't have to go clone other repos also.  Of course, I'd make sure to credit you and point at your git repo.

Is this something you'd find agreeable?

**Comment by nlohmann** [comment]
I am not a license expert, but I think it is no problem to include my library as long as you also redistribute the MIT license text.

And of course I would be happy if the library is useful to you, so please go ahead and add it to Apache Thrift. Please let me know once it is in so I can mention in in my README file.

**Comment by chetmurthy** [comment]
Hello, everything just as you say, with one correction: this probably won't be a -part- of Thrift.  Rather, this library is an addon to Thrift.

**Comment by nlohmann** [comment]
Alright.
