### ISSUE TITLE
json data = std::string_view("hi"); doesn't work?

### ISSUE THREAD

**Issue by lethe555** [nlohmann/json#801]

**Comment by nlohmann** [comment]
`std::string_view` is a C++17 feature. The library supports C++11 and currently does not know what `std::string_view` is. This should be fixed in the future. In the meantime, you may need to pass string values as `std::string` to the library - they are stored internally as `std::string` anyway, so you would need to make a copy anyway.

**Comment by theodelrieu** [comment]
You could also provide a specialization of `adl_serializer<std::string_view>`.

**Comment by nlohmann** [comment]
For reference, here is a possible implementation:

```cpp
#include <iostream>
#include <string_view>
#include "json.hpp"

using json = nlohmann::json;

namespace nlohmann {
    template<>
    struct adl_serializer<std::string_view> {
        static void to_json(json& j, const std::string_view& value) {
            j = std::string(value.data(), value.size());
        }
        
        static void from_json(const json& j, std::string_view& value) {
            auto ref = j.get_ref<const std::string&>();
            value = std::string_view(ref.data(), ref.size());
        }
    };
}

int main(int argc, char* argv[]) {
    json data = std::string_view("hi");
    std::cout << data << std::endl;
    data = "hello";
    std::string_view sv = data;
    std::cout << sv << std::endl;
}
```

**Comment by gregmarr** [comment]
Note that the lifetime of `data` here must be at least as long as the lifetime of `sv`, or you'll end up with dangling pointers in `sv`.

**Comment by lethe555** [comment]
I only add `adl_serializer::to_json`  , `adl_serializer::from_json`  may lead to a mistake with the description above
thanks!

**Comment by nlohmann** [comment]
FYI: After merging #1028, conversions from/to `std::string_view` are now supported out of the box.

**Comment by JasonDictos** [comment]
For the next guy:

```
        static void from_json(const json& j, std::string_view& value) {
            auto ref = j.get_ref<const std::string&>();
            value = std::string_view(ref.data(), ref.size());
        }
```

Change 'auto ref' to 'auto &ref', otherwise the string is copied then destructed when the frame leaves, resulting in an invalid string view returned.
