### ISSUE TITLE
_finite and _isnan are no members of "std"

### ISSUE THREAD

**Issue by COOLGAMETUBE** [nlohmann/json#808]
![image](https://user-images.githubusercontent.com/6717311/32136669-0df2b9b6-bc12-11e7-8f34-06cd875aa217.png)

**Comment by COOLGAMETUBE** [comment]
those are defined, but not in the std namespace.

**Comment by nlohmann** [comment]
MSVC tests succeed with MSVC 2015 and 2017y which version are you using?

**Comment by COOLGAMETUBE** [comment]
I am using MS Visual Studio Community 2017 with the newest update and WindowsSDK 10.0.15063.0

It does work tho when i remove the namespace

**Comment by COOLGAMETUBE** [comment]
Also quick question, which isn't actually related with this issue: Is there a function to make it ready for HTML Js strings? like make out of `var example = "{"hi", "bla"}";` to `var example = "{\"hi\", \"bla\"}";` safely

**Comment by nlohmann** [comment]
Do you compile the test suite or some custom code?

**Comment by nlohmann** [comment]
Strangely, the error message mentions `_finite` and `_isnan` which are both not in the highlighted line.

**Comment by gregmarr** [comment]
I would check your include files for something like

    #define isfinite(x) _finite(x)
    #define isnan(x) _isnan(x)

**Comment by COOLGAMETUBE** [comment]
it is defined. but not in the std namespace. It works when i remove the std namespace in those lines. Also on of our other devs do have the issue aswell, while an other one doesn't.

**Comment by gregmarr** [comment]
If you have those defines, then the code that calls `std::isfinite` is being changed to instead call the non-existent function `std::_finite`, which is why you're getting the error.

**Comment by COOLGAMETUBE** [comment]
std::isfinite is NOT defined
isfinite is defined

**Comment by gregmarr** [comment]
The preprocessor doesn't care about the `std::` part.

**Comment by nlohmann** [comment]
This seems not to be an issue of the library.
