### ISSUE TITLE
This shit is shit 

### ISSUE THREAD

**Issue by reijpower** [nlohmann/json#809]
When not even loading works without an error
`
std::ifstream f("issue325.json");
    json j = json::parse(f);`
Its just supposed to load json not to crash my whole project. never use again

**Comment by nlohmann** [comment]
@reijpower Please respect this project's [code of conduct](https://github.com/nlohmann/json/blob/develop/CODE_OF_CONDUCT.md).

How exactly did parsing a JSON file crash your project? Please provide detailed information so we can analyze this issue.

**Comment by gregmarr** [comment]
My guess is that it threw a parsing exception and @reijpower didn't use any exception handling around the parse call.

**Comment by reijpower** [comment]
sorry for my language, everything worked fine after i found a working example, i dont know what the reason was it didnt work at first
