### ISSUE TITLE
stream error 

### ISSUE THREAD

**Issue by benglishSCSU** [nlohmann/json#815]
I've been trying to implement this solution and I have been consistently getting the same stream error, regardless of the json file or example I use/follow. I know I'm probably doing something silly but I'm a lowly junior in my CS degree. Here is my code:

```cpp
#include "json.hpp"

#include <fstream>

using json = nlohmann::json;

int main() {
    std::ifstream ifs{"file.json"};
    json parsed_json = json::parse(ifs);
    return 0;
}
``` 

and here is the json I've been using:
```js
[
  {
    "stringKey": "Nathen",
    "intKey": 236
  },
  {
    "stringKey": "Emerald",
    "intKey": 739
  },
  {
    "stringKey": "Franco",
    "intKey": 544
  }
]
```

and here is the error:
`/home/bry/CLionProjects/jsonexample/cmake-build-debug/jsonexample
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stream error
Process finished with exit code 134 (interrupted by signal 6: SIGABRT)`

**Comment by nlohmann** [comment]
Could you please try with the `develop` version. There, the exception should contain more information where the parse error occurs (though the file looks OK).

**Comment by benglishSCSU** [comment]
How would I go about doing that? 

Also, I ran the same program from my linux command line and the program executed perfectly. The issue I've reported happens when using CLion.

**Comment by nlohmann** [comment]
Please try with this header: https://github.com/nlohmann/json/raw/develop/src/json.hpp

**Comment by nlohmann** [comment]
Any news on this?

**Comment by benglishSCSU** [comment]
Sorry, I was out deer hunting this past weekend and I've had some other projects to work on. I will try it tonight.

**Comment by benglishSCSU** [comment]
I still receive an error, here's the output

`terminate called after throwing an instance of 'nlohmann::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at 1: syntax error - unexpected end of input; expected '[', '{', or a literal`

**Comment by nlohmann** [comment]
It seems the file could not be opened - the first thing the parser sees is the end of file. In your example, can you make sure it is properly opened? Can you `std::cout << ifs << std::endl;`?

**Comment by benglishSCSU** [comment]
So I did manage to figure it out, I simply added the whole file path instead of just the file name. Thanks for all your help, this newbie appreciates it!

**Comment by nlohmann** [comment]
No worries. Thanks for checking back!

**Comment by feugen** [comment]
Hello, I have the same issue, its working only for the whole file path but its not a solution for me. :-(

**Comment by benglishSCSU** [comment]
This isn't an issue related to this repository, it's an issue connected to your IDE

**Comment by nlohmann** [comment]
@feugen Could you please provide more information?

**Comment by feugen** [comment]
What information do you need? I am using QtCreator and I dont thinnk its an IDE issue. The output of the binary is wrong, it says 

> terminate called after throwing an instance of 'std::invalid_argument'
  what():  stream error

If I use the full path to my json file, I dont get this error, the output of the binary is the expected one.

**Comment by gregmarr** [comment]
That's because if you don't use the full path to the file, then the part you use is combined with the working directory to form the full path.  If you just include the filename and not the path, then it will only find your file if your working directory is the directory containing the file.  That depends on how you're running the program.  It is not related at all to this library.  You'll find that this error does not change even if you remove all traces of the JSON library from your program.

**Comment by feugen** [comment]
Ah ok, just moved my json file to a working directory and the error is gone, lol.

**Comment by abkalyan** [comment]
Hi, I'm still getting the same error as @ghost, where my error is: 

terminate called after throwing an instance of 'nlohmann::detail::parse_error' what(): [json.exception.parse_error.101] parse error at 1: syntax error - unexpected end of input; expected '[', '{', or a literal

How would I approach it? I tried using the whole path, but that doesn't seem to be fixing it. 

- Adit

**Comment by nlohmann** [comment]
Can you access the content of the file without passing it to the JSON library?

**Comment by abkalyan** [comment]
So apparently my issue has something to do with initializer lists, dsteeam and command line args. When I pass a command line argument [: jsonFileIn("./result.json")] through an fstream initializer list, it didn't read anything in the file. But when I explicitly write[ : jsonFileIn("./result.json")] it works.  I still don't get why this works, but I guess it does?

Long story short, it had nothing to do with your library.

**Comment by abkalyan** [comment]
Thanks for responding so promptly though

**Comment by LucaMarconato** [comment]
I having a similar problem and I think it is related to the one described in this topic. I am using macOS.

If I open a terminal, go to the folder in which the executable is located and run the executable, everything works. But if I run `open -a Termina.app name_of_executable` (which is equivalent to double clicking to the executable from the Finder) I got the following error:

`libc++abi.dylib: terminating with uncaught exception of type nlohmann::detail::parse_error: [json.exception.parse_error.101] parse error at 1: syntax error - unexpected end of input; expected '[', '{', or a literal`

The `argv[0]` parameters coincides for both the way of executing the program.

**Comment by LucaMarconato** [comment]
Looking at `boost::filesystem::path full_path(boost::filesystem::current_path());` I noticed that this path changes depending on the way I am executing the program, so the .json file was not found in one case.

**Comment by OPENFIVE** [comment]
> So apparently my issue has something to do with initializer lists, dsteeam and command line args. When I pass a command line argument [: jsonFileIn(argv[2])] through an fstream initializer list, it didn't read anything in the file. But when I explicitly write[ : jsonFileIn("./result.json")] it works. I still don't get why this works, but I guess it does?
> 
> Long story short, it had nothing to do with your library.
>you can pass a command line argument[:jsonFileLn(argv[1])],Maybe you get null commend message!

**Comment by nhule11** [comment]
I have the same problem. I'm getting Json string from TCP protocol. I get some packets perfect but then I get an error "
terminate called after throwing an instance of 'std::invalid_argument'
  what():  parse error - unexpected '"'; expected string literal
Aborted
"


this is how I convert my char into string then into Json "
        std::string s = (string(buf, 0, bytesReceived));
        json j = json::parse(s);
        cout << j.dump(4) << endl;
"
I'm a newbie to c++ and raspberrypi. I really appreciate if anyone can help.

**Comment by nlohmann** [comment]
The exception says the received JSON is invalid. Try to print `s` it to `std::cout` before parsing and check if the value is indeed valid JSON.

**Comment by nhule11** [comment]
@nlohmann You are right the string which I was receiving was incomplete. Your library works perfect! Thank you.

**Comment by Wangyouai** [comment]
@nlohmann Hello When I used this code `./surfelwarp_app /path/to/config` under ubuntu16.04 to run the _surfelwarp_app_ file in **application/x-executable** format, I encountered the same error: terminate called after throwing an instance of'nlohmann::detail: :parse_error'   what(): [json.exception.parse_error.101] parse error at 1: syntax error-unexpected end of input; expected'[','{', or a literal
The error seems to be unable to open the json file, because after I delete the json file, I still encounter this error when I run it again. I think it may be necessary to read the absolute path,
However, currently I cannot view and modify how _surfelwarp_app_ reads the json code through the compiler, so do you have other ways to solve this problem?

**Comment by nlohmann** [comment]
The error means in 99.9% of the time that the stream is broken somehow and the parser could not read a single byte. Please double check that the stream is OK, e.g., by trying to print it to stdout.

**Comment by Wangyouai** [comment]
> Looking at `boost::filesystem::path full_path(boost::filesystem::current_path());` I noticed that this path changes depending on the way I am executing the program, so the .json file was not found in one case.

So I want to know how you solved this problem？ please

**Comment by Wangyouai** [comment]
> The error means in 99.9% of the time that the stream is broken somehow and the parser could not read a single byte. Please double check that the stream is OK, e.g., by trying to print it to stdout.
Is this stdout?
```
wya@wya:~/project/SW/surfelwarp/test_data$ cat boxing_config.json
{
    "clip_far":1300,
    "clip_near":10,
    "data_prefix":"/home/wei/Documents/programs/surfelwarp/test_data/boxing",
    "depth_focal_x":570.0,"depth_focal_y":570.0,"depth_principal_x":320.0,"depth_principal_y":240.0,
    "gpc_model_path":"/home/wei/Documents/programs/surfelwarp/test_data/sintel_small_speed",
    "image_cols":640,"image_rows":480,
    "start_frame":0,
    "num_frame":310,
    "rgb_focal_x":570.0,"rgb_focal_y":570.0,"rgb_principal_x":320.0,"rgb_principal_y":240.0,
    "use_periodic_reinit":false,
    "reinit_period":30,
    "use_density":true,
    "use_foreground":false,
    "use_offline_foreground":false
}

```

**Comment by nlohmann** [comment]
What I meant is that you need to make sure the stream you pass to the library is valid.
