### ISSUE TITLE
Conan package for the library

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [nlohmann/json#817]
Hello,
Do you know about Conan package manager? Can you add Conan package for the library and maintain it? Here you can find example of my conan recipe for libpng: https://github.com/ZaMaZaN4iK/conan-libpng

**Comment by gregmarr** [comment]
See the README: If you are using Conan to manage your dependencies, merely add jsonformoderncpp/x.y.z@vthiery/stable to your conanfile.py's requires, where x.y.z is the release version you want to use.

**Comment by ZaMaZaN4iK** [comment]
But why there is no this package in conan-center repo?

**Comment by gregmarr** [comment]
See the next line of the README: Please file issues [here](https://github.com/vthiery/conan-jsonformoderncpp/issues) if you experience problems with the packages.
