### ISSUE TITLE
vs2015 error : static member will remain uninitialized at runtime but use in constant-expressions is supported

### ISSUE THREAD

**Issue by xtythansky** [nlohmann/json#824]
on some vs2015 occurs 
`json.hpp(887): error C4579: 'nlohmann::detail::static_const<nlohmann::detail::to_json_fn>::value': in-class initialization for type 'const T' is not yet implemented; static member will remain uninitialized at runtime but use in constant-expressions is supported
 with
        [
            T=nlohmann::detail::to_json_fn
        ]

`

**Comment by gregmarr** [comment]
This, I believe, fixed in Update 3.
