### ISSUE TITLE
std::map<std::string, std::string> from json object yields C2665: 'std::pair<const _Kty,_Ty>::pair': none of the 2 overloads could convert all the argument types

### ISSUE THREAD

**Issue by na-n** [nlohmann/json#827]
please close me, I am a duplicate of #734.

**Comment by gregmarr** [comment]
The map underlying a `json` object is of type `std::map<std::string, json>`.  The value of each entry can be any of the valid `json` types, so this isn't a compile-time conversion.  You will probably have to iterate through all of the entries in the object and check their types manually.  I'm not aware of any magic in the library that will allow you to pull out just the items with a string value type.  (Maybe one of the other users/maintainers knows of some method here that I don't.)

**Comment by gregmarr** [comment]
If you're going to do this more than once, you might be able to do something with the code from this section of the README:

>This serializer works fine when you have control over the type's namespace. However, what about boost::optional, or std::filesystem::path (C++17)? Hijacking the boost namespace is pretty bad, and it's illegal to add something other than template specializations to std...

    namespace nlohmann {
        template <typename T>
        struct adl_serializer<std::map<std::string, std::string>> {
            static void from_json(const json& j, std::map<std::string, std::string>& mapss) {
                // If j is an object, iterate over the values of j and store the ones that are strings
            }
        };
    }

**Comment by na-n** [comment]
Thanks for your timely response @gregmarr, but this appears to be a duplicate of #734 I'm afraid. I think that approach was mentioned on 734 by leozzyzheng. 734 was closed, but I'm not sure what the consensus was. 

From 734:

> I am confused...

Me too.

**Comment by na-n** [comment]
I've figured it out @gregmarr. Thanks again for the timely responses. I've posted a suggested workaround on #734. I'll be quiet now. :)
