### ISSUE TITLE
Application terminating

### ISSUE THREAD

**Issue by pompex** [nlohmann/json#830]
When I'm trying to run compiled application with simple parse code it fails with an exception:

> [json.exception.parse_error.101] parse error at 73: syntax error - unexpected '}'; expected string literal

Code:

```
int main() {
    std::ifstream     file("test.json");
    std::stringstream buffer;
    buffer << file.rdbuf();

    json config;

    try {
        config = json::parse(buffer);
    } catch (const json::exception& e) {
        std::cout << "Loading error: " << e.what() << "\n";
        exit(-1);
    }

    try {
        std::cout << "Name: " << config["name"] << "\n";
    } catch (const json::exception& e) {
        std::cout << "Couldnt parse: " << e.what() << "\n";
        exit(-1);
    }
    return 0;
}
```

JSON file is indeed valid:

```
{
  "pi": 3.141,
  "happy": true,
  "name": "Niels",
  "nothing": null,
}
```

Compiler:

Thread model: win32
gcc version 6.3.0 (MinGW.org GCC-6.3.0-1)

Bug or something I'm doing wrong?

**Comment by gregmarr** [comment]
As the error says, the JSON file is invalid.  You have a comma after `null` which doesn't belong.

**Comment by pompex** [comment]
Oh right. Been tired.
