### ISSUE TITLE
Show the path of the currently parsed value when an error occurs

### ISSUE THREAD

**Issue by santilin** [nlohmann/json#835]
**Feature Request**
It would be nice to get the path of the json file when an error occurs. Currently, only the type of the error is printed, with no way to know where in the json tree it happend, so it is very difficult to find the error.

For parse errors, I have implemented a way to show the place of the error:

```cpp
	try {
		return json::parse(f);
	} catch( nlohmann::detail::parse_error &e ) {
		Xtring err = e.what();
		std::cout << err << std::endl;
		if (e.byte > 1 )
			f.seekg(e.byte - 2);
		else 
			f.seekg(0);
		char text[121];
		f.read(text, 120);
		std::cout << text << std::endl;
		exit(1);
	}
    }
```

And for type errors, I have tweaked the code for every JSON_THROW so that I get a dump of the value being parsed. But as I can not get the parent nor the name, only the value, I don't know where the error in the parse tree es:

```cpp
        JSON_THROW(type_error::create(302, "type must be string, but is " + std::string(j.type_name()) + j.dump() ));
```

**Comment by nlohmann** [comment]
- I understand your usecase, but I am hesitant into serializing whole JSON values into exceptions.
- About the parse errors: you perfectly showed that such a feature is possible without a library change, and following the “not pay for what you don't use” principle, I don't think that we should add this to the library - especially printing to an output stream.
