### ISSUE TITLE
Use reference or pointer as Object value

### ISSUE THREAD

**Issue by go2sh** [nlohmann/json#841]
Hi there,

I have a small question. Is it possible to set the value of an object element to a reference or point without copying it?
What I like to achieve is the following
```
json data, result, response;
bool hasError = calcResult(data, result);
if (hasError) {
response["error"] = result; // no copy
} else {
response["result"] = result; // nocopy
}
```
Thanks for your help. :)

**Comment by nlohmann** [comment]
No, this is currently not possible. The only thing that could avoid copies is to move the data to the JSON value.

**Comment by go2sh** [comment]
@nlohmann just for fun. Would it be hard to change the behavior? I guess so...

**Comment by itviewer** [comment]
I use this method to avoid copying
>     
    json data;
    json response = {{"result",{}}};
    json &result = response["result"];

    bool hasError = calcResult(data, result);
    //std::cout << response ;

**Comment by nlohmann** [comment]
Of course, you can use references to JSON values where possible - you just can't store them in a JSON value itself.

**Comment by nlohmann** [comment]
Can I close this issue?

**Comment by go2sh** [comment]
Yes, I found some ways around it. SharedPtr and Value References. Thanks.

**Comment by CraigHutchinson** [comment]
+1 For supporting references to allow:
json **datas** = { "vals", json::array() };
… elsewhere ..
json document = { {"meta", "something"}, {"content", **datas**} );
… next..
datas["vals"] = **{1,2,3,4,5}**
… so …
document.dump() == { {"meta", "something"}, {"content", **[1,2,3,4,5]** } );
