### ISSUE TITLE
Iteration weirdness

### ISSUE THREAD

**Issue by Exaeta** [nlohmann/json#842]
**Feature Request**

It seems that right now iterating over a `json` object iterates over it as though it was an array, which is counter intuitive from the C++ perspective, which you would expect to be iterated like a `std::map`.

I suggest `json::as_map()` and `json::as_array()` so that one can do:

```C++
void foobar (nlohmann::json js1, nlohmann::json js2)
{
  for (auto & x : js2.as_map())
  {
    foo(x.first, x.second);
  }

  for (auto & x : js2.as_array())
  {
    bar(x);
  }
}
```

Both would return proxy objects (objects that contain a reference to the original, and different `begin()` and `end()` functions.)

**Comment by nlohmann** [comment]
Have you seen the `iteration_wrapper`? Here is an example: https://github.com/nlohmann/json/blob/develop/doc/examples/iterator_wrapper.cpp

**Comment by pingsoli** [comment]
@nlohmann 
Sorry to disturb you. How to merge two json arrays into one ? such as  
[ { "name": "Ally", "age": "11" }, ... ] and [ {"name": "Bob", "age": "10"}, ...  ] merge into 
[ {"name": "Ally", "age": "11" }, ... , {"name": "Bob", "age": "10"}, .... ].

Using iterator can solve it , but, do you have another way? or a faster way?

I'm really sorry to trouble you, I'll appreciate your reply. Thanks.

**Comment by nlohmann** [comment]
@pingsoli see #428.

**Comment by Exaeta** [comment]
@nlohmann .key() and .value() are kinda weird from the C++ world. I think imitating std::map would be better personally.

**Comment by nlohmann** [comment]
I did not find a better way. PRs welcome!

**Comment by nlohmann** [comment]
@Exaeta Do you have an idea how to implement a better interface?

**Comment by nlohmann** [comment]
Any news on this?

**Comment by Exaeta** [comment]
I'm not super familiar with the implementation, but thinking about it, you'd probably lose the array vs object distinction if you did that, so maybe an obvious solution is not available.

**Comment by nlohmann** [comment]
Related: #874

**Comment by nlohmann** [comment]
I'm closing this. Hopefully, #874 solves this issue.
