### ISSUE TITLE
Converting to array not working

### ISSUE THREAD

**Issue by hsdk123** [nlohmann/json#843]
Converting from an std array to json works fine.
However, the other way round gives errors.

```
json j;
std::array<int, 4> ar = {1, 1, 1, 1};
j = ar; // works fine
ar = j; // breaks
```

I'm given the error that 'insert' doesn't exist for array.
Considering we're given j.size(), I believe this shouldn't be something that should be breaking. 
(since I can already work around this by creating a loop that adds individual elements)

**Comment by nlohmann** [comment]
Duplicates #553

**Comment by nlohmann** [comment]
On the other hand: a conversion that checks the bounds and throws an exception in case the array does not match the JSON‘s size would be better here.

**Comment by hsdk123** [comment]
@nlohmann 
Thanks for the quick reply - yup, checking bounds and throwing exceptions if outside sound like an implementation that would be helpful and functional.

**Comment by nlohmann** [comment]
Are you using the `develop` version? There, https://github.com/nlohmann/json/blob/develop/src/json.hpp#L1235 implements the conversion:

```cpp
template<typename BasicJsonType, typename T, std::size_t N>
void from_json_array_impl(const BasicJsonType& j, std::array<T, N>& arr, priority_tag<2> /*unused*/)
{
    for (std::size_t i = 0; i < N; ++i)
    {
        arr[i] = j.at(i).template get<T>();
    }
}
```

Up to `N` elements are copied to the `std::array`. If the JSON array is too short, an exception is raised. If the `std::array` is shorter than the JSON array, no further values are copied.

**Comment by hsdk123** [comment]
@nlohmann 
I'm using the latest 'release' - I'm currently trying to use the library for production code, but it's going to be difficult to get use permission for code being marked as being in the develop branch.

I see the final release was in February, are there plans on a nearby official release?

**Comment by nlohmann** [comment]
I hope to get the 3.0.0 release out this year.

**Comment by nlohmann** [comment]
I'm closing this issue as there is nothing I can do here right now.
