### ISSUE TITLE
MSVC2017, 15.5 new issues.  

### ISSUE THREAD

**Issue by aj664** [nlohmann/json#857]
yesterday 2017.12.05  using MSVC2017, 15.4.4   was compiling v.2.1.1 fine.
today, upgraded to MSVC2017 15.5..  now v2.1.1 has lots of std::allocator warnings/errors.

**Comment by nlohmann** [comment]
Related: #856

**Comment by aj664** [comment]
if you aren't going to make the changes MS suggest for reasons of other-compiler compatibility, then at least add the #define the error suggests to suppress the warning.

**Comment by nlohmann** [comment]
What is Microsoft suggesting? I am not using MSVC myself, so I am surprised that existing code would break with a new MSVC version.

**Comment by aj664** [comment]
#define _SILENCE_CXX17_OLD_ALLOCATOR_MEMBERS_DEPRECATION_WARNING

if you wanted to add  #if _MSC_VER >= 1912  around that too, it might help readers to understand when/if/what it's for.

**Comment by nlohmann** [comment]
Is this relevant unless you choose C++17 as standard? Did you try whether the code of #856 still exhibits these warnings?

**Comment by aj664** [comment]
I am compiling with C++17, i imagine a lot of people now do.  after adding
 #define _SILENCE_CXX17_OLD_ALLOCATOR_MEMBERS_DEPRECATION_WARNING  
all warnings/errors  have gone; and v.2.1.1 compiles without error again.  

i don't see a reason not to add this #define, it's clearly something that will need to be addressed eventually. it breaks builds without it.  it's a C++17 issue, not a MS specific one, it's just co-incidence the first compiler to deprecate it is the MS one.  By adding this define i don't think you are hiding a bug, just a valid deprecation warning.

**Comment by nlohmann** [comment]
If I understand correctly, #856 is addressing these warnings by solving them instead of defining away the deprecation warnings.

**Comment by aj664** [comment]
I think it is attempting that,  but if that fails to work because it's introducing features only supported in C++17 then that would break your C++11 support?!    Aren't you trying to support C++11 still?   are the proposed std::allocator_traits a supported C++11 feature?!  

if the patch can not be applied because of breaking changes, then the #define _SILENCE_CXX17_OLD_ALLOC..  would allow the old code to continue to work, AND allow modern compilation to succeed.

**Comment by nlohmann** [comment]
@aj664 Could you check whether #856 fixes the warnings? Alternatively, could you post the error/warning messages you mentioned in your report?

**Comment by nlohmann** [comment]
(#856 is merged, so could someone check the develop branch with MSVC2017?)

**Comment by erengy** [comment]
I can confirm that #856 fixes the following warning in Visual Studio 2017 version 15.5:

> warning STL4010: Various members of `std::allocator` are deprecated in C++17. Use `std::allocator_traits` instead of accessing these members directly. You can define `_SILENCE_CXX17_OLD_ALLOCATOR_MEMBERS_DEPRECATION_WARNING` or `_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS` to acknowledge that you have received this warning.

I get a couple of these with v2.1.1, but the `develop` branch is fine.

**Comment by nlohmann** [comment]
Thanks a lot!
