### ISSUE TITLE
Make optional user-data available in from_json

### ISSUE THREAD

**Issue by chadlayton** [nlohmann/json#864]
I'd like to be able to supply optional user-data to json::parse which would then be retrievable in from_json. A naive implementation might look like this:

```c++
void from_json(const json& j, image& img, void* user_data)
{
	const char* root_directory = reinterpret_cast<const char*>(user_data);
	std::string filename = j["filename"];

	img.data = load_external_dependency(std::string(root_directory) + "//" + filename);
}

// ...

json j = json::parse(json_string, "C:\\images\\");
```

Or maybe this is already possible? Right now the only way I can see to do it requires global state or caching the data on the object and fixing it up after parsing.

**Comment by theodelrieu** [comment]
I have thought about it, but I fail to see how the library could call `from_json` with the extra argument.

I would say that such logic should be avoided in `from_json`, you can always embed that in your type.

Could you precise your use case?

**Comment by chadlayton** [comment]
My exact use case is very much like the one I shared except the root directory isn't hard-coded. In practice it will be relative to wherever the json was loaded from. For example:

```
C:/models/
  badguy/
     badguy.json
       { "filename" : "images/badguy.png" }
     images/
       badguy.png
```

I'd prefer to not save the filename at all since only the data is important. And I don't want to use global state since there could be multiple threads doing jobs that require different root directories. Another option for the user data would be caching it on the json object itself somehow?

**Comment by jaredgrubb** [comment]
I would like to see a visitor-based parse API, which would be perfect for things like this. (Would also make it possible to implement a "does it parse" API as well as many other variants). Something like:

MyVisitorWithExtraStuff visitor{helpfulThing1, helpfulThing2};
auto parsedThing = json::parse(visitor, source);

**Comment by gregmarr** [comment]
@jaredgrubb Like this?

https://github.com/nlohmann/json/blob/develop/src/json.hpp#L12914-L12916

    static basic_json parse(detail::input_adapter i,
                            const parser_callback_t cb = nullptr,
                            const bool allow_exceptions = true)

**Comment by jaredgrubb** [comment]
Hm... I didn't know that was there! I'll have to see if that will do what I was hoping.

**Comment by nlohmann** [comment]
Can I close this issue?

**Comment by chadlayton** [comment]
I think @jaredgrubb found a solution to his problem but mine is still the same as presented originally - wanting to pass some kind of user-data / context through to the from_json methods. It's a just a feature request though so of course you're free to close the issue if you like :)

**Comment by nlohmann** [comment]
I think we are not able to make this extension. The whole `from_json` stuff is pretty advanced, and if @theodelrieu has no idea, then we are out of luck.
