### ISSUE TITLE
unicode strings

### ISSUE THREAD

**Issue by zoncpp** [nlohmann/json#878]
- How do I work by unicode json strings. 

I have unicode strings in my json . some values are unicode .
Now, how do I change the json class (json.hpp) for my project?

My Project is in VS 2015.

**Comment by nlohmann** [comment]
I do not understand the question. The library only supports UTF-8. If you mean this with "Unicode", then everything should be fine. If not, could you please provide example code and the respective error message?

**Comment by zoncpp** [comment]
Setting of my VC Project in Character Set is "Use Unicode Character Set"
Then I have Unicode strings in values of Json String :
```
auto j3 = json::parse("{ \"name\": \"زهره\", \"LastName\": \"نادری\" }");
	CString ss = j3["name"];
```
this assigned has error

**Comment by nlohmann** [comment]
The library stores strings as `std::string`. Maybe assigning it to a `CString` does not work. What is the exact error message?

**Comment by zoncpp** [comment]
CString or std::wstring . both has error.
`std::wstring ss = j3["name"];
`
that error is:

json.hpp(1384): error C2100: illegal indirection

**Comment by nlohmann** [comment]
Maybe helpful: https://stackoverflow.com/a/258052/266378

**Comment by nlohmann** [comment]
As I wrote before: the library stores strings as `std::string`. If you want to convert them to another type like `CString` or `std::wstring`, then you need to provide the code for this.

**Comment by zoncpp** [comment]
Thanks so much for your online response

**Comment by nlohmann** [comment]
I added an FAQ entry: https://json.nlohmann.me/home/faq/#wide-string-handling
