### ISSUE TITLE
Container function overview in Doxygen is not updated

### ISSUE THREAD

**Issue by pravic** [nlohmann/json#883]
**Bug Report**

- What is the issue you have?
Outdated documentation.

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?
Check https://nlohmann.github.io/json/

- What is the expected behavior?
`json::parse_error` instead of `std::domain_error` and so on.

- And what is the actual behavior instead?
We see old exception types still.

- Did you use a released version of the library or the version from the `develop` branch?
Documentation [says](https://nlohmann.github.io/json/) it is version `3.0.0`.
 
P.S. 3.0 is a huge and exciting work, actually.

**Comment by nlohmann** [comment]
Thanks for reporting! This was an oversight.

**Comment by nlohmann** [comment]
Fixed:

<img width="1175" alt="table" src="https://user-images.githubusercontent.com/159488/34194323-7d7e37d2-e558-11e7-8c97-ff0b2e020b9e.png">
