### ISSUE TITLE
JSON Pointer resolve failure resulting in incorrect exception code

### ISSUE THREAD

**Issue by cmannett85** [nlohmann/json#888]
```cpp
int main()
{
    auto model = R"({
        "a": {
            "b": 42
        }
    })"_json;

    try {
        model.at("/a/c"_json_pointer);
    } catch (json::exception& e) {
        std::cout << "ID: " << e.id << std::endl;
    }

    return EXIT_SUCCESS;
}
```
Prints:
> ID: 403

According to the `json::out_of_range` and `json::at(const json_pointer&)` docs, a JSON pointer that cannot be resolved should return a 404, but it actually returns a 403.

**Comment by nlohmann** [comment]
Thanks for the info! I'll check.

**Comment by nlohmann** [comment]
Fixed. See http://nlohmann.github.io/json/classnlohmann_1_1basic__json_a8ab61397c10f18b305520da7073b2b45.html#a8ab61397c10f18b305520da7073b2b45

<img width="1171" alt="documentation" src="https://user-images.githubusercontent.com/159488/34321513-1c677f38-e811-11e7-8b96-2163cf4f6f27.png">

**Comment by nlohmann** [comment]
@cmannett85 Can you please have a look whether the updated documentation better describes the behavior of the function?

**Comment by cmannett85** [comment]
@nlohmann, can you explain the difference between a 403 and 404 error?  In the example code:
```
    // out_of_range.403
    try
    {
        // try to use a JSON pointer to an nonexistent object key
        json::const_reference ref = j.at("/foo"_json_pointer);
    }
    catch (json::out_of_range& e)
    {
        std::cout << e.what() << '\n';
    }

    // out_of_range.404
    try
    {
        // try to use a JSON pointer that cannot be resolved
        json::reference ref = j.at("/number/foo"_json_pointer);
    }
    catch (json::out_of_range& e)
    {
        std::cout << e.what() << '\n';
    }
```
In the latter example `foo` is a non-existent object key in `number`, so why does not it not also throw a 403?

**Comment by nlohmann** [comment]
Take

```js
{"one": 1, "two": 2, "list": [1,2,3]}
```

as example.

- JSON Pointer `/bar` yields 403, because `/` is an object, but key `bar` was not found.
- JSON Pointer `/list/foo` yields 404, because `/list` is an array, and `foo` makes no sense here.

**Comment by cmannett85** [comment]
Ah, so a 403 is always thrown when a missing object member is requested, whilst a 404 is thrown when the JSON pointer is invalid (as opposed to 'malformed')?  If so, why does the last example in your link throw a 404 instead of a 403 (as `number` is an object)?

**Comment by nlohmann** [comment]
In the example, `/` is an object, `/number` is the number `1`, so `/number/foo` fails, because a number is not an object, so there cannot be a key `foo`.

**Comment by cmannett85** [comment]
I finally understand!  Your documentation update addresses the issue, so I'll close this issue.

**Comment by nlohmann** [comment]
:)
