### ISSUE TITLE
Nonstandard integer type

### ISSUE THREAD

**Issue by arnaudbrejeon** [nlohmann/json#89]
Hi,

the following does not build on OSX with C++14:

    #include "nlohmann.json.hpp"
    using json = nlohmann::basic_json<std::map, std::vector, std::string, bool, int32_t, float>;
    int main(int argc, const char * argv[]) {   
        json j;
        j["int_1"] = 1; << Conversion from 'int' to 'nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>, bool, int, float, std::allocator>' is ambiguous
        return 0;
    }

I'd rather use number type *int32_t* instead of the default *int64_t* (which builds properly). Do you have any idea how to fix this issue?
Thank you,

Arnaud

**Comment by nlohmann** [comment]
I understand the problem - it is a conflict with the solution to issue #71. I see what I can do.

**Comment by nlohmann** [comment]
Your code example should work now - I added a respective test case.

**Comment by arnaudbrejeon** [comment]
It's working perfectly. Thank you for your super-fast feedback.
