### ISSUE TITLE
[Request] Macro generating from_json() and to_json()

### ISSUE THREAD

**Issue by unrealmistake** [nlohmann/json#895]
Making to_json() and from_json() for all classes in my object model is a chore.
I want to create a macro that would generate bodies for these functions. I saw some clues how to make it, but my knowledge of C++ is not good enough to implement it.
I want to be able to write something like this:
```cpp
class MyClass
{
...
    JsonVar(int, intvar)
    JsonVar(string, stingvar)
...
}
void to_json(json& j, const MyClass& p) {
JsonTo(MyClass)
... //some extra serialization
}
void from_json(const json& j, MyClass& p) {
JsonFrom(MyClass)
... //some extra deserialization
}
```
and get
```cpp
class MyClass
{
...
    int intvar;
    string stringvar;
...
}
void to_json(json& j, const MyClass& p) {
j = json{ { "intvar", p.intvar},
			{ "stringvar", p.stringvar} };
... //some extra serialization
}
void from_json(const json& j, MyClass& p) {
p.intvar= j.at("intvar").get<int>();
p.stringvar= j.at("stringvar").get<string>();
... //some extra deserialization
}
```

**Comment by nlohmann** [comment]
I also have little experience in this. You may want to have a look at cereal (http://uscilab.github.io/cereal/index.html) which employs some nice macro magic.

**Comment by unrealmistake** [comment]
Well, looks like I found a solution. It was inspired by [a topic on StackOverflow](https://stackoverflow.com/questions/41453/how-can-i-add-reflection-to-a-c-application)
Macros in boost are no magic at all, they are just a bunch of overrides for each parameter count. So boost dependency can be avoided by using the same technique.
Use of variadic macros is sugar. It only helps omitting parameter number.
Also, this code probably will not work with mingw. To add mingw support, you need to change all occurrences of MACRO arg to MACRO ## arg. I didn't test it on mingw though, that's just a guess from studying the code of boost.
And I didn't expect that extracting a name of variable is so... fun. Took me some time to find that I just need to be more insistent.
Here is my code for 1 and 2 arguments:
```
#define REM(x) x
#define EAT(x)
#define MAKEQUOTES(x) #x
#define PLEASEMAKEQUOTES(x) MAKEQUOTES x
#define PRETTYPLEASEMAKEQUOTES(x) PLEASEMAKEQUOTES((x))

// Strip off the type
#define STRIP(x) EAT x
//#define STRIP_AND_BRACE(x) (STRIP(x))
// Get the name of variable
#define NAMEOF(x) PRETTYPLEASEMAKEQUOTES(STRIP(x))
// Show the type without parenthesis
#define PAIR(x) REM x

#define JSONVARS1(a1) \
PAIR(a1);\
void _member_to_json(json& j) const { \
j = json{{ NAMEOF(a1), STRIP(a1) } \
		};\
} \
void _member_from_json(const json& j){ \
STRIP(a1) = j.at(NAMEOF(a1)).get<decltype(STRIP(a1))>();\
}

#define JSONVARS2(a1, a2) \
PAIR(a1);\
PAIR(a2);\
void _member_to_json(json& j) const { \
j = json{{ NAMEOF(a1), STRIP(a1) }, \
		{ NAMEOF(a2), STRIP(a2) } \
		};\
} \
void _member_from_json(const json& j){ \
STRIP(a1) = j.at(NAMEOF(a1)).get<decltype(STRIP(a1))>();\
STRIP(a2) = j.at(NAMEOF(a2)).get<decltype(STRIP(a2))>();\
}

#define TO_JSON(MyClass) inline void to_json(json& j, const MyClass& p) {\
p._member_to_json(j);

#define FROM_JSON(MyClass) inline void from_json(const json& j, MyClass& p) {\
p._member_from_json(j);

//to match the style
#define END }
```
Feel free to use it.
