### ISSUE TITLE
How to get the length of a JSON string without retrieving its std::string?

### ISSUE THREAD

**Issue by ibc** [nlohmann/json#897]
Basically that. I know that a `json` object holds a string and I need to know its length, hopefully without having to convert it into a C++ `std::string`.

Is it possible?

**Comment by ijijn** [comment]
Hi. How are you getting your `json` object?

Not sure that this helps, but if you do something like:
`const auto name{ j.value("name", "") };` (using the default-value hint technique for a `string_t` type)
you can then use `name.length()` to get the length without additional casting. That's how I usually do this sort of thing anyway, but I'm very new to the library ... and loving it!

**Comment by ibc** [comment]
Thanks @ijijn. Not valid for my use case, but good to know.

**Comment by rexdf** [comment]
- value access
-1. get  – get a value
-2. get_ptr  – get a value pointer
-3. get_ref  – get a value reference

string `json` object seems to be internally  implemented in `std::string`

**Comment by ibc** [comment]
Great. Perhaps this should be documented?

**Comment by rexdf** [comment]
https://nlohmann.github.io/json/

**Comment by ibc** [comment]
Thanks @rexdf, my absolute fault.

**Comment by nlohmann** [comment]
For reference:

```cpp
json j_string = "foo bar";
size_t len = j_string.get_ref<json::string_t&>().size();
```

**Comment by ibc** [comment]
Thanks. Would that also work if `json j_string = 1234`?

**Comment by nlohmann** [comment]
No. You would get an exception:

```
[json.exception.type_error.303] incompatible ReferenceType for get_ref, actual type is number
```
