### ISSUE TITLE
move code into namespace

### ISSUE THREAD

**Issue by nlohmann** [nlohmann/json#9]
The code should be moved into a namespace not to pollute the global namespace.

**Comment by PaulFreund** [comment]
While I encourage the use of namespaces and understand the current naming, I'd suggest using something more expressive. Without knowing the original origin of this code the namespace nlohmann might become meaningless, especially as you already have a bunch of forks that might differ with time.

On the other hand I admittedly don't have a better idea.

**Comment by connormanning** [comment]
Was hoping this had been addressed and came upon this ticket.  I fully agree with @PaulFreund, and I'll throw out alternatives like `json11`, `mjson` (`m` for "modern"), `njson` (`n` for native), etc.  Anything related to the library itself would be an improvement.

**Comment by gregmarr** [comment]
Using the github username of the main repo as the top level namespace is actually a good practice as it helps to locate the library and prevents any possibility of namespace collisions, at least on github.

If you want to use something else in your own code, you can create your own namespace alias.

http://en.cppreference.com/w/cpp/language/namespace_alias

**Comment by nlohmann** [comment]
I think it is too late now to change the name of the namespace...

**Comment by allanleal** [comment]
@nlohmann First, you've managed to develop a very elegant and simple to use json library. 
I was surprised, however, to learn that the namespace you chose, `nlohmann`, derives from your own name - something at least unusual. I know you think it is now too late to change, but I would encourage you to re-think. 

Some have suggested the use of namespace alias. I can understand the use of `namespace py = boost::python` for convenience reasons. However, users that decide to do, for example, `namespace json = nlohmann` indicate that something is strange.

Many thanks for all your work on this library. It needs now a more professional name to be consistent with its excellence.

**Comment by nlohmann** [comment]
@allanleal Thanks for the feedback. After so many versions already published, I *do* think it is to late to change the namespace, or at least I do not see the necessity to create a breaking change just for this. If using my own GitHub account name for the namespace may appear unprofessional, I am sorry - the truth is, this is a hobby project of mine.
