### ISSUE TITLE
[json.exception.type_error.304] cannot use at() with object

### ISSUE THREAD

**Issue by aprowe** [nlohmann/json#902]
Hi, I am getting 
```
[json.exception.type_error.304] cannot use at() with object
```

Which doesn't make sense to me, since I figured thats what `at()` is for. 
What does this error mean? Printing my json object it seems to look like a normal json string.

Code: 
```
  std::stringstream ss;

  // msgpack object
  ss << obj;

  std::cout << ss.str();
  // {"subject":"set_detection_mapping_mode", "mode":"3d"}

  std::string str;
  try {
    auto j = json::parse(ss.str().c_str());
    str = j.at('subject').get<std::string>();

  } catch (detail::type_error &e) {
    std::cout << e.what();
    // [json.exception.type_error.304] cannot use at() with object
  }
```

Thanks

**Comment by gregmarr** [comment]
@aprowe You have `.at('subject')` (single quotes).  You want `.at("subject")` (double quotes).

**Comment by aprowe** [comment]
Wow. Didn't even know I could use single quotes like that in c++. Thanks!

**Comment by gregmarr** [comment]
It's legal to have multiple characters between the quotes for things like hex escapes and unicode characters, but I'm surprised that your compiler didn't warn you about this.
