### ISSUE TITLE
C2864 error when compiling with VS2015 and VS 2017

### ISSUE THREAD

**Issue by xelatihy** [nlohmann/json#903]
**Bug Report**

I have several compiler errors of type C2864 when compiling of both VS2015 and VS2017. Using cmake build script with C++14 as required version.

I am using AppVeyor to build my app since I do not have a local Windows install, so I cannot verify whether it builds with your CMake.

First error is in 
/json.hpp(812): error C2864: 'nlohmann::detail::has_mapped_type::value': a static data member with an in-class initializer must have non-volatile const integral type

**Comment by nlohmann** [comment]
That is strange, because the project compiles without problems on AppVeyor, see https://ci.appveyor.com/project/nlohmann/json. You may want to check the flags set in the CMakefile, because this seems to be the only difference to your project.

**Comment by xelatihy** [comment]
I was able to track down the problem to an inclusion that fiddle with constexpr behaviour to fix it for non standard MSVC 2015 issues. It had nothing to do with your code, but showed up there (strangely enough). I am closing this. Thanks.

**Comment by rexdf** [comment]
constexpr maybe something about header order. See OpenCC/pull#285


Maybe you can try just to move the `json.hpp` to top of any Windows api and STL header.

**Comment by gutwinski** [comment]
@xelatihy , can you please give details about your solution? I think that I have come across a similar issue with MSVC 2015 Professional.  I get this error:

`error C4579: 'nlohmann::detail::static_const<nlohmann::detail::from_json_fn>::value': in-class initialization for type 'const T' is not yet implemented; static member will remain uninitialized at runtime but use in constant-expressions is supported`

It references the following code of `cpp_future.hpp`:
```
// taken from ranges-v3
template<typename T>
struct static_const
{
    static constexpr T value{};
};
```
Thanks for your help!
