### ISSUE TITLE
Problem when writing to file.

### ISSUE THREAD

**Issue by liorbiu** [nlohmann/json#904]
**Bug Report**

- What is the issue you have?

I'm trying to write json file to file. When I'm printing the json to the screen, I can see it created normally.
JSON example file:

```
[{
	"iteration_0": 13,
	"iteration_1": 11,
	"name": "ComputeCircuit"
}, {
	"iteration_0": 0,
	"iteration_1": 1,
	"name": "InputSharing"
}, {
	"iteration_0": 14,
	"iteration_1": 13,
	"name": "Online"
}, {
	"iteration_0": 5,
	"iteration_1": 2,
	"name": "GenerateTriples"
}, {
	"iteration_0": 6,
	"iteration_1": 2,
	"name": "Offline"
}]
```

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?
I attempt to create the json file using this code sample:

```
void Measurement::analyze(string type)
{
    string filePath = getcwdStr();
    string fileName = filePath + "/" + m_protocolName + "_" + type + "_partyId=" + to_string(m_partyId)
                      +"_numOfParties=" + to_string(m_numOfParties) + ".json";

    //party is the root of the json objects
    json party = json::array();

    for (int taskNameIdx = 0; taskNameIdx < m_names.size(); taskNameIdx++)
    {
        //Write for each task name all the iteration
        json task = json::object();
        task["name"] = m_names[taskNameIdx];

        for (int iterationIdx = 0; iterationIdx < m_numberOfIterations; iterationIdx++)
        {
            task["iteration_" + to_string(iterationIdx)] = (*m_cpuEndTimes)[taskNameIdx][iterationIdx];
        }
        party.insert(party.begin(), task);
    }

    //send json object to create file
    createJsonFile(party, fileName);
}


void Measurement::createJsonFile(json j, string fileName)
{
    try
    {
        ifstream myfile;
        myfile.open(fileName, ifstream::out);
        cout << j << endl;
        if (myfile.is_open())
        {
            myfile >> j;
        }
    }

    catch (exception& e)
    {
        cout << "Exception thrown : " << e.what() << endl;
    }
}
```

- What is the expected behavior?
Create json file

- And what is the actual behavior instead?
I got this error: `[json.exception.parse_error.101] parse error at 1: syntax error - unexpected end of input; expected '[', '{', or a literal`

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?
I'm using GCC 5.4, Ubuntu 16.04.3 LTS

- Did you use a released version of the library or the version from the `develop` branch?
I used the latest release 3.0.1

**Comment by nlohmann** [comment]
In your `createJsonFile` function, `myfile >> j` means "parse file `myfile` into JSON value `j`". I don't think this is what you want to do, and this could explain the error.

**Comment by liorbiu** [comment]
yes you are right, this is no what I wanted.
How do I right this json object to a file? When I'm printing it using `cout` everything is fine.

**Comment by nlohmann** [comment]
```cpp
std::ofstream o("myoutfile.json");
o << j;
```

See https://github.com/nlohmann/json#tofrom-streams-eg-files-string-streams for examples.

**Comment by liorbiu** [comment]
Thank you very much, It helped me. I will look at the attached link.
