### ISSUE TITLE
Installation path is incorrect

### ISSUE THREAD

**Issue by InFaMoUsZero** [nlohmann/json#910]
Calling "make install" now installs json.hpp to "nlohmann/src/json.hpp".

No sure if this was intentional.

The issue is from the latest PR change [here](https://github.com/nlohmann/json/blob/b67e00b9b56a344bfdb3ce92bf1f6724db518c95/CMakeLists.txt#L24).

**Comment by nlohmann** [comment]
I am not CMake expert - what should be the value in your opinion?

**Comment by theodelrieu** [comment]
Oops I haven't tried that, I'll take a look this afternoon

**Comment by nlohmann** [comment]
Fixed with merging #911.

@InFaMoUsZero Could you please check if this fixes the issue for you?

**Comment by InFaMoUsZero** [comment]
@nlohmann Sure, I can test this on Tuesday and hopefully get this closed off.

**Comment by InFaMoUsZero** [comment]
@nlohmann I can confirm this has now fixed the issue.

**Comment by nlohmann** [comment]
Thanks for checking back!
