### ISSUE TITLE
Read key1 from .value example

### ISSUE THREAD

**Issue by Diablillowilly** [nlohmann/json#914]
I was trying to use the library to read and parse a json post which I receive, so I just want to read each value, but , I dont know how to read a value inside an object. In this [example](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_adcf8ca5079f5db993820bf50036bf45d.html#adcf8ca5079f5db993820bf50036bf45d) I would like to access the value of key1 or key2, I have tryed things like  object.key1 or object:key1, but none of them worked.

**Comment by nlohmann** [comment]
Assume you read this JSON value:

```js
{
  "key1": true,
  "key2": 2
}
```

Then you can access the values with:

```cpp
bool k1 = j["key1"];
int k2 = j["key2"];
```

(assuming you parsed your JSON value to `json j`).

If you need more information, please provide some example code, the error you experience and your expected behavior.

**Comment by Diablillowilly** [comment]
I get a json in a string from a http post

`std::string input=
    "{
       
        {\"str\", \"helloworld\"},
        {\"int\", 24},
        {\"object\", {{\"key1\", 1}, {\"key2\", 2}, {\"subobject\",{\"subkey1\", 1}, {\"subkey2\", 2}}}},
    }";`
and after that I parse them like this so I get rid of the '\':
` nlohmann::json j = nlohmann::json::parse(input);`

and I am reading values at the same level as str or int by making:
 ```
 std::string str = j.value("str", "");
  int str = j.value("int", 0);
```
but what do I have to do If I want to rad key1/2 or subkey1/2?

**Comment by nlohmann** [comment]
- Right now, `value` does not support nesting. That is, you can only apply it to an object to retrieve a primitive value.
- `j["key"]` adds key `"key"` if it does not exist and stores `null`. If `j` is const, the behavior is undefined for nonexisting keys.
- `j.at("key")` throws an exception if key `"key"` does not exist and will not change the object.

**Comment by cronnosli** [comment]
_"but what do I have to do If I want to read key1/2 or subkey1/2?"_

If you want to read a subkey you could access the json object as it is like a multilevel array:

```c++
int value = j["object"]["subobject"][subkey1].get<int>();
```

Or by walk throw in a STL manner:
```c++
for (json::iterator it = j["object"].begin(); it != j["object"].end(); ++it) {
  std::cout << it.key() << " : " << it.value() << "\n";
}
```
But with a loop you would need to interact each subobject in a nested loop!

**Comment by pingsoli** [comment]
@nlohmann I'm very sorry to disturb you. If a value is string, the double quote can be remove ?
I want to write more elegant code, so I do it like this:
```
json account;
account["id"]              = "1234567890";
account["name"]        = "pingsoli";
account["age"]           = 18; 
account["registered"] = true;

std::ostringstream oss;
for (json::iterator it = account.begin(); it != account.end(); ++it)
{
  oss << "&" << it.key() << "=" << it.value();
}
std::cout << oss.str() << std::endl;
```
I got the output like this:
```
&age=18&id="1234567890"&name="pingsoli"&registered=true
```
BUT, I want the result like following code(removing the double quote, it looks like query options):
```
&age=18&id=1234567890&name=pingsoli&registered=true
```
What should I do ? Checking the type, if it is string, I remove the double quote, if not, do nothing ? Thank you again, I really want to get your help or some advise.

**Comment by Diablillowilly** [comment]
I have finally made it like this:

`if (!j["object"]["subobject"]["subkey"].is_null()) {
    return j["object"]["subobject"]["subkey"];
 }`

So I check if it exists, and then I read it. Thank you very much for your help
