### ISSUE TITLE
json_fwd.hpp not installed

### ISSUE THREAD

**Issue by zerodefect** [nlohmann/json#923]
**Bug Report**

- What is the issue you have?

Not sure if this is by design or not, but I notice that when I perform 'cmake install', the json_fwd.hpp is not installed. 

- What is the expected behavior?

Well, if I want to perform an in-source build (ExternalProject_Add()), as an example, it makes things difficult if their is no install procedure for the fwd declaration.

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

Ubuntu 17.10 and GCC v7.2

- Did you use a released version of the library or the version from the `develop` branch?

Released

**Comment by theodelrieu** [comment]
The default install method only installs the amalgamated `json.hpp`, you have to set the CMake option `-DJSON_MultipleHeaders=ON`.

**Comment by gregmarr** [comment]
I think installing the fwd header in the default install would make sense. Lots of people want forward declarations but don't need the rest of the individual headers.

**Comment by zerodefect** [comment]
@gregmarr I agree actually. Nonetheless, I feel that is a separate issue (imho).

**Comment by theodelrieu** [comment]
I personally want to include only `adl_serializer.hpp` in my code, for this I need every header installed.

That's why I think adding another target to install the amalgamated version + json_fwd is superfluous.

Users can still only include `json.hpp` as before, I'm not sure having every header or not is a big issue.
