### ISSUE TITLE
GCC 7.x issue

### ISSUE THREAD

**Issue by sander-visser** [nlohmann/json#926]
**Bug Report**

- What is the issue you have?
Gcc 7.x complains about json.hpp row ~1581:

        // assertion to check that the iterator range is indeed contiguous,
        // see http://stackoverflow.com/a/35008842/266378 for more discussion
        assert(std::accumulate(
                   first, last, std::pair<bool, int>(true, 0),
                   [&first](std::pair<bool, int> res, decltype(*first) val)
        {

with error "lamda-expression in unevaluated context"

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?
just include header in hello world application built using gcc 7.3

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?
looks to be the same on master

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Feature Request**

- Describe the feature in as much detail as possible.

- Include sample usage where appropriate.

**Comment by nlohmann** [comment]
We could wrap this line in a `#ifndef NDEBUG` macro - @sander-visser could you try if this silences the warning?

**Comment by theodelrieu** [comment]
Is it the same issue as #705?

**Comment by sander-visser** [comment]
`#ifndef` wrap allows build to complete.  AS i want runtime assertions and since im building using Yocto I guess the proper solution for me would be to cherry pick http://git.yoctoproject.org/cgit.cgi/poky/commit/?id=1bd447bc606603a32a8ff75708bf377bcd82de2d ahead of it being included in yocto rocko. You may close this issue as duplicate/invalid.

**Comment by nlohmann** [comment]
Duplicate, see #705.
