### ISSUE TITLE
use in visual studio 2015

### ISSUE THREAD

**Issue by jelofen** [nlohmann/json#929]
Hello 
- I am a beginner in c++ could anyone please give me an instruction of how to use this in visual studio 2015 step by step?
by including the hpp file I got error

I need to know how to install this project to use it in VS15, and since I am a beginner please be  patiente with me and tell me the tools, the paths, and way to install this package. I installed my visual studio in default path. 
thank you

**Comment by nlohmann** [comment]
What is the error message?

**Comment by tdeb-incise** [comment]
I am getting this errors : 

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2338	forcing MSVC stacktrace to show which T we're talking about.	facedetectionapp	d:\workspace\facedetectionapp\facedetectionapp\facedetectionapp\json.hpp	1525	
Error	C2338	could not find to_json() method in T's namespace	facedetectionapp	d:\workspace\facedetectionapp\facedetectionapp\facedetectionapp\json.hpp	1519	
Error	C2039	'force_msvc_stacktrace': is not a member of 'papillon::PDateTime'	facedetectionapp	d:\workspace\facedetectionapp\facedetectionapp\facedetectionapp\json.hpp	1524	
Error	C2065	'force_msvc_stacktrace': undeclared identifier	facedetectionapp	d:\workspace\facedetectionapp\facedetectionapp\facedetectionapp\json.hpp	1524

**Comment by nlohmann** [comment]
You probably try to assign some object to a `nlohmann::json` value and the library does does not find a `to_json` function for this conversion.

Example:

```cpp
MyObjectType foo;
nlohmann::json j = foo; // this line would generate the error like above
```

See https://github.com/nlohmann/json#arbitrary-types-conversions for more information on how to provide a `to_json` function.
