### ISSUE TITLE
Equality operator fails

### ISSUE THREAD

**Issue by axx** [nlohmann/json#931]
**Bug Report**

- What is the issue you have?
The equality operator returns false even though 2 JSON objects have the same content, just different order.

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

#include < iostream >
#include "json.hpp"

int main(int argc, char** argv)
{
  auto j1 = R"#(
{
"alertResponses": [
{"profileId": "CEMAV1",
"errors": [{"code": 1666, "title": "Not Allowed"}]
},
{"profileId": "CEMAV2",
"errors": [{"code": 1666, "title": "Not Allowed"}]
}]
}
)#"_json;

  auto j2 = R"#(
{
"alertResponses": [
{"profileId": "CEMAV2",
"errors": [{"code": 1666, "title": "Not Allowed"}]
},
{"profileId": "CEMAV1",
"errors": [{"code": 1666, "title": "Not Allowed"}]
}]
}
)#"_json;

  if (j1 == j2) std::cout << "The same!" << std::endl;
  else std::cout << "Not the same!" << std::endl;

  return 0;
}

- What is the expected behavior?

"The same!" should be printed out.

- And what is the actual behavior instead?

"Not the same!" is printed out.

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

g++ 4.9.3 on SUSE Linux
g++ Apple LLVM version 9.0.0 (clang-900.0.39.2) on Mac OS X

- Did you use a released version of the library or the version from the `develop` branch?

It's from the "develop" branch version 2.1.1.
Same problem is found in version 3.0.1

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

No compilation error

**Feature Request**

- Describe the feature in as much detail as possible.

- Include sample usage where appropriate.

**Comment by gregmarr** [comment]
I would expect two arrays having different orders to result in the JSON being different.  Objects have unordered keys, but arrays are ordered.  Why would you expect them to be the same?

**Comment by gregmarr** [comment]
www.json.org
>JSON is built on two structures:
>
>A collection of name/value pairs. In various languages, this is realized as an object, record, struct, dictionary, hash table, keyed list, or associative array.
>An ordered list of values. In most languages, this is realized as an array, vector, list, or sequence.

**Comment by gregmarr** [comment]
These two would be the same, for example:

    int main(int argc, char** argv)
    {
        auto j1 = R"#({
            "alertResponses": {
                "CEMAV1": [{"code": 1666, "title": "Not Allowed"}],
                "CEMAV2": [{"code": 1666, "title": "Not Allowed"}]
            }
        })#"_json;

        auto j2 = R"#({
            "alertResponses": {
                "CEMAV2": [{"code": 1666, "title": "Not Allowed"}],
                "CEMAV1": [{"code": 1666, "title": "Not Allowed"}]
            }
        })#"_json;

**Comment by axx** [comment]
OK, fair enough. I missed the part about the ordered list.  Thanks for the clarification.
