### ISSUE TITLE
Change header include directory to nlohmann/json

### ISSUE THREAD

**Issue by patrikhuber** [nlohmann/json#942]
Hi!

The [readme](https://github.com/nlohmann/json#integration) advises to include the header with `#include "json.hpp"`. If we add this repo as a git submodule, we would add the `src/` directory of this repo to the include path, and also do `#include "json.hpp"`. However, if one runs the CMake INSTALL target of this repo, or uses it via e.g. [vcpkg](https://github.com/Microsoft/vcpkg/blob/master/ports/nlohmann-json/portfile.cmake), the header gets copied to the location `nlohmann/json.hpp` and should now be included as `#include "nlohmann/json.hpp"`.
I think it would be better (and best practice) to put the header in the repo into a directory `include/nlohmann/`. Most header-only libraries that I know of do this. This would unify the `#include`: We could just use `#include "nlohmann/json.hpp`, no matter whether we're including via git submodule, CMake INSTALL target, vcpkg, etc. Another plus is that it sort-of "namespaces" the header, i.e. a clash with a potential other `json.hpp` file in any of the compiler's include directories is avoided (not unlikely, as `json.hpp` is quite a generic name).

**Comment by nlohmann** [comment]
I am afraid that changing the path of the single header from `src/json.hpp` to anything else would also break existing systems.

**Comment by nlohmann** [comment]
Ok. This will be fixed with #944.

**Comment by patrikhuber** [comment]
Great to see this awesome discussion on that matter! The PR will make me very happy as well ;-) 👍

**Comment by nlohmann** [comment]
Fixed with #944.
