### ISSUE TITLE
Please expose a NLOHMANN_JSON_VERSION macro

### ISSUE THREAD

**Issue by ringerc** [nlohmann/json#943]
Hi folks

It'd be very handy if the library exposed a NLOHMANN_JSON_VERSION macro for easy version detection in configure scripts, cmake files, etc. Especially since the fancy formatting in the comment header makes text extraction harder.

**Comment by nlohmann** [comment]
Would the [`meta` function](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_aef6d0eeccee7c5c7e1317c2ea1607fab.html#aef6d0eeccee7c5c7e1317c2ea1607fab) help your use case?

**Comment by ringerc** [comment]
@nlohmann Yeah, that'd probably do. I never would've thought to look for it there. But a configure test / CMake `Find` module etc could compile a trivial program to print the version based on that, assuming it's not cross-compiling.

For now I landed up with a hideous regexp based hack to match the version from the comment header.

**Comment by nlohmann** [comment]
@ringerc Is e8bf1f62f76e1393f741ecf690d4b52c403f17b4 satisfying your needs?

**Comment by ringerc** [comment]
That's handy, thanks very much. It's considerably easier to pluck out some
constants when probing for versions etc.​
