### ISSUE TITLE
VERSION define(s)

### ISSUE THREAD

**Issue by mark-99** [nlohmann/json#948]
It would be useful if there was a #define for the version of the package. This would make it easier to transition client code across breaking changes, e.g. the 3.x changes to operator<< and exception types.

Just something like
`#define NLOHMANN_JSON_VERSION   30102   // v3.1.2`

Some people prefer to use hex, and some split into separate VERSION_MAJOR/MINOR/PATCH, whatever you want.

**Comment by nlohmann** [comment]
Related: #943

**Comment by mark-99** [comment]
Ah didn't see that.
However meta() is not useful here, you need to conditionally compile via #ifdef which can't be done with a runtime var.

**Comment by nlohmann** [comment]
I understand, and it is the second time within 3 days that someone is asking for this. I'll have a look.

**Comment by mark-99** [comment]
To illustrate, e.g.:
```
#if NLOHMANN_JSON_VERSION >= 30000
catch (const json::parse_error& ex)
#else
catch (const std::invalid_input& ex)
#endif
{ /*etc*/ }
```

**Comment by nlohmann** [comment]
@mark-99 Is e8bf1f62f76e1393f741ecf690d4b52c403f17b4 satisfying your needs?

**Comment by mark-99** [comment]
Looks good.
