### ISSUE TITLE
I have a proposal

### ISSUE THREAD

**Issue by daoqiang** [nlohmann/json#949]
The serialization part of this library should be dependent on boost:: serialization. I'm using boost and your JSON library at the same time. Are there any interests to be compatible?

Because if my custom type needs to be serialized to JSON and others at the same time. I need to write three additional functions, to_json from_json, serialize., to_json and from_json, which should be similar to serialize's load and save. They belong to the custom type attribute registration.

So I mean, this library depends on boost:: serialization, why don't do a compatible property registration method
Or to do a serialize wrapper, just write this wrapper function to realize the serialization on the boost

thank you

**Comment by daoqiang** [comment]
I'm sorry, it doesn't seem to be using serializtion

**Comment by nlohmann** [comment]
Right, the library is independent of Boost.
