### ISSUE TITLE
Coveralls shows no coverage data

### ISSUE THREAD

**Issue by nlohmann** [nlohmann/json#953]
Since the split into the new subdirectories, Coveralls displays no coverage data, see https://coveralls.io/github/nlohmann/json. I tried to fix the `.travis.yml` file, but probably overlooked something.

**Comment by theodelrieu** [comment]
Weird, I remember battling against coveralls in #700 and making it work.

Could you try to set `--include include`?

I think it's because in my PR, `src` was containing split headers, and there was a `single_include` folder, that has been renamed to `src` after the merge.

**Comment by nlohmann** [comment]
But the tests are compiled using the header from the `single_header` directory.

**Comment by nlohmann** [comment]
And I think it is more handy to have the coverage for the single header file, because this is the main artifact of the repository.

**Comment by theodelrieu** [comment]
But having it on the `include` folder is way better to know where the not covered code is. When I had to open `json.hpp` in coveralls it froze my browser so I'd go for multiple headers all day everyday.

Is there a Travis job that runs `make check-amalgamation`? If that's the case, I think there is no need to run coveralls on the single header

**Comment by nlohmann** [comment]
Yes, there is a job calling `make check-amalgamation`, so we can actually let Coveralls work on the multiple-headers version.

**Comment by nlohmann** [comment]
Coverage data are now shown for the single-header version. I am fine with this and would close this issue. For coverage of the multi-header version, there is the `make coverage` target which uses lcov locally.

To extend Travis/Coveralls to use the multi-header version, we need way to call cmake with `-DJSON_Coverage=ON` **and** `-DJSON_MultipleHeaders=ON` - so far I only managed to pass one flag via environment variable `CMAKE_OPTIONS` to the call to cmake in the `script` passage.
