### ISSUE TITLE
Split headers should be part of the release

### ISSUE THREAD

**Issue by theodelrieu** [nlohmann/json#956]
Currently, only the amalgamated `json.hpp` file and the entire repository source code (over 100MB) are available in the Releases tab.

It would help a lot to add a zip archive containing the `include` directory as well, especially for package managers which have to fully clone the repository if not installing the amalgamated version.

**Comment by nlohmann** [comment]
I agree.

**Comment by pboettch** [comment]
I like the idea of @astoeckel, having a read-only-header-file-release-repo. I'd use that as a sub-module. https://github.com/nlohmann/json/issues/96#issuecomment-362882567

**Comment by nlohmann** [comment]
Let's see if this works better than https://github.com/nlohmann/json/issues/96#issuecomment-313372948 :)

**Comment by nlohmann** [comment]
Fixed:

<img width="769" alt="release" src="https://user-images.githubusercontent.com/159488/35777510-47e2d4cc-09af-11e8-97e7-5772aee16066.png">

**Comment by pboettch** [comment]
Yeah, in the long run it would be safer if you'd semi-automatically maintain such a repo I guess.

**Comment by theodelrieu** [comment]
Great! Could you add the SHA-256 for the `include.zip` as well?
