### ISSUE TITLE
With non-unique keys, later stored entries are not taken into account anymore

### ISSUE THREAD

**Issue by jeremysingy** [nlohmann/json#963]
While updating to 3.1.0, I noticed that the behavior of the library is not consistent with the [documentation](http://nlohmann.github.io/json/classnlohmann_1_1basic__json_a5e48a7893520e1314bf0c9723e26ea2a.html#a5e48a7893520e1314bf0c9723e26ea2a) anymore for objects with non-unique names (also discussed in issue #375).

> When the names within an object are not unique, **later stored name/value pairs overwrite previously stored name/value pairs**, leaving the used names unique. For instance, {"key": 1} and {"key": 2, "key": 1} will be treated as equal and both stored as {"key": 1}.

Whereas  it will now be treated equally as `{"key": 2}` instead.

I bissected to the commit 85c76808 replacing `operator[]` with `emplace` to insert an object, which will not update an already existing object in the `map`.

I actually don't need this "feature" anymore, so not sure if it's best to fix the code for consistency or update the corresponding documentation.

**Comment by gregmarr** [comment]
I'm wondering if that behavior should be left unspecified:

> When the names within an object are not unique, it is unspecified which one of the values for a given key will be chosen. For instance, {"key": 2, "key": 1} could be equal to either {"key": 1} or {"key": 2}.

**Comment by nlohmann** [comment]
I agree - this is more a documentation issue: we over-specified the library's behavior before. I shall change the documentation as @gregmarr proposes.
