### ISSUE TITLE
Json and fmt::lib's format_arg()

### ISSUE THREAD

**Issue by AlexandreBossard** [nlohmann/json#964]
**Bug Report**

[jsonbug.zip](https://github.com/nlohmann/json/files/1707716/jsonbug.zip)

I use the glorious [fmt::lib](https://github.com/fmtlib/fmt) for my project. Since i got bored of typing code
like ```fmt::print("my json {}", jsonvar.dump(2));```, i set myself to use the fmt customization point for user-defined type.

Normally, fmtlib trigger static_assert when unrecognized type are passed as arguments, asking you to defined ``format_arg()`` or an ``ostream<<`` overload.

Not with nhlomann::json. I get some horrible error messages with gcc (7.2.0) with an ambiguous call to a constructor of some fmtlib internals.

By digging fmt code, i found a macro which disabled implicit int conversion. Shooting in the dark, copy paste the macro, and passing nhlomann::json to it. Fixed!

I am not sure if this is a the fmtlib or json fault (both?). But looking for related issues in both project, i found this one #958, which kind of help me.

**Comment by theodelrieu** [comment]
After hacking the library a bit with Alex we found that removing the `operator T` fixed the issue (We also had to replace every instance of `std::is_convertible` with `std::is_constructible` inside `conversions/from_json.hpp`).

Luckily we can workaround the problem as Alex said with the **internal** fmt macro, while waiting for the next major json version (if we decide to remove `operator T()`)

**Comment by nlohmann** [comment]
I'm not convinced that removing `operator T()` would be a good idea, but let's discuss this in #958. However, adding a macro to our library to switch it off would be a first step.

**Comment by nlohmann** [comment]
Can this be closed as the error can be fixed by defining a macro in fmtlib?

**Comment by AlexandreBossard** [comment]
I can not call that a fix, since you have to used an undocumented API from fmtlib. The real bug is that json somehow short circuit the fmt's static_assert. replacing the cute and informative message about customization point by compiler errors barf. I was lucky to find the workaround with the fmtlib. But I suspect someone would come across the same issue with different lib and not be so "fortunate".

**Comment by nlohmann** [comment]
If the only fix is #958, then this issue will not be fixed for a while (if ever). :-(

**Comment by nlohmann** [comment]
Closing this for now.

**Comment by tesch1** [comment]
@AlexandreBossard what was this glorious macro that disabled the implicit int conversion?!?  is it still in fmt?  I dont see it.
