### ISSUE TITLE
reverse order of serialization 

### ISSUE THREAD

**Issue by CDitzel** [nlohmann/json#979]
why is the snippet 

`json j;
  j["pi"] = 3.141;
  j["happy"] = true;
  std::ofstream ofs{ "test.json" };
  ofs << j << std::endl;`

rsulting in an output like the following

{
    "happy": true,
    "pi": 3.141
}

it should be the other way around should it not? What am I missing here?

**Comment by nlohmann** [comment]
See last entry in the notes section: https://github.com/nlohmann/json#notes
