### ISSUE TITLE
Problem with adding the lib as a submodule

### ISSUE THREAD

**Issue by CDitzel** [nlohmann/json#983]
I am trying to use your lib as a submodule in my CMake Project in an externalLibs directory that I call via add_subdirectory(json). CMake runs through, but when I try to compile I get a whole lot of errors along the following lines

~/project/extLibs/json/test/src/unit-json_patch.cpp:65:12: warning: missing terminating " character
             CHECK(doc1.patch(patch) == R"(
            ^
~/project/extLibs/json/test/src/unit-json_patch.cpp:65:12: error: missing terminating " character
             CHECK(doc1.patch(patch) == R"(
            ^~~~~~~~~~~~~~~~~~~~~~~~~~
~/project/extLibs/json/test/src/unit-json_patch.cpp:67:21: error: stray ‘\’ in program
                     "a": {

I cant seem to find the reason for that; i use gcc-7.2 

help is deeply appreciated

**Comment by nlohmann** [comment]
Can you make sure you are using C++11?

**Comment by CDitzel** [comment]
I am sure, I am using some C++17 features and have 

ADD_DEFINITIONS(
    -std=c++1z
)

in my root CMakeLists.txt file

**Comment by CDitzel** [comment]
all right, it seems to work now. Apparently ccache was the culprit
I used 

`find_program(CCACHE_PROGRAM ccache)
if(CCACHE_PROGRAM)
    message(STATUS ${ColourYellow} "-> Launching compiler through ccache and caching compilation outputs" ${ColourReset})
    set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE "${CCACHE_PROGRAM}")
endif()
`

in my root CMakeLists.txt file and for reasons I dont yet fully understand that caused the compilation errors

**Comment by nlohmann** [comment]
Thanks for reporting back!
