### ISSUE TITLE
number parsing

### ISSUE THREAD

**Issue by Yaossg** [nlohmann/json#993]
**Bug Report**

number literals like `"+1"_json` , `".5"_json` , `"5."_json` are invalid

**Feature Request**

hexadecimal floating literal (like`0x1.2p3`)

**Comment by nlohmann** [comment]
All these numbers are non-confirming JSON, see

![numbers](http://json.org/number.gif)

**Comment by nlohmann** [comment]
We shall not add features that do not conform to JSON.
