### ISSUE TITLE
Prevent Null values to appear in .dump()

### ISSUE THREAD

**Issue by nuno407** [nlohmann/json#995]
Imagine that you have the following json string created by .dump()

`
{"connectorId":0,
"meterValue": [{"sampledValue":[{"context":"Sample.Periodic","format":null,"location":"Body","measurand":null,"phase":"L1","unit":"V","value":"18440"},{"context":"Sample.Periodic","format":null,"location":"Body","measurand":null,"phase":"L2","unit":"V","value":"46927"},{"context":"Sample.Periodic","format":null,"location":"Body","measurand":null,"phase":"L3","unit":"V","value":"44515"}]
`

How can I configure the library to not include null values in the dump? I research in the documentation by with no success. The only way I can find is to create a For loop that removes all null entries but is quite inefficient.

Thank you for the help,
Nuno

**Comment by nlohmann** [comment]
No, this is currently not possible.

If the value is coming from an external JSON file, then you could add a callback to the parser which removes the `null` entries.

**Comment by nlohmann** [comment]
See https://nlohmann.github.io/json/classnlohmann_1_1basic__json_ab4f78c5f9fd25172eeec84482e03f5b7.html#ab4f78c5f9fd25172eeec84482e03f5b7 for an overview and https://nlohmann.github.io/json/classnlohmann_1_1basic__json_aa9676414f2e36383c4b181fe856aa3c0.html#aa9676414f2e36383c4b181fe856aa3c0 for an example.

**Comment by nuno407** [comment]
Solution:

```
std::string a = jsonprop.dump();
jsonprop = nlohmann::json::parse(a, RemoveNullCallBack);

nlohmann::json::parser_callback_t RemoveNullCallBack = [](int depth, nlohmann::json::parse_event_t event, nlohmann::json & parsed){
	 if (event == nlohmann::json::parse_event_t::value and parsed == nullptr)
	 {
		 return false;
	 }
	 else
	 {
		 return true;
	 }
 };
```
Not optimal but works for now.
Thank you.

**Comment by nlohmann** [comment]
Thanks for checking back!

If your workflow is to first parse and then dump, then I think this is the best you can get, because you filter right during parsing and never need to take care about `null` again later.

**Comment by albertborges** [comment]
static void recurseAndFilterNullValues(nlohmann::json & jsonObject) {
	if (!jsonObject.is_object() && !jsonObject.is_array()) {
        return;
    }

    std::vector<nlohmann::json::object_t::key_type> keysToRemove;
    for (auto &it : jsonObject.items()) {
        if (it.value().is_null())
        {
            keysToRemove.push_back(it.key());
            continue;
        }
        
        recurseAndFilterNullValues(it.value());
    }

    for (auto key : keysToRemove)
    {
        jsonObject.erase(key);
    }
}

**Comment by albertborges** [comment]
```
static void recurseAndFilterNullValues(nlohmann::json & jsonObject) {
	if (!jsonObject.is_object() && !jsonObject.is_array()) {
        return;
    }

    std::vector<nlohmann::json::object_t::key_type> keysToRemove;
    for (auto &it : jsonObject.items()) {
        if (it.value().is_null())
        {
            keysToRemove.push_back(it.key());
            continue;
        }
        
        recurseAndFilterNullValues(it.value());
    }

    for (auto key : keysToRemove)
    {
        jsonObject.erase(key);
    }
}
```

**Comment by albertborges** [comment]
@nlohmann FYI. Had to clean null values recently and found nothing online. A simple DFS did the trick.

**Comment by deleeuwict** [comment]
> ```
> static void recurseAndFilterNullValues(nlohmann::json & jsonObject) {
>     if (!jsonObject.is_object() && !jsonObject.is_array()) {
>         return;
>     }
> 
>     std::vector<nlohmann::json::object_t::key_type> keysToRemove;
>     for (auto &it : jsonObject.items()) {
>         if (it.value().is_null())
>         {
>             keysToRemove.push_back(it.key());
>             continue;
>         }
>         
>         recurseAndFilterNullValues(it.value());
>     }
> 
>     for (auto key : keysToRemove)
>     {
>         jsonObject.erase(key);
>     }
> }
> ```

This code didnt work for array indexes, solution:

```
void RecurseAndFilterNullValues(nlohmann::json& jsonObject) 
{
	if (!jsonObject.is_object() && !jsonObject.is_array()) {
		return;
	}

	std::vector<nlohmann::json::object_t::key_type> keysToRemove;
	for (auto& it : jsonObject.items()) {
		if (it.value().is_null())
		{
			keysToRemove.push_back(it.key());
			continue;
		}

		RecurseAndFilterNullValues(it.value());
	}

	for (auto const& key : keysToRemove)
	{
		if (jsonObject.is_object())
		{
			jsonObject.erase(key);
		}
		else
		{
			assert(jsonObject.is_array());
			jsonObject.erase(static_cast<size_t>(std::stoi(key)));
			//other indexes are now invalid
			return RecurseAndFilterNullValues(jsonObject);
		}
	}
}
```
