### ISSUE TITLE
Enable forward declaration of json by making json a class instead of a using declaration

### ISSUE THREAD

**Issue by pgoodman** [nlohmann/json#997]
I would like to be able to be able to declare the conversion operators in a header without having to `#include` the json.h file. I would then define the conversion operators in a source file, which actually includes json.h.

Here is an example of what I want do do, but can't:

```c++
namespace nlohmann {
class json;
void to_json(json &j, const MyType &blah);
void from_json(const json &j, MyType &blah);
}  // namespace nlohmann
```

What is stopping me is `using json = basic_json<>;`. A simple fix should be `class json : public basic_json<> {};`.

**Comment by theodelrieu** [comment]
Making this change would break everything, but since version `3.1.0` you can use the multiple header version, to include the `nlohmann/json_fwd.hpp`, which does what you want :)

**Comment by nlohmann** [comment]
@pgoodman Did you have the chance to test whether `include/nlohmann/json_fwd.hpp` helps?

**Comment by pgoodman** [comment]
I didn't test the multiple header approach because I wanted to put the single header version into my project at `third_party/JSON/json.h`, rather than duplicate the `nlohmann` directory structure. I might change this in the future, though.

**Comment by gregmarr** [comment]
I would think that you could put both the single file and the fwd file in your project.

**Comment by pgoodman** [comment]
this had not occurred to me ;-)

**Comment by pgoodman** [comment]
That didn't work for me.

**Comment by theodelrieu** [comment]
Did you include `json_fwd.hpp`?

**Comment by nlohmann** [comment]
@pgoodman Could you provide more information like a small example program or the concrete error message?

**Comment by pasbi** [comment]
copying both ` json/include/nlohmann/json_fwd.hpp` and ` json/single_include/nlohmann/json.hpp
` into my `src/json/` directory enables me to use `#include "json/json_fwd.hpp"` whenever I need the declarations and `#include "json/json.hpp"` whenever definitions are required.
