### ISSUE TITLE
Range-based iteration over a non-array object

### ISSUE THREAD

**Issue by dvhwgumby** [nlohmann/json#998]
It is possible or planned to be able to use a range-based for loop to iterate over a non-array object?

That is, you can do:

    for (auto& element : j) 
      std::cout << element << std::endl;

for an array ```[ "a", "b" ]``` but not for ```{"foo": "bar", "quux":"baaz"}``` (well, range-based iteration works if you don't care about the key)

The json package compiles and works just fine under C++17, so I would like to be able to do:

    for (auto& [key, value] : j)
      std::cout << key << " : " << value << std::endl;

I am sure there are more important feature requests (e.g. SAX read & write) but I thought I would submit this one anyway.  This package is great!  Thanks, d

**Comment by nlohmann** [comment]
You can do this with the [`items()`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_afe3e137ace692efa08590d8df40f58dd.html#afe3e137ace692efa08590d8df40f58dd) function.

For structured bindings, see #901.

**Comment by dvhwgumby** [comment]
Thanks

**Comment by nlohmann** [comment]
FYI: Structured binding support has recently been merged (#1391) and will be part of the next release.
